/* ============================================================
   LangLab — MỤC TỪ CHO TỪNG CHỮ HÁN (单字)
   ------------------------------------------------------------
   Trong bài đọc, mỗi chữ Hán đều bấm được. Giáo trình chỉ dạy TỪ
   (两 chữ trở lên) nên bấm vào một chữ lẻ thường ra rỗng. Tệp này
   bù các chữ lẻ có mặt trong 50 bài đọc tiếng Trung.

   Do LangLab tự biên soạn. Chữ nào đã là mục từ sẽ được khử trùng
   lặp khi gộp vào ZH_LOOKUP (xem js/app.js).

   Trường dữ liệu:  zh · pinyin · hv (âm Hán–Việt) · vi · pos
   ============================================================ */

const CHARS_ZH = [

  /* ---------- Họ · tên riêng ---------- */
  {zh:'阮', pinyin:'Ruǎn', hv:'Nguyễn', vi:'họ Nguyễn', pos:'chữ Hán'},
  {zh:'李', pinyin:'Lǐ', hv:'Lý', vi:'họ Lý; quả mận', pos:'chữ Hán'},
  {zh:'王', pinyin:'Wáng', hv:'Vương', vi:'họ Vương; vua', pos:'chữ Hán'},
  {zh:'林', pinyin:'lín', hv:'lâm', vi:'rừng; họ Lâm', pos:'chữ Hán'},
  {zh:'北', pinyin:'běi', hv:'bắc', vi:'phía bắc', pos:'chữ Hán'},
  {zh:'京', pinyin:'jīng', hv:'kinh', vi:'kinh đô', pos:'chữ Hán'},
  {zh:'西', pinyin:'xī', hv:'tây', vi:'phía tây', pos:'chữ Hán'},
  {zh:'安', pinyin:'ān', hv:'an', vi:'yên ổn, bình an', pos:'chữ Hán'},
  {zh:'南', pinyin:'nán', hv:'nam', vi:'phía nam', pos:'chữ Hán'},
  {zh:'东', pinyin:'dōng', hv:'đông', vi:'phía đông', pos:'chữ Hán'},

  /* ---------- Học hành ---------- */
  {zh:'学', pinyin:'xué', hv:'học', vi:'học', pos:'chữ Hán'},
  {zh:'习', pinyin:'xí', hv:'tập', vi:'luyện tập', pos:'chữ Hán'},
  {zh:'汉', pinyin:'hàn', hv:'hán', vi:'người Hán, chữ Hán', pos:'chữ Hán'},
  {zh:'语', pinyin:'yǔ', hv:'ngữ', vi:'ngôn ngữ, tiếng', pos:'chữ Hán'},
  {zh:'词', pinyin:'cí', hv:'từ', vi:'từ (ngôn ngữ)', pos:'chữ Hán'},
  {zh:'字', pinyin:'zì', hv:'tự', vi:'chữ', pos:'chữ Hán'},
  {zh:'典', pinyin:'diǎn', hv:'điển', vi:'sách chuẩn mực (từ điển)', pos:'chữ Hán'},
  {zh:'校', pinyin:'xiào', hv:'hiệu', vi:'trường học', pos:'chữ Hán'},
  {zh:'师', pinyin:'shī', hv:'sư', vi:'thầy, người dạy', pos:'chữ Hán'},
  {zh:'生', pinyin:'shēng', hv:'sinh', vi:'sinh ra, sống; học sinh', pos:'chữ Hán'},
  {zh:'考', pinyin:'kǎo', hv:'khảo', vi:'thi, kiểm tra', pos:'chữ Hán'},
  {zh:'复', pinyin:'fù', hv:'phục', vi:'lặp lại, ôn lại', pos:'chữ Hán'},
  {zh:'解', pinyin:'jiě', hv:'giải', vi:'cởi ra, giải thích', pos:'chữ Hán'},
  {zh:'释', pinyin:'shì', hv:'thích', vi:'giải nghĩa, buông ra', pos:'chữ Hán'},
  {zh:'记', pinyin:'jì', hv:'ký', vi:'ghi, nhớ', pos:'chữ Hán'},
  {zh:'首', pinyin:'shǒu', hv:'thủ', vi:'đầu; đứng đầu (bộ thủ)', pos:'chữ Hán'},
  {zh:'系', pinyin:'xì', hv:'hệ', vi:'hệ thống, liên hệ', pos:'chữ Hán'},
  {zh:'知', pinyin:'zhī', hv:'tri', vi:'biết', pos:'chữ Hán'},
  {zh:'道', pinyin:'dào', hv:'đạo', vi:'đường; đạo lý', pos:'chữ Hán'},
  {zh:'注', pinyin:'zhù', hv:'chú', vi:'rót vào; chú ý', pos:'chữ Hán'},
  {zh:'意', pinyin:'yì', hv:'ý', vi:'ý, ý nghĩ', pos:'chữ Hán'},
  {zh:'思', pinyin:'sī', hv:'tư', vi:'nghĩ', pos:'chữ Hán'},
  {zh:'认', pinyin:'rèn', hv:'nhận', vi:'nhận biết, thừa nhận', pos:'chữ Hán'},
  {zh:'识', pinyin:'shí', hv:'thức', vi:'biết, hiểu biết', pos:'chữ Hán'},
  {zh:'简', pinyin:'jiǎn', hv:'giản', vi:'đơn giản', pos:'chữ Hán'},
  {zh:'技', pinyin:'jì', hv:'kỹ', vi:'kỹ năng, tay nghề', pos:'chữ Hán'},
  {zh:'术', pinyin:'shù', hv:'thuật', vi:'thuật, kỹ thuật', pos:'chữ Hán'},
  {zh:'法', pinyin:'fǎ', hv:'pháp', vi:'phép, cách, luật', pos:'chữ Hán'},
  {zh:'讲', pinyin:'jiǎng', hv:'giảng', vi:'nói, giảng giải', pos:'chữ Hán'},
  {zh:'究', pinyin:'jiū', hv:'cứu', vi:'xét kỹ, nghiên cứu', pos:'chữ Hán'},

  /* ---------- Thời gian ---------- */
  {zh:'今', pinyin:'jīn', hv:'kim', vi:'nay, hiện tại', pos:'chữ Hán'},
  {zh:'年', pinyin:'nián', hv:'niên', vi:'năm', pos:'chữ Hán'},
  {zh:'早', pinyin:'zǎo', hv:'tảo', vi:'sớm; buổi sáng', pos:'chữ Hán'},
  {zh:'午', pinyin:'wǔ', hv:'ngọ', vi:'buổi trưa', pos:'chữ Hán'},
  {zh:'时', pinyin:'shí', hv:'thời', vi:'thời gian, lúc', pos:'chữ Hán'},
  {zh:'候', pinyin:'hòu', hv:'hậu', vi:'lúc, thời điểm; chờ', pos:'chữ Hán'},
  {zh:'间', pinyin:'jiān', hv:'gian', vi:'khoảng giữa; phòng', pos:'chữ Hán'},
  {zh:'后', pinyin:'hòu', hv:'hậu', vi:'sau, phía sau', pos:'chữ Hán'},
  {zh:'前', pinyin:'qián', hv:'tiền', vi:'trước, phía trước', pos:'chữ Hán'},
  {zh:'始', pinyin:'shǐ', hv:'thuỷ', vi:'bắt đầu', pos:'chữ Hán'},
  {zh:'终', pinyin:'zhōng', hv:'chung', vi:'cuối cùng, kết thúc', pos:'chữ Hán'},
  {zh:'昨', pinyin:'zuó', hv:'tạc', vi:'hôm qua', pos:'chữ Hán'},
  {zh:'现', pinyin:'xiàn', hv:'hiện', vi:'hiện nay, xuất hiện', pos:'chữ Hán'},
  {zh:'星', pinyin:'xīng', hv:'tinh', vi:'ngôi sao; tuần (星期)', pos:'chữ Hán'},
  {zh:'期', pinyin:'qī', hv:'kỳ', vi:'kỳ hạn, thời kỳ', pos:'chữ Hán'},
  {zh:'周', pinyin:'zhōu', hv:'chu', vi:'tuần; vòng quanh', pos:'chữ Hán'},
  {zh:'末', pinyin:'mò', hv:'mạt', vi:'cuối, ngọn', pos:'chữ Hán'},
  {zh:'春', pinyin:'chūn', hv:'xuân', vi:'mùa xuân', pos:'chữ Hán'},
  {zh:'夏', pinyin:'xià', hv:'hạ', vi:'mùa hè', pos:'chữ Hán'},
  {zh:'秋', pinyin:'qiū', hv:'thu', vi:'mùa thu', pos:'chữ Hán'},
  {zh:'夜', pinyin:'yè', hv:'dạ', vi:'đêm', pos:'chữ Hán'},
  {zh:'除', pinyin:'chú', hv:'trừ', vi:'trừ bỏ; đêm trừ tịch', pos:'chữ Hán'},
  {zh:'夕', pinyin:'xī', hv:'tịch', vi:'chiều tối', pos:'chữ Hán'},
  {zh:'刻', pinyin:'kè', hv:'khắc', vi:'khắc (15 phút); khoảnh khắc; khắc chạm', pos:'chữ Hán'},
  {zh:'历', pinyin:'lì', hv:'lịch', vi:'lịch; trải qua', pos:'chữ Hán'},
  {zh:'农', pinyin:'nóng', hv:'nông', vi:'nông nghiệp, nhà nông', pos:'chữ Hán'},
  {zh:'之', pinyin:'zhī', hv:'chi', vi:'của (văn viết)', pos:'chữ Hán'},
  {zh:'至', pinyin:'zhì', hv:'chí', vi:'đến, tới; cực kỳ', pos:'chữ Hán'},
  {zh:'已', pinyin:'yǐ', hv:'dĩ', vi:'đã, rồi', pos:'chữ Hán'},
  {zh:'经', pinyin:'jīng', hv:'kinh', vi:'trải qua; kinh sách', pos:'chữ Hán'},
  {zh:'总', pinyin:'zǒng', hv:'tổng', vi:'tổng cộng; luôn luôn', pos:'chữ Hán'},
  {zh:'常', pinyin:'cháng', hv:'thường', vi:'thường xuyên', pos:'chữ Hán'},
  {zh:'随', pinyin:'suí', hv:'tuỳ', vi:'theo, tuỳ theo', pos:'chữ Hán'},
  {zh:'忽', pinyin:'hū', hv:'hốt', vi:'bỗng nhiên', pos:'chữ Hán'},
  {zh:'正', pinyin:'zhèng', hv:'chính', vi:'đúng, chính; đang', pos:'chữ Hán'},
  {zh:'直', pinyin:'zhí', hv:'trực', vi:'thẳng; thẳng thắn', pos:'chữ Hán'},
  {zh:'万', pinyin:'wàn', hv:'vạn', vi:'vạn (10 000)', pos:'chữ Hán'},
  {zh:'百', pinyin:'bǎi', hv:'bách', vi:'trăm', pos:'chữ Hán'},
  {zh:'第', pinyin:'dì', hv:'đệ', vi:'thứ (số thứ tự)', pos:'chữ Hán'},
  {zh:'单', pinyin:'dān', hv:'đơn', vi:'đơn lẻ; đơn, phiếu', pos:'chữ Hán'},
  {zh:'共', pinyin:'gòng', hv:'cộng', vi:'chung, cộng lại', pos:'chữ Hán'},
  {zh:'全', pinyin:'quán', hv:'toàn', vi:'toàn bộ, đầy đủ', pos:'chữ Hán'},
  {zh:'量', pinyin:'liàng', hv:'lượng', vi:'số lượng; đo', pos:'chữ Hán'},
  {zh:'些', pinyin:'xiē', hv:'ta', vi:'một ít, vài', pos:'chữ Hán'},
  {zh:'条', pinyin:'tiáo', hv:'điều', vi:'lượng từ cho vật dài; điều khoản', pos:'chữ Hán'},
  {zh:'片', pinyin:'piàn', hv:'phiến', vi:'miếng, tấm', pos:'chữ Hán'},
  {zh:'般', pinyin:'bān', hv:'ban', vi:'loại, kiểu (一般: nói chung)', pos:'chữ Hán'},
  {zh:'样', pinyin:'yàng', hv:'dạng', vi:'kiểu, dáng', pos:'chữ Hán'},
  {zh:'次', pinyin:'cì', hv:'thứ', vi:'lần; thứ tự', pos:'chữ Hán'},

  /* ---------- Con người · gia đình ---------- */
  {zh:'朋', pinyin:'péng', hv:'bằng', vi:'bạn bè', pos:'chữ Hán'},
  {zh:'友', pinyin:'yǒu', hv:'hữu', vi:'bạn', pos:'chữ Hán'},
  {zh:'爸', pinyin:'bà', hv:'ba', vi:'bố', pos:'chữ Hán'},
  {zh:'妈', pinyin:'mā', hv:'ma', vi:'mẹ', pos:'chữ Hán'},
  {zh:'哥', pinyin:'gē', hv:'ca', vi:'anh trai', pos:'chữ Hán'},
  {zh:'妹', pinyin:'mèi', hv:'muội', vi:'em gái', pos:'chữ Hán'},
  {zh:'男', pinyin:'nán', hv:'nam', vi:'nam giới', pos:'chữ Hán'},
  {zh:'奶', pinyin:'nǎi', hv:'nãi', vi:'bà nội; sữa', pos:'chữ Hán'},
  {zh:'爷', pinyin:'yé', hv:'gia', vi:'ông nội', pos:'chữ Hán'},
  {zh:'阿', pinyin:'ā', hv:'a', vi:'tiền tố gọi thân mật', pos:'chữ Hán'},
  {zh:'姨', pinyin:'yí', hv:'di', vi:'dì, cô (phụ nữ trung niên)', pos:'chữ Hán'},
  {zh:'孩', pinyin:'hái', hv:'hài', vi:'đứa trẻ', pos:'chữ Hán'},
  {zh:'儿', pinyin:'ér', hv:'nhi', vi:'con, trẻ nhỏ; đuôi 儿', pos:'chữ Hán'},
  {zh:'辈', pinyin:'bèi', hv:'bối', vi:'thế hệ, bậc', pos:'chữ Hán'},
  {zh:'夫', pinyin:'fū', hv:'phu', vi:'chồng; người đàn ông', pos:'chữ Hán'},
  {zh:'妻', pinyin:'qī', hv:'thê', vi:'vợ', pos:'chữ Hán'},
  {zh:'员', pinyin:'yuán', hv:'viên', vi:'thành viên, nhân viên', pos:'chữ Hán'},
  {zh:'傅', pinyin:'fù', hv:'phó', vi:'thầy dạy nghề (师傅)', pos:'chữ Hán'},
  {zh:'坊', pinyin:'fāng', hv:'phường', vi:'xóm, phường; xưởng', pos:'chữ Hán'},
  {zh:'邻', pinyin:'lín', hv:'lân', vi:'láng giềng', pos:'chữ Hán'},
  {zh:'居', pinyin:'jū', hv:'cư', vi:'ở, cư trú', pos:'chữ Hán'},
  {zh:'客', pinyin:'kè', hv:'khách', vi:'khách', pos:'chữ Hán'},
  {zh:'己', pinyin:'jǐ', hv:'kỷ', vi:'mình, bản thân', pos:'chữ Hán'},
  {zh:'身', pinyin:'shēn', hv:'thân', vi:'thân thể', pos:'chữ Hán'},
  {zh:'体', pinyin:'tǐ', hv:'thể', vi:'cơ thể; thể loại', pos:'chữ Hán'},

  /* ---------- Cơ thể · sức khoẻ ---------- */
  {zh:'医', pinyin:'yī', hv:'y', vi:'y học, chữa bệnh', pos:'chữ Hán'},
  {zh:'院', pinyin:'yuàn', hv:'viện', vi:'viện, sân trong', pos:'chữ Hán'},
  {zh:'病', pinyin:'bìng', hv:'bệnh', vi:'bệnh', pos:'chữ Hán'},
  {zh:'感', pinyin:'gǎn', hv:'cảm', vi:'cảm thấy; cảm động', pos:'chữ Hán'},
  {zh:'冒', pinyin:'mào', hv:'mạo', vi:'bốc lên; liều (感冒: cảm)', pos:'chữ Hán'},
  {zh:'咳', pinyin:'ké', hv:'khái', vi:'ho', pos:'chữ Hán'},
  {zh:'嗽', pinyin:'sou', hv:'thấu', vi:'ho (咳嗽)', pos:'chữ Hán'},
  {zh:'烧', pinyin:'shāo', hv:'thiêu', vi:'đốt; sốt', pos:'chữ Hán'},
  {zh:'检', pinyin:'jiǎn', hv:'kiểm', vi:'kiểm tra', pos:'chữ Hán'},
  {zh:'查', pinyin:'chá', hv:'tra', vi:'tra cứu, kiểm tra', pos:'chữ Hán'},
  {zh:'针', pinyin:'zhēn', hv:'châm', vi:'cây kim; mũi tiêm', pos:'chữ Hán'},
  {zh:'护', pinyin:'hù', hv:'hộ', vi:'bảo vệ, chăm sóc', pos:'chữ Hán'},
  {zh:'休', pinyin:'xiū', hv:'hưu', vi:'nghỉ ngơi', pos:'chữ Hán'},
  {zh:'息', pinyin:'xī', hv:'tức', vi:'nghỉ; hơi thở; tin tức', pos:'chữ Hán'},
  {zh:'睡', pinyin:'shuì', hv:'thuỵ', vi:'ngủ', pos:'chữ Hán'},
  {zh:'舒', pinyin:'shū', hv:'thư', vi:'thư thái, dễ chịu', pos:'chữ Hán'},
  {zh:'服', pinyin:'fú', hv:'phục', vi:'quần áo; phục vụ; uống thuốc', pos:'chữ Hán'},
  {zh:'嗓', pinyin:'sǎng', hv:'tảng', vi:'cổ họng, giọng', pos:'chữ Hán'},
  {zh:'眼', pinyin:'yǎn', hv:'nhãn', vi:'mắt', pos:'chữ Hán'},
  {zh:'睛', pinyin:'jīng', hv:'tinh', vi:'con ngươi (眼睛: mắt)', pos:'chữ Hán'},
  {zh:'牙', pinyin:'yá', hv:'nha', vi:'răng', pos:'chữ Hán'},
  {zh:'肚', pinyin:'dù', hv:'đỗ', vi:'bụng', pos:'chữ Hán'},
  {zh:'呼', pinyin:'hū', hv:'hô', vi:'thở ra; gọi', pos:'chữ Hán'},
  {zh:'吸', pinyin:'xī', hv:'hấp', vi:'hít vào, hút', pos:'chữ Hán'},
  {zh:'严', pinyin:'yán', hv:'nghiêm', vi:'nghiêm, nghiêm trọng', pos:'chữ Hán'},

  /* ---------- Ăn uống ---------- */
  {zh:'食', pinyin:'shí', hv:'thực', vi:'ăn, thức ăn', pos:'chữ Hán'},
  {zh:'堂', pinyin:'táng', hv:'đường', vi:'nhà lớn, sảnh (食堂)', pos:'chữ Hán'},
  {zh:'馆', pinyin:'guǎn', hv:'quán', vi:'quán, nhà (饭馆)', pos:'chữ Hán'},
  {zh:'面', pinyin:'miàn', hv:'diện', vi:'mặt; mì; phía', pos:'chữ Hán'},
  {zh:'蛋', pinyin:'dàn', hv:'đản', vi:'trứng', pos:'chữ Hán'},
  {zh:'青', pinyin:'qīng', hv:'thanh', vi:'xanh; trẻ', pos:'chữ Hán'},
  {zh:'豆', pinyin:'dòu', hv:'đậu', vi:'đậu', pos:'chữ Hán'},
  {zh:'腐', pinyin:'fǔ', hv:'hủ', vi:'thiu, mục (豆腐: đậu phụ)', pos:'chữ Hán'},
  {zh:'苹', pinyin:'píng', hv:'bình', vi:'táo (苹果)', pos:'chữ Hán'},
  {zh:'果', pinyin:'guǒ', hv:'quả', vi:'quả, kết quả', pos:'chữ Hán'},
  {zh:'香', pinyin:'xiāng', hv:'hương', vi:'thơm', pos:'chữ Hán'},
  {zh:'蕉', pinyin:'jiāo', hv:'tiêu', vi:'chuối (香蕉)', pos:'chữ Hán'},
  {zh:'柿', pinyin:'shì', hv:'thị', vi:'quả hồng; cà chua (西红柿)', pos:'chữ Hán'},
  {zh:'葱', pinyin:'cōng', hv:'thông', vi:'hành lá', pos:'chữ Hán'},
  {zh:'鲜', pinyin:'xiān', hv:'tiên', vi:'tươi, tươi ngon', pos:'chữ Hán'},
  {zh:'味', pinyin:'wèi', hv:'vị', vi:'mùi vị', pos:'chữ Hán'},
  {zh:'饺', pinyin:'jiǎo', hv:'giảo', vi:'sủi cảo (饺子)', pos:'chữ Hán'},
  {zh:'糕', pinyin:'gāo', hv:'cao', vi:'bánh (蛋糕: bánh ga-tô)', pos:'chữ Hán'},
  {zh:'饼', pinyin:'bǐng', hv:'bính', vi:'bánh dẹt (月饼)', pos:'chữ Hán'},
  {zh:'沙', pinyin:'shā', hv:'sa', vi:'cát; nhân nghiền (豆沙)', pos:'chữ Hán'},
  {zh:'莲', pinyin:'lián', hv:'liên', vi:'hoa sen', pos:'chữ Hán'},
  {zh:'蓉', pinyin:'róng', hv:'dung', vi:'bột nhuyễn (莲蓉: nhân hạt sen)', pos:'chữ Hán'},
  {zh:'仁', pinyin:'rén', hv:'nhân', vi:'nhân hạt; lòng nhân', pos:'chữ Hán'},
  {zh:'瓶', pinyin:'píng', hv:'bình', vi:'cái chai', pos:'chữ Hán'},
  {zh:'桶', pinyin:'tǒng', hv:'dũng', vi:'cái thùng', pos:'chữ Hán'},
  {zh:'火', pinyin:'huǒ', hv:'hoả', vi:'lửa', pos:'chữ Hán'},
  {zh:'浇', pinyin:'jiāo', hv:'kiêu', vi:'tưới, dội', pos:'chữ Hán'},

  /* ---------- Nhà cửa · đồ vật ---------- */
  {zh:'房', pinyin:'fáng', hv:'phòng', vi:'nhà, phòng', pos:'chữ Hán'},
  {zh:'屋', pinyin:'wū', hv:'ốc', vi:'nhà, gian nhà', pos:'chữ Hán'},
  {zh:'室', pinyin:'shì', hv:'thất', vi:'phòng, buồng', pos:'chữ Hán'},
  {zh:'栋', pinyin:'dòng', hv:'đống', vi:'toà (lượng từ cho nhà)', pos:'chữ Hán'},
  {zh:'窗', pinyin:'chuāng', hv:'song', vi:'cửa sổ', pos:'chữ Hán'},
  {zh:'户', pinyin:'hù', hv:'hộ', vi:'cửa; hộ gia đình', pos:'chữ Hán'},
  {zh:'桌', pinyin:'zhuō', hv:'trác', vi:'cái bàn', pos:'chữ Hán'},
  {zh:'椅', pinyin:'yǐ', hv:'ỷ', vi:'cái ghế', pos:'chữ Hán'},
  {zh:'子', pinyin:'zi', hv:'tử', vi:'con; hậu tố danh từ', pos:'chữ Hán'},
  {zh:'枕', pinyin:'zhěn', hv:'chẩm', vi:'cái gối', pos:'chữ Hán'},
  {zh:'柜', pinyin:'guì', hv:'quỹ', vi:'cái tủ', pos:'chữ Hán'},
  {zh:'箱', pinyin:'xiāng', hv:'tương', vi:'cái hộp, thùng', pos:'chữ Hán'},
  {zh:'袋', pinyin:'dài', hv:'đại', vi:'cái túi', pos:'chữ Hán'},
  {zh:'板', pinyin:'bǎn', hv:'bản', vi:'tấm ván; ông chủ (老板)', pos:'chữ Hán'},
  {zh:'叶', pinyin:'yè', hv:'diệp', vi:'lá cây', pos:'chữ Hán'},
  {zh:'尘', pinyin:'chén', hv:'trần', vi:'bụi', pos:'chữ Hán'},
  {zh:'器', pinyin:'qì', hv:'khí', vi:'đồ dùng, thiết bị', pos:'chữ Hán'},
  {zh:'机', pinyin:'jī', hv:'cơ', vi:'máy; cơ hội', pos:'chữ Hán'},
  {zh:'脑', pinyin:'nǎo', hv:'não', vi:'não; máy tính (电脑)', pos:'chữ Hán'},
  {zh:'电', pinyin:'diàn', hv:'điện', vi:'điện', pos:'chữ Hán'},
  {zh:'视', pinyin:'shì', hv:'thị', vi:'nhìn; tivi (电视)', pos:'chữ Hán'},
  {zh:'影', pinyin:'yǐng', hv:'ảnh', vi:'bóng; phim (电影)', pos:'chữ Hán'},
  {zh:'照', pinyin:'zhào', hv:'chiếu', vi:'chiếu sáng; chụp ảnh', pos:'chữ Hán'},
  {zh:'响', pinyin:'xiǎng', hv:'hưởng', vi:'vang lên, kêu', pos:'chữ Hán'},
  {zh:'音', pinyin:'yīn', hv:'âm', vi:'âm thanh', pos:'chữ Hán'},
  {zh:'乐', pinyin:'yuè', hv:'nhạc', vi:'âm nhạc; (lè) vui', pos:'chữ Hán'},
  {zh:'钥', pinyin:'yào', hv:'dược', vi:'chìa khoá (钥匙)', pos:'chữ Hán'},
  {zh:'匙', pinyin:'shi', hv:'thi', vi:'thìa; chìa (钥匙)', pos:'chữ Hán'},
  {zh:'充', pinyin:'chōng', hv:'sung', vi:'nạp, đổ đầy', pos:'chữ Hán'},
  {zh:'宝', pinyin:'bǎo', hv:'bảo', vi:'báu vật', pos:'chữ Hán'},
  {zh:'支', pinyin:'zhī', hv:'chi', vi:'chi trả; cái (lượng từ)', pos:'chữ Hán'},
  {zh:'卡', pinyin:'kǎ', hv:'ca', vi:'cái thẻ', pos:'chữ Hán'},
  {zh:'码', pinyin:'mǎ', hv:'mã', vi:'mã số', pos:'chữ Hán'},
  {zh:'牌', pinyin:'pái', hv:'bài', vi:'tấm biển; thương hiệu', pos:'chữ Hán'},
  {zh:'表', pinyin:'biǎo', hv:'biểu', vi:'bảng, biểu; đồng hồ đeo tay', pos:'chữ Hán'},
  {zh:'栏', pinyin:'lán', hv:'lan', vi:'ô, cột (trong biểu mẫu)', pos:'chữ Hán'},
  {zh:'衣', pinyin:'yī', hv:'y', vi:'áo, quần áo', pos:'chữ Hán'},
  {zh:'色', pinyin:'sè', hv:'sắc', vi:'màu sắc', pos:'chữ Hán'},
  {zh:'颜', pinyin:'yán', hv:'nhan', vi:'màu; nét mặt', pos:'chữ Hán'},
  {zh:'金', pinyin:'jīn', hv:'kim', vi:'vàng, kim loại', pos:'chữ Hán'},
  {zh:'银', pinyin:'yín', hv:'ngân', vi:'bạc; ngân hàng (银行)', pos:'chữ Hán'},
  {zh:'礼', pinyin:'lǐ', hv:'lễ', vi:'lễ nghi; quà tặng', pos:'chữ Hán'},
  {zh:'物', pinyin:'wù', hv:'vật', vi:'vật, đồ vật', pos:'chữ Hán'},

  /* ---------- Giao thông · nơi chốn ---------- */
  {zh:'车', pinyin:'chē', hv:'xa', vi:'xe', pos:'chữ Hán'},
  {zh:'铁', pinyin:'tiě', hv:'thiết', vi:'sắt; tàu điện ngầm (地铁)', pos:'chữ Hán'},
  {zh:'地', pinyin:'dì', hv:'địa', vi:'đất, mặt đất', pos:'chữ Hán'},
  {zh:'图', pinyin:'tú', hv:'đồ', vi:'bản đồ, hình vẽ', pos:'chữ Hán'},
  {zh:'路', pinyin:'lù', hv:'lộ', vi:'đường', pos:'chữ Hán'},
  {zh:'往', pinyin:'wǎng', hv:'vãng', vi:'đi về phía', pos:'chữ Hán'},
  {zh:'左', pinyin:'zuǒ', hv:'tả', vi:'bên trái', pos:'chữ Hán'},
  {zh:'右', pinyin:'yòu', hv:'hữu', vi:'bên phải', pos:'chữ Hán'},
  {zh:'拐', pinyin:'guǎi', hv:'quải', vi:'rẽ, ngoặt', pos:'chữ Hán'},
  {zh:'旁', pinyin:'páng', hv:'bàng', vi:'bên cạnh', pos:'chữ Hán'},
  {zh:'边', pinyin:'biān', hv:'biên', vi:'bên, mép, rìa', pos:'chữ Hán'},
  {zh:'内', pinyin:'nèi', hv:'nội', vi:'bên trong', pos:'chữ Hán'},
  {zh:'外', pinyin:'wài', hv:'ngoại', vi:'bên ngoài', pos:'chữ Hán'},
  {zh:'上', pinyin:'shàng', hv:'thượng', vi:'trên; lên', pos:'chữ Hán'},
  {zh:'下', pinyin:'xià', hv:'hạ', vi:'dưới; xuống', pos:'chữ Hán'},
  {zh:'中', pinyin:'zhōng', hv:'trung', vi:'giữa; Trung Quốc', pos:'chữ Hán'},
  {zh:'国', pinyin:'guó', hv:'quốc', vi:'nước, quốc gia', pos:'chữ Hán'},
  {zh:'城', pinyin:'chéng', hv:'thành', vi:'thành phố, thành luỹ', pos:'chữ Hán'},
  {zh:'市', pinyin:'shì', hv:'thị', vi:'chợ; thành phố', pos:'chữ Hán'},
  {zh:'店', pinyin:'diàn', hv:'điếm', vi:'cửa hàng', pos:'chữ Hán'},
  {zh:'摊', pinyin:'tān', hv:'than', vi:'quầy hàng, sạp', pos:'chữ Hán'},
  {zh:'公', pinyin:'gōng', hv:'công', vi:'chung, công cộng', pos:'chữ Hán'},
  {zh:'司', pinyin:'sī', hv:'ty', vi:'quản lý (公司: công ty)', pos:'chữ Hán'},
  {zh:'业', pinyin:'yè', hv:'nghiệp', vi:'nghề, ngành', pos:'chữ Hán'},
  {zh:'商', pinyin:'shāng', hv:'thương', vi:'buôn bán; bàn bạc', pos:'chữ Hán'},
  {zh:'务', pinyin:'wù', hv:'vụ', vi:'việc, nhiệm vụ', pos:'chữ Hán'},
  {zh:'园', pinyin:'yuán', hv:'viên', vi:'vườn, công viên', pos:'chữ Hán'},
  {zh:'卫', pinyin:'wèi', hv:'vệ', vi:'bảo vệ, vệ sinh', pos:'chữ Hán'},
  {zh:'址', pinyin:'zhǐ', hv:'chỉ', vi:'địa chỉ, vị trí', pos:'chữ Hán'},
  {zh:'籍', pinyin:'jí', hv:'tịch', vi:'sổ sách; quốc tịch', pos:'chữ Hán'},
  {zh:'名', pinyin:'míng', hv:'danh', vi:'tên; nổi tiếng', pos:'chữ Hán'},
  {zh:'堵', pinyin:'dǔ', hv:'đổ', vi:'tắc, nghẽn', pos:'chữ Hán'},
  {zh:'售', pinyin:'shòu', hv:'thụ', vi:'bán', pos:'chữ Hán'},
  {zh:'广', pinyin:'guǎng', hv:'quảng', vi:'rộng; quảng bá', pos:'chữ Hán'},
  {zh:'播', pinyin:'bō', hv:'bá', vi:'phát, gieo', pos:'chữ Hán'},
  {zh:'递', pinyin:'dì', hv:'đệ', vi:'chuyển giao (快递)', pos:'chữ Hán'},
  {zh:'裹', pinyin:'guǒ', hv:'khoả', vi:'bọc, gói (包裹)', pos:'chữ Hán'},
  {zh:'信', pinyin:'xìn', hv:'tín', vi:'thư; tin tưởng', pos:'chữ Hán'},

  /* ---------- Thiên nhiên ---------- */
  {zh:'雨', pinyin:'yǔ', hv:'vũ', vi:'mưa', pos:'chữ Hán'},
  {zh:'阳', pinyin:'yáng', hv:'dương', vi:'mặt trời, dương', pos:'chữ Hán'},
  {zh:'气', pinyin:'qì', hv:'khí', vi:'khí, hơi; tức giận', pos:'chữ Hán'},
  {zh:'氵', pinyin:'shuǐ', hv:'thuỷ', vi:'bộ ba chấm thuỷ (nước)', pos:'bộ thủ'},
  {zh:'山', pinyin:'shān', hv:'sơn', vi:'núi', pos:'chữ Hán'},
  {zh:'顶', pinyin:'dǐng', hv:'đỉnh', vi:'đỉnh, chóp', pos:'chữ Hán'},
  {zh:'爬', pinyin:'pá', hv:'ba', vi:'leo, bò', pos:'chữ Hán'},
  {zh:'游', pinyin:'yóu', hv:'du', vi:'bơi; đi chơi', pos:'chữ Hán'},
  {zh:'泳', pinyin:'yǒng', hv:'vịnh', vi:'bơi lội', pos:'chữ Hán'},
  {zh:'浪', pinyin:'làng', hv:'lãng', vi:'sóng; phóng túng', pos:'chữ Hán'},
  {zh:'费', pinyin:'fèi', hv:'phí', vi:'chi phí; tiêu tốn', pos:'chữ Hán'},
  {zh:'团', pinyin:'tuán', hv:'đoàn', vi:'đoàn, khối tròn', pos:'chữ Hán'},
  {zh:'赏', pinyin:'shǎng', hv:'thưởng', vi:'thưởng thức; ban thưởng', pos:'chữ Hán'},

  /* ---------- Động từ ---------- */
  {zh:'起', pinyin:'qǐ', hv:'khởi', vi:'dậy, khởi đầu', pos:'chữ Hán'},
  {zh:'喜', pinyin:'xǐ', hv:'hỷ', vi:'vui mừng, thích', pos:'chữ Hán'},
  {zh:'欢', pinyin:'huān', hv:'hoan', vi:'vui vẻ (喜欢: thích)', pos:'chữ Hán'},
  {zh:'和', pinyin:'hé', hv:'hoà', vi:'và; hoà thuận', pos:'chữ Hán'},
  {zh:'可', pinyin:'kě', hv:'khả', vi:'có thể; nhưng', pos:'chữ Hán'},
  {zh:'高', pinyin:'gāo', hv:'cao', vi:'cao', pos:'chữ Hán'},
  {zh:'兴', pinyin:'xìng', hv:'hứng', vi:'hứng thú (高兴: vui)', pos:'chữ Hán'},
  {zh:'卖', pinyin:'mài', hv:'mại', vi:'bán', pos:'chữ Hán'},
  {zh:'有', pinyin:'yǒu', hv:'hữu', vi:'có', pos:'chữ Hán'},
  {zh:'小', pinyin:'xiǎo', hv:'tiểu', vi:'nhỏ', pos:'chữ Hán'},
  {zh:'大', pinyin:'dà', hv:'đại', vi:'to, lớn', pos:'chữ Hán'},
  {zh:'按', pinyin:'àn', hv:'án', vi:'bấm, ấn; theo', pos:'chữ Hán'},
  {zh:'顺', pinyin:'shùn', hv:'thuận', vi:'thuận, xuôi', pos:'chữ Hán'},
  {zh:'序', pinyin:'xù', hv:'tự', vi:'thứ tự', pos:'chữ Hán'},
  {zh:'排', pinyin:'pái', hv:'bài', vi:'xếp hàng, sắp xếp', pos:'chữ Hán'},
  {zh:'问', pinyin:'wèn', hv:'vấn', vi:'hỏi', pos:'chữ Hán'},
  {zh:'扣', pinyin:'kòu', hv:'khấu', vi:'trừ, khấu; cài', pos:'chữ Hán'},
  {zh:'所', pinyin:'suǒ', hv:'sở', vi:'nơi; sở dĩ (所以)', pos:'chữ Hán'},
  {zh:'以', pinyin:'yǐ', hv:'dĩ', vi:'lấy, dùng; để mà', pos:'chữ Hán'},
  {zh:'来', pinyin:'lái', hv:'lai', vi:'đến, tới', pos:'chữ Hán'},
  {zh:'回', pinyin:'huí', hv:'hồi', vi:'quay về; lần', pos:'chữ Hán'},
  {zh:'工', pinyin:'gōng', hv:'công', vi:'công việc, thợ', pos:'chữ Hán'},
  {zh:'作', pinyin:'zuò', hv:'tác', vi:'làm, sáng tác', pos:'chữ Hán'},
  {zh:'辛', pinyin:'xīn', hv:'tân', vi:'cay đắng, vất vả', pos:'chữ Hán'},
  {zh:'但', pinyin:'dàn', hv:'đãn', vi:'nhưng', pos:'chữ Hán'},
  {zh:'自', pinyin:'zì', hv:'tự', vi:'tự, từ', pos:'chữ Hán'},
  {zh:'由', pinyin:'yóu', hv:'do', vi:'do, bởi; tự do', pos:'chữ Hán'},
  {zh:'算', pinyin:'suàn', hv:'toán', vi:'tính toán; coi như', pos:'chữ Hán'},
  {zh:'存', pinyin:'cún', hv:'tồn', vi:'gửi, cất giữ; tồn tại', pos:'chữ Hán'},
  {zh:'行', pinyin:'xíng', hv:'hành', vi:'đi; được; (háng) hàng', pos:'chữ Hán'},
  {zh:'见', pinyin:'jiàn', hv:'kiến', vi:'thấy, gặp', pos:'chữ Hán'},
  {zh:'告', pinyin:'gào', hv:'cáo', vi:'báo, nói cho biết', pos:'chữ Hán'},
  {zh:'诉', pinyin:'sù', hv:'tố', vi:'kể, tố cáo', pos:'chữ Hán'},
  {zh:'迟', pinyin:'chí', hv:'trì', vi:'chậm, trễ', pos:'chữ Hán'},
  {zh:'净', pinyin:'jìng', hv:'tịnh', vi:'sạch (干净)', pos:'chữ Hán'},
  {zh:'管', pinyin:'guǎn', hv:'quản', vi:'quản lý; cái ống', pos:'chữ Hán'},
  {zh:'走', pinyin:'zǒu', hv:'tẩu', vi:'đi, bước', pos:'chữ Hán'},
  {zh:'取', pinyin:'qǔ', hv:'thủ', vi:'lấy, rút', pos:'chữ Hán'},
  {zh:'轮', pinyin:'lún', hv:'luân', vi:'bánh xe; đến lượt', pos:'chữ Hán'},
  {zh:'需', pinyin:'xū', hv:'nhu', vi:'cần', pos:'chữ Hán'},
  {zh:'填', pinyin:'tián', hv:'điền', vi:'điền vào', pos:'chữ Hán'},
  {zh:'耐', pinyin:'nài', hv:'nại', vi:'chịu đựng, kiên nhẫn', pos:'chữ Hán'},
  {zh:'提', pinyin:'tí', hv:'đề', vi:'nâng, xách; nêu ra', pos:'chữ Hán'},
  {zh:'醒', pinyin:'xǐng', hv:'tỉnh', vi:'tỉnh dậy; nhắc nhở', pos:'chữ Hán'},
  {zh:'密', pinyin:'mì', hv:'mật', vi:'kín, dày; bí mật', pos:'chữ Hán'},
  {zh:'载', pinyin:'zài', hv:'tải', vi:'chở, tải', pos:'chữ Hán'},
  {zh:'出', pinyin:'chū', hv:'xuất', vi:'ra, đi ra', pos:'chữ Hán'},
  {zh:'动', pinyin:'dòng', hv:'động', vi:'động, cử động', pos:'chữ Hán'},
  {zh:'紧', pinyin:'jǐn', hv:'khẩn', vi:'chặt, gấp', pos:'chữ Hán'},
  {zh:'原', pinyin:'yuán', hv:'nguyên', vi:'vốn, nguyên; đồng bằng', pos:'chữ Hán'},
  {zh:'漂', pinyin:'piào', hv:'phiêu', vi:'đẹp (漂亮); trôi nổi', pos:'chữ Hán'},
  {zh:'努', pinyin:'nǔ', hv:'nỗ', vi:'gắng sức', pos:'chữ Hán'},
  {zh:'力', pinyin:'lì', hv:'lực', vi:'sức, lực', pos:'chữ Hán'},
  {zh:'玩', pinyin:'wán', hv:'ngoạn', vi:'chơi', pos:'chữ Hán'},
  {zh:'舞', pinyin:'wǔ', hv:'vũ', vi:'múa, nhảy', pos:'chữ Hán'},
  {zh:'理', pinyin:'lǐ', hv:'lý', vi:'lý lẽ; chỉnh lý', pos:'chữ Hán'},
  {zh:'假', pinyin:'jià', hv:'giả', vi:'kỳ nghỉ; (jiǎ) giả', pos:'chữ Hán'},
  {zh:'运', pinyin:'yùn', hv:'vận', vi:'vận chuyển; vận động', pos:'chữ Hán'},
  {zh:'谢', pinyin:'xiè', hv:'tạ', vi:'cảm ơn', pos:'chữ Hán'},
  {zh:'靠', pinyin:'kào', hv:'kháo', vi:'dựa vào', pos:'chữ Hán'},
  {zh:'细', pinyin:'xì', hv:'tế', vi:'nhỏ, mảnh; tỉ mỉ', pos:'chữ Hán'},
  {zh:'爆', pinyin:'bào', hv:'bạo', vi:'nổ bùng', pos:'chữ Hán'},
  {zh:'故', pinyin:'gù', hv:'cố', vi:'cũ, cố; nguyên do', pos:'chữ Hán'},
  {zh:'事', pinyin:'shì', hv:'sự', vi:'việc, chuyện', pos:'chữ Hán'},
  {zh:'决', pinyin:'jué', hv:'quyết', vi:'quyết định', pos:'chữ Hán'},
  {zh:'定', pinyin:'dìng', hv:'định', vi:'định, ổn định', pos:'chữ Hán'},
  {zh:'扫', pinyin:'sǎo', hv:'tảo', vi:'quét', pos:'chữ Hán'},
  {zh:'收', pinyin:'shōu', hv:'thu', vi:'thu, nhận, cất', pos:'chữ Hán'},
  {zh:'结', pinyin:'jié', hv:'kết', vi:'kết, buộc; kết quả', pos:'chữ Hán'},
  {zh:'超', pinyin:'chāo', hv:'siêu', vi:'vượt quá', pos:'chữ Hán'},
  {zh:'且', pinyin:'qiě', hv:'thả', vi:'vả lại, hơn nữa', pos:'chữ Hán'},
  {zh:'价', pinyin:'jià', hv:'giá', vi:'giá cả', pos:'chữ Hán'},
  {zh:'闹', pinyin:'nào', hv:'náo', vi:'ồn ào, náo nhiệt', pos:'chữ Hán'},
  {zh:'实', pinyin:'shí', hv:'thực', vi:'thật, thực tế', pos:'chữ Hán'},
  {zh:'惯', pinyin:'guàn', hv:'quán', vi:'quen (习惯)', pos:'chữ Hán'},
  {zh:'申', pinyin:'shēn', hv:'thân', vi:'trình bày, xin', pos:'chữ Hán'},
  {zh:'退', pinyin:'tuì', hv:'thoái', vi:'lùi; trả lại', pos:'chữ Hán'},
  {zh:'评', pinyin:'píng', hv:'bình', vi:'bình luận, đánh giá', pos:'chữ Hán'},
  {zh:'成', pinyin:'chéng', hv:'thành', vi:'thành, trở thành', pos:'chữ Hán'},
  {zh:'胎', pinyin:'tāi', hv:'thai', vi:'bào thai; lốp, săm xe', pos:'chữ Hán'},
  {zh:'隔', pinyin:'gé', hv:'cách', vi:'ngăn cách', pos:'chữ Hán'},
  {zh:'壁', pinyin:'bì', hv:'bích', vi:'vách, tường', pos:'chữ Hán'},
  {zh:'差', pinyin:'chà', hv:'sai', vi:'kém, thiếu; (chāi) công tác', pos:'chữ Hán'},
  {zh:'活', pinyin:'huó', hv:'hoạt', vi:'sống; linh hoạt', pos:'chữ Hán'},
  {zh:'麻', pinyin:'má', hv:'ma', vi:'cây gai; tê (麻烦: phiền)', pos:'chữ Hán'},
  {zh:'烦', pinyin:'fán', hv:'phiền', vi:'phiền, bực', pos:'chữ Hán'},
  {zh:'其', pinyin:'qí', hv:'kỳ', vi:'của nó, đó (其实: thật ra)', pos:'chữ Hán'},
  {zh:'特', pinyin:'tè', hv:'đặc', vi:'đặc biệt', pos:'chữ Hán'},
  {zh:'散', pinyin:'sàn', hv:'tán', vi:'tản ra, chia lìa', pos:'chữ Hán'},
  {zh:'拒', pinyin:'jù', hv:'cự', vi:'từ chối, cự tuyệt', pos:'chữ Hán'},
  {zh:'绝', pinyin:'jué', hv:'tuyệt', vi:'dứt, tuyệt đối', pos:'chữ Hán'},
  {zh:'貌', pinyin:'mào', hv:'mạo', vi:'dáng vẻ (礼貌: lễ phép)', pos:'chữ Hán'},
  {zh:'尊', pinyin:'zūn', hv:'tôn', vi:'tôn kính', pos:'chữ Hán'},

  /* ---------- Tính chất · cảm xúc ---------- */
  {zh:'幸', pinyin:'xìng', hv:'hạnh', vi:'may mắn, hạnh phúc', pos:'chữ Hán'},
  {zh:'福', pinyin:'fú', hv:'phúc', vi:'phúc, may mắn', pos:'chữ Hán'},
  {zh:'情', pinyin:'qíng', hv:'tình', vi:'tình cảm, tình hình', pos:'chữ Hán'},
  {zh:'心', pinyin:'xīn', hv:'tâm', vi:'tim; lòng', pos:'chữ Hán'},
  {zh:'觉', pinyin:'jué', hv:'giác', vi:'cảm thấy; (jiào) giấc ngủ', pos:'chữ Hán'},
  {zh:'错', pinyin:'cuò', hv:'thác', vi:'sai; (不错) khá tốt', pos:'chữ Hán'},
  {zh:'宜', pinyin:'yí', hv:'nghi', vi:'thích hợp (便宜: rẻ)', pos:'chữ Hán'},
  {zh:'附', pinyin:'fù', hv:'phụ', vi:'kèm theo, gần (附近)', pos:'chữ Hán'},
  {zh:'对', pinyin:'duì', hv:'đối', vi:'đúng; đối với', pos:'chữ Hán'},
  {zh:'虽', pinyin:'suī', hv:'tuy', vi:'tuy, mặc dù', pos:'chữ Hán'},
  {zh:'然', pinyin:'rán', hv:'nhiên', vi:'như vậy, thế nhưng', pos:'chữ Hán'},
  {zh:'因', pinyin:'yīn', hv:'nhân', vi:'nguyên nhân, bởi vì', pos:'chữ Hán'},
  {zh:'为', pinyin:'wèi', hv:'vị', vi:'vì, cho; (wéi) làm', pos:'chữ Hán'},
  {zh:'如', pinyin:'rú', hv:'như', vi:'như, giống như', pos:'chữ Hán'},
  {zh:'什', pinyin:'shén', hv:'thập', vi:'cái gì (什么)', pos:'chữ Hán'},
  {zh:'么', pinyin:'me', hv:'ma', vi:'trợ từ nghi vấn (什么, 怎么)', pos:'chữ Hán'},
  {zh:'怎', pinyin:'zěn', hv:'chẩm', vi:'thế nào (怎么)', pos:'chữ Hán'},
  {zh:'吧', pinyin:'ba', hv:'ba', vi:'trợ từ đề nghị: … nhé', pos:'chữ Hán'},
  {zh:'烟', pinyin:'yān', hv:'yên', vi:'khói; thuốc lá', pos:'chữ Hán'},
  {zh:'明', pinyin:'míng', hv:'minh', vi:'sáng, rõ; ngày mai (明天)', pos:'chữ Hán'},
  {zh:'于', pinyin:'yú', hv:'vu', vi:'ở, tại, đối với (văn viết)', pos:'chữ Hán'},
  {zh:'住', pinyin:'zhù', hv:'trú', vi:'ở, cư trú; dừng lại', pos:'chữ Hán'},
  {zh:'同', pinyin:'tóng', hv:'đồng', vi:'giống nhau, cùng', pos:'chữ Hán'},
  {zh:'帽', pinyin:'mào', hv:'mạo', vi:'mũ (trong 帽子)', pos:'chữ Hán'},
  {zh:'汽', pinyin:'qì', hv:'khí', vi:'hơi nước (trong 汽车)', pos:'chữ Hán'},
  {zh:'另', pinyin:'lìng', hv:'lánh', vi:'khác, cái kia', pos:'chữ Hán'},
  {zh:'筷', pinyin:'kuài', hv:'khoái', vi:'đũa (trong 筷子)', pos:'chữ Hán'},
  {zh:'套', pinyin:'tào', hv:'sáo', vi:'bộ; bọc ngoài (trong 外套)', pos:'chữ Hán'},
  {zh:'架', pinyin:'jià', hv:'giá', vi:'cái giá, kệ (trong 书架)', pos:'chữ Hán'},

  /* ---------- Bổ sung vòng hai: chữ lẻ trong câu ví dụ của khoá học ----------
     Đo độ phủ thấy 475 chữ Hán bấm vào không ra gì. Phần lớn là chữ rất thông
     dụng — 哪, 报, 通, 无, 爱 — chỉ vì giáo trình dạy theo TỪ nên chữ lẻ không
     bao giờ thành mục từ. Với người Việt thì âm Hán–Việt của từng chữ là chỗ
     bám quý nhất, nên thiếu chữ lẻ là thiếu đúng thứ đáng giá. */
  {zh:'哪', pinyin:'nǎ', hv:'na', vi:'nào; đâu', pos:'chữ Hán'},
  {zh:'报', pinyin:'bào', hv:'báo', vi:'báo cáo; tờ báo; ghi danh', pos:'chữ Hán'},
  {zh:'持', pinyin:'chí', hv:'trì', vi:'cầm, giữ; duy trì', pos:'chữ Hán'},
  {zh:'备', pinyin:'bèi', hv:'bị', vi:'chuẩn bị; đầy đủ', pos:'chữ Hán'},
  {zh:'通', pinyin:'tōng', hv:'thông', vi:'thông suốt; qua; thông báo', pos:'chữ Hán'},
  {zh:'啊', pinyin:'a', hv:'a', vi:'(trợ từ cuối câu, làm giọng mềm đi)', pos:'chữ Hán'},
  {zh:'坚', pinyin:'jiān', hv:'kiên', vi:'vững, bền; kiên trì', pos:'chữ Hán'},
  {zh:'非', pinyin:'fēi', hv:'phi', vi:'không phải; châu Phi', pos:'chữ Hán'},
  {zh:'材', pinyin:'cái', hv:'tài', vi:'vật liệu; tài năng', pos:'chữ Hán'},
  {zh:'平', pinyin:'píng', hv:'bình', vi:'bằng phẳng; yên bình', pos:'chữ Hán'},
  {zh:'化', pinyin:'huà', hv:'hoá', vi:'biến đổi; hậu tố «-hoá»', pos:'chữ Hán'},
  {zh:'无', pinyin:'wú', hv:'vô', vi:'không có', pos:'chữ Hán'},
  {zh:'免', pinyin:'miǎn', hv:'miễn', vi:'miễn, khỏi phải', pos:'chữ Hán'},
  {zh:'与', pinyin:'yǔ', hv:'dữ', vi:'và; với (văn viết)', pos:'chữ Hán'},
  {zh:'文', pinyin:'wén', hv:'văn', vi:'chữ viết; văn hoá', pos:'chữ Hán'},
  {zh:'任', pinyin:'rèn', hv:'nhiệm', vi:'nhiệm vụ; mặc cho', pos:'chữ Hán'},
  {zh:'何', pinyin:'hé', hv:'hà', vi:'gì, sao (văn viết)', pos:'chữ Hán'},
  {zh:'必', pinyin:'bì', hv:'tất', vi:'ắt, nhất định', pos:'chữ Hán'},
  {zh:'旅', pinyin:'lǚ', hv:'lữ', vi:'đi xa, du lịch', pos:'chữ Hán'},
  {zh:'准', pinyin:'zhǔn', hv:'chuẩn', vi:'chuẩn xác; cho phép', pos:'chữ Hán'},
  {zh:'消', pinyin:'xiāo', hv:'tiêu', vi:'tiêu tan; tin tức', pos:'chữ Hán'},
  {zh:'聊', pinyin:'liáo', hv:'liêu', vi:'trò chuyện phiếm', pos:'chữ Hán'},
  {zh:'相', pinyin:'xiāng', hv:'tương', vi:'lẫn nhau; xem tướng', pos:'chữ Hán'},
  {zh:'害', pinyin:'hài', hv:'hại', vi:'làm hại; tai hại', pos:'chữ Hán'},
  {zh:'误', pinyin:'wù', hv:'ngộ', vi:'nhầm; nhỡ (tàu, xe)', pos:'chữ Hán'},
  {zh:'减', pinyin:'jiǎn', hv:'giảm', vi:'giảm, bớt', pos:'chữ Hán'},
  {zh:'该', pinyin:'gāi', hv:'cai', vi:'nên; cái đó', pos:'chữ Hán'},
  {zh:'责', pinyin:'zé', hv:'trách', vi:'trách nhiệm; trách mắng', pos:'chữ Hán'},
  {zh:'验', pinyin:'yàn', hv:'nghiệm', vi:'kiểm nghiệm, thử', pos:'chữ Hán'},
  {zh:'虚', pinyin:'xū', hv:'hư', vi:'rỗng, hư; khiêm tốn', pos:'chữ Hán'},
  {zh:'性', pinyin:'xìng', hv:'tính', vi:'tính chất; giới tính', pos:'chữ Hán'},
  {zh:'言', pinyin:'yán', hv:'ngôn', vi:'lời nói; ngôn ngữ', pos:'chữ Hán'},
  {zh:'独', pinyin:'dú', hv:'độc', vi:'một mình, riêng', pos:'chữ Hán'},
  {zh:'爱', pinyin:'ài', hv:'ái', vi:'yêu, thích', pos:'chữ Hán'},
  {zh:'婚', pinyin:'hūn', hv:'hôn', vi:'hôn nhân, cưới', pos:'chữ Hán'},
  {zh:'料', pinyin:'liào', hv:'liệu', vi:'vật liệu; liệu trước', pos:'chữ Hán'},
  {zh:'练', pinyin:'liàn', hv:'luyện', vi:'luyện tập', pos:'chữ Hán'},
  {zh:'预', pinyin:'yù', hv:'dự', vi:'trước, dự trước', pos:'chữ Hán'},
  {zh:'计', pinyin:'jì', hv:'kế', vi:'tính toán; kế hoạch', pos:'chữ Hán'},
  {zh:'怪', pinyin:'guài', hv:'quái', vi:'lạ lùng; trách', pos:'chữ Hán'},
  {zh:'调', pinyin:'tiáo', hv:'điều', vi:'điều chỉnh; đọc «diào» là chuyển đi, giọng điệu', pos:'chữ Hán'},
  {zh:'当', pinyin:'dāng', hv:'đương', vi:'làm, đảm nhận; vào lúc', pos:'chữ Hán'},
  {zh:'论', pinyin:'lùn', hv:'luận', vi:'bàn luận; lí luận', pos:'chữ Hán'},
  {zh:'效', pinyin:'xiào', hv:'hiệu', vi:'hiệu quả; noi theo', pos:'chữ Hán'},
  {zh:'位', pinyin:'wèi', hv:'vị', vi:'vị trí; (lượng từ lịch sự cho người)', pos:'chữ Hán'},
  {zh:'证', pinyin:'zhèng', hv:'chứng', vi:'chứng minh; giấy tờ', pos:'chữ Hán'},
  {zh:'毕', pinyin:'bì', hv:'tất', vi:'xong; tốt nghiệp', pos:'chữ Hán'},
  {zh:'流', pinyin:'liú', hv:'lưu', vi:'chảy; dòng, luồng', pos:'chữ Hán'},
  {zh:'环', pinyin:'huán', hv:'hoàn', vi:'vòng; môi trường', pos:'chữ Hán'},
  {zh:'据', pinyin:'jù', hv:'cứ', vi:'căn cứ; theo như', pos:'chữ Hán'},
  {zh:'向', pinyin:'xiàng', hv:'hướng', vi:'hướng về; phía', pos:'chữ Hán'},
  {zh:'乡', pinyin:'xiāng', hv:'hương', vi:'quê, làng', pos:'chữ Hán'},
  {zh:'清', pinyin:'qīng', hv:'thanh', vi:'trong; rõ ràng', pos:'chữ Hán'},
  {zh:'代', pinyin:'dài', hv:'đại', vi:'thay thế; thời đại', pos:'chữ Hán'},
  {zh:'女', pinyin:'nǚ', hv:'nữ', vi:'nữ, con gái', pos:'chữ Hán'},
  {zh:'介', pinyin:'jiè', hv:'giới', vi:'ở giữa, môi giới', pos:'chữ Hán'},
  {zh:'绍', pinyin:'shào', hv:'thiệu', vi:'nối tiếp — chủ yếu dùng trong 介绍 «giới thiệu»', pos:'chữ Hán'},
  {zh:'场', pinyin:'chǎng', hv:'trường', vi:'sân, chỗ; (lượng từ cho buổi)', pos:'chữ Hán'},
  {zh:'静', pinyin:'jìng', hv:'tĩnh', vi:'yên tĩnh', pos:'chữ Hán'},
  {zh:'温', pinyin:'wēn', hv:'ôn', vi:'ấm; ôn lại bài', pos:'chữ Hán'},
  {zh:'弃', pinyin:'qì', hv:'khí', vi:'vứt bỏ, từ bỏ', pos:'chữ Hán'},
  {zh:'健', pinyin:'jiàn', hv:'kiện', vi:'khoẻ mạnh', pos:'chữ Hán'},
  {zh:'助', pinyin:'zhù', hv:'trợ', vi:'giúp đỡ', pos:'chữ Hán'},
  {zh:'者', pinyin:'zhě', hv:'giả', vi:'người… (hậu tố: 记者 kí giả)', pos:'chữ Hán'},
  {zh:'死', pinyin:'sǐ', hv:'tử', vi:'chết; chết đi được (nhấn mạnh)', pos:'chữ Hán'},
  {zh:'极', pinyin:'jí', hv:'cực', vi:'cực, hết sức', pos:'chữ Hán'},
  {zh:'数', pinyin:'shù', hv:'số', vi:'số, con số; đọc «shǔ» là đếm', pos:'chữ Hán'},
  {zh:'延', pinyin:'yán', hv:'diên', vi:'kéo dài, hoãn', pos:'chữ Hán'},
  {zh:'甚', pinyin:'shèn', hv:'thậm', vi:'rất; thậm chí', pos:'chữ Hán'},
  {zh:'川', pinyin:'chuān', hv:'xuyên', vi:'sông; Tứ Xuyên', pos:'chữ Hán'},
  {zh:'受', pinyin:'shòu', hv:'thụ', vi:'nhận; chịu đựng', pos:'chữ Hán'},
  {zh:'底', pinyin:'dǐ', hv:'để', vi:'đáy; cuối (tháng, năm)', pos:'chữ Hán'},
  {zh:'千', pinyin:'qiān', hv:'thiên', vi:'nghìn', pos:'chữ Hán'},
  {zh:'及', pinyin:'jí', hv:'cập', vi:'và; kịp, đạt tới', pos:'chữ Hán'},
  {zh:'育', pinyin:'yù', hv:'dục', vi:'nuôi dạy, giáo dục', pos:'chữ Hán'},
  {zh:'翻', pinyin:'fān', hv:'phiên', vi:'lật; dịch (翻译)', pos:'chữ Hán'},
  {zh:'译', pinyin:'yì', hv:'dịch', vi:'dịch, phiên dịch', pos:'chữ Hán'},
  {zh:'具', pinyin:'jù', hv:'cụ', vi:'dụng cụ; có (具有)', pos:'chữ Hán'},
  {zh:'主', pinyin:'zhǔ', hv:'chủ', vi:'chủ; chính yếu', pos:'chữ Hán'},
  {zh:'推', pinyin:'tuī', hv:'thôi', vi:'đẩy; tiến cử, suy ra', pos:'chữ Hán'},
  {zh:'态', pinyin:'tài', hv:'thái', vi:'thái độ; trạng thái', pos:'chữ Hán'},
  {zh:'顾', pinyin:'gù', hv:'cố', vi:'trông nom; khách hàng', pos:'chữ Hán'},
  {zh:'境', pinyin:'jìng', hv:'cảnh', vi:'hoàn cảnh; biên giới', pos:'chữ Hán'},
  {zh:'选', pinyin:'xuǎn', hv:'tuyển', vi:'chọn, tuyển', pos:'chữ Hán'},
  {zh:'择', pinyin:'zé', hv:'trạch', vi:'lựa chọn', pos:'chữ Hán'},
  {zh:'设', pinyin:'shè', hv:'thiết', vi:'đặt, lập; thiết kế', pos:'chữ Hán'},
  {zh:'旦', pinyin:'dàn', hv:'đán', vi:'buổi sớm — 元旦 Tết dương lịch', pos:'chữ Hán'},
  {zh:'担', pinyin:'dān', hv:'đảm', vi:'gánh vác, đảm nhận', pos:'chữ Hán'},
  {zh:'距', pinyin:'jù', hv:'cự', vi:'cách, khoảng cách', pos:'chữ Hán'},
  {zh:'键', pinyin:'jiàn', hv:'kiện', vi:'phím; then chốt (关键)', pos:'chữ Hán'},
  {zh:'未', pinyin:'wèi', hv:'vị', vi:'chưa; tương lai', pos:'chữ Hán'},
  {zh:'品', pinyin:'pǐn', hv:'phẩm', vi:'đồ vật; phẩm chất', pos:'chữ Hán'},
  {zh:'村', pinyin:'cūn', hv:'thôn', vi:'làng, thôn', pos:'chữ Hán'},
  {zh:'施', pinyin:'shī', hv:'thi', vi:'thi hành, thực hiện', pos:'chữ Hán'},
  {zh:'迷', pinyin:'mí', hv:'mê', vi:'mê, say mê; lạc đường', pos:'chữ Hán'},
  {zh:'此', pinyin:'cǐ', hv:'thử', vi:'này, đây (văn viết)', pos:'chữ Hán'},
  {zh:'频', pinyin:'pín', hv:'tần', vi:'tần số; thường xuyên', pos:'chữ Hán'},
  {zh:'议', pinyin:'yì', hv:'nghị', vi:'bàn bạc, nghị luận', pos:'chữ Hán'},
  {zh:'度', pinyin:'dù', hv:'độ', vi:'độ, mức độ', pos:'chữ Hán'},
  {zh:'突', pinyin:'tū', hv:'đột', vi:'đột ngột; nhô ra', pos:'chữ Hán'},
  {zh:'声', pinyin:'shēng', hv:'thanh', vi:'tiếng, âm thanh', pos:'chữ Hán'},
  {zh:'赛', pinyin:'sài', hv:'tái', vi:'thi đấu', pos:'chữ Hán'},
  {zh:'印', pinyin:'yìn', hv:'ấn', vi:'in; con dấu; Ấn Độ', pos:'chữ Hán'},
  {zh:'象', pinyin:'xiàng', hv:'tượng', vi:'con voi; hình tượng', pos:'chữ Hán'},
  {zh:'史', pinyin:'shǐ', hv:'sử', vi:'lịch sử', pos:'chữ Hán'},
  {zh:'弟', pinyin:'dì', hv:'đệ', vi:'em trai', pos:'chữ Hán'},
  {zh:'慰', pinyin:'wèi', hv:'uỷ', vi:'an ủi', pos:'chữ Hán'},
  {zh:'康', pinyin:'kāng', hv:'khang', vi:'khoẻ mạnh, an khang', pos:'chữ Hán'},
  {zh:'咖', pinyin:'kā', hv:'ca', vi:'(phiên âm — trong 咖啡 cà phê)', pos:'chữ Hán'},
  {zh:'啡', pinyin:'fēi', hv:'phi', vi:'(phiên âm — trong 咖啡 cà phê)', pos:'chữ Hán'},
  {zh:'精', pinyin:'jīng', hv:'tinh', vi:'tinh tuý; tinh thần', pos:'chữ Hán'},
  {zh:'订', pinyin:'dìng', hv:'đính', vi:'đặt (chỗ, hàng); đính ước', pos:'chữ Hán'},
  {zh:'则', pinyin:'zé', hv:'tắc', vi:'quy tắc; thì (văn viết)', pos:'chữ Hán'},
  {zh:'观', pinyin:'guān', hv:'quan', vi:'xem, quan sát; quan điểm', pos:'chữ Hán'},
  {zh:'航', pinyin:'háng', hv:'hàng', vi:'đi thuyền, bay; hàng không', pos:'chữ Hán'},
  {zh:'默', pinyin:'mò', hv:'mặc', vi:'im lặng; thầm', pos:'chữ Hán'},
  {zh:'恐', pinyin:'kǒng', hv:'khủng', vi:'sợ; e rằng', pos:'chữ Hán'},
  {zh:'止', pinyin:'zhǐ', hv:'chỉ', vi:'dừng, ngừng', pos:'chữ Hán'},
  {zh:'竟', pinyin:'jìng', hv:'cánh', vi:'rốt cuộc; lại (ngoài dự liệu)', pos:'chữ Hán'},
  {zh:'敢', pinyin:'gǎn', hv:'cảm', vi:'dám', pos:'chữ Hán'},
  {zh:'展', pinyin:'zhǎn', hv:'triển', vi:'mở ra; triển lãm', pos:'chữ Hán'},
  {zh:'式', pinyin:'shì', hv:'thức', vi:'kiểu, hình thức', pos:'chữ Hán'},
  {zh:'购', pinyin:'gòu', hv:'cấu', vi:'mua sắm', pos:'chữ Hán'},
  {zh:'络', pinyin:'luò', hv:'lạc', vi:'mạng lưới — 网络 mạng', pos:'chữ Hán'},
  {zh:'趣', pinyin:'qù', hv:'thú', vi:'thú vị; hứng thú', pos:'chữ Hán'},
  {zh:'演', pinyin:'yǎn', hv:'diễn', vi:'diễn, biểu diễn', pos:'chữ Hán'},
  {zh:'账', pinyin:'zhàng', hv:'trướng', vi:'tài khoản; sổ nợ', pos:'chữ Hán'},
  {zh:'折', pinyin:'zhé', hv:'chiết', vi:'gấp; chiết khấu', pos:'chữ Hán'},
  {zh:'污', pinyin:'wū', hv:'ô', vi:'bẩn, ô nhiễm', pos:'chữ Hán'},
  {zh:'染', pinyin:'rǎn', hv:'nhiễm', vi:'nhuộm; lây nhiễm', pos:'chữ Hán'},
  {zh:'资', pinyin:'zī', hv:'tư', vi:'vốn, tài nguyên; tư liệu', pos:'chữ Hán'},
  {zh:'禁', pinyin:'jìn', hv:'cấm', vi:'cấm', pos:'chữ Hán'},
  {zh:'垃', pinyin:'lā', hv:'lạp', vi:'(trong 垃圾 rác)', pos:'chữ Hán'},
  {zh:'圾', pinyin:'jī', hv:'ngập', vi:'(trong 垃圾 rác)', pos:'chữ Hán'},
  {zh:'保', pinyin:'bǎo', hv:'bảo', vi:'giữ gìn, bảo vệ', pos:'chữ Hán'},
  {zh:'质', pinyin:'zhì', hv:'chất', vi:'chất lượng; bản chất', pos:'chữ Hán'},
  {zh:'标', pinyin:'biāo', hv:'tiêu', vi:'dấu hiệu; mục tiêu', pos:'chữ Hán'},
  {zh:'联', pinyin:'lián', hv:'liên', vi:'liên kết, nối', pos:'chữ Hán'},
  {zh:'母', pinyin:'mǔ', hv:'mẫu', vi:'mẹ; cái gốc', pos:'chữ Hán'},
  {zh:'亲', pinyin:'qīn', hv:'thân', vi:'thân thiết; cha mẹ', pos:'chữ Hán'},
  {zh:'凡', pinyin:'fán', hv:'phàm', vi:'phàm là; bình thường', pos:'chữ Hán'},
  {zh:'陪', pinyin:'péi', hv:'bồi', vi:'đi cùng, bầu bạn', pos:'chữ Hán'},
  {zh:'尽', pinyin:'jìn', hv:'tận', vi:'hết, tận; dốc sức', pos:'chữ Hán'},
  {zh:'仍', pinyin:'réng', hv:'nhưng', vi:'vẫn, vẫn còn', pos:'chữ Hán'},
  {zh:'握', pinyin:'wò', hv:'ác', vi:'nắm, cầm', pos:'chữ Hán'},
  {zh:'端', pinyin:'duān', hv:'đoan', vi:'đầu mối; bưng', pos:'chữ Hán'},
  {zh:'淡', pinyin:'dàn', hv:'đạm', vi:'nhạt; thờ ơ', pos:'chữ Hán'},
  {zh:'眠', pinyin:'mián', hv:'miên', vi:'ngủ — 失眠 mất ngủ', pos:'chữ Hán'},
  {zh:'愿', pinyin:'yuàn', hv:'nguyện', vi:'nguyện, muốn', pos:'chữ Hán'},
  {zh:'冲', pinyin:'chōng', hv:'xung', vi:'xông lên; pha (nước)', pos:'chữ Hán'},
  {zh:'限', pinyin:'xiàn', hv:'hạn', vi:'giới hạn, hạn chế', pos:'chữ Hán'},
  {zh:'创', pinyin:'chuàng', hv:'sáng', vi:'sáng tạo, lập nên', pos:'chữ Hán'},
  {zh:'立', pinyin:'lì', hv:'lập', vi:'đứng; lập nên', pos:'chữ Hán'},
  {zh:'优', pinyin:'yōu', hv:'ưu', vi:'ưu tú, hơn hẳn', pos:'chữ Hán'},
  {zh:'粤', pinyin:'yuè', hv:'việt', vi:'Quảng Đông (tên gọi tắt)', pos:'chữ Hán'},
  {zh:'社', pinyin:'shè', hv:'xã', vi:'xã hội; hội, đoàn', pos:'chữ Hán'},
  {zh:'摄', pinyin:'shè', hv:'nhiếp', vi:'chụp, quay phim', pos:'chữ Hán'},
  {zh:'艺', pinyin:'yì', hv:'nghệ', vi:'nghệ thuật, tài nghệ', pos:'chữ Hán'},
  {zh:'唱', pinyin:'chàng', hv:'xướng', vi:'hát', pos:'chữ Hán'},
  {zh:'篮', pinyin:'lán', hv:'lam', vi:'cái rổ — 篮球 bóng rổ', pos:'chữ Hán'},
  {zh:'姐', pinyin:'jiě', hv:'tỉ', vi:'chị', pos:'chữ Hán'},
  {zh:'冬', pinyin:'dōng', hv:'đông', vi:'mùa đông', pos:'chữ Hán'},
  {zh:'季', pinyin:'jì', hv:'quý', vi:'mùa, quý', pos:'chữ Hán'},
  {zh:'概', pinyin:'gài', hv:'khái', vi:'đại khái; khái quát', pos:'chữ Hán'},
  {zh:'划', pinyin:'huà', hv:'hoạch', vi:'vạch ra, hoạch định', pos:'chữ Hán'},
  {zh:'聪', pinyin:'cōng', hv:'thông', vi:'thông minh', pos:'chữ Hán'},
  {zh:'继', pinyin:'jì', hv:'kế', vi:'nối tiếp, kế tục', pos:'chữ Hán'},
  {zh:'续', pinyin:'xù', hv:'tục', vi:'tiếp tục', pos:'chữ Hán'},
  {zh:'处', pinyin:'chù', hv:'xứ', vi:'nơi, chỗ; đọc «chǔ» là xử lí', pos:'chữ Hán'},
  {zh:'景', pinyin:'jǐng', hv:'cảnh', vi:'cảnh vật, phong cảnh', pos:'chữ Hán'},
  {zh:'锻', pinyin:'duàn', hv:'đoán', vi:'rèn — 锻炼 rèn luyện', pos:'chữ Hán'},
  {zh:'炼', pinyin:'liàn', hv:'luyện', vi:'luyện, tôi luyện', pos:'chữ Hán'},
  {zh:'压', pinyin:'yā', hv:'áp', vi:'ép, đè; áp lực', pos:'chữ Hán'},
  {zh:'应', pinyin:'yīng', hv:'ưng', vi:'nên; đọc «yìng» là đáp ứng', pos:'chữ Hán'},
  {zh:'规', pinyin:'guī', hv:'quy', vi:'quy tắc, quy định', pos:'chữ Hán'},
  {zh:'律', pinyin:'lǜ', hv:'luật', vi:'luật, quy luật', pos:'chữ Hán'},
  {zh:'即', pinyin:'jí', hv:'tức', vi:'tức là; ngay lập tức', pos:'chữ Hán'},
  {zh:'否', pinyin:'fǒu', hv:'phủ', vi:'không, phủ định', pos:'chữ Hán'},
  {zh:'座', pinyin:'zuò', hv:'toạ', vi:'chỗ ngồi; (lượng từ cho toà nhà, núi)', pos:'chữ Hán'},
  {zh:'待', pinyin:'dài', hv:'đãi', vi:'đối đãi; chờ', pos:'chữ Hán'},
  {zh:'碎', pinyin:'suì', hv:'toái', vi:'vỡ vụn', pos:'chữ Hán'},
  {zh:'歉', pinyin:'qiàn', hv:'khiểm', vi:'áy náy — 抱歉 xin lỗi', pos:'chữ Hán'},
  {zh:'惊', pinyin:'jīng', hv:'kinh', vi:'kinh ngạc, giật mình', pos:'chữ Hán'},
  {zh:'秘', pinyin:'mì', hv:'bí', vi:'bí mật', pos:'chữ Hán'},
  {zh:'隐', pinyin:'yǐn', hv:'ẩn', vi:'ẩn giấu; riêng tư', pos:'chữ Hán'},
  {zh:'亏', pinyin:'kuī', hv:'khuy', vi:'thiệt, lỗ; may mà', pos:'chữ Hán'},
  {zh:'承', pinyin:'chéng', hv:'thừa', vi:'nhận lấy, kế thừa', pos:'chữ Hán'},
  {zh:'讨', pinyin:'tǎo', hv:'thảo', vi:'bàn bạc; xin', pos:'chữ Hán'},
  {zh:'入', pinyin:'rù', hv:'nhập', vi:'vào, nhập', pos:'chữ Hán'},
  {zh:'营', pinyin:'yíng', hv:'doanh', vi:'kinh doanh; doanh trại', pos:'chữ Hán'},
  {zh:'加', pinyin:'jiā', hv:'gia', vi:'thêm, cộng', pos:'chữ Hán'},
  {zh:'沟', pinyin:'gōu', hv:'câu', vi:'rãnh — 沟通 trao đổi, giao tiếp', pos:'chữ Hán'},
  {zh:'适', pinyin:'shì', hv:'thích', vi:'thích hợp', pos:'chữ Hán'},
  {zh:'建', pinyin:'jiàn', hv:'kiến', vi:'xây dựng; kiến nghị', pos:'chữ Hán'},
  {zh:'尾', pinyin:'wěi', hv:'vĩ', vi:'đuôi; cuối', pos:'chữ Hán'},
  {zh:'泪', pinyin:'lèi', hv:'lệ', vi:'nước mắt', pos:'chữ Hán'},
  {zh:'抱', pinyin:'bào', hv:'bão', vi:'ôm; ôm giữ (ý nghĩ)', pos:'chữ Hán'},
  {zh:'约', pinyin:'yuē', hv:'ước', vi:'hẹn; khoảng chừng', pos:'chữ Hán'},
  {zh:'源', pinyin:'yuán', hv:'nguyên', vi:'nguồn', pos:'chữ Hán'},
  {zh:'供', pinyin:'gōng', hv:'cung', vi:'cung cấp', pos:'chữ Hán'},
  {zh:'倡', pinyin:'chàng', hv:'xướng', vi:'đề xướng, khởi xướng', pos:'chữ Hán'},
  {zh:'求', pinyin:'qiú', hv:'cầu', vi:'cầu, xin; yêu cầu', pos:'chữ Hán'},
  {zh:'类', pinyin:'lèi', hv:'loại', vi:'loại, thứ', pos:'chữ Hán'},
  {zh:'控', pinyin:'kòng', hv:'khống', vi:'khống chế, điều khiển', pos:'chữ Hán'},
  {zh:'曾', pinyin:'céng', hv:'tằng', vi:'đã từng', pos:'chữ Hán'},
  {zh:'获', pinyin:'huò', hv:'hoạch', vi:'thu được, giành được', pos:'chữ Hán'},
  {zh:'目', pinyin:'mù', hv:'mục', vi:'mắt; mục, đề mục', pos:'chữ Hán'},
  {zh:'腾', pinyin:'téng', hv:'đằng', vi:'bốc lên, nhảy vọt', pos:'chữ Hán'},
  {zh:'伴', pinyin:'bàn', hv:'bạn', vi:'bạn đồng hành, đi cùng', pos:'chữ Hán'},
  {zh:'珍', pinyin:'zhēn', hv:'trân', vi:'quý báu; trân trọng', pos:'chữ Hán'},
  {zh:'父', pinyin:'fù', hv:'phụ', vi:'cha', pos:'chữ Hán'},
  {zh:'恨', pinyin:'hèn', hv:'hận', vi:'hận, ghét', pos:'chữ Hán'},
  {zh:'争', pinyin:'zhēng', hv:'tranh', vi:'tranh giành, tranh cãi', pos:'chữ Hán'},
  {zh:'许', pinyin:'xǔ', hv:'hứa', vi:'cho phép; có lẽ (也许)', pos:'chữ Hán'},
  {zh:'妥', pinyin:'tuǒ', hv:'thoả', vi:'thoả đáng, ổn thoả', pos:'chữ Hán'},
  {zh:'协', pinyin:'xié', hv:'hiệp', vi:'hiệp lực, phối hợp', pos:'chữ Hán'},
  {zh:'功', pinyin:'gōng', hv:'công', vi:'công lao; thành công', pos:'chữ Hán'},
  {zh:'积', pinyin:'jī', hv:'tích', vi:'tích luỹ; tích cực', pos:'chữ Hán'},
  {zh:'委', pinyin:'wěi', hv:'uỷ', vi:'uỷ thác; uỷ ban', pos:'chữ Hán'},
  {zh:'屈', pinyin:'qū', hv:'khuất', vi:'cong, khuất phục; oan ức', pos:'chữ Hán'},
  {zh:'宁', pinyin:'nìng', hv:'ninh', vi:'thà rằng; đọc «níng» là yên ổn', pos:'chữ Hán'},
  {zh:'罪', pinyin:'zuì', hv:'tội', vi:'tội, tội lỗi', pos:'chữ Hán'},
  {zh:'足', pinyin:'zú', hv:'túc', vi:'chân; đủ', pos:'chữ Hán'},
  {zh:'率', pinyin:'lǜ', hv:'suất', vi:'tỉ lệ; đọc «shuài» là dẫn dắt', pos:'chữ Hán'},
  {zh:'界', pinyin:'jiè', hv:'giới', vi:'ranh giới; giới (thế giới)', pos:'chữ Hán'},
  {zh:'拉', pinyin:'lā', hv:'lạp', vi:'kéo', pos:'chữ Hán'},
  {zh:'利', pinyin:'lì', hv:'lợi', vi:'lợi ích; sắc bén', pos:'chữ Hán'},
  {zh:'恰', pinyin:'qià', hv:'kháp', vi:'vừa vặn, vừa đúng', pos:'chữ Hán'},
  {zh:'职', pinyin:'zhí', hv:'chức', vi:'chức vụ, nghề nghiệp', pos:'chữ Hán'},
  {zh:'奏', pinyin:'zòu', hv:'tấu', vi:'tấu nhạc; nhịp (节奏)', pos:'chữ Hán'},
  {zh:'虑', pinyin:'lǜ', hv:'lự', vi:'lo nghĩ, cân nhắc', pos:'chữ Hán'},
  {zh:'组', pinyin:'zǔ', hv:'tổ', vi:'tổ, nhóm; tổ chức', pos:'chữ Hán'},
  {zh:'掌', pinyin:'zhǎng', hv:'chưởng', vi:'lòng bàn tay; nắm giữ', pos:'chữ Hán'},
  {zh:'念', pinyin:'niàn', hv:'niệm', vi:'nhớ, tưởng; đọc lên', pos:'chữ Hán'},
  {zh:'氛', pinyin:'fēn', hv:'phân', vi:'không khí (气氛)', pos:'chữ Hán'},
  {zh:'炸', pinyin:'zhá', hv:'tạc', vi:'rán; đọc «zhà» là nổ', pos:'chữ Hán'},
  {zh:'失', pinyin:'shī', hv:'thất', vi:'mất; thất bại', pos:'chữ Hán'},
  {zh:'绪', pinyin:'xù', hv:'tự', vi:'mối, đầu mối — 情绪 tâm trạng', pos:'chữ Hán'},
  {zh:'整', pinyin:'zhěng', hv:'chỉnh', vi:'nguyên vẹn; chỉnh đốn', pos:'chữ Hán'},
  {zh:'汇', pinyin:'huì', hv:'hối', vi:'tụ lại; chuyển tiền; từ vựng', pos:'chữ Hán'},
  {zh:'各', pinyin:'gè', hv:'các', vi:'mỗi, các', pos:'chữ Hán'},
  {zh:'投', pinyin:'tóu', hv:'đầu', vi:'ném; đầu tư', pos:'chữ Hán'},
  {zh:'善', pinyin:'shàn', hv:'thiện', vi:'tốt lành; giỏi về', pos:'chữ Hán'},
  {zh:'鉴', pinyin:'jiàn', hv:'giám', vi:'soi xét, tham khảo', pos:'chữ Hán'},
  {zh:'须', pinyin:'xū', hv:'tu', vi:'phải, cần — 必须', pos:'chữ Hán'},
  {zh:'孔', pinyin:'kǒng', hv:'khổng', vi:'lỗ; họ Khổng', pos:'chữ Hán'},
  {zh:'著', pinyin:'zhù', hv:'trứ', vi:'trứ danh; soạn sách', pos:'chữ Hán'},
  {zh:'伤', pinyin:'shāng', hv:'thương', vi:'vết thương; tổn thương', pos:'chữ Hán'},
  {zh:'岗', pinyin:'gǎng', hv:'cương', vi:'vị trí làm việc, cương vị', pos:'chữ Hán'},
  {zh:'擅', pinyin:'shàn', hv:'thiện', vi:'giỏi về; tự tiện', pos:'chữ Hán'},
  {zh:'造', pinyin:'zào', hv:'tạo', vi:'tạo ra, chế tạo', pos:'chữ Hán'},
  {zh:'专', pinyin:'zhuān', hv:'chuyên', vi:'chuyên, chuyên môn', pos:'chữ Hán'},
  {zh:'况', pinyin:'kuàng', hv:'huống', vi:'tình huống; huống chi', pos:'chữ Hán'},
  {zh:'宠', pinyin:'chǒng', hv:'sủng', vi:'cưng chiều — 宠物 thú cưng', pos:'chữ Hán'},
  {zh:'诚', pinyin:'chéng', hv:'thành', vi:'thành thật', pos:'chữ Hán'},
  {zh:'固', pinyin:'gù', hv:'cố', vi:'vững chắc; cố nhiên', pos:'chữ Hán'},
  {zh:'培', pinyin:'péi', hv:'bồi', vi:'vun trồng, bồi dưỡng', pos:'chữ Hán'},
  {zh:'罢', pinyin:'bà', hv:'bãi', vi:'thôi, bãi bỏ', pos:'chữ Hán'},
  {zh:'谦', pinyin:'qiān', hv:'khiêm', vi:'khiêm tốn', pos:'chữ Hán'},
  {zh:'彩', pinyin:'cǎi', hv:'thái', vi:'màu sắc; rực rỡ', pos:'chữ Hán'},
  {zh:'熬', pinyin:'áo', hv:'ngao', vi:'ninh, sắc; thức khuya chịu đựng', pos:'chữ Hán'},
  {zh:'际', pinyin:'jì', hv:'tế', vi:'giữa, lúc; quốc tế', pos:'chữ Hán'},
  {zh:'束', pinyin:'shù', hv:'thúc', vi:'bó; ràng buộc; kết thúc', pos:'chữ Hán'},
  {zh:'程', pinyin:'chéng', hv:'trình', vi:'chặng, trình tự; công trình', pos:'chữ Hán'},
  {zh:'志', pinyin:'zhì', hv:'chí', vi:'chí hướng; tạp chí', pos:'chữ Hán'},
  {zh:'归', pinyin:'guī', hv:'quy', vi:'trở về, quy về', pos:'chữ Hán'},
  {zh:'孤', pinyin:'gū', hv:'cô', vi:'cô đơn, lẻ loi', pos:'chữ Hán'},
  {zh:'梦', pinyin:'mèng', hv:'mộng', vi:'giấc mơ', pos:'chữ Hán'},
  {zh:'孙', pinyin:'sūn', hv:'tôn', vi:'cháu; họ Tôn', pos:'chữ Hán'},
  {zh:'岂', pinyin:'qǐ', hv:'khởi', vi:'há lẽ nào (văn viết)', pos:'chữ Hán'},
  {zh:'制', pinyin:'zhì', hv:'chế', vi:'chế tạo; chế độ', pos:'chữ Hán'},
  {zh:'谈', pinyin:'tán', hv:'đàm', vi:'nói chuyện, đàm phán', pos:'chữ Hán'},
  {zh:'欣', pinyin:'xīn', hv:'hân', vi:'vui mừng — 欣赏 thưởng thức', pos:'chữ Hán'},
  {zh:'英', pinyin:'yīng', hv:'anh', vi:'nước Anh; tinh hoa', pos:'chữ Hán'},
  {zh:'低', pinyin:'dī', hv:'đê', vi:'thấp; cúi xuống', pos:'chữ Hán'},
  {zh:'杂', pinyin:'zá', hv:'tạp', vi:'lộn xộn, tạp', pos:'chữ Hán'},
  {zh:'贺', pinyin:'hè', hv:'hạ', vi:'chúc mừng', pos:'chữ Hán'},
  {zh:'奇', pinyin:'qí', hv:'kì', vi:'lạ lùng, kì lạ', pos:'chữ Hán'},
  {zh:'偶', pinyin:'ǒu', hv:'ngẫu', vi:'tình cờ; đôi, chẵn', pos:'chữ Hán'},
  {zh:'尔', pinyin:'ěr', hv:'nhĩ', vi:'(phiên âm); ngươi (văn cổ)', pos:'chữ Hán'},
  {zh:'肥', pinyin:'féi', hv:'phì', vi:'béo, màu mỡ', pos:'chữ Hán'},
  {zh:'或', pinyin:'huò', hv:'hoặc', vi:'hoặc, hay là', pos:'chữ Hán'},
  {zh:'遇', pinyin:'yù', hv:'ngộ', vi:'gặp; đãi ngộ', pos:'chữ Hán'},
  {zh:'困', pinyin:'kùn', hv:'khốn', vi:'khó khăn; buồn ngủ', pos:'chữ Hán'},
  {zh:'佩', pinyin:'pèi', hv:'bội', vi:'đeo; khâm phục', pos:'chữ Hán'},
  {zh:'神', pinyin:'shén', hv:'thần', vi:'thần; tinh thần', pos:'chữ Hán'},
  {zh:'显', pinyin:'xiǎn', hv:'hiển', vi:'rõ ràng, hiện ra', pos:'chữ Hán'},
  {zh:'众', pinyin:'zhòng', hv:'chúng', vi:'đông người, quần chúng', pos:'chữ Hán'},
  {zh:'举', pinyin:'jǔ', hv:'cử', vi:'giơ lên; nêu ra; cử hành', pos:'chữ Hán'},
  {zh:'脾', pinyin:'pí', hv:'tì', vi:'lá lách — 脾气 tính khí', pos:'chữ Hán'},
  {zh:'幽', pinyin:'yōu', hv:'u', vi:'thâm u; 幽默 hài hước', pos:'chữ Hán'},
  {zh:'瞒', pinyin:'mán', hv:'man', vi:'giấu giếm', pos:'chữ Hán'},
  {zh:'坦', pinyin:'tǎn', hv:'thản', vi:'bằng phẳng; thẳng thắn', pos:'chữ Hán'},
  {zh:'邀', pinyin:'yāo', hv:'yêu', vi:'mời', pos:'chữ Hán'},
  {zh:'截', pinyin:'jié', hv:'tiệt', vi:'cắt đứt; đến hạn', pos:'chữ Hán'},
  {zh:'粗', pinyin:'cū', hv:'thô', vi:'thô, to; cẩu thả', pos:'chữ Hán'},
  {zh:'省', pinyin:'shěng', hv:'tỉnh', vi:'tỉnh; tiết kiệm', pos:'chữ Hán'},
  {zh:'科', pinyin:'kē', hv:'khoa', vi:'khoa, ngành; khoa học', pos:'chữ Hán'},
  {zh:'济', pinyin:'jì', hv:'tế', vi:'cứu giúp — 经济 kinh tế', pos:'chữ Hán'},
  {zh:'销', pinyin:'xiāo', hv:'tiêu', vi:'bán ra, tiêu thụ', pos:'chữ Hán'},
  {zh:'厅', pinyin:'tīng', hv:'sảnh', vi:'gian lớn, sảnh', pos:'chữ Hán'},
  {zh:'齐', pinyin:'qí', hv:'tề', vi:'đều, ngay ngắn; đầy đủ', pos:'chữ Hán'},
  {zh:'押', pinyin:'yā', hv:'áp', vi:'đặt cọc; áp giải', pos:'chữ Hán'},
  {zh:'款', pinyin:'kuǎn', hv:'khoản', vi:'khoản tiền; kiểu dáng', pos:'chữ Hán'},
  {zh:'厉', pinyin:'lì', hv:'lệ', vi:'nghiêm khắc; 厉害 ghê gớm', pos:'chữ Hán'},
  {zh:'恢', pinyin:'huī', hv:'khôi', vi:'khôi phục', pos:'chữ Hán'},
  {zh:'荐', pinyin:'jiàn', hv:'tiến', vi:'tiến cử, giới thiệu', pos:'chữ Hán'},
  {zh:'塑', pinyin:'sù', hv:'tố', vi:'nặn, tạo hình; nhựa', pos:'chữ Hán'},
  {zh:'政', pinyin:'zhèng', hv:'chính', vi:'chính trị, chính quyền', pos:'chữ Hán'},
  {zh:'府', pinyin:'fǔ', hv:'phủ', vi:'phủ, cơ quan — 政府 chính phủ', pos:'chữ Hán'},
  {zh:'确', pinyin:'què', hv:'xác', vi:'xác thực, chắc chắn', pos:'chữ Hán'},
  {zh:'虎', pinyin:'hǔ', hv:'hổ', vi:'con hổ', pos:'chữ Hán'},
  {zh:'零', pinyin:'líng', hv:'linh', vi:'số không; lẻ', pos:'chữ Hán'},
  {zh:'骤', pinyin:'zhòu', hv:'sậu', vi:'đột ngột — 步骤 bước, trình tự', pos:'chữ Hán'},
  {zh:'怀', pinyin:'huái', hv:'hoài', vi:'ôm ấp trong lòng; nhớ', pos:'chữ Hán'},
  {zh:'疑', pinyin:'yí', hv:'nghi', vi:'nghi ngờ', pos:'chữ Hán'},
  {zh:'毫', pinyin:'háo', hv:'hào', vi:'mảy may — 毫不 chẳng chút nào', pos:'chữ Hán'},
  {zh:'监', pinyin:'jiān', hv:'giám', vi:'giám sát', pos:'chữ Hán'},
  {zh:'撒', pinyin:'sā', hv:'tát', vi:'buông ra, rắc — 撒谎 nói dối', pos:'chữ Hán'},
  {zh:'谎', pinyin:'huǎng', hv:'hoang', vi:'lời nói dối', pos:'chữ Hán'},
  {zh:'冤', pinyin:'yuān', hv:'oan', vi:'oan ức', pos:'chữ Hán'},
  {zh:'枉', pinyin:'wǎng', hv:'uổng', vi:'oan uổng; uổng công', pos:'chữ Hán'},
  {zh:'遗', pinyin:'yí', hv:'di', vi:'để lại, sót lại', pos:'chữ Hán'},
  {zh:'憾', pinyin:'hàn', hv:'hám', vi:'tiếc nuối — 遗憾 đáng tiếc', pos:'chữ Hán'},
  {zh:'挑', pinyin:'tiāo', hv:'khiêu', vi:'chọn; gánh; đọc «tiǎo» là khêu gợi', pos:'chữ Hán'},
  {zh:'战', pinyin:'zhàn', hv:'chiến', vi:'chiến đấu, chiến tranh', pos:'chữ Hán'},
  {zh:'怨', pinyin:'yuàn', hv:'oán', vi:'oán trách', pos:'chữ Hán'},
  {zh:'唠', pinyin:'láo', hv:'lao', vi:'lải nhải — 唠叨 càu nhàu', pos:'chữ Hán'},
  {zh:'叨', pinyin:'dao', hv:'đao', vi:'(trong 唠叨 càu nhàu)', pos:'chữ Hán'},
  {zh:'达', pinyin:'dá', hv:'đạt', vi:'đạt tới; truyền đạt', pos:'chữ Hán'},
  {zh:'惜', pinyin:'xī', hv:'tích', vi:'tiếc; quý trọng', pos:'chữ Hán'},
  {zh:'巴', pinyin:'bā', hv:'ba', vi:'mong mỏi; (phiên âm)', pos:'chữ Hán'},
  {zh:'途', pinyin:'tú', hv:'đồ', vi:'đường đi — 前途 tiền đồ', pos:'chữ Hán'},
  {zh:'稳', pinyin:'wěn', hv:'ổn', vi:'vững, ổn định', pos:'chữ Hán'},
  {zh:'互', pinyin:'hù', hv:'hỗ', vi:'lẫn nhau', pos:'chữ Hán'},
  {zh:'易', pinyin:'yì', hv:'dị', vi:'dễ; trao đổi (贸易)', pos:'chữ Hán'},
  {zh:'挫', pinyin:'cuò', hv:'toả', vi:'vấp váp — 挫折 thất bại', pos:'chữ Hán'},
  {zh:'诀', pinyin:'jué', hv:'quyết', vi:'bí quyết', pos:'chữ Hán'},
  {zh:'勤', pinyin:'qín', hv:'cần', vi:'siêng năng', pos:'chữ Hán'},
  {zh:'奋', pinyin:'fèn', hv:'phấn', vi:'hăng hái — 勤奋 chăm chỉ', pos:'chữ Hán'},
  {zh:'赚', pinyin:'zhuàn', hv:'trám', vi:'kiếm lời', pos:'chữ Hán'},
  {zh:'勉', pinyin:'miǎn', hv:'miễn', vi:'cố gắng; miễn cưỡng', pos:'chữ Hán'},
  {zh:'负', pinyin:'fù', hv:'phụ', vi:'gánh vác; âm, phụ', pos:'chữ Hán'},
  {zh:'妨', pinyin:'fáng', hv:'phương', vi:'cản trở — 不妨 chẳng ngại gì', pos:'chữ Hán'},
  {zh:'婉', pinyin:'wǎn', hv:'uyển', vi:'uyển chuyển, khéo léo', pos:'chữ Hán'},
  {zh:'违', pinyin:'wéi', hv:'vi', vi:'trái, vi phạm', pos:'chữ Hán'},
  {zh:'依', pinyin:'yī', hv:'y', vi:'dựa vào, theo', pos:'chữ Hán'},
  {zh:'赖', pinyin:'lài', hv:'lại', vi:'ỷ lại; đổ lỗi', pos:'chữ Hán'},
  {zh:'拟', pinyin:'nǐ', hv:'nghĩ', vi:'dự định; mô phỏng', pos:'chữ Hán'},
  {zh:'世', pinyin:'shì', hv:'thế', vi:'đời; thế giới', pos:'chữ Hán'},
  {zh:'私', pinyin:'sī', hv:'tư', vi:'riêng tư; tư nhân', pos:'chữ Hán'},
  {zh:'弊', pinyin:'bì', hv:'tệ', vi:'điều hại, tệ nạn', pos:'chữ Hán'},
  {zh:'册', pinyin:'cè', hv:'sách', vi:'quyển, tập; đăng kí (注册)', pos:'chữ Hán'},
  {zh:'辞', pinyin:'cí', hv:'từ', vi:'từ ngữ; từ chức', pos:'chữ Hán'},
  {zh:'匆', pinyin:'cōng', hv:'thông', vi:'vội vàng', pos:'chữ Hán'},
  {zh:'追', pinyin:'zhuī', hv:'truy', vi:'đuổi theo, truy tìm', pos:'chữ Hán'},
  {zh:'焦', pinyin:'jiāo', hv:'tiêu', vi:'cháy khét; lo lắng (焦虑)', pos:'chữ Hán'},
  {zh:'示', pinyin:'shì', hv:'thị', vi:'chỉ ra, tỏ rõ', pos:'chữ Hán'},
  {zh:'映', pinyin:'yìng', hv:'ánh', vi:'chiếu, phản chiếu', pos:'chữ Hán'},
  {zh:'含', pinyin:'hán', hv:'hàm', vi:'ngậm; chứa đựng', pos:'chữ Hán'},
  {zh:'义', pinyin:'yì', hv:'nghĩa', vi:'nghĩa, ý nghĩa', pos:'chữ Hán'},
  {zh:'纪', pinyin:'jì', hv:'kỉ', vi:'ghi chép; kỉ luật; thế kỉ', pos:'chữ Hán'},
  {zh:'征', pinyin:'zhēng', hv:'trưng', vi:'đặc trưng; trưng thu', pos:'chữ Hán'},
  {zh:'俗', pinyin:'sú', hv:'tục', vi:'phong tục; thông tục', pos:'chữ Hán'},
  {zh:'涨', pinyin:'zhǎng', hv:'trướng', vi:'dâng lên, tăng giá', pos:'chữ Hán'},
  {zh:'饮', pinyin:'yǐn', hv:'ẩm', vi:'uống — 饮食 ăn uống', pos:'chữ Hán'},
  {zh:'蔬', pinyin:'shū', hv:'sơ', vi:'rau — 蔬菜 rau củ', pos:'chữ Hán'},
  {zh:'宵', pinyin:'xiāo', hv:'tiêu', vi:'đêm — 宵夜 ăn khuya', pos:'chữ Hán'},
  {zh:'搭', pinyin:'dā', hv:'đáp', vi:'bắc, dựng; đi (xe); phối', pos:'chữ Hán'},
  {zh:'配', pinyin:'pèi', hv:'phối', vi:'phối hợp, xứng', pos:'chữ Hán'},
  {zh:'崩', pinyin:'bēng', hv:'băng', vi:'sụp đổ — 崩溃 sụp đổ, vỡ vụn', pos:'chữ Hán'},
  {zh:'溃', pinyin:'kuì', hv:'hội', vi:'tan vỡ', pos:'chữ Hán'},
  {zh:'倾', pinyin:'qīng', hv:'khuynh', vi:'nghiêng; dốc hết', pos:'chữ Hán'},
  {zh:'疗', pinyin:'liáo', hv:'liệu', vi:'chữa trị — 治疗', pos:'chữ Hán'},
  {zh:'拥', pinyin:'yōng', hv:'ủng', vi:'ôm; ủng hộ; đông đúc', pos:'chữ Hán'},
  {zh:'舍', pinyin:'shě', hv:'xả', vi:'bỏ, từ bỏ; đọc «shè» là nhà trọ', pos:'chữ Hán'},
  {zh:'脆', pinyin:'cuì', hv:'thuý', vi:'giòn; mong manh', pos:'chữ Hán'},
  {zh:'型', pinyin:'xíng', hv:'hình', vi:'kiểu, mẫu', pos:'chữ Hán'},
  {zh:'光', pinyin:'guāng', hv:'quang', vi:'ánh sáng; hết sạch', pos:'chữ Hán'},
  {zh:'族', pinyin:'zú', hv:'tộc', vi:'dân tộc; nhóm người', pos:'chữ Hán'},
  {zh:'索', pinyin:'suǒ', hv:'tác', vi:'dây thừng; tìm tòi (探索)', pos:'chữ Hán'},
  {zh:'删', pinyin:'shān', hv:'san', vi:'xoá bỏ', pos:'chữ Hán'},
  {zh:'储', pinyin:'chǔ', hv:'trữ', vi:'tích trữ', pos:'chữ Hán'},
  {zh:'蓄', pinyin:'xù', hv:'súc', vi:'tích luỹ — 储蓄 tiết kiệm', pos:'chữ Hán'},
  {zh:'败', pinyin:'bài', hv:'bại', vi:'thua, thất bại', pos:'chữ Hán'},
  {zh:'险', pinyin:'xiǎn', hv:'hiểm', vi:'nguy hiểm; bảo hiểm', pos:'chữ Hán'},
  {zh:'餐', pinyin:'cān', hv:'xan', vi:'bữa ăn — 餐厅 nhà hàng', pos:'chữ Hán'},
  {zh:'导', pinyin:'dǎo', hv:'đạo', vi:'dẫn dắt, hướng dẫn', pos:'chữ Hán'},
  {zh:'措', pinyin:'cuò', hv:'thố', vi:'biện pháp — 措施', pos:'chữ Hán'},
  {zh:'循', pinyin:'xún', hv:'tuần', vi:'noi theo — 循环 tuần hoàn', pos:'chữ Hán'},
  {zh:'乎', pinyin:'hū', hv:'hồ', vi:'(trợ từ văn viết) — 几乎 hầu như', pos:'chữ Hán'},
  {zh:'致', pinyin:'zhì', hv:'trí', vi:'dẫn đến; tỉ mỉ (细致)', pos:'chữ Hán'},
  {zh:'恶', pinyin:'è', hv:'ác', vi:'xấu, ác', pos:'chữ Hán'},
  {zh:'劣', pinyin:'liè', hv:'liệt', vi:'kém, tồi — 恶劣 tồi tệ', pos:'chữ Hán'},
  {zh:'伟', pinyin:'wěi', hv:'vĩ', vi:'vĩ đại', pos:'chữ Hán'},
  {zh:'陌', pinyin:'mò', hv:'mạch', vi:'xa lạ — 陌生 lạ lẫm', pos:'chữ Hán'},
  {zh:'阔', pinyin:'kuò', hv:'khoát', vi:'rộng rãi', pos:'chữ Hán'},
  {zh:'尴', pinyin:'gān', hv:'cam', vi:'(trong 尴尬 ngượng nghịu)', pos:'chữ Hán'},
  {zh:'尬', pinyin:'gà', hv:'giới', vi:'(trong 尴尬 ngượng nghịu)', pos:'chữ Hán'},
  {zh:'缓', pinyin:'huǎn', hv:'hoãn', vi:'chậm; hoãn lại', pos:'chữ Hán'},
  {zh:'寸', pinyin:'cùn', hv:'thốn', vi:'tấc; chừng mực (分寸)', pos:'chữ Hán'},
  {zh:'嘲', pinyin:'cháo', hv:'trào', vi:'chế giễu — 嘲笑', pos:'chữ Hán'},
  {zh:'引', pinyin:'yǐn', hv:'dẫn', vi:'dẫn, kéo; thu hút', pos:'chữ Hán'},
  {zh:'智', pinyin:'zhì', hv:'trí', vi:'trí tuệ', pos:'chữ Hán'},
  {zh:'忧', pinyin:'yōu', hv:'ưu', vi:'lo buồn', pos:'chữ Hán'},
  {zh:'析', pinyin:'xī', hv:'tích', vi:'phân tích', pos:'chữ Hán'},
  {zh:'判', pinyin:'pàn', hv:'phán', vi:'phán đoán, xét xử', pos:'chữ Hán'},
  {zh:'断', pinyin:'duàn', hv:'đoán', vi:'đứt, ngắt; phán đoán', pos:'chữ Hán'},
  {zh:'伦', pinyin:'lún', hv:'luân', vi:'luân lí, thứ bậc', pos:'chữ Hán'},
  {zh:'领', pinyin:'lǐng', hv:'lĩnh', vi:'lĩnh nhận; dẫn dắt; cổ áo', pos:'chữ Hán'},
  {zh:'抛', pinyin:'pāo', hv:'phao', vi:'ném, vứt bỏ', pos:'chữ Hán'},
  {zh:'忠', pinyin:'zhōng', hv:'trung', vi:'trung thành', pos:'chữ Hán'},
  {zh:'野', pinyin:'yě', hv:'dã', vi:'đồng hoang; hoang dã', pos:'chữ Hán'},
  {zh:'灭', pinyin:'miè', hv:'diệt', vi:'tắt; tiêu diệt', pos:'chữ Hán'},
  {zh:'衡', pinyin:'héng', hv:'hành', vi:'cân bằng — 平衡', pos:'chữ Hán'},
  {zh:'增', pinyin:'zēng', hv:'tăng', vi:'tăng thêm', pos:'chữ Hán'},
  {zh:'统', pinyin:'tǒng', hv:'thống', vi:'thống nhất; hệ thống', pos:'chữ Hán'},
  {zh:'绩', pinyin:'jì', hv:'tích', vi:'thành tích', pos:'chữ Hán'},
  {zh:'补', pinyin:'bǔ', hv:'bổ', vi:'vá, bù, bổ sung', pos:'chữ Hán'},
  {zh:'童', pinyin:'tóng', hv:'đồng', vi:'trẻ em', pos:'chữ Hán'},
  {zh:'竞', pinyin:'jìng', hv:'cạnh', vi:'cạnh tranh, đua', pos:'chữ Hán'},
  {zh:'激', pinyin:'jī', hv:'kích', vi:'kích động; mãnh liệt', pos:'chữ Hán'},
  {zh:'烈', pinyin:'liè', hv:'liệt', vi:'mạnh mẽ, dữ dội', pos:'chữ Hán'},
  {zh:'落', pinyin:'luò', hv:'lạc', vi:'rơi, rụng; tụt lại', pos:'chữ Hán'},
  {zh:'格', pinyin:'gé', hv:'cách', vi:'ô, khuôn; tính cách', pos:'chữ Hán'},
  {zh:'素', pinyin:'sù', hv:'tố', vi:'vốn có; chay; yếu tố', pos:'chữ Hán'},
  {zh:'鼓', pinyin:'gǔ', hv:'cổ', vi:'cái trống; cổ vũ', pos:'chữ Hán'},
  {zh:'较', pinyin:'jiào', hv:'giảo', vi:'so sánh; khá (比较)', pos:'chữ Hán'},
  {zh:'骄', pinyin:'jiāo', hv:'kiêu', vi:'kiêu ngạo; tự hào', pos:'chữ Hán'},
  {zh:'傲', pinyin:'ào', hv:'ngạo', vi:'ngạo nghễ — 骄傲 tự hào', pos:'chữ Hán'},
  {zh:'矛', pinyin:'máo', hv:'mâu', vi:'cây giáo — 矛盾 mâu thuẫn', pos:'chữ Hán'},
  {zh:'盾', pinyin:'dùn', hv:'thuẫn', vi:'cái khiên', pos:'chữ Hán'},
  {zh:'聚', pinyin:'jù', hv:'tụ', vi:'tụ họp', pos:'chữ Hán'},
  {zh:'圈', pinyin:'quān', hv:'quyển', vi:'vòng tròn; giới (朋友圈)', pos:'chữ Hán'},
  {zh:'列', pinyin:'liè', hv:'liệt', vi:'xếp hàng, liệt kê', pos:'chữ Hán'},
  {zh:'患', pinyin:'huàn', hv:'hoạn', vi:'mắc (bệnh); hoạn nạn', pos:'chữ Hán'},
  {zh:'丰', pinyin:'fēng', hv:'phong', vi:'dồi dào, phong phú', pos:'chữ Hán'},
  {zh:'恋', pinyin:'liàn', hv:'luyến', vi:'yêu đương, quyến luyến', pos:'chữ Hán'},
  {zh:'茫', pinyin:'máng', hv:'mang', vi:'mênh mông; mơ hồ (迷茫)', pos:'chữ Hán'},
  {zh:'攒', pinyin:'zǎn', hv:'toàn', vi:'dành dụm, tích cóp', pos:'chữ Hán'},
  {zh:'似', pinyin:'sì', hv:'tự', vi:'giống như — 似乎 dường như', pos:'chữ Hán'},
  {zh:'锦', pinyin:'jǐn', hv:'cẩm', vi:'gấm; tươi đẹp', pos:'chữ Hán'},
  {zh:'肤', pinyin:'fū', hv:'phu', vi:'da — 皮肤', pos:'chữ Hán'},
  {zh:'测', pinyin:'cè', hv:'trắc', vi:'đo, kiểm tra', pos:'chữ Hán'},
  {zh:'惠', pinyin:'huì', hv:'huệ', vi:'ân huệ; ưu đãi (优惠)', pos:'chữ Hán'},
  {zh:'诱', pinyin:'yòu', hv:'dụ', vi:'dụ dỗ, lôi kéo', pos:'chữ Hán'},
  {zh:'惑', pinyin:'huò', hv:'hoặc', vi:'mê hoặc — 诱惑 cám dỗ', pos:'chữ Hán'},
  {zh:'奉', pinyin:'fèng', hv:'phụng', vi:'phụng sự, dâng', pos:'chữ Hán'},
  {zh:'献', pinyin:'xiàn', hv:'hiến', vi:'hiến dâng — 奉献 cống hiến', pos:'chữ Hán'},
  {zh:'副', pinyin:'fù', hv:'phó', vi:'phó, phụ; (lượng từ cho bộ)', pos:'chữ Hán'},
  {zh:'兼', pinyin:'jiān', hv:'kiêm', vi:'kiêm nhiệm', pos:'chữ Hán'},
  {zh:'勇', pinyin:'yǒng', hv:'dũng', vi:'dũng cảm', pos:'chữ Hán'},
  {zh:'龄', pinyin:'líng', hv:'linh', vi:'tuổi — 年龄', pos:'chữ Hán'},
  {zh:'谱', pinyin:'pǔ', hv:'phổ', vi:'bản nhạc, biểu đồ; 靠谱 đáng tin', pos:'chữ Hán'},
  {zh:'融', pinyin:'róng', hv:'dung', vi:'tan chảy; hoà nhập; tài chính', pos:'chữ Hán'},
  {zh:'升', pinyin:'shēng', hv:'thăng', vi:'lên cao, thăng tiến; lít', pos:'chữ Hán'},
  {zh:'洪', pinyin:'hóng', hv:'hồng', vi:'lũ lụt', pos:'chữ Hán'},
  {zh:'旱', pinyin:'hàn', hv:'hạn', vi:'hạn hán', pos:'chữ Hán'},
  {zh:'繁', pinyin:'fán', hv:'phồn', vi:'nhiều, phồn thịnh; phức tạp', pos:'chữ Hán'},
  {zh:'迫', pinyin:'pò', hv:'bách', vi:'ép buộc; gấp gáp', pos:'chữ Hán'},
  {zh:'招', pinyin:'zhāo', hv:'chiêu', vi:'vẫy gọi; tuyển', pos:'chữ Hán'},
  {zh:'凌', pinyin:'líng', hv:'lăng', vi:'vượt lên — 凌晨 rạng sáng', pos:'chữ Hán'},
  {zh:'晨', pinyin:'chén', hv:'thần', vi:'buổi sớm', pos:'chữ Hán'},
  {zh:'沉', pinyin:'chén', hv:'trầm', vi:'chìm; nặng nề, trầm', pos:'chữ Hán'},
  {zh:'屏', pinyin:'píng', hv:'bình', vi:'bình phong; màn hình (屏幕)', pos:'chữ Hán'},
  {zh:'幕', pinyin:'mù', hv:'mạc', vi:'màn, bức màn', pos:'chữ Hán'},
  {zh:'略', pinyin:'lüè', hv:'lược', vi:'sơ lược; chiến lược', pos:'chữ Hán'},
  {zh:'槛', pinyin:'kǎn', hv:'hạm', vi:'ngưỡng cửa — 门槛', pos:'chữ Hán'},
  {zh:'博', pinyin:'bó', hv:'bác', vi:'rộng lớn, uyên bác; 博物馆 bảo tàng', pos:'chữ Hán'},
  {zh:'览', pinyin:'lǎn', hv:'lãm', vi:'xem, duyệt — 展览 triển lãm', pos:'chữ Hán'},
  {zh:'灵', pinyin:'líng', hv:'linh', vi:'linh hoạt; linh thiêng', pos:'chữ Hán'},
  {zh:'台', pinyin:'tái', hv:'đài', vi:'đài, bục; Đài Loan', pos:'chữ Hán'},
  {zh:'闻', pinyin:'wén', hv:'văn', vi:'nghe thấy; ngửi; tin tức', pos:'chữ Hán'},
  {zh:'颈', pinyin:'jǐng', hv:'cảnh', vi:'cổ — 颈椎 đốt sống cổ', pos:'chữ Hán'},
  {zh:'慨', pinyin:'kǎi', hv:'khái', vi:'cảm khái; hào phóng (慷慨)', pos:'chữ Hán'},

];

if (typeof window !== 'undefined') window.CHARS_ZH = CHARS_ZH;
if (typeof module !== 'undefined' && module.exports) module.exports = { CHARS_ZH };
