/* ============================================================
   LangLab — MỤC TỪ CHO TỪNG CHỮ HÁN (单字)
   ------------------------------------------------------------
   Trong bài đọc, mỗi chữ Hán đều bấm được. Giáo trình chỉ dạy TỪ
   (两 chữ trở lên) nên bấm vào một chữ lẻ thường ra rỗng. Tệp này
   bù các chữ lẻ có mặt trong 50 bài đọc tiếng Trung.

   Do LangLab tự biên soạn. Chữ nào đã là mục từ sẽ được khử trùng
   lặp khi gộp vào ZH_LOOKUP (xem js/app.js).

   Trường dữ liệu:  zh · pinyin · hv (âm Hán–Việt) · vi · pos
   ============================================================ */

const CHARS_ZH = [

  /* ---------- Họ · tên riêng ---------- */
  {zh:'阮', pinyin:'Ruǎn', hv:'Nguyễn', vi:'họ Nguyễn', pos:'chữ Hán'},
  {zh:'李', pinyin:'Lǐ', hv:'Lý', vi:'họ Lý; quả mận', pos:'chữ Hán'},
  {zh:'王', pinyin:'Wáng', hv:'Vương', vi:'họ Vương; vua', pos:'chữ Hán'},
  {zh:'林', pinyin:'lín', hv:'lâm', vi:'rừng; họ Lâm', pos:'chữ Hán'},
  {zh:'北', pinyin:'běi', hv:'bắc', vi:'phía bắc', pos:'chữ Hán'},
  {zh:'京', pinyin:'jīng', hv:'kinh', vi:'kinh đô', pos:'chữ Hán'},
  {zh:'西', pinyin:'xī', hv:'tây', vi:'phía tây', pos:'chữ Hán'},
  {zh:'安', pinyin:'ān', hv:'an', vi:'yên ổn, bình an', pos:'chữ Hán'},
  {zh:'南', pinyin:'nán', hv:'nam', vi:'phía nam', pos:'chữ Hán'},
  {zh:'东', pinyin:'dōng', hv:'đông', vi:'phía đông', pos:'chữ Hán'},

  /* ---------- Học hành ---------- */
  {zh:'学', pinyin:'xué', hv:'học', vi:'học', pos:'chữ Hán'},
  {zh:'习', pinyin:'xí', hv:'tập', vi:'luyện tập', pos:'chữ Hán'},
  {zh:'汉', pinyin:'hàn', hv:'hán', vi:'người Hán, chữ Hán', pos:'chữ Hán'},
  {zh:'语', pinyin:'yǔ', hv:'ngữ', vi:'ngôn ngữ, tiếng', pos:'chữ Hán'},
  {zh:'词', pinyin:'cí', hv:'từ', vi:'từ (ngôn ngữ)', pos:'chữ Hán'},
  {zh:'字', pinyin:'zì', hv:'tự', vi:'chữ', pos:'chữ Hán'},
  {zh:'典', pinyin:'diǎn', hv:'điển', vi:'sách chuẩn mực (từ điển)', pos:'chữ Hán'},
  {zh:'校', pinyin:'xiào', hv:'hiệu', vi:'trường học', pos:'chữ Hán'},
  {zh:'师', pinyin:'shī', hv:'sư', vi:'thầy, người dạy', pos:'chữ Hán'},
  {zh:'生', pinyin:'shēng', hv:'sinh', vi:'sinh ra, sống; học sinh', pos:'chữ Hán'},
  {zh:'考', pinyin:'kǎo', hv:'khảo', vi:'thi, kiểm tra', pos:'chữ Hán'},
  {zh:'复', pinyin:'fù', hv:'phục', vi:'lặp lại, ôn lại', pos:'chữ Hán'},
  {zh:'解', pinyin:'jiě', hv:'giải', vi:'cởi ra, giải thích', pos:'chữ Hán'},
  {zh:'释', pinyin:'shì', hv:'thích', vi:'giải nghĩa, buông ra', pos:'chữ Hán'},
  {zh:'记', pinyin:'jì', hv:'ký', vi:'ghi, nhớ', pos:'chữ Hán'},
  {zh:'首', pinyin:'shǒu', hv:'thủ', vi:'đầu; đứng đầu (bộ thủ)', pos:'chữ Hán'},
  {zh:'系', pinyin:'xì', hv:'hệ', vi:'hệ thống, liên hệ', pos:'chữ Hán'},
  {zh:'知', pinyin:'zhī', hv:'tri', vi:'biết', pos:'chữ Hán'},
  {zh:'道', pinyin:'dào', hv:'đạo', vi:'đường; đạo lý', pos:'chữ Hán'},
  {zh:'注', pinyin:'zhù', hv:'chú', vi:'rót vào; chú ý', pos:'chữ Hán'},
  {zh:'意', pinyin:'yì', hv:'ý', vi:'ý, ý nghĩ', pos:'chữ Hán'},
  {zh:'思', pinyin:'sī', hv:'tư', vi:'nghĩ', pos:'chữ Hán'},
  {zh:'认', pinyin:'rèn', hv:'nhận', vi:'nhận biết, thừa nhận', pos:'chữ Hán'},
  {zh:'识', pinyin:'shí', hv:'thức', vi:'biết, hiểu biết', pos:'chữ Hán'},
  {zh:'简', pinyin:'jiǎn', hv:'giản', vi:'đơn giản', pos:'chữ Hán'},
  {zh:'技', pinyin:'jì', hv:'kỹ', vi:'kỹ năng, tay nghề', pos:'chữ Hán'},
  {zh:'术', pinyin:'shù', hv:'thuật', vi:'thuật, kỹ thuật', pos:'chữ Hán'},
  {zh:'法', pinyin:'fǎ', hv:'pháp', vi:'phép, cách, luật', pos:'chữ Hán'},
  {zh:'讲', pinyin:'jiǎng', hv:'giảng', vi:'nói, giảng giải', pos:'chữ Hán'},
  {zh:'究', pinyin:'jiū', hv:'cứu', vi:'xét kỹ, nghiên cứu', pos:'chữ Hán'},

  /* ---------- Thời gian ---------- */
  {zh:'今', pinyin:'jīn', hv:'kim', vi:'nay, hiện tại', pos:'chữ Hán'},
  {zh:'年', pinyin:'nián', hv:'niên', vi:'năm', pos:'chữ Hán'},
  {zh:'早', pinyin:'zǎo', hv:'tảo', vi:'sớm; buổi sáng', pos:'chữ Hán'},
  {zh:'午', pinyin:'wǔ', hv:'ngọ', vi:'buổi trưa', pos:'chữ Hán'},
  {zh:'时', pinyin:'shí', hv:'thời', vi:'thời gian, lúc', pos:'chữ Hán'},
  {zh:'候', pinyin:'hòu', hv:'hậu', vi:'lúc, thời điểm; chờ', pos:'chữ Hán'},
  {zh:'间', pinyin:'jiān', hv:'gian', vi:'khoảng giữa; phòng', pos:'chữ Hán'},
  {zh:'后', pinyin:'hòu', hv:'hậu', vi:'sau, phía sau', pos:'chữ Hán'},
  {zh:'前', pinyin:'qián', hv:'tiền', vi:'trước, phía trước', pos:'chữ Hán'},
  {zh:'始', pinyin:'shǐ', hv:'thuỷ', vi:'bắt đầu', pos:'chữ Hán'},
  {zh:'终', pinyin:'zhōng', hv:'chung', vi:'cuối cùng, kết thúc', pos:'chữ Hán'},
  {zh:'昨', pinyin:'zuó', hv:'tạc', vi:'hôm qua', pos:'chữ Hán'},
  {zh:'现', pinyin:'xiàn', hv:'hiện', vi:'hiện nay, xuất hiện', pos:'chữ Hán'},
  {zh:'星', pinyin:'xīng', hv:'tinh', vi:'ngôi sao; tuần (星期)', pos:'chữ Hán'},
  {zh:'期', pinyin:'qī', hv:'kỳ', vi:'kỳ hạn, thời kỳ', pos:'chữ Hán'},
  {zh:'周', pinyin:'zhōu', hv:'chu', vi:'tuần; vòng quanh', pos:'chữ Hán'},
  {zh:'末', pinyin:'mò', hv:'mạt', vi:'cuối, ngọn', pos:'chữ Hán'},
  {zh:'春', pinyin:'chūn', hv:'xuân', vi:'mùa xuân', pos:'chữ Hán'},
  {zh:'夏', pinyin:'xià', hv:'hạ', vi:'mùa hè', pos:'chữ Hán'},
  {zh:'秋', pinyin:'qiū', hv:'thu', vi:'mùa thu', pos:'chữ Hán'},
  {zh:'夜', pinyin:'yè', hv:'dạ', vi:'đêm', pos:'chữ Hán'},
  {zh:'除', pinyin:'chú', hv:'trừ', vi:'trừ bỏ; đêm trừ tịch', pos:'chữ Hán'},
  {zh:'夕', pinyin:'xī', hv:'tịch', vi:'chiều tối', pos:'chữ Hán'},
  {zh:'刻', pinyin:'kè', hv:'khắc', vi:'khắc (15 phút); khoảnh khắc; khắc chạm', pos:'chữ Hán'},
  {zh:'历', pinyin:'lì', hv:'lịch', vi:'lịch; trải qua', pos:'chữ Hán'},
  {zh:'农', pinyin:'nóng', hv:'nông', vi:'nông nghiệp, nhà nông', pos:'chữ Hán'},
  {zh:'之', pinyin:'zhī', hv:'chi', vi:'của (văn viết)', pos:'chữ Hán'},
  {zh:'至', pinyin:'zhì', hv:'chí', vi:'đến, tới; cực kỳ', pos:'chữ Hán'},
  {zh:'已', pinyin:'yǐ', hv:'dĩ', vi:'đã, rồi', pos:'chữ Hán'},
  {zh:'经', pinyin:'jīng', hv:'kinh', vi:'trải qua; kinh sách', pos:'chữ Hán'},
  {zh:'总', pinyin:'zǒng', hv:'tổng', vi:'tổng cộng; luôn luôn', pos:'chữ Hán'},
  {zh:'常', pinyin:'cháng', hv:'thường', vi:'thường xuyên', pos:'chữ Hán'},
  {zh:'随', pinyin:'suí', hv:'tuỳ', vi:'theo, tuỳ theo', pos:'chữ Hán'},
  {zh:'忽', pinyin:'hū', hv:'hốt', vi:'bỗng nhiên', pos:'chữ Hán'},
  {zh:'正', pinyin:'zhèng', hv:'chính', vi:'đúng, chính; đang', pos:'chữ Hán'},
  {zh:'直', pinyin:'zhí', hv:'trực', vi:'thẳng; thẳng thắn', pos:'chữ Hán'},
  {zh:'万', pinyin:'wàn', hv:'vạn', vi:'vạn (10 000)', pos:'chữ Hán'},
  {zh:'百', pinyin:'bǎi', hv:'bách', vi:'trăm', pos:'chữ Hán'},
  {zh:'第', pinyin:'dì', hv:'đệ', vi:'thứ (số thứ tự)', pos:'chữ Hán'},
  {zh:'单', pinyin:'dān', hv:'đơn', vi:'đơn lẻ; đơn, phiếu', pos:'chữ Hán'},
  {zh:'共', pinyin:'gòng', hv:'cộng', vi:'chung, cộng lại', pos:'chữ Hán'},
  {zh:'全', pinyin:'quán', hv:'toàn', vi:'toàn bộ, đầy đủ', pos:'chữ Hán'},
  {zh:'量', pinyin:'liàng', hv:'lượng', vi:'số lượng; đo', pos:'chữ Hán'},
  {zh:'些', pinyin:'xiē', hv:'ta', vi:'một ít, vài', pos:'chữ Hán'},
  {zh:'条', pinyin:'tiáo', hv:'điều', vi:'lượng từ cho vật dài; điều khoản', pos:'chữ Hán'},
  {zh:'片', pinyin:'piàn', hv:'phiến', vi:'miếng, tấm', pos:'chữ Hán'},
  {zh:'般', pinyin:'bān', hv:'ban', vi:'loại, kiểu (一般: nói chung)', pos:'chữ Hán'},
  {zh:'样', pinyin:'yàng', hv:'dạng', vi:'kiểu, dáng', pos:'chữ Hán'},
  {zh:'次', pinyin:'cì', hv:'thứ', vi:'lần; thứ tự', pos:'chữ Hán'},

  /* ---------- Con người · gia đình ---------- */
  {zh:'朋', pinyin:'péng', hv:'bằng', vi:'bạn bè', pos:'chữ Hán'},
  {zh:'友', pinyin:'yǒu', hv:'hữu', vi:'bạn', pos:'chữ Hán'},
  {zh:'爸', pinyin:'bà', hv:'ba', vi:'bố', pos:'chữ Hán'},
  {zh:'妈', pinyin:'mā', hv:'ma', vi:'mẹ', pos:'chữ Hán'},
  {zh:'哥', pinyin:'gē', hv:'ca', vi:'anh trai', pos:'chữ Hán'},
  {zh:'妹', pinyin:'mèi', hv:'muội', vi:'em gái', pos:'chữ Hán'},
  {zh:'男', pinyin:'nán', hv:'nam', vi:'nam giới', pos:'chữ Hán'},
  {zh:'奶', pinyin:'nǎi', hv:'nãi', vi:'bà nội; sữa', pos:'chữ Hán'},
  {zh:'爷', pinyin:'yé', hv:'gia', vi:'ông nội', pos:'chữ Hán'},
  {zh:'阿', pinyin:'ā', hv:'a', vi:'tiền tố gọi thân mật', pos:'chữ Hán'},
  {zh:'姨', pinyin:'yí', hv:'di', vi:'dì, cô (phụ nữ trung niên)', pos:'chữ Hán'},
  {zh:'孩', pinyin:'hái', hv:'hài', vi:'đứa trẻ', pos:'chữ Hán'},
  {zh:'儿', pinyin:'ér', hv:'nhi', vi:'con, trẻ nhỏ; đuôi 儿', pos:'chữ Hán'},
  {zh:'辈', pinyin:'bèi', hv:'bối', vi:'thế hệ, bậc', pos:'chữ Hán'},
  {zh:'夫', pinyin:'fū', hv:'phu', vi:'chồng; người đàn ông', pos:'chữ Hán'},
  {zh:'妻', pinyin:'qī', hv:'thê', vi:'vợ', pos:'chữ Hán'},
  {zh:'员', pinyin:'yuán', hv:'viên', vi:'thành viên, nhân viên', pos:'chữ Hán'},
  {zh:'傅', pinyin:'fù', hv:'phó', vi:'thầy dạy nghề (师傅)', pos:'chữ Hán'},
  {zh:'坊', pinyin:'fāng', hv:'phường', vi:'xóm, phường; xưởng', pos:'chữ Hán'},
  {zh:'邻', pinyin:'lín', hv:'lân', vi:'láng giềng', pos:'chữ Hán'},
  {zh:'居', pinyin:'jū', hv:'cư', vi:'ở, cư trú', pos:'chữ Hán'},
  {zh:'客', pinyin:'kè', hv:'khách', vi:'khách', pos:'chữ Hán'},
  {zh:'己', pinyin:'jǐ', hv:'kỷ', vi:'mình, bản thân', pos:'chữ Hán'},
  {zh:'身', pinyin:'shēn', hv:'thân', vi:'thân thể', pos:'chữ Hán'},
  {zh:'体', pinyin:'tǐ', hv:'thể', vi:'cơ thể; thể loại', pos:'chữ Hán'},

  /* ---------- Cơ thể · sức khoẻ ---------- */
  {zh:'医', pinyin:'yī', hv:'y', vi:'y học, chữa bệnh', pos:'chữ Hán'},
  {zh:'院', pinyin:'yuàn', hv:'viện', vi:'viện, sân trong', pos:'chữ Hán'},
  {zh:'病', pinyin:'bìng', hv:'bệnh', vi:'bệnh', pos:'chữ Hán'},
  {zh:'感', pinyin:'gǎn', hv:'cảm', vi:'cảm thấy; cảm động', pos:'chữ Hán'},
  {zh:'冒', pinyin:'mào', hv:'mạo', vi:'bốc lên; liều (感冒: cảm)', pos:'chữ Hán'},
  {zh:'咳', pinyin:'ké', hv:'khái', vi:'ho', pos:'chữ Hán'},
  {zh:'嗽', pinyin:'sou', hv:'thấu', vi:'ho (咳嗽)', pos:'chữ Hán'},
  {zh:'烧', pinyin:'shāo', hv:'thiêu', vi:'đốt; sốt', pos:'chữ Hán'},
  {zh:'检', pinyin:'jiǎn', hv:'kiểm', vi:'kiểm tra', pos:'chữ Hán'},
  {zh:'查', pinyin:'chá', hv:'tra', vi:'tra cứu, kiểm tra', pos:'chữ Hán'},
  {zh:'针', pinyin:'zhēn', hv:'châm', vi:'cây kim; mũi tiêm', pos:'chữ Hán'},
  {zh:'护', pinyin:'hù', hv:'hộ', vi:'bảo vệ, chăm sóc', pos:'chữ Hán'},
  {zh:'休', pinyin:'xiū', hv:'hưu', vi:'nghỉ ngơi', pos:'chữ Hán'},
  {zh:'息', pinyin:'xī', hv:'tức', vi:'nghỉ; hơi thở; tin tức', pos:'chữ Hán'},
  {zh:'睡', pinyin:'shuì', hv:'thuỵ', vi:'ngủ', pos:'chữ Hán'},
  {zh:'舒', pinyin:'shū', hv:'thư', vi:'thư thái, dễ chịu', pos:'chữ Hán'},
  {zh:'服', pinyin:'fú', hv:'phục', vi:'quần áo; phục vụ; uống thuốc', pos:'chữ Hán'},
  {zh:'嗓', pinyin:'sǎng', hv:'tảng', vi:'cổ họng, giọng', pos:'chữ Hán'},
  {zh:'眼', pinyin:'yǎn', hv:'nhãn', vi:'mắt', pos:'chữ Hán'},
  {zh:'睛', pinyin:'jīng', hv:'tinh', vi:'con ngươi (眼睛: mắt)', pos:'chữ Hán'},
  {zh:'牙', pinyin:'yá', hv:'nha', vi:'răng', pos:'chữ Hán'},
  {zh:'肚', pinyin:'dù', hv:'đỗ', vi:'bụng', pos:'chữ Hán'},
  {zh:'呼', pinyin:'hū', hv:'hô', vi:'thở ra; gọi', pos:'chữ Hán'},
  {zh:'吸', pinyin:'xī', hv:'hấp', vi:'hít vào, hút', pos:'chữ Hán'},
  {zh:'严', pinyin:'yán', hv:'nghiêm', vi:'nghiêm, nghiêm trọng', pos:'chữ Hán'},

  /* ---------- Ăn uống ---------- */
  {zh:'食', pinyin:'shí', hv:'thực', vi:'ăn, thức ăn', pos:'chữ Hán'},
  {zh:'堂', pinyin:'táng', hv:'đường', vi:'nhà lớn, sảnh (食堂)', pos:'chữ Hán'},
  {zh:'馆', pinyin:'guǎn', hv:'quán', vi:'quán, nhà (饭馆)', pos:'chữ Hán'},
  {zh:'面', pinyin:'miàn', hv:'diện', vi:'mặt; mì; phía', pos:'chữ Hán'},
  {zh:'蛋', pinyin:'dàn', hv:'đản', vi:'trứng', pos:'chữ Hán'},
  {zh:'青', pinyin:'qīng', hv:'thanh', vi:'xanh; trẻ', pos:'chữ Hán'},
  {zh:'豆', pinyin:'dòu', hv:'đậu', vi:'đậu', pos:'chữ Hán'},
  {zh:'腐', pinyin:'fǔ', hv:'hủ', vi:'thiu, mục (豆腐: đậu phụ)', pos:'chữ Hán'},
  {zh:'苹', pinyin:'píng', hv:'bình', vi:'táo (苹果)', pos:'chữ Hán'},
  {zh:'果', pinyin:'guǒ', hv:'quả', vi:'quả, kết quả', pos:'chữ Hán'},
  {zh:'香', pinyin:'xiāng', hv:'hương', vi:'thơm', pos:'chữ Hán'},
  {zh:'蕉', pinyin:'jiāo', hv:'tiêu', vi:'chuối (香蕉)', pos:'chữ Hán'},
  {zh:'柿', pinyin:'shì', hv:'thị', vi:'quả hồng; cà chua (西红柿)', pos:'chữ Hán'},
  {zh:'葱', pinyin:'cōng', hv:'thông', vi:'hành lá', pos:'chữ Hán'},
  {zh:'鲜', pinyin:'xiān', hv:'tiên', vi:'tươi, tươi ngon', pos:'chữ Hán'},
  {zh:'味', pinyin:'wèi', hv:'vị', vi:'mùi vị', pos:'chữ Hán'},
  {zh:'饺', pinyin:'jiǎo', hv:'giảo', vi:'sủi cảo (饺子)', pos:'chữ Hán'},
  {zh:'糕', pinyin:'gāo', hv:'cao', vi:'bánh (蛋糕: bánh ga-tô)', pos:'chữ Hán'},
  {zh:'饼', pinyin:'bǐng', hv:'bính', vi:'bánh dẹt (月饼)', pos:'chữ Hán'},
  {zh:'沙', pinyin:'shā', hv:'sa', vi:'cát; nhân nghiền (豆沙)', pos:'chữ Hán'},
  {zh:'莲', pinyin:'lián', hv:'liên', vi:'hoa sen', pos:'chữ Hán'},
  {zh:'蓉', pinyin:'róng', hv:'dung', vi:'bột nhuyễn (莲蓉: nhân hạt sen)', pos:'chữ Hán'},
  {zh:'仁', pinyin:'rén', hv:'nhân', vi:'nhân hạt; lòng nhân', pos:'chữ Hán'},
  {zh:'瓶', pinyin:'píng', hv:'bình', vi:'cái chai', pos:'chữ Hán'},
  {zh:'桶', pinyin:'tǒng', hv:'dũng', vi:'cái thùng', pos:'chữ Hán'},
  {zh:'火', pinyin:'huǒ', hv:'hoả', vi:'lửa', pos:'chữ Hán'},
  {zh:'浇', pinyin:'jiāo', hv:'kiêu', vi:'tưới, dội', pos:'chữ Hán'},

  /* ---------- Nhà cửa · đồ vật ---------- */
  {zh:'房', pinyin:'fáng', hv:'phòng', vi:'nhà, phòng', pos:'chữ Hán'},
  {zh:'屋', pinyin:'wū', hv:'ốc', vi:'nhà, gian nhà', pos:'chữ Hán'},
  {zh:'室', pinyin:'shì', hv:'thất', vi:'phòng, buồng', pos:'chữ Hán'},
  {zh:'栋', pinyin:'dòng', hv:'đống', vi:'toà (lượng từ cho nhà)', pos:'chữ Hán'},
  {zh:'窗', pinyin:'chuāng', hv:'song', vi:'cửa sổ', pos:'chữ Hán'},
  {zh:'户', pinyin:'hù', hv:'hộ', vi:'cửa; hộ gia đình', pos:'chữ Hán'},
  {zh:'桌', pinyin:'zhuō', hv:'trác', vi:'cái bàn', pos:'chữ Hán'},
  {zh:'椅', pinyin:'yǐ', hv:'ỷ', vi:'cái ghế', pos:'chữ Hán'},
  {zh:'子', pinyin:'zi', hv:'tử', vi:'con; hậu tố danh từ', pos:'chữ Hán'},
  {zh:'枕', pinyin:'zhěn', hv:'chẩm', vi:'cái gối', pos:'chữ Hán'},
  {zh:'柜', pinyin:'guì', hv:'quỹ', vi:'cái tủ', pos:'chữ Hán'},
  {zh:'箱', pinyin:'xiāng', hv:'tương', vi:'cái hộp, thùng', pos:'chữ Hán'},
  {zh:'袋', pinyin:'dài', hv:'đại', vi:'cái túi', pos:'chữ Hán'},
  {zh:'板', pinyin:'bǎn', hv:'bản', vi:'tấm ván; ông chủ (老板)', pos:'chữ Hán'},
  {zh:'叶', pinyin:'yè', hv:'diệp', vi:'lá cây', pos:'chữ Hán'},
  {zh:'尘', pinyin:'chén', hv:'trần', vi:'bụi', pos:'chữ Hán'},
  {zh:'器', pinyin:'qì', hv:'khí', vi:'đồ dùng, thiết bị', pos:'chữ Hán'},
  {zh:'机', pinyin:'jī', hv:'cơ', vi:'máy; cơ hội', pos:'chữ Hán'},
  {zh:'脑', pinyin:'nǎo', hv:'não', vi:'não; máy tính (电脑)', pos:'chữ Hán'},
  {zh:'电', pinyin:'diàn', hv:'điện', vi:'điện', pos:'chữ Hán'},
  {zh:'视', pinyin:'shì', hv:'thị', vi:'nhìn; tivi (电视)', pos:'chữ Hán'},
  {zh:'影', pinyin:'yǐng', hv:'ảnh', vi:'bóng; phim (电影)', pos:'chữ Hán'},
  {zh:'照', pinyin:'zhào', hv:'chiếu', vi:'chiếu sáng; chụp ảnh', pos:'chữ Hán'},
  {zh:'响', pinyin:'xiǎng', hv:'hưởng', vi:'vang lên, kêu', pos:'chữ Hán'},
  {zh:'音', pinyin:'yīn', hv:'âm', vi:'âm thanh', pos:'chữ Hán'},
  {zh:'乐', pinyin:'yuè', hv:'nhạc', vi:'âm nhạc; (lè) vui', pos:'chữ Hán'},
  {zh:'钥', pinyin:'yào', hv:'dược', vi:'chìa khoá (钥匙)', pos:'chữ Hán'},
  {zh:'匙', pinyin:'shi', hv:'thi', vi:'thìa; chìa (钥匙)', pos:'chữ Hán'},
  {zh:'充', pinyin:'chōng', hv:'sung', vi:'nạp, đổ đầy', pos:'chữ Hán'},
  {zh:'宝', pinyin:'bǎo', hv:'bảo', vi:'báu vật', pos:'chữ Hán'},
  {zh:'支', pinyin:'zhī', hv:'chi', vi:'chi trả; cái (lượng từ)', pos:'chữ Hán'},
  {zh:'卡', pinyin:'kǎ', hv:'ca', vi:'cái thẻ', pos:'chữ Hán'},
  {zh:'码', pinyin:'mǎ', hv:'mã', vi:'mã số', pos:'chữ Hán'},
  {zh:'牌', pinyin:'pái', hv:'bài', vi:'tấm biển; thương hiệu', pos:'chữ Hán'},
  {zh:'表', pinyin:'biǎo', hv:'biểu', vi:'bảng, biểu; đồng hồ đeo tay', pos:'chữ Hán'},
  {zh:'栏', pinyin:'lán', hv:'lan', vi:'ô, cột (trong biểu mẫu)', pos:'chữ Hán'},
  {zh:'衣', pinyin:'yī', hv:'y', vi:'áo, quần áo', pos:'chữ Hán'},
  {zh:'色', pinyin:'sè', hv:'sắc', vi:'màu sắc', pos:'chữ Hán'},
  {zh:'颜', pinyin:'yán', hv:'nhan', vi:'màu; nét mặt', pos:'chữ Hán'},
  {zh:'金', pinyin:'jīn', hv:'kim', vi:'vàng, kim loại', pos:'chữ Hán'},
  {zh:'银', pinyin:'yín', hv:'ngân', vi:'bạc; ngân hàng (银行)', pos:'chữ Hán'},
  {zh:'礼', pinyin:'lǐ', hv:'lễ', vi:'lễ nghi; quà tặng', pos:'chữ Hán'},
  {zh:'物', pinyin:'wù', hv:'vật', vi:'vật, đồ vật', pos:'chữ Hán'},

  /* ---------- Giao thông · nơi chốn ---------- */
  {zh:'车', pinyin:'chē', hv:'xa', vi:'xe', pos:'chữ Hán'},
  {zh:'铁', pinyin:'tiě', hv:'thiết', vi:'sắt; tàu điện ngầm (地铁)', pos:'chữ Hán'},
  {zh:'地', pinyin:'dì', hv:'địa', vi:'đất, mặt đất', pos:'chữ Hán'},
  {zh:'图', pinyin:'tú', hv:'đồ', vi:'bản đồ, hình vẽ', pos:'chữ Hán'},
  {zh:'路', pinyin:'lù', hv:'lộ', vi:'đường', pos:'chữ Hán'},
  {zh:'往', pinyin:'wǎng', hv:'vãng', vi:'đi về phía', pos:'chữ Hán'},
  {zh:'左', pinyin:'zuǒ', hv:'tả', vi:'bên trái', pos:'chữ Hán'},
  {zh:'右', pinyin:'yòu', hv:'hữu', vi:'bên phải', pos:'chữ Hán'},
  {zh:'拐', pinyin:'guǎi', hv:'quải', vi:'rẽ, ngoặt', pos:'chữ Hán'},
  {zh:'旁', pinyin:'páng', hv:'bàng', vi:'bên cạnh', pos:'chữ Hán'},
  {zh:'边', pinyin:'biān', hv:'biên', vi:'bên, mép, rìa', pos:'chữ Hán'},
  {zh:'内', pinyin:'nèi', hv:'nội', vi:'bên trong', pos:'chữ Hán'},
  {zh:'外', pinyin:'wài', hv:'ngoại', vi:'bên ngoài', pos:'chữ Hán'},
  {zh:'上', pinyin:'shàng', hv:'thượng', vi:'trên; lên', pos:'chữ Hán'},
  {zh:'下', pinyin:'xià', hv:'hạ', vi:'dưới; xuống', pos:'chữ Hán'},
  {zh:'中', pinyin:'zhōng', hv:'trung', vi:'giữa; Trung Quốc', pos:'chữ Hán'},
  {zh:'国', pinyin:'guó', hv:'quốc', vi:'nước, quốc gia', pos:'chữ Hán'},
  {zh:'城', pinyin:'chéng', hv:'thành', vi:'thành phố, thành luỹ', pos:'chữ Hán'},
  {zh:'市', pinyin:'shì', hv:'thị', vi:'chợ; thành phố', pos:'chữ Hán'},
  {zh:'店', pinyin:'diàn', hv:'điếm', vi:'cửa hàng', pos:'chữ Hán'},
  {zh:'摊', pinyin:'tān', hv:'than', vi:'quầy hàng, sạp', pos:'chữ Hán'},
  {zh:'公', pinyin:'gōng', hv:'công', vi:'chung, công cộng', pos:'chữ Hán'},
  {zh:'司', pinyin:'sī', hv:'ty', vi:'quản lý (公司: công ty)', pos:'chữ Hán'},
  {zh:'业', pinyin:'yè', hv:'nghiệp', vi:'nghề, ngành', pos:'chữ Hán'},
  {zh:'商', pinyin:'shāng', hv:'thương', vi:'buôn bán; bàn bạc', pos:'chữ Hán'},
  {zh:'务', pinyin:'wù', hv:'vụ', vi:'việc, nhiệm vụ', pos:'chữ Hán'},
  {zh:'园', pinyin:'yuán', hv:'viên', vi:'vườn, công viên', pos:'chữ Hán'},
  {zh:'馆', pinyin:'guǎn', hv:'quán', vi:'quán, toà nhà công', pos:'chữ Hán'},
  {zh:'卫', pinyin:'wèi', hv:'vệ', vi:'bảo vệ, vệ sinh', pos:'chữ Hán'},
  {zh:'址', pinyin:'zhǐ', hv:'chỉ', vi:'địa chỉ, vị trí', pos:'chữ Hán'},
  {zh:'籍', pinyin:'jí', hv:'tịch', vi:'sổ sách; quốc tịch', pos:'chữ Hán'},
  {zh:'名', pinyin:'míng', hv:'danh', vi:'tên; nổi tiếng', pos:'chữ Hán'},
  {zh:'堵', pinyin:'dǔ', hv:'đổ', vi:'tắc, nghẽn', pos:'chữ Hán'},
  {zh:'售', pinyin:'shòu', hv:'thụ', vi:'bán', pos:'chữ Hán'},
  {zh:'广', pinyin:'guǎng', hv:'quảng', vi:'rộng; quảng bá', pos:'chữ Hán'},
  {zh:'播', pinyin:'bō', hv:'bá', vi:'phát, gieo', pos:'chữ Hán'},
  {zh:'递', pinyin:'dì', hv:'đệ', vi:'chuyển giao (快递)', pos:'chữ Hán'},
  {zh:'裹', pinyin:'guǒ', hv:'khoả', vi:'bọc, gói (包裹)', pos:'chữ Hán'},
  {zh:'信', pinyin:'xìn', hv:'tín', vi:'thư; tin tưởng', pos:'chữ Hán'},

  /* ---------- Thiên nhiên ---------- */
  {zh:'雨', pinyin:'yǔ', hv:'vũ', vi:'mưa', pos:'chữ Hán'},
  {zh:'阳', pinyin:'yáng', hv:'dương', vi:'mặt trời, dương', pos:'chữ Hán'},
  {zh:'气', pinyin:'qì', hv:'khí', vi:'khí, hơi; tức giận', pos:'chữ Hán'},
  {zh:'氵', pinyin:'shuǐ', hv:'thuỷ', vi:'bộ ba chấm thuỷ (nước)', pos:'bộ thủ'},
  {zh:'山', pinyin:'shān', hv:'sơn', vi:'núi', pos:'chữ Hán'},
  {zh:'顶', pinyin:'dǐng', hv:'đỉnh', vi:'đỉnh, chóp', pos:'chữ Hán'},
  {zh:'爬', pinyin:'pá', hv:'ba', vi:'leo, bò', pos:'chữ Hán'},
  {zh:'游', pinyin:'yóu', hv:'du', vi:'bơi; đi chơi', pos:'chữ Hán'},
  {zh:'泳', pinyin:'yǒng', hv:'vịnh', vi:'bơi lội', pos:'chữ Hán'},
  {zh:'浪', pinyin:'làng', hv:'lãng', vi:'sóng; phóng túng', pos:'chữ Hán'},
  {zh:'费', pinyin:'fèi', hv:'phí', vi:'chi phí; tiêu tốn', pos:'chữ Hán'},
  {zh:'团', pinyin:'tuán', hv:'đoàn', vi:'đoàn, khối tròn', pos:'chữ Hán'},
  {zh:'赏', pinyin:'shǎng', hv:'thưởng', vi:'thưởng thức; ban thưởng', pos:'chữ Hán'},

  /* ---------- Động từ ---------- */
  {zh:'起', pinyin:'qǐ', hv:'khởi', vi:'dậy, khởi đầu', pos:'chữ Hán'},
  {zh:'喜', pinyin:'xǐ', hv:'hỷ', vi:'vui mừng, thích', pos:'chữ Hán'},
  {zh:'欢', pinyin:'huān', hv:'hoan', vi:'vui vẻ (喜欢: thích)', pos:'chữ Hán'},
  {zh:'和', pinyin:'hé', hv:'hoà', vi:'và; hoà thuận', pos:'chữ Hán'},
  {zh:'可', pinyin:'kě', hv:'khả', vi:'có thể; nhưng', pos:'chữ Hán'},
  {zh:'高', pinyin:'gāo', hv:'cao', vi:'cao', pos:'chữ Hán'},
  {zh:'兴', pinyin:'xìng', hv:'hứng', vi:'hứng thú (高兴: vui)', pos:'chữ Hán'},
  {zh:'卖', pinyin:'mài', hv:'mại', vi:'bán', pos:'chữ Hán'},
  {zh:'有', pinyin:'yǒu', hv:'hữu', vi:'có', pos:'chữ Hán'},
  {zh:'小', pinyin:'xiǎo', hv:'tiểu', vi:'nhỏ', pos:'chữ Hán'},
  {zh:'大', pinyin:'dà', hv:'đại', vi:'to, lớn', pos:'chữ Hán'},
  {zh:'按', pinyin:'àn', hv:'án', vi:'bấm, ấn; theo', pos:'chữ Hán'},
  {zh:'顺', pinyin:'shùn', hv:'thuận', vi:'thuận, xuôi', pos:'chữ Hán'},
  {zh:'序', pinyin:'xù', hv:'tự', vi:'thứ tự', pos:'chữ Hán'},
  {zh:'排', pinyin:'pái', hv:'bài', vi:'xếp hàng, sắp xếp', pos:'chữ Hán'},
  {zh:'问', pinyin:'wèn', hv:'vấn', vi:'hỏi', pos:'chữ Hán'},
  {zh:'扣', pinyin:'kòu', hv:'khấu', vi:'trừ, khấu; cài', pos:'chữ Hán'},
  {zh:'所', pinyin:'suǒ', hv:'sở', vi:'nơi; sở dĩ (所以)', pos:'chữ Hán'},
  {zh:'以', pinyin:'yǐ', hv:'dĩ', vi:'lấy, dùng; để mà', pos:'chữ Hán'},
  {zh:'来', pinyin:'lái', hv:'lai', vi:'đến, tới', pos:'chữ Hán'},
  {zh:'回', pinyin:'huí', hv:'hồi', vi:'quay về; lần', pos:'chữ Hán'},
  {zh:'工', pinyin:'gōng', hv:'công', vi:'công việc, thợ', pos:'chữ Hán'},
  {zh:'作', pinyin:'zuò', hv:'tác', vi:'làm, sáng tác', pos:'chữ Hán'},
  {zh:'辛', pinyin:'xīn', hv:'tân', vi:'cay đắng, vất vả', pos:'chữ Hán'},
  {zh:'但', pinyin:'dàn', hv:'đãn', vi:'nhưng', pos:'chữ Hán'},
  {zh:'自', pinyin:'zì', hv:'tự', vi:'tự, từ', pos:'chữ Hán'},
  {zh:'由', pinyin:'yóu', hv:'do', vi:'do, bởi; tự do', pos:'chữ Hán'},
  {zh:'算', pinyin:'suàn', hv:'toán', vi:'tính toán; coi như', pos:'chữ Hán'},
  {zh:'存', pinyin:'cún', hv:'tồn', vi:'gửi, cất giữ; tồn tại', pos:'chữ Hán'},
  {zh:'行', pinyin:'xíng', hv:'hành', vi:'đi; được; (háng) hàng', pos:'chữ Hán'},
  {zh:'见', pinyin:'jiàn', hv:'kiến', vi:'thấy, gặp', pos:'chữ Hán'},
  {zh:'告', pinyin:'gào', hv:'cáo', vi:'báo, nói cho biết', pos:'chữ Hán'},
  {zh:'诉', pinyin:'sù', hv:'tố', vi:'kể, tố cáo', pos:'chữ Hán'},
  {zh:'迟', pinyin:'chí', hv:'trì', vi:'chậm, trễ', pos:'chữ Hán'},
  {zh:'净', pinyin:'jìng', hv:'tịnh', vi:'sạch (干净)', pos:'chữ Hán'},
  {zh:'管', pinyin:'guǎn', hv:'quản', vi:'quản lý; cái ống', pos:'chữ Hán'},
  {zh:'走', pinyin:'zǒu', hv:'tẩu', vi:'đi, bước', pos:'chữ Hán'},
  {zh:'取', pinyin:'qǔ', hv:'thủ', vi:'lấy, rút', pos:'chữ Hán'},
  {zh:'轮', pinyin:'lún', hv:'luân', vi:'bánh xe; đến lượt', pos:'chữ Hán'},
  {zh:'需', pinyin:'xū', hv:'nhu', vi:'cần', pos:'chữ Hán'},
  {zh:'填', pinyin:'tián', hv:'điền', vi:'điền vào', pos:'chữ Hán'},
  {zh:'耐', pinyin:'nài', hv:'nại', vi:'chịu đựng, kiên nhẫn', pos:'chữ Hán'},
  {zh:'提', pinyin:'tí', hv:'đề', vi:'nâng, xách; nêu ra', pos:'chữ Hán'},
  {zh:'醒', pinyin:'xǐng', hv:'tỉnh', vi:'tỉnh dậy; nhắc nhở', pos:'chữ Hán'},
  {zh:'密', pinyin:'mì', hv:'mật', vi:'kín, dày; bí mật', pos:'chữ Hán'},
  {zh:'载', pinyin:'zài', hv:'tải', vi:'chở, tải', pos:'chữ Hán'},
  {zh:'出', pinyin:'chū', hv:'xuất', vi:'ra, đi ra', pos:'chữ Hán'},
  {zh:'动', pinyin:'dòng', hv:'động', vi:'động, cử động', pos:'chữ Hán'},
  {zh:'紧', pinyin:'jǐn', hv:'khẩn', vi:'chặt, gấp', pos:'chữ Hán'},
  {zh:'原', pinyin:'yuán', hv:'nguyên', vi:'vốn, nguyên; đồng bằng', pos:'chữ Hán'},
  {zh:'漂', pinyin:'piào', hv:'phiêu', vi:'đẹp (漂亮); trôi nổi', pos:'chữ Hán'},
  {zh:'努', pinyin:'nǔ', hv:'nỗ', vi:'gắng sức', pos:'chữ Hán'},
  {zh:'力', pinyin:'lì', hv:'lực', vi:'sức, lực', pos:'chữ Hán'},
  {zh:'玩', pinyin:'wán', hv:'ngoạn', vi:'chơi', pos:'chữ Hán'},
  {zh:'舞', pinyin:'wǔ', hv:'vũ', vi:'múa, nhảy', pos:'chữ Hán'},
  {zh:'理', pinyin:'lǐ', hv:'lý', vi:'lý lẽ; chỉnh lý', pos:'chữ Hán'},
  {zh:'假', pinyin:'jià', hv:'giả', vi:'kỳ nghỉ; (jiǎ) giả', pos:'chữ Hán'},
  {zh:'运', pinyin:'yùn', hv:'vận', vi:'vận chuyển; vận động', pos:'chữ Hán'},
  {zh:'谢', pinyin:'xiè', hv:'tạ', vi:'cảm ơn', pos:'chữ Hán'},
  {zh:'靠', pinyin:'kào', hv:'kháo', vi:'dựa vào', pos:'chữ Hán'},
  {zh:'细', pinyin:'xì', hv:'tế', vi:'nhỏ, mảnh; tỉ mỉ', pos:'chữ Hán'},
  {zh:'爆', pinyin:'bào', hv:'bạo', vi:'nổ bùng', pos:'chữ Hán'},
  {zh:'故', pinyin:'gù', hv:'cố', vi:'cũ, cố; nguyên do', pos:'chữ Hán'},
  {zh:'事', pinyin:'shì', hv:'sự', vi:'việc, chuyện', pos:'chữ Hán'},
  {zh:'决', pinyin:'jué', hv:'quyết', vi:'quyết định', pos:'chữ Hán'},
  {zh:'定', pinyin:'dìng', hv:'định', vi:'định, ổn định', pos:'chữ Hán'},
  {zh:'扫', pinyin:'sǎo', hv:'tảo', vi:'quét', pos:'chữ Hán'},
  {zh:'收', pinyin:'shōu', hv:'thu', vi:'thu, nhận, cất', pos:'chữ Hán'},
  {zh:'结', pinyin:'jié', hv:'kết', vi:'kết, buộc; kết quả', pos:'chữ Hán'},
  {zh:'超', pinyin:'chāo', hv:'siêu', vi:'vượt quá', pos:'chữ Hán'},
  {zh:'且', pinyin:'qiě', hv:'thả', vi:'vả lại, hơn nữa', pos:'chữ Hán'},
  {zh:'价', pinyin:'jià', hv:'giá', vi:'giá cả', pos:'chữ Hán'},
  {zh:'闹', pinyin:'nào', hv:'náo', vi:'ồn ào, náo nhiệt', pos:'chữ Hán'},
  {zh:'实', pinyin:'shí', hv:'thực', vi:'thật, thực tế', pos:'chữ Hán'},
  {zh:'惯', pinyin:'guàn', hv:'quán', vi:'quen (习惯)', pos:'chữ Hán'},
  {zh:'申', pinyin:'shēn', hv:'thân', vi:'trình bày, xin', pos:'chữ Hán'},
  {zh:'退', pinyin:'tuì', hv:'thoái', vi:'lùi; trả lại', pos:'chữ Hán'},
  {zh:'评', pinyin:'píng', hv:'bình', vi:'bình luận, đánh giá', pos:'chữ Hán'},
  {zh:'成', pinyin:'chéng', hv:'thành', vi:'thành, trở thành', pos:'chữ Hán'},
  {zh:'胎', pinyin:'tāi', hv:'thai', vi:'bào thai; lốp, săm xe', pos:'chữ Hán'},
  {zh:'隔', pinyin:'gé', hv:'cách', vi:'ngăn cách', pos:'chữ Hán'},
  {zh:'壁', pinyin:'bì', hv:'bích', vi:'vách, tường', pos:'chữ Hán'},
  {zh:'差', pinyin:'chà', hv:'sai', vi:'kém, thiếu; (chāi) công tác', pos:'chữ Hán'},
  {zh:'活', pinyin:'huó', hv:'hoạt', vi:'sống; linh hoạt', pos:'chữ Hán'},
  {zh:'麻', pinyin:'má', hv:'ma', vi:'cây gai; tê (麻烦: phiền)', pos:'chữ Hán'},
  {zh:'烦', pinyin:'fán', hv:'phiền', vi:'phiền, bực', pos:'chữ Hán'},
  {zh:'其', pinyin:'qí', hv:'kỳ', vi:'của nó, đó (其实: thật ra)', pos:'chữ Hán'},
  {zh:'特', pinyin:'tè', hv:'đặc', vi:'đặc biệt', pos:'chữ Hán'},
  {zh:'散', pinyin:'sàn', hv:'tán', vi:'tản ra, chia lìa', pos:'chữ Hán'},
  {zh:'拒', pinyin:'jù', hv:'cự', vi:'từ chối, cự tuyệt', pos:'chữ Hán'},
  {zh:'绝', pinyin:'jué', hv:'tuyệt', vi:'dứt, tuyệt đối', pos:'chữ Hán'},
  {zh:'貌', pinyin:'mào', hv:'mạo', vi:'dáng vẻ (礼貌: lễ phép)', pos:'chữ Hán'},
  {zh:'尊', pinyin:'zūn', hv:'tôn', vi:'tôn kính', pos:'chữ Hán'},

  /* ---------- Tính chất · cảm xúc ---------- */
  {zh:'幸', pinyin:'xìng', hv:'hạnh', vi:'may mắn, hạnh phúc', pos:'chữ Hán'},
  {zh:'福', pinyin:'fú', hv:'phúc', vi:'phúc, may mắn', pos:'chữ Hán'},
  {zh:'情', pinyin:'qíng', hv:'tình', vi:'tình cảm, tình hình', pos:'chữ Hán'},
  {zh:'心', pinyin:'xīn', hv:'tâm', vi:'tim; lòng', pos:'chữ Hán'},
  {zh:'觉', pinyin:'jué', hv:'giác', vi:'cảm thấy; (jiào) giấc ngủ', pos:'chữ Hán'},
  {zh:'错', pinyin:'cuò', hv:'thác', vi:'sai; (不错) khá tốt', pos:'chữ Hán'},
  {zh:'宜', pinyin:'yí', hv:'nghi', vi:'thích hợp (便宜: rẻ)', pos:'chữ Hán'},
  {zh:'附', pinyin:'fù', hv:'phụ', vi:'kèm theo, gần (附近)', pos:'chữ Hán'},
  {zh:'对', pinyin:'duì', hv:'đối', vi:'đúng; đối với', pos:'chữ Hán'},
  {zh:'虽', pinyin:'suī', hv:'tuy', vi:'tuy, mặc dù', pos:'chữ Hán'},
  {zh:'然', pinyin:'rán', hv:'nhiên', vi:'như vậy, thế nhưng', pos:'chữ Hán'},
  {zh:'因', pinyin:'yīn', hv:'nhân', vi:'nguyên nhân, bởi vì', pos:'chữ Hán'},
  {zh:'为', pinyin:'wèi', hv:'vị', vi:'vì, cho; (wéi) làm', pos:'chữ Hán'},
  {zh:'如', pinyin:'rú', hv:'như', vi:'như, giống như', pos:'chữ Hán'},
  {zh:'什', pinyin:'shén', hv:'thập', vi:'cái gì (什么)', pos:'chữ Hán'},
  {zh:'么', pinyin:'me', hv:'ma', vi:'trợ từ nghi vấn (什么, 怎么)', pos:'chữ Hán'},
  {zh:'怎', pinyin:'zěn', hv:'chẩm', vi:'thế nào (怎么)', pos:'chữ Hán'},
  {zh:'吧', pinyin:'ba', hv:'ba', vi:'trợ từ đề nghị: … nhé', pos:'chữ Hán'},
  {zh:'烟', pinyin:'yān', hv:'yên', vi:'khói; thuốc lá', pos:'chữ Hán'},
  {zh:'王', pinyin:'wáng', hv:'vương', vi:'vua; họ Vương', pos:'chữ Hán'},
  {zh:'明', pinyin:'míng', hv:'minh', vi:'sáng, rõ; ngày mai (明天)', pos:'chữ Hán'},
  {zh:'于', pinyin:'yú', hv:'vu', vi:'ở, tại, đối với (văn viết)', pos:'chữ Hán'},
  {zh:'住', pinyin:'zhù', hv:'trú', vi:'ở, cư trú; dừng lại', pos:'chữ Hán'},
  {zh:'同', pinyin:'tóng', hv:'đồng', vi:'giống nhau, cùng', pos:'chữ Hán'}
];

if (typeof window !== 'undefined') window.CHARS_ZH = CHARS_ZH;
if (typeof module !== 'undefined' && module.exports) module.exports = { CHARS_ZH };
