/* ============================================================
   LangLab — TIẾNG NHẬT: khoá học N5 → N2 (A1 → B2), tự soạn cho người Việt theo khung JLPT
   và trình tự sư phạm quen thuộc (chào hỏi → chỉ định → thời gian → động từ ます → tính từ → tồn tại → đếm → て形 → ない形 → 辞書形 → た形 → 普通形…).
   Quy ước văn bản: furigana ghi 漢字[かな]; các từ trong câu tách bằng dấu cách để bấm tra được (hiển thị sẽ ghép liền).
   Từ vựng: jp (kanji nếu có), kana, romaji, vi, pos, g (nhóm động từ 1/2/3), note.
   Nhân vật: クアン (Quân, sinh viên Việt Nam ở Hà Nội), 田中 (Tanaka), 鈴木先生 (cô Suzuki), 山田 (Yamada), リン (Linh).
   ============================================================ */
const COURSE_JA = {
  levels: [
    { id:'n5', jp:'N5 · A1', vi:'N5 · Sơ cấp (A1)', lessons:20, status:'active' },
    { id:'n4', jp:'N4 · A2', vi:'N4 · Sơ trung cấp (A2)', lessons:20, status:'soon' },
    { id:'n3', jp:'N3 · B1', vi:'N3 · Trung cấp (B1)', lessons:20, status:'soon' },
    { id:'n2', jp:'N2 · B2', vi:'N2 · Trung cao cấp (B2)', lessons:20, status:'soon' }
  ],
  lessons: [
    /* ================= N5 ================= */
    {
      level:'n5', no:1, jp:'はじめまして', vi:'Rất hân hạnh — giới thiệu bản thân',
      skill:'Chào hỏi, tự giới thiệu, hỏi tên/quốc tịch/nghề nghiệp; câu 〜は〜です',
      kanji:['人','日','本','学','生'],
      grammar:[
        { form:'N1 は N2 です', vi:'N1 là N2', note:'は (đọc «wa») đánh dấu chủ đề; です kết câu lịch sự, không đổi theo ngôi. Phủ định: じゃありません (khẩu ngữ) / ではありません (trang trọng).', ex:{ jp:'わたし は ベトナム人[じん] です 。', vi:'Tôi là người Việt Nam.' } },
        { form:'N1 は N2 ですか', vi:'N1 có phải là N2 không?', note:'Thêm か cuối câu để hỏi, ngữ điệu lên. Trả lời: はい、〜です / いいえ、〜じゃありません.', ex:{ jp:'田中[たなか]さん は 学生[がくせい] ですか 。 — いいえ 、 会社員[かいしゃいん] です 。', vi:'Anh Tanaka là sinh viên phải không? — Không, tôi là nhân viên công ty.' } },
        { form:'N1 の N2', vi:'N2 của N1 (thuộc về, thuộc tổ chức)', note:'の nối hai danh từ: ハノイ大学の学生 (sinh viên ĐH Hà Nội), 日本の車 (xe Nhật).', ex:{ jp:'わたし は ハノイ大学[だいがく] の 学生[がくせい] です 。', vi:'Tôi là sinh viên Đại học Hà Nội.' } }
      ],
      vocab:[
        { jp:'わたし', kana:'わたし', romaji:'watashi', vi:'tôi', pos:'đại từ', note:'Nam giới thân mật: ぼく; trang trọng: わたくし' },
        { jp:'あなた', kana:'あなた', romaji:'anata', vi:'bạn, anh/chị', pos:'đại từ', note:'Ít dùng với người quen; gọi bằng tên + さん lịch sự hơn' },
        { jp:'〜さん', kana:'さん', romaji:'-san', vi:'anh/chị/ông/bà (hậu tố tên)', pos:'hậu tố', note:'Không dùng cho chính mình' },
        { jp:'〜人', kana:'じん', romaji:'-jin', vi:'người (nước)', pos:'hậu tố', note:'ベトナム人, 日本人, アメリカ人' },
        { jp:'日本', kana:'にほん', romaji:'Nihon', vi:'Nhật Bản', pos:'danh từ' },
        { jp:'ベトナム', kana:'ベトナム', romaji:'Betonamu', vi:'Việt Nam', pos:'danh từ' },
        { jp:'学生', kana:'がくせい', romaji:'gakusei', vi:'sinh viên, học sinh', pos:'danh từ' },
        { jp:'先生', kana:'せんせい', romaji:'sensei', vi:'thầy/cô giáo', pos:'danh từ', note:'Gọi người khác; nói về nghề của mình dùng 教師 (きょうし)' },
        { jp:'会社員', kana:'かいしゃいん', romaji:'kaishain', vi:'nhân viên công ty', pos:'danh từ' },
        { jp:'医者', kana:'いしゃ', romaji:'isha', vi:'bác sĩ', pos:'danh từ' },
        { jp:'大学', kana:'だいがく', romaji:'daigaku', vi:'trường đại học', pos:'danh từ' },
        { jp:'はじめまして', kana:'はじめまして', romaji:'hajimemashite', vi:'rất hân hạnh (lần đầu gặp)', pos:'cụm chào' },
        { jp:'どうぞよろしく', kana:'どうぞよろしく', romaji:'dōzo yoroshiku', vi:'mong được giúp đỡ', pos:'cụm chào', note:'Đầy đủ: どうぞよろしくお願いします' },
        { jp:'はい', kana:'はい', romaji:'hai', vi:'vâng, có', pos:'thán từ' },
        { jp:'いいえ', kana:'いいえ', romaji:'iie', vi:'không', pos:'thán từ' },
        { jp:'おはようございます', kana:'おはようございます', romaji:'ohayō gozaimasu', vi:'chào buổi sáng', pos:'cụm chào' },
        { jp:'こんにちは', kana:'こんにちは', romaji:'konnichiwa', vi:'xin chào (ban ngày)', pos:'cụm chào', note:'は đọc «wa»' },
        { jp:'こんばんは', kana:'こんばんは', romaji:'konbanwa', vi:'chào buổi tối', pos:'cụm chào' },
        { jp:'すみません', kana:'すみません', romaji:'sumimasen', vi:'xin lỗi; xin phép', pos:'cụm' },
        { jp:'ありがとうございます', kana:'ありがとうございます', romaji:'arigatō gozaimasu', vi:'cảm ơn', pos:'cụm chào' }
      ],
      dialogue:[
        { sp:'A', jp:'はじめまして 。 田中[たなか] です 。 どうぞ よろしく 。', vi:'Rất hân hạnh. Tôi là Tanaka. Mong được giúp đỡ.' },
        { sp:'B', jp:'はじめまして 。 わたし は クアン です 。 ベトナム人[じん] です 。', vi:'Rất hân hạnh. Tôi là Quân. Tôi là người Việt Nam.' },
        { sp:'A', jp:'クアンさん は 学生[がくせい] ですか 。', vi:'Quân là sinh viên phải không?' },
        { sp:'B', jp:'はい 、 ハノイ大学[だいがく] の 学生[がくせい] です 。 田中[たなか]さん は ？', vi:'Vâng, tôi là sinh viên Đại học Hà Nội. Còn anh Tanaka?' },
        { sp:'A', jp:'わたし は 会社員[かいしゃいん] です 。 どうぞ よろしく お願[ねが]いします 。', vi:'Tôi là nhân viên công ty. Rất mong được giúp đỡ.' }
      ]
    },
    {
      level:'n5', no:2, jp:'これは何ですか', vi:'Cái này là gì? — chỉ định vật',
      skill:'これ/それ/あれ, この/その/あの, hỏi «cái gì», sở hữu の, 〜も; số 0–100',
      kanji:['一','二','三','四','五','六','七','八','九','十','百','何'],
      grammar:[
        { form:'これ / それ / あれ は N です', vi:'Cái này / cái đó / cái kia là N', note:'これ gần người nói, それ gần người nghe, あれ xa cả hai. Hỏi vật: 何 (なん/なに) ですか.', ex:{ jp:'これ は 本[ほん] です 。 それ は 何[なん] ですか 。', vi:'Cái này là sách. Cái đó là gì?' } },
        { form:'この / その / あの N', vi:'N này / đó / kia', note:'Bắt buộc có danh từ đi sau: この本 (quyển sách này). Không nói ×この は.', ex:{ jp:'この 本[ほん] は わたし の です 。', vi:'Quyển sách này là của tôi.' } },
        { form:'N も', vi:'N cũng', note:'も thay cho は khi nội dung giống câu trước: 田中さんも学生です.', ex:{ jp:'リンさん は 学生[がくせい] です 。 クアンさん も 学生[がくせい] です 。', vi:'Linh là sinh viên. Quân cũng là sinh viên.' } },
        { form:'〜の (sở hữu, lược danh từ)', vi:'của …', note:'わたしの本 → わたしの (cái của tôi). Hỏi chủ: だれの〜ですか.', ex:{ jp:'この かばん は だれ の ですか 。 — 山田[やまだ]さん の です 。', vi:'Cái cặp này của ai? — Của anh Yamada.' } }
      ],
      vocab:[
        { jp:'これ', kana:'これ', romaji:'kore', vi:'cái này', pos:'đại từ chỉ định' },
        { jp:'それ', kana:'それ', romaji:'sore', vi:'cái đó', pos:'đại từ chỉ định' },
        { jp:'あれ', kana:'あれ', romaji:'are', vi:'cái kia', pos:'đại từ chỉ định' },
        { jp:'この', kana:'この', romaji:'kono', vi:'… này', pos:'từ chỉ định (+ danh từ)' },
        { jp:'その', kana:'その', romaji:'sono', vi:'… đó', pos:'từ chỉ định (+ danh từ)' },
        { jp:'あの', kana:'あの', romaji:'ano', vi:'… kia', pos:'từ chỉ định (+ danh từ)' },
        { jp:'何', kana:'なん', romaji:'nan / nani', vi:'cái gì', pos:'đại từ nghi vấn', note:'なん trước です/の/đếm; なに trước を/が' },
        { jp:'だれ', kana:'だれ', romaji:'dare', vi:'ai', pos:'đại từ nghi vấn', note:'Lịch sự: どなた' },
        { jp:'本', kana:'ほん', romaji:'hon', vi:'sách', pos:'danh từ' },
        { jp:'辞書', kana:'じしょ', romaji:'jisho', vi:'từ điển', pos:'danh từ' },
        { jp:'ノート', kana:'ノート', romaji:'nōto', vi:'vở', pos:'danh từ' },
        { jp:'鉛筆', kana:'えんぴつ', romaji:'enpitsu', vi:'bút chì', pos:'danh từ' },
        { jp:'ペン', kana:'ペン', romaji:'pen', vi:'bút', pos:'danh từ' },
        { jp:'かばん', kana:'かばん', romaji:'kaban', vi:'cặp, túi', pos:'danh từ' },
        { jp:'時計', kana:'とけい', romaji:'tokei', vi:'đồng hồ', pos:'danh từ' },
        { jp:'傘', kana:'かさ', romaji:'kasa', vi:'ô, dù', pos:'danh từ' },
        { jp:'携帯電話', kana:'けいたいでんわ', romaji:'keitai denwa', vi:'điện thoại di động', pos:'danh từ', note:'Khẩu ngữ: けいたい / スマホ' },
        { jp:'机', kana:'つくえ', romaji:'tsukue', vi:'bàn học', pos:'danh từ' },
        { jp:'椅子', kana:'いす', romaji:'isu', vi:'ghế', pos:'danh từ' },
        { jp:'日本語', kana:'にほんご', romaji:'nihongo', vi:'tiếng Nhật', pos:'danh từ' },
        { jp:'英語', kana:'えいご', romaji:'eigo', vi:'tiếng Anh', pos:'danh từ' },
        { jp:'そうです', kana:'そうです', romaji:'sō desu', vi:'đúng vậy', pos:'cụm' },
        { jp:'違います', kana:'ちがいます', romaji:'chigaimasu', vi:'không phải, khác', pos:'cụm', note:'Động từ 違う (nhóm I)' }
      ],
      dialogue:[
        { sp:'A', jp:'すみません 、 これ は 何[なん] ですか 。', vi:'Xin lỗi, cái này là gì?' },
        { sp:'B', jp:'それ は 日本語[にほんご] の 辞書[じしょ] です 。', vi:'Cái đó là từ điển tiếng Nhật.' },
        { sp:'A', jp:'だれ の 辞書[じしょ] ですか 。', vi:'Từ điển của ai vậy?' },
        { sp:'B', jp:'わたし の です 。 あの かばん も わたし の です 。', vi:'Của tôi. Cái cặp kia cũng của tôi.' },
        { sp:'A', jp:'この ペン は ？', vi:'Còn cây bút này?' },
        { sp:'B', jp:'それ は 田中[たなか]さん の です 。', vi:'Cái đó của anh Tanaka.' }
      ]
    },
    {
      level:'n5', no:3, jp:'ここはどこですか', vi:'Đây là đâu? — nơi chốn và giá cả',
      skill:'ここ/そこ/あそこ/こちら, どこ/どちら, 〜の〜 (nước, hãng), hỏi giá いくら; số lớn 百・千・万',
      kanji:['千','万','円','国','大','小','中'],
      grammar:[
        { form:'ここ / そこ / あそこ / こちら', vi:'ở đây / ở đó / ở kia (lịch sự: こちら…)', note:'Hỏi: どこ (đâu) — lịch sự: どちら. こちら cũng dùng để giới thiệu người: こちらは田中さんです.', ex:{ jp:'トイレ は どこ ですか 。 — あそこ です 。', vi:'Nhà vệ sinh ở đâu? — Ở đằng kia.' } },
        { form:'N1 は N2 (nơi) です', vi:'N1 ở N2', note:'Chỉ vị trí bằng です: 田中さんは会社です (anh Tanaka đang ở công ty).', ex:{ jp:'鈴木[すずき]先生[せんせい] は 教室[きょうしつ] です 。', vi:'Cô Suzuki đang ở lớp học.' } },
        { form:'どこの / 何の N', vi:'N của nước nào / N loại gì', note:'これはどこの車ですか — 日本の車です. 何の本ですか — 日本語の本です.', ex:{ jp:'これ は どこ の 時計[とけい] ですか 。 — スイス の 時計[とけい] です 。', vi:'Đồng hồ này của nước nào? — Của Thụy Sĩ.' } },
        { form:'いくらですか', vi:'Bao nhiêu tiền?', note:'Số + 円 (えん). 百 hyaku, 千 sen, 万 man: 3.500円 = 三千五百円; 12.000円 = 一万二千円. Biến âm: 300 さんびゃく, 600 ろっぴゃく, 800 はっぴゃく, 3000 さんぜん, 8000 はっせん.', ex:{ jp:'この かばん は いくら ですか 。 — 三千五百円[さんぜんごひゃくえん] です 。', vi:'Cái cặp này bao nhiêu? — 3.500 yên.' } }
      ],
      vocab:[
        { jp:'ここ', kana:'ここ', romaji:'koko', vi:'ở đây', pos:'đại từ nơi chốn' },
        { jp:'そこ', kana:'そこ', romaji:'soko', vi:'ở đó', pos:'đại từ nơi chốn' },
        { jp:'あそこ', kana:'あそこ', romaji:'asoko', vi:'ở kia', pos:'đại từ nơi chốn' },
        { jp:'どこ', kana:'どこ', romaji:'doko', vi:'ở đâu', pos:'đại từ nghi vấn' },
        { jp:'こちら', kana:'こちら', romaji:'kochira', vi:'phía này, đây (lịch sự)', pos:'đại từ', note:'そちら / あちら / どちら' },
        { jp:'教室', kana:'きょうしつ', romaji:'kyōshitsu', vi:'lớp học, phòng học', pos:'danh từ' },
        { jp:'食堂', kana:'しょくどう', romaji:'shokudō', vi:'nhà ăn, căng tin', pos:'danh từ' },
        { jp:'事務所', kana:'じむしょ', romaji:'jimusho', vi:'văn phòng', pos:'danh từ' },
        { jp:'トイレ', kana:'トイレ', romaji:'toire', vi:'nhà vệ sinh', pos:'danh từ', note:'お手洗い (おてあらい) lịch sự hơn' },
        { jp:'受付', kana:'うけつけ', romaji:'uketsuke', vi:'quầy lễ tân', pos:'danh từ' },
        { jp:'エレベーター', kana:'エレベーター', romaji:'erebētā', vi:'thang máy', pos:'danh từ' },
        { jp:'階段', kana:'かいだん', romaji:'kaidan', vi:'cầu thang', pos:'danh từ' },
        { jp:'〜階', kana:'かい', romaji:'-kai', vi:'tầng …', pos:'lượng từ', note:'1階 いっかい, 3階 さんがい, 何階 なんがい' },
        { jp:'国', kana:'くに', romaji:'kuni', vi:'nước, quê hương', pos:'danh từ' },
        { jp:'会社', kana:'かいしゃ', romaji:'kaisha', vi:'công ty', pos:'danh từ' },
        { jp:'銀行', kana:'ぎんこう', romaji:'ginkō', vi:'ngân hàng', pos:'danh từ' },
        { jp:'郵便局', kana:'ゆうびんきょく', romaji:'yūbinkyoku', vi:'bưu điện', pos:'danh từ' },
        { jp:'車', kana:'くるま', romaji:'kuruma', vi:'ô tô', pos:'danh từ' },
        { jp:'いくら', kana:'いくら', romaji:'ikura', vi:'bao nhiêu tiền', pos:'nghi vấn' },
        { jp:'〜円', kana:'えん', romaji:'-en', vi:'yên', pos:'đơn vị tiền' },
        { jp:'百', kana:'ひゃく', romaji:'hyaku', vi:'một trăm', pos:'số từ' },
        { jp:'千', kana:'せん', romaji:'sen', vi:'một nghìn', pos:'số từ' },
        { jp:'万', kana:'まん', romaji:'man', vi:'mười nghìn', pos:'số từ', note:'Đếm theo vạn: 10万 = 100.000' },
        { jp:'高い', kana:'たかい', romaji:'takai', vi:'đắt; cao', pos:'tính từ い' },
        { jp:'安い', kana:'やすい', romaji:'yasui', vi:'rẻ', pos:'tính từ い' }
      ],
      dialogue:[
        { sp:'A', jp:'すみません 、 食堂[しょくどう] は どこ ですか 。', vi:'Xin lỗi, nhà ăn ở đâu ạ?' },
        { sp:'B', jp:'食堂[しょくどう] は 二階[にかい] です 。 エレベーター は あそこ です 。', vi:'Nhà ăn ở tầng hai. Thang máy ở đằng kia.' },
        { sp:'A', jp:'ありがとうございます 。 あのう 、 これ は どこ の お茶[ちゃ] ですか 。', vi:'Cảm ơn. À, trà này của nước nào vậy?' },
        { sp:'B', jp:'ベトナム の お茶[ちゃ] です 。', vi:'Trà Việt Nam.' },
        { sp:'A', jp:'いくら ですか 。', vi:'Bao nhiêu tiền?' },
        { sp:'B', jp:'五百円[ごひゃくえん] です 。', vi:'500 yên.' }
      ]
    },
    {
      level:'n5', no:4, jp:'今何時ですか', vi:'Bây giờ mấy giờ? — thời gian và động từ ます',
      skill:'Giờ phút, thứ trong tuần, から〜まで; động từ ます/ません/ました/ませんでした',
      kanji:['今','時','分','半','月','火','水','木','金','土','曜'],
      grammar:[
        { form:'今 〜時 〜分 です', vi:'Bây giờ là … giờ … phút', note:'Giờ: 4時 よじ, 7時 しちじ, 9時 くじ. Phút: 1分 いっぷん, 3分 さんぷん, 6分 ろっぷん, 8分 はっぷん, 10分 じゅっぷん; 半 = rưỡi. Sáng/chiều: 午前 / 午後.', ex:{ jp:'今[いま] 何時[なんじ] ですか 。 — 午後[ごご] 四時[よじ] 半[はん] です 。', vi:'Bây giờ mấy giờ? — 4 giờ rưỡi chiều.' } },
        { form:'V ます / V ません / V ました / V ませんでした', vi:'Động từ lịch sự: hiện tại-tương lai / phủ định / quá khứ / quá khứ phủ định', note:'Thể ます dùng cho thói quen và tương lai; quá khứ ました. Chủ ngữ thường lược nếu đã rõ.', ex:{ jp:'わたし は 毎日[まいにち] 六時[ろくじ] に 起[お]きます 。 昨日[きのう] は 働[はたら]きませんでした 。', vi:'Mỗi ngày tôi dậy lúc 6 giờ. Hôm qua tôi không làm việc.' } },
        { form:'N (thời gian) に V', vi:'làm gì lúc/vào …', note:'に đi với mốc thời gian có số (時, 日, 曜日 tuỳ chọn); không dùng に với 今日, 明日, 毎日, 朝, 晩.', ex:{ jp:'日曜日[にちようび] に 友達[ともだち] と 会[あ]います 。', vi:'Chủ nhật tôi gặp bạn.' } },
        { form:'N1 から N2 まで', vi:'từ N1 đến N2 (thời gian, nơi chốn)', note:'Có thể dùng riêng: 9時から働きます / 5時まで働きます.', ex:{ jp:'銀行[ぎんこう] は 九時[くじ] から 三時[さんじ] まで です 。', vi:'Ngân hàng mở từ 9 giờ đến 3 giờ.' } }
      ],
      vocab:[
        { jp:'今', kana:'いま', romaji:'ima', vi:'bây giờ', pos:'danh từ / trạng từ' },
        { jp:'〜時', kana:'じ', romaji:'-ji', vi:'… giờ', pos:'lượng từ' },
        { jp:'〜分', kana:'ふん / ぷん', romaji:'-fun / -pun', vi:'… phút', pos:'lượng từ' },
        { jp:'半', kana:'はん', romaji:'han', vi:'rưỡi', pos:'danh từ' },
        { jp:'午前', kana:'ごぜん', romaji:'gozen', vi:'buổi sáng (AM)', pos:'danh từ' },
        { jp:'午後', kana:'ごご', romaji:'gogo', vi:'buổi chiều (PM)', pos:'danh từ' },
        { jp:'朝', kana:'あさ', romaji:'asa', vi:'buổi sáng', pos:'danh từ' },
        { jp:'昼', kana:'ひる', romaji:'hiru', vi:'buổi trưa, ban ngày', pos:'danh từ' },
        { jp:'晩', kana:'ばん', romaji:'ban', vi:'buổi tối', pos:'danh từ', note:'夜 (よる) = đêm' },
        { jp:'今日', kana:'きょう', romaji:'kyō', vi:'hôm nay', pos:'danh từ' },
        { jp:'明日', kana:'あした', romaji:'ashita', vi:'ngày mai', pos:'danh từ' },
        { jp:'昨日', kana:'きのう', romaji:'kinō', vi:'hôm qua', pos:'danh từ' },
        { jp:'毎日', kana:'まいにち', romaji:'mainichi', vi:'mỗi ngày', pos:'danh từ' },
        { jp:'月曜日', kana:'げつようび', romaji:'getsuyōbi', vi:'thứ Hai', pos:'danh từ', note:'火 thứ Ba, 水 thứ Tư, 木 thứ Năm, 金 thứ Sáu, 土 thứ Bảy, 日 Chủ nhật; 何曜日 thứ mấy' },
        { jp:'日曜日', kana:'にちようび', romaji:'nichiyōbi', vi:'Chủ nhật', pos:'danh từ' },
        { jp:'起きる', kana:'おきる', romaji:'okiru', vi:'thức dậy', pos:'động từ nhóm II', g:'2' },
        { jp:'寝る', kana:'ねる', romaji:'neru', vi:'đi ngủ', pos:'động từ nhóm II', g:'2' },
        { jp:'働く', kana:'はたらく', romaji:'hataraku', vi:'làm việc', pos:'động từ nhóm I', g:'1' },
        { jp:'休む', kana:'やすむ', romaji:'yasumu', vi:'nghỉ', pos:'động từ nhóm I', g:'1' },
        { jp:'勉強する', kana:'べんきょうする', romaji:'benkyō suru', vi:'học', pos:'động từ nhóm III', g:'3' },
        { jp:'終わる', kana:'おわる', romaji:'owaru', vi:'kết thúc', pos:'động từ nhóm I', g:'1' },
        { jp:'始まる', kana:'はじまる', romaji:'hajimaru', vi:'bắt đầu (tự thân)', pos:'động từ nhóm I', g:'1' },
        { jp:'会う', kana:'あう', romaji:'au', vi:'gặp (人に会う)', pos:'động từ nhóm I', g:'1' },
        { jp:'友達', kana:'ともだち', romaji:'tomodachi', vi:'bạn bè', pos:'danh từ' },
        { jp:'授業', kana:'じゅぎょう', romaji:'jugyō', vi:'giờ học, tiết học', pos:'danh từ' }
      ],
      dialogue:[
        { sp:'A', jp:'クアンさん 、 今[いま] 何時[なんじ] ですか 。', vi:'Quân ơi, bây giờ mấy giờ?' },
        { sp:'B', jp:'八時[はちじ] 十五分[じゅうごふん] です 。 授業[じゅぎょう] は 何時[なんじ] から ですか 。', vi:'8 giờ 15. Giờ học bắt đầu từ mấy giờ?' },
        { sp:'A', jp:'八時[はちじ] 半[はん] から 十二時[じゅうにじ] まで です 。', vi:'Từ 8 rưỡi đến 12 giờ.' },
        { sp:'B', jp:'毎日[まいにち] 何時[なんじ] に 起[お]きますか 。', vi:'Mỗi ngày bạn dậy lúc mấy giờ?' },
        { sp:'A', jp:'六時[ろくじ] に 起[お]きます 。 昨日[きのう] は 十一時[じゅういちじ] に 寝[ね]ました 。', vi:'6 giờ. Hôm qua tôi ngủ lúc 11 giờ.' }
      ]
    },
    {
      level:'n5', no:5, jp:'どこへ行きますか', vi:'Đi đâu? — di chuyển và ngày tháng',
      skill:'行きます・来ます・帰ります với へ, phương tiện で, cùng ai と, いつ, 〜ましょう; ngày tháng, sinh nhật',
      kanji:['行','来','帰','年','日','何','前','後'],
      grammar:[
        { form:'N (nơi) へ 行きます / 来ます / 帰ります', vi:'đi / đến / về đâu', note:'へ (đọc «e») chỉ hướng; cũng dùng に. Không đi đâu: どこへも行きません.', ex:{ jp:'日曜日[にちようび] に 京都[きょうと] へ 行[い]きます 。', vi:'Chủ nhật tôi đi Kyoto.' } },
        { form:'N (phương tiện) で 行きます', vi:'đi bằng …', note:'電車で, バスで, 自転車で; đi bộ: 歩いて (không dùng で).', ex:{ jp:'バス で 大学[だいがく] へ 来[き]ます 。', vi:'Tôi đến trường bằng xe buýt.' } },
        { form:'N (người) と V', vi:'làm gì cùng với ai', note:'Một mình: 一人で.', ex:{ jp:'友達[ともだち] と 映画[えいが] を 見[み]ます 。', vi:'Tôi xem phim với bạn.' } },
        { form:'いつ〜ますか · 〜月〜日', vi:'Khi nào? Ngày tháng', note:'Tháng: 4月 しがつ, 7月 しちがつ, 9月 くがつ. Ngày 1–10 và 14, 20, 24 đọc đặc biệt: ついたち, ふつか, みっか, よっか, いつか, むいか, なのか, ようか, ここのか, とおか, じゅうよっか, はつか, にじゅうよっか.', ex:{ jp:'誕生日[たんじょうび] は いつ ですか 。 — 四月[しがつ] 二十日[はつか] です 。', vi:'Sinh nhật bạn khi nào? — Ngày 20 tháng 4.' } },
        { form:'V ましょう', vi:'Chúng ta hãy … (rủ rê, đề nghị)', note:'Đáp lời rủ: ええ、〜ましょう.', ex:{ jp:'一緒[いっしょ]に 帰[かえ]りましょう 。', vi:'Chúng ta cùng về nhé.' } }
      ],
      vocab:[
        { jp:'行く', kana:'いく', romaji:'iku', vi:'đi', pos:'động từ nhóm I', g:'1', note:'Thể て: 行って (ngoại lệ)' },
        { jp:'来る', kana:'くる', romaji:'kuru', vi:'đến', pos:'động từ nhóm III', g:'3', note:'来ます きます, 来ない こない' },
        { jp:'帰る', kana:'かえる', romaji:'kaeru', vi:'về (nhà)', pos:'động từ nhóm I', g:'1', note:'Nhóm I dù kết thúc -eru' },
        { jp:'学校', kana:'がっこう', romaji:'gakkō', vi:'trường học', pos:'danh từ' },
        { jp:'スーパー', kana:'スーパー', romaji:'sūpā', vi:'siêu thị', pos:'danh từ' },
        { jp:'駅', kana:'えき', romaji:'eki', vi:'nhà ga', pos:'danh từ' },
        { jp:'空港', kana:'くうこう', romaji:'kūkō', vi:'sân bay', pos:'danh từ' },
        { jp:'電車', kana:'でんしゃ', romaji:'densha', vi:'tàu điện', pos:'danh từ' },
        { jp:'バス', kana:'バス', romaji:'basu', vi:'xe buýt', pos:'danh từ' },
        { jp:'自転車', kana:'じてんしゃ', romaji:'jitensha', vi:'xe đạp', pos:'danh từ' },
        { jp:'バイク', kana:'バイク', romaji:'baiku', vi:'xe máy', pos:'danh từ' },
        { jp:'タクシー', kana:'タクシー', romaji:'takushī', vi:'taxi', pos:'danh từ' },
        { jp:'歩いて', kana:'あるいて', romaji:'aruite', vi:'đi bộ (thể て của 歩く)', pos:'trạng ngữ' },
        { jp:'一人で', kana:'ひとりで', romaji:'hitori de', vi:'một mình', pos:'trạng ngữ' },
        { jp:'一緒に', kana:'いっしょに', romaji:'issho ni', vi:'cùng nhau', pos:'trạng ngữ' },
        { jp:'いつ', kana:'いつ', romaji:'itsu', vi:'khi nào', pos:'nghi vấn' },
        { jp:'誕生日', kana:'たんじょうび', romaji:'tanjōbi', vi:'sinh nhật', pos:'danh từ' },
        { jp:'〜月', kana:'がつ', romaji:'-gatsu', vi:'tháng …', pos:'lượng từ' },
        { jp:'〜日', kana:'にち', romaji:'-nichi', vi:'ngày …', pos:'lượng từ' },
        { jp:'先週', kana:'せんしゅう', romaji:'senshū', vi:'tuần trước', pos:'danh từ', note:'今週 tuần này, 来週 tuần sau' },
        { jp:'来月', kana:'らいげつ', romaji:'raigetsu', vi:'tháng sau', pos:'danh từ', note:'先月 tháng trước, 今月 tháng này' },
        { jp:'去年', kana:'きょねん', romaji:'kyonen', vi:'năm ngoái', pos:'danh từ', note:'今年 ことし, 来年 らいねん' },
        { jp:'映画', kana:'えいが', romaji:'eiga', vi:'phim', pos:'danh từ' },
        { jp:'京都', kana:'きょうと', romaji:'Kyōto', vi:'Kyoto', pos:'danh từ riêng' }
      ],
      dialogue:[
        { sp:'A', jp:'クアンさん 、 明日[あした] どこ へ 行[い]きますか 。', vi:'Quân, mai bạn đi đâu?' },
        { sp:'B', jp:'友達[ともだち] と 京都[きょうと] へ 行[い]きます 。', vi:'Tôi đi Kyoto với bạn.' },
        { sp:'A', jp:'何[なん] で 行[い]きますか 。', vi:'Đi bằng gì?' },
        { sp:'B', jp:'電車[でんしゃ] で 行[い]きます 。 田中[たなか]さん も 一緒[いっしょ]に 行[い]きましょう 。', vi:'Đi bằng tàu điện. Anh Tanaka cũng đi cùng nhé.' },
        { sp:'A', jp:'いい です ね 。 何時[なんじ] に 帰[かえ]りますか 。', vi:'Hay đấy. Mấy giờ về?' },
        { sp:'B', jp:'晩[ばん] 八時[はちじ] ごろ 帰[かえ]ります 。', vi:'Khoảng 8 giờ tối về.' }
      ]
    },
    {
      level:'n5', no:6, jp:'何を食べますか', vi:'Ăn gì? — hành động với tân ngữ',
      skill:'Trợ từ を, nơi diễn ra hành động で, rủ 〜ませんか, 何を, 一緒に; ăn uống, mua sắm',
      kanji:['食','飲','見','聞','買','読','書','話'],
      grammar:[
        { form:'N を V', vi:'V (làm gì) N (tân ngữ)', note:'を (đọc «o») đánh dấu tân ngữ trực tiếp của ngoại động từ: ご飯を食べます, 本を読みます.', ex:{ jp:'朝[あさ] パン を 食[た]べます 。 コーヒー を 飲[の]みます 。', vi:'Buổi sáng tôi ăn bánh mì. Tôi uống cà phê.' } },
        { form:'N (nơi) で V', vi:'làm gì ở đâu', note:'で chỉ nơi xảy ra hành động (khác に chỉ nơi tồn tại và へ chỉ hướng).', ex:{ jp:'食堂[しょくどう] で 昼[ひる]ご飯[はん] を 食[た]べます 。', vi:'Tôi ăn trưa ở nhà ăn.' } },
        { form:'V ませんか', vi:'… không? (mời, rủ lịch sự)', note:'Mời: 一緒に食べませんか. Đáp: ええ、いいですね / すみません、ちょっと…', ex:{ jp:'一緒[いっしょ]に お茶[ちゃ] を 飲[の]みませんか 。', vi:'Cùng uống trà không?' } },
        { form:'何を / 何も', vi:'cái gì / không gì cả', note:'何も + phủ định: 何も食べません (không ăn gì cả).', ex:{ jp:'朝[あさ] 何[なに] を 食[た]べましたか 。 — 何[なに] も 食[た]べませんでした 。', vi:'Sáng bạn ăn gì? — Tôi không ăn gì cả.' } }
      ],
      vocab:[
        { jp:'食べる', kana:'たべる', romaji:'taberu', vi:'ăn', pos:'động từ nhóm II', g:'2' },
        { jp:'飲む', kana:'のむ', romaji:'nomu', vi:'uống', pos:'động từ nhóm I', g:'1' },
        { jp:'見る', kana:'みる', romaji:'miru', vi:'xem, nhìn', pos:'động từ nhóm II', g:'2' },
        { jp:'聞く', kana:'きく', romaji:'kiku', vi:'nghe; hỏi', pos:'động từ nhóm I', g:'1' },
        { jp:'読む', kana:'よむ', romaji:'yomu', vi:'đọc', pos:'động từ nhóm I', g:'1' },
        { jp:'書く', kana:'かく', romaji:'kaku', vi:'viết', pos:'động từ nhóm I', g:'1' },
        { jp:'買う', kana:'かう', romaji:'kau', vi:'mua', pos:'động từ nhóm I', g:'1' },
        { jp:'話す', kana:'はなす', romaji:'hanasu', vi:'nói chuyện', pos:'động từ nhóm I', g:'1' },
        { jp:'作る', kana:'つくる', romaji:'tsukuru', vi:'làm, nấu, chế tạo', pos:'động từ nhóm I', g:'1' },
        { jp:'する', kana:'する', romaji:'suru', vi:'làm', pos:'động từ nhóm III', g:'3' },
        { jp:'ご飯', kana:'ごはん', romaji:'gohan', vi:'cơm, bữa ăn', pos:'danh từ', note:'朝ご飯, 昼ご飯, 晩ご飯' },
        { jp:'パン', kana:'パン', romaji:'pan', vi:'bánh mì', pos:'danh từ' },
        { jp:'卵', kana:'たまご', romaji:'tamago', vi:'trứng', pos:'danh từ' },
        { jp:'肉', kana:'にく', romaji:'niku', vi:'thịt', pos:'danh từ' },
        { jp:'魚', kana:'さかな', romaji:'sakana', vi:'cá', pos:'danh từ' },
        { jp:'野菜', kana:'やさい', romaji:'yasai', vi:'rau', pos:'danh từ' },
        { jp:'果物', kana:'くだもの', romaji:'kudamono', vi:'hoa quả', pos:'danh từ' },
        { jp:'水', kana:'みず', romaji:'mizu', vi:'nước', pos:'danh từ' },
        { jp:'お茶', kana:'おちゃ', romaji:'ocha', vi:'trà', pos:'danh từ' },
        { jp:'コーヒー', kana:'コーヒー', romaji:'kōhī', vi:'cà phê', pos:'danh từ' },
        { jp:'牛乳', kana:'ぎゅうにゅう', romaji:'gyūnyū', vi:'sữa bò', pos:'danh từ' },
        { jp:'お酒', kana:'おさけ', romaji:'osake', vi:'rượu', pos:'danh từ' },
        { jp:'レストラン', kana:'レストラン', romaji:'resutoran', vi:'nhà hàng', pos:'danh từ' },
        { jp:'音楽', kana:'おんがく', romaji:'ongaku', vi:'âm nhạc', pos:'danh từ' },
        { jp:'テレビ', kana:'テレビ', romaji:'terebi', vi:'ti vi', pos:'danh từ' },
        { jp:'写真', kana:'しゃしん', romaji:'shashin', vi:'ảnh', pos:'danh từ', note:'写真を撮る (とる): chụp ảnh' },
        { jp:'手紙', kana:'てがみ', romaji:'tegami', vi:'thư', pos:'danh từ' },
        { jp:'いいですね', kana:'いいですね', romaji:'ii desu ne', vi:'hay đấy, được đấy', pos:'cụm' }
      ],
      dialogue:[
        { sp:'A', jp:'クアンさん 、 昼[ひる]ご飯[はん] は 何[なに] を 食[た]べますか 。', vi:'Quân ơi, trưa nay ăn gì?' },
        { sp:'B', jp:'食堂[しょくどう] で ラーメン を 食[た]べます 。 田中[たなか]さん は ？', vi:'Tôi ăn mì ramen ở nhà ăn. Còn anh Tanaka?' },
        { sp:'A', jp:'わたし は 何[なに] も 食[た]べません 。 コーヒー だけ 飲[の]みます 。', vi:'Tôi không ăn gì. Chỉ uống cà phê thôi.' },
        { sp:'B', jp:'そう ですか 。 じゃ 、 一緒[いっしょ]に コーヒー を 飲[の]みませんか 。', vi:'Vậy à. Thế thì cùng uống cà phê nhé?' },
        { sp:'A', jp:'ええ 、 いい です ね 。 駅[えき] の 前[まえ] の 店[みせ] で 飲[の]みましょう 。', vi:'Ừ, hay đấy. Uống ở quán trước ga nhé.' }
      ]
    },
    {
      level:'n5', no:7, jp:'あげます・もらいます', vi:'Cho và nhận — công cụ, người nhận',
      skill:'で (công cụ, ngôn ngữ), に (người nhận), から (từ ai), もう〜ました / まだ; quà tặng',
      kanji:['上','下','手','紙','語','電','話','母','父'],
      grammar:[
        { form:'N (công cụ / ngôn ngữ) で V', vi:'bằng (công cụ, ngôn ngữ)', note:'箸で食べます (ăn bằng đũa), 日本語で話します. Hỏi: 「〜」は日本語で何ですか.', ex:{ jp:'「cảm ơn」 は 日本語[にほんご] で 何[なん] ですか 。 — 「ありがとう」 です 。', vi:'«Cảm ơn» tiếng Nhật là gì? — Là «arigatō».' } },
        { form:'N (người) に あげます / 貸します / 教えます', vi:'cho / cho mượn / dạy ai', note:'に đánh dấu người nhận. 電話をかけます, 手紙を書きます cũng dùng に cho đối tượng.', ex:{ jp:'母[はは] に 花[はな] を あげました 。', vi:'Tôi tặng hoa cho mẹ.' } },
        { form:'N (người) に / から もらいます · 借ります · 習います', vi:'nhận / mượn / học từ ai', note:'Người cho ở に hoặc から; から bắt buộc khi người cho là tổ chức (会社から).', ex:{ jp:'田中[たなか]さん に 本[ほん] を もらいました 。', vi:'Tôi được anh Tanaka tặng sách.' } },
        { form:'もう V ました / まだ です', vi:'đã … rồi / chưa', note:'Hỏi: もう昼ご飯を食べましたか. Đáp: はい、もう食べました / いいえ、まだです (không nói ×まだ食べませんでした).', ex:{ jp:'もう 宿題[しゅくだい] を しましたか 。 — いいえ 、 まだ です 。', vi:'Bạn làm bài tập chưa? — Chưa.' } }
      ],
      vocab:[
        { jp:'あげる', kana:'あげる', romaji:'ageru', vi:'cho, tặng', pos:'động từ nhóm II', g:'2' },
        { jp:'もらう', kana:'もらう', romaji:'morau', vi:'nhận', pos:'động từ nhóm I', g:'1' },
        { jp:'貸す', kana:'かす', romaji:'kasu', vi:'cho mượn', pos:'động từ nhóm I', g:'1' },
        { jp:'借りる', kana:'かりる', romaji:'kariru', vi:'mượn', pos:'động từ nhóm II', g:'2' },
        { jp:'教える', kana:'おしえる', romaji:'oshieru', vi:'dạy, chỉ cho', pos:'động từ nhóm II', g:'2' },
        { jp:'習う', kana:'ならう', romaji:'narau', vi:'học (từ ai)', pos:'động từ nhóm I', g:'1' },
        { jp:'かける', kana:'かける', romaji:'kakeru', vi:'gọi (điện thoại)', pos:'động từ nhóm II', g:'2', note:'電話をかける' },
        { jp:'送る', kana:'おくる', romaji:'okuru', vi:'gửi', pos:'động từ nhóm I', g:'1' },
        { jp:'手', kana:'て', romaji:'te', vi:'tay', pos:'danh từ' },
        { jp:'箸', kana:'はし', romaji:'hashi', vi:'đũa', pos:'danh từ' },
        { jp:'スプーン', kana:'スプーン', romaji:'supūn', vi:'thìa', pos:'danh từ' },
        { jp:'花', kana:'はな', romaji:'hana', vi:'hoa', pos:'danh từ' },
        { jp:'プレゼント', kana:'プレゼント', romaji:'purezento', vi:'quà', pos:'danh từ' },
        { jp:'お土産', kana:'おみやげ', romaji:'omiyage', vi:'quà lưu niệm (từ chuyến đi)', pos:'danh từ' },
        { jp:'母', kana:'はは', romaji:'haha', vi:'mẹ (của tôi)', pos:'danh từ', note:'Mẹ người khác / gọi mẹ: お母さん (おかあさん)' },
        { jp:'父', kana:'ちち', romaji:'chichi', vi:'bố (của tôi)', pos:'danh từ', note:'お父さん (おとうさん)' },
        { jp:'家族', kana:'かぞく', romaji:'kazoku', vi:'gia đình', pos:'danh từ' },
        { jp:'電話', kana:'でんわ', romaji:'denwa', vi:'điện thoại', pos:'danh từ' },
        { jp:'メール', kana:'メール', romaji:'mēru', vi:'email, tin nhắn', pos:'danh từ' },
        { jp:'宿題', kana:'しゅくだい', romaji:'shukudai', vi:'bài tập về nhà', pos:'danh từ' },
        { jp:'もう', kana:'もう', romaji:'mō', vi:'đã … rồi', pos:'trạng từ' },
        { jp:'まだ', kana:'まだ', romaji:'mada', vi:'chưa, vẫn', pos:'trạng từ' },
        { jp:'これから', kana:'これから', romaji:'korekara', vi:'từ giờ, sắp', pos:'trạng từ' },
        { jp:'すてき', kana:'すてき', romaji:'suteki', vi:'tuyệt, đẹp', pos:'tính từ な' }
      ],
      dialogue:[
        { sp:'A', jp:'クアンさん 、 それ は 何[なん] ですか 。', vi:'Quân, cái đó là gì?' },
        { sp:'B', jp:'ベトナム の お土産[みやげ] です 。 母[はは] に もらいました 。', vi:'Quà lưu niệm Việt Nam. Mẹ tôi gửi cho.' },
        { sp:'A', jp:'すてき です ね 。 「お土産[みやげ]」 は ベトナム語[ご] で 何[なん] ですか 。', vi:'Đẹp quá. «Omiyage» tiếng Việt là gì?' },
        { sp:'B', jp:'「quà」 です 。 田中[たなか]さん 、 もう 晩[ばん]ご飯[はん] を 食[た]べましたか 。', vi:'Là «quà». Anh Tanaka ăn tối chưa?' },
        { sp:'A', jp:'いいえ 、 まだ です 。 これから 家[うち] で 作[つく]ります 。', vi:'Chưa. Giờ tôi về nhà nấu.' }
      ]
    },
    {
      level:'n5', no:8, jp:'どんな町ですか', vi:'Thành phố thế nào? — tính từ',
      skill:'Tính từ い / な: khẳng định, phủ định; とても/あまり; どう/どんな; 〜が (nhưng); どれ',
      kanji:['新','古','高','安','大','小','多','少','長','白','赤','青'],
      grammar:[
        { form:'A-い です / A-くないです · A-な です / A-じゃありません', vi:'Tính từ い và な ở hiện tại', note:'い-adj: 高い → 高くないです (いい → よくないです). な-adj: しずかです → しずかじゃありません. Trước danh từ: 高い山 / しずかな町.', ex:{ jp:'ハノイ は にぎやか な 町[まち] です 。 でも 、 あまり 静[しず]か じゃ ありません 。', vi:'Hà Nội là thành phố nhộn nhịp. Nhưng không yên tĩnh lắm.' } },
        { form:'とても / あまり〜ない', vi:'rất / không … lắm', note:'あまり luôn đi với phủ định.', ex:{ jp:'この 料理[りょうり] は とても おいしい です 。 あの 店[みせ] は あまり 高[たか]くないです 。', vi:'Món này rất ngon. Quán kia không đắt lắm.' } },
        { form:'どうですか / どんな N ですか', vi:'thế nào? / N như thế nào?', note:'どう hỏi cảm nhận; どんな + danh từ hỏi tính chất.', ex:{ jp:'日本[にほん] の 生活[せいかつ] は どう ですか 。 — 楽[たの]しい です が 、 忙[いそが]しい です 。', vi:'Cuộc sống ở Nhật thế nào? — Vui nhưng bận.' } },
        { form:'〜が、〜 / そして', vi:'nhưng / và (nối câu)', note:'が nối hai vế đối lập trong một câu; そして thêm ý.', ex:{ jp:'この 部屋[へや] は 広[ひろ]い です が 、 古[ふる]い です 。', vi:'Phòng này rộng nhưng cũ.' } },
        { form:'どれ', vi:'cái nào (trong nhiều cái)', note:'Hai cái: どちら.', ex:{ jp:'クアンさん の 傘[かさ] は どれ ですか 。 — あの 青[あお]い の です 。', vi:'Ô của Quân là cái nào? — Cái màu xanh kia.' } }
      ],
      vocab:[
        { jp:'大きい', kana:'おおきい', romaji:'ōkii', vi:'to, lớn', pos:'tính từ い' },
        { jp:'小さい', kana:'ちいさい', romaji:'chiisai', vi:'nhỏ', pos:'tính từ い' },
        { jp:'新しい', kana:'あたらしい', romaji:'atarashii', vi:'mới', pos:'tính từ い' },
        { jp:'古い', kana:'ふるい', romaji:'furui', vi:'cũ', pos:'tính từ い' },
        { jp:'いい', kana:'いい', romaji:'ii', vi:'tốt', pos:'tính từ い', note:'Phủ định よくない, quá khứ よかった' },
        { jp:'悪い', kana:'わるい', romaji:'warui', vi:'xấu, tệ', pos:'tính từ い' },
        { jp:'暑い', kana:'あつい', romaji:'atsui', vi:'nóng (thời tiết)', pos:'tính từ い' },
        { jp:'寒い', kana:'さむい', romaji:'samui', vi:'lạnh', pos:'tính từ い' },
        { jp:'難しい', kana:'むずかしい', romaji:'muzukashii', vi:'khó', pos:'tính từ い' },
        { jp:'易しい', kana:'やさしい', romaji:'yasashii', vi:'dễ', pos:'tính từ い', note:'優しい (やさしい) = hiền' },
        { jp:'おいしい', kana:'おいしい', romaji:'oishii', vi:'ngon', pos:'tính từ い' },
        { jp:'楽しい', kana:'たのしい', romaji:'tanoshii', vi:'vui', pos:'tính từ い' },
        { jp:'忙しい', kana:'いそがしい', romaji:'isogashii', vi:'bận', pos:'tính từ い' },
        { jp:'広い', kana:'ひろい', romaji:'hiroi', vi:'rộng', pos:'tính từ い' },
        { jp:'狭い', kana:'せまい', romaji:'semai', vi:'hẹp', pos:'tính từ い' },
        { jp:'白い', kana:'しろい', romaji:'shiroi', vi:'trắng', pos:'tính từ い', note:'赤い đỏ, 青い xanh, 黒い đen' },
        { jp:'静か', kana:'しずか', romaji:'shizuka', vi:'yên tĩnh', pos:'tính từ な' },
        { jp:'にぎやか', kana:'にぎやか', romaji:'nigiyaka', vi:'nhộn nhịp', pos:'tính từ な' },
        { jp:'きれい', kana:'きれい', romaji:'kirei', vi:'đẹp, sạch', pos:'tính từ な', note:'Dù kết thúc bằng い vẫn là tính từ な' },
        { jp:'親切', kana:'しんせつ', romaji:'shinsetsu', vi:'tốt bụng', pos:'tính từ な' },
        { jp:'有名', kana:'ゆうめい', romaji:'yūmei', vi:'nổi tiếng', pos:'tính từ な' },
        { jp:'便利', kana:'べんり', romaji:'benri', vi:'tiện lợi', pos:'tính từ な' },
        { jp:'元気', kana:'げんき', romaji:'genki', vi:'khoẻ', pos:'tính từ な', note:'お元気ですか — Bạn khoẻ không?' },
        { jp:'暇', kana:'ひま', romaji:'hima', vi:'rảnh', pos:'tính từ な' },
        { jp:'町', kana:'まち', romaji:'machi', vi:'thành phố, thị trấn', pos:'danh từ' },
        { jp:'生活', kana:'せいかつ', romaji:'seikatsu', vi:'cuộc sống', pos:'danh từ' },
        { jp:'料理', kana:'りょうり', romaji:'ryōri', vi:'món ăn, nấu ăn', pos:'danh từ' },
        { jp:'とても', kana:'とても', romaji:'totemo', vi:'rất', pos:'trạng từ' },
        { jp:'あまり', kana:'あまり', romaji:'amari', vi:'không … lắm (+ phủ định)', pos:'trạng từ' },
        { jp:'どんな', kana:'どんな', romaji:'donna', vi:'như thế nào (+ danh từ)', pos:'nghi vấn' },
        { jp:'どれ', kana:'どれ', romaji:'dore', vi:'cái nào', pos:'nghi vấn' }
      ],
      dialogue:[
        { sp:'A', jp:'クアンさん 、 ハノイ は どんな 町[まち] ですか 。', vi:'Quân ơi, Hà Nội là thành phố thế nào?' },
        { sp:'B', jp:'古[ふる]い 町[まち] です 。 とても にぎやか です 。', vi:'Là thành phố cổ. Rất nhộn nhịp.' },
        { sp:'A', jp:'料理[りょうり] は どう ですか 。', vi:'Đồ ăn thế nào?' },
        { sp:'B', jp:'とても おいしい です 。 そして 、 安[やす]い です 。', vi:'Rất ngon. Và rẻ nữa.' },
        { sp:'A', jp:'いい です ね 。 東京[とうきょう] の 料理[りょうり] は おいしい です が 、 高[たか]い です 。', vi:'Thích thật. Đồ ăn Tokyo ngon nhưng đắt.' }
      ]
    },
    {
      level:'n5', no:9, jp:'好きですか', vi:'Bạn có thích không? — sở thích, khả năng, lý do',
      skill:'〜が好き/嫌い/上手/下手/分かります, どうして〜から, よく/だいたい/あまり/全然',
      kanji:['好','上','手','下','分','天','気','雨','雪','山','川'],
      grammar:[
        { form:'N が 好きです / 嫌いです / 上手です / 下手です', vi:'thích / ghét / giỏi / kém N', note:'Đối tượng của các tính từ này dùng が chứ không phải を. Mức độ: 大好き, とても上手.', ex:{ jp:'わたし は 日本[にほん] の 音楽[おんがく] が 好[す]き です 。', vi:'Tôi thích nhạc Nhật.' } },
        { form:'N が 分かります / あります', vi:'hiểu N / có N', note:'分かります (hiểu) và あります (có, sở hữu) cũng dùng が: 日本語が分かります, 時間があります.', ex:{ jp:'田中[たなか]さん は ベトナム語[ご] が 少[すこ]し 分[わ]かります 。', vi:'Anh Tanaka hiểu một chút tiếng Việt.' } },
        { form:'どうして〜か / 〜から', vi:'Tại sao? / vì …', note:'Trả lời: lý do + から. どうしてですか hỏi ngắn.', ex:{ jp:'どうして 日本語[にほんご] を 勉強[べんきょう]します か 。 — 日本[にほん] で 働[はたら]きたい です から 。', vi:'Tại sao bạn học tiếng Nhật? — Vì tôi muốn làm việc ở Nhật.' } },
        { form:'よく / だいたい / 少し / あまり / 全然', vi:'trạng từ mức độ', note:'よく分かります (hiểu rõ), だいたい (đại khái), 少し (một chút), あまり〜ない, 全然〜ない (hoàn toàn không).', ex:{ jp:'漢字[かんじ] は 全然[ぜんぜん] 分[わ]かりません 。', vi:'Kanji tôi hoàn toàn không hiểu.' } }
      ],
      vocab:[
        { jp:'好き', kana:'すき', romaji:'suki', vi:'thích', pos:'tính từ な (〜が)' },
        { jp:'嫌い', kana:'きらい', romaji:'kirai', vi:'ghét', pos:'tính từ な (〜が)' },
        { jp:'上手', kana:'じょうず', romaji:'jōzu', vi:'giỏi', pos:'tính từ な (〜が)', note:'Không dùng cho bản thân; nói mình giỏi: 得意 (とくい)' },
        { jp:'下手', kana:'へた', romaji:'heta', vi:'kém', pos:'tính từ な (〜が)' },
        { jp:'分かる', kana:'わかる', romaji:'wakaru', vi:'hiểu, biết', pos:'động từ nhóm I (〜が)', g:'1' },
        { jp:'ある', kana:'ある', romaji:'aru', vi:'có (đồ vật, thời gian)', pos:'động từ nhóm I', g:'1', note:'Phủ định: ない' },
        { jp:'歌', kana:'うた', romaji:'uta', vi:'bài hát', pos:'danh từ' },
        { jp:'スポーツ', kana:'スポーツ', romaji:'supōtsu', vi:'thể thao', pos:'danh từ' },
        { jp:'サッカー', kana:'サッカー', romaji:'sakkā', vi:'bóng đá', pos:'danh từ' },
        { jp:'漢字', kana:'かんじ', romaji:'kanji', vi:'chữ Hán', pos:'danh từ', note:'ひらがな, カタカナ' },
        { jp:'天気', kana:'てんき', romaji:'tenki', vi:'thời tiết', pos:'danh từ' },
        { jp:'雨', kana:'あめ', romaji:'ame', vi:'mưa', pos:'danh từ', note:'雨が降る (ふる): trời mưa' },
        { jp:'雪', kana:'ゆき', romaji:'yuki', vi:'tuyết', pos:'danh từ' },
        { jp:'山', kana:'やま', romaji:'yama', vi:'núi', pos:'danh từ' },
        { jp:'海', kana:'うみ', romaji:'umi', vi:'biển', pos:'danh từ' },
        { jp:'時間', kana:'じかん', romaji:'jikan', vi:'thời gian', pos:'danh từ' },
        { jp:'お金', kana:'おかね', romaji:'okane', vi:'tiền', pos:'danh từ' },
        { jp:'仕事', kana:'しごと', romaji:'shigoto', vi:'công việc', pos:'danh từ' },
        { jp:'よく', kana:'よく', romaji:'yoku', vi:'rõ; thường xuyên', pos:'trạng từ' },
        { jp:'だいたい', kana:'だいたい', romaji:'daitai', vi:'đại khái, hầu như', pos:'trạng từ' },
        { jp:'少し', kana:'すこし', romaji:'sukoshi', vi:'một chút', pos:'trạng từ' },
        { jp:'全然', kana:'ぜんぜん', romaji:'zenzen', vi:'hoàn toàn không (+ phủ định)', pos:'trạng từ' },
        { jp:'どうして', kana:'どうして', romaji:'dōshite', vi:'tại sao', pos:'nghi vấn', note:'なぜ (trang trọng hơn)' },
        { jp:'〜から', kana:'から', romaji:'-kara', vi:'vì … (đứng cuối vế lý do)', pos:'trợ từ' },
        { jp:'残念', kana:'ざんねん', romaji:'zannen', vi:'tiếc', pos:'tính từ な' }
      ],
      dialogue:[
        { sp:'A', jp:'クアンさん は スポーツ が 好[す]き ですか 。', vi:'Quân thích thể thao không?' },
        { sp:'B', jp:'はい 、 サッカー が 大好[だいす]き です 。 でも 、 あまり 上手[じょうず] じゃ ありません 。', vi:'Có, tôi rất thích bóng đá. Nhưng không giỏi lắm.' },
        { sp:'A', jp:'日曜日[にちようび] 、 一緒[いっしょ]に サッカー を 見[み]ませんか 。', vi:'Chủ nhật cùng xem bóng đá không?' },
        { sp:'B', jp:'すみません 、 日曜日[にちようび] は 時間[じかん] が ありません 。', vi:'Xin lỗi, Chủ nhật tôi không có thời gian.' },
        { sp:'A', jp:'どうして ですか 。', vi:'Tại sao vậy?' },
        { sp:'B', jp:'来週[らいしゅう] 試験[しけん] が あります から 。 残念[ざんねん] です 。', vi:'Vì tuần sau tôi có kỳ thi. Tiếc thật.' }
      ]
    },
    {
      level:'n5', no:10, jp:'あります・います', vi:'Có / ở — tồn tại và vị trí',
      skill:'あります (vật) / います (người, động vật), N に, 上/下/中/前/後ろ/横/隣, や〜など, 〜に〜があります',
      kanji:['右','左','外','間','近','東','西','南','北','店','家'],
      grammar:[
        { form:'N (nơi) に N があります / います', vi:'Ở … có …', note:'あります cho vật/cây; います cho người/động vật. Chủ thể tồn tại dùng が.', ex:{ jp:'机[つくえ] の 上[うえ] に 本[ほん] が あります 。 部屋[へや] に 猫[ねこ] が います 。', vi:'Trên bàn có sách. Trong phòng có con mèo.' } },
        { form:'N は N (nơi) に あります / います', vi:'… ở đâu', note:'Khi hỏi vị trí của vật đã biết: 銀行はどこにありますか. Người: 田中さんは事務所にいます.', ex:{ jp:'郵便局[ゆうびんきょく] は 駅[えき] の 近[ちか]く に あります 。', vi:'Bưu điện ở gần ga.' } },
        { form:'N1 の 上 / 下 / 中 / 前 / 後ろ / 横 / 隣 / 間', vi:'trên / dưới / trong / trước / sau / bên / cạnh / giữa N1', note:'N1のN2 (vị trí) に: 銀行と郵便局の間に (giữa ngân hàng và bưu điện).', ex:{ jp:'かばん の 中[なか] に 財布[さいふ] や 鍵[かぎ] など が あります 。', vi:'Trong cặp có ví, chìa khoá, v.v.' } },
        { form:'N1 や N2 (など)', vi:'N1 và N2 (liệt kê không đầy đủ)', note:'と liệt kê đủ; や liệt kê ví dụ, thường kèm など.', ex:{ jp:'冷蔵庫[れいぞうこ] に 牛乳[ぎゅうにゅう] や 卵[たまご] など が あります 。', vi:'Trong tủ lạnh có sữa, trứng, v.v.' } }
      ],
      vocab:[
        { jp:'いる', kana:'いる', romaji:'iru', vi:'có, ở (người, động vật)', pos:'động từ nhóm II', g:'2' },
        { jp:'上', kana:'うえ', romaji:'ue', vi:'trên', pos:'danh từ vị trí' },
        { jp:'下', kana:'した', romaji:'shita', vi:'dưới', pos:'danh từ vị trí' },
        { jp:'中', kana:'なか', romaji:'naka', vi:'trong', pos:'danh từ vị trí' },
        { jp:'前', kana:'まえ', romaji:'mae', vi:'trước', pos:'danh từ vị trí' },
        { jp:'後ろ', kana:'うしろ', romaji:'ushiro', vi:'sau', pos:'danh từ vị trí' },
        { jp:'右', kana:'みぎ', romaji:'migi', vi:'bên phải', pos:'danh từ vị trí' },
        { jp:'左', kana:'ひだり', romaji:'hidari', vi:'bên trái', pos:'danh từ vị trí' },
        { jp:'横', kana:'よこ', romaji:'yoko', vi:'bên cạnh (ngang)', pos:'danh từ vị trí' },
        { jp:'隣', kana:'となり', romaji:'tonari', vi:'bên cạnh, hàng xóm', pos:'danh từ vị trí' },
        { jp:'間', kana:'あいだ', romaji:'aida', vi:'giữa (hai vật)', pos:'danh từ vị trí' },
        { jp:'近く', kana:'ちかく', romaji:'chikaku', vi:'gần', pos:'danh từ vị trí' },
        { jp:'外', kana:'そと', romaji:'soto', vi:'bên ngoài', pos:'danh từ vị trí' },
        { jp:'部屋', kana:'へや', romaji:'heya', vi:'phòng', pos:'danh từ' },
        { jp:'家', kana:'うち / いえ', romaji:'uchi / ie', vi:'nhà', pos:'danh từ' },
        { jp:'店', kana:'みせ', romaji:'mise', vi:'cửa hàng, quán', pos:'danh từ' },
        { jp:'公園', kana:'こうえん', romaji:'kōen', vi:'công viên', pos:'danh từ' },
        { jp:'病院', kana:'びょういん', romaji:'byōin', vi:'bệnh viện', pos:'danh từ' },
        { jp:'図書館', kana:'としょかん', romaji:'toshokan', vi:'thư viện', pos:'danh từ' },
        { jp:'コンビニ', kana:'コンビニ', romaji:'konbini', vi:'cửa hàng tiện lợi', pos:'danh từ' },
        { jp:'冷蔵庫', kana:'れいぞうこ', romaji:'reizōko', vi:'tủ lạnh', pos:'danh từ' },
        { jp:'財布', kana:'さいふ', romaji:'saifu', vi:'ví', pos:'danh từ' },
        { jp:'鍵', kana:'かぎ', romaji:'kagi', vi:'chìa khoá', pos:'danh từ' },
        { jp:'猫', kana:'ねこ', romaji:'neko', vi:'mèo', pos:'danh từ' },
        { jp:'犬', kana:'いぬ', romaji:'inu', vi:'chó', pos:'danh từ' },
        { jp:'木', kana:'き', romaji:'ki', vi:'cây', pos:'danh từ' },
        { jp:'男の人', kana:'おとこのひと', romaji:'otoko no hito', vi:'người đàn ông', pos:'danh từ', note:'女の人 (おんなのひと)' },
        { jp:'子供', kana:'こども', romaji:'kodomo', vi:'trẻ em', pos:'danh từ' },
        { jp:'〜など', kana:'など', romaji:'nado', vi:'v.v.', pos:'trợ từ' }
      ],
      dialogue:[
        { sp:'A', jp:'すみません 、 この 近[ちか]く に コンビニ が ありますか 。', vi:'Xin lỗi, gần đây có cửa hàng tiện lợi không?' },
        { sp:'B', jp:'ええ 、 あります よ 。 銀行[ぎんこう] の 隣[となり] です 。', vi:'Có đấy. Bên cạnh ngân hàng.' },
        { sp:'A', jp:'銀行[ぎんこう] は どこ に ありますか 。', vi:'Ngân hàng ở đâu ạ?' },
        { sp:'B', jp:'あの 病院[びょういん] の 前[まえ] に あります 。', vi:'Ở trước bệnh viện kia.' },
        { sp:'A', jp:'ありがとうございます 。 あのう 、 田中[たなか]さん は 今[いま] どこ に いますか 。', vi:'Cảm ơn. À, anh Tanaka giờ đang ở đâu?' },
        { sp:'B', jp:'事務所[じむしょ] に います 。 机[つくえ] の 上[うえ] に 田中[たなか]さん の 鍵[かぎ] も あります よ 。', vi:'Đang ở văn phòng. Trên bàn còn có chìa khoá của anh ấy nữa.' }
      ]
    },
    {
      level:'n5', no:11, jp:'いくつありますか', vi:'Có mấy cái? — lượng từ và thời lượng',
      skill:'Lượng từ 〜つ・人・枚・台・冊・本・匹・回・個; thời lượng 〜時間・分・日・週間・か月・年; どのくらい, 〜だけ',
      kanji:['個','枚','台','冊','回','週','人','年','毎','間'],
      grammar:[
        { form:'N を [số + lượng từ] V', vi:'làm gì với bao nhiêu N', note:'Số đếm đứng sau danh từ + trợ từ, trước động từ: りんごを三つ買います. Đếm vật chung: ひとつ・ふたつ・みっつ・よっつ・いつつ・むっつ・ななつ・やっつ・ここのつ・とお. Hỏi: いくつ / 何+lượng từ.', ex:{ jp:'切手[きって] を 五枚[ごまい] と はがき を 二枚[にまい] ください 。', vi:'Cho tôi 5 con tem và 2 bưu thiếp.' } },
        { form:'Bảng lượng từ', vi:'người 〜人, tờ 〜枚, máy/xe 〜台, sách 〜冊, vật dài 〜本, thú nhỏ 〜匹, lần 〜回, cái 〜個', note:'Biến âm: 一人 ひとり, 二人 ふたり; 一本 いっぽん, 三本 さんぼん, 六本 ろっぽん; 一匹 いっぴき, 三匹 さんびき; 一回 いっかい, 六回 ろっかい; 一個 いっこ, 六個 ろっこ.', ex:{ jp:'家族[かぞく] は 四人[よにん] です 。 犬[いぬ] が 一匹[いっぴき] います 。', vi:'Gia đình tôi có 4 người. Có một con chó.' } },
        { form:'Thời lượng: 〜時間・〜分・〜日・〜週間・〜か月・〜年', vi:'… tiếng / phút / ngày / tuần / tháng / năm', note:'Thời lượng không dùng に. Hỏi: どのくらい. Một tuần: 一週間 いっしゅうかん; một tháng: 一か月 いっかげつ; nửa năm: 半年 はんとし.', ex:{ jp:'毎日[まいにち] 二時間[にじかん] 日本語[にほんご] を 勉強[べんきょう]します 。', vi:'Mỗi ngày tôi học tiếng Nhật hai tiếng.' } },
        { form:'〜に [số lần] · 〜だけ', vi:'… lần trong … / chỉ …', note:'一週間に二回 (2 lần một tuần). だけ = chỉ: 一人だけ.', ex:{ jp:'一週間[いっしゅうかん] に 二回[にかい] 母[はは] に 電話[でんわ] を かけます 。', vi:'Tôi gọi điện cho mẹ hai lần một tuần.' } }
      ],
      vocab:[
        { jp:'一つ', kana:'ひとつ', romaji:'hitotsu', vi:'một cái', pos:'số đếm', note:'ふたつ, みっつ, よっつ, いつつ, むっつ, ななつ, やっつ, ここのつ, とお' },
        { jp:'いくつ', kana:'いくつ', romaji:'ikutsu', vi:'mấy cái; mấy tuổi', pos:'nghi vấn', note:'おいくつですか — Bạn bao nhiêu tuổi?' },
        { jp:'〜人', kana:'にん', romaji:'-nin', vi:'… người', pos:'lượng từ', note:'一人 ひとり, 二人 ふたり, 何人 なんにん' },
        { jp:'〜枚', kana:'まい', romaji:'-mai', vi:'… tờ, tấm (vật mỏng)', pos:'lượng từ' },
        { jp:'〜台', kana:'だい', romaji:'-dai', vi:'… chiếc (máy, xe)', pos:'lượng từ' },
        { jp:'〜冊', kana:'さつ', romaji:'-satsu', vi:'… quyển', pos:'lượng từ' },
        { jp:'〜本', kana:'ほん / ぽん / ぼん', romaji:'-hon', vi:'… cái (vật dài: bút, chai, ô)', pos:'lượng từ' },
        { jp:'〜匹', kana:'ひき / ぴき / びき', romaji:'-hiki', vi:'… con (thú nhỏ)', pos:'lượng từ' },
        { jp:'〜回', kana:'かい', romaji:'-kai', vi:'… lần', pos:'lượng từ' },
        { jp:'〜個', kana:'こ', romaji:'-ko', vi:'… cái (vật nhỏ)', pos:'lượng từ' },
        { jp:'〜歳', kana:'さい', romaji:'-sai', vi:'… tuổi', pos:'lượng từ', note:'二十歳 はたち' },
        { jp:'〜時間', kana:'じかん', romaji:'-jikan', vi:'… tiếng (thời lượng)', pos:'lượng từ' },
        { jp:'〜週間', kana:'しゅうかん', romaji:'-shūkan', vi:'… tuần', pos:'lượng từ' },
        { jp:'〜か月', kana:'かげつ', romaji:'-kagetsu', vi:'… tháng', pos:'lượng từ' },
        { jp:'〜年', kana:'ねん', romaji:'-nen', vi:'… năm', pos:'lượng từ' },
        { jp:'どのくらい', kana:'どのくらい', romaji:'dono kurai', vi:'bao lâu, bao nhiêu', pos:'nghi vấn' },
        { jp:'〜だけ', kana:'だけ', romaji:'dake', vi:'chỉ', pos:'trợ từ' },
        { jp:'切手', kana:'きって', romaji:'kitte', vi:'tem', pos:'danh từ' },
        { jp:'はがき', kana:'はがき', romaji:'hagaki', vi:'bưu thiếp', pos:'danh từ' },
        { jp:'りんご', kana:'りんご', romaji:'ringo', vi:'táo', pos:'danh từ' },
        { jp:'みかん', kana:'みかん', romaji:'mikan', vi:'quýt', pos:'danh từ' },
        { jp:'兄弟', kana:'きょうだい', romaji:'kyōdai', vi:'anh chị em', pos:'danh từ' },
        { jp:'両親', kana:'りょうしん', romaji:'ryōshin', vi:'bố mẹ', pos:'danh từ' },
        { jp:'ください', kana:'ください', romaji:'kudasai', vi:'cho tôi … (N をください)', pos:'cụm' },
        { jp:'留学生', kana:'りゅうがくせい', romaji:'ryūgakusei', vi:'du học sinh', pos:'danh từ' }
      ],
      dialogue:[
        { sp:'A', jp:'すみません 、 八十円[はちじゅうえん] の 切手[きって] を 三枚[さんまい] ください 。', vi:'Cho tôi 3 con tem 80 yên.' },
        { sp:'B', jp:'はい 。 二百四十円[にひゃくよんじゅうえん] です 。', vi:'Vâng. 240 yên.' },
        { sp:'A', jp:'クアンさん は 兄弟[きょうだい] が 何人[なんにん] いますか 。', vi:'Quân có mấy anh chị em?' },
        { sp:'C', jp:'二人[ふたり] います 。 兄[あに] と 妹[いもうと] です 。', vi:'Có hai người. Anh trai và em gái.' },
        { sp:'A', jp:'日本[にほん] に どのくらい います か 。', vi:'Bạn ở Nhật bao lâu rồi?' },
        { sp:'C', jp:'まだ 三[さん]か月[げつ] だけ です 。 一週間[いっしゅうかん] に 一回[いっかい] 家族[かぞく] に 電話[でんわ] を かけます 。', vi:'Mới được 3 tháng thôi. Mỗi tuần tôi gọi cho gia đình một lần.' }
      ]
    },
    {
      level:'n5', no:12, jp:'昨日は暑かったです', vi:'Hôm qua nóng quá — quá khứ tính từ và so sánh',
      skill:'Tính từ quá khứ, danh từ quá khứ, 〜より, 〜と〜とどちらが, 〜の中で〜が一番; thời tiết, mùa',
      kanji:['春','夏','秋','冬','暑','寒','一','番','天','気'],
      grammar:[
        { form:'A-かったです / A-くなかったです · N/な-A でした / じゃありませんでした', vi:'quá khứ của tính từ và danh từ', note:'い-adj: 楽しい → 楽しかったです / 楽しくなかったです (いい → よかった). な-adj/N: 暇でした / 暇じゃありませんでした.', ex:{ jp:'昨日[きのう] の パーティー は 楽[たの]しかった です 。 天気[てんき] は あまり よくなかった です 。', vi:'Bữa tiệc hôm qua rất vui. Thời tiết không tốt lắm.' } },
        { form:'N1 は N2 より A です', vi:'N1 … hơn N2', note:'So sánh hơn: より đặt sau cái bị so. Không đổi dạng tính từ.', ex:{ jp:'ハノイ は 東京[とうきょう] より 暑[あつ]い です 。', vi:'Hà Nội nóng hơn Tokyo.' } },
        { form:'N1 と N2 と どちらが A ですか — N1 のほうが A です', vi:'N1 và N2 cái nào … hơn? — N1 hơn', note:'Dùng cho hai vật/người bất kể loại. Bằng nhau: どちらも.', ex:{ jp:'夏[なつ] と 冬[ふゆ] と どちら が 好[す]き ですか 。 — 冬[ふゆ] の ほう が 好[す]き です 。', vi:'Hè và đông bạn thích mùa nào hơn? — Tôi thích mùa đông hơn.' } },
        { form:'N (nhóm) の中で [nghi vấn] が 一番 A ですか', vi:'Trong … cái gì/ai/đâu … nhất?', note:'Từ nghi vấn tuỳ loại: 何 (vật), だれ (người), どこ (nơi), いつ (thời gian).', ex:{ jp:'日本[にほん] の 料理[りょうり] の 中[なか] で 何[なに] が 一番[いちばん] おいしい ですか 。 — 寿司[すし] が 一番[いちばん] おいしい です 。', vi:'Trong các món Nhật, món gì ngon nhất? — Sushi ngon nhất.' } }
      ],
      vocab:[
        { jp:'春', kana:'はる', romaji:'haru', vi:'mùa xuân', pos:'danh từ' },
        { jp:'夏', kana:'なつ', romaji:'natsu', vi:'mùa hè', pos:'danh từ' },
        { jp:'秋', kana:'あき', romaji:'aki', vi:'mùa thu', pos:'danh từ' },
        { jp:'冬', kana:'ふゆ', romaji:'fuyu', vi:'mùa đông', pos:'danh từ' },
        { jp:'季節', kana:'きせつ', romaji:'kisetsu', vi:'mùa', pos:'danh từ' },
        { jp:'暖かい', kana:'あたたかい', romaji:'atatakai', vi:'ấm', pos:'tính từ い' },
        { jp:'涼しい', kana:'すずしい', romaji:'suzushii', vi:'mát', pos:'tính từ い' },
        { jp:'晴れ', kana:'はれ', romaji:'hare', vi:'trời nắng', pos:'danh từ', note:'曇り (くもり) trời âm u' },
        { jp:'風', kana:'かぜ', romaji:'kaze', vi:'gió', pos:'danh từ' },
        { jp:'桜', kana:'さくら', romaji:'sakura', vi:'hoa anh đào', pos:'danh từ' },
        { jp:'パーティー', kana:'パーティー', romaji:'pātī', vi:'tiệc', pos:'danh từ' },
        { jp:'旅行', kana:'りょこう', romaji:'ryokō', vi:'du lịch', pos:'danh từ (する)' },
        { jp:'寿司', kana:'すし', romaji:'sushi', vi:'sushi', pos:'danh từ' },
        { jp:'速い', kana:'はやい', romaji:'hayai', vi:'nhanh', pos:'tính từ い', note:'早い = sớm' },
        { jp:'遅い', kana:'おそい', romaji:'osoi', vi:'chậm; muộn', pos:'tính từ い' },
        { jp:'近い', kana:'ちかい', romaji:'chikai', vi:'gần', pos:'tính từ い' },
        { jp:'遠い', kana:'とおい', romaji:'tōi', vi:'xa', pos:'tính từ い' },
        { jp:'多い', kana:'おおい', romaji:'ōi', vi:'nhiều', pos:'tính từ い', note:'Không đặt trước danh từ; dùng 人が多い' },
        { jp:'少ない', kana:'すくない', romaji:'sukunai', vi:'ít', pos:'tính từ い' },
        { jp:'〜より', kana:'より', romaji:'yori', vi:'hơn (so với)', pos:'trợ từ' },
        { jp:'どちら', kana:'どちら', romaji:'dochira', vi:'cái nào (trong hai)', pos:'nghi vấn' },
        { jp:'〜のほうが', kana:'のほうが', romaji:'no hō ga', vi:'… hơn (phía …)', pos:'cụm' },
        { jp:'一番', kana:'いちばん', romaji:'ichiban', vi:'nhất', pos:'trạng từ' },
        { jp:'ずっと', kana:'ずっと', romaji:'zutto', vi:'hơn hẳn; suốt', pos:'trạng từ' },
        { jp:'去年', kana:'きょねん', romaji:'kyonen', vi:'năm ngoái', pos:'danh từ' }
      ],
      dialogue:[
        { sp:'A', jp:'クアンさん 、 旅行[りょこう] は どう でした か 。', vi:'Quân, chuyến du lịch thế nào?' },
        { sp:'B', jp:'とても 楽[たの]しかった です 。 でも 、 北海道[ほっかいどう] は 寒[さむ]かった です 。', vi:'Rất vui. Nhưng Hokkaido lạnh quá.' },
        { sp:'A', jp:'ハノイ の 冬[ふゆ] と 北海道[ほっかいどう] の 冬[ふゆ] と どちら が 寒[さむ]い ですか 。', vi:'Mùa đông Hà Nội và mùa đông Hokkaido, nơi nào lạnh hơn?' },
        { sp:'B', jp:'北海道[ほっかいどう] の ほう が ずっと 寒[さむ]い です 。 雪[ゆき] が 多[おお]かった です 。', vi:'Hokkaido lạnh hơn hẳn. Tuyết nhiều lắm.' },
        { sp:'A', jp:'日本[にほん] の 季節[きせつ] の 中[なか] で いつ が 一番[いちばん] 好[す]き ですか 。', vi:'Trong các mùa ở Nhật, bạn thích mùa nào nhất?' },
        { sp:'B', jp:'春[はる] が 一番[いちばん] 好[す]き です 。 桜[さくら] が きれい です から 。', vi:'Tôi thích mùa xuân nhất. Vì hoa anh đào đẹp.' }
      ]
    },
    {
      level:'n5', no:13, jp:'何が欲しいですか', vi:'Bạn muốn gì? — mong muốn và mục đích',
      skill:'〜が欲しいです, V-たいです, N/V-ます に行きます (mục đích), 何か・どこか, 〜ませんか (rủ)',
      kanji:['欲','買','物','出','入','休','立','座','走','歩'],
      grammar:[
        { form:'N が 欲しいです', vi:'muốn có N', note:'Chỉ dùng cho bản thân hoặc hỏi người đối diện; nói về người thứ ba dùng 〜を欲しがっています.', ex:{ jp:'新[あたら]しい パソコン が 欲[ほ]しい です 。', vi:'Tôi muốn có máy tính mới.' } },
        { form:'V-ます → V-たいです', vi:'muốn làm gì', note:'Bỏ ます thêm たい, biến đổi như tính từ い: 食べたくないです, 食べたかったです. Tân ngữ: を hoặc が.', ex:{ jp:'日本[にほん] で 働[はたら]きたい です 。 寿司[すし] が 食[た]べたい です 。', vi:'Tôi muốn làm việc ở Nhật. Tôi muốn ăn sushi.' } },
        { form:'N (nơi) へ V-ます / N に 行きます', vi:'đi đâu để làm gì', note:'Mục đích đứng trước に: 映画を見に行きます, 買い物に行きます (danh từ hành động).', ex:{ jp:'週末[しゅうまつ] 友達[ともだち] と 海[うみ] へ 泳[およ]ぎ に 行[い]きます 。', vi:'Cuối tuần tôi đi biển bơi với bạn.' } },
        { form:'何か / どこか / だれか', vi:'cái gì đó / đâu đó / ai đó', note:'Trong câu hỏi: 何か食べたいですか (muốn ăn gì đó không?). Trợ từ が/を thường lược sau 何か.', ex:{ jp:'どこ か 行[い]きたい です か 。 — はい 、 京都[きょうと] へ 行[い]きたい です 。', vi:'Bạn muốn đi đâu đó không? — Có, tôi muốn đi Kyoto.' } }
      ],
      vocab:[
        { jp:'欲しい', kana:'ほしい', romaji:'hoshii', vi:'muốn có', pos:'tính từ い (〜が)' },
        { jp:'〜たい', kana:'たい', romaji:'-tai', vi:'muốn (làm)', pos:'hậu tố' },
        { jp:'買い物', kana:'かいもの', romaji:'kaimono', vi:'mua sắm', pos:'danh từ (する)' },
        { jp:'食事', kana:'しょくじ', romaji:'shokuji', vi:'bữa ăn', pos:'danh từ (する)' },
        { jp:'散歩', kana:'さんぽ', romaji:'sanpo', vi:'đi dạo', pos:'danh từ (する)' },
        { jp:'泳ぐ', kana:'およぐ', romaji:'oyogu', vi:'bơi', pos:'động từ nhóm I', g:'1' },
        { jp:'遊ぶ', kana:'あそぶ', romaji:'asobu', vi:'chơi', pos:'động từ nhóm I', g:'1' },
        { jp:'撮る', kana:'とる', romaji:'toru', vi:'chụp (ảnh)', pos:'động từ nhóm I', g:'1' },
        { jp:'疲れる', kana:'つかれる', romaji:'tsukareru', vi:'mệt', pos:'động từ nhóm II', g:'2', note:'疲れました = mệt rồi' },
        { jp:'結婚する', kana:'けっこんする', romaji:'kekkon suru', vi:'kết hôn', pos:'động từ nhóm III', g:'3' },
        { jp:'出る', kana:'でる', romaji:'deru', vi:'ra, rời', pos:'động từ nhóm II', g:'2', note:'家を出る' },
        { jp:'入る', kana:'はいる', romaji:'hairu', vi:'vào', pos:'động từ nhóm I', g:'1', note:'Nhóm I dù -iru' },
        { jp:'座る', kana:'すわる', romaji:'suwaru', vi:'ngồi', pos:'động từ nhóm I', g:'1' },
        { jp:'立つ', kana:'たつ', romaji:'tatsu', vi:'đứng', pos:'động từ nhóm I', g:'1' },
        { jp:'歩く', kana:'あるく', romaji:'aruku', vi:'đi bộ', pos:'động từ nhóm I', g:'1' },
        { jp:'走る', kana:'はしる', romaji:'hashiru', vi:'chạy', pos:'động từ nhóm I', g:'1' },
        { jp:'パソコン', kana:'パソコン', romaji:'pasokon', vi:'máy tính', pos:'danh từ' },
        { jp:'服', kana:'ふく', romaji:'fuku', vi:'quần áo', pos:'danh từ' },
        { jp:'靴', kana:'くつ', romaji:'kutsu', vi:'giày', pos:'danh từ' },
        { jp:'週末', kana:'しゅうまつ', romaji:'shūmatsu', vi:'cuối tuần', pos:'danh từ' },
        { jp:'お腹', kana:'おなか', romaji:'onaka', vi:'bụng', pos:'danh từ', note:'お腹がすきました = đói rồi' },
        { jp:'喉', kana:'のど', romaji:'nodo', vi:'cổ họng', pos:'danh từ', note:'喉が渇きました = khát rồi' },
        { jp:'何か', kana:'なにか', romaji:'nanika', vi:'cái gì đó', pos:'đại từ bất định' },
        { jp:'どこか', kana:'どこか', romaji:'dokoka', vi:'đâu đó', pos:'đại từ bất định' },
        { jp:'ちょっと', kana:'ちょっと', romaji:'chotto', vi:'một chút; hơi', pos:'trạng từ' }
      ],
      dialogue:[
        { sp:'A', jp:'クアンさん 、 お腹[なか] が すきました ね 。 何[なに] か 食[た]べません か 。', vi:'Quân ơi, đói rồi nhỉ. Ăn gì đó không?' },
        { sp:'B', jp:'ええ 。 わたし は 天[てん]ぷら が 食[た]べたい です 。', vi:'Ừ. Tôi muốn ăn tempura.' },
        { sp:'A', jp:'じゃ 、 駅[えき] の 近[ちか]く の 店[みせ] へ 食[た]べ に 行[い]きましょう 。', vi:'Vậy đi ăn ở quán gần ga nhé.' },
        { sp:'B', jp:'いい です ね 。 それから 、 買[か]い物[もの] に 行[い]きたい です 。 新[あたら]しい 靴[くつ] が 欲[ほ]しい です 。', vi:'Hay đấy. Sau đó tôi muốn đi mua sắm. Tôi muốn có đôi giày mới.' },
        { sp:'A', jp:'わたし は ちょっと 疲[つか]れました 。 家[うち] へ 帰[かえ]りたい です 。', vi:'Tôi hơi mệt. Tôi muốn về nhà.' }
      ]
    },
    {
      level:'n5', no:14, jp:'て形① — ちょっと待ってください', vi:'Thể て — yêu cầu và hành động đang diễn ra',
      skill:'Cách chia thể て ba nhóm, V-てください, V-ています (đang), V-ましょうか (đề nghị giúp)',
      kanji:['待','使','持','立','貸','急','消','開','閉','取'],
      grammar:[
        { form:'Cách chia thể て', vi:'Nhóm I theo âm cuối; nhóm II bỏ る + て; nhóm III: して / 来て', note:'Nhóm I: う・つ・る → って (買って, 待って, 帰って); む・ぶ・ぬ → んで (読んで, 遊んで, 死んで); く → いて (書いて; ngoại lệ 行って); ぐ → いで (泳いで); す → して (話して). Nhóm II: 食べて, 見て. Nhóm III: して, 来て (きて).', ex:{ jp:'ちょっと 待[ま]って ください 。', vi:'Đợi một chút.' } },
        { form:'V-て ください', vi:'Hãy … (yêu cầu, chỉ dẫn lịch sự)', note:'Nhẹ hơn với người trên: 〜ていただけませんか (N4).', ex:{ jp:'ここ に 名前[なまえ] を 書[か]いて ください 。', vi:'Hãy viết tên vào đây.' } },
        { form:'V-て います', vi:'đang … (hành động tiếp diễn)', note:'Hỏi: 今何をしていますか. Phủ định: 〜ていません.', ex:{ jp:'田中[たなか]さん は 今[いま] 電話[でんわ] を かけて います 。', vi:'Anh Tanaka đang gọi điện.' } },
        { form:'V-ましょうか', vi:'Để tôi … nhé? (đề nghị giúp)', note:'Đáp: すみません、お願いします / いいえ、結構です.', ex:{ jp:'荷物[にもつ] を 持[も]ちましょう か 。 — すみません 、 お願[ねが]いします 。', vi:'Để tôi xách đồ cho nhé? — Cảm ơn, nhờ anh.' } }
      ],
      vocab:[
        { jp:'待つ', kana:'まつ', romaji:'matsu', vi:'đợi', pos:'động từ nhóm I', g:'1' },
        { jp:'使う', kana:'つかう', romaji:'tsukau', vi:'dùng', pos:'động từ nhóm I', g:'1' },
        { jp:'持つ', kana:'もつ', romaji:'motsu', vi:'cầm, mang', pos:'động từ nhóm I', g:'1' },
        { jp:'取る', kana:'とる', romaji:'toru', vi:'lấy', pos:'động từ nhóm I', g:'1' },
        { jp:'手伝う', kana:'てつだう', romaji:'tetsudau', vi:'giúp (việc)', pos:'động từ nhóm I', g:'1' },
        { jp:'呼ぶ', kana:'よぶ', romaji:'yobu', vi:'gọi', pos:'động từ nhóm I', g:'1' },
        { jp:'急ぐ', kana:'いそぐ', romaji:'isogu', vi:'vội', pos:'động từ nhóm I', g:'1' },
        { jp:'開ける', kana:'あける', romaji:'akeru', vi:'mở (cửa, cửa sổ)', pos:'động từ nhóm II', g:'2' },
        { jp:'閉める', kana:'しめる', romaji:'shimeru', vi:'đóng', pos:'động từ nhóm II', g:'2' },
        { jp:'つける', kana:'つける', romaji:'tsukeru', vi:'bật (đèn, máy)', pos:'động từ nhóm II', g:'2' },
        { jp:'消す', kana:'けす', romaji:'kesu', vi:'tắt; xoá', pos:'động từ nhóm I', g:'1' },
        { jp:'止める', kana:'とめる', romaji:'tomeru', vi:'dừng, đỗ (xe)', pos:'động từ nhóm II', g:'2' },
        { jp:'見せる', kana:'みせる', romaji:'miseru', vi:'cho xem', pos:'động từ nhóm II', g:'2' },
        { jp:'言う', kana:'いう', romaji:'iu', vi:'nói', pos:'động từ nhóm I', g:'1' },
        { jp:'降る', kana:'ふる', romaji:'furu', vi:'rơi (mưa, tuyết)', pos:'động từ nhóm I', g:'1' },
        { jp:'名前', kana:'なまえ', romaji:'namae', vi:'tên', pos:'danh từ' },
        { jp:'住所', kana:'じゅうしょ', romaji:'jūsho', vi:'địa chỉ', pos:'danh từ' },
        { jp:'荷物', kana:'にもつ', romaji:'nimotsu', vi:'hành lý', pos:'danh từ' },
        { jp:'電気', kana:'でんき', romaji:'denki', vi:'điện; đèn', pos:'danh từ' },
        { jp:'エアコン', kana:'エアコン', romaji:'eakon', vi:'điều hoà', pos:'danh từ' },
        { jp:'窓', kana:'まど', romaji:'mado', vi:'cửa sổ', pos:'danh từ' },
        { jp:'ドア', kana:'ドア', romaji:'doa', vi:'cửa', pos:'danh từ' },
        { jp:'塩', kana:'しお', romaji:'shio', vi:'muối', pos:'danh từ', note:'砂糖 (さとう) đường' },
        { jp:'ゆっくり', kana:'ゆっくり', romaji:'yukkuri', vi:'chậm rãi, thong thả', pos:'trạng từ' },
        { jp:'すぐ', kana:'すぐ', romaji:'sugu', vi:'ngay', pos:'trạng từ' },
        { jp:'また', kana:'また', romaji:'mata', vi:'lại, nữa', pos:'trạng từ' },
        { jp:'お願いします', kana:'おねがいします', romaji:'onegai shimasu', vi:'nhờ, làm ơn', pos:'cụm' }
      ],
      dialogue:[
        { sp:'A', jp:'すみません 、 ちょっと 手伝[てつだ]って ください 。', vi:'Xin lỗi, giúp tôi một chút.' },
        { sp:'B', jp:'はい 。 何[なん] ですか 。', vi:'Vâng. Việc gì thế?' },
        { sp:'A', jp:'この 荷物[にもつ] を 事務所[じむしょ] へ 持[も]って 行[い]って ください 。', vi:'Mang hành lý này lên văn phòng giúp tôi.' },
        { sp:'B', jp:'分[わ]かりました 。 田中[たなか]さん は 今[いま] 何[なに] を して います か 。', vi:'Tôi hiểu rồi. Anh Tanaka giờ đang làm gì?' },
        { sp:'A', jp:'会議室[かいぎしつ] で 山田[やまだ]さん と 話[はな]して います 。', vi:'Đang nói chuyện với anh Yamada ở phòng họp.' },
        { sp:'B', jp:'じゃ 、 ドア を 開[あ]けましょう か 。', vi:'Vậy để tôi mở cửa nhé?' },
        { sp:'A', jp:'はい 、 お願[ねが]いします 。', vi:'Vâng, nhờ bạn.' }
      ]
    },
    {
      level:'n5', no:15, jp:'て形② — 写真を撮ってもいいですか', vi:'Thể て — xin phép, cấm đoán, trạng thái',
      skill:'V-てもいいです, V-てはいけません, V-ています (trạng thái: 住んでいます, 持っています, 知っています, 結婚しています)',
      kanji:['住','知','結','婚','写','真','注','意','禁','止'],
      grammar:[
        { form:'V-ても いいですか', vi:'Tôi … có được không? (xin phép)', note:'Cho phép: ええ、いいですよ / どうぞ. Từ chối nhẹ: すみません、ちょっと…', ex:{ jp:'ここ で 写真[しゃしん] を 撮[と]って も いい ですか 。 — ええ 、 どうぞ 。', vi:'Chụp ảnh ở đây được không? — Vâng, mời anh.' } },
        { form:'V-ては いけません', vi:'không được … (cấm)', note:'Khẩu ngữ: 〜ちゃいけない / 〜じゃいけない. Biển báo: 禁止 (きんし).', ex:{ jp:'ここ で たばこ を 吸[す]って は いけません 。', vi:'Không được hút thuốc ở đây.' } },
        { form:'V-て います (trạng thái, nghề nghiệp)', vi:'đang trong trạng thái …', note:'住んでいます (đang sống), 結婚しています (đã kết hôn), 知っています (biết; phủ định: 知りません), 持っています (có/mang), 〜で働いています (làm việc ở).', ex:{ jp:'わたし は ハノイ に 住[す]んで います 。 兄[あに] は 銀行[ぎんこう] で 働[はたら]いて います 。', vi:'Tôi sống ở Hà Nội. Anh tôi làm ở ngân hàng.' } },
        { form:'N は V-ています か — はい、〜ています / いいえ、〜ていません', vi:'Bạn (đã/đang) … chưa?', note:'知っていますか → はい、知っています / いいえ、知りません (đặc biệt).', ex:{ jp:'田中[たなか]さん の 住所[じゅうしょ] を 知[し]って います か 。 — いいえ 、 知[し]りません 。', vi:'Bạn có biết địa chỉ anh Tanaka không? — Không, tôi không biết.' } }
      ],
      vocab:[
        { jp:'住む', kana:'すむ', romaji:'sumu', vi:'sống, cư trú (〜に)', pos:'động từ nhóm I', g:'1' },
        { jp:'知る', kana:'しる', romaji:'shiru', vi:'biết', pos:'động từ nhóm I', g:'1', note:'知っています / 知りません' },
        { jp:'吸う', kana:'すう', romaji:'suu', vi:'hút (thuốc)', pos:'động từ nhóm I', g:'1' },
        { jp:'触る', kana:'さわる', romaji:'sawaru', vi:'sờ, chạm (〜に)', pos:'động từ nhóm I', g:'1' },
        { jp:'入れる', kana:'いれる', romaji:'ireru', vi:'cho vào, bỏ vào', pos:'động từ nhóm II', g:'2' },
        { jp:'出す', kana:'だす', romaji:'dasu', vi:'lấy ra; nộp; gửi', pos:'động từ nhóm I', g:'1' },
        { jp:'心配する', kana:'しんぱいする', romaji:'shinpai suru', vi:'lo lắng', pos:'động từ nhóm III', g:'3' },
        { jp:'たばこ', kana:'たばこ', romaji:'tabako', vi:'thuốc lá', pos:'danh từ' },
        { jp:'携帯', kana:'けいたい', romaji:'keitai', vi:'điện thoại di động', pos:'danh từ' },
        { jp:'独身', kana:'どくしん', romaji:'dokushin', vi:'độc thân', pos:'danh từ' },
        { jp:'兄', kana:'あに', romaji:'ani', vi:'anh trai (của tôi)', pos:'danh từ', note:'お兄さん (おにいさん)' },
        { jp:'姉', kana:'あね', romaji:'ane', vi:'chị gái (của tôi)', pos:'danh từ', note:'お姉さん (おねえさん)' },
        { jp:'弟', kana:'おとうと', romaji:'otōto', vi:'em trai', pos:'danh từ' },
        { jp:'妹', kana:'いもうと', romaji:'imōto', vi:'em gái', pos:'danh từ' },
        { jp:'美術館', kana:'びじゅつかん', romaji:'bijutsukan', vi:'bảo tàng mỹ thuật', pos:'danh từ' },
        { jp:'寮', kana:'りょう', romaji:'ryō', vi:'ký túc xá', pos:'danh từ' },
        { jp:'アパート', kana:'アパート', romaji:'apāto', vi:'chung cư nhỏ', pos:'danh từ' },
        { jp:'禁止', kana:'きんし', romaji:'kinshi', vi:'cấm', pos:'danh từ', note:'駐車禁止 cấm đỗ xe' },
        { jp:'大丈夫', kana:'だいじょうぶ', romaji:'daijōbu', vi:'không sao, ổn', pos:'tính từ な' },
        { jp:'だめ', kana:'だめ', romaji:'dame', vi:'không được', pos:'tính từ な' },
        { jp:'どうぞ', kana:'どうぞ', romaji:'dōzo', vi:'xin mời', pos:'trạng từ' },
        { jp:'もちろん', kana:'もちろん', romaji:'mochiron', vi:'tất nhiên', pos:'trạng từ' }
      ],
      dialogue:[
        { sp:'A', jp:'すみません 、 ここ で 写真[しゃしん] を 撮[と]って も いい ですか 。', vi:'Xin lỗi, chụp ảnh ở đây được không ạ?' },
        { sp:'B', jp:'すみません 、 美術館[びじゅつかん] の 中[なか] で 撮[と]って は いけません 。', vi:'Xin lỗi, trong bảo tàng không được chụp.' },
        { sp:'A', jp:'分[わ]かりました 。 携帯[けいたい] を 使[つか]って も いい ですか 。', vi:'Tôi hiểu rồi. Dùng điện thoại có được không?' },
        { sp:'B', jp:'ええ 、 大丈夫[だいじょうぶ] です 。', vi:'Vâng, không sao.' },
        { sp:'C', jp:'クアンさん は 今[いま] どこ に 住[す]んで います か 。', vi:'Quân giờ đang sống ở đâu?' },
        { sp:'A', jp:'大学[だいがく] の 寮[りょう] に 住[す]んで います 。 山田[やまだ]さん は 結婚[けっこん]して います か 。', vi:'Tôi ở ký túc xá trường. Anh Yamada kết hôn chưa?' },
        { sp:'C', jp:'いいえ 、 独身[どくしん] です 。', vi:'Chưa, tôi độc thân.' }
      ]
    },
    {
      level:'n5', no:16, jp:'て形③ — 朝起きて、シャワーを浴びて', vi:'Thể て — nối hành động và tính chất',
      skill:'V-て、V-て (trình tự), V-てから, A-くて / な-A で / N で (nối tính chất), どうやって, どの',
      kanji:['朝','夜','浴','起','洗','顔','歯','着','乗','降'],
      grammar:[
        { form:'V1-て、V2-て、V3', vi:'làm V1, rồi V2, rồi V3 (theo trình tự)', note:'Thì của cả câu do động từ cuối quyết định: 朝起きて、シャワーを浴びて、会社へ行きました.', ex:{ jp:'朝[あさ] 起[お]きて 、 シャワー を 浴[あ]びて 、 朝[あさ]ご飯[はん] を 食[た]べます 。', vi:'Buổi sáng tôi dậy, tắm, rồi ăn sáng.' } },
        { form:'V1-て から、V2', vi:'sau khi V1 thì V2', note:'Nhấn mạnh thứ tự; chủ ngữ vế đầu dùng が nếu khác chủ ngữ.', ex:{ jp:'仕事[しごと] が 終[お]わって から 、 買[か]い物[もの] に 行[い]きます 。', vi:'Sau khi xong việc tôi đi mua sắm.' } },
        { form:'A-くて / な-A で / N で、〜', vi:'… và … (nối hai tính chất)', note:'い-adj: 安くて、おいしい; な-adj/N: きれいで、静か / 学生で、22歳. Không nối hai ý trái ngược (dùng が).', ex:{ jp:'この 店[みせ] は 安[やす]くて 、 おいしい です 。 田中[たなか]さん は 親切[しんせつ] で 、 元気[げんき] な 人[ひと] です 。', vi:'Quán này rẻ mà ngon. Anh Tanaka là người tốt bụng và khoẻ khoắn.' } },
        { form:'どうやって / どの N', vi:'bằng cách nào / N nào (trong ba trở lên)', note:'Chỉ đường: 〜で〜へ行って、〜で降りて… ', ex:{ jp:'大学[だいがく] まで どうやって 行[い]きますか 。 — 駅[えき] から バス に 乗[の]って 、 三[みっ]つ目[め] で 降[お]ります 。', vi:'Đến trường đi thế nào? — Từ ga lên xe buýt, xuống ở bến thứ ba.' } }
      ],
      vocab:[
        { jp:'浴びる', kana:'あびる', romaji:'abiru', vi:'tắm (vòi sen)', pos:'động từ nhóm II', g:'2', note:'シャワーを浴びる' },
        { jp:'洗う', kana:'あらう', romaji:'arau', vi:'rửa, giặt', pos:'động từ nhóm I', g:'1' },
        { jp:'磨く', kana:'みがく', romaji:'migaku', vi:'đánh (răng), đánh bóng', pos:'động từ nhóm I', g:'1' },
        { jp:'着る', kana:'きる', romaji:'kiru', vi:'mặc (áo)', pos:'động từ nhóm II', g:'2', note:'Quần/giày: はく; mũ: かぶる' },
        { jp:'乗る', kana:'のる', romaji:'noru', vi:'lên (xe, tàu) (〜に)', pos:'động từ nhóm I', g:'1' },
        { jp:'降りる', kana:'おりる', romaji:'oriru', vi:'xuống (xe) (〜を)', pos:'động từ nhóm II', g:'2' },
        { jp:'乗り換える', kana:'のりかえる', romaji:'norikaeru', vi:'đổi tàu/xe', pos:'động từ nhóm II', g:'2' },
        { jp:'曲がる', kana:'まがる', romaji:'magaru', vi:'rẽ (〜を)', pos:'động từ nhóm I', g:'1' },
        { jp:'渡る', kana:'わたる', romaji:'wataru', vi:'băng qua (〜を)', pos:'động từ nhóm I', g:'1' },
        { jp:'着く', kana:'つく', romaji:'tsuku', vi:'đến nơi (〜に)', pos:'động từ nhóm I', g:'1' },
        { jp:'出かける', kana:'でかける', romaji:'dekakeru', vi:'ra ngoài', pos:'động từ nhóm II', g:'2' },
        { jp:'シャワー', kana:'シャワー', romaji:'shawā', vi:'vòi sen', pos:'danh từ' },
        { jp:'顔', kana:'かお', romaji:'kao', vi:'mặt', pos:'danh từ' },
        { jp:'歯', kana:'は', romaji:'ha', vi:'răng', pos:'danh từ' },
        { jp:'背が高い', kana:'せがたかい', romaji:'se ga takai', vi:'cao (người)', pos:'cụm tính từ' },
        { jp:'髪', kana:'かみ', romaji:'kami', vi:'tóc', pos:'danh từ' },
        { jp:'交差点', kana:'こうさてん', romaji:'kōsaten', vi:'ngã tư', pos:'danh từ' },
        { jp:'信号', kana:'しんごう', romaji:'shingō', vi:'đèn giao thông', pos:'danh từ' },
        { jp:'橋', kana:'はし', romaji:'hashi', vi:'cây cầu', pos:'danh từ' },
        { jp:'角', kana:'かど', romaji:'kado', vi:'góc (phố)', pos:'danh từ' },
        { jp:'まっすぐ', kana:'まっすぐ', romaji:'massugu', vi:'thẳng', pos:'trạng từ' },
        { jp:'〜つ目', kana:'つめ', romaji:'-tsume', vi:'thứ … (一つ目 thứ nhất)', pos:'hậu tố' },
        { jp:'どうやって', kana:'どうやって', romaji:'dō yatte', vi:'bằng cách nào', pos:'nghi vấn' },
        { jp:'どの', kana:'どの', romaji:'dono', vi:'… nào (+ danh từ)', pos:'nghi vấn' },
        { jp:'それから', kana:'それから', romaji:'sorekara', vi:'sau đó', pos:'liên từ' }
      ],
      dialogue:[
        { sp:'A', jp:'クアンさん は 毎朝[まいあさ] 何[なに] を します か 。', vi:'Mỗi sáng Quân làm gì?' },
        { sp:'B', jp:'六時[ろくじ] に 起[お]きて 、 顔[かお] を 洗[あら]って 、 朝[あさ]ご飯[はん] を 食[た]べます 。 それから 、 大学[だいがく] へ 行[い]きます 。', vi:'Tôi dậy lúc 6 giờ, rửa mặt, ăn sáng. Sau đó đi đến trường.' },
        { sp:'A', jp:'大学[だいがく] まで どうやって 行[い]きますか 。', vi:'Đến trường đi thế nào?' },
        { sp:'B', jp:'駅[えき] から 電車[でんしゃ] に 乗[の]って 、 二[ふた]つ目[め] の 駅[えき] で 降[お]ります 。 それから 、 十分[じゅっぷん] ぐらい 歩[ある]きます 。', vi:'Từ ga lên tàu, xuống ở ga thứ hai. Rồi đi bộ khoảng 10 phút.' },
        { sp:'A', jp:'大学[だいがく] は どんな ところ です か 。', vi:'Trường là nơi thế nào?' },
        { sp:'B', jp:'新[あたら]しくて 、 きれい な ところ です 。 先生[せんせい] は 親切[しんせつ] で 、 授業[じゅぎょう] は 楽[たの]しい です 。', vi:'Mới và đẹp. Thầy cô thân thiện, giờ học vui.' }
      ]
    },
    {
      level:'n5', no:17, jp:'ない形 — 忘れないでください', vi:'Thể ない — đừng, phải, không cần',
      skill:'Cách chia thể ない, V-ないでください, V-なければなりません, V-なくてもいいです',
      kanji:['忘','飲','薬','病','院','体','元','気','医','者'],
      grammar:[
        { form:'Cách chia thể ない', vi:'Nhóm I: âm う → あ + ない (買う → 買わない); nhóm II: bỏ る + ない; する → しない, 来る → 来ない (こない)', note:'Ngoại lệ: ある → ない. 書く → 書かない, 待つ → 待たない, 飲む → 飲まない, 話す → 話さない.', ex:{ jp:'明日[あした] は 大学[だいがく] へ 行[い]かない 。', vi:'Mai tôi không đi đến trường. (thể thường)' } },
        { form:'V-ないで ください', vi:'Xin đừng …', note:'Nhẹ nhàng hơn: 〜ないでくださいね.', ex:{ jp:'ここ に 車[くるま] を 止[と]めないで ください 。', vi:'Xin đừng đỗ xe ở đây.' } },
        { form:'V-なければ なりません', vi:'phải … (nghĩa vụ)', note:'Khẩu ngữ: 〜なきゃ / 〜ないと. Trang trọng: 〜なければいけません.', ex:{ jp:'毎日[まいにち] 薬[くすり] を 飲[の]まなければ なりません 。', vi:'Mỗi ngày phải uống thuốc.' } },
        { form:'V-なくても いいです', vi:'không cần … cũng được', note:'Đối lập với なければなりません. Trả lời câu hỏi 〜なければなりませんか.', ex:{ jp:'明日[あした] は 来[こ]なくて も いい です 。', vi:'Mai không cần đến cũng được.' } }
      ],
      vocab:[
        { jp:'忘れる', kana:'わすれる', romaji:'wasureru', vi:'quên', pos:'động từ nhóm II', g:'2' },
        { jp:'無くす', kana:'なくす', romaji:'nakusu', vi:'làm mất', pos:'động từ nhóm I', g:'1' },
        { jp:'払う', kana:'はらう', romaji:'harau', vi:'trả (tiền)', pos:'động từ nhóm I', g:'1' },
        { jp:'返す', kana:'かえす', romaji:'kaesu', vi:'trả lại', pos:'động từ nhóm I', g:'1' },
        { jp:'脱ぐ', kana:'ぬぐ', romaji:'nugu', vi:'cởi (giày, áo)', pos:'động từ nhóm I', g:'1' },
        { jp:'覚える', kana:'おぼえる', romaji:'oboeru', vi:'ghi nhớ', pos:'động từ nhóm II', g:'2' },
        { jp:'薬を飲む', kana:'くすりをのむ', romaji:'kusuri o nomu', vi:'uống thuốc', pos:'cụm động từ' },
        { jp:'熱', kana:'ねつ', romaji:'netsu', vi:'sốt', pos:'danh từ', note:'熱があります' },
        { jp:'風邪', kana:'かぜ', romaji:'kaze', vi:'cảm', pos:'danh từ', note:'風邪をひきました' },
        { jp:'頭', kana:'あたま', romaji:'atama', vi:'đầu', pos:'danh từ', note:'頭が痛い' },
        { jp:'痛い', kana:'いたい', romaji:'itai', vi:'đau', pos:'tính từ い' },
        { jp:'体', kana:'からだ', romaji:'karada', vi:'cơ thể', pos:'danh từ' },
        { jp:'病気', kana:'びょうき', romaji:'byōki', vi:'bệnh', pos:'danh từ' },
        { jp:'お風呂', kana:'おふろ', romaji:'ofuro', vi:'bồn tắm', pos:'danh từ', note:'お風呂に入る' },
        { jp:'レポート', kana:'レポート', romaji:'repōto', vi:'báo cáo', pos:'danh từ' },
        { jp:'試験', kana:'しけん', romaji:'shiken', vi:'kỳ thi', pos:'danh từ' },
        { jp:'パスポート', kana:'パスポート', romaji:'pasupōto', vi:'hộ chiếu', pos:'danh từ' },
        { jp:'保険証', kana:'ほけんしょう', romaji:'hokenshō', vi:'thẻ bảo hiểm', pos:'danh từ' },
        { jp:'お大事に', kana:'おだいじに', romaji:'odaiji ni', vi:'mau khoẻ nhé', pos:'cụm' },
        { jp:'ゆっくり休む', kana:'ゆっくりやすむ', romaji:'yukkuri yasumu', vi:'nghỉ ngơi thư thả', pos:'cụm' }
      ],
      dialogue:[
        { sp:'A', jp:'どう しました か 。', vi:'Anh làm sao thế? (bác sĩ hỏi)' },
        { sp:'B', jp:'昨日[きのう] から 頭[あたま] が 痛[いた]くて 、 熱[ねつ] が あります 。', vi:'Từ hôm qua tôi đau đầu và bị sốt.' },
        { sp:'A', jp:'風邪[かぜ] です ね 。 薬[くすり] を 出[だ]します 。 一日[いちにち] に 三回[さんかい] 飲[の]まなければ なりません 。', vi:'Cảm rồi. Tôi kê thuốc. Một ngày phải uống ba lần.' },
        { sp:'B', jp:'はい 。 お風呂[ふろ] に 入[はい]って も いい ですか 。', vi:'Vâng. Tôi tắm bồn được không?' },
        { sp:'A', jp:'今日[きょう] は 入[はい]らないで ください 。 明日[あした] は 大学[だいがく] を 休[やす]んで 、 ゆっくり 休[やす]んで ください 。', vi:'Hôm nay đừng tắm. Mai nghỉ học, nghỉ ngơi cho khoẻ.' },
        { sp:'B', jp:'レポート を 出[だ]さなくて も いい ですか 。', vi:'Không cần nộp báo cáo cũng được ạ?' },
        { sp:'A', jp:'ええ 、 先生[せんせい] に 電話[でんわ] を して ください 。 お大事[だいじ]に 。', vi:'Vâng, hãy gọi điện cho thầy. Mau khoẻ nhé.' }
      ]
    },
    {
      level:'n5', no:18, jp:'辞書形 — 泳ぐことができます', vi:'Thể từ điển — khả năng, sở thích, trước khi',
      skill:'Thể từ điển, V-ることができます, 趣味は V-ることです, V-る前に, N の前に',
      kanji:['前','趣','味','歌','楽','習','練','泳','車','運'],
      grammar:[
        { form:'Thể từ điển (辞書形)', vi:'Dạng gốc trong từ điển: nhóm I tận cùng う-row; nhóm II 〜る; nhóm III する / 来る', note:'Từ thể ます: nhóm I い-row → う-row (かきます → かく); nhóm II bỏ ます + る (たべます → たべる).', ex:{ jp:'毎朝[まいあさ] 六時[ろくじ] に 起[お]きる 。', vi:'Mỗi sáng dậy lúc 6 giờ. (thể thường)' } },
        { form:'N / V-る こと が できます', vi:'có thể … (khả năng, điều kiện cho phép)', note:'N: 日本語ができます. V: 漢字を読むことができます. Cách khác: thể khả năng (N4).', ex:{ jp:'クアンさん は 車[くるま] を 運転[うんてん]する こと が できます か 。', vi:'Quân có thể lái xe không?' } },
        { form:'趣味 は N / V-る こと です', vi:'Sở thích của tôi là …', note:'V-ること biến động từ thành danh từ.', ex:{ jp:'わたし の 趣味[しゅみ] は 写真[しゃしん] を 撮[と]る こと です 。', vi:'Sở thích của tôi là chụp ảnh.' } },
        { form:'V-る 前に / N の 前に / [thời lượng] 前に', vi:'trước khi …', note:'Trước động từ luôn dùng thể từ điển bất kể thì: 日本へ来る前に、日本語を勉強しました.', ex:{ jp:'寝[ね]る 前[まえ] に 本[ほん] を 読[よ]みます 。 食事[しょくじ] の 前[まえ] に 手[て] を 洗[あら]います 。', vi:'Trước khi ngủ tôi đọc sách. Trước bữa ăn tôi rửa tay.' } }
      ],
      vocab:[
        { jp:'できる', kana:'できる', romaji:'dekiru', vi:'có thể; làm được', pos:'động từ nhóm II', g:'2' },
        { jp:'運転する', kana:'うんてんする', romaji:'unten suru', vi:'lái xe', pos:'động từ nhóm III', g:'3' },
        { jp:'弾く', kana:'ひく', romaji:'hiku', vi:'chơi (đàn)', pos:'động từ nhóm I', g:'1', note:'ピアノを弾く' },
        { jp:'歌う', kana:'うたう', romaji:'utau', vi:'hát', pos:'động từ nhóm I', g:'1' },
        { jp:'集める', kana:'あつめる', romaji:'atsumeru', vi:'sưu tầm, thu thập', pos:'động từ nhóm II', g:'2' },
        { jp:'捨てる', kana:'すてる', romaji:'suteru', vi:'vứt', pos:'động từ nhóm II', g:'2' },
        { jp:'換える', kana:'かえる', romaji:'kaeru', vi:'đổi (tiền)', pos:'động từ nhóm II', g:'2' },
        { jp:'練習する', kana:'れんしゅうする', romaji:'renshū suru', vi:'luyện tập', pos:'động từ nhóm III', g:'3' },
        { jp:'趣味', kana:'しゅみ', romaji:'shumi', vi:'sở thích', pos:'danh từ' },
        { jp:'ピアノ', kana:'ピアノ', romaji:'piano', vi:'piano', pos:'danh từ' },
        { jp:'ギター', kana:'ギター', romaji:'gitā', vi:'ghi-ta', pos:'danh từ' },
        { jp:'ゲーム', kana:'ゲーム', romaji:'gēmu', vi:'trò chơi điện tử', pos:'danh từ' },
        { jp:'漫画', kana:'まんが', romaji:'manga', vi:'truyện tranh', pos:'danh từ' },
        { jp:'アニメ', kana:'アニメ', romaji:'anime', vi:'phim hoạt hình', pos:'danh từ' },
        { jp:'免許', kana:'めんきょ', romaji:'menkyo', vi:'bằng lái', pos:'danh từ' },
        { jp:'現金', kana:'げんきん', romaji:'genkin', vi:'tiền mặt', pos:'danh từ' },
        { jp:'カード', kana:'カード', romaji:'kādo', vi:'thẻ', pos:'danh từ' },
        { jp:'日記', kana:'にっき', romaji:'nikki', vi:'nhật ký', pos:'danh từ' },
        { jp:'国際', kana:'こくさい', romaji:'kokusai', vi:'quốc tế', pos:'danh từ' },
        { jp:'ぜひ', kana:'ぜひ', romaji:'zehi', vi:'nhất định (mời)', pos:'trạng từ' },
        { jp:'特に', kana:'とくに', romaji:'toku ni', vi:'đặc biệt là', pos:'trạng từ' }
      ],
      dialogue:[
        { sp:'A', jp:'クアンさん の 趣味[しゅみ] は 何[なん] ですか 。', vi:'Sở thích của Quân là gì?' },
        { sp:'B', jp:'ギター を 弾[ひ]く こと です 。 日本[にほん] の 歌[うた] を 歌[うた]う こと も できます 。', vi:'Là chơi ghi-ta. Tôi cũng hát được bài hát Nhật.' },
        { sp:'A', jp:'すごい です ね 。 日本[にほん] へ 来[く]る 前[まえ] に 日本語[にほんご] を 勉強[べんきょう]しました か 。', vi:'Giỏi quá. Trước khi đến Nhật bạn học tiếng Nhật chưa?' },
        { sp:'B', jp:'はい 、 ハノイ で 一年[いちねん] 勉強[べんきょう]しました 。 でも 、 漢字[かんじ] を 書[か]く こと は あまり できません 。', vi:'Rồi, tôi học một năm ở Hà Nội. Nhưng viết kanji thì chưa được lắm.' },
        { sp:'A', jp:'この 店[みせ] で カード を 使[つか]う こと が できます か 。', vi:'Ở quán này dùng thẻ được không?' },
        { sp:'B', jp:'いいえ 、 現金[げんきん] だけ です 。', vi:'Không, chỉ tiền mặt thôi.' }
      ]
    },
    {
      level:'n5', no:19, jp:'た形 — 富士山に登ったことがあります', vi:'Thể た — kinh nghiệm, liệt kê, thay đổi',
      skill:'Thể た, V-たことがあります, V-たり V-たりします, A-く / な-A に / N に なります',
      kanji:['登','富','士','山','変','成','低','広','静','便','利'],
      grammar:[
        { form:'Thể た (quá khứ thường)', vi:'Chia như thể て, đổi て → た, で → だ', note:'買った, 待った, 帰った, 読んだ, 遊んだ, 書いた, 行った, 泳いだ, 話した, 食べた, した, 来た (きた).', ex:{ jp:'昨日[きのう] 友達[ともだち] と 映画[えいが] を 見[み]た 。', vi:'Hôm qua tôi xem phim với bạn. (thể thường)' } },
        { form:'V-た こと が あります', vi:'đã từng …', note:'Kinh nghiệm. Phủ định: 〜たことがありません. Không dùng cho việc mới xảy ra gần đây (dùng 〜ました).', ex:{ jp:'富士山[ふじさん] に 登[のぼ]った こと が あります か 。 — いいえ 、 一度[いちど] も ありません 。', vi:'Bạn đã từng leo núi Phú Sĩ chưa? — Chưa, chưa lần nào.' } },
        { form:'V1-たり、V2-たり します', vi:'lúc thì V1, lúc thì V2 (liệt kê tiêu biểu)', note:'Không theo thứ tự; thì đặt ở します cuối: 週末は掃除したり、洗濯したりしました.', ex:{ jp:'休[やす]み の 日[ひ] は 本[ほん] を 読[よ]んだり 、 音楽[おんがく] を 聞[き]いたり します 。', vi:'Ngày nghỉ tôi lúc thì đọc sách, lúc thì nghe nhạc.' } },
        { form:'A-く なります / な-A に なります / N に なります', vi:'trở nên …', note:'寒くなります, 元気になります, 医者になります. Quá khứ: 〜くなりました.', ex:{ jp:'日本語[にほんご] が 上手[じょうず] に なりました ね 。 — いいえ 、 まだまだ です 。', vi:'Tiếng Nhật của bạn giỏi lên rồi nhỉ. — Không, vẫn còn kém lắm.' } }
      ],
      vocab:[
        { jp:'登る', kana:'のぼる', romaji:'noboru', vi:'leo (〜に)', pos:'động từ nhóm I', g:'1' },
        { jp:'泊まる', kana:'とまる', romaji:'tomaru', vi:'nghỉ trọ (〜に)', pos:'động từ nhóm I', g:'1' },
        { jp:'掃除する', kana:'そうじする', romaji:'sōji suru', vi:'dọn dẹp', pos:'động từ nhóm III', g:'3' },
        { jp:'洗濯する', kana:'せんたくする', romaji:'sentaku suru', vi:'giặt giũ', pos:'động từ nhóm III', g:'3' },
        { jp:'なる', kana:'なる', romaji:'naru', vi:'trở thành, trở nên', pos:'động từ nhóm I', g:'1' },
        { jp:'眠い', kana:'ねむい', romaji:'nemui', vi:'buồn ngủ', pos:'tính từ い' },
        { jp:'強い', kana:'つよい', romaji:'tsuyoi', vi:'mạnh', pos:'tính từ い', note:'弱い (よわい) yếu' },
        { jp:'富士山', kana:'ふじさん', romaji:'Fujisan', vi:'núi Phú Sĩ', pos:'danh từ riêng' },
        { jp:'温泉', kana:'おんせん', romaji:'onsen', vi:'suối nước nóng', pos:'danh từ' },
        { jp:'お寺', kana:'おてら', romaji:'otera', vi:'chùa', pos:'danh từ' },
        { jp:'神社', kana:'じんじゃ', romaji:'jinja', vi:'đền Thần đạo', pos:'danh từ' },
        { jp:'着物', kana:'きもの', romaji:'kimono', vi:'kimono', pos:'danh từ' },
        { jp:'一度', kana:'いちど', romaji:'ichido', vi:'một lần', pos:'danh từ', note:'一度も〜ない: chưa lần nào' },
        { jp:'休みの日', kana:'やすみのひ', romaji:'yasumi no hi', vi:'ngày nghỉ', pos:'cụm danh từ' },
        { jp:'相撲', kana:'すもう', romaji:'sumō', vi:'sumo', pos:'danh từ' },
        { jp:'花見', kana:'はなみ', romaji:'hanami', vi:'ngắm hoa anh đào', pos:'danh từ' },
        { jp:'まだまだ', kana:'まだまだ', romaji:'madamada', vi:'vẫn còn kém lắm (khiêm tốn)', pos:'trạng từ' },
        { jp:'だんだん', kana:'だんだん', romaji:'dandan', vi:'dần dần', pos:'trạng từ' },
        { jp:'もうすぐ', kana:'もうすぐ', romaji:'mōsugu', vi:'sắp', pos:'trạng từ' }
      ],
      dialogue:[
        { sp:'A', jp:'クアンさん は 温泉[おんせん] に 行[い]った こと が あります か 。', vi:'Quân đã từng đi suối nước nóng chưa?' },
        { sp:'B', jp:'はい 、 去年[きょねん] 箱根[はこね] へ 行[い]きました 。 温泉[おんせん] に 入[はい]ったり 、 おいしい 魚[さかな] を 食[た]べたり しました 。', vi:'Rồi, năm ngoái tôi đi Hakone. Tôi tắm suối nước nóng, ăn cá ngon.' },
        { sp:'A', jp:'いい です ね 。 富士山[ふじさん] に 登[のぼ]った こと は ？', vi:'Thích thật. Thế đã leo núi Phú Sĩ chưa?' },
        { sp:'B', jp:'一度[いちど] も ありません 。 でも 、 夏[なつ] に 登[のぼ]りたい です 。', vi:'Chưa lần nào. Nhưng hè này tôi muốn leo.' },
        { sp:'A', jp:'夏[なつ] は 人[ひと] が 多[おお]く なります よ 。 早[はや]く 予約[よやく] して ください 。', vi:'Mùa hè đông người lắm đấy. Hãy đặt sớm nhé.' },
        { sp:'B', jp:'はい 。 クアン の 日本語[にほんご] も だんだん 上手[じょうず] に なりました ね 。', vi:'Vâng. Tiếng Nhật của Quân cũng dần giỏi lên rồi nhỉ.' }
      ]
    },
    {
      level:'n5', no:20, jp:'普通形 — 明日は雨だと思います', vi:'Thể thường — nói ý kiến, tường thuật; tổng ôn N5',
      skill:'Bảng thể thường (V/A/N), 〜と思います, 〜と言いました, 〜でしょう?, câu hỏi thể thường; checklist JLPT N5',
      kanji:['思','言','雨','天','気','明','雪','今','週','末'],
      grammar:[
        { form:'Bảng thể thường (普通形)', vi:'V: 書く / 書かない / 書いた / 書かなかった · A-い: 高い / 高くない / 高かった / 高くなかった · な-A, N: 静かだ / 静かじゃない / 静かだった / 静かじゃなかった', note:'Dùng với bạn bè, trong nhật ký, và trước と思う・と言う・でしょう… Câu hỏi thể thường lược か: 行く？ ↗', ex:{ jp:'明日[あした] 、 一緒[いっしょ]に 映画[えいが] を 見[み]ない ？ — うん 、 見[み]る 。', vi:'Mai xem phim cùng không? — Ừ, xem.' } },
        { form:'普通形 と 思います', vi:'tôi nghĩ rằng …', note:'Ý kiến/phỏng đoán. N/な-A cần だ: 雨だと思います. Hỏi ý: 〜についてどう思いますか.', ex:{ jp:'明日[あした] は 雨[あめ] だ と 思[おも]います 。 日本語[にほんご] の 試験[しけん] は 難[むずか]しくない と 思[おも]います 。', vi:'Tôi nghĩ mai mưa. Tôi nghĩ bài thi tiếng Nhật không khó.' } },
        { form:'「〜」と 言いました / 普通形 と 言いました', vi:'đã nói rằng …', note:'Trực tiếp giữ nguyên trong ngoặc 「」; gián tiếp đổi sang thể thường.', ex:{ jp:'先生[せんせい] は 明日[あした] 試験[しけん] が ある と 言[い]いました 。', vi:'Thầy nói mai có bài thi.' } },
        { form:'〜でしょう？ ↗', vi:'… phải không? (tìm sự đồng tình)', note:'Ngữ điệu lên; thể thường + でしょう (N/な-A không có だ): 楽しいでしょう？ 静かでしょう？', ex:{ jp:'日本[にほん] の 冬[ふゆ] は 寒[さむ]い でしょう ？ — ええ 、 とても 寒[さむ]い です 。', vi:'Mùa đông Nhật lạnh lắm phải không? — Vâng, rất lạnh.' } }
      ],
      vocab:[
        { jp:'思う', kana:'おもう', romaji:'omou', vi:'nghĩ', pos:'động từ nhóm I', g:'1' },
        { jp:'言う', kana:'いう', romaji:'iu', vi:'nói', pos:'động từ nhóm I', g:'1' },
        { jp:'勝つ', kana:'かつ', romaji:'katsu', vi:'thắng', pos:'động từ nhóm I', g:'1', note:'負ける (まける) thua' },
        { jp:'役に立つ', kana:'やくにたつ', romaji:'yaku ni tatsu', vi:'có ích', pos:'cụm động từ' },
        { jp:'足りる', kana:'たりる', romaji:'tariru', vi:'đủ', pos:'động từ nhóm II', g:'2' },
        { jp:'意見', kana:'いけん', romaji:'iken', vi:'ý kiến', pos:'danh từ' },
        { jp:'話', kana:'はなし', romaji:'hanashi', vi:'câu chuyện', pos:'danh từ' },
        { jp:'ニュース', kana:'ニュース', romaji:'nyūsu', vi:'tin tức', pos:'danh từ' },
        { jp:'本当', kana:'ほんとう', romaji:'hontō', vi:'thật', pos:'danh từ / tính từ な', note:'本当ですか — Thật à?' },
        { jp:'嘘', kana:'うそ', romaji:'uso', vi:'nói dối', pos:'danh từ' },
        { jp:'きっと', kana:'きっと', romaji:'kitto', vi:'chắc chắn', pos:'trạng từ' },
        { jp:'たぶん', kana:'たぶん', romaji:'tabun', vi:'có lẽ', pos:'trạng từ' },
        { jp:'うん', kana:'うん', romaji:'un', vi:'ừ (thân mật)', pos:'thán từ', note:'ううん = không' },
        { jp:'〜について', kana:'について', romaji:'ni tsuite', vi:'về …', pos:'cụm trợ từ' },
        { jp:'〜でしょう', kana:'でしょう', romaji:'deshō', vi:'… phải không / có lẽ', pos:'trợ động từ' },
        { jp:'合格', kana:'ごうかく', romaji:'gōkaku', vi:'đỗ (thi)', pos:'danh từ (する)' },
        { jp:'頑張る', kana:'がんばる', romaji:'ganbaru', vi:'cố gắng', pos:'động từ nhóm I', g:'1', note:'頑張ってください — Cố lên!' }
      ],
      dialogue:[
        { sp:'A', jp:'クアン 、 明日[あした] 試験[しけん] だ ね 。 大丈夫[だいじょうぶ] ？', vi:'Quân, mai thi rồi nhỉ. Ổn chứ?' },
        { sp:'B', jp:'うん 。 でも 、 聴解[ちょうかい] は ちょっと 難[むずか]しい と 思[おも]う 。', vi:'Ừ. Nhưng tôi nghĩ phần nghe hơi khó.' },
        { sp:'A', jp:'先生[せんせい] は 何[なん] て 言[い]った ？', vi:'Thầy nói gì?' },
        { sp:'B', jp:'毎日[まいにち] 日本語[にほんご] の ニュース を 聞[き]いた ほう が いい と 言[い]った 。', vi:'Thầy nói nên nghe tin tức tiếng Nhật mỗi ngày.' },
        { sp:'A', jp:'そう だ ね 。 クアン は 毎日[まいにち] 勉強[べんきょう]して いる でしょう ？ きっと 合格[ごうかく]する と 思[おも]う よ 。', vi:'Đúng đấy. Quân học mỗi ngày mà, phải không? Tớ nghĩ chắc chắn đỗ.' },
        { sp:'B', jp:'ありがとう 。 頑張[がんば]る 。', vi:'Cảm ơn. Tớ sẽ cố.' }
      ]
    }
  ]
};
if (typeof module !== 'undefined') module.exports = { COURSE_JA };
