/* ============================================================
   LangLab — KHO NGHĨA TỪ ĐIỂN TIẾNG NHẬT (soạn tay) cho từ lõi: trợ từ, đại từ, từ nối, động từ/tính từ hay dùng.
   key = dạng từ điển (kanji nếu có) → { kana, romaji, vi, pos, g, senses:[{vi, ex:[jp (furigana, tách từ), vi]}], gov, coll:[...], note }
   ============================================================ */
const JA_DICT = {
  /* ---------- Trợ từ ---------- */
  'は':{ kana:'は', romaji:'wa', vi:'(trợ từ chủ đề)', pos:'trợ từ', senses:[{vi:'đánh dấu chủ đề của câu («về … thì»)', ex:['わたし は 学生[がくせい] です 。','Tôi là sinh viên.']},{vi:'đối chiếu, nhấn mạnh phủ định', ex:['肉[にく] は 食[た]べません 。','Thịt thì tôi không ăn.']}], note:'Đọc «wa». Khác が: は nêu chủ đề đã biết; が nêu chủ ngữ mới/nhấn mạnh (だれが来ましたか).' },
  'が':{ kana:'が', romaji:'ga', vi:'(trợ từ chủ ngữ); nhưng', pos:'trợ từ', senses:[{vi:'chủ ngữ (thông tin mới, sau từ nghi vấn)', ex:['だれ が 来[き]ました か 。','Ai đã đến?']},{vi:'đối tượng của 好き・上手・分かる・欲しい・できる', ex:['寿司[すし] が 好[す]き です 。','Tôi thích sushi.']},{vi:'nối câu: nhưng', ex:['安[やす]い です が 、 おいしくない です 。','Rẻ nhưng không ngon.']}] },
  'を':{ kana:'を', romaji:'o', vi:'(trợ từ tân ngữ)', pos:'trợ từ', senses:[{vi:'tân ngữ trực tiếp', ex:['本[ほん] を 読[よ]みます 。','Tôi đọc sách.']},{vi:'nơi đi qua / rời khỏi', ex:['橋[はし] を 渡[わた]ります 。 家[うち] を 出[で]ます 。','Băng qua cầu. Rời khỏi nhà.']}], note:'Đọc «o».' },
  'に':{ kana:'に', romaji:'ni', vi:'ở, vào, đến, cho', pos:'trợ từ', senses:[{vi:'nơi tồn tại (あります/います)', ex:['机[つくえ] の 上[うえ] に 本[ほん] が あります 。','Trên bàn có sách.']},{vi:'thời điểm', ex:['七時[しちじ] に 起[お]きます 。','Dậy lúc 7 giờ.']},{vi:'đích đến / người nhận', ex:['母[はは] に 電話[でんわ] を かけます 。','Gọi điện cho mẹ.']},{vi:'mục đích với 行く/来る', ex:['映画[えいが] を 見[み] に 行[い]きます 。','Đi xem phim.']}], coll:['〜に 乗[の]る — lên xe','〜に 会[あ]う — gặp','〜に 住[す]む — sống ở','〜に なる — trở thành'] },
  'で':{ kana:'で', romaji:'de', vi:'ở (nơi hành động); bằng', pos:'trợ từ', senses:[{vi:'nơi diễn ra hành động', ex:['食堂[しょくどう] で 食[た]べます 。','Ăn ở nhà ăn.']},{vi:'phương tiện, công cụ, ngôn ngữ', ex:['電車[でんしゃ] で 行[い]きます 。 日本語[にほんご] で 話[はな]します 。','Đi bằng tàu. Nói bằng tiếng Nhật.']},{vi:'phạm vi (nhất trong…)', ex:['クラス で 一番[いちばん] 背[せ] が 高[たか]い です 。','Cao nhất lớp.']},{vi:'nguyên nhân', ex:['病気[びょうき] で 休[やす]みました 。','Nghỉ vì ốm.']}] },
  'へ':{ kana:'へ', romaji:'e', vi:'đến, về phía', pos:'trợ từ', senses:[{vi:'hướng di chuyển', ex:['学校[がっこう] へ 行[い]きます 。','Đi đến trường.']}], note:'Đọc «e». Có thể thay bằng に.' },
  'と':{ kana:'と', romaji:'to', vi:'và; với; rằng', pos:'trợ từ', senses:[{vi:'liệt kê đầy đủ: và', ex:['パン と 卵[たまご] を 買[か]います 。','Mua bánh mì và trứng.']},{vi:'cùng với', ex:['友達[ともだち] と 行[い]きます 。','Đi với bạn.']},{vi:'trích dẫn: rằng (と思う, と言う)', ex:['雨[あめ] だ と 思[おも]います 。','Tôi nghĩ trời mưa.']}] },
  'も':{ kana:'も', romaji:'mo', vi:'cũng; cả', pos:'trợ từ', senses:[{vi:'cũng (thay は/が/を)', ex:['わたし も 学生[がくせい] です 。','Tôi cũng là sinh viên.']},{vi:'với từ nghi vấn + phủ định: không … gì cả', ex:['何[なに] も 食[た]べません でした 。','Không ăn gì cả.']}] },
  'の':{ kana:'の', romaji:'no', vi:'của; (danh từ hoá)', pos:'trợ từ', senses:[{vi:'sở hữu, thuộc tính', ex:['わたし の 本[ほん] 。 日本[にほん] の 車[くるま] 。','Sách của tôi. Xe Nhật.']},{vi:'thay danh từ đã nói', ex:['この かばん は わたし の です 。','Cái cặp này là của tôi.']},{vi:'danh từ hoá động từ (N4)', ex:['歌[うた]う の が 好[す]き です 。','Tôi thích hát.']}] },
  'か':{ kana:'か', romaji:'ka', vi:'(hỏi); hay', pos:'trợ từ', senses:[{vi:'cuối câu hỏi', ex:['学生[がくせい] です か 。','Là sinh viên phải không?']},{vi:'hoặc', ex:['お茶[ちゃ] か コーヒー を 飲[の]みます 。','Uống trà hoặc cà phê.']},{vi:'bất định: 何か, どこか, だれか', ex:['だれ か 来[き]ました 。','Ai đó đã đến.']}] },
  'ね':{ kana:'ね', romaji:'ne', vi:'… nhỉ (tìm đồng tình)', pos:'trợ từ cuối câu', senses:[{vi:'xác nhận, đồng cảm', ex:['いい 天気[てんき] です ね 。','Trời đẹp nhỉ.']}] },
  'よ':{ kana:'よ', romaji:'yo', vi:'… đấy (báo thông tin mới)', pos:'trợ từ cuối câu', senses:[{vi:'nhấn mạnh điều người nghe chưa biết', ex:['この 店[みせ] は おいしい です よ 。','Quán này ngon đấy.']}] },
  'から':{ kana:'から', romaji:'kara', vi:'từ; vì', pos:'trợ từ / liên từ', senses:[{vi:'từ (thời gian, nơi, người)', ex:['九時[くじ] から 働[はたら]きます 。','Làm từ 9 giờ.']},{vi:'vì (cuối vế lý do)', ex:['忙[いそが]しい です から 、 行[い]きません 。','Vì bận nên không đi.']},{vi:'V-てから: sau khi', ex:['食[た]べて から 、 出[で]かけます 。','Ăn xong rồi ra ngoài.']}] },
  'まで':{ kana:'まで', romaji:'made', vi:'đến (tận)', pos:'trợ từ', senses:[{vi:'điểm kết thúc thời gian/nơi', ex:['五時[ごじ] まで 働[はたら]きます 。','Làm đến 5 giờ.']}], coll:['〜までに — trước (hạn) (N4)'] },
  'や':{ kana:'や', romaji:'ya', vi:'và (liệt kê ví dụ)', pos:'trợ từ', senses:[{vi:'liệt kê không đầy đủ, thường kèm など', ex:['りんご や みかん など を 買[か]いました 。','Mua táo, quýt, v.v.']}] },
  'だけ':{ kana:'だけ', romaji:'dake', vi:'chỉ', pos:'trợ từ', senses:[{vi:'giới hạn', ex:['一人[ひとり] だけ 来[き]ました 。','Chỉ một người đến.']}], note:'Khác しか + phủ định (N4): 一人しか来ませんでした.' },
  /* ---------- Đại từ, từ hỏi ---------- */
  'ぼく':{ kana:'ぼく', romaji:'boku', vi:'tôi (nam, thân mật)', pos:'đại từ', senses:[{vi:'ngôi thứ nhất, nam giới, không trang trọng', ex:['ぼく は 大学生[だいがくせい] です 。','Tớ là sinh viên.']}], note:'Trang trọng hơn: わたし; nam thô: おれ.' },
  'どう':{ kana:'どう', romaji:'dō', vi:'thế nào', pos:'trạng từ nghi vấn', senses:[{vi:'hỏi cảm nhận, cách thức', ex:['日本[にほん] の 生活[せいかつ] は どう です か 。','Cuộc sống ở Nhật thế nào?']}], coll:['どうですか — thế nào? / mời dùng','どうして — tại sao','どうやって — bằng cách nào','どうぞ — xin mời','どうも — cảm ơn/xin lỗi (ngắn)'] },
  'いつ':{ kana:'いつ', romaji:'itsu', vi:'khi nào', pos:'nghi vấn', senses:[{vi:'hỏi thời gian (không dùng に sau いつ)', ex:['いつ 日本[にほん] へ 来[き]ました か 。','Bạn đến Nhật khi nào?']}], coll:['いつも — luôn luôn','いつか — một ngày nào đó'] },
  /* ---------- Từ nối, trạng từ hay gặp ---------- */
  'でも':{ kana:'でも', romaji:'demo', vi:'nhưng (đầu câu)', pos:'liên từ', senses:[{vi:'đối lập, khẩu ngữ', ex:['高[たか]い です 。 でも 、 おいしい です 。','Đắt. Nhưng ngon.']}], note:'Trang trọng: しかし. Trong câu: 〜が.' },
  'そして':{ kana:'そして', romaji:'soshite', vi:'và, rồi', pos:'liên từ', senses:[{vi:'thêm ý, nối sự việc', ex:['朝[あさ]ご飯[はん] を 食[た]べました 。 そして 、 学校[がっこう] へ 行[い]きました 。','Ăn sáng. Rồi đi học.']}] },
  'じゃ':{ kana:'じゃ', romaji:'ja', vi:'vậy thì', pos:'liên từ (khẩu ngữ)', senses:[{vi:'mở lời kết luận/tạm biệt', ex:['じゃ 、 また 明日[あした] 。','Vậy hẹn mai nhé.']}], note:'Đầy đủ: では. じゃありません = không phải.' },
  'ぐらい':{ kana:'ぐらい', romaji:'gurai', vi:'khoảng', pos:'trợ từ', senses:[{vi:'ước lượng số lượng/thời lượng', ex:['駅[えき] まで 十分[じゅっぷん] ぐらい かかります 。','Đến ga mất khoảng 10 phút.']}], note:'Thời điểm dùng ごろ: 八時ごろ.' },
  'ごろ':{ kana:'ごろ', romaji:'goro', vi:'khoảng (thời điểm)', pos:'hậu tố', senses:[{vi:'ước lượng mốc thời gian', ex:['八時[はちじ] ごろ 帰[かえ]ります 。','Khoảng 8 giờ về.']}] },
  /* ---------- Động từ lõi ---------- */
  'ある':{ kana:'ある', romaji:'aru', vi:'có; ở (vật)', pos:'động từ nhóm I', g:'1', senses:[{vi:'tồn tại (vật, cây, sự việc)', ex:['机[つくえ] の 上[うえ] に 本[ほん] が あります 。','Trên bàn có sách.']},{vi:'sở hữu', ex:['時間[じかん] が ありません 。','Không có thời gian.']},{vi:'diễn ra (sự kiện)', ex:['明日[あした] 試験[しけん] が あります 。','Mai có bài thi.']}], note:'Phủ định thường: ない (không phải あらない).' },
  'いる':{ kana:'いる', romaji:'iru', vi:'có; ở (người, động vật)', pos:'động từ nhóm II', g:'2', senses:[{vi:'tồn tại của người/động vật', ex:['部屋[へや] に 猫[ねこ] が います 。','Trong phòng có mèo.']},{vi:'V-ている: đang / trạng thái', ex:['今[いま] 本[ほん] を 読[よ]んで います 。','Đang đọc sách.']}] },
  'する':{ kana:'する', romaji:'suru', vi:'làm', pos:'động từ nhóm III', g:'3', senses:[{vi:'làm (hành động chung)', ex:['何[なに] を して います か 。','Bạn đang làm gì?']},{vi:'N + する: nhiều danh từ Hán thành động từ', ex:['勉強[べんきょう]します 、 電話[でんわ]します 、 結婚[けっこん]します','học, gọi điện, kết hôn']},{vi:'〜にする: chọn', ex:['コーヒー に します 。','Tôi chọn cà phê.']}], note:'します, して, した, しない; khả năng: できる.' },
  'できる':{ kana:'できる', romaji:'dekiru', vi:'có thể; làm được; hoàn thành', pos:'động từ nhóm II', g:'2', senses:[{vi:'khả năng (N が / V-ること が できる)', ex:['日本語[にほんご] が できます 。','Tôi biết tiếng Nhật.']},{vi:'được tạo ra, xong', ex:['新[あたら]しい 駅[えき] が できました 。','Ga mới đã xây xong.']}] },
  '行く':{ kana:'いく', romaji:'iku', vi:'đi', pos:'động từ nhóm I', g:'1', senses:[{vi:'đi (rời khỏi vị trí người nói)', ex:['明日[あした] 大阪[おおさか] へ 行[い]きます 。','Mai tôi đi Osaka.']},{vi:'V-ていく: đi rồi làm; tiếp diễn về sau (N4)', ex:['持[も]って 行[い]きます 。','Mang đi.']}], note:'Thể て bất quy tắc: 行って; いく cũng viết ゆく (văn).' },
  '来る':{ kana:'くる', romaji:'kuru', vi:'đến', pos:'động từ nhóm III', g:'3', senses:[{vi:'đến (về phía người nói)', ex:['友達[ともだち] が 家[うち] へ 来[き]ます 。','Bạn đến nhà tôi.']}], note:'来ます (きます), 来て (きて), 来ない (こない), 来られる (こられる).' },
  '見る':{ kana:'みる', romaji:'miru', vi:'xem, nhìn', pos:'động từ nhóm II', g:'2', senses:[{vi:'xem, nhìn thấy', ex:['テレビ を 見[み]ます 。','Xem ti vi.']},{vi:'V-てみる: thử làm (N4)', ex:['食[た]べて みます 。','Ăn thử.']}] },
  '言う':{ kana:'いう', romaji:'iu', vi:'nói', pos:'động từ nhóm I', g:'1', senses:[{vi:'nói, phát ngôn', ex:['先生[せんせい] は 「明日[あした] 休[やす]み です」 と 言[い]いました 。','Thầy nói: «Mai nghỉ».']},{vi:'〜と言います: tên là', ex:['これ は 日本語[にほんご] で 何[なん] と 言[い]います か 。','Cái này tiếng Nhật gọi là gì?']}], note:'Phát âm ゆう trong khẩu ngữ.' },
  '思う':{ kana:'おもう', romaji:'omou', vi:'nghĩ', pos:'động từ nhóm I', g:'1', senses:[{vi:'普通形 + と思う: nghĩ rằng', ex:['明日[あした] は 晴[は]れる と 思[おも]います 。','Tôi nghĩ mai trời nắng.']},{vi:'〜について どう思いますか', ex:['日本[にほん] の 生活[せいかつ] について どう 思[おも]います か 。','Bạn nghĩ gì về cuộc sống ở Nhật?']}] },
  /* ---------- Tính từ lõi ---------- */
  'いい':{ kana:'いい', romaji:'ii', vi:'tốt, được', pos:'tính từ い', senses:[{vi:'tốt', ex:['いい 天気[てんき] です ね 。','Trời đẹp nhỉ.']},{vi:'được (cho phép)', ex:['入[はい]って も いい です か 。 — いい です よ 。','Vào được không? — Được.']}], note:'Biến đổi theo よい: よくない, よかった, よくて, よければ.' },
  '大きい':{ kana:'おおきい', romaji:'ōkii', vi:'to, lớn', pos:'tính từ い', senses:[{vi:'kích thước, quy mô, âm lượng lớn', ex:['大[おお]きい 声[こえ] で 話[はな]して ください 。','Hãy nói to lên.']}], note:'Trước danh từ cũng có dạng 大きな (大きな木).' },
  '好き':{ kana:'すき', romaji:'suki', vi:'thích', pos:'tính từ な', senses:[{vi:'N が 好き: thích', ex:['犬[いぬ] が 好[す]き です 。','Tôi thích chó.']},{vi:'好きな N: N yêu thích', ex:['好[す]き な 食[た]べ物[もの] は 何[なん] です か 。','Món ăn yêu thích của bạn là gì?']}], coll:['大好き — rất thích','好きになる — trở nên thích, phải lòng'] }
};
if (typeof module !== 'undefined') module.exports = { JA_DICT };
