/* ============================================================
   LangLab — «BẠN CÓ BIẾT?» : kho fact văn hoá – ngôn ngữ – ẩm thực – lễ hội –
   con người – động vật – thói quen của các nước có tiếng đang học.
   Mỗi mục: { lang, cat, title, body, extra, word:{t (bản ngữ), r (phiên âm), vi}, art (mã hình minh hoạ) }
   Hình minh hoạ là SVG tự vẽ (FACT_ART trong app.js) — không dùng ảnh ngoài, đổi màu theo tông của ngôn ngữ.
   Nội dung tự biên soạn, kiểm chứng theo hiểu biết phổ thông; không sao chép nguyên văn nguồn nào.
   ============================================================ */
const FACTS = [
  /* =============== TIẾNG HÀN =============== */
  { lang:'ko', cat:'Ngôn ngữ', art:'hangul', title:'Hangul được «phát minh», không phải tiến hoá tự nhiên',
    body:'Phần lớn hệ chữ trên thế giới hình thành dần qua hàng nghìn năm. Hangul thì khác: vua Sejong cho công bố năm 1446 với tên 훈민정음 (Huấn dân chính âm) — «âm đúng để dạy dân».',
    extra:'Phụ âm được vẽ mô phỏng hình dáng miệng – lưỡi khi phát âm: ㄱ giống cuống lưỡi chạm ngạc mềm, ㅁ giống khuôn miệng khép. Nhờ vậy người mới có thể đọc được Hangul trong vài giờ.',
    word:{ t:'한글', r:'hangeul', vi:'chữ Hàn' } },
  { lang:'ko', cat:'Ẩm thực', art:'kimchi', title:'Mỗi nhà một vị kimchi, và có cả tủ lạnh riêng cho nó',
    body:'Kimchi có hàng trăm biến thể theo vùng và mùa. Cuối thu, các gia đình cùng nhau muối một lượng lớn cho cả mùa đông — phong tục 김장 (kimjang) đã được UNESCO ghi danh năm 2013.',
    extra:'Nhiều căn hộ Hàn Quốc có 김치냉장고 — tủ lạnh chuyên dụng giữ nhiệt độ ổn định quanh 0 °C để kimchi lên men chậm và không ám mùi sang thực phẩm khác.',
    word:{ t:'김치', r:'gimchi', vi:'kim chi' } },
  { lang:'ko', cat:'Thói quen', art:'bow', title:'Rót rượu cho người lớn tuổi phải bằng hai tay',
    body:'Trong bữa ăn, người nhỏ tuổi rót cho người lớn bằng hai tay, và khi uống thì hơi quay mặt sang bên, che ly bằng tay — cử chỉ thể hiện sự kính trọng.',
    extra:'Người Hàn cũng không tự rót cho mình: bạn rót cho người bên cạnh, và họ rót lại cho bạn. Đó là một cách giữ sự quan tâm lẫn nhau trong bàn tiệc.',
    word:{ t:'건배', r:'geonbae', vi:'cạn ly' } },
  { lang:'ko', cat:'Con người', art:'age', title:'Người Hàn từng có «tuổi Hàn» — sinh ra đã một tuổi',
    body:'Theo cách tính truyền thống, em bé chào đời là 1 tuổi và thêm một tuổi vào ngày Tết, nên có người «già» hơn tuổi thật tới hai năm.',
    extra:'Từ tháng 6/2023, Hàn Quốc chính thức dùng tuổi quốc tế trong giấy tờ hành chính. Nhưng trong đời thường, câu hỏi «몇 살이에요?» vẫn quan trọng, vì tuổi quyết định cách xưng hô và mức kính ngữ.',
    word:{ t:'몇 살이에요?', r:'myeot sarieyo?', vi:'Bạn bao nhiêu tuổi?' } },
  { lang:'ko', cat:'Lễ hội', art:'lantern', title:'Chuseok — «Lễ Tạ ơn» của người Hàn',
    body:'Rằm tháng Tám âm lịch, cả nước về quê tạ ơn tổ tiên vì mùa màng. Món không thể thiếu là 송편 — bánh gạo hình bán nguyệt hấp trên lá thông.',
    extra:'Người ta nói ai nặn 송편 đẹp sẽ sinh con xinh — một cách vui để cả nhà cùng ngồi nặn bánh với nhau đêm trước lễ.',
    word:{ t:'추석', r:'chuseok', vi:'Tết Trung thu Hàn Quốc' } },
  { lang:'ko', cat:'Ngôn ngữ', art:'letter', title:'Tiếng Hàn có tới bảy bậc lịch sự',
    body:'Cùng một câu «ăn cơm» có thể nói theo nhiều bậc: 먹어 (thân), 먹어요 (lịch sự), 먹습니다 (trang trọng), 드십니다 (kính ngữ dành cho người trên).',
    extra:'Ngày nay đời sống dùng chủ yếu ba bậc, nhưng chọn sai bậc vẫn gây khó xử — nên người Hàn hỏi tuổi và nghề nghiệp khá sớm để biết nên nói thế nào.',
    word:{ t:'존댓말', r:'jondaenmal', vi:'kính ngữ' } },
  { lang:'ko', cat:'Động vật', art:'tiger', title:'Hổ là «linh vật quốc gia», và luôn xuất hiện trong truyện cổ',
    body:'Truyện cổ Hàn thường mở đầu bằng «호랑이 담배 피우던 시절» — thời hổ còn hút thuốc, tức là ngày xửa ngày xưa.',
    extra:'Hổ Siberia từng sống khắp bán đảo. Hình hổ được chọn làm linh vật Olympic Seoul 1988 (Hodori) và PyeongChang 2018 (Soohorang).',
    word:{ t:'호랑이', r:'horangi', vi:'con hổ' } },
  { lang:'ko', cat:'Thói quen', art:'ondol', title:'Nhà Hàn sưởi từ dưới sàn, nên người ta ngồi bệt',
    body:'온돌 (ondol) là hệ thống dẫn hơi nóng dưới nền nhà, có từ hơn hai nghìn năm. Vì chỗ ấm nhất là mặt sàn nên sinh hoạt truyền thống diễn ra ở dưới thấp: ngồi bệt, ngủ nệm trải sàn.',
    extra:'Đó cũng là lý do phải bỏ giày ở cửa: sàn nhà là nơi ngồi và nằm, phải giữ sạch tuyệt đối.',
    word:{ t:'온돌', r:'ondol', vi:'sàn sưởi' } },
  { lang:'ko', cat:'Văn hoá', art:'seaweed', title:'Sinh nhật thì ăn canh rong biển',
    body:'Sản phụ Hàn Quốc ăn 미역국 để hồi sức. Vì thế mỗi sinh nhật, người ta lại ăn món canh ấy — như một lời nhớ ơn mẹ.',
    extra:'Ngược lại, trước kỳ thi quan trọng thì kiêng 미역국, vì rong biển trơn, sợ «trượt».',
    word:{ t:'미역국', r:'miyeokguk', vi:'canh rong biển' } },
  { lang:'ko', cat:'Con người', art:'ppalli', title:'«빨리빨리» — nhịp sống nhanh thành nét văn hoá',
    body:'Giao hàng trong ngày, wifi khắp nơi, hành chính trực tuyến vài phút xong: tinh thần 빨리빨리 (nhanh lên, nhanh lên) đã đẩy Hàn Quốc thành nước có hạ tầng số hàng đầu.',
    extra:'Mặt trái là áp lực. Gần đây xu hướng «워라밸» (work–life balance) và các quán cà phê tĩnh lặng nổi lên như một phản ứng cân bằng lại.',
    word:{ t:'빨리빨리', r:'ppalli-ppalli', vi:'nhanh lên, nhanh lên' } },
  { lang:'ko', cat:'Lễ hội', art:'lantern', title:'Ngày lễ tình nhân kéo dài suốt ba tháng',
    body:'14/2 con gái tặng chocolate; 14/3 (White Day) con trai tặng lại kẹo; 14/4 (Black Day) những người còn độc thân rủ nhau ăn 짜장면 — mì tương đen.',
    extra:'Thực ra tháng nào ngày 14 cũng có một «ngày lễ» nhỏ do giới trẻ nghĩ ra, từ Rose Day tới Hug Day.',
    word:{ t:'짜장면', r:'jjajangmyeon', vi:'mì tương đen' } },
  { lang:'ko', cat:'Ẩm thực', art:'bowl', title:'Bát cơm không được nhấc khỏi bàn',
    body:'Khác với Nhật hay Việt Nam, người Hàn để bát cơm trên bàn và dùng thìa 숟가락 để ăn cơm, canh; đũa dùng cho thức ăn.',
    extra:'Bộ thìa – đũa kim loại 수저 là nét riêng của Hàn Quốc: từ thời Joseon, đồ ăn bằng đồng được cho là giúp phát hiện độc trong thức ăn của hoàng gia.',
    word:{ t:'수저', r:'sujeo', vi:'bộ thìa đũa' } },

  /* =============== TIẾNG TRUNG =============== */
  { lang:'zh', cat:'Ngôn ngữ', art:'hanzi', title:'Biết 3.000 chữ Hán là đọc được ~99% văn bản đời thường',
    body:'Kho chữ Hán có hàng chục nghìn ký tự, nhưng tần suất rất lệch: khoảng 1.000 chữ phổ biến nhất đã bao phủ ~90% văn bản, 2.500–3.000 chữ đưa con số lên gần 99%.',
    extra:'Danh sách chữ thông dụng do nhà nước công bố (通用规范汉字表) gồm 8.105 chữ, chia ba bậc; bậc một 3.500 chữ là mức yêu cầu cho giáo dục phổ thông.',
    word:{ t:'汉字', r:'hànzì', vi:'chữ Hán' } },
  { lang:'zh', cat:'Ngôn ngữ', art:'tone', title:'Cùng âm «ma», đổi thanh điệu là đổi cả nghĩa',
    body:'妈 (mā) mẹ · 麻 (má) gai · 马 (mǎ) ngựa · 骂 (mà) mắng. Tiếng phổ thông có bốn thanh và một thanh nhẹ, nên thanh điệu quan trọng ngang phụ âm và nguyên âm.',
    extra:'Người nói tiếng Việt có lợi thế lớn: tiếng Việt cũng là ngôn ngữ thanh điệu, tai đã quen phân biệt cao độ.',
    word:{ t:'妈麻马骂', r:'mā má mǎ mà', vi:'mẹ – gai – ngựa – mắng' } },
  { lang:'zh', cat:'Lễ hội', art:'redenvelope', title:'Xuân vận — cuộc di chuyển lớn nhất hành tinh',
    body:'Dịp Tết Nguyên đán, hàng trăm triệu người Trung Quốc về quê. Giai đoạn 40 ngày này gọi là 春运 (xuân vận), với số lượt di chuyển lên tới hàng tỉ.',
    extra:'Phong bao đỏ 红包 nay phần lớn được gửi qua điện thoại; đêm giao thừa, các ứng dụng xử lý hàng tỉ lượt lì xì điện tử chỉ trong vài giờ.',
    word:{ t:'红包', r:'hóngbāo', vi:'bao lì xì' } },
  { lang:'zh', cat:'Động vật', art:'panda', title:'Gấu trúc là loài ăn thịt… nhưng 99% khẩu phần là tre',
    body:'Hệ tiêu hoá của gấu trúc vẫn là hệ của loài ăn thịt, hấp thu tre rất kém, nên chúng phải ăn 12–38 kg tre mỗi ngày và dành 12–16 giờ để ăn.',
    extra:'Mọi con gấu trúc ở sở thú nước ngoài đều thuộc sở hữu Trung Quốc theo thoả thuận cho mượn — «ngoại giao gấu trúc» có từ thập niên 1950.',
    word:{ t:'熊猫', r:'xióngmāo', vi:'gấu trúc' } },
  { lang:'zh', cat:'Ẩm thực', art:'dumpling', title:'Bắc ăn mì và sủi cảo, Nam ăn cơm',
    body:'Miền Bắc trồng lúa mì nên bột mì là chính: 饺子 (sủi cảo), 面条 (mì), 包子 (bánh bao). Miền Nam trồng lúa nước nên bữa ăn xoay quanh cơm và các món hấp.',
    extra:'Đêm giao thừa miền Bắc gói 饺子 vì hình dáng giống nén bạc cổ 元宝 — mong năm mới sung túc.',
    word:{ t:'饺子', r:'jiǎozi', vi:'sủi cảo' } },
  { lang:'zh', cat:'Văn hoá', art:'number', title:'Số 8 rất được ưa, số 4 bị tránh',
    body:'八 (bā) gần âm với 发 (fā — phát tài), nên biển số, số nhà, số điện thoại có nhiều số 8 được trả giá cao. 四 (sì) lại gần âm 死 (sǐ — chết).',
    extra:'Nhiều toà nhà không có tầng 4, 14, 24; thang máy nhảy thẳng từ 3 lên 5. Lễ khai mạc Olympic Bắc Kinh mở lúc 8 giờ 8 phút ngày 8/8/2008.',
    word:{ t:'八', r:'bā', vi:'số tám' } },
  { lang:'zh', cat:'Thói quen', art:'tea', title:'Gõ nhẹ hai ngón tay là «cảm ơn» khi được rót trà',
    body:'Khi ai đó rót trà cho bạn, thay vì nói cảm ơn giữa cuộc trò chuyện, người ta gõ nhẹ hai ngón tay xuống bàn.',
    extra:'Tương truyền vua Càn Long vi hành, tự rót trà cho tuỳ tùng; họ không thể quỳ lạy giữa quán nên gập hai ngón tay gõ bàn thay cho cái vái.',
    word:{ t:'谢谢', r:'xièxie', vi:'cảm ơn' } },
  { lang:'zh', cat:'Con người', art:'square', title:'Sáng và tối, quảng trường thuộc về các bà các cô',
    body:'广场舞 — nhảy tập thể ngoài quảng trường — là sinh hoạt của hàng chục triệu người trung niên và cao tuổi, thường bắt đầu từ 6 giờ sáng hoặc sau bữa tối.',
    extra:'Loa mở to từng gây tranh cãi tới mức nhiều thành phố phải ra quy định về âm lượng và giờ giấc.',
    word:{ t:'广场舞', r:'guǎngchǎngwǔ', vi:'nhảy quảng trường' } },
  { lang:'zh', cat:'Ngôn ngữ', art:'pinyin', title:'Pinyin mới có từ 1958',
    body:'Trước đó, cách phiên âm phổ biến là Wade–Giles (Peking, Mao Tse-tung). Pinyin ra đời năm 1958 và dần thành chuẩn quốc tế (Beijing, Mao Zedong).',
    extra:'Trẻ em Trung Quốc học pinyin trước, dùng nó để tra chữ và gõ máy tính; hầu hết người lớn ngày nay nhập chữ Hán bằng pinyin.',
    word:{ t:'拼音', r:'pīnyīn', vi:'phiên âm pinyin' } },
  { lang:'zh', cat:'Văn hoá', art:'greatwall', title:'Vạn Lý Trường Thành không phải một bức tường liền',
    body:'Đó là hệ thống tường thành, hào, tháp canh do nhiều triều đại xây trong hơn hai nghìn năm. Phần du khách hay tới gần Bắc Kinh chủ yếu được xây thời Minh.',
    extra:'Tổng chiều dài các đoạn khảo sát được vượt 21.000 km — nhưng nói «nhìn thấy từ vũ trụ bằng mắt thường» là không đúng: tường quá hẹp so với khoảng cách.',
    word:{ t:'长城', r:'Chángchéng', vi:'Trường Thành' } },
  { lang:'zh', cat:'Ẩm thực', art:'hotpot', title:'Lẩu Tứ Xuyên cay nhờ «tê», không chỉ nhờ «cay»',
    body:'Hạt tiêu Tứ Xuyên 花椒 tạo cảm giác tê rần trên môi lưỡi, kết hợp với ớt thành vị 麻辣 (má là) — tê + cay, đặc trưng của ẩm thực Tứ Xuyên.',
    extra:'Cảm giác tê là do chất hydroxy-alpha-sanshool kích thích dây thần kinh xúc giác, tần số rung được đo vào khoảng 50 Hz.',
    word:{ t:'麻辣', r:'málà', vi:'tê cay' } },
  { lang:'zh', cat:'Thói quen', art:'phone', title:'Nhiều người ra đường không mang ví',
    body:'Thanh toán bằng mã QQ/WeChat/Alipay phổ biến tới mức từ quán ăn vỉa hè tới người bán rong đều dán mã QR; tiền mặt gần như chỉ dùng ở vùng sâu.',
    extra:'Vì thế du khách nên cài sẵn ví điện tử liên kết thẻ quốc tế trước khi đến, hoặc mang theo ít tiền mặt để đề phòng.',
    word:{ t:'扫码', r:'sǎomǎ', vi:'quét mã' } },

  /* =============== TIẾNG NGA =============== */
  { lang:'ru', cat:'Ngôn ngữ', art:'cyrillic', title:'Bảng chữ Kirin sinh ra để dịch kinh sách',
    body:'Hai anh em Kirill và Mefodi tạo bảng chữ Slav vào thế kỷ IX để dịch kinh Kitô giáo. Bảng Kirin ngày nay được đặt theo tên Kirill; tiếng Nga hiện dùng 33 chữ cái.',
    extra:'Cuộc cải cách năm 1918 bỏ bốn chữ cái thừa (ѣ, і, ѳ, ѵ) và chữ ъ ở cuối từ — sách in trước đó nhìn rất khác.',
    word:{ t:'алфавит', r:'alfavít', vi:'bảng chữ cái' } },
  { lang:'ru', cat:'Thói quen', art:'shoes', title:'Vào nhà là đổi dép — luôn luôn',
    body:'Chủ nhà thường có sẵn тапочки (dép đi trong nhà) cho khách. Đi giày vào phòng khách bị coi là bất lịch sự, phần vì mùa đông đường đầy tuyết muối và bùn.',
    extra:'Cũng đừng bắt tay hay trao đồ qua ngưỡng cửa — theo quan niệm dân gian sẽ mang lại điều không may.',
    word:{ t:'тапочки', r:'tápochki', vi:'dép đi trong nhà' } },
  { lang:'ru', cat:'Văn hoá', art:'matryoshka', title:'Búp bê Matryoshka trẻ hơn bạn tưởng',
    body:'Con búp bê lồng đầu tiên được làm khoảng năm 1890 tại xưởng ở Moskva, lấy cảm hứng một phần từ búp bê gỗ Nhật Bản.',
    extra:'Tên Matryoshka bắt nguồn từ Matryona — tên phụ nữ thôn quê phổ biến, gợi hình ảnh người mẹ đông con.',
    word:{ t:'матрёшка', r:'matryóshka', vi:'búp bê Nga' } },
  { lang:'ru', cat:'Ẩm thực', art:'samovar', title:'Trà Nga pha đặc rồi… pha loãng ra',
    body:'Người Nga đun nước bằng самовар, pha một ấm trà rất đặc gọi là заварка, rồi rót một chút vào cốc và thêm nước sôi cho vừa khẩu vị từng người.',
    extra:'Trà thường uống kèm mứt варенье — có người cho mứt vào trà, có người ăn từng thìa rồi nhấp trà.',
    word:{ t:'самовар', r:'samovár', vi:'ấm samovar' } },
  { lang:'ru', cat:'Con người', art:'smile', title:'Không cười với người lạ — không phải vì lạnh lùng',
    body:'Trong văn hoá Nga, nụ cười xã giao với người không quen bị xem là thiếu chân thành. Nụ cười dành cho người mình thực sự vui khi gặp.',
    extra:'Có câu «Смех без причины — признак дурачины» (cười vô cớ là dấu hiệu của kẻ dại) — nhưng khi đã thân, người Nga cực kỳ nồng hậu và hiếu khách.',
    word:{ t:'улыбка', r:'ulýbka', vi:'nụ cười' } },
  { lang:'ru', cat:'Lễ hội', art:'blin', title:'Maslenitsa — tuần lễ bánh xèo tiễn mùa đông',
    body:'Trước Mùa Chay, người Nga ăn блины suốt một tuần. Bánh tròn vàng tượng trưng cho mặt trời, mời mùa xuân trở lại.',
    extra:'Cuối tuần lễ, hình nộm rơm Maslenitsa được đốt để tiễn mùa đông; ngày cuối cùng gọi là «Chủ nhật tha thứ», mọi người xin lỗi nhau.',
    word:{ t:'блины', r:'bliný', vi:'bánh xèo Nga' } },
  { lang:'ru', cat:'Văn hoá', art:'metro', title:'Tàu điện ngầm Moskva như một bảo tàng ngầm',
    body:'Mở cửa năm 1935, nhiều ga được trang trí đèn chùm, tranh khảm, tượng đồng. Ga Ploshchad Revolyutsii có 76 bức tượng đồng.',
    extra:'Mũi con chó của bức tượng người lính biên phòng bóng loáng vì hành khách xoa lấy may trước kỳ thi.',
    word:{ t:'метро', r:'metró', vi:'tàu điện ngầm' } },
  { lang:'ru', cat:'Ngôn ngữ', art:'stress', title:'Trọng âm tiếng Nga có thể đổi cả nghĩa',
    body:'за́мок là lâu đài, замо́к là ổ khoá; му́ка là nỗi đau, мука́ là bột mì. Trọng âm không cố định vị trí và không được đánh dấu trong sách báo thường.',
    extra:'Vì thế từ điển và sách học luôn in dấu trọng âm — thói quen nhớ trọng âm cùng lúc với từ mới sẽ tiết kiệm rất nhiều thời gian về sau.',
    word:{ t:'замо́к', r:'zamók', vi:'ổ khoá' } },
  { lang:'ru', cat:'Động vật', art:'bear', title:'Gấu là biểu tượng, nhưng «медведь» nghĩa là «kẻ ăn mật»',
    body:'Người Slav cổ kiêng gọi thẳng tên con gấu vì sợ gọi là nó tới, nên đặt tên vòng: медведь = мёд (mật) + ведать (biết chỗ).',
    extra:'Tên gốc Ấn–Âu của loài gấu vì thế đã biến mất khỏi tiếng Nga — một ví dụ kinh điển về kiêng huý trong ngôn ngữ học.',
    word:{ t:'медведь', r:'medvéd’', vi:'con gấu' } },
  { lang:'ru', cat:'Thói quen', art:'banya', title:'Xông hơi banya rồi lăn xuống tuyết',
    body:'Trong баня, người ta quật nhẹ lên da bằng bó cành bạch dương (веник) để tăng tuần hoàn, rồi ra ngoài dội nước lạnh hoặc lăn mình vào tuyết.',
    extra:'Banya là chuyện xã giao chứ không chỉ là tắm: bạn bè, đồng nghiệp hẹn nhau ở banya để trò chuyện hàng giờ.',
    word:{ t:'баня', r:'bánya', vi:'nhà tắm hơi Nga' } },
  { lang:'ru', cat:'Con người', art:'newyear', title:'Ông già Tuyết Nga đến vào đêm Giao thừa, cùng cháu gái',
    body:'Дед Мороз (Ông già Băng giá) mặc áo choàng xanh hoặc đỏ dài chấm đất, đi cùng cháu gái Снегурочка, và tặng quà đêm 31/12 chứ không phải Giáng sinh.',
    extra:'Giáng sinh Chính thống giáo Nga rơi vào ngày 7/1 theo lịch Julius, nên tháng Một ở Nga có tới hai kỳ nghỉ liền nhau.',
    word:{ t:'Дед Мороз', r:'Ded Moróz', vi:'Ông già Tuyết' } },
  { lang:'ru', cat:'Văn hoá', art:'train', title:'Đi tàu xuyên Siberia mất bảy ngày',
    body:'Tuyến Transsib từ Moskva tới Vladivostok dài 9.289 km, qua 8 múi giờ. Trên tàu, hành khách đổi sang đồ ở nhà, uống trà và trò chuyện với bạn cùng khoang suốt hành trình.',
    extra:'Toàn tuyến chạy theo giờ Moskva để tránh nhầm lẫn — bảng giờ ở ga Vladivostok vẫn ghi giờ thủ đô.',
    word:{ t:'поезд', r:'póyezd', vi:'tàu hoả' } },

  /* =============== TIẾNG NHẬT =============== */
  { lang:'ja', cat:'Ngôn ngữ', art:'sansho', title:'Tiếng Nhật dùng cùng lúc ba hệ chữ',
    body:'Hiragana cho từ thuần Nhật và phần đuôi ngữ pháp, katakana cho từ mượn và nhấn mạnh, kanji cho phần nghĩa. Một câu bình thường thường có cả ba.',
    extra:'Nhờ kanji mà tiếng Nhật viết liền không dấu cách vẫn đọc được: khối kanji báo hiệu chỗ bắt đầu của từ mới.',
    word:{ t:'漢字', r:'kanji', vi:'chữ Hán' } },
  { lang:'ja', cat:'Ẩm thực', art:'sushi', title:'Sushi vốn là cách bảo quản cá bằng cơm lên men',
    body:'Nguyên bản 熟れ寿司 ủ cá trong cơm hàng tháng, khi ăn thì bỏ cơm đi. Sushi kiểu Edo với cơm giấm và cá tươi chỉ xuất hiện đầu thế kỷ 19 như một món ăn nhanh vỉa hè.',
    extra:'Vì thế sushi truyền thống được ăn bằng tay và trong một, hai miếng — người bán tính toán để miếng cơm vừa đủ tan trong miệng.',
    word:{ t:'寿司', r:'sushi', vi:'sushi' } },
  { lang:'ja', cat:'Thói quen', art:'bowjp', title:'Cúi chào có nhiều độ nghiêng khác nhau',
    body:'会釈 nghiêng khoảng 15° khi chào hỏi, 敬礼 khoảng 30° trong công việc, 最敬礼 tới 45° khi xin lỗi hay cảm ơn sâu sắc.',
    extra:'Khi nói chuyện điện thoại, nhiều người Nhật vẫn cúi đầu theo phản xạ dù đối phương không nhìn thấy.',
    word:{ t:'お辞儀', r:'ojigi', vi:'cúi chào' } },
  { lang:'ja', cat:'Lễ hội', art:'sakura', title:'Dự báo hoa anh đào được phát trên bản tin thời tiết',
    body:'Mỗi mùa xuân, «mặt trận hoa anh đào» 桜前線 di chuyển từ Kyushu lên Hokkaido trong khoảng hai tháng, được dự báo tới từng thành phố.',
    extra:'Ngắm hoa 花見 thường là tiệc ngoài trời dưới tán cây; công ty cử người đi giữ chỗ từ sáng sớm.',
    word:{ t:'花見', r:'hanami', vi:'ngắm hoa anh đào' } },
  { lang:'ja', cat:'Con người', art:'train_jp', title:'Tàu trễ 5 phút thì hành khách được phát giấy xác nhận',
    body:'遅延証明書 là giấy chứng nhận tàu chậm để nộp cho công ty hoặc trường học. Ở Tokyo, chậm 5 phút đã đủ điều kiện cấp.',
    extra:'Độ trễ trung bình của Shinkansen tuyến Tokaido tính cả thiên tai chỉ khoảng một phút mỗi chuyến.',
    word:{ t:'遅延証明書', r:'chien shōmeisho', vi:'giấy xác nhận tàu trễ' } },
  { lang:'ja', cat:'Văn hoá', art:'onsen', title:'Tắm onsen: kỳ cọ sạch trước, rồi mới ngâm',
    body:'Bồn onsen là để ngâm thư giãn, không phải để tắm. Khách tắm gội sạch ở khu vòi sen bên ngoài, khăn nhỏ không được thả xuống nước — thường đặt lên đầu.',
    extra:'Nhiều onsen truyền thống vẫn từ chối khách có hình xăm, dù các cơ sở du lịch đang dần nới lỏng quy định này.',
    word:{ t:'温泉', r:'onsen', vi:'suối nước nóng' } },
  { lang:'ja', cat:'Động vật', art:'maneki', title:'Mèo vẫy tay: chân trái gọi khách, chân phải gọi tiền',
    body:'招き猫 giơ chân trái được cho là mời khách vào cửa hàng, giơ chân phải là mời tài lộc. Chân giơ càng cao, phúc đến càng xa.',
    extra:'Nhật cũng có những «đảo mèo» như Aoshima, nơi mèo đông hơn người rất nhiều lần.',
    word:{ t:'招き猫', r:'manekineko', vi:'mèo vẫy tay' } },
  { lang:'ja', cat:'Thói quen', art:'trash', title:'Đường phố sạch nhưng gần như không có thùng rác',
    body:'Người Nhật mang rác về nhà và phân loại theo ngày: rác cháy được, nhựa, chai, lon, giấy — mỗi loại một ngày trong tuần.',
    extra:'Thói quen dọn dẹp bắt đầu từ trường học: học sinh tự lau lớp, hành lang và nhà vệ sinh mỗi ngày, gọi là 掃除の時間.',
    word:{ t:'分別', r:'bunbetsu', vi:'phân loại rác' } },
  { lang:'ja', cat:'Ngôn ngữ', art:'onomat', title:'Có hơn một nghìn từ tượng thanh – tượng hình',
    body:'ドキドキ (tim đập), ペコペコ (đói bụng), しーん (im lặng tuyệt đối) — người Nhật dùng từ láy tượng thanh cả trong văn viết trang trọng lẫn báo chí.',
    extra:'Học các từ này giúp nghe hiểu truyện tranh, phim ảnh và hội thoại đời thường nhanh hơn nhiều so với học thêm từ Hán–Nhật.',
    word:{ t:'ドキドキ', r:'dokidoki', vi:'tim đập thình thịch' } },
  { lang:'ja', cat:'Ẩm thực', art:'bento', title:'Hộp cơm bento được sắp như một bức tranh',
    body:'Bento chú trọng bố cục và màu sắc: đỏ, vàng, xanh, trắng, đen — vừa đẹp mắt vừa cân bằng dinh dưỡng.',
    extra:'キャラ弁 (bento hình nhân vật) là cả một thú chơi công phu của các bà mẹ, với cơm nắm tạo hình và rong biển cắt tỉa.',
    word:{ t:'弁当', r:'bentō', vi:'cơm hộp' } },
  { lang:'ja', cat:'Văn hoá', art:'torii', title:'Cổng torii đánh dấu ranh giới giữa đời thường và cõi thiêng',
    body:'Bước qua torii là bước vào khuôn viên đền thần đạo. Người ta đi lệch sang bên, tránh chính giữa vì đó là lối của thần.',
    extra:'Ở Fushimi Inari (Kyoto) có hàng nghìn torii đỏ nối nhau, phần lớn do doanh nghiệp cúng tiến, mặt sau khắc tên người dâng.',
    word:{ t:'鳥居', r:'torii', vi:'cổng đền' } },
  { lang:'ja', cat:'Con người', art:'vending', title:'Cứ khoảng 30 người dân có một máy bán hàng tự động',
    body:'Nhật có hơn 4 triệu máy bán hàng tự động: nước nóng và lạnh, mì, kem, thậm chí hoa tươi — hoạt động cả đêm ở nơi rất vắng.',
    extra:'Điều đó phản ánh mức độ an toàn công cộng cao: máy đứng ngoài trời quanh năm mà hiếm khi bị phá.',
    word:{ t:'自動販売機', r:'jidōhanbaiki', vi:'máy bán hàng tự động' } }
];
if (typeof module !== 'undefined') module.exports = { FACTS };

/* ------------------------------------------------------------
   Hình minh hoạ: SVG phẳng tự vẽ, dùng biến màu của giao diện nên tự đổi theo
   ngôn ngữ và chế độ sáng/tối. Khung chung 120×84, nền bo tròn.
   ------------------------------------------------------------ */
const FACT_ART = {
  hangul:'<rect x="16" y="14" width="88" height="56" rx="10" fill="var(--surface)" stroke="var(--line-strong)"/><text x="60" y="52" text-anchor="middle" font-size="30" font-weight="700" fill="var(--accent)" font-family="Noto Sans KR, sans-serif">한글</text>',
  kimchi:'<path d="M30 34h60l-6 34a8 8 0 0 1-8 7H44a8 8 0 0 1-8-7z" fill="var(--accent)"/><path d="M30 34h60l-2 10H32z" fill="var(--accent-2)"/><path d="M44 24c4-8 12-10 16-4 3-6 12-5 14 4" fill="none" stroke="var(--seal)" stroke-width="3" stroke-linecap="round"/><circle cx="52" cy="52" r="4" fill="var(--surface)" opacity=".55"/><circle cx="70" cy="60" r="3" fill="var(--surface)" opacity=".45"/>',
  bow:'<circle cx="44" cy="30" r="9" fill="var(--accent)"/><path d="M30 68c0-11 6-19 14-19s14 8 14 19z" fill="var(--accent)"/><circle cx="82" cy="26" r="8" fill="var(--seal)"/><path d="M70 66c0-10 5-17 12-17s12 7 12 17z" fill="var(--seal)"/><path d="M58 46q6 6 12 0" fill="none" stroke="var(--line-strong)" stroke-width="2.5"/>',
  age:'<circle cx="60" cy="42" r="26" fill="none" stroke="var(--accent)" stroke-width="4"/><path d="M60 24v20l13 8" fill="none" stroke="var(--accent)" stroke-width="4" stroke-linecap="round"/><text x="98" y="30" text-anchor="middle" font-size="16" font-weight="700" fill="var(--seal)">1</text>',
  lantern:'<rect x="52" y="10" width="16" height="5" rx="2" fill="var(--line-strong)"/><ellipse cx="60" cy="42" rx="22" ry="26" fill="var(--accent)"/><path d="M38 42h44M60 16v52" stroke="var(--accent-2)" stroke-width="2" opacity=".6"/><rect x="54" y="66" width="12" height="4" fill="var(--line-strong)"/><path d="M58 70v8M62 70v8" stroke="var(--accent-2)" stroke-width="2"/>',
  letter:'<rect x="22" y="20" width="76" height="48" rx="6" fill="var(--surface)" stroke="var(--line-strong)"/><path d="M22 24l38 26 38-26" fill="none" stroke="var(--accent)" stroke-width="3"/><path d="M34 60h28" stroke="var(--seal)" stroke-width="3" stroke-linecap="round"/>',
  tiger:'<circle cx="60" cy="44" r="24" fill="var(--accent)"/><path d="M40 26l6 10M80 26l-6 10" stroke="var(--accent-2)" stroke-width="6" stroke-linecap="round"/><circle cx="51" cy="40" r="3.5" fill="var(--surface)"/><circle cx="69" cy="40" r="3.5" fill="var(--surface)"/><path d="M54 52q6 6 12 0" fill="none" stroke="var(--surface)" stroke-width="3" stroke-linecap="round"/><path d="M46 30v8M74 30v8" stroke="var(--ink)" stroke-width="2" opacity=".4"/>',
  ondol:'<rect x="20" y="46" width="80" height="24" rx="4" fill="var(--surface-2)" stroke="var(--line-strong)"/><path d="M30 44c0-8 8-8 8-16M50 44c0-8 8-8 8-16M70 44c0-8 8-8 8-16M90 44c0-6 4-8 4-12" fill="none" stroke="var(--accent)" stroke-width="3" stroke-linecap="round"/>',
  seaweed:'<ellipse cx="60" cy="52" rx="30" ry="14" fill="var(--surface)" stroke="var(--line-strong)"/><path d="M34 48q10-8 20 0t22-2" fill="none" stroke="var(--seal)" stroke-width="4" stroke-linecap="round"/><path d="M38 56q12-6 22 2t20-4" fill="none" stroke="var(--accent)" stroke-width="3.5" stroke-linecap="round"/><path d="M26 44c0-4 68-4 68 0" fill="none" stroke="var(--line-strong)" stroke-width="2"/>',
  ppalli:'<path d="M26 60l22-30 6 14 12-20 8 16 6-8 14 28z" fill="var(--accent)"/><path d="M92 18l-8 10h6l-8 12" fill="none" stroke="var(--seal)" stroke-width="3" stroke-linecap="round"/>',
  bowl:'<path d="M30 40h60c0 16-13 26-30 26S30 56 30 40z" fill="var(--surface)" stroke="var(--line-strong)"/><ellipse cx="60" cy="40" rx="30" ry="6" fill="var(--accent-soft)" stroke="var(--line-strong)"/><path d="M70 20l16 6M74 14l14 8" stroke="var(--accent)" stroke-width="3" stroke-linecap="round"/>',
  hanzi:'<rect x="20" y="12" width="80" height="60" rx="8" fill="var(--surface)" stroke="var(--line-strong)"/><path d="M20 42h80M60 12v60" stroke="var(--line)" stroke-width="1.5" stroke-dasharray="4 4"/><text x="60" y="54" text-anchor="middle" font-size="34" font-weight="700" fill="var(--accent)">字</text>',
  tone:'<path d="M20 40h20" stroke="var(--accent)" stroke-width="4" stroke-linecap="round"/><path d="M46 52l14-16" stroke="var(--accent)" stroke-width="4" stroke-linecap="round"/><path d="M66 36q6 16 14 0" fill="none" stroke="var(--accent)" stroke-width="4" stroke-linecap="round"/><path d="M86 30l14 20" stroke="var(--accent)" stroke-width="4" stroke-linecap="round"/><text x="60" y="72" text-anchor="middle" font-size="13" fill="var(--muted)">mā má mǎ mà</text>',
  redenvelope:'<rect x="34" y="14" width="52" height="60" rx="6" fill="var(--accent)"/><path d="M34 14l26 20 26-20" fill="none" stroke="var(--accent-2)" stroke-width="3"/><circle cx="60" cy="46" r="11" fill="var(--surface)" opacity=".9"/><text x="60" y="51" text-anchor="middle" font-size="13" font-weight="700" fill="var(--accent)">福</text>',
  panda:'<circle cx="60" cy="44" r="23" fill="var(--surface)" stroke="var(--line-strong)"/><circle cx="41" cy="26" r="9" fill="var(--ink)"/><circle cx="79" cy="26" r="9" fill="var(--ink)"/><ellipse cx="50" cy="42" rx="7" ry="9" fill="var(--ink)"/><ellipse cx="70" cy="42" rx="7" ry="9" fill="var(--ink)"/><circle cx="50" cy="42" r="2.5" fill="var(--surface)"/><circle cx="70" cy="42" r="2.5" fill="var(--surface)"/><ellipse cx="60" cy="55" rx="4" ry="3" fill="var(--ink)"/>',
  dumpling:'<path d="M28 56c0-16 14-26 32-26s32 10 32 26z" fill="var(--surface)" stroke="var(--line-strong)"/><path d="M28 56h64" stroke="var(--line-strong)" stroke-width="2"/><path d="M36 42q6-8 12 0M52 38q6-8 12 0M68 40q6-8 12 0" fill="none" stroke="var(--accent)" stroke-width="3" stroke-linecap="round"/>',
  number:'<text x="42" y="58" text-anchor="middle" font-size="40" font-weight="700" fill="var(--accent)">八</text><text x="84" y="52" text-anchor="middle" font-size="26" font-weight="700" fill="var(--faint)">四</text><path d="M70 26l28 28M98 26L70 54" stroke="var(--faint)" stroke-width="3" opacity=".55"/>',
  tea:'<path d="M32 34h44v18c0 10-10 16-22 16s-22-6-22-16z" fill="var(--surface)" stroke="var(--line-strong)"/><path d="M76 40h8a7 7 0 0 1 0 14h-8" fill="none" stroke="var(--line-strong)" stroke-width="3"/><path d="M44 26c0-6 4-6 4-10M56 26c0-6 4-6 4-10M68 26c0-6 4-6 4-10" fill="none" stroke="var(--accent)" stroke-width="2.5" stroke-linecap="round"/><ellipse cx="54" cy="40" rx="20" ry="5" fill="var(--accent-soft)"/>',
  square:'<circle cx="40" cy="28" r="7" fill="var(--accent)"/><path d="M28 66c0-12 6-20 12-20s12 8 12 20z" fill="var(--accent)"/><circle cx="76" cy="28" r="7" fill="var(--seal)"/><path d="M64 66c0-12 6-20 12-20s12 8 12 20z" fill="var(--seal)"/><path d="M20 72h80" stroke="var(--line-strong)" stroke-width="3" stroke-linecap="round"/><path d="M96 20c4 4 4 10 0 14" fill="none" stroke="var(--accent-2)" stroke-width="2.5"/>',
  pinyin:'<rect x="20" y="24" width="80" height="36" rx="8" fill="var(--surface)" stroke="var(--line-strong)"/><text x="60" y="50" text-anchor="middle" font-size="22" font-weight="600" fill="var(--accent)">pīn yīn</text><path d="M30 66h60" stroke="var(--seal)" stroke-width="3" stroke-linecap="round"/>',
  greatwall:'<path d="M14 66l18-14 18 8 18-16 18 10 20-12v24z" fill="var(--accent)" opacity=".85"/><path d="M30 52v-8h6v6M66 44v-8h6v6M100 42v-8h6v6" fill="var(--accent-2)"/><path d="M14 66h92" stroke="var(--line-strong)" stroke-width="2"/>',
  hotpot:'<path d="M28 40h64c0 16-14 26-32 26S28 56 28 40z" fill="var(--accent)"/><ellipse cx="60" cy="40" rx="32" ry="7" fill="var(--accent-2)"/><path d="M60 33v14" stroke="var(--surface)" stroke-width="3"/><path d="M46 22c0-6 5-6 5-11M60 20c0-6 5-6 5-11M74 22c0-6 5-6 5-11" fill="none" stroke="var(--seal)" stroke-width="2.5" stroke-linecap="round"/>',
  phone:'<rect x="44" y="10" width="32" height="62" rx="6" fill="var(--surface)" stroke="var(--line-strong)" stroke-width="2"/><rect x="50" y="20" width="20" height="20" fill="var(--accent)"/><rect x="54" y="24" width="5" height="5" fill="var(--surface)"/><rect x="61" y="31" width="5" height="5" fill="var(--surface)"/><path d="M50 50h20M50 58h12" stroke="var(--line-strong)" stroke-width="3" stroke-linecap="round"/>',
  cyrillic:'<rect x="16" y="16" width="88" height="52" rx="10" fill="var(--surface)" stroke="var(--line-strong)"/><text x="60" y="52" text-anchor="middle" font-size="26" font-weight="700" fill="var(--accent)">Аа Бб Вв</text>',
  shoes:'<path d="M22 56h26c8 0 8 8 18 8H30a8 8 0 0 1-8-8z" fill="var(--accent)"/><path d="M22 56c0-10 4-14 10-14 4 0 4 6 10 6" fill="none" stroke="var(--accent-2)" stroke-width="3"/><path d="M62 56h26c8 0 8 8 18 8H70a8 8 0 0 1-8-8z" fill="var(--seal)"/><path d="M62 56c0-10 4-14 10-14 4 0 4 6 10 6" fill="none" stroke="var(--seal)" stroke-width="3" opacity=".6"/>',
  matryoshka:'<path d="M60 12c12 0 18 10 18 20 6 6 8 14 8 22 0 10-12 16-26 16s-26-6-26-16c0-8 2-16 8-22 0-10 6-20 18-20z" fill="var(--accent)"/><path d="M60 20c7 0 11 6 11 13 0 6-5 9-11 9s-11-3-11-9c0-7 4-13 11-13z" fill="var(--surface)"/><circle cx="55" cy="32" r="2" fill="var(--ink)"/><circle cx="65" cy="32" r="2" fill="var(--ink)"/><path d="M55 38q5 4 10 0" fill="none" stroke="var(--accent-2)" stroke-width="2"/><circle cx="60" cy="58" r="8" fill="var(--surface)" opacity=".85"/>',
  samovar:'<path d="M44 26h32l6 26c0 10-8 16-22 16s-22-6-22-16z" fill="var(--accent)"/><rect x="52" y="14" width="16" height="12" rx="3" fill="var(--accent-2)"/><path d="M82 40h6a6 6 0 0 1 0 12h-6" fill="none" stroke="var(--accent-2)" stroke-width="3"/><rect x="56" y="68" width="8" height="6" fill="var(--line-strong)"/><path d="M38 46h-6" stroke="var(--accent-2)" stroke-width="4" stroke-linecap="round"/>',
  smile:'<circle cx="60" cy="42" r="26" fill="var(--surface)" stroke="var(--line-strong)" stroke-width="2"/><circle cx="50" cy="36" r="3" fill="var(--ink)"/><circle cx="70" cy="36" r="3" fill="var(--ink)"/><path d="M46 52h28" stroke="var(--accent)" stroke-width="3.5" stroke-linecap="round"/>',
  blin:'<ellipse cx="60" cy="50" rx="34" ry="12" fill="var(--accent)"/><ellipse cx="60" cy="44" rx="34" ry="12" fill="var(--accent-2)"/><ellipse cx="60" cy="38" rx="34" ry="12" fill="var(--accent)"/><ellipse cx="60" cy="34" rx="12" ry="5" fill="var(--seal)"/><path d="M26 50c0 6 15 12 34 12s34-6 34-12" fill="none" stroke="var(--line-strong)" stroke-width="2"/>',
  metro:'<rect x="26" y="18" width="68" height="40" rx="10" fill="var(--accent)"/><rect x="34" y="26" width="22" height="16" rx="3" fill="var(--surface)"/><rect x="64" y="26" width="22" height="16" rx="3" fill="var(--surface)"/><circle cx="40" cy="62" r="6" fill="var(--ink)"/><circle cx="80" cy="62" r="6" fill="var(--ink)"/><path d="M26 70h68" stroke="var(--line-strong)" stroke-width="3"/>',
  stress:'<text x="60" y="52" text-anchor="middle" font-size="30" font-weight="700" fill="var(--accent)">замо́к</text><path d="M64 22l6-10 6 10" fill="none" stroke="var(--seal)" stroke-width="3" stroke-linecap="round"/>',
  bear:'<circle cx="42" cy="26" r="8" fill="var(--accent-2)"/><circle cx="78" cy="26" r="8" fill="var(--accent-2)"/><circle cx="60" cy="46" r="24" fill="var(--accent)"/><ellipse cx="60" cy="54" rx="11" ry="8" fill="var(--surface)"/><circle cx="52" cy="40" r="3" fill="var(--ink)"/><circle cx="68" cy="40" r="3" fill="var(--ink)"/><ellipse cx="60" cy="50" rx="4" ry="3" fill="var(--ink)"/>',
  banya:'<rect x="28" y="40" width="64" height="28" rx="6" fill="var(--surface-2)" stroke="var(--line-strong)"/><path d="M24 40l36-22 36 22z" fill="var(--accent)"/><path d="M46 34c0-6 5-6 5-12M60 32c0-6 5-6 5-12M74 34c0-6 5-6 5-12" fill="none" stroke="var(--seal)" stroke-width="2.5" stroke-linecap="round" opacity=".8"/><rect x="54" y="52" width="12" height="16" fill="var(--accent-2)"/>',
  newyear:'<path d="M60 14l6 14h14l-11 9 4 14-13-8-13 8 4-14-11-9h14z" fill="var(--seal)"/><path d="M40 70l20-24 20 24z" fill="var(--accent)"/><rect x="55" y="70" width="10" height="6" fill="var(--line-strong)"/>',
  train:'<rect x="18" y="30" width="84" height="26" rx="6" fill="var(--accent)"/><rect x="26" y="36" width="18" height="12" rx="2" fill="var(--surface)"/><rect x="50" y="36" width="18" height="12" rx="2" fill="var(--surface)"/><rect x="74" y="36" width="18" height="12" rx="2" fill="var(--surface)"/><circle cx="34" cy="62" r="6" fill="var(--ink)"/><circle cx="86" cy="62" r="6" fill="var(--ink)"/><path d="M12 68h96" stroke="var(--line-strong)" stroke-width="3"/>',
  sansho:'<rect x="16" y="20" width="88" height="44" rx="10" fill="var(--surface)" stroke="var(--line-strong)"/><text x="60" y="50" text-anchor="middle" font-size="24" font-weight="700" fill="var(--accent)" font-family="Noto Sans JP, sans-serif">あ ア 亜</text>',
  sushi:'<ellipse cx="60" cy="54" rx="30" ry="12" fill="var(--surface)" stroke="var(--line-strong)"/><path d="M32 46c0-8 12-14 28-14s28 6 28 14z" fill="var(--accent)"/><rect x="52" y="34" width="16" height="26" rx="3" fill="var(--seal)"/><path d="M36 50q10-6 20 0" fill="none" stroke="var(--surface)" stroke-width="2" opacity=".7"/>',
  bowjp:'<circle cx="46" cy="24" r="8" fill="var(--accent)"/><path d="M32 62c2-12 8-18 14-18s12 6 14 18z" fill="var(--accent)"/><path d="M60 62l14-4" stroke="var(--line-strong)" stroke-width="3"/><circle cx="86" cy="30" r="7" fill="var(--seal)"/><path d="M74 64c0-10 5-16 12-16s12 6 12 16z" fill="var(--seal)"/><path d="M24 68h72" stroke="var(--line)" stroke-width="2"/>',
  sakura:'<g fill="var(--accent)"><ellipse cx="60" cy="26" rx="7" ry="11"/><ellipse cx="76" cy="38" rx="7" ry="11" transform="rotate(72 76 38)"/><ellipse cx="70" cy="58" rx="7" ry="11" transform="rotate(144 70 58)"/><ellipse cx="50" cy="58" rx="7" ry="11" transform="rotate(216 50 58)"/><ellipse cx="44" cy="38" rx="7" ry="11" transform="rotate(288 44 38)"/></g><circle cx="60" cy="43" r="6" fill="var(--accent-2)"/><circle cx="24" cy="20" r="4" fill="var(--accent)" opacity=".6"/><circle cx="98" cy="62" r="5" fill="var(--accent)" opacity=".5"/>',
  train_jp:'<path d="M24 24h72v34H24z" fill="var(--accent)"/><path d="M24 24c0-8 16-12 36-12s36 4 36 12" fill="var(--accent-2)"/><rect x="32" y="32" width="22" height="14" rx="3" fill="var(--surface)"/><rect x="66" y="32" width="22" height="14" rx="3" fill="var(--surface)"/><path d="M18 64h84" stroke="var(--line-strong)" stroke-width="3"/><path d="M96 20l14 8-14 8" fill="none" stroke="var(--seal)" stroke-width="3" stroke-linejoin="round"/>',
  onsen:'<path d="M26 44h68v10c0 10-8 16-24 16H50c-16 0-24-6-24-16z" fill="var(--seal-soft)" stroke="var(--line-strong)"/><path d="M30 54q8-6 16 0t16 0 16 0 12 0" fill="none" stroke="var(--seal)" stroke-width="3"/><path d="M44 34c0-8 6-8 6-16M60 32c0-8 6-8 6-16M76 34c0-8 6-8 6-16" fill="none" stroke="var(--accent)" stroke-width="3" stroke-linecap="round"/>',
  maneki:'<circle cx="60" cy="46" r="24" fill="var(--surface)" stroke="var(--line-strong)"/><path d="M40 28l4-14 12 8zM80 28l-4-14-12 8z" fill="var(--surface)" stroke="var(--line-strong)"/><circle cx="52" cy="44" r="3" fill="var(--ink)"/><circle cx="68" cy="44" r="3" fill="var(--ink)"/><path d="M54 54q6 5 12 0" fill="none" stroke="var(--ink)" stroke-width="2"/><path d="M36 42c-6-4-6-14 2-16" fill="none" stroke="var(--accent)" stroke-width="5" stroke-linecap="round"/><rect x="50" y="60" width="20" height="10" rx="3" fill="var(--accent)"/>',
  trash:'<rect x="30" y="30" width="26" height="38" rx="4" fill="var(--accent)"/><rect x="64" y="30" width="26" height="38" rx="4" fill="var(--seal)"/><rect x="26" y="24" width="34" height="8" rx="3" fill="var(--accent-2)"/><rect x="60" y="24" width="34" height="8" rx="3" fill="var(--seal)" opacity=".7"/><path d="M43 40v18M77 40v18" stroke="var(--surface)" stroke-width="3" opacity=".7"/>',
  onomat:'<path d="M22 20h56a8 8 0 0 1 8 8v20a8 8 0 0 1-8 8H44l-14 12V56h-8a8 8 0 0 1-8-8V28a8 8 0 0 1 8-8z" fill="var(--accent)"/><text x="52" y="44" text-anchor="middle" font-size="16" font-weight="700" fill="var(--surface)" font-family="Noto Sans JP, sans-serif">ドキドキ</text><circle cx="98" cy="30" r="6" fill="var(--seal)" opacity=".7"/>',
  bento:'<rect x="22" y="24" width="76" height="44" rx="6" fill="var(--surface)" stroke="var(--line-strong)" stroke-width="2"/><rect x="28" y="30" width="30" height="32" rx="3" fill="var(--accent-soft)"/><circle cx="43" cy="46" r="8" fill="var(--accent)"/><rect x="62" y="30" width="30" height="14" rx="3" fill="var(--seal-soft)"/><rect x="62" y="48" width="30" height="14" rx="3" fill="var(--accent-soft)"/><path d="M66 55h22" stroke="var(--accent-2)" stroke-width="3" stroke-linecap="round"/>',
  torii:'<path d="M18 26h84l-4 8H22z" fill="var(--accent)"/><rect x="26" y="38" width="68" height="6" fill="var(--accent)"/><rect x="34" y="34" width="9" height="38" fill="var(--accent)"/><rect x="77" y="34" width="9" height="38" fill="var(--accent)"/><rect x="56" y="38" width="8" height="10" fill="var(--accent-2)"/>',
  vending:'<rect x="34" y="12" width="52" height="60" rx="6" fill="var(--accent)"/><rect x="40" y="18" width="24" height="34" rx="3" fill="var(--surface)"/><circle cx="46" cy="26" r="4" fill="var(--accent-2)"/><circle cx="58" cy="26" r="4" fill="var(--seal)"/><circle cx="46" cy="38" r="4" fill="var(--seal)"/><circle cx="58" cy="38" r="4" fill="var(--accent-2)"/><rect x="70" y="18" width="12" height="20" rx="2" fill="var(--surface)" opacity=".8"/><rect x="40" y="58" width="42" height="8" rx="2" fill="var(--surface)" opacity=".85"/>'
};
if (typeof module !== 'undefined') module.exports.FACT_ART = FACT_ART;
