/* ============================================================
   LangLab — Ngữ âm tiếng Anh (IPA)
   44 âm vị chuẩn RP (Anh) kèm đối chiếu GA (Mỹ), quy tắc trọng âm,
   quy tắc chính tả → âm, và các hiện tượng nối âm trong lời nói tự nhiên.
   Biên soạn cho người Việt: mỗi âm có mô tả khẩu hình, lỗi thường gặp
   của người Việt, cặp từ tối thiểu để tự kiểm tra.
   ============================================================ */

const PHON_EN = {

  /* ---------- 12 nguyên âm đơn ---------- */
  vowels: [
    { s:'iː', type:'Nguyên âm dài', name:'i dài', us:'i',
      vi:'Lưỡi đưa cao và ra trước, môi kéo dẹt sang hai bên như đang cười. Giữ âm dài hơn hẳn /ɪ/.',
      spell:['ee — see, tree','ea — eat, sea','e_e — these','ie/ei — piece, receive','y cuối từ nhiều âm tiết — happy, city'],
      eg:[['see','siː','nhìn thấy'],['eat','iːt','ăn'],['machine','məˈʃiːn','máy'],['believe','bɪˈliːv','tin']],
      pair:[['sheep','ʃiːp','ship','ʃɪp','cừu / con tàu'],['feel','fiːl','fill','fɪl','cảm thấy / lấp đầy'],['seat','siːt','sit','sɪt','chỗ ngồi / ngồi']],
      tip:'Người Việt hay đọc /iː/ và /ɪ/ giống nhau. Hãy nhớ: /iː/ căng, dài, môi dẹt; /ɪ/ ngắn, lỏng, hàm thả.' },

    { s:'ɪ', type:'Nguyên âm ngắn', name:'i ngắn', us:'ɪ',
      vi:'Lưỡi cao vừa, cơ hàm và môi thả lỏng. Âm rất ngắn, gần giữa «i» và «ê» tiếng Việt.',
      spell:['i — sit, big','y — gym, myth','e ở tiền tố — begin, decide','a/e ở âm tiết không nhấn — village, wanted'],
      eg:[['sit','sɪt','ngồi'],['big','bɪɡ','to'],['women','ˈwɪmɪn','phụ nữ (số nhiều)'],['minute','ˈmɪnɪt','phút']],
      pair:[['bit','bɪt','beat','biːt','miếng nhỏ / đánh bại'],['live','lɪv','leave','liːv','sống / rời đi']],
      tip:'Đừng kéo dài. Nếu bạn thấy môi mình đang cười thì có lẽ bạn đang đọc thành /iː/.' },

    { s:'e', type:'Nguyên âm ngắn', name:'e', us:'ɛ',
      vi:'Miệng mở vừa, lưỡi ở giữa và hơi trước. Rất gần âm «e» trong tiếng Việt.',
      spell:['e — bed, ten','ea — head, bread','a — many, any','ai — said'],
      eg:[['bed','bed','giường'],['head','hed','đầu'],['friend','frend','bạn'],['says','sez','nói (ngôi 3)']],
      pair:[['bed','bed','bad','bæd','giường / tệ'],['men','men','man','mæn','những người đàn ông / một người đàn ông']],
      tip:'Khác biệt lớn nhất là với /æ/: /e/ hàm mở ít, /æ/ hàm mở rộng hơn nhiều.' },

    { s:'æ', type:'Nguyên âm ngắn', name:'a bẹt', us:'æ',
      vi:'Mở hàm rộng, lưỡi thấp và ra trước, môi kéo ngang. Nằm giữa «e» và «a» của tiếng Việt.',
      spell:['a trong âm tiết đóng — cat, map, black'],
      eg:[['cat','kæt','con mèo'],['map','mæp','bản đồ'],['happy','ˈhæpi','vui'],['travel','ˈtrævl','đi lại']],
      pair:[['cat','kæt','cut','kʌt','con mèo / cắt'],['bad','bæd','bed','bed','tệ / giường'],['man','mæn','men','men','đàn ông / những người đàn ông']],
      tip:'Người Việt thường đọc thành «e» hoặc «a». Mẹo: hạ hàm như sắp cắn quả táo rồi mới phát âm.' },

    { s:'ɑː', type:'Nguyên âm dài', name:'a dài sau', us:'ɑ',
      vi:'Miệng mở to, lưỡi lùi về sau và hạ thấp, âm vang sâu trong họng, kéo dài.',
      spell:['ar — car, start','a trước s/f/th (Anh) — fast, path, laugh','al — calm, palm'],
      eg:[['car','kɑː','xe hơi'],['father','ˈfɑːðə','bố'],['start','stɑːt','bắt đầu'],['heart','hɑːt','trái tim']],
      pair:[['cart','kɑːt','cut','kʌt','xe kéo / cắt'],['hard','hɑːd','head','hed','cứng / đầu']],
      tip:'Giọng Anh không đọc chữ «r» trong car; giọng Mỹ thì có: /kɑːr/. Chọn một giọng và giữ nhất quán.' },

    { s:'ɒ', type:'Nguyên âm ngắn', name:'o mở ngắn', us:'ɑː',
      vi:'Môi tròn nhẹ, lưỡi lùi sau và hạ thấp, âm ngắn. Giọng Mỹ thường thay bằng /ɑː/.',
      spell:['o — hot, box, stop','a sau w/qu — want, watch, quality'],
      eg:[['hot','hɒt','nóng'],['stop','stɒp','dừng'],['watch','wɒtʃ','xem, đồng hồ'],['because','bɪˈkɒz','bởi vì']],
      pair:[['cot','kɒt','caught','kɔːt','giường cũi / bắt (quá khứ)'],['not','nɒt','nut','nʌt','không / hạt']],
      tip:'Ngắn và tròn môi. Nếu kéo dài, nó thành /ɔː/ (bought).' },

    { s:'ɔː', type:'Nguyên âm dài', name:'o dài', us:'ɔ',
      vi:'Môi tròn rõ và đưa ra trước, lưỡi lùi sau ở tầm giữa, giữ dài.',
      spell:['or — sport, born','aw/au — saw, autumn','al — talk, walk','ough/augh — bought, caught','oor/our — door, four'],
      eg:[['four','fɔː','bốn'],['talk','tɔːk','nói chuyện'],['thought','θɔːt','ý nghĩ'],['already','ɔːlˈredi','đã rồi']],
      pair:[['port','pɔːt','pot','pɒt','cảng / cái nồi'],['walk','wɔːk','work','wɜːk','đi bộ / làm việc']],
      tip:'walk /wɔːk/ và work /wɜːk/ là cặp gây nhầm kinh điển: một bên tròn môi, một bên môi trung hoà.' },

    { s:'ʊ', type:'Nguyên âm ngắn', name:'u ngắn', us:'ʊ',
      vi:'Môi tròn lỏng, lưỡi cao vừa và lùi sau. Rất ngắn, cơ miệng không căng.',
      spell:['oo (ngắn) — book, good, look','u — put, full, push','ou — could, would, should'],
      eg:[['book','bʊk','sách'],['good','ɡʊd','tốt'],['put','pʊt','đặt'],['woman','ˈwʊmən','phụ nữ']],
      pair:[['full','fʊl','fool','fuːl','đầy / kẻ ngốc'],['pull','pʊl','pool','puːl','kéo / hồ bơi']],
      tip:'Không đẩy môi ra trước. Nếu môi chu lại như thổi nến thì bạn đang đọc /uː/.' },

    { s:'uː', type:'Nguyên âm dài', name:'u dài', us:'u',
      vi:'Môi tròn và chu ra trước, lưỡi đưa cao và lùi sau, giữ âm dài.',
      spell:['oo — food, moon','u_e — rule, June','ew/ue — new, blue','ou — group, soup'],
      eg:[['food','fuːd','thức ăn'],['blue','bluː','màu xanh'],['June','dʒuːn','tháng Sáu'],['through','θruː','xuyên qua']],
      pair:[['fool','fuːl','full','fʊl','kẻ ngốc / đầy'],['suit','suːt','soot','sʊt','bộ vest / bồ hóng']],
      tip:'Sau /j/ thường thành /juː/: music /ˈmjuːzɪk/, new (Anh) /njuː/ nhưng Mỹ /nuː/.' },

    { s:'ʌ', type:'Nguyên âm ngắn', name:'â ngắn', us:'ʌ',
      vi:'Miệng mở vừa, lưỡi ở giữa và hơi lùi, môi hoàn toàn không tròn. Gần «â» của tiếng Việt nhưng ngắn hơn.',
      spell:['u — cup, sun, but','o — come, love, money','ou — country, young','oo — blood, flood'],
      eg:[['cup','kʌp','cái cốc'],['love','lʌv','yêu'],['money','ˈmʌni','tiền'],['enough','ɪˈnʌf','đủ']],
      pair:[['cup','kʌp','cap','kæp','cốc / mũ lưỡi trai'],['luck','lʌk','lock','lɒk','may mắn / khoá']],
      tip:'/ʌ/ luôn nằm ở âm tiết CÓ trọng âm; âm giống nó ở âm tiết không trọng âm là /ə/.' },

    { s:'ɜː', type:'Nguyên âm dài', name:'ơ dài', us:'ɜr',
      vi:'Lưỡi ở chính giữa khoang miệng, môi trung hoà, kéo dài. Giọng Mỹ cuộn lưỡi thành /ɝ/.',
      spell:['er — her, term','ir — girl, first','ur — turn, nurse','ear — learn, earth','wor — word, work'],
      eg:[['work','wɜːk','làm việc'],['girl','ɡɜːl','cô gái'],['learn','lɜːn','học'],['nurse','nɜːs','y tá']],
      pair:[['work','wɜːk','walk','wɔːk','làm việc / đi bộ'],['bird','bɜːd','bed','bed','con chim / giường']],
      tip:'Đây là nguyên âm dài duy nhất ở vị trí trung tâm — không tròn môi, không kéo môi.' },

    { s:'ə', type:'Nguyên âm yếu', name:'schwa', us:'ə',
      vi:'Âm mờ, ngắn nhất và phổ biến nhất trong tiếng Anh. Cơ miệng thả lỏng hoàn toàn, hầu như không tạo hình.',
      spell:['a — about, sofa','e — taken, problem','o — today, police','u — support','er — teacher, water'],
      eg:[['about','əˈbaʊt','về, khoảng'],['teacher','ˈtiːtʃə','giáo viên'],['banana','bəˈnɑːnə','quả chuối'],['computer','kəmˈpjuːtə','máy tính']],
      pair:[['ˈdesert','ˈdezət','deˈssert','dɪˈzɜːt','sa mạc / món tráng miệng']],
      tip:'Chìa khoá của nhịp điệu tiếng Anh: mọi âm tiết KHÔNG trọng âm đều có xu hướng rút về /ə/. Nói rõ từng âm tiết sẽ nghe rất «Việt».' }
  ],

  /* ---------- 8 nguyên âm đôi ---------- */
  diphthongs: [
    { s:'eɪ', type:'Nguyên âm đôi', name:'ây', us:'eɪ',
      vi:'Bắt đầu ở /e/ rồi trượt lên /ɪ/. Phần đầu dài, phần sau nhẹ.',
      spell:['a_e — make, name','ai — rain, wait','ay — day, play','ei/ey — eight, they'],
      eg:[['make','meɪk','làm'],['day','deɪ','ngày'],['eight','eɪt','số tám'],['break','breɪk','làm vỡ, nghỉ']],
      pair:[['late','leɪt','let','let','muộn / cho phép'],['pain','peɪn','pen','pen','đau / cái bút']],
      tip:'Đừng dừng ở /e/. Phải nghe rõ đuôi trượt lên trên.' },

    { s:'aɪ', type:'Nguyên âm đôi', name:'ai', us:'aɪ',
      vi:'Bắt đầu miệng mở rộng ở /a/, trượt nhanh lên /ɪ/.',
      spell:['i_e — time, nice','igh — light, night','y — my, try','ie — die, tie'],
      eg:[['time','taɪm','thời gian'],['night','naɪt','đêm'],['buy','baɪ','mua'],['height','haɪt','chiều cao']],
      pair:[['light','laɪt','let','let','ánh sáng / cho phép'],['bite','baɪt','bit','bɪt','cắn / miếng nhỏ']],
      tip:'Rất giống «ai» tiếng Việt — đây là một trong các âm dễ nhất với người Việt.' },

    { s:'ɔɪ', type:'Nguyên âm đôi', name:'oi', us:'ɔɪ',
      vi:'Bắt đầu tròn môi ở /ɔː/ rồi trượt lên /ɪ/, môi từ tròn sang dẹt.',
      spell:['oi — coin, voice','oy — boy, enjoy'],
      eg:[['boy','bɔɪ','cậu bé'],['voice','vɔɪs','giọng nói'],['choice','tʃɔɪs','lựa chọn'],['enjoy','ɪnˈdʒɔɪ','tận hưởng']],
      pair:[['boil','bɔɪl','bile','baɪl','đun sôi / mật']],
      tip:'Phải thấy môi thay đổi hình rõ ràng từ tròn sang dẹt.' },

    { s:'əʊ', type:'Nguyên âm đôi', name:'ơu (Anh)', us:'oʊ',
      vi:'Giọng Anh bắt đầu ở /ə/ trung tâm rồi trượt lên /ʊ/. Giọng Mỹ bắt đầu tròn hơn: /oʊ/.',
      spell:['o_e — home, note','oa — boat, road','ow — snow, know','o cuối từ — go, no'],
      eg:[['home','həʊm','nhà'],['go','ɡəʊ','đi'],['know','nəʊ','biết'],['although','ɔːlˈðəʊ','mặc dù']],
      pair:[['coat','kəʊt','caught','kɔːt','áo khoác / bắt'],['so','səʊ','saw','sɔː','vậy / đã thấy']],
      tip:'Không đọc thành «ô» đơn của tiếng Việt — phải có đuôi trượt về phía /ʊ/.' },

    { s:'aʊ', type:'Nguyên âm đôi', name:'ao', us:'aʊ',
      vi:'Bắt đầu miệng mở rộng ở /a/, trượt về /ʊ/, môi khép tròn dần.',
      spell:['ou — house, sound','ow — now, town, brown'],
      eg:[['house','haʊs','ngôi nhà'],['now','naʊ','bây giờ'],['about','əˈbaʊt','về'],['crowd','kraʊd','đám đông']],
      pair:[['loud','laʊd','load','ləʊd','ồn / tải'],['found','faʊnd','fond','fɒnd','tìm thấy / quý mến']],
      tip:'ow có hai cách đọc: now /naʊ/ nhưng know /nəʊ/ — phải học theo từ.' },

    { s:'ɪə', type:'Nguyên âm đôi', name:'ia (Anh)', us:'ɪr',
      vi:'Bắt đầu ở /ɪ/, trượt về /ə/. Giọng Mỹ đọc thành /ɪr/ có cuộn lưỡi.',
      spell:['ear — hear, near','eer — beer, deer','ere — here','ia — idea'],
      eg:[['here','hɪə','ở đây'],['year','jɪə','năm'],['idea',"aɪˈdɪə",'ý tưởng'],['serious','ˈsɪəriəs','nghiêm túc']],
      pair:[['here','hɪə','hair','heə','ở đây / tóc'],['beer','bɪə','bear','beə','bia / con gấu']],
      tip:'Đây là một trong ba nguyên âm đôi «hướng tâm» kết thúc bằng /ə/.' },

    { s:'eə', type:'Nguyên âm đôi', name:'ea (Anh)', us:'er',
      vi:'Bắt đầu ở /e/, trượt về /ə/. Giọng Mỹ đọc thành /er/.',
      spell:['air — hair, fair','are — care, share','ear — bear, wear','ere — there, where'],
      eg:[['hair','heə','tóc'],['care','keə','quan tâm'],['where','weə','ở đâu'],['compare','kəmˈpeə','so sánh']],
      pair:[['hair','heə','here','hɪə','tóc / ở đây'],['fair','feə','fear','fɪə','công bằng / sợ']],
      tip:'wear /weə/ nhưng ear /ɪə/ — cùng chữ «ear» nhưng khác âm hoàn toàn.' },

    { s:'ʊə', type:'Nguyên âm đôi', name:'ua (Anh)', us:'ʊr',
      vi:'Bắt đầu ở /ʊ/, trượt về /ə/. Âm này đang mai một, nhiều người Anh trẻ đọc thành /ɔː/.',
      spell:['ure — sure, cure','our — tour','oor — poor (một số người)'],
      eg:[['tour','tʊə','chuyến du lịch'],['sure','ʃʊə','chắc chắn'],['pure','pjʊə','tinh khiết'],['during','ˈdjʊərɪŋ','trong suốt']],
      pair:[['poor','pʊə','pour','pɔː','nghèo / rót']],
      tip:'Nếu bạn nghe sure thành /ʃɔː/, đó là biến thể hiện đại — cả hai đều được chấp nhận.' }
  ],

  /* ---------- 24 phụ âm ---------- */
  consonants: [
    { s:'p', type:'Tắc, vô thanh', name:'p bật hơi', vi:'Hai môi ngậm rồi bật ra. Ở đầu từ có trọng âm phải bật một luồng hơi mạnh.',
      spell:['p — pen, happy','pp — apple'],
      eg:[['pen','pen','cái bút'],['happy','ˈhæpi','vui'],['stop','stɒp','dừng']],
      pair:[['pin','pɪn','bin','bɪn','ghim / thùng rác'],['cap','kæp','cab','kæb','mũ / taxi']],
      tip:'Người Việt hay quên bật hơi. Cầm tờ giấy trước miệng: đọc «pen» đúng thì tờ giấy phải rung.' },
    { s:'b', type:'Tắc, hữu thanh', name:'b', vi:'Giống /p/ nhưng dây thanh rung và không bật hơi.',
      spell:['b — book','bb — rubber'],
      eg:[['book','bʊk','sách'],['about','əˈbaʊt','về'],['job','dʒɒb','công việc']],
      pair:[['bad','bæd','pad','pæd','tệ / miếng đệm']], tip:'Đặt tay lên cổ họng: đọc /b/ phải thấy rung, /p/ thì không.' },
    { s:'t', type:'Tắc, vô thanh', name:'t bật hơi', vi:'Đầu lưỡi chạm lợi trên rồi bật ra kèm hơi.',
      spell:['t — ten','tt — better','ed sau âm vô thanh — worked /wɜːkt/'],
      eg:[['ten','ten','mười'],['water','ˈwɔːtə','nước'],['worked','wɜːkt','đã làm']],
      pair:[['ten','ten','den','den','mười / hang']],
      tip:'Giọng Mỹ biến /t/ giữa hai nguyên âm thành âm vỗ giống /d/: water nghe như «wader».' },
    { s:'d', type:'Tắc, hữu thanh', name:'d', vi:'Giống /t/ nhưng có rung dây thanh, không bật hơi.',
      spell:['d — do','dd — ladder','ed sau âm hữu thanh — played /pleɪd/'],
      eg:[['do','duː','làm'],['played','pleɪd','đã chơi'],['red','red','màu đỏ']],
      pair:[['do','duː','to','tuː','làm / đến']], tip:'/d/ tiếng Anh là âm lợi, khác «đ» tiếng Việt vốn bật mạnh hơn.' },
    { s:'k', type:'Tắc, vô thanh', name:'k bật hơi', vi:'Mặt lưỡi sau chạm ngạc mềm rồi bật ra kèm hơi.',
      spell:['c trước a/o/u — cat, cup','k — key','ck — back','ch — school, character','qu — /kw/ quick'],
      eg:[['cat','kæt','mèo'],['school','skuːl','trường'],['quick','kwɪk','nhanh']],
      pair:[['coat','kəʊt','goat','ɡəʊt','áo khoác / con dê']], tip:'Sau /s/ thì KHÔNG bật hơi: school nghe gần như «sgool».' },
    { s:'ɡ', type:'Tắc, hữu thanh', name:'g', vi:'Giống /k/ nhưng dây thanh rung.',
      spell:['g trước a/o/u — go, game','gg — bigger','gu — guess'],
      eg:[['go','ɡəʊ','đi'],['big','bɪɡ','to'],['guess','ɡes','đoán']],
      pair:[['game','ɡeɪm','came','keɪm','trò chơi / đã đến']], tip:'g trước e/i/y thường thành /dʒ/: gentle, giant, gym.' },
    { s:'tʃ', type:'Tắc xát, vô thanh', name:'ch', vi:'Lưỡi chạm lợi rồi nhả từ từ tạo tiếng xát. Bật hơi rõ.',
      spell:['ch — chair','tch — watch','t + ure — picture, future'],
      eg:[['chair','tʃeə','ghế'],['watch','wɒtʃ','xem'],['picture','ˈpɪktʃə','bức tranh']],
      pair:[['chair','tʃeə','share','ʃeə','ghế / chia sẻ'],['cheap','tʃiːp','jeep','dʒiːp','rẻ / xe jeep']],
      tip:'Khác «ch» tiếng Việt: âm Anh có phần bật /t/ rõ ở đầu.' },
    { s:'dʒ', type:'Tắc xát, hữu thanh', name:'j', vi:'Giống /tʃ/ nhưng dây thanh rung.',
      spell:['j — job','g trước e/i/y — gentle, gym','dge — bridge','du — education'],
      eg:[['job','dʒɒb','việc'],['bridge','brɪdʒ','cây cầu'],['age','eɪdʒ','tuổi']],
      pair:[['jeep','dʒiːp','cheap','tʃiːp','xe jeep / rẻ']], tip:'Người Việt hay đọc thành «gi» — nhớ giữ phần tắc /d/ ở đầu.' },
    { s:'f', type:'Xát, vô thanh', name:'f', vi:'Răng trên chạm nhẹ môi dưới, đẩy hơi qua khe.',
      spell:['f — five','ff — off','ph — phone','gh — laugh, enough'],
      eg:[['five','faɪv','năm'],['phone','fəʊn','điện thoại'],['enough','ɪˈnʌf','đủ']],
      pair:[['fan','fæn','van','væn','quạt / xe tải nhỏ']], tip:'Gần «ph» tiếng Việt — âm dễ với người Việt.' },
    { s:'v', type:'Xát, hữu thanh', name:'v', vi:'Giống /f/ nhưng dây thanh rung. Răng phải chạm môi.',
      spell:['v — very','ve cuối — love, give'],
      eg:[['very','ˈveri','rất'],['love','lʌv','yêu'],['have','hæv','có']],
      pair:[['vine','vaɪn','fine','faɪn','dây leo / ổn']],
      tip:'LỖI RẤT PHỔ BIẾN: người Việt đọc /v/ thành «d» hoặc «z». Bắt buộc phải chạm răng vào môi dưới.' },
    { s:'θ', type:'Xát, vô thanh', name:'th vô thanh', vi:'Đầu lưỡi đặt nhẹ giữa hai hàm răng, đẩy hơi ra, dây thanh KHÔNG rung.',
      spell:['th — think, three, both'],
      eg:[['think','θɪŋk','nghĩ'],['three','θriː','ba'],['month','mʌnθ','tháng']],
      pair:[['think','θɪŋk','sink','sɪŋk','nghĩ / chìm'],['thin','θɪn','tin','tɪn','mỏng / thiếc']],
      tip:'Người Việt hay thay bằng /t/ hoặc /s/. Soi gương: phải nhìn thấy đầu lưỡi thò ra.' },
    { s:'ð', type:'Xát, hữu thanh', name:'th hữu thanh', vi:'Giống /θ/ nhưng dây thanh rung.',
      spell:['th ở từ chức năng — the, this, that, they, there','th giữa nguyên âm — mother, weather'],
      eg:[['this','ðɪs','cái này'],['mother','ˈmʌðə','mẹ'],['breathe','briːð','thở']],
      pair:[['they','ðeɪ','day','deɪ','họ / ngày'],['breathe','briːð','breeze','briːz','thở / gió nhẹ']],
      tip:'Quy tắc mẹo: từ ngữ pháp (the, this, then, though) thường /ð/; từ nội dung (think, thick, thank) thường /θ/.' },
    { s:'s', type:'Xát, vô thanh', name:'s', vi:'Đầu lưỡi gần lợi trên, hơi thoát qua rãnh hẹp tạo tiếng rít.',
      spell:['s — see','ss — miss','c trước e/i/y — city, ice','sc — science'],
      eg:[['see','siː','thấy'],['city','ˈsɪti','thành phố'],['books','bʊks','những cuốn sách']],
      pair:[['sip','sɪp','zip','zɪp','nhấp / khoá kéo']], tip:'Đuôi -s đọc /s/ sau âm vô thanh: cats, maps, books.' },
    { s:'z', type:'Xát, hữu thanh', name:'z', vi:'Giống /s/ nhưng dây thanh rung.',
      spell:['z — zoo','zz — buzz','s giữa nguyên âm — busy, easy','đuôi -s sau âm hữu thanh — dogs'],
      eg:[['zoo','zuː','sở thú'],['easy','ˈiːzi','dễ'],['dogs','dɒɡz','những con chó']],
      pair:[['zoo','zuː','sue','suː','sở thú / kiện']],
      tip:'Người Việt hay bỏ hẳn đuôi -s. Nhớ: sau âm hữu thanh (b, d, g, v, n, l, nguyên âm) thì đọc /z/.' },
    { s:'ʃ', type:'Xát, vô thanh', name:'sh', vi:'Lưỡi rút lui một chút so với /s/, môi hơi chu, tiếng xát trầm hơn.',
      spell:['sh — she','ti + on — nation','ci/si — special, session','ch (gốc Pháp) — machine'],
      eg:[['she','ʃiː','cô ấy'],['nation','ˈneɪʃn','quốc gia'],['machine','məˈʃiːn','máy']],
      pair:[['ship','ʃɪp','sip','sɪp','tàu / nhấp']], tip:'Gần «s» tiếng Việt miền Nam nhưng môi tròn hơn.' },
    { s:'ʒ', type:'Xát, hữu thanh', name:'zh', vi:'Giống /ʃ/ nhưng dây thanh rung. Âm hiếm nhất tiếng Anh.',
      spell:['s + ure/ion — measure, vision','g (gốc Pháp) — genre, beige'],
      eg:[['vision','ˈvɪʒn','tầm nhìn'],['usual','ˈjuːʒuəl','thường lệ'],['measure','ˈmeʒə','đo lường']],
      pair:[['vision','ˈvɪʒn','fission','ˈfɪʃn','tầm nhìn / phân hạch']], tip:'Không bao giờ đứng đầu từ tiếng Anh gốc.' },
    { s:'h', type:'Xát, vô thanh', name:'h', vi:'Chỉ là một luồng hơi thoát ra, không có cản trở trong miệng.',
      spell:['h — hat, home','wh trong who, whole'],
      eg:[['hat','hæt','mũ'],['who','huː','ai'],['behind','bɪˈhaɪnd','phía sau']],
      pair:[['hair','heə','air','eə','tóc / không khí']],
      tip:'h câm trong hour, honest, heir. Trong lời nói nhanh, h ở he/him/her cũng thường rơi mất.' },
    { s:'m', type:'Mũi', name:'m', vi:'Hai môi ngậm, hơi thoát qua mũi, dây thanh rung.',
      spell:['m — man','mm — summer','mb — climb (b câm)'],
      eg:[['man','mæn','người đàn ông'],['summer','ˈsʌmə','mùa hè'],['climb','klaɪm','trèo']],
      pair:[['some','sʌm','sun','sʌn','một vài / mặt trời']], tip:'Đuôi -m phải ngậm môi lại, không được nuốt mất.' },
    { s:'n', type:'Mũi', name:'n', vi:'Đầu lưỡi chạm lợi trên, hơi thoát qua mũi.',
      spell:['n — no','nn — dinner','kn — know (k câm)'],
      eg:[['no','nəʊ','không'],['dinner','ˈdɪnə','bữa tối'],['know','nəʊ','biết']],
      pair:[['thin','θɪn','thing','θɪŋ','mỏng / thứ']], tip:'Người Việt (miền Bắc) hay lẫn n/l — chú ý ở night, light.' },
    { s:'ŋ', type:'Mũi', name:'ng', vi:'Mặt lưỡi sau chạm ngạc mềm, hơi thoát qua mũi. Không bao giờ đứng đầu từ.',
      spell:['ng — sing, long','n trước k/g — think, finger'],
      eg:[['sing','sɪŋ','hát'],['long','lɒŋ','dài'],['think','θɪŋk','nghĩ']],
      pair:[['sing','sɪŋ','sin','sɪn','hát / tội lỗi'],['thing','θɪŋ','thin','θɪn','thứ / mỏng']],
      tip:'Trong singer /ˈsɪŋə/ không có /ɡ/, nhưng finger /ˈfɪŋɡə/ thì có.' },
    { s:'l', type:'Bên', name:'l', vi:'Đầu lưỡi chạm lợi, hơi thoát hai bên lưỡi. Cuối từ thành «l tối» — lưỡi sau nâng lên.',
      spell:['l — like','ll — ball'],
      eg:[['like','laɪk','thích'],['ball','bɔːl','quả bóng'],['people','ˈpiːpl','mọi người']],
      pair:[['light','laɪt','right','raɪt','ánh sáng / phải']],
      tip:'l cuối từ (full, milk, well) rất khác l đầu từ — nghe trầm và tối hơn hẳn.' },
    { s:'r', type:'Tiếp cận', name:'r', vi:'Đầu lưỡi cong lên gần lợi nhưng KHÔNG chạm, môi hơi tròn. Tuyệt đối không rung lưỡi.',
      spell:['r — red','rr — sorry','wr — write (w câm)'],
      eg:[['red','red','đỏ'],['write','raɪt','viết'],['sorry','ˈsɒri','xin lỗi']],
      pair:[['right','raɪt','light','laɪt','phải / ánh sáng']],
      tip:'Giọng Anh chỉ đọc /r/ trước nguyên âm (car nhưng carry); giọng Mỹ đọc mọi vị trí.' },
    { s:'w', type:'Tiếp cận', name:'w', vi:'Môi chu tròn mạnh rồi mở nhanh sang nguyên âm sau.',
      spell:['w — we','wh — what, when','u sau q/g — quick, language'],
      eg:[['we','wiː','chúng tôi'],['what','wɒt','cái gì'],['quick','kwɪk','nhanh']],
      pair:[['west','west','vest','vest','phía tây / áo gilê']],
      tip:'w câm trong write, wrong, answer, sword.' },
    { s:'j', type:'Tiếp cận', name:'y', vi:'Lưỡi nâng cao về phía ngạc cứng như chuẩn bị đọc /iː/ rồi trượt sang nguyên âm sau.',
      spell:['y đầu từ — yes, young','u/eu — use, Europe','i trong onion'],
      eg:[['yes','jes','vâng'],['use','juːz','dùng'],['music','ˈmjuːzɪk','âm nhạc']],
      pair:[['year','jɪə','ear','ɪə','năm / tai']],
      tip:'Chú ý university /ˌjuːnɪˈvɜːsəti/ bắt đầu bằng /j/ nên dùng «a university» chứ không phải «an».' }
  ],

  /* ---------- Trọng âm từ ---------- */
  stress: [
    { t:'Danh từ và tính từ 2 âm tiết → phần lớn nhấn âm 1',
      d:'Khoảng 80% danh từ hai âm tiết nhấn vào âm tiết đầu.',
      ex:[['TAble','ˈteɪbl'],['HAPpy','ˈhæpi'],['MOUNtain','ˈmaʊntɪn'],['DOCtor','ˈdɒktə']] },
    { t:'Động từ 2 âm tiết → phần lớn nhấn âm 2',
      d:'Ngược lại với danh từ. Đây là cơ sở của các cặp danh–động cùng chính tả.',
      ex:[['beGIN','bɪˈɡɪn'],['deCIDE','dɪˈsaɪd'],['reLAX','rɪˈlæks'],['forGET','fəˈɡet']] },
    { t:'Cặp danh–động cùng mặt chữ: danh nhấn trước, động nhấn sau',
      d:'Đổi trọng âm là đổi từ loại, và nguyên âm không trọng âm rút về /ə/.',
      ex:[['a REcord ˈrekɔːd','to reCORD rɪˈkɔːd'],['a PREsent ˈpreznt','to preSENT prɪˈzent'],['an OBject ˈɒbdʒɪkt','to obJECT əbˈdʒekt'],['an INcrease ˈɪŋkriːs','to inCREASE ɪnˈkriːs']] },
    { t:'Đuôi -ion, -ic, -ical, -ity, -ity → nhấn ngay TRƯỚC đuôi',
      d:'Đây là nhóm quy tắc chắc chắn nhất, dùng được cho hàng nghìn từ.',
      ex:[['naTIONal ˈnæʃnəl','eduCAtion ˌedʒuˈkeɪʃn'],['ecoNOMic ˌiːkəˈnɒmɪk'],['aBIlity əˈbɪləti'],['phoTOgraphy fəˈtɒɡrəfi']] },
    { t:'Đuôi -ee, -eer, -ese, -ette, -esque → nhấn vào chính đuôi',
      d:'Nhóm đuôi gốc Pháp giữ trọng âm ở cuối.',
      ex:[['employEE ɪmplɔɪˈiː'],['engiNEER ˌendʒɪˈnɪə'],['VietnamESE ˌvjetnəˈmiːz'],['picturESQUE ˌpɪktʃəˈresk']] },
    { t:'Đuôi -ate, -fy, -ise/-ize (động từ dài) → nhấn lùi hai âm tiết',
      d:'Đếm ngược từ đuôi: đuôi, một âm tiết, rồi trọng âm.',
      ex:[['ˈcommunicate kəˈmjuːnɪkeɪt'],['ˈidentify aɪˈdentɪfaɪ'],['ˈorganise ˈɔːɡənaɪz']] },
    { t:'Từ ghép: danh + danh nhấn phần đầu, tính + danh nhấn phần sau',
      d:'Đây là điểm phân biệt nghĩa quan trọng trong hội thoại.',
      ex:[['a GREENhouse ˈɡriːnhaʊs = nhà kính','a green HOUSE = ngôi nhà màu xanh'],['a BLACKboard = bảng đen','a black BOARD = tấm ván màu đen']] },
    { t:'Tiền tố un-, in-, dis-, re-, pre- thường KHÔNG nhận trọng âm',
      d:'Trọng âm giữ nguyên ở gốc từ.',
      ex:[['HAPpy → unHAPpy'],['CORrect → inCORrect'],['aGREE → disaGREE']] }
  ],

  /* ---------- Nhịp điệu & nối âm ---------- */
  connected: [
    { t:'Dạng yếu (weak forms)',
      d:'Từ chức năng (a, an, the, of, to, for, and, can, was, are…) trong câu thường rút gọn về /ə/. Nói dạng mạnh ở mọi chỗ sẽ nghe rất gượng.',
      ex:[['a cup of tea','ə ˈkʌp əv ˈtiː'],['fish and chips','ˈfɪʃ ən ˈtʃɪps'],['I can swim','aɪ kən ˈswɪm'],['Where are you from?','ˈweər ə ju ˈfrɒm']] },
    { t:'Nối phụ âm với nguyên âm (linking)',
      d:'Phụ âm cuối từ chạy sang nguyên âm đầu từ sau, ranh giới từ biến mất.',
      ex:[['an apple','ə ˈnæpl'],['pick it up','ˈpɪ kɪ ˈtʌp'],['turn off','ˈtɜː ˈnɒf'],['not at all','ˈnɒ tə ˈtɔːl']] },
    { t:'Nối bằng /j/ và /w/ (intrusive glide)',
      d:'Giữa hai nguyên âm, người bản ngữ chèn một âm lướt rất nhẹ.',
      ex:[['I am','aɪ‿jæm'],['go on','ɡəʊ‿wɒn'],['the end','ði‿jend'],['too old','tuː‿wəʊld']] },
    { t:'Linking /r/ (giọng Anh)',
      d:'Chữ r cuối từ vốn câm sẽ được đọc lên khi từ sau bắt đầu bằng nguyên âm.',
      ex:[['far away','ˈfɑːr əˈweɪ'],['four apples','ˈfɔːr ˈæplz'],['mother and father','ˈmʌðər ən ˈfɑːðə']] },
    { t:'Nuốt âm (elision)',
      d:'/t/ và /d/ giữa hai phụ âm thường biến mất; âm /ə/ ở âm tiết yếu cũng có thể rơi.',
      ex:[['next day','ˈneks ˈdeɪ'],['last night','ˈlɑːs ˈnaɪt'],['friendship','ˈfrenʃɪp'],['comfortable','ˈkʌmftəbl']] },
    { t:'Đồng hoá (assimilation)',
      d:'Âm cuối đổi cho giống âm đầu của từ kế tiếp để miệng đỡ phải di chuyển.',
      ex:[['ten pounds','ˈtem ˈpaʊndz'],['good boy','ˈɡʊb ˈbɔɪ'],['this shop','ˈðɪʃ ˈʃɒp'],['did you','ˈdɪdʒu']] },
    { t:'Nhịp theo trọng âm (stress-timed rhythm)',
      d:'Tiếng Anh giữ khoảng cách đều giữa các âm tiết CÓ trọng âm, nén các âm tiết yếu ở giữa. Tiếng Việt thì mỗi âm tiết một nhịp — đây là khác biệt gốc rễ.',
      ex:[['DOGS eat BONES','3 nhịp'],['the DOGS have EAten the BONES','vẫn 3 nhịp, chỉ nén phần yếu']] },
    { t:'Ngữ điệu',
      d:'Xuống giọng ở câu trần thuật và câu hỏi Wh-; lên giọng ở câu hỏi Yes/No và khi liệt kê chưa hết.',
      ex:[['She lives in Hanoi. ↘'],['Where do you live? ↘'],['Do you live in Hanoi? ↗'],['tea ↗, coffee ↗, or juice ↘?']] }
  ],

  /* ---------- Quy tắc chính tả → âm ---------- */
  spelling: [
    { t:'Đuôi -s (số nhiều, ngôi 3 số ít, sở hữu)',
      d:'/ɪz/ sau âm rít s, z, ʃ, ʒ, tʃ, dʒ · /s/ sau âm vô thanh khác · /z/ sau âm hữu thanh và nguyên âm.',
      ex:[['watches','ˈwɒtʃɪz'],['books','bʊks'],['dogs','dɒɡz'],['plays','pleɪz']] },
    { t:'Đuôi -ed (quá khứ, phân từ)',
      d:'/ɪd/ sau /t/ và /d/ · /t/ sau âm vô thanh khác · /d/ sau âm hữu thanh và nguyên âm.',
      ex:[['wanted','ˈwɒntɪd'],['worked','wɜːkt'],['played','pleɪd'],['needed','ˈniːdɪd']] },
    { t:'Quy tắc «e câm» (magic e)',
      d:'Chữ e cuối không đọc nhưng làm nguyên âm trước đó thành nguyên âm dài / đôi.',
      ex:[['hat hæt → hate heɪt'],['bit bɪt → bite baɪt'],['not nɒt → note nəʊt'],['cut kʌt → cute kjuːt']] },
    { t:'Chữ cái câm',
      d:'Rất nhiều từ giữ chữ không đọc do lịch sử chính tả.',
      ex:[['k câm — know, knee, knife'],['w câm — write, wrong, answer'],['b câm — climb, doubt, lamb'],['gh câm — night, though, weight'],['t câm — listen, castle, often'],['h câm — hour, honest, ghost']] },
    { t:'ough — bảy cách đọc',
      d:'Chuỗi chữ bất trị nhất tiếng Anh, phải học theo từ.',
      ex:[['though','ðəʊ'],['through','θruː'],['tough','tʌf'],['cough','kɒf'],['bough','baʊ'],['thorough','ˈθʌrə'],['thought','θɔːt']] },
    { t:'c và g mềm',
      d:'Trước e, i, y thì c đọc /s/ và g đọc /dʒ/; trước a, o, u thì c đọc /k/ và g đọc /ɡ/.',
      ex:[['city ˈsɪti · cat kæt'],['gym dʒɪm · go ɡəʊ'],['circle ˈsɜːkl'],['giant ˈdʒaɪənt']] }
  ],

  /* ---------- Anh vs Mỹ ---------- */
  variants: [
    { t:'Âm /r/ cuối âm tiết', uk:'không đọc — car /kɑː/, hard /hɑːd/', us:'đọc rõ và cuộn lưỡi — car /kɑːr/, hard /hɑːrd/' },
    { t:'Chữ a trước s, f, th', uk:'/ɑː/ — bath /bɑːθ/, ask /ɑːsk/, dance /dɑːns/', us:'/æ/ — bath /bæθ/, ask /æsk/, dance /dæns/' },
    { t:'Âm /ɒ/', uk:'giữ nguyên /ɒ/ — hot /hɒt/, not /nɒt/', us:'thành /ɑː/ — hot /hɑːt/, not /nɑːt/' },
    { t:'/t/ giữa hai nguyên âm', uk:'giữ /t/ rõ — water /ˈwɔːtə/', us:'thành âm vỗ gần /d/ — water /ˈwɑːɾər/' },
    { t:'/juː/ sau t, d, n', uk:'giữ /j/ — tune /tjuːn/, new /njuː/, duty /ˈdjuːti/', us:'rụng /j/ — tune /tuːn/, new /nuː/, duty /ˈduːti/' },
    { t:'Trọng âm một số từ', uk:'ADdress ˈædres · GARage ˈɡærɑːʒ · BALlet ˈbæleɪ', us:'aDDRESS əˈdres · gaRAGE ɡəˈrɑːʒ · balLET bæˈleɪ' },
    { t:'Chính tả', uk:'colour, centre, travelling, realise, defence, catalogue', us:'color, center, traveling, realize, defense, catalog' }
  ]
};

/* Gộp toàn bộ âm vị thành một mảng phẳng để tra cứu */
const PHON_EN_ALL = []
  .concat(PHON_EN.vowels.map(x => Object.assign({ group:'vowel' }, x)))
  .concat(PHON_EN.diphthongs.map(x => Object.assign({ group:'diph' }, x)))
  .concat(PHON_EN.consonants.map(x => Object.assign({ group:'cons' }, x)));

if (typeof module !== 'undefined'){ module.exports = { PHON_EN, PHON_EN_ALL }; }
