/* ============================================================
   LangLab — BẢNG BỘ THỦ ĐẦY ĐỦ (部首表) cho chữ Hán giản thể
   ------------------------------------------------------------
   Dùng cho màn «Tra theo bộ thủ»: thấy một chữ lạ, không biết đọc thế nào,
   thì tìm bộ thủ của nó rồi đếm số nét còn lại — đúng cách tra từ điển giấy.

   Trường:
     r   chữ bộ thủ (dạng chuẩn)
     alt các dạng biến thể khi đứng trong chữ (氵 của 水, 亻 của 人…)
     s   SỐ NÉT của chính bộ thủ (theo lối viết giản thể)
     py  pinyin · hv âm Hán–Việt · vi nghĩa
     ex  chuỗi các chữ mang bộ này. Danh sách này liệt kê rộng tay; app chỉ
         hiện những chữ THẬT SỰ có trong kho từ của LangLab, chữ nào không có
         thì tự rụng, nên thêm dư không gây lỗi.

   Số nét TỔNG của từng chữ không ghi ở đây — app đếm trực tiếp từ dữ liệu nét
   của Hanzi Writer (hanzi/<mã>.json), nên luôn khớp với hình vẽ trong Tập viết.
   ============================================================ */

const RADICALS_FULL_ZH = [

  /* ================= 1 nét ================= */
  {r:'一', alt:'', s:1, py:'yī', hv:'nhất', vi:'một; nét ngang', ex:'一三上下不七丁万与且世丘丙东丝'},
  {r:'丨', alt:'', s:1, py:'gǔn', hv:'cổn', vi:'nét sổ thẳng', ex:'中旧串个'},
  {r:'丶', alt:'', s:1, py:'zhǔ', hv:'chủ', vi:'nét chấm', ex:'主丸为'},
  {r:'丿', alt:'', s:1, py:'piě', hv:'phiệt', vi:'nét phẩy', ex:'乃久么之乎乘年'},
  {r:'乙', alt:'乚', s:1, py:'yǐ', hv:'ất', vi:'can Ất; nét gập', ex:'九也乞习乡买乱书'},
  {r:'亅', alt:'', s:1, py:'jué', hv:'quyết', vi:'nét móc', ex:'了事予'},

  /* ================= 2 nét ================= */
  {r:'二', alt:'', s:2, py:'èr', hv:'nhị', vi:'hai', ex:'二五云互井些'},
  {r:'亠', alt:'', s:2, py:'tóu', hv:'đầu', vi:'nắp đậy', ex:'京亮交产六市亡亦高夜'},
  {r:'人', alt:'亻', s:2, py:'rén', hv:'nhân', vi:'người', ex:'人个今以会他你们住信件休作低体但便位何供修倒健像化介付仔仍代'},
  {r:'儿', alt:'', s:2, py:'ér', hv:'nhi', vi:'trẻ con; chân người', ex:'儿元兄充先光克免'},
  {r:'入', alt:'', s:2, py:'rù', hv:'nhập', vi:'vào', ex:'入内全'},
  {r:'八', alt:'丷', s:2, py:'bā', hv:'bát', vi:'tám; chia ra', ex:'八公六兰共兴具其兵典单'},
  {r:'冂', alt:'', s:2, py:'jiōng', hv:'quynh', vi:'vùng ngoài thành', ex:'内再同网周册'},
  {r:'冖', alt:'', s:2, py:'mì', hv:'mịch', vi:'trùm khăn', ex:'写军农冠'},
  {r:'冫', alt:'', s:2, py:'bīng', hv:'băng', vi:'nước đá', ex:'冰冷冲决况准凉减净'},
  {r:'几', alt:'', s:2, py:'jī', hv:'kỷ', vi:'cái ghế nhỏ', ex:'几凡凭'},
  {r:'凵', alt:'', s:2, py:'kǎn', hv:'khảm', vi:'há miệng', ex:'出击凶画'},
  {r:'刀', alt:'刂', s:2, py:'dāo', hv:'đao', vi:'con dao', ex:'刀分切列刚创别到刻前利判刷剪剩割'},
  {r:'力', alt:'', s:2, py:'lì', hv:'lực', vi:'sức lực', ex:'力办加动助努劳勇功男劝'},
  {r:'勹', alt:'', s:2, py:'bāo', hv:'bao', vi:'bao bọc', ex:'包勺句匆'},
  {r:'匕', alt:'', s:2, py:'bǐ', hv:'chuỷ', vi:'cái thìa', ex:'北比化'},
  {r:'匚', alt:'', s:2, py:'fāng', hv:'phương', vi:'cái hộp vuông', ex:'区匹医'},
  {r:'十', alt:'', s:2, py:'shí', hv:'thập', vi:'mười', ex:'十千午半协博直南真'},
  {r:'卜', alt:'', s:2, py:'bǔ', hv:'bốc', vi:'bói toán', ex:'卡外占处'},
  {r:'卩', alt:'', s:2, py:'jié', hv:'tiết', vi:'cái ấn tín', ex:'印却卫危却'},
  {r:'厂', alt:'', s:2, py:'chǎng', hv:'hán', vi:'sườn núi; nhà xưởng', ex:'厂厅历厚原厨压'},
  {r:'厶', alt:'', s:2, py:'sī', hv:'khư', vi:'riêng tư', ex:'去参能台'},
  {r:'又', alt:'', s:2, py:'yòu', hv:'hựu', vi:'lại; bàn tay phải', ex:'又反友双发取受叔难对观欢'},
  {r:'讠', alt:'言', s:2, py:'yán', hv:'ngôn', vi:'lời nói', ex:'说话请谁语讲认识课谢词讨订记许议论访该试详谈调'},

  /* ================= 3 nét ================= */
  {r:'口', alt:'', s:3, py:'kǒu', hv:'khẩu', vi:'cái miệng; cửa', ex:'口叫号吃各名吗和品哪问员唱喝听右台可句古另合同吧啊咖啡嘴'},
  {r:'囗', alt:'', s:3, py:'wéi', hv:'vi', vi:'vây quanh', ex:'四回因国园图团围困'},
  {r:'土', alt:'', s:3, py:'tǔ', hv:'thổ', vi:'đất', ex:'土地在坐场城块堂墙基址均型堆'},
  {r:'士', alt:'', s:3, py:'shì', hv:'sĩ', vi:'kẻ sĩ', ex:'士声壮喜'},
  {r:'夕', alt:'', s:3, py:'xī', hv:'tịch', vi:'chiều tối', ex:'夕外多名夜梦'},
  {r:'大', alt:'', s:3, py:'dà', hv:'đại', vi:'to lớn', ex:'大天太夫失夹奇奋奖'},
  {r:'女', alt:'', s:3, py:'nǚ', hv:'nữ', vi:'nữ giới', ex:'女好妈她姐妹婚娘始姓妻安要嫁奶'},
  {r:'子', alt:'', s:3, py:'zǐ', hv:'tử', vi:'con; hạt', ex:'子孩学孙字存孝孔季'},
  {r:'宀', alt:'', s:3, py:'mián', hv:'miên', vi:'mái nhà', ex:'家安室客宿定完宝宽察官守宜宫容寄密'},
  {r:'寸', alt:'', s:3, py:'cùn', hv:'thốn', vi:'tấc', ex:'寸对寻导封射将'},
  {r:'小', alt:'', s:3, py:'xiǎo', hv:'tiểu', vi:'nhỏ', ex:'小少尖当尝'},
  {r:'尸', alt:'', s:3, py:'shī', hv:'thi', vi:'thây; thân người nằm', ex:'尺尾局屋展层居届'},
  {r:'山', alt:'', s:3, py:'shān', hv:'sơn', vi:'núi', ex:'山岁岛峰岸'},
  {r:'川', alt:'巛', s:3, py:'chuān', hv:'xuyên', vi:'sông', ex:'川州巡'},
  {r:'工', alt:'', s:3, py:'gōng', hv:'công', vi:'công việc; thợ', ex:'工左巧差功'},
  {r:'己', alt:'已巳', s:3, py:'jǐ', hv:'kỷ', vi:'bản thân', ex:'己已巴导'},
  {r:'巾', alt:'', s:3, py:'jīn', hv:'cân', vi:'cái khăn', ex:'巾市布帮常帽带席幅'},
  {r:'干', alt:'', s:3, py:'gān', hv:'can', vi:'cái chày; khô', ex:'干平年幸'},
  {r:'幺', alt:'', s:3, py:'yāo', hv:'yêu', vi:'nhỏ bé', ex:'幻幼'},
  {r:'广', alt:'', s:3, py:'guǎng', hv:'nghiễm', vi:'mái che; rộng', ex:'广床店座应度庭康府底废'},
  {r:'廴', alt:'', s:3, py:'yǐn', hv:'dẫn', vi:'bước dài', ex:'建延'},
  {r:'弋', alt:'', s:3, py:'yì', hv:'dặc', vi:'bắn tên có dây', ex:'式'},
  {r:'弓', alt:'', s:3, py:'gōng', hv:'cung', vi:'cái cung', ex:'弓引张弟弱强'},
  {r:'彐', alt:'彑', s:3, py:'jì', hv:'kệ', vi:'mõm con lợn', ex:'录归当灵'},
  {r:'彡', alt:'', s:3, py:'shān', hv:'sam', vi:'lông tóc', ex:'形影须彩'},
  {r:'彳', alt:'', s:3, py:'chì', hv:'sách', vi:'bước chân trái', ex:'行往很得德街循律征'},
  {r:'忄', alt:'心', s:3, py:'xīn', hv:'tâm', vi:'tim (đứng bên trái)', ex:'忙快怕情性懂惊怀慢恨愉惯'},
  {r:'扌', alt:'手', s:3, py:'shǒu', hv:'thủ', vi:'tay (đứng bên trái)', ex:'打找把拿指接换提技拉推排搬擦抱拍挂扫招持挺掉播搞抓'},
  {r:'氵', alt:'水', s:3, py:'shuǐ', hv:'thuỷ', vi:'nước (đứng bên trái)', ex:'汉江没河法洗酒游清海深注活漂消汤治济流渴满演潮浪'},
  {r:'犭', alt:'犬', s:3, py:'quǎn', hv:'khuyển', vi:'chó (đứng bên trái)', ex:'猫狗猪独狼猴狮'},
  {r:'艹', alt:'艸', s:3, py:'cǎo', hv:'thảo', vi:'cỏ cây', ex:'花草茶苹菜药英节萝蓝落荔菠营蒜葡萄薄'},
  {r:'辶', alt:'辵', s:3, py:'chuò', hv:'sước', vi:'đi, bước', ex:'过还这送近远进边道通选迎追返遇速迟逛'},
  {r:'阝', alt:'', s:3, py:'fù / yì', hv:'phụ / ấp', vi:'gò đất (trái) · làng xóm (phải)', ex:'陈陪院附队阳险都部邮那阿限'},
  {r:'饣', alt:'食', s:3, py:'shí', hv:'thực', vi:'ăn', ex:'饭饿馆饱饼饺'},
  {r:'纟', alt:'糸', s:3, py:'sī', hv:'ti', vi:'sợi tơ', ex:'红纸经给结级练线约绿细绍纪织续纷统'},
  {r:'门', alt:'門', s:3, py:'mén', hv:'môn', vi:'cửa', ex:'门问闭间闻闹闲'},
  {r:'马', alt:'馬', s:3, py:'mǎ', hv:'mã', vi:'con ngựa', ex:'马骑妈吗骂驾验'},
  {r:'飞', alt:'', s:3, py:'fēi', hv:'phi', vi:'bay', ex:'飞'},
  {r:'习', alt:'', s:3, py:'xí', hv:'tập', vi:'học tập', ex:'习'},

  /* ================= 4 nét ================= */
  {r:'心', alt:'', s:4, py:'xīn', hv:'tâm', vi:'trái tim; lòng dạ', ex:'心思念您想感意忘志急怒态'},
  {r:'戈', alt:'', s:4, py:'gē', hv:'qua', vi:'cây giáo', ex:'战成或我戏'},
  {r:'户', alt:'', s:4, py:'hù', hv:'hộ', vi:'cánh cửa; hộ gia đình', ex:'房所扇'},
  {r:'手', alt:'', s:4, py:'shǒu', hv:'thủ', vi:'bàn tay', ex:'手掌拜'},
  {r:'攵', alt:'攴', s:4, py:'pū', hv:'phốc', vi:'đánh khẽ', ex:'收放故教敢数政改效'},
  {r:'文', alt:'', s:4, py:'wén', hv:'văn', vi:'chữ nghĩa, văn', ex:'文'},
  {r:'斗', alt:'', s:4, py:'dǒu', hv:'đẩu', vi:'cái đấu đong', ex:'斗料'},
  {r:'斤', alt:'', s:4, py:'jīn', hv:'cân', vi:'cái rìu; cân', ex:'斤新断所'},
  {r:'方', alt:'', s:4, py:'fāng', hv:'phương', vi:'vuông; phương hướng', ex:'方放旅族旁'},
  {r:'日', alt:'', s:4, py:'rì', hv:'nhật', vi:'mặt trời; ngày', ex:'日明时早春是昨晚暖晴景暗星易普量'},
  {r:'曰', alt:'', s:4, py:'yuē', hv:'viết', vi:'nói rằng', ex:'曲最'},
  {r:'月', alt:'', s:4, py:'yuè', hv:'nguyệt', vi:'mặt trăng; (bên trái) thịt', ex:'月有朋服期朝脸脚胖能肚腿肉背'},
  {r:'木', alt:'', s:4, py:'mù', hv:'mộc', vi:'cây, gỗ', ex:'木本机杯校样村林果树桌椅棵极检楼梯板'},
  {r:'欠', alt:'', s:4, py:'qiàn', hv:'khiếm', vi:'thiếu; ngáp', ex:'欢次歌'},
  {r:'止', alt:'', s:4, py:'zhǐ', hv:'chỉ', vi:'dừng lại', ex:'止正步此武'},
  {r:'歹', alt:'', s:4, py:'dǎi', hv:'ngạt', vi:'xương tàn; xấu', ex:'死残'},
  {r:'比', alt:'', s:4, py:'bǐ', hv:'tỷ', vi:'so sánh', ex:'比'},
  {r:'毛', alt:'', s:4, py:'máo', hv:'mao', vi:'lông', ex:'毛毯'},
  {r:'气', alt:'', s:4, py:'qì', hv:'khí', vi:'hơi, khí', ex:'气'},
  {r:'水', alt:'', s:4, py:'shuǐ', hv:'thuỷ', vi:'nước', ex:'水永求'},
  {r:'火', alt:'灬', s:4, py:'huǒ', hv:'hoả', vi:'lửa', ex:'火烧热烟然照点煮灯炒烤'},
  {r:'爪', alt:'爫', s:4, py:'zhǎo', hv:'trảo', vi:'móng vuốt', ex:'爬爱受'},
  {r:'父', alt:'', s:4, py:'fù', hv:'phụ', vi:'người cha', ex:'父爸爷'},
  {r:'片', alt:'', s:4, py:'piàn', hv:'phiến', vi:'mảnh, tấm', ex:'片版'},
  {r:'牛', alt:'牜', s:4, py:'niú', hv:'ngưu', vi:'trâu bò', ex:'牛物特牌'},
  {r:'犬', alt:'', s:4, py:'quǎn', hv:'khuyển', vi:'con chó', ex:'哭'},
  {r:'王', alt:'玉', s:4, py:'wáng', hv:'vương', vi:'vua; ngọc', ex:'王玩现球理班环玻'},
  {r:'礻', alt:'示', s:4, py:'shì', hv:'kỳ', vi:'thần linh, thờ cúng', ex:'礼社神福视祝'},
  {r:'车', alt:'車', s:4, py:'chē', hv:'xa', vi:'xe', ex:'车轮软转较辆'},
  {r:'见', alt:'見', s:4, py:'jiàn', hv:'kiến', vi:'nhìn thấy', ex:'见观览觉规'},
  {r:'贝', alt:'貝', s:4, py:'bèi', hv:'bối', vi:'vỏ sò; tiền của', ex:'贝贵费购资赢赛财货贷账'},
  {r:'长', alt:'長', s:4, py:'cháng', hv:'trường', vi:'dài; lớn lên', ex:'长'},
  {r:'风', alt:'風', s:4, py:'fēng', hv:'phong', vi:'gió', ex:'风飘'},
  {r:'韦', alt:'韋', s:4, py:'wéi', hv:'vi', vi:'da thuộc', ex:'韩'},
  {r:'无', alt:'', s:4, py:'wú', hv:'vô', vi:'không có', ex:'无既'},

  /* ================= 5 nét ================= */
  {r:'瓜', alt:'', s:5, py:'guā', hv:'qua', vi:'quả dưa', ex:'瓜'},
  {r:'甘', alt:'', s:5, py:'gān', hv:'cam', vi:'ngọt', ex:'甜甚'},
  {r:'生', alt:'', s:5, py:'shēng', hv:'sinh', vi:'sinh ra, sống', ex:'生'},
  {r:'用', alt:'', s:5, py:'yòng', hv:'dụng', vi:'dùng', ex:'用'},
  {r:'田', alt:'', s:5, py:'tián', hv:'điền', vi:'ruộng', ex:'田男界画留番'},
  {r:'疒', alt:'', s:5, py:'nè', hv:'nạch', vi:'bệnh tật', ex:'病疼痛疲瘦疗'},
  {r:'白', alt:'', s:5, py:'bái', hv:'bạch', vi:'trắng', ex:'白百的'},
  {r:'皮', alt:'', s:5, py:'pí', hv:'bì', vi:'da, vỏ', ex:'皮'},
  {r:'皿', alt:'', s:5, py:'mǐn', hv:'mãnh', vi:'bát đĩa', ex:'盘盖盐盒'},
  {r:'目', alt:'', s:5, py:'mù', hv:'mục', vi:'con mắt', ex:'目看眼睛睡直相省着'},
  {r:'矛', alt:'', s:5, py:'máo', hv:'mâu', vi:'cây mâu', ex:'矛'},
  {r:'矢', alt:'', s:5, py:'shǐ', hv:'thỉ', vi:'mũi tên', ex:'知短矮'},
  {r:'石', alt:'', s:5, py:'shí', hv:'thạch', vi:'đá', ex:'石码硬碗确破碰'},
  {r:'禾', alt:'', s:5, py:'hé', hv:'hoà', vi:'cây lúa', ex:'秋种科秒税和香程稍'},
  {r:'穴', alt:'', s:5, py:'xué', hv:'huyệt', vi:'hang, lỗ', ex:'空穿突窗究'},
  {r:'立', alt:'', s:5, py:'lì', hv:'lập', vi:'đứng', ex:'立站亲章竞端'},
  {r:'衤', alt:'衣', s:5, py:'yī', hv:'y', vi:'áo (đứng bên trái)', ex:'衬衫被裤裙初'},
  {r:'钅', alt:'金', s:5, py:'jīn', hv:'kim', vi:'kim loại', ex:'钱铁银错钟镜钥铅锅键'},
  {r:'鸟', alt:'鳥', s:5, py:'niǎo', hv:'điểu', vi:'con chim', ex:'鸟鸡鸭鹅鸽'},
  {r:'龙', alt:'龍', s:5, py:'lóng', hv:'long', vi:'con rồng', ex:'龙'},

  /* ================= 6 nét ================= */
  {r:'竹', alt:'⺮', s:6, py:'zhú', hv:'trúc', vi:'tre trúc', ex:'笔第答等算篮笑简筷签箱'},
  {r:'米', alt:'', s:6, py:'mǐ', hv:'mễ', vi:'gạo', ex:'米粉糖精类粥'},
  {r:'网', alt:'罒', s:6, py:'wǎng', hv:'võng', vi:'cái lưới', ex:'罗罚置'},
  {r:'羊', alt:'', s:6, py:'yáng', hv:'dương', vi:'con dê, cừu', ex:'羊美差养鲜'},
  {r:'羽', alt:'', s:6, py:'yǔ', hv:'vũ', vi:'lông vũ', ex:'翻'},
  {r:'老', alt:'耂', s:6, py:'lǎo', hv:'lão', vi:'già', ex:'老考者'},
  {r:'而', alt:'', s:6, py:'ér', hv:'nhi', vi:'mà, rồi', ex:'而耐'},
  {r:'耳', alt:'', s:6, py:'ěr', hv:'nhĩ', vi:'cái tai', ex:'耳取闻聊职联'},
  {r:'自', alt:'', s:6, py:'zì', hv:'tự', vi:'tự mình; cái mũi', ex:'自'},
  {r:'至', alt:'', s:6, py:'zhì', hv:'chí', vi:'đến', ex:'至到致'},
  {r:'舌', alt:'', s:6, py:'shé', hv:'thiệt', vi:'cái lưỡi', ex:'舌话甜乱'},
  {r:'舟', alt:'', s:6, py:'zhōu', hv:'chu', vi:'con thuyền', ex:'船'},
  {r:'艮', alt:'', s:6, py:'gèn', hv:'cấn', vi:'quẻ Cấn; cứng', ex:'很艰良'},
  {r:'色', alt:'', s:6, py:'sè', hv:'sắc', vi:'màu sắc', ex:'色'},
  {r:'虫', alt:'', s:6, py:'chóng', hv:'trùng', vi:'sâu bọ', ex:'虫蚊蛇虾蝴蜜蚂蜘蝶'},
  {r:'血', alt:'', s:6, py:'xuè', hv:'huyết', vi:'máu', ex:'血'},
  {r:'行', alt:'', s:6, py:'xíng', hv:'hành', vi:'đi; hàng', ex:'行街'},
  {r:'衣', alt:'', s:6, py:'yī', hv:'y', vi:'áo quần', ex:'衣装表'},
  {r:'页', alt:'頁', s:6, py:'yè', hv:'hiệt', vi:'trang giấy; cái đầu', ex:'页顶项顺须题颜额预颗'},
  {r:'西', alt:'覀', s:6, py:'xī', hv:'tây', vi:'phía tây', ex:'西要票'},
  {r:'麦', alt:'麥', s:6, py:'mài', hv:'mạch', vi:'lúa mạch', ex:'麦'},

  /* ================= 7 nét ================= */
  {r:'角', alt:'', s:7, py:'jiǎo', hv:'giác', vi:'cái sừng; góc', ex:'角解'},
  {r:'言', alt:'', s:7, py:'yán', hv:'ngôn', vi:'lời nói (dạng đủ nét)', ex:'言警'},
  {r:'谷', alt:'', s:7, py:'gǔ', hv:'cốc', vi:'thung lũng', ex:'谷'},
  {r:'豆', alt:'', s:7, py:'dòu', hv:'đậu', vi:'hạt đậu', ex:'豆短'},
  {r:'豕', alt:'', s:7, py:'shǐ', hv:'thỉ', vi:'con lợn', ex:'象'},
  {r:'赤', alt:'', s:7, py:'chì', hv:'xích', vi:'màu đỏ', ex:'赤'},
  {r:'走', alt:'', s:7, py:'zǒu', hv:'tẩu', vi:'đi, chạy', ex:'走起超越赶趣'},
  {r:'足', alt:'⻊', s:7, py:'zú', hv:'túc', vi:'bàn chân', ex:'足跑路跟跳踢距跪'},
  {r:'身', alt:'', s:7, py:'shēn', hv:'thân', vi:'thân mình', ex:'身躺'},
  {r:'辛', alt:'', s:7, py:'xīn', hv:'tân', vi:'cay; vất vả', ex:'辛辣'},
  {r:'辰', alt:'', s:7, py:'chén', hv:'thần', vi:'chi Thìn', ex:'农'},
  {r:'酉', alt:'', s:7, py:'yǒu', hv:'dậu', vi:'chi Dậu; hũ rượu', ex:'酒酸醋配醒'},
  {r:'里', alt:'', s:7, py:'lǐ', hv:'lý', vi:'dặm; bên trong', ex:'里重野量'},

  /* ================= 8 nét trở lên ================= */
  {r:'金', alt:'', s:8, py:'jīn', hv:'kim', vi:'vàng, kim loại (dạng đủ nét)', ex:'金'},
  {r:'青', alt:'', s:8, py:'qīng', hv:'thanh', vi:'xanh', ex:'青静'},
  {r:'雨', alt:'', s:8, py:'yǔ', hv:'vũ', vi:'mưa', ex:'雨雪雷需震零'},
  {r:'非', alt:'', s:8, py:'fēi', hv:'phi', vi:'không phải', ex:'非靠'},
  {r:'鱼', alt:'魚', s:8, py:'yú', hv:'ngư', vi:'con cá', ex:'鱼鲜鲨鲸'},
  {r:'齿', alt:'齒', s:8, py:'chǐ', hv:'xỉ', vi:'răng', ex:'齿龄'},
  {r:'面', alt:'', s:9, py:'miàn', hv:'diện', vi:'mặt; mì', ex:'面'},
  {r:'革', alt:'', s:9, py:'gé', hv:'cách', vi:'da thuộc; cải cách', ex:'鞋'},
  {r:'音', alt:'', s:9, py:'yīn', hv:'âm', vi:'âm thanh', ex:'音意章'},
  {r:'食', alt:'', s:9, py:'shí', hv:'thực', vi:'ăn (dạng đủ nét)', ex:'食餐'},
  {r:'首', alt:'', s:9, py:'shǒu', hv:'thủ', vi:'cái đầu; đứng đầu', ex:'首'},
  {r:'香', alt:'', s:9, py:'xiāng', hv:'hương', vi:'thơm', ex:'香'},
  {r:'骨', alt:'', s:9, py:'gǔ', hv:'cốt', vi:'xương', ex:'骨'},
  {r:'高', alt:'', s:10, py:'gāo', hv:'cao', vi:'cao', ex:'高'},
  {r:'鬼', alt:'', s:9, py:'guǐ', hv:'quỷ', vi:'ma quỷ', ex:'鬼'},
  {r:'鹿', alt:'', s:11, py:'lù', hv:'lộc', vi:'con hươu', ex:'鹿'},
  {r:'麻', alt:'', s:11, py:'má', hv:'ma', vi:'cây gai; tê', ex:'麻磨'},
  {r:'黑', alt:'', s:12, py:'hēi', hv:'hắc', vi:'màu đen', ex:'黑默'},
  {r:'黄', alt:'黃', s:11, py:'huáng', hv:'hoàng', vi:'màu vàng', ex:'黄'},
  {r:'鼓', alt:'', s:13, py:'gǔ', hv:'cổ', vi:'cái trống', ex:'鼓'},
  {r:'鼠', alt:'', s:13, py:'shǔ', hv:'thử', vi:'con chuột', ex:'鼠'},
  {r:'鼻', alt:'', s:14, py:'bí', hv:'tị', vi:'cái mũi', ex:'鼻'}
];

if (typeof window !== 'undefined') window.RADICALS_FULL_ZH = RADICALS_FULL_ZH;
if (typeof module !== 'undefined' && module.exports) module.exports = { RADICALS_FULL_ZH };
