/* ============================================================
   LangLab — LUYỆN NÓI TIẾNG NHẬT: chủ đề tự soạn (N5 → N2), nhân vật クアン (Quân), Hà Nội.
   Shape: { id, jp, vi, level, keys:[[jp (furigana), vi]], qs:[jp], paras:[{jp (furigana, tách từ), vi}] }
   ============================================================ */
const SPEAKING_JA = [
  { id:'jikoshoukai', jp:'自己紹介', vi:'Tự giới thiệu', level:'n5',
    keys:[['自己[じこ]紹介[しょうかい]','tự giới thiệu'],['出身[しゅっしん]','xuất thân, quê'],['専門[せんもん]','chuyên ngành'],['趣味[しゅみ]','sở thích'],['将来[しょうらい]','tương lai'],['よろしくお願[ねが]いします','mong được giúp đỡ']],
    qs:['お名前[なまえ]は何[なん]ですか。','お国[くに]はどちらですか。','お仕事[しごと]は何[なん]ですか。','趣味[しゅみ]は何[なん]ですか。','どうして日本語[にほんご]を勉強[べんきょう]していますか。'],
    paras:[
      { jp:'はじめまして 。 グエン・ディン・クアン と 申[もう]します 。 クアン と 呼[よ]んで ください 。', vi:'Rất hân hạnh. Tôi tên là Nguyễn Đình Quân. Hãy gọi tôi là Quân.' },
      { jp:'ベトナム の ハノイ から 来[き]ました 。 今[いま] 二十二歳[にじゅうにさい] で 、 ハノイ大学[だいがく] の 三年生[さんねんせい] です 。 専門[せんもん] は 日本語[にほんご] です 。', vi:'Tôi đến từ Hà Nội, Việt Nam. Tôi 22 tuổi, là sinh viên năm ba Đại học Hà Nội. Chuyên ngành của tôi là tiếng Nhật.' },
      { jp:'家族[かぞく] は 五人[ごにん] です 。 父[ちち] と 母[はは] と 兄[あに] と 妹[いもうと] が います 。 父[ちち] は 会社員[かいしゃいん] で 、 母[はは] は 先生[せんせい] です 。', vi:'Gia đình tôi có 5 người: bố, mẹ, anh trai và em gái. Bố là nhân viên công ty, mẹ là giáo viên.' },
      { jp:'趣味[しゅみ] は サッカー と 音楽[おんがく] です 。 週末[しゅうまつ] は 友達[ともだち] と サッカー を したり 、 ギター を 弾[ひ]いたり します 。', vi:'Sở thích của tôi là bóng đá và âm nhạc. Cuối tuần tôi chơi bóng với bạn hoặc chơi ghi-ta.' },
      { jp:'日本語[にほんご] は 二年[にねん] 勉強[べんきょう]して います 。 将来[しょうらい] 日本[にほん] の 会社[かいしゃ] で 働[はたら]きたい です から 。 どうぞ よろしく お願[ねが]いします 。', vi:'Tôi học tiếng Nhật được hai năm. Vì tương lai tôi muốn làm việc ở công ty Nhật. Rất mong được giúp đỡ.' }
    ] },
  { id:'ichinichi', jp:'私の一日', vi:'Một ngày của tôi', level:'n5',
    keys:[['起[お]きる','thức dậy'],['朝[あさ]ご飯[はん]','bữa sáng'],['授業[じゅぎょう]','giờ học'],['アルバイト','làm thêm'],['帰[かえ]る','về nhà'],['寝[ね]る','đi ngủ']],
    qs:['毎朝[まいあさ]何時[なんじ]に起[お]きますか。','朝[あさ]ご飯[はん]に何[なに]を食[た]べますか。','どうやって大学[だいがく]へ行[い]きますか。','午後[ごご]は何[なに]をしますか。','何時[なんじ]に寝[ね]ますか。'],
    paras:[
      { jp:'わたし は 毎朝[まいあさ] 六時[ろくじ] に 起[お]きます 。 顔[かお] を 洗[あら]って 、 朝[あさ]ご飯[はん] に フォー を 食[た]べます 。 ハノイ の 人[ひと] は 朝[あさ] よく 外[そと] で 食[た]べます 。', vi:'Mỗi sáng tôi dậy lúc 6 giờ. Tôi rửa mặt rồi ăn phở cho bữa sáng. Người Hà Nội hay ăn sáng ở ngoài.' },
      { jp:'七時[しちじ] に 家[うち] を 出[で]て 、 バイク で 大学[だいがく] へ 行[い]きます 。 三十分[さんじゅっぷん] ぐらい かかります 。 授業[じゅぎょう] は 八時[はちじ] から 十二時[じゅうにじ] まで です 。', vi:'7 giờ tôi ra khỏi nhà, đi xe máy đến trường. Mất khoảng 30 phút. Giờ học từ 8 đến 12 giờ.' },
      { jp:'昼[ひる] は 食堂[しょくどう] で 友達[ともだち] と 昼[ひる]ご飯[はん] を 食[た]べます 。 午後[ごご] は 図書館[としょかん] で 勉強[べんきょう]したり 、 カフェ で アルバイト を したり します 。', vi:'Buổi trưa tôi ăn ở nhà ăn với bạn. Buổi chiều tôi học ở thư viện hoặc làm thêm ở quán cà phê.' },
      { jp:'七時[しちじ] ごろ 家[うち] へ 帰[かえ]って 、 家族[かぞく] と 晩[ばん]ご飯[はん] を 食[た]べます 。 晩[ばん]ご飯[はん] の 後[あと] で 日本語[にほんご] の ニュース を 聞[き]きます 。 十一時[じゅういちじ] に 寝[ね]ます 。', vi:'Khoảng 7 giờ tôi về nhà, ăn tối với gia đình. Sau bữa tối tôi nghe tin tức tiếng Nhật. 11 giờ tôi đi ngủ.' }
    ] },
  { id:'watashi-no-machi', jp:'私の町 — ハノイ', vi:'Thành phố của tôi — Hà Nội', level:'n5',
    keys:[['首都[しゅと]','thủ đô'],['古[ふる]い 町[まち]','phố cổ'],['湖[みずうみ]','hồ'],['バイク','xe máy'],['料理[りょうり]','món ăn'],['にぎやか','nhộn nhịp']],
    qs:['ハノイはどんな町[まち]ですか。','ハノイで何[なに]が有名[ゆうめい]ですか。','ハノイの料理[りょうり]はどうですか。','ハノイの天気[てんき]はどうですか。'],
    paras:[
      { jp:'ハノイ は ベトナム の 首都[しゅと] です 。 古[ふる]くて 、 にぎやか な 町[まち] です 。 人[ひと] が 多[おお]くて 、 バイク も とても 多[おお]い です 。', vi:'Hà Nội là thủ đô của Việt Nam. Là thành phố cổ và nhộn nhịp. Đông người và rất nhiều xe máy.' },
      { jp:'町[まち] の 中心[ちゅうしん] に ホアンキエム湖[こ] という 湖[みずうみ] が あります 。 朝[あさ] 、 たくさん の 人[ひと] が 湖[みずうみ] の そば で 運動[うんどう] を します 。 湖[みずうみ] の 近[ちか]く に 旧市街[きゅうしがい] が あって 、 三十六[さんじゅうろく] の 古[ふる]い 通[とお]り が あります 。', vi:'Ở trung tâm thành phố có hồ Hoàn Kiếm. Buổi sáng nhiều người tập thể dục quanh hồ. Gần hồ là khu phố cổ với 36 phố cũ.' },
      { jp:'ハノイ の 料理[りょうり] は 安[やす]くて おいしい です 。 フォー や ブンチャー が 有名[ゆうめい] です 。 コーヒー も おいしい です 。 わたし は 卵[たまご] コーヒー が 大好[だいす]き です 。', vi:'Đồ ăn Hà Nội rẻ và ngon. Phở và bún chả nổi tiếng. Cà phê cũng ngon. Tôi rất thích cà phê trứng.' },
      { jp:'夏[なつ] は とても 暑[あつ]くて 、 冬[ふゆ] は 少[すこ]し 寒[さむ]い です 。 一番[いちばん] いい 季節[きせつ] は 秋[あき] だ と 思[おも]います 。 ぜひ ハノイ へ 来[き]て ください 。', vi:'Mùa hè rất nóng, mùa đông hơi lạnh. Tôi nghĩ mùa đẹp nhất là mùa thu. Nhất định hãy đến Hà Nội nhé.' }
    ] },
  { id:'kazoku', jp:'家族', vi:'Gia đình', level:'n5',
    keys:[['家族[かぞく]','gia đình'],['両親[りょうしん]','bố mẹ'],['兄弟[きょうだい]','anh chị em'],['〜歳[さい]','tuổi'],['優[やさ]しい','hiền'],['仲[なか]がいい','thân thiết']],
    qs:['ご家族[かぞく]は何人[なんにん]ですか。','お父[とう]さんはどんな人[ひと]ですか。','兄弟[きょうだい]がいますか。','家族[かぞく]と何[なに]をしますか。'],
    paras:[
      { jp:'わたし の 家族[かぞく] は 五人[ごにん] 家族[かぞく] です 。 父[ちち] 、 母[はは] 、 兄[あに] 、 妹[いもうと] 、 そして わたし です 。 みんな ハノイ に 住[す]んで います 。', vi:'Gia đình tôi có 5 người: bố, mẹ, anh trai, em gái và tôi. Mọi người đều sống ở Hà Nội.' },
      { jp:'父[ちち] は 五十歳[ごじゅっさい] で 、 銀行[ぎんこう] で 働[はたら]いて います 。 まじめ で 、 少[すこ]し 厳[きび]しい 人[ひと] です 。 母[はは] は 小学校[しょうがっこう] の 先生[せんせい] で 、 とても 優[やさ]しい です 。 料理[りょうり] が 上手[じょうず] です 。', vi:'Bố tôi 50 tuổi, làm ở ngân hàng. Bố nghiêm túc và hơi nghiêm khắc. Mẹ là giáo viên tiểu học, rất hiền. Mẹ nấu ăn giỏi.' },
      { jp:'兄[あに] は 二十五歳[にじゅうごさい] で 、 エンジニア です 。 去年[きょねん] 結婚[けっこん]しました 。 妹[いもうと] は 高校生[こうこうせい] で 、 歌[うた] が 好[す]き です 。 わたし たち は 仲[なか] が いい です 。', vi:'Anh trai tôi 25 tuổi, là kỹ sư. Anh kết hôn năm ngoái. Em gái tôi là học sinh cấp ba, thích hát. Chúng tôi rất thân nhau.' },
      { jp:'日曜日[にちようび] に は 家族[かぞく] みんな で 晩[ばん]ご飯[はん] を 食[た]べます 。 テト に は おばあさん の 家[うち] へ 行[い]って 、 バインチュン を 作[つく]ります 。', vi:'Chủ nhật cả nhà cùng ăn tối. Tết thì về nhà bà và gói bánh chưng.' }
    ] },
  { id:'ryugaku-no-mokuteki', jp:'留学の目的と将来の夢', vi:'Mục đích du học và ước mơ tương lai', level:'n4',
    keys:[['留学[りゅうがく]','du học'],['目的[もくてき]','mục đích'],['将来[しょうらい]','tương lai'],['就職[しゅうしょく]','xin việc'],['〜ようになる','trở nên có thể'],['〜つもりです','định …']],
    qs:['どうして日本[にほん]に留学[りゅうがく]しようと思[おも]ったんですか。','日本[にほん]に来[き]て、何[なに]ができるようになりましたか。','将来[しょうらい]、どんな仕事[しごと]をするつもりですか。','日本語[にほんご]の勉強[べんきょう]で何[なに]が一番[いちばん]難[むずか]しいですか。'],
    paras:[
      { jp:'わたし は 去年[きょねん] の 十月[じゅうがつ] に 日本[にほん] へ 来[き]ました 。 ハノイ大学[だいがく] で 二年[にねん] 日本語[にほんご] を 勉強[べんきょう]して 、 もっと 上手[じょうず] に なりたかった ので 、 留学[りゅうがく]する こと に しました 。', vi:'Tôi đến Nhật vào tháng 10 năm ngoái. Tôi đã học tiếng Nhật hai năm ở Đại học Hà Nội và muốn giỏi hơn nữa nên đã quyết định du học.' },
      { jp:'留学[りゅうがく] の 目的[もくてき] は 二[ふた]つ あります 。 一[ひと]つ は 日本語[にほんご] で 自由[じゆう] に 話[はな]せる よう に なる こと 、 もう 一[ひと]つ は 日本[にほん] の 会社[かいしゃ] の 働[はたら]き方[かた] を 知[し]る こと です 。', vi:'Mục đích du học của tôi có hai điều: một là nói được tiếng Nhật một cách tự do, hai là hiểu cách làm việc của công ty Nhật.' },
      { jp:'日本[にほん] に 来[き]た ばかり の 頃[ころ] は 、 電車[でんしゃ] の アナウンス が 全然[ぜんぜん] 聞[き]き取[と]れません でした 。 でも 、 毎日[まいにち] ニュース を 聞[き]く よう に して いた ので 、 だんだん 分[わ]かる よう に なりました 。 今[いま] は アルバイト先[さき] で お客[きゃく]さん と 話[はな]す こと も できます 。', vi:'Hồi mới đến Nhật tôi hoàn toàn không nghe được thông báo trên tàu. Nhưng vì cố gắng nghe tin tức mỗi ngày nên dần dần tôi hiểu được. Bây giờ tôi có thể nói chuyện với khách ở chỗ làm thêm.' },
      { jp:'将来[しょうらい] は 、 ベトナム と 日本[にほん] の 間[あいだ] で 仕事[しごと] を したい と 思[おも]って います 。 卒業[そつぎょう]したら 、 ハノイ に ある 日本[にほん] の 会社[かいしゃ] に 就職[しゅうしょく]する つもり です 。 その ため に 、 来年[らいねん] は N3 に 合格[ごうかく]しよう と 思[おも]って います 。', vi:'Tương lai tôi muốn làm công việc kết nối Việt Nam và Nhật Bản. Tốt nghiệp xong tôi định xin vào công ty Nhật ở Hà Nội. Vì thế năm sau tôi định thi đỗ N3.' }
    ] },
  { id:'arubaito', jp:'アルバイトの経験', vi:'Kinh nghiệm làm thêm', level:'n4',
    keys:[['アルバイト','làm thêm'],['店長[てんちょう]','quản lý cửa hàng'],['お客[きゃく]さん','khách'],['レジ','quầy thu ngân'],['〜てしまう','lỡ …'],['〜ようになる','trở nên …'],['敬語[けいご]','kính ngữ']],
    qs:['今[いま]、どんなアルバイトをしていますか。','どうしてそのアルバイトを選[えら]んだんですか。','アルバイトで何[なに]が大変[たいへん]でしたか。','アルバイトをして、何[なに]を覚[おぼ]えましたか。'],
    paras:[
      { jp:'わたし は 今[いま] 、 駅前[えきまえ] の コンビニ で 週[しゅう] に 三回[さんかい] アルバイト を して います 。 寮[りょう] から 近[ちか]い し 、 時給[じきゅう] も 悪[わる]くない し 、 それに 日本人[にほんじん] と 話[はな]す 機会[きかい] が 多[おお]い ので 、 この 店[みせ] を 選[えら]びました 。', vi:'Hiện tôi làm thêm ở cửa hàng tiện lợi trước ga ba buổi một tuần. Gần ký túc, lương giờ cũng không tệ, hơn nữa có nhiều cơ hội nói chuyện với người Nhật nên tôi chọn cửa hàng này.' },
      { jp:'最初[さいしょ] は レジ の 仕事[しごと] が 難[むずか]しくて 、 お釣[つ]り を 間違[まちが]えて しまった こと も あります 。 お客[きゃく]さん に 「 袋[ふくろ] は いりますか 」 と 聞[き]く の も 、 早口[はやくち] で 言[い]えなくて 大変[たいへん] でした 。', vi:'Lúc đầu công việc thu ngân khó, có lần tôi còn lỡ trả nhầm tiền thừa. Ngay cả hỏi khách «Anh/chị có cần túi không» tôi cũng không nói nhanh được, rất vất vả.' },
      { jp:'店長[てんちょう] は とても 親切[しんせつ] で 、 敬語[けいご] の 使[つか]い方[かた] を 何度[なんど] も 教[おし]えて くださいました 。 おかげ で 、 「 いらっしゃいませ 」 や 「 少々[しょうしょう] お待[ま]ち ください 」 が 自然[しぜん] に 言[い]える よう に なりました 。', vi:'Quản lý rất tốt bụng, đã nhiều lần chỉ cho tôi cách dùng kính ngữ. Nhờ vậy tôi đã nói được tự nhiên các câu «Kính chào quý khách», «Xin đợi một chút».' },
      { jp:'アルバイト は 疲[つか]れます が 、 日本[にほん] の 社会[しゃかい] を 知[し]る のに とても 役[やく] に 立[た]ちます 。 貯[た]めた お金[かね] で 、 春休[はるやす]み に 家族[かぞく] を 日本[にほん] へ 呼[よ]ぼう と 思[おも]って います 。', vi:'Làm thêm tuy mệt nhưng rất có ích để hiểu xã hội Nhật. Với số tiền để dành, tôi định mời gia đình sang Nhật vào kỳ nghỉ xuân.' }
    ] },
  { id:'nihon-no-seikatsu', jp:'日本の生活で驚いたこと', vi:'Những điều bất ngờ trong cuộc sống ở Nhật', level:'n4',
    keys:[['驚[おどろ]く','ngạc nhiên'],['時間[じかん]どおり','đúng giờ'],['ゴミの分別[ぶんべつ]','phân loại rác'],['静[しず]か','yên tĩnh'],['〜そうです','nghe nói / có vẻ'],['〜と言[い]われている','được cho là']],
    qs:['日本[にほん]に来[き]て、何[なに]に一番[いちばん]驚[おどろ]きましたか。','ハノイと東京[とうきょう]はどこが違[ちが]いますか。','日本[にほん]の習慣[しゅうかん]で難[むずか]しいものはありますか。','日本[にほん]の生活[せいかつ]にはもう慣[な]れましたか。'],
    paras:[
      { jp:'日本[にほん] に 来[き]て 一番[いちばん] 驚[おどろ]いた の は 、 電車[でんしゃ] が 時間[じかん] どおり に 来[く]る こと です 。 ハノイ では バス が 三十分[さんじゅっぷん] 遅[おく]れる こと も 珍[めずら]しく ありません 。 東京[とうきょう] では 一分[いっぷん] 遅[おく]れた だけ で 、 アナウンス で 謝[あやま]られます 。', vi:'Điều làm tôi bất ngờ nhất khi đến Nhật là tàu đến đúng giờ. Ở Hà Nội xe buýt trễ 30 phút không phải chuyện hiếm. Ở Tokyo chỉ trễ một phút thôi là đã có thông báo xin lỗi.' },
      { jp:'ゴミ の 分別[ぶんべつ] も 大変[たいへん] でした 。 燃[も]える ゴミ 、 プラスチック 、 びん 、 缶[かん] を 曜日[ようび] ごと に 分[わ]けて 出[だ]さなければ なりません 。 最初[さいしょ] は 間違[まちが]えて 、 管理人[かんりにん]さん に 注意[ちゅうい]されて しまいました 。', vi:'Phân loại rác cũng vất vả. Rác cháy được, nhựa, chai, lon phải chia theo từng thứ trong tuần để đổ. Lúc đầu tôi làm sai và bị bác quản lý nhắc nhở.' },
      { jp:'それから 、 電車[でんしゃ] の 中[なか] が とても 静[しず]か な こと に も 驚[おどろ]きました 。 誰[だれ] も 電話[でんわ] で 話[はな]しません 。 日本人[にほんじん] は 周[まわ]り の 人[ひと] に 迷惑[めいわく] を かけない よう に して いる の だ と 思[おも]います 。', vi:'Rồi tôi cũng ngạc nhiên vì trong tàu rất yên tĩnh. Không ai nói chuyện điện thoại. Tôi nghĩ người Nhật luôn cố gắng không làm phiền người xung quanh.' },
      { jp:'今[いま] は もう だいぶ 慣[な]れました が 、 ハノイ の にぎやか な 朝[あさ] が 恋[こい]しく なる こと も あります 。 日本[にほん] は 安全[あんぜん] で 便利[べんり] な 国[くに] だ と 言[い]われて います が 、 わたし に とって は 、 少[すこ]し 静[しず]か すぎる 国[くに] かも しれません 。', vi:'Giờ tôi đã khá quen, nhưng có lúc nhớ buổi sáng nhộn nhịp ở Hà Nội. Nhật được cho là đất nước an toàn và tiện lợi, nhưng với tôi có lẽ hơi yên tĩnh quá.' }
    ] },
  { id:'tet', jp:'ベトナムのテト', vi:'Tết Việt Nam', level:'n4',
    keys:[['旧正月[きゅうしょうがつ]','Tết âm lịch'],['お年玉[としだま]','tiền mừng tuổi'],['先祖[せんぞ]','tổ tiên'],['飾[かざ]る','trang trí'],['〜てあります','đã được … sẵn'],['〜と言[い]われている','được cho là']],
    qs:['テトはいつですか。','テトの前[まえ]に何[なに]を準備[じゅんび]しますか。','テトにはどんな料理[りょうり]を食[た]べますか。','日本[にほん]のお正月[しょうがつ]とどこが違[ちが]いますか。'],
    paras:[
      { jp:'テト は ベトナム の 旧正月[きゅうしょうがつ] で 、 一年[いちねん] で 一番[いちばん] 大切[たいせつ] な 行事[ぎょうじ] です 。 毎年[まいとし] 一月[いちがつ] の 終[お]わり か 二月[にがつ] の 初[はじ]め に あって 、 一週間[いっしゅうかん] ぐらい 休[やす]み に なります 。', vi:'Tết là năm mới âm lịch của Việt Nam, là sự kiện quan trọng nhất trong năm. Mỗi năm Tết vào cuối tháng Một hoặc đầu tháng Hai, được nghỉ khoảng một tuần.' },
      { jp:'テト の 前[まえ] に 、 家族[かぞく] みんな で 家[いえ] を 掃除[そうじ]して 、 桃[もも] の 花[はな] や 金柑[きんかん] の 木[き] を 飾[かざ]ります 。 台所[だいどころ] に は バインチュン という もち米[ごめ] の 料理[りょうり] が 用意[ようい]して あります 。 祖母[そぼ] が 作[つく]り方[かた] を 教[おし]えて くれた ので 、 わたし も 作[つく]れます 。', vi:'Trước Tết cả nhà cùng dọn nhà, trang trí hoa đào và cây quất. Trong bếp đã chuẩn bị sẵn bánh chưng — món làm từ gạo nếp. Bà đã dạy cách gói nên tôi cũng gói được.' },
      { jp:'大晦日[おおみそか] の 夜[よる] は 家族[かぞく] で 先祖[せんぞ] に お祈[いの]り を して 、 花火[はなび] を 見[み]ます 。 元日[がんじつ] に は 親戚[しんせき] の 家[いえ] を 回[まわ]って 、 子[こ]ども は お年玉[としだま] を もらいます 。 最初[さいしょ] に 家[いえ] に 来[く]る 人[ひと] が 一年[いちねん] の 運[うん] を 決[き]める と 言[い]われて います 。', vi:'Đêm giao thừa cả nhà cúng tổ tiên rồi xem pháo hoa. Mùng Một đi chúc Tết họ hàng, trẻ con được mừng tuổi. Người ta nói người xông đất đầu tiên quyết định vận may cả năm.' },
      { jp:'日本[にほん] の お正月[しょうがつ] と 似[に]て いる ところ も 多[おお]い です が 、 ベトナム では 花[はな] を 飾[かざ]る の が 特徴[とくちょう] です 。 今年[ことし] は 日本[にほん] に いる ので 国[くに] へ 帰[かえ]れません が 、 寮[りょう] の 友達[ともだち] に バインチュン を 作[つく]って あげよう と 思[おも]って います 。', vi:'Có nhiều điểm giống Tết Nhật, nhưng ở Việt Nam đặc trưng là trang trí hoa. Năm nay tôi ở Nhật nên không về nước được, nhưng tôi định gói bánh chưng cho bạn ở ký túc.' }
    ] },
  { id:'nihon-no-kaisha', jp:'日本の会社で働いて感じたこと', vi:'Điều cảm nhận khi làm việc ở công ty Nhật', level:'n3',
    keys:[['職場[しょくば]','nơi làm việc'],['報告[ほうこく]・連絡[れんらく]・相談[そうだん]','báo cáo – liên lạc – bàn bạc'],['責任[せきにん]','trách nhiệm'],['〜ことになっている','theo quy định là'],['〜わけではない','không hẳn là'],['〜にとって','đối với']],
    qs:['日本[にほん]の会社[かいしゃ]で一番[いちばん]驚[おどろ]いたことは何[なん]ですか。','ベトナムの会社[かいしゃ]と比[くら]べて、どこが違[ちが]いますか。','日本[にほん]の働[はたら]き方[かた]のいい点[てん]と悪[わる]い点[てん]は何[なん]ですか。','将来[しょうらい]、どんな職場[しょくば]で働[はたら]きたいですか。'],
    paras:[
      { jp:'わたし は 東京[とうきょう] の 商社[しょうしゃ] で 三か月[さんかげつ] インターン を 経験[けいけん]しました 。 最初[さいしょ] に 驚[おどろ]いた の は 、 朝[あさ] の 挨拶[あいさつ] から 会議[かいぎ] の 進[すす]め方[かた] まで 、 すべて が 細[こま]かく 決[き]まって いる こと です 。 例[たと]えば 、 メール は 必[かなら]ず 上司[じょうし] に CC を 入[い]れる こと に なって いました 。', vi:'Tôi đã thực tập ba tháng ở một công ty thương mại tại Tokyo. Điều đầu tiên làm tôi ngạc nhiên là mọi thứ từ chào hỏi buổi sáng đến cách tiến hành họp đều được quy định tỉ mỉ. Ví dụ, theo quy định email luôn phải CC cho cấp trên.' },
      { jp:'日本[にほん] の 職場[しょくば] では 「 報告[ほうこく] ・ 連絡[れんらく] ・ 相談[そうだん] 」 が 何[なに] より 大切[たいせつ] だ と 言[い]われて います 。 小[ちい]さな こと でも 報告[ほうこく]しない と 、 後[あと] で 大[おお]きな 問題[もんだい] に なり かねません 。 最初[さいしょ] は 面倒[めんどう] だ と 思[おも]いました が 、 慣[な]れる に つれて 、 チーム 全体[ぜんたい] の 効率[こうりつ] が 上[あ]がる 仕組[しく]み だ と 分[わ]かって きました 。', vi:'Ở nơi làm việc Nhật, người ta nói «báo cáo – liên lạc – bàn bạc» là quan trọng hơn hết. Việc nhỏ mà không báo cáo có thể thành vấn đề lớn về sau. Lúc đầu tôi thấy phiền, nhưng theo đà quen dần, tôi hiểu ra đó là cơ chế giúp tăng hiệu suất của cả nhóm.' },
      { jp:'ベトナム の 会社[かいしゃ] と 比[くら]べる と 、 日本[にほん] は 決[き]める まで に 時間[じかん] が かかる 反面[はんめん] 、 一度[いちど] 決[き]まれば 計画[けいかく] どおり に 進[すす]みます 。 ただし 、 残業[ざんぎょう] が 多[おお]い の は 事実[じじつ] です 。 とはいえ 、 すべて の 会社[かいしゃ] が そう だ という わけ では なく 、 最近[さいきん] は 働[はたら]き方[かた] を 見直[みなお]す 会社[かいしゃ] も 増[ふ]えて いる そう です 。', vi:'So với công ty Việt Nam, ở Nhật mất nhiều thời gian để quyết định, nhưng ngược lại một khi đã quyết thì tiến hành đúng kế hoạch. Có điều, làm thêm giờ nhiều là sự thật. Dù vậy, không phải công ty nào cũng thế; nghe nói gần đây ngày càng nhiều công ty xem lại cách làm việc.' },
      { jp:'わたし に とって 一番[いちばん] の 収穫[しゅうかく] は 、 責任[せきにん] を 持[も]って 仕事[しごと] を やり遂[と]げる 姿勢[しせい] を 学[まな]べた こと です 。 将来[しょうらい] は 、 日本[にほん] の 良[よ]い ところ と ベトナム の 柔軟[じゅうなん]さ を 合[あ]わせた 職場[しょくば] を 作[つく]りたい と 思[おも]って います 。', vi:'Đối với tôi, thu hoạch lớn nhất là học được thái độ làm việc có trách nhiệm đến cùng. Tương lai tôi muốn tạo ra một nơi làm việc kết hợp điểm tốt của Nhật với sự linh hoạt của Việt Nam.' }
    ] },
  { id:'kankyo-mondai', jp:'環境問題について', vi:'Về vấn đề môi trường', level:'n3',
    keys:[['環境[かんきょう]','môi trường'],['大気[たいき]汚染[おせん]','ô nhiễm không khí'],['ゴミの分別[ぶんべつ]','phân loại rác'],['〜一方だ','ngày càng (một chiều)'],['〜べきだ','nên'],['〜さえ〜ば','chỉ cần … là']],
    qs:['あなたの町[まち]にはどんな環境[かんきょう]問題[もんだい]がありますか。','日本[にほん]と比[くら]べて、ベトナムのゴミの出[だ]し方[かた]はどう違[ちが]いますか。','環境[かんきょう]のために、個人[こじん]ができることは何[なん]ですか。','政府[せいふ]や企業[きぎょう]は何[なに]をすべきだと思[おも]いますか。'],
    paras:[
      { jp:'ハノイ が 抱[かか]えて いる 最[もっと]も 深刻[しんこく] な 環境[かんきょう] 問題[もんだい] は 、 大気[たいき] 汚染[おせん] だ と 思[おも]います 。 バイク や 車[くるま] の 数[かず] は 増[ふ]える 一方[いっぽう] で 、 冬[ふゆ] に なる と 空[そら] が 灰色[はいいろ] に 見[み]える 日[ひ] が 続[つづ]きます 。 マスク なし で は 外[そと] を 歩[ある]けない ほど です 。', vi:'Vấn đề môi trường nghiêm trọng nhất Hà Nội đang đối mặt, theo tôi, là ô nhiễm không khí. Số xe máy và ô tô cứ tăng mãi, đến mùa đông có những ngày liên tiếp bầu trời trông xám xịt. Đến mức không đeo khẩu trang thì không đi bộ ngoài đường được.' },
      { jp:'日本[にほん] に 来[き]て 感心[かんしん]した の は 、 ゴミ の 分別[ぶんべつ] が 徹底[てってい]して いる こと です 。 燃[も]える ゴミ 、 プラスチック 、 びん 、 缶[かん] を 曜日[ようび] ごと に 分[わ]けて 出[だ]す こと に なって いて 、 子[こ]ども でも 当然[とうぜん] の よう に 守[まも]って います 。 ベトナム でも 分別[ぶんべつ] を 始[はじ]めた 地域[ちいき] は あります が 、 まだ 習慣[しゅうかん] に なって いる と は 言[い]えません 。', vi:'Đến Nhật tôi khâm phục vì việc phân loại rác được thực hiện triệt để. Rác cháy được, nhựa, chai, lon phải chia theo ngày trong tuần, và ngay cả trẻ em cũng tuân thủ như lẽ đương nhiên. Ở Việt Nam cũng có khu vực bắt đầu phân loại, nhưng chưa thể nói là đã thành thói quen.' },
      { jp:'環境[かんきょう] 問題[もんだい] は 、 政府[せいふ] に 任[まか]せて おけば 解決[かいけつ]する という もの では ありません 。 一人一人[ひとりひとり] が 少[すこ]し ずつ 行動[こうどう]する こと こそ 大切[たいせつ] です 。 例[たと]えば 、 買[か]い物[もの] に エコバッグ を 持[も]って 行[い]く 、 近[ちか]い 所[ところ] なら 歩[ある]く 、 電気[でんき] を こまめ に 消[け]す 。 意識[いしき] さえ 変[か]われば 、 誰[だれ] でも 今日[きょう] から 始[はじ]められます 。', vi:'Vấn đề môi trường không phải chuyện cứ giao cho chính phủ là giải quyết được. Chính việc mỗi người hành động từng chút một mới quan trọng. Chẳng hạn mang túi thân thiện môi trường khi đi mua sắm, gần thì đi bộ, tắt điện thường xuyên. Chỉ cần ý thức thay đổi, ai cũng có thể bắt đầu từ hôm nay.' },
      { jp:'一方[いっぽう] で 、 企業[きぎょう] や 政府[せいふ] に は もっと 大[おお]きな 責任[せきにん] が あります 。 公共[こうきょう] 交通[こうつう] を 整備[せいび]し 、 工場[こうじょう] の 排出[はいしゅつ] を 厳[きび]しく 規制[きせい]す べき です 。 ハノイ の 地下鉄[ちかてつ] が 完成[かんせい]すれば 、 バイク の 数[かず] も 減[へ]る に 違[ちが]いない と 期待[きたい]して います 。', vi:'Mặt khác, doanh nghiệp và chính phủ có trách nhiệm lớn hơn. Nên hoàn thiện giao thông công cộng và quy định nghiêm ngặt khí thải nhà máy. Tôi kỳ vọng khi tàu điện ngầm Hà Nội hoàn thành, số xe máy chắc chắn sẽ giảm.' }
    ] },
  { id:'shigoto-to-seikatsu', jp:'仕事と生活のバランス', vi:'Cân bằng công việc và cuộc sống', level:'n3',
    keys:[['ワークライフバランス','cân bằng công việc – cuộc sống'],['残業[ざんぎょう]','làm thêm giờ'],['有給休暇[ゆうきゅうきゅうか]','nghỉ phép có lương'],['〜がち','hay bị'],['〜ことはない','không cần phải'],['〜からこそ','chính vì']],
    qs:['一日[いちにち]にどのぐらい働[はたら]いていますか。','仕事[しごと]と生活[せいかつ]、どちらを大切[たいせつ]にしたいですか。','ストレスがたまったとき、どうやって解消[かいしょう]しますか。','理想[りそう]的[てき]な働[はたら]き方[かた]はどんなものですか。'],
    paras:[
      { jp:'日本[にほん] で 働[はたら]き 始[はじ]めて 、 わたし の 生活[せいかつ] は 仕事[しごと] 中心[ちゅうしん] に なり がち でした 。 平日[へいじつ] は 九時[くじ] から 七時[しちじ] まで 働[はたら]き 、 帰[かえ]って から も 資料[しりょう] を 読[よ]む 日[ひ] が 続[つづ]きました 。 気[き] が つく と 、 友達[ともだち] と 会[あ]う 時間[じかん] も 、 運動[うんどう]する 時間[じかん] も なくなって いました 。', vi:'Bắt đầu làm việc ở Nhật, cuộc sống của tôi dễ trở nên chỉ xoay quanh công việc. Ngày thường làm từ 9 giờ đến 7 giờ, về nhà vẫn đọc tài liệu, ngày này qua ngày khác. Đến khi nhận ra thì thời gian gặp bạn bè lẫn thời gian vận động đều đã biến mất.' },
      { jp:'そんな とき 、 先輩[せんぱい] に 「 焦[あせ]る こと は ない 。 長[なが]く 働[はたら]く ため に は 休[やす]む こと も 仕事[しごと] の うち だ 」 と 言[い]われました 。 その 言葉[ことば] を きっかけ に 、 週末[しゅうまつ] は 仕事[しごと] の メール を 見[み]ない こと に しました 。 忙[いそが]しい から こそ 、 意識[いしき]して 休[やす]む 必要[ひつよう] が ある の だ と 思[おも]います 。', vi:'Khi ấy, đàn anh bảo tôi: «Không cần sốt ruột. Để làm việc lâu dài thì nghỉ ngơi cũng là một phần công việc». Từ câu nói đó, tôi quyết định cuối tuần không xem email công việc. Tôi nghĩ chính vì bận nên mới cần nghỉ ngơi một cách có ý thức.' },
      { jp:'ストレス が たまった とき は 、 カメラ を 持[も]って 町[まち] を 歩[ある]きます 。 写真[しゃしん] を 撮[と]る こと に 夢中[むちゅう] に なって いる うち に 、 仕事[しごと] の 悩[なや]み を 忘[わす]れられる から です 。 それ に 、 週[しゅう] に 二回[にかい] は ジム に 通[かよ]う よう に して います 。 体[からだ] を 動[うご]かせば 動[うご]かす ほど 、 頭[あたま] も すっきり します 。', vi:'Khi căng thẳng tích tụ, tôi cầm máy ảnh đi bộ khắp phố. Trong lúc mải mê chụp ảnh, tôi quên được những lo lắng công việc. Ngoài ra tôi cố gắng đi phòng gym hai lần một tuần. Càng vận động cơ thể, đầu óc càng thoải mái.' },
      { jp:'理想[りそう] の 働[はたら]き方[かた] は 、 時間[じかん] の 長[なが]さ で は なく 成果[せいか] で 評価[ひょうか]される こと だ と 思[おも]います 。 ベトナム で は 家族[かぞく] と 過[す]ごす 時間[じかん] を 何[なに] より 大切[たいせつ] に します 。 日本[にほん] の 効率[こうりつ] の 良[よ]さ と ベトナム の ゆとり 、 その 両方[りょうほう] を 持[も]った 生活[せいかつ] を 目指[めざ]したい です 。', vi:'Cách làm việc lý tưởng, theo tôi, là được đánh giá bằng thành quả chứ không bằng độ dài thời gian. Ở Việt Nam, thời gian bên gia đình được coi trọng hơn hết. Tôi muốn hướng tới cuộc sống có cả tính hiệu quả của Nhật lẫn sự thư thái của Việt Nam.' }
    ] },
  { id:'betonamu-no-miryoku', jp:'ベトナムの魅力を紹介する', vi:'Giới thiệu sức hút của Việt Nam', level:'n3',
    keys:[['魅力[みりょく]','sức hút'],['世界[せかい]遺産[いさん]','di sản thế giới'],['多様[たよう]','đa dạng'],['〜だけでなく〜も','không chỉ … mà cả'],['〜に限[かぎ]らず','không chỉ'],['〜と言[い]われている','được cho là']],
    qs:['ベトナムのどこをおすすめしますか。','ベトナム料理[りょうり]の特徴[とくちょう]は何[なん]ですか。','日本人[にほんじん]観光客[かんこうきゃく]が気[き]をつけることはありますか。','日本[にほん]とベトナムの似[に]ているところはどこですか。'],
    paras:[
      { jp:'ベトナム は 南北[なんぼく] に 長[なが]い 国[くに] で 、 北[きた] の ハノイ から 南[みなみ] の ホーチミン まで 千七百[せんななひゃく] キロ 以上[いじょう] あります 。 その ため 、 気候[きこう] も 文化[ぶんか] も 地域[ちいき] に よって 大[おお]きく 違[ちが]います 。 ハノイ に は 四季[しき] が あります が 、 ホーチミン は 一年中[いちねんじゅう] 夏[なつ] の よう な 気候[きこう] です 。', vi:'Việt Nam là đất nước trải dài từ Bắc xuống Nam, từ Hà Nội ở phía Bắc đến TP. Hồ Chí Minh ở phía Nam hơn 1.700 km. Vì thế khí hậu lẫn văn hoá khác nhau nhiều tuỳ vùng. Hà Nội có bốn mùa, còn TP. Hồ Chí Minh khí hậu như mùa hè quanh năm.' },
      { jp:'観光[かんこう] なら 、 ハロン湾[わん] や ホイアン の 旧市街[きゅうしがい] など の 世界[せかい] 遺産[いさん] だけ で なく 、 北部[ほくぶ] の 山岳[さんがく] 地帯[ちたい] も おすすめ です 。 サパ で は 少数[しょうすう] 民族[みんぞく] の 生活[せいかつ] に 触[ふ]れる こと が でき 、 棚田[たなだ] の 景色[けしき] は 「 世界[せかい] で 最[もっと]も 美[うつく]しい 」 と 言[い]われて います 。', vi:'Nếu đi du lịch, không chỉ các di sản thế giới như vịnh Hạ Long hay phố cổ Hội An, mà vùng núi phía Bắc cũng rất đáng giới thiệu. Ở Sa Pa có thể tiếp xúc với đời sống các dân tộc thiểu số, và cảnh ruộng bậc thang được cho là «đẹp nhất thế giới».' },
      { jp:'ベトナム 料理[りょうり] の 特徴[とくちょう] は 、 新鮮[しんせん] な 野菜[やさい] と ハーブ を たっぷり 使[つか]い 、 油[あぶら] が 少[すく]ない こと です 。 フォー や 生春巻[なまはるま]き に 限[かぎ]らず 、 バインミー や ブンチャー など 、 屋台[やたい] で 手軽[てがる] に 食[た]べられる 料理[りょうり] が 数[かぞ]え きれない ほど あります 。 健康的[けんこうてき] な 上[うえ] に 安[やす]い ので 、 日本人[にほんじん] に も 人気[にんき] が ある わけ です 。', vi:'Đặc trưng của ẩm thực Việt Nam là dùng nhiều rau tươi và rau thơm, ít dầu mỡ. Không chỉ phở hay gỏi cuốn, còn có bánh mì, bún chả… vô số món ăn dễ dàng thưởng thức ở quán vỉa hè. Vừa tốt cho sức khoẻ lại rẻ, thảo nào được người Nhật ưa thích.' },
      { jp:'日本人[にほんじん] の 観光客[かんこうきゃく] が 驚[おどろ]く の は 、 道路[どうろ] を 渡[わた]る 難[むずか]しさ かも しれません 。 コツ は 、 慌[あわ]て ず に ゆっくり 一定[いってい] の 速[はや]さ で 歩[ある]く こと です 。 バイク の 方[ほう] が 避[よ]けて くれます 。 日本[にほん] と 同[おな]じ よう に 、 ベトナム人[じん] も 目上[めうえ] の 人[ひと] を 敬[うやま]い 、 家族[かぞく] を 大切[たいせつ] に します から 、 きっと 親[した]しみ を 感[かん]じて いただける はず です 。', vi:'Điều khiến du khách Nhật ngạc nhiên có lẽ là độ khó khi sang đường. Bí quyết là không cuống, đi chậm với tốc độ đều. Xe máy sẽ tránh mình. Giống như ở Nhật, người Việt cũng kính trọng người trên và coi trọng gia đình, nên chắc chắn quý vị sẽ cảm thấy thân thuộc.' }
    ] },
  { id:'purezen-shijou', jp:'プレゼンテーション — ベトナム市場の魅力', vi:'Thuyết trình — sức hút của thị trường Việt Nam', level:'n2',
    keys:[['〜において','tại (trang trọng)'],['〜に伴って','kéo theo'],['〜を中心に','lấy làm trung tâm'],['市場[しじょう]規模[きぼ]','quy mô thị trường'],['購買力[こうばいりょく]','sức mua'],['〜にほかならない','không gì khác chính là']],
    qs:['ベトナム市場[しじょう]の特徴[とくちょう]は何[なん]ですか。','日本[にほん]企業[きぎょう]にとってどんなチャンスがありますか。','進出[しんしゅつ]の際[さい]に注意[ちゅうい]すべき点[てん]は何[なん]ですか。','今後[こんご]五年[ごねん]の見通[みとお]しをどう考[かんが]えますか。'],
    paras:[
      { jp:'本日[ほんじつ] は お忙[いそが]しい 中[なか] お集[あつ]まり いただき 、 誠[まこと] に ありがとう ございます 。 ハノイ 支店[してん] の グエン・ディン・クアン と 申[もう]します 。 本日[ほんじつ] は 、 ベトナム 市場[しじょう] の 現状[げんじょう] と 当社[とうしゃ] の 今後[こんご] の 方針[ほうしん] に ついて 、 三点[さんてん] に 絞[しぼ]って ご説明[せつめい] させて いただきます 。', vi:'Hôm nay cảm ơn quý vị đã dành thời gian đến dự dù rất bận. Tôi là Nguyễn Đình Quân, chi nhánh Hà Nội. Hôm nay tôi xin phép trình bày, gói gọn trong ba điểm, về hiện trạng thị trường Việt Nam và phương châm sắp tới của công ty.' },
      { jp:'まず 、 市場[しじょう] の 規模[きぼ] です 。 ベトナム に おいて 、 中間層[ちゅうかんそう] の 人口[じんこう] は 過去[かこ] 十年[じゅうねん] で 二倍[にばい] に なりました 。 所得[しょとく] の 増加[ぞうか] に 伴[ともな]って 購買力[こうばいりょく] も 高[たか]まり 、 品質[ひんしつ] を 重視[じゅうし]する 消費者[しょうひしゃ] が 増[ふ]え つつ あります 。 これ は 日本[にほん] 製品[せいひん] に とって 追[お]い風[かぜ] に ほか なりません 。', vi:'Thứ nhất là quy mô thị trường. Tại Việt Nam, dân số tầng lớp trung lưu đã tăng gấp đôi trong mười năm qua. Cùng với thu nhập tăng, sức mua cũng lên và người tiêu dùng coi trọng chất lượng đang dần tăng. Đây không gì khác chính là gió thuận cho hàng Nhật.' },
      { jp:'次[つぎ] に 、 当社[とうしゃ] の 戦略[せんりゃく] です 。 ハノイ と ホーチミン を 中心[ちゅうしん] に 販売[はんばい] 網[もう] を 築[きず]く 一方[いっぽう] で 、 地方[ちほう] 都市[とし] へ の 展開[てんかい] も 視野[しや] に 入[い]れて います 。 ただし 、 地域[ちいき] ごと に 所得[しょとく] 水準[すいじゅん] が 大[おお]きく 異[こと]なる ため 、 価格[かかく] と 包装[ほうそう] を 地域[ちいき] に 応[おう]じて 変[か]える 必要[ひつよう] が あります 。', vi:'Thứ hai là chiến lược của công ty. Một mặt xây dựng mạng lưới bán hàng lấy Hà Nội và TP. Hồ Chí Minh làm trung tâm, mặt khác chúng tôi cũng đưa việc mở rộng ra các đô thị địa phương vào tầm nhìn. Có điều, vì mức thu nhập khác nhau nhiều theo từng vùng nên cần thay đổi giá và bao bì tuỳ theo vùng.' },
      { jp:'最後[さいご] に 、 注意[ちゅうい]す べき 点[てん] です 。 ベトナム は 変化[へんか] の 速[はや]い 国[くに] です 。 昨年[さくねん] の データ に 基[もと]づいて 判断[はんだん]する だけ では 、 誤[あやま]り かねません 。 現地[げんち] スタッフ の 声[こえ] を 通[つう]じて 、 市場[しじょう] の 変化[へんか] を 常[つね] に 把握[はあく]して いく こと が 、 成功[せいこう] へ の 鍵[かぎ] だ と 考[かんが]えます 。 ご清聴[せいちょう] ありがとう ございました 。', vi:'Cuối cùng là điểm cần lưu ý. Việt Nam là đất nước thay đổi nhanh. Chỉ phán đoán dựa trên dữ liệu năm ngoái thì có nguy cơ sai lầm. Tôi cho rằng luôn nắm bắt biến động thị trường thông qua tiếng nói của nhân viên địa phương chính là chìa khoá thành công. Cảm ơn quý vị đã lắng nghe.' }
    ] },
  { id:'kyouiku-to-shigoto', jp:'教育と仕事 — 意見を述べる', vi:'Giáo dục và công việc — nêu ý kiến', level:'n2',
    keys:[['〜べきだ','nên'],['〜ものの','tuy … nhưng'],['〜に限[かぎ]らず','không chỉ'],['学歴[がくれき]','học vấn'],['即戦力[そくせんりょく]','người làm được việc ngay'],['生涯[しょうがい]学習[がくしゅう]','học tập suốt đời']],
    qs:['大学[だいがく]で学[まな]んだことは仕事[しごと]に役立[やくだ]っていますか。','企業[きぎょう]は新人[しんじん]をどう育[そだ]てるべきだと思[おも]いますか。','学歴[がくれき]は採用[さいよう]においてどのぐらい重要[じゅうよう]ですか。','社会人[しゃかいじん]になっても勉強[べんきょう]を続[つづ]けるべきですか。'],
    paras:[
      { jp:'「 大学[だいがく] で 学[まな]んだ こと は 仕事[しごと] で 役[やく] に 立[た]たない 」 と よく 言[い]われます 。 確[たし]か に 、 わたし が 大学[だいがく] で 学[まな]んだ 日本語[にほんご] は 、 職場[しょくば] の 日本語[にほんご] と は 違[ちが]って いました 。 と は いえ 、 基礎[きそ] が なければ 応用[おうよう] も できません 。 大学[だいがく] は 「 学[まな]び方[かた] 」 を 学[まな]ぶ 場所[ばしょ] だった と 、 今[いま] では 思[おも]って います 。', vi:'Người ta hay nói «Điều học ở đại học không có ích cho công việc». Quả thật, tiếng Nhật tôi học ở đại học khác với tiếng Nhật nơi công sở. Dù vậy, không có nền tảng thì không thể ứng dụng. Giờ tôi nghĩ đại học là nơi học «cách học».' },
      { jp:'企業[きぎょう] の 側[がわ] に も 責任[せきにん] が あります 。 即戦力[そくせんりょく] ばかり を 求[もと]める あまり 、 新人[しんじん] を 育[そだ]てる 余裕[よゆう] を 失[うしな]って いる 会社[かいしゃ] が 少[すく]なく ありません 。 しかし 、 人[ひと] は 育[そだ]てて はじめて 戦力[せんりょく] に なる もの です 。 日本[にほん] の 会社[かいしゃ] の 研修[けんしゅう] 制度[せいど] は 、 ベトナム 企業[きぎょう] が 学[まな]ぶ べき 点[てん] だ と 思[おも]います 。', vi:'Phía doanh nghiệp cũng có trách nhiệm. Vì quá chỉ đòi hỏi người làm được ngay, không ít công ty đã mất đi sự thong thả để đào tạo người mới. Nhưng con người vốn dĩ phải được đào tạo mới thành lực lượng. Tôi nghĩ chế độ đào tạo của công ty Nhật là điểm doanh nghiệp Việt Nam nên học.' },
      { jp:'学歴[がくれき] に ついて は 、 参考[さんこう] に は なる もの の 、 それ だけ で 人[ひと] を 判断[はんだん]する べき では ありません 。 当社[とうしゃ] では 、 学歴[がくれき] や 国籍[こくせき] を 問[と]わず 、 意欲[いよく] と 学[まな]び 続[つづ]ける 姿勢[しせい] を 重視[じゅうし]して います 。 実際[じっさい] 、 高校[こうこう] 卒業[そつぎょう] 後[ご] に 独学[どくがく] で 日本語[にほんご] を 身[み] に つけ 、 今[いま] は チーム を まとめて いる スタッフ も います 。', vi:'Về học vấn, tuy có thể tham khảo nhưng không nên chỉ dựa vào đó để đánh giá con người. Ở công ty tôi, bất kể học vấn hay quốc tịch, chúng tôi coi trọng nhiệt huyết và thái độ học hỏi không ngừng. Thực tế, có nhân viên sau khi tốt nghiệp phổ thông đã tự học tiếng Nhật và hiện đang điều hành cả một nhóm.' },
      { jp:'社会人[しゃかいじん] に なって から こそ 、 学[まな]び は 大切[たいせつ] です 。 技術[ぎじゅつ] も 市場[しじょう] も 変[か]わり 続[つづ]ける 以上[いじょう] 、 学[まな]ぶ こと を やめた 瞬間[しゅんかん] に 取[と]り残[のこ]されて しまいます 。 わたし 自身[じしん] 、 仕事[しごと] の 傍[かたわ]ら 、 N1 を 目指[めざ]して 勉強[べんきょう] を 続[つづ]けて います 。 生涯[しょうがい] 学習[がくしゅう] と いう 言葉[ことば] は 、 決[けっ]して 大[おお]げさ では ない と 思[おも]います 。', vi:'Chính khi đã đi làm, việc học mới quan trọng. Một khi công nghệ và thị trường không ngừng thay đổi, khoảnh khắc ngừng học là bị bỏ lại phía sau. Bản thân tôi, bên cạnh công việc, vẫn tiếp tục học hướng tới N1. Tôi nghĩ cụm từ «học tập suốt đời» hoàn toàn không phải là nói quá.' }
    ] },
  { id:'gijutsu-to-shakai', jp:'技術と社会 — AI時代の働き方', vi:'Công nghệ và xã hội — cách làm việc thời AI', level:'n2',
    keys:[['人工[じんこう]知能[ちのう]','trí tuệ nhân tạo'],['〜つつある','đang dần'],['〜一方[いっぽう]で','mặt khác'],['〜どころか','đừng nói là'],['効率化[こうりつか]','tăng hiệu suất'],['〜ざるを得[え]ない','buộc phải']],
    qs:['AIは仕事[しごと]を奪[うば]うと思[おも]いますか。','あなたの職場[しょくば]でAIはどう使[つか]われていますか。','AIに任[まか]せてはいけない仕事[しごと]は何[なん]ですか。','これからの社会人[しゃかいじん]に必要[ひつよう]な能力[のうりょく]は何[なん]ですか。'],
    paras:[
      { jp:'人工[じんこう] 知能[ちのう] が 仕事[しごと] を 奪[うば]う と いう 議論[ぎろん] が 盛[さか]ん です が 、 わたし の 職場[しょくば] では 、 奪[うば]う どころ か 、 むしろ 仕事[しごと] を 助[たす]けて くれて います 。 翻訳[ほんやく] の 下書[したが]き や 報告書[ほうこくしょ] の 要約[ようやく] は AI に 任[まか]せ 、 人間[にんげん] は 確認[かくにん] と 判断[はんだん] に 集中[しゅうちゅう]する 。 その 結果[けっか] 、 残業[ざんぎょう] は 三割[さんわり] 減[へ]りました 。', vi:'Tranh luận rằng AI cướp việc làm đang sôi nổi, nhưng ở nơi tôi làm, đừng nói là cướp, nó ngược lại đang hỗ trợ công việc. Bản nháp dịch và tóm tắt báo cáo giao cho AI, con người tập trung vào kiểm tra và phán đoán. Kết quả là làm thêm giờ giảm 30%.' },
      { jp:'一方[いっぽう] で 、 課題[かだい] も 明[あき]らか に なり つつ あります 。 AI の 翻訳[ほんやく] は 一見[いっけん] 自然[しぜん] に 見[み]えて も 、 数字[すうじ] や 固有[こゆう] 名詞[めいし] を 間違[まちが]える こと が あり 、 そのまま 使[つか]えば 大[おお]きな 損失[そんしつ] に つながり かねません 。 便利[べんり] で ある 反面[はんめん] 、 人間[にんげん] の 目[め] に よる 確認[かくにん] を 省[はぶ]く わけ に は いかない のです 。', vi:'Mặt khác, các vấn đề cũng đang dần lộ rõ. Bản dịch của AI trông có vẻ tự nhiên nhưng có khi sai số liệu hay tên riêng, dùng nguyên có nguy cơ dẫn đến tổn thất lớn. Tiện lợi nhưng mặt trái là không thể bỏ qua khâu kiểm tra bằng mắt người.' },
      { jp:'AI に 任[まか]せて は いけない の は 、 相手[あいて] の 気持[きも]ち に 関[かか]わる 仕事[しごと] だ と 思[おも]います 。 例[たと]えば クレーム へ の 対応[たいおう] や 部下[ぶか] へ の 助言[じょげん] は 、 言葉[ことば] の 正[ただ]しさ 以上[いじょう] に 誠意[せいい] が 求[もと]められます 。 どんな に 技術[ぎじゅつ] が 進[すす]んだ に せよ 、 人[ひと] と 人[ひと] と の 信頼[しんらい] は 人間[にんげん] に しか 築[きず]けません 。', vi:'Điều không được giao cho AI, theo tôi, là những công việc liên quan đến cảm xúc của đối phương. Ví dụ xử lý khiếu nại hay khuyên bảo cấp dưới đòi hỏi thành ý hơn cả sự đúng đắn của lời nói. Dù công nghệ tiến bộ đến đâu, lòng tin giữa người với người chỉ có con người mới xây được.' },
      { jp:'これ から の 社会人[しゃかいじん] に 必要[ひつよう] な の は 、 AI を 使[つか]いこなす 技術[ぎじゅつ] より も 、 何[なに] を AI に 任[まか]せ 、 何[なに] を 自分[じぶん] で やる か を 見極[みきわ]める 力[ちから] です 。 効率化[こうりつか] を 進[すす]め ざる を 得[え]ない 時代[じだい] だ から こそ 、 人間[にんげん] に しか できない 仕事[しごと] の 価値[かち] は 高[たか]まる 一方[いっぽう] だ と 、 わたし は 考[かんが]えて います 。', vi:'Điều người đi làm sắp tới cần không phải kỹ năng dùng thành thạo AI, mà là khả năng phân định việc gì giao cho AI, việc gì tự làm. Chính vì là thời đại buộc phải tăng hiệu suất, tôi cho rằng giá trị của những công việc chỉ con người làm được sẽ ngày càng tăng.' }
    ] },
  { id:'nihon-to-betonamu', jp:'日本とベトナム — 架け橋として', vi:'Nhật Bản và Việt Nam — với tư cách cầu nối', level:'n2',
    keys:[['架[か]け橋[はし]','cầu nối'],['相互[そうご]理解[りかい]','hiểu biết lẫn nhau'],['〜を問[と]わず','bất kể'],['〜からこそ','chính vì'],['〜てからというもの','kể từ khi'],['〜ようではないか','hãy cùng … nào']],
    qs:['日本[にほん]で学[まな]んで一番[いちばん]変[か]わったことは何[なん]ですか。','両国[りょうこく]の文化[ぶんか]の違[ちが]いで苦労[くろう]したことはありますか。','日本人[にほんじん]とベトナム人[じん]が一緒[いっしょ]に働[はたら]くコツは何[なん]ですか。','将来[しょうらい]、どんな形[かたち]で両国[りょうこく]に貢献[こうけん]したいですか。'],
    paras:[
      { jp:'日本[にほん] で 一年[いちねん] 学[まな]んで から と いう もの 、 わたし の 考[かんが]え方[かた] は 大[おお]きく 変[か]わりました 。 以前[いぜん] は 「 日本[にほん] の やり方[かた] が 正[ただ]しい 」 と 思[おも]い込[こ]んで いました が 、 今[いま] は 、 どちら の 国[くに] に も 学[まな]ぶ べき 点[てん] と 見直[みなお]す べき 点[てん] が ある と 考[かんが]えて います 。', vi:'Kể từ khi học một năm ở Nhật, cách nghĩ của tôi đã thay đổi lớn. Trước đây tôi đinh ninh «cách làm của Nhật là đúng», nhưng giờ tôi cho rằng nước nào cũng có điểm nên học và điểm nên xem lại.' },
      { jp:'文化[ぶんか] の 違[ちが]い で 一番[いちばん] 苦労[くろう]した の は 、 「 はい 」 の 意味[いみ] です 。 ベトナム人[じん] の 「 はい 」 は 「 聞[き]いて います 」 の 意味[いみ] で ある こと が 多[おお]い の に 対[たい]して 、 日本人[にほんじん] は 「 了解[りょうかい]しました 」 と 受[う]け取[と]ります 。 この ずれ の せい で 、 納期[のうき] を めぐって 誤解[ごかい] が 生[う]じた こと も あります 。 言葉[ことば] が 通[つう]じる から と いって 、 意味[いみ] が 通[つう]じる と は 限[かぎ]らない のです 。', vi:'Khác biệt văn hoá làm tôi vất vả nhất là nghĩa của «vâng». Trong khi «vâng» của người Việt thường có nghĩa «tôi đang nghe», người Nhật lại hiểu là «tôi đã rõ». Do lệch pha này, đã từng nảy sinh hiểu lầm xoay quanh ngày giao hàng. Không phải cứ hiểu lời là hiểu ý.' },
      { jp:'日本人[にほんじん] と ベトナム人[じん] が 一緒[いっしょ] に 働[はたら]く コツ は 、 国籍[こくせき] を 問[と]わず 「 確認[かくにん] を 面倒[めんどう] がらない 」 こと だ と 思[おも]います 。 分[わ]かった つもり で 進[すす]める くらい なら 、 しつこい と 思[おも]われて も 一言[ひとこと] 確[たし]かめた ほう が いい 。 違[ちが]い が ある から こそ 、 言葉[ことば] に して 伝[つた]える 努力[どりょく] が 必要[ひつよう] な のです 。', vi:'Bí quyết để người Nhật và người Việt làm việc cùng nhau, theo tôi, là bất kể quốc tịch, «không ngại việc xác nhận». Thà bị cho là dai dẳng mà hỏi lại một câu còn hơn là tiến hành với ý nghĩ đã hiểu. Chính vì có khác biệt nên mới cần nỗ lực diễn đạt thành lời.' },
      { jp:'将来[しょうらい] は 、 ベトナム の 若者[わかもの] が 日本[にほん] で 学[まな]び 、 日本[にほん] の 企業[きぎょう] が ベトナム で 成長[せいちょう]する 、 その 両方[りょうほう] を 支[ささ]える 仕事[しごと] を したい と 思[おも]って います 。 相互[そうご] 理解[りかい] は 一日[いちにち] に して 成[な]らず 、 です 。 だから こそ 、 小[ちい]さな 橋[はし] を 一[ひと]つ ずつ 架[か]けて いこう では ありません か 。', vi:'Tương lai tôi muốn làm công việc nâng đỡ cả hai chiều: người trẻ Việt Nam học ở Nhật và doanh nghiệp Nhật phát triển ở Việt Nam. Hiểu biết lẫn nhau không thể có trong một ngày. Chính vì thế, chúng ta hãy cùng bắc từng cây cầu nhỏ một nào.' }
    ] }
];
if (typeof module !== 'undefined') module.exports = { SPEAKING_JA };
