/* ============================================================
   LangLab — Đề thi thử TOEFL iBT
   Do LangLab tự biên soạn theo dạng thức TOEFL iBT (ets.org),
   KHÔNG phải đề thi chính thức của ETS.

   Cấu trúc phần làm trên máy trong app:
     Reading    20 câu · 35 phút · 2 bài đọc học thuật
     Listening  28 câu · 36 phút · 2 hội thoại + 3 bài giảng
     Writing     2 task · 29 phút (Integrated 20′ · Academic Discussion 10′)
   Phần Speaking gồm 4 task nói vào micro — luyện ở màn «Luyện nói».

   Quy đổi: mỗi phần quy về thang 0–30, tổng 0–120 (TOEFL_SCALE).
   ============================================================ */

/* Quy đổi điểm thô sang thang 30 của từng phần (ước lượng theo bảng công bố của ETS) */
const TOEFL_SCALE = {
  reading:   [[20,30],[19,29],[18,28],[17,26],[16,25],[15,23],[14,22],[13,20],[12,18],[11,17],[10,15],[9,13],[8,11],[7,9],[6,7],[5,5],[4,3],[3,2],[2,1]],
  listening: [[28,30],[27,29],[26,28],[25,27],[24,26],[23,25],[22,23],[21,22],[20,21],[19,20],[18,18],[17,17],[16,15],[15,14],[14,13],[13,11],[12,10],[10,7],[8,5],[6,3],[4,1]]
};
function toeflScale(raw, kind){
  const t = TOEFL_SCALE[kind] || TOEFL_SCALE.reading;
  for (let i = 0; i < t.length; i++) if (raw >= t[i][0]) return t[i][1];
  return 0;
}

const TOEFL_EXAMS = [

{
  id:'toefl-ibt-1', lang:'en', level:'toefl', badge:'TOEFL · iBT', title:'Đề thi thử TOEFL iBT — Đề 1',
  official:'Đúng cấu trúc phần làm trên máy: Reading 20 câu (35′) · Listening 28 câu (36′) · Writing 2 task (29′). Speaking 4 task nói vào micro — luyện ở màn «Luyện nói». Tổng điểm quy về thang 0–120.',
  minutes:100, maxScore:300, pass:180, passEach:0, plays:1,
  sections:[
    { id:'R', name:'Reading', vi:'Đọc · 20 câu · 35 phút', parts:[
      { title:'Passage 1 — The Domestication of the Horse', ins:'Read the passage and answer Questions 1–10.', vi:'Câu 1–10: Đọc bài về việc thuần hoá ngựa.',
        qs:[
          { t:'mc', q:'1. According to paragraph 1, the main obstacle to identifying early domestication is that', o:['horse bones decay quickly.','domesticated and wild bones look almost identical.','few horse bones survive from that period.','the sites have never been excavated.'], c:1,
            p:'THE DOMESTICATION OF THE HORSE\n\n[1] Establishing when horses were first domesticated has proved unusually difficult. Unlike cattle or sheep, whose skeletons changed noticeably within a few generations of domestication, early domestic horses were anatomically almost indistinguishable from wild ones. A bone from a tamed horse and a bone from a hunted horse can look the same under a microscope, and for decades this meant that archaeologists were arguing about evidence that could not settle the question.\n\n[2] Three lines of indirect evidence eventually broke the deadlock. The first was bit wear. A metal or rope bit held in the mouth leaves a characteristic pattern of damage on the second premolar, and this pattern does not occur in wild populations. The second was the shape of the herd. In a hunted population, the remains are dominated by young adults, because hunters take the animals they can catch; in a managed herd, the age profile is broader and includes old animals that were kept for breeding. The third was chemical: residues absorbed into the walls of clay pots have been shown to include mare’s milk, which no hunter could obtain.\n\n[3] Taken together, this evidence points to the steppe grasslands north of the Black Sea, around five and a half thousand years ago. The date remains contested, and some researchers argue for a slightly later and more western origin, but the region is now widely accepted.\n\n[4] The consequences were out of all proportion to the animal. A person on foot travels perhaps thirty kilometres a day; a rider covers three times that and arrives able to fight. Herding, which had previously limited a family to the number of animals it could watch on foot, became possible on a far larger scale. Trade routes lengthened. So did the reach of disease, and of language: the spread of the Indo-European languages across Eurasia is now thought to be linked, though not simply, to the mobility that horses allowed.\n\n[5] It is worth noting what domestication did not immediately produce. Riding appears to have come first, but the evidence for horses pulling wheeled vehicles is a thousand years later, and cavalry as an organised military force is later still. The technologies that made the horse decisive in warfare — the chariot, the saddle, the stirrup — were each separated by centuries. The animal was available long before people worked out what to do with it.',
            e:'Đoạn [1]: «early domestic horses were anatomically almost indistinguishable from wild ones».' },
          { t:'mc', q:'2. The word «deadlock» in paragraph 2 is closest in meaning to', o:['a situation with no progress','a violent argument','a locked container','a written agreement'], c:0, e:'deadlock = bế tắc, không tiến triển được.' },
          { t:'mc', q:'3. Bit wear is useful as evidence because it', o:['appears on all horse bones.','is easy to date precisely.','does not occur in wild horses.','shows the age of the animal.'], c:2, e:'«this pattern does not occur in wild populations».' },
          { t:'mc', q:'4. According to paragraph 2, the age profile of a hunted population is dominated by', o:['very old animals.','young adults.','newborn foals.','males only.'], c:1, e:'«the remains are dominated by young adults».' },
          { t:'mc', q:'5. Traces of mare’s milk are significant because they show that horses were', o:['eaten rather than ridden.','kept and milked rather than hunted.','traded over long distances.','used to pull vehicles.'], c:1, e:'«mare’s milk, which no hunter could obtain» → phải nuôi mới vắt sữa được.' },
          { t:'mc', q:'6. What does the author say about the date of domestication?', o:['It is now agreed by all researchers.','It is still disputed by some researchers.','It has been shown to be much earlier.','It cannot be estimated at all.'], c:1, e:'«The date remains contested».' },
          { t:'mc', q:'7. According to paragraph 4, a rider could travel about', o:['thirty kilometres a day.','sixty kilometres a day.','ninety kilometres a day.','one hundred and fifty kilometres a day.'], c:2, e:'«a rider covers three times that» — ba lần 30 km = 90 km.' },
          { t:'mc', q:'8. The author mentions the spread of Indo-European languages in order to', o:['prove that horses originated in Europe.','illustrate a consequence of increased mobility.','question the dating of domestication.','contrast language with disease.'], c:1, e:'Ngôn ngữ được nêu như một hệ quả của khả năng di chuyển.' },
          { t:'mc', q:'9. Paragraph 5 emphasises that', o:['riding and driving developed at the same time.','the military use of horses came long after domestication.','chariots were invented before riding.','the stirrup was the earliest invention.'], c:1, e:'«cavalry as an organised military force is later still».' },
          { t:'mc', q:'10. Which sentence best expresses the main idea of the passage?', o:['Horses were domesticated much earlier than cattle.','Indirect evidence resolved a long-standing problem, and the consequences of domestication unfolded slowly.','Bit wear is the only reliable evidence of domestication.','Horses were more important for trade than for war.'], c:1, e:'Bài trình bày ba loại chứng cứ gián tiếp rồi nói hệ quả diễn ra dần qua nhiều thế kỷ.' }
        ] },
      { title:'Passage 2 — Why Some Species Become Invasive', ins:'Read the passage and answer Questions 11–20.', vi:'Câu 11–20: Đọc bài về loài xâm lấn.',
        qs:[
          { t:'mc', q:'11. According to paragraph 1, most introduced species', o:['become invasive within a decade.','fail to establish at all.','are introduced deliberately.','spread faster than native species.'], c:1,
            p:'WHY SOME SPECIES BECOME INVASIVE\n\n[1] Of every hundred species carried by humans into a new region, the great majority simply die. Of those that survive, most establish small, unremarkable populations that never spread. Only a handful — the figure often quoted is around one in a thousand — become what ecologists call invasive: abundant, widespread and damaging. Explaining why that handful behaves so differently is one of the oldest unsolved problems in ecology.\n\n[2] The most influential early explanation was the enemy release hypothesis. A species arriving in a new region leaves behind the predators, parasites and diseases that limited it at home. Freed from these controls, it can allocate to growth and reproduction the resources it previously spent on defence. The hypothesis has clear supporting cases: several plants introduced to North America carry far fewer insect herbivores there than in their native range, and grow correspondingly larger.\n\n[3] Yet enemy release cannot be the whole story, since every introduced species enjoys it and only a few become invasive. Attention has therefore shifted to what the arriving species does that the residents cannot. Some invaders exploit a resource nobody else is using; others change the environment itself. A grass that burns readily, for example, can convert a shrubland into a fire-prone grassland in which it thrives and its competitors do not. In such cases the invader is not simply winning a competition but altering the rules of the game.\n\n[4] Timing matters as much as biology. Analyses of invasion records show that the strongest single predictor of establishment is not any trait of the species but propagule pressure — the number of individuals released and the number of separate release events. A species introduced once, in small numbers, usually fails however well adapted it is; the same species introduced repeatedly over decades usually succeeds. This finding is uncomfortable, because it suggests that much of what looks like biological superiority is in fact an accident of trade volume.\n\n[5] There is also a time lag that complicates every attempt at prediction. Many invasions begin with a long quiet phase — sometimes fifty years or more — during which the population is small and apparently harmless, before expanding rapidly. A management agency looking at a newly established population therefore has very little information on which to act, and the cost of acting is immediate while the benefit is distant and uncertain. It is precisely this asymmetry, rather than any scientific disagreement, that explains why so few invasions are stopped early.',
            e:'Đoạn [1]: «the great majority simply die» và chỉ khoảng một phần nghìn thành xâm lấn.' },
          { t:'mc', q:'12. The enemy release hypothesis explains invasiveness in terms of', o:['faster reproduction in warm climates.','the absence of natural predators and diseases.','competition with native plants.','human transport routes.'], c:1, e:'«leaves behind the predators, parasites and diseases».' },
          { t:'mc', q:'13. According to paragraph 2, freed from natural enemies, a species can', o:['change its genetic make-up.','move resources from defence to growth.','survive without water.','avoid detection.'], c:1, e:'«allocate to growth and reproduction the resources it previously spent on defence».' },
          { t:'mc', q:'14. The main weakness of the enemy release hypothesis is that', o:['it has no supporting evidence.','it applies to all introduced species, not only invasive ones.','it only works for animals.','it was proposed too recently.'], c:1, e:'«every introduced species enjoys it and only a few become invasive».' },
          { t:'mc', q:'15. The example of the fire-prone grass illustrates a species that', o:['outcompetes rivals for the same resource.','modifies its environment to its own advantage.','is spread deliberately by humans.','has no natural enemies.'], c:1, e:'«altering the rules of the game» — thay đổi chính môi trường.' },
          { t:'mc', q:'16. «Propagule pressure» refers to', o:['the speed at which a species reproduces.','the number of individuals and release events.','the strength of native competition.','the temperature range a species tolerates.'], c:1, e:'«the number of individuals released and the number of separate release events».' },
          { t:'mc', q:'17. The author describes the propagule pressure finding as «uncomfortable» because it suggests that', o:['scientists have been dishonest.','invasion success is partly a matter of trade volume rather than biology.','no management is possible.','the data are unreliable.'], c:1, e:'«much of what looks like biological superiority is in fact an accident of trade volume».' },
          { t:'mc', q:'18. According to paragraph 5, the quiet phase before an invasion expands may last', o:['a few months.','about five years.','fifty years or more.','several centuries.'], c:2, e:'«sometimes fifty years or more».' },
          { t:'mc', q:'19. According to the passage, the main reason invasions are rarely stopped early is', o:['scientific disagreement.','a lack of trained staff.','the mismatch between immediate costs and distant benefits.','public opposition to control measures.'], c:2, e:'«the cost of acting is immediate while the benefit is distant and uncertain… this asymmetry, rather than any scientific disagreement».' },
          { t:'mc', q:'20. The passage as a whole is organised as', o:['a chronological history of invasions.','a single hypothesis defended throughout.','a sequence of explanations, each shown to be incomplete.','a comparison of two regions.'], c:2, e:'Bài lần lượt nêu enemy release → thay đổi môi trường → propagule pressure → độ trễ, mỗi cái bổ khuyết cho cái trước.' }
        ] }
    ]},
    { id:'L', name:'Listening', vi:'Nghe · 28 câu · 36 phút', parts:[
      { title:'Conversation 1 — Student and Registrar (Questions 21–25)', ins:'Listen to each item and choose the best answer.', vi:'Câu 21–25: Hội thoại giữa sinh viên và phòng đào tạo.',
        qs:[
          { k:'listen', t:'mc', q:'21. Why does the student go to the registrar’s office?', o:['To pay a fee','To change a course','To collect a transcript','To report a lost card'], c:1, e:'«I want to drop statistics and add data visualisation» → đổi môn.',
            a:'Hi, how can I help? — Hi. I want to drop statistics and add data visualisation instead, if that is still possible.' },
          { k:'listen', t:'mc', q:'22. What is the problem with the student’s request?', o:['The new course is full.','The deadline has passed.','He lacks a prerequisite.','The two courses clash.'], c:2, e:'«you have not taken the programming course» → thiếu môn tiên quyết.',
            a:'Let me check. Data visualisation has a prerequisite, and according to your record you have not taken the programming course.' },
          { k:'listen', t:'mc', q:'23. What does the registrar suggest he does first?', o:['Email the department head','Speak to the course instructor','Take a placement test','Wait until next term'], c:1, e:'«talk to Dr Reid, the instructor» → gặp giảng viên.',
            a:'What are my options? — Talk to Dr Reid, the instructor. If she signs a waiver, I can process the change today.' },
          { k:'listen', t:'mc', q:'24. What does the student say about his timetable?', o:['He has no free afternoons.','He works on Fridays.','He has two classes at the same time.','He prefers morning classes.'], c:1, e:'«I work on Fridays» → đi làm thứ Sáu.',
            a:'Is Friday afternoon possible for you? — Not really. I work on Fridays, that is the one day I cannot come in.' },
          { k:'listen', t:'mc', q:'25. What will the student probably do next?', o:['Go to Dr Reid’s office','Pay the late fee','Return the following week','Enrol online'], c:0, e:'«Her office hours are today from two» → tới gặp Dr Reid.',
            a:'Her office hours are today from two until four, room 3.14. If you go now you will probably catch her.' }
        ] },
      { title:'Lecture 1 — Art History (Questions 26–31)', ins:'Listen to each item and choose the best answer.', vi:'Câu 26–31: Bài giảng lịch sử nghệ thuật.',
        qs:[
          { k:'listen', t:'mc', q:'26. What is the lecture mainly about?', o:['The invention of oil paint','Why fresco painting declined','How pigments were traded','The restoration of frescoes'], c:1, e:'«why fresco largely disappeared» → vì sao bích hoạ suy tàn.',
            a:'Today I want to explain something that puzzles a lot of students: why fresco, the dominant wall-painting technique for centuries, largely disappeared.' },
          { k:'listen', t:'mc', q:'27. According to the professor, the main technical demand of fresco is that', o:['the wall must be dry.','the paint must be applied while the plaster is wet.','only three colours can be used.','it must be done in daylight.'], c:1, e:'«you paint into wet plaster» → phải vẽ khi vữa còn ướt.',
            a:'In true fresco you paint into wet plaster, so the pigment becomes part of the wall as it dries. That is why it lasts, and also why it is unforgiving.' },
          { k:'listen', t:'mc', q:'28. The professor uses the term «giornata» to refer to', o:['a type of pigment.','the amount of plaster laid for one day’s work.','a school of painters.','a preparatory drawing.'], c:1, e:'«the patch you can finish in one day» → mảng vữa làm trong một ngày.',
            a:'Painters worked in sections called giornate — literally «days» — the patch of plaster you can finish in one day, because tomorrow it will be dry and useless.' },
          { k:'listen', t:'mc', q:'29. What does the professor say about correcting mistakes in fresco?', o:['They can be painted over easily.','The plaster must be cut out and replaced.','They are usually left visible.','Only the artist can see them.'], c:1, e:'«you chisel it out» → phải đục bỏ và trát lại.',
            a:'And if you make a mistake? You cannot paint over it. You chisel the section out, replaster and start again.' },
          { k:'listen', t:'mc', q:'30. According to the lecture, one advantage of oil on canvas was that it', o:['dried faster.','could be moved and sold.','used cheaper pigments.','required less skill.'], c:1, e:'«a painting you can roll up and sell» → có thể di chuyển và bán.',
            a:'Oil on canvas changed the economics completely. A fresco belongs to a wall; a canvas is a painting you can roll up, transport and sell to somebody in another city.' },
          { k:'listen', t:'mc', q:'31. What does the professor imply about climate?', o:['It had no effect on the technique.','Damp northern conditions were unsuitable for fresco.','Frescoes survive better in cold regions.','Climate mattered less than cost.'], c:1, e:'«damp walls of northern Europe destroy fresco» → khí hậu ẩm miền Bắc không hợp.',
            a:'There is a geographical point too. The damp walls of northern Europe destroy fresco within a generation, which is one reason the technique stayed largely Italian.' }
        ] },
      { title:'Lecture 2 — Environmental Science (Questions 32–37)', ins:'Listen to each item and choose the best answer.', vi:'Câu 32–37: Bài giảng khoa học môi trường.',
        qs:[
          { k:'listen', t:'mc', q:'32. What aspect of wetlands does the professor focus on?', o:['Their role in flood control','Their bird populations','Their soil chemistry','Their legal protection'], c:0, e:'«what wetlands do to floodwater» → vai trò điều tiết lũ.',
            a:'Right — wetlands. I am not going to talk about birds today. I want to look at something less photogenic: what wetlands do to floodwater.' },
          { k:'listen', t:'mc', q:'33. The professor compares a wetland to', o:['a filter.','a sponge.','a wall.','a pump.'], c:1, e:'«behaves like a sponge» → như miếng bọt biển.',
            a:'A healthy wetland behaves like a sponge. It absorbs water quickly during a storm and releases it slowly over the following days.' },
          { k:'listen', t:'mc', q:'34. According to the lecture, draining a wetland tends to', o:['reduce flooding downstream.','increase the speed of runoff.','improve water quality.','have no measurable effect.'], c:1, e:'«water arrives downstream faster and all at once» → dòng chảy nhanh hơn.',
            a:'Drain it, and the same rainfall now runs off a hard surface. The water arrives downstream faster and all at once, which is precisely what causes a flood peak.' },
          { k:'listen', t:'mc', q:'35. The professor mentions the cost of engineered defences in order to', o:['argue that they never work.','show that wetland restoration can be cheaper.','criticise local government.','explain why they are rarely built.'], c:1, e:'«restoring the marsh cost a fraction» → phục hồi đầm rẻ hơn nhiều.',
            a:'In one catchment the concrete option was costed at forty million. Restoring the marsh upstream cost a fraction of that and did the same job.' },
          { k:'listen', t:'mc', q:'36. What limitation of wetland restoration does the professor acknowledge?', o:['It takes years to become effective.','It requires imported plants.','It only works in warm climates.','It increases mosquito populations.'], c:0, e:'«it takes years before it functions» → cần nhiều năm mới có tác dụng.',
            a:'I should be honest about the drawback. You cannot build a wetland in a season. It takes years before it functions properly, and politicians rarely have years.' },
          { k:'listen', t:'mc', q:'37. What does the professor ask students to do before the next class?', o:['Read two articles','Visit a local wetland','Prepare a presentation','Submit a data table'], c:0, e:'«read the two papers» → đọc hai bài báo.',
            a:'For Thursday, please read the two papers in the folder — the Danish case study and the review article. We will compare them.' }
        ] },
      { title:'Conversation 2 & Lecture 3 (Questions 38–48)', ins:'Listen to each item and choose the best answer.', vi:'Câu 38–48: Hội thoại thư viện và bài giảng tâm lý học.',
        qs:[
          { k:'listen', t:'mc', q:'38. Why does the student visit the library desk?', o:['To renew a book','To find a missing article','To book a study room','To pay a fine'], c:1, e:'«the article is not in the database» → tìm bài báo không thấy.',
            a:'Excuse me — I am trying to find an article for my essay and it does not seem to be in the database at all.' },
          { k:'listen', t:'mc', q:'39. What does the librarian say about the journal?', o:['It was cancelled last year.','It is only available in print.','It is under a different title.','It is restricted to staff.'], c:2, e:'«the journal changed its name in 2019» → đổi tên.',
            a:'Ah — I know this one. The journal changed its name in twenty nineteen, so anything older is filed under the old title.' },
          { k:'listen', t:'mc', q:'40. What does the librarian offer to do?', o:['Order the article from another library','Print the article','Extend the essay deadline','Contact the author'], c:0, e:'«request it from another library» → mượn liên thư viện.',
            a:'If you still cannot find it, I can request it from another library. It usually takes two or three days and it is free for students.' },
          { k:'listen', t:'mc', q:'41. What is the student’s main concern?', o:['The cost','The deadline','The referencing style','The length of the essay'], c:1, e:'«my essay is due on Monday» → hạn nộp.',
            a:'Two or three days might be tight. My essay is due on Monday.' },
          { k:'listen', t:'mc', q:'42. What does the librarian suggest as an alternative?', o:['Citing a later paper by the same author','Using a textbook instead','Asking the tutor for an extension','Searching a different database'], c:3, e:'«try the open archive» → thử một cơ sở dữ liệu khác.',
            a:'In that case try the open archive — a lot of authors deposit a free version there. Search the title, not the journal.' },
          { k:'listen', t:'mc', q:'43. What is the lecture mainly about?', o:['How memory is stored','Why eyewitness testimony is unreliable','The development of language in children','Methods of measuring attention'], c:1, e:'«why eyewitnesses get things wrong» → độ tin cậy của lời khai nhân chứng.',
            a:'Today: eyewitness testimony. Specifically, why eyewitnesses get things wrong so often while feeling completely certain.',
            p:'' },
          { k:'listen', t:'mc', q:'44. According to the professor, confidence and accuracy are', o:['strongly related.','only weakly related.','identical.','inversely related in all cases.'], c:1, e:'«the correlation is weak» → tương quan yếu.',
            a:'The first thing to understand is that the correlation between how confident a witness feels and how accurate they are is weak. Juries assume the opposite.' },
          { k:'listen', t:'mc', q:'45. In the classic study described, what changed the participants’ estimates of speed?', o:['The colour of the cars','The verb used in the question','The time of day','The number of witnesses'], c:1, e:'«smashed versus hit» → động từ dùng trong câu hỏi.',
            a:'In the classic study, participants watched the same film of a collision. Some were asked how fast the cars were going when they smashed into each other; others, when they hit. The smashed group gave higher speeds — and a week later were more likely to report broken glass that was never there.' },
          { k:'listen', t:'mc', q:'46. The professor uses the term «reconstruction» to argue that memory is', o:['stored like a recording.','rebuilt each time it is recalled.','permanent once formed.','stronger under stress.'], c:1, e:'«rebuilt from fragments each time» → dựng lại mỗi lần nhớ.',
            a:'Memory is not a recording that we play back. It is rebuilt from fragments each time, and anything we have heard since can be built into it.' },
          { k:'listen', t:'mc', q:'47. What practical change does the professor mention?', o:['Longer interviews','Sequential rather than simultaneous line-ups','Recording all testimony on video','Using two interviewers'], c:1, e:'«show faces one at a time» → nhận diện tuần tự.',
            a:'One practical result: police in several countries now show faces one at a time rather than all together, which reduces the tendency to pick whoever looks most like the memory.' },
          { k:'listen', t:'mc', q:'48. What does the professor say about the reliability of witnesses overall?', o:['They should never be believed.','Their evidence is useful but must be handled carefully.','They are accurate if questioned quickly.','Only trained observers are reliable.'], c:1, e:'«useful evidence, but it needs handling like any fragile material» → hữu ích nhưng phải xử lý cẩn thận.',
            a:'None of this means witnesses are useless. It means their evidence is useful evidence, but it needs handling like any fragile material — carefully, and early.' }
        ] }
    ]},
    { id:'W', name:'Writing', vi:'Viết · 2 task · 29 phút', parts:[
      { title:'Integrated Writing Task — 20 minutes', ins:'Read the passage, listen to the lecture, then write 150–225 words summarising the points made in the lecture and explaining how they cast doubt on the reading.', vi:'Task 1 (20 phút, 150–225 từ): tóm tắt ý bài giảng và giải thích chúng phản bác bài đọc thế nào.',
        qs:[
          { k:'listen', t:'essay', min:150, words:['lecture','reading'],
            q:'READING PASSAGE (3 minutes)\n\nMany companies have introduced a four-day working week with no reduction in pay. Supporters give three reasons. First, productivity rises: employees who work fewer hours waste less time and concentrate better, so total output does not fall. Second, staff turnover drops sharply, because a shorter week is a benefit competitors find hard to match, and recruitment is expensive. Third, the environmental impact is positive, since one fewer commuting day per employee per week reduces traffic and office energy use.\n\nNow listen to the lecture. Then write your response.\n\n(Bài viết BẮT BUỘC có từ «lecture» và «reading».)',
            a:'The reading gives three reasons for the four-day week. I want to look at each one more carefully. On productivity: the trials that show output holding steady are almost all in office work where output is hard to measure. Where output is measurable — a factory line, a hospital ward, a call centre — four days of work produce four days of output. You cannot compress a shift. On turnover: yes, the firms that moved first saw a dramatic fall in resignations, but that is a competitive advantage, not a general effect. If every employer offers four days, nobody has an advantage, and the effect disappears. And on the environment: the studies that found lower emissions measured commuting only. Two of them also found that employees used the extra day for leisure travel, and in one case the additional weekend journeys cancelled out the entire commuting saving.',
            e:'BÀI MẪU (band cao):\n\nThe lecture challenges all three arguments presented in the reading.\n\nFirst, the reading claims that productivity rises because employees concentrate better. The lecture points out that this finding comes almost entirely from office work, where output is difficult to measure. In settings where output can be counted — a factory, a hospital ward or a call centre — four days of work simply produce four days of output, because a shift cannot be compressed.\n\nSecond, the reading argues that a shorter week reduces staff turnover. The lecturer accepts that early adopters saw resignations fall sharply, but explains that this is a competitive advantage rather than a property of the policy itself. Once every employer offers the same benefit, no firm gains an advantage and the effect disappears.\n\nFinally, the reading states that the environmental impact is positive. The lecture responds that the relevant studies measured commuting alone. Two of them found that employees used the free day for leisure travel, and in one case these extra weekend journeys cancelled out the entire saving from not commuting.\n\nGHI CHÚ: bài Integrated KHÔNG nêu ý kiến cá nhân. Nhiệm vụ duy nhất là thuật lại ý bài giảng và đối chiếu với bài đọc.' }
        ] },
      { title:'Writing for an Academic Discussion — 10 minutes', ins:'Read the discussion and write a response of at least 100 words that contributes your own opinion.', vi:'Task 2 (10 phút, tối thiểu 100 từ): tham gia thảo luận học thuật, nêu quan điểm riêng có lập luận.',
        qs:[
          { t:'essay', min:100, words:['I','because'],
            q:'PROFESSOR NGUYEN: This week we are looking at transport policy. Some cities have made public transport completely free, funded by taxes. Others argue that fares should be kept but kept low, and that the money saved should be spent on improving the service. Which approach do you think works better, and why?\n\nMAYA: I would make it free. Every study I have read shows that the biggest barrier for low-income households is cost, not frequency. Free travel is also simple to administer — no ticket machines, no inspectors, no fare evasion.\n\nDANIEL: I disagree. A free service that arrives every forty minutes is worthless. If we have limited money, spend it on more buses and longer hours. People will pay a small fare for a service that actually turns up.\n\nWrite a post responding to the discussion. State your own opinion and support it.\n\n(Bài viết BẮT BUỘC có từ «I» và «because».)',
            e:'BÀI MẪU (band cao):\n\nI find Daniel’s argument more convincing, although I think the two positions are less opposed than they appear.\n\nMaya is right that cost is a real barrier, but a free service only helps people who can actually use it. In my own city the buses are cheap and still half empty, because they run every forty minutes and stop at nine in the evening. Making those buses free would not persuade a nurse finishing a night shift to leave her motorbike at home; a bus every ten minutes until midnight would.\n\nI would therefore keep a low, flat fare and spend the money on frequency first, because frequency is what turns public transport into a genuine alternative. Once the service is good enough that most people prefer it, targeted free travel for students and low-income households becomes affordable — and by then it would actually be used.\n\nGHI CHÚ: dạng bài này chỉ 10 phút. Công thức an toàn: nêu bạn nghiêng về ai → thừa nhận điểm đúng của phía kia → một ví dụ cụ thể → chốt lại quan điểm.' }
        ] }
    ]}
  ]
}

,
{
  id:'toefl-ibt-2', lang:'en', level:'toefl', badge:'TOEFL · iBT', title:'Đề thi thử TOEFL iBT — Đề 2',
  official:'Đúng cấu trúc phần làm trên máy: Reading 20 câu (35′) · Listening 28 câu (36′) · Writing 2 task (29′). Speaking 4 task nói vào micro — luyện ở màn «Luyện nói». Tổng điểm quy về thang 0–120.',
  minutes:100, maxScore:120, pass:0, passEach:0, plays:1,
  sections:[
    { id:'reading', name:'Reading', vi:'Đọc hiểu · 20 câu · 35 phút', parts:[
      { title:'Passage 1 — How Cities Cool Themselves', ins:'Read the passage and answer Questions 1–10.', vi:'Câu 1–10: Đọc bài về đảo nhiệt đô thị.',
        qs:[
          { t:'mc', q:'1. According to paragraph 1, the main cause of the urban heat island is', o:['waste heat from engines and air conditioners.','the materials cities are built from.','the density of population.','a lack of wind at night.'], c:1, e:'The larger factor is much duller: the materials cities are built from.',
            p:'HOW CITIES COOL THEMSELVES\n\n[1] On a still summer night a large city can be six to eight degrees warmer than the farmland around it. The effect has been measured since the early nineteenth century and is now called the urban heat island. Its cause is not, as many assume, the waste heat of engines and air conditioners, although that contributes. The larger factor is much duller: the materials cities are built from.\n\n[2] Asphalt and dark roofing absorb far more solar energy than vegetation, and they release it slowly through the night. A field of grass, by contrast, spends much of the day converting sunlight into evaporation rather than heat. A city has removed most of that evaporating surface and replaced it with stone that stores warmth and drains water away before it can evaporate at all.\n\n[3] The remedies follow directly from the diagnosis, and none of them is new. Painting roofs a pale colour raises reflectivity and can lower indoor temperatures by several degrees. Street trees do more, because they cool twice: once by shading the surface beneath them and again by releasing water vapour. Measurements in several cities put the difference between a shaded and an unshaded street at up to twelve degrees at pavement level.\n\n[4] What complicates the picture is that these measures are unevenly distributed. Wealthier districts tend to have older, larger trees, while the districts with the least canopy are often those where residents can least afford air conditioning. The heat island is therefore not a single citywide problem but a map of small, very unequal ones.\n\n[5] Planting is also slow. A tree that will shade a street in 2050 has to be planted now, survive drought and roadworks, and be watered for its first five summers. Cities that treat tree planting as a one-off announcement rather than a thirty-year maintenance commitment usually end up with a photograph and very little shade.' },
          { t:'mc', q:'2. Why does the author call the main factor "much duller"?', o:['Because dark surfaces look dull','Because it is less dramatic than machines producing heat','Because it was discovered recently','Because it applies only at night'], c:1, e:'Tác giả đối lập lời giải thích hấp dẫn (máy móc) với lời giải thích tẻ nhạt nhưng đúng hơn (vật liệu).' },
          { t:'mc', q:'3. According to paragraph 2, grass stays cooler than asphalt mainly because it', o:['reflects all sunlight','uses sunlight for evaporation instead of heat','is a lighter colour','loses heat faster at night'], c:1, e:'spends much of the day converting sunlight into evaporation rather than heat.' },
          { t:'mc', q:'4. The word "drains" in paragraph 2 is closest in meaning to', o:['stores','carries away','absorbs','freezes'], c:1, e:'drains water away = dẫn nước đi chỗ khác.' },
          { t:'mc', q:'5. According to paragraph 3, street trees cool a street in two ways:', o:['shade and wind','shade and water vapour','reflection and shade','reflection and drainage'], c:1, e:'once by shading the surface beneath them and again by releasing water vapour.' },
          { t:'tf', q:'6. Painting roofs a pale colour is described as a new idea.', o:['Đúng','Sai'], c:1, e:'and none of them is new — các biện pháp đều không mới.' },
          { t:'mc', q:'7. What complication is raised in paragraph 4?', o:['Trees need too much water','The benefits are spread unequally between districts','Pale roofs are expensive','Measurements are unreliable'], c:1, e:'these measures are unevenly distributed… very unequal ones.' },
          { t:'mc', q:'8. The author suggests that districts with the least tree cover are often those where residents', o:['prefer open space','can least afford air conditioning','own the most cars','have the newest buildings'], c:1, e:'Câu cuối đoạn 4 nêu đúng điều này.' },
          { t:'mc', q:'9. According to paragraph 5, what does a newly planted street tree require?', o:['Only planting','Watering for its first five summers and long-term care','Annual replacement','Removal of nearby buildings'], c:1, e:'survive drought and roadworks, and be watered for its first five summers.' },
          { t:'mc', q:'10. What is the author’s attitude towards cities that announce tree-planting schemes?', o:['Fully supportive','Sceptical unless long-term maintenance follows','Completely opposed','Neutral and uninterested'], c:1, e:'Câu cuối: end up with a photograph and very little shade — mỉa mai nhẹ.' }
        ] },
      { title:'Passage 2 — The Puzzle of Animal Play', ins:'Read the passage and answer Questions 11–20.', vi:'Câu 11–20: Đọc bài về hành vi chơi đùa ở động vật.',
        qs:[
          { t:'mc', q:'11. According to paragraph 1, why is play surprising from a biological point of view?', o:['It is rare among mammals','It is costly in energy, injury and risk','It occurs only in captivity','It disappears in adulthood'], c:1, e:'play is expensive: it burns energy, causes injuries and attracts predators.',
            p:'THE PUZZLE OF ANIMAL PLAY\n\n[1] Young mammals of almost every species play. They chase, wrestle, pounce on objects that cannot be eaten and repeat movements that lead nowhere. For a long time this was treated as a minor curiosity, but play is expensive: it burns energy, causes injuries and attracts predators. A behaviour that costly is unlikely to survive unless it does something useful.\n\n[2] The oldest explanation is practice. Play, on this view, rehearses adult skills — hunting, fighting, escaping — in conditions where mistakes are cheap. The theory is intuitive and partly supported: predator species play more than grazers, and much of their play resembles hunting. Yet it fits some observations badly. Kittens raised without any play still hunt competently, and many playful movements have no adult equivalent at all.\n\n[3] A second explanation shifts attention from skills to flexibility. On this account the function of play is to produce unusual situations — a slip, a fall, a sudden loss of control — and to train the animal to recover from them. Supporting evidence comes from studies showing that animals deliberately put themselves off balance during play far more often than chance would predict.\n\n[4] A third line of research treats play as social calibration. Rats that play together develop more stable relationships, and a rat that consistently wins every play fight will be avoided by its partners. Winning too often, in other words, is a losing strategy. This suggests play has rules, and that learning the rules matters more than the outcome of any single bout.\n\n[5] These explanations are not rivals so much as answers to different questions. Practice explains what is rehearsed; flexibility explains why the rehearsal is so untidy; calibration explains why it is usually done with a partner. What none of them yet explains is why animals appear to enjoy it.' },
          { t:'mc', q:'12. The "practice" explanation says that play', o:['rehearses adult skills where mistakes are cheap','has no function at all','only occurs in grazing animals','replaces adult behaviour'], c:0, e:'Play… rehearses adult skills… in conditions where mistakes are cheap.' },
          { t:'mc', q:'13. Which evidence in paragraph 2 works AGAINST the practice explanation?', o:['Predators play more than grazers','Play resembles hunting','Kittens raised without play still hunt well','Play is common in young animals'], c:2, e:'Kittens raised without any play still hunt competently.' },
          { t:'mc', q:'14. The second explanation focuses on training animals to', o:['win fights','recover from losing control','find food faster','recognise their own species'], c:1, e:'train the animal to recover from them (slips, falls, loss of control).' },
          { t:'mc', q:'15. What evidence supports the flexibility explanation?', o:['Animals avoid falling during play','Animals put themselves off balance more often than chance predicts','Play increases with age','Play only happens alone'], c:1, e:'studies showing that animals deliberately put themselves off balance.' },
          { t:'mc', q:'16. According to paragraph 4, a rat that wins every play fight will', o:['become the leader','be avoided by its partners','play more often','stop playing entirely'], c:1, e:'a rat that consistently wins every play fight will be avoided by its partners.' },
          { t:'tf', q:'17. The passage says the three explanations contradict one another.', o:['Đúng','Sai'], c:1, e:'These explanations are not rivals so much as answers to different questions.' },
          { t:'mc', q:'18. The word "bout" in paragraph 4 is closest in meaning to', o:['injury','single episode of fighting','partner','rule'], c:1, e:'bout = một hiệp, một lượt.' },
          { t:'mc', q:'19. Which question does the passage say remains unanswered?', o:['What is rehearsed in play','Why play is untidy','Why play is done with a partner','Why animals appear to enjoy play'], c:3, e:'Câu cuối: What none of them yet explains is why animals appear to enjoy it.' },
          { t:'mc', q:'20. What is the overall organisation of the passage?', o:['A problem followed by three partial explanations','A chronological history','A comparison of two species','An argument against a single theory'], c:0, e:'Đoạn 1 nêu nghịch lý, đoạn 2–4 đưa ba cách giải thích, đoạn 5 tổng hợp.' }
        ] } ] },

    { id:'listening', name:'Listening', vi:'Nghe hiểu · 28 câu · 36 phút', parts:[
      { title:'Conversation 1 — Student and Housing Office (Questions 21–25)', ins:'Listen to each item and choose the best answer.', vi:'Câu 21–25: Hội thoại giữa sinh viên và phòng ở ký túc.',
        qs:[
          { k:'listen', t:'mc', q:'21. Why does the student visit the housing office?', o:['To pay rent','To ask about moving rooms','To return a key','To book a guest room'], c:1, e:'«I was hoping to move to a quieter room» → xin đổi phòng.', a:'Good afternoon. How can I help? — Hi. I am in Block C, room 214, and I was hoping to move to a quieter room if anything is free.' },
          { k:'listen', t:'mc', q:'22. What is the student’s main complaint?', o:['The room is small','Noise from the shared kitchen','The heating does not work','The rent has increased'], c:1, e:'«the kitchen is right next door and people cook until two in the morning».', a:'What is the problem with 214? — The kitchen is right next door and people cook until two in the morning. I have early lectures.' },
          { k:'listen', t:'mc', q:'23. What does the officer say about rooms on the top floor?', o:['They are all taken','Two are free but cost more','They are being repainted','They are reserved for staff'], c:1, e:'«Two on the fourth floor are free, but they are twelve pounds a week more».', a:'Let me look. Two on the fourth floor are free, but they are twelve pounds a week more. There is nothing at the same price until December.' },
          { k:'listen', t:'mc', q:'24. What does the student decide to do?', o:['Take a room immediately','Wait until December','Look at the room first','Complain about the neighbours'], c:2, e:'«Could I see one before I decide?»', a:'Could I see one before I decide? Twelve pounds is a lot on my budget. — Of course. I can show you at four today.' },
          { k:'listen', t:'mc', q:'25. What does the officer suggest as an alternative?', o:['Reporting the noise so it is recorded','Changing course','Buying earplugs','Moving off campus'], c:0, e:'«report it each time… it builds a record» — ghi nhận để có căn cứ xử lý.', a:'And whatever you decide, report the noise each time it happens. It builds a record, and that is what we act on.' }
        ] },
      { title:'Lecture 1 — Geology (Questions 26–31)', ins:'Listen to each item and choose the best answer.', vi:'Câu 26–31: Bài giảng địa chất.',
        qs:[
          { k:'listen', t:'mc', q:'26. What is the lecture mainly about?', o:['How mountains form','How rivers change their course','How deserts expand','How glaciers melt'], c:1, e:'«today we look at why rivers do not stay where we put them».', a:'Right, today we look at why rivers do not stay where we put them — how and why a river changes course.' },
          { k:'listen', t:'mc', q:'27. According to the professor, a meander grows because', o:['water flows faster on the outer bank','the riverbed rises','rainfall increases','the banks are made of rock'], c:0, e:'«the water on the outside of a bend moves faster and cuts away the bank».', a:'The water on the outside of a bend moves faster and cuts away the bank, while the inside is slow and drops sediment. So the curve deepens.' },
          { k:'listen', t:'mc', q:'28. What is an oxbow lake?', o:['A lake formed by a dam','A cut-off meander left behind','A lake at a river mouth','An underground lake'], c:1, e:'«the neck is cut through and the old loop is left as a lake».', a:'Eventually the neck is cut through and the old loop is left behind as a lake. That is your oxbow.' },
          { k:'listen', t:'mc', q:'29. Why does the professor mention flood defences?', o:['To show they always work','To explain that straightening a river moves the problem downstream','To recommend building more of them','To describe their cost'], c:1, e:'«you have not removed the water, you have moved it downstream faster».', a:'Now, if you straighten a river to protect a town, you have not removed the water. You have moved it downstream faster, and someone else gets it.' },
          { k:'listen', t:'mc', q:'30. What does the professor say about older maps?', o:['They are useless','They show where a river used to run, which predicts flooding','They exaggerate river width','They were drawn from the air'], c:1, e:'«an old map tells you where the river considers home».', a:'And look at old maps. An old map tells you where the river considers home — and rivers do go home.' },
          { k:'listen', t:'mc', q:'31. What will the next class cover?', o:['Coastal erosion','Sediment in deltas','Groundwater','Volcanic soils'], c:1, e:'«next week: what happens to all that sediment when the river reaches the sea».', a:'Next week: what happens to all that sediment when the river finally reaches the sea.' }
        ] },
      { title:'Lecture 2 — Economics (Questions 32–37)', ins:'Listen to each item and choose the best answer.', vi:'Câu 32–37: Bài giảng kinh tế học.',
        qs:[
          { k:'listen', t:'mc', q:'32. What concept does the lecture introduce?', o:['Inflation','Opportunity cost','Interest rates','Trade deficits'], c:1, e:'«the cost of anything is what you gave up to get it» — chi phí cơ hội.', a:'Today, one idea that sounds obvious and is almost never applied: the cost of anything is what you gave up to get it.' },
          { k:'listen', t:'mc', q:'33. What example does the professor use first?', o:['Buying a car','Spending a Saturday on badly paid work','Renting a flat','Choosing a university'], c:1, e:'Ví dụ mở đầu là một ngày thứ Bảy làm việc trả công thấp.', a:'Say you spend Saturday on a piece of freelance work that pays very little. The cost is not the effort. It is the course you did not take.' },
          { k:'listen', t:'mc', q:'34. Why does the professor say the alternative is "invisible"?', o:['Because it never happened, so its problems never appeared','Because nobody records it','Because it is illegal','Because it happens later'], c:0, e:'«had you chosen it, you would have seen its problems too».', a:'The trouble is the alternative is invisible. Had you chosen it, you would have seen its problems too — and they might have been worse.' },
          { k:'listen', t:'mc', q:'35. What warning does the professor give about regret?', o:['It is always useful','It compares a real life with an untested imagined one','It fades quickly','It only affects older people'], c:1, e:'«comparing a real life… against an imagined one that was never tested».', a:'So regret is a bad guide. You are comparing a real life, with all its friction, against an imagined one that was never tested.' },
          { k:'listen', t:'mc', q:'36. What does the professor recommend judging instead of outcomes?', o:['The amount of money involved','The quality of the decision at the time','The opinion of others','The length of time taken'], c:1, e:'«judge the decision, not the outcome».', a:'Judge the decision, not the outcome. Given what you knew and the time you had, was the reasoning sound?' },
          { k:'listen', t:'mc', q:'37. According to the professor, what happens if you learn only from results?', o:['You improve faster','You will draw the wrong lesson about half the time','You become too cautious','Nothing changes'], c:1, e:'«you will draw the wrong lesson roughly half the time».', a:'Some good decisions end badly and some careless ones end well. Learn only from results and you will draw the wrong lesson roughly half the time.' }
        ] },
      { title:'Conversation 2 & Lecture 3 (Questions 38–48)', ins:'Listen to each item and choose the best answer.', vi:'Câu 38–48: Hội thoại phòng thí nghiệm và bài giảng sinh học.',
        qs:[
          { k:'listen', t:'mc', q:'38. Why does the student email the professor?', o:['To ask for an extension','To report broken equipment','To join a research group','To change supervisor'], c:2, e:'«I read your paper and wondered whether you take undergraduates».', a:'Professor, I read your paper on soil bacteria and wondered whether you ever take undergraduates in the lab.' },
          { k:'listen', t:'mc', q:'39. What does the professor ask about first?', o:['The student’s grades','Whether the student can commit regular hours','The student’s year of study','The student’s funding'], c:1, e:'«can you give me the same six hours every week?»', a:'The first question is not grades. Can you give me the same six hours every week for a whole term?' },
          { k:'listen', t:'mc', q:'40. Why does the professor emphasise regularity?', o:['Because experiments run on fixed schedules','Because the lab is small','Because of safety rules','Because of funding rules'], c:0, e:'«cultures do not wait for your timetable».', a:'Cultures do not wait for your timetable. If nobody feeds them on Thursday, Thursday is lost.' },
          { k:'listen', t:'mc', q:'41. What task does the professor offer the student at first?', o:['Designing an experiment','Washing and preparing equipment','Writing a paper','Teaching first-years'], c:1, e:'«you would start with preparation and cleaning».', a:'You would start with preparation and cleaning. It sounds dull. It is also where you learn what contamination looks like.' },
          { k:'listen', t:'mc', q:'42. How does the student react?', o:['Disappointed','Willing, and asks when to start','Confused','Uninterested'], c:1, e:'«That is fine. When can I start?»', a:'That is fine. Honestly, I just want to be in the room. When can I start?' },
          { k:'listen', t:'mc', q:'43. What is the lecture mainly about?', o:['Bird migration','How gut bacteria affect digestion','Plant growth','Insect vision'], c:1, e:'«what your gut bacteria actually do for you».', a:'So: what your gut bacteria actually do for you, and why the answer keeps changing.' },
          { k:'listen', t:'mc', q:'44. According to the lecturer, gut bacteria help break down', o:['proteins only','fibre that human enzymes cannot digest','fats only','vitamins'], c:1, e:'«fibre that our own enzymes cannot touch».', a:'They break down fibre that our own enzymes cannot touch, and they release compounds we then absorb.' },
          { k:'listen', t:'mc', q:'45. Why does the lecturer mention antibiotics?', o:['They cure all infections','They reduce bacterial diversity for months','They improve digestion','They are no longer used'], c:1, e:'«diversity can stay reduced for months afterwards».', a:'A course of antibiotics does its job, but diversity can stay reduced for months afterwards.' },
          { k:'listen', t:'mc', q:'46. What does the lecturer say about probiotic products?', o:['They always work','Effects depend on the strain and are often overstated','They are dangerous','They replace a healthy diet'], c:1, e:'«the effect depends on the strain, and the marketing rarely says which».', a:'As for probiotics — the effect depends on the strain, and the marketing rarely says which one it is.' },
          { k:'listen', t:'mc', q:'47. What does the lecturer recommend as the best-supported advice?', o:['Taking supplements daily','Eating a wide range of plant foods','Avoiding all bacteria','Fasting regularly'], c:1, e:'«the dullest advice is the best supported: eat a wide range of plants».', a:'The dullest advice turns out to be the best supported: eat a wide range of plants.' },
          { k:'listen', t:'mc', q:'48. What is the lecturer’s attitude towards current knowledge in this field?', o:['Confident that it is settled','Cautious, noting the answers keep changing','Dismissive of the whole field','Only interested in medicine'], c:1, e:'«why the answer keeps changing» và giọng thận trọng suốt bài.', a:'Be careful with anything that sounds certain here. Five years is a long time in this field.' }
        ] } ] },

    { id:'writing', name:'Writing', vi:'Viết · 2 task · 29 phút', parts:[
      { title:'Integrated Writing Task — 20 minutes', ins:'Read the passage, listen to the lecture, then write 150–225 words summarising the points made in the lecture and explaining how they cast doubt on the reading.', vi:'Task 1 (20 phút, 150–225 từ): tóm tắt ý bài giảng và giải thích chúng phản bác bài đọc thế nào.',
        qs:[
          { k:'listen', t:'essay', min:150, words:['lecture','reading'],
            q:'READING PASSAGE (3 minutes)\n\nMany cities are replacing on-street parking with cycle lanes. Supporters give three arguments. First, cycle lanes move more people in the same space: a lane of parked cars serves a handful of drivers, while a cycle lane can carry several thousand riders a day. Second, local shops benefit, because cyclists stop more often and spend more per month than drivers passing through. Third, the change is cheap: paint and bollards cost a fraction of any new road.',
            a:'Now listen to part of a lecture on this topic. — The reading gives three reasons, and each needs qualifying. On capacity: a cycle lane can carry thousands of riders, but only where enough people are willing and able to cycle. In a hilly city, or one where the average trip is fifteen kilometres, that lane may carry a few hundred, and the capacity argument collapses. Second, the claim about shops. The studies behind it were mostly done in dense inner districts where customers already live nearby. Repeat the same study in an outer suburb where people arrive by car with a boot to fill, and the result reverses. Third, cost. Paint and bollards are indeed cheap, and that is exactly the problem. Cheap lanes are narrow, badly protected and often blocked, so they attract only the confident riders who were cycling anyway. The lanes that actually change behaviour are physically separated, need drainage and signalling, and cost far more than the reading suggests.',
            e:'Bài giảng không bác bỏ hoàn toàn mà thêm điều kiện cho từng luận điểm: sức chở phụ thuộc địa hình và cự ly; nghiên cứu về cửa hàng chỉ đúng ở khu nội đô đông đúc; và làn rẻ tiền thì không đổi được hành vi.' }
        ] },
      { title:'Writing for an Academic Discussion — 10 minutes', ins:'Read the discussion and write a response of at least 100 words that contributes your own opinion.', vi:'Task 2 (10 phút, tối thiểu 100 từ): tham gia thảo luận học thuật, nêu quan điểm riêng có lập luận.',
        qs:[
          { t:'essay', min:100, words:['I','because'],
            q:'PROFESSOR: This week we are discussing assessment. Some universities have replaced final examinations with continuous coursework; others have kept exams and argue that coursework rewards the students with the most free time. In your view, which system assesses learning more fairly, and why?\n\nMAI: Coursework is fairer. An exam measures how you performed on one morning, and a bad morning can undo a year of work.\n\nTOM: I disagree. Coursework quietly favours students who are not working twenty hours a week to pay rent. An exam at least gives everyone the same three hours.',
            e:'Bài đạt điểm cao thường: nêu rõ lập trường, phản hồi TRỰC TIẾP tên một bạn trong thảo luận, thêm một lý do hoặc ví dụ MỚI chưa ai nói, và giữ trong khoảng 100–140 từ.' }
        ] } ] }
  ]
}
,
{
  id:'toefl-ibt-3', lang:'en', level:'toefl', badge:'TOEFL · iBT', title:'Đề thi thử TOEFL iBT — Đề 3',
  official:'Đúng cấu trúc phần làm trên máy: Reading 20 câu (35′) · Listening 28 câu (36′) · Writing 2 task (29′). Speaking 4 task nói vào micro — luyện ở màn «Luyện nói». Tổng điểm quy về thang 0–120.',
  minutes:100, maxScore:120, pass:0, passEach:0, plays:1,
  sections:[
    { id:'reading', name:'Reading', vi:'Đọc hiểu · 20 câu · 35 phút', parts:[
      { title:'Passage 1 — Why Writing Systems Are Borrowed', ins:'Read the passage and answer Questions 1–10.', vi:'Câu 1–10: Đọc bài về nguồn gốc các hệ chữ viết.',
        qs:[
          { t:'mc', q:'1. According to paragraph 1, how many times has writing been invented independently?', o:['Only once','Three or four times','Dozens of times','It is unknown'], c:1, e:'most scholars accept three or four independent cases.', p:'WHY WRITING SYSTEMS ARE BORROWED, NOT INVENTED\n\n[1] Writing has been invented from nothing only a handful of times in human history — most scholars accept three or four independent cases. Every other script on earth, including the alphabet used for this sentence, descends from one of those few origins by borrowing and adaptation.\n\n[2] The reason is that inventing writing is extraordinarily hard, while adapting it is merely difficult. An inventor must first grasp that speech can be broken into repeatable units, then decide which units to record, then persuade others that the marks mean anything at all. A borrower faces none of these problems. The idea arrives already proven.\n\n[3] Borrowing is rarely tidy, because a script fitted to one language usually suits the next one badly. When the Greeks took the Phoenician consonantal script, they found themselves with symbols for sounds their language did not use. Rather than discard them, they reassigned several to vowels — a change that was almost accidental and that turned out to matter enormously.\n\n[4] Similar adjustments occur wherever a script travels. Japanese borrowed Chinese characters for a language of a completely different structure and had to develop two additional syllabic systems to write the grammatical endings that Chinese characters could not represent. The result is a writing system of unusual complexity, produced not by design but by accumulated repair.\n\n[5] This history has a consequence that is easy to miss. Because scripts are inherited rather than designed, the awkward features of a writing system are usually fossils: records of a decision taken for a different language, in another century, by people who were not thinking about us at all.' },
          { t:'mc', q:'2. Why does the author say inventing writing is harder than adapting it?', o:['Because materials were scarce','Because the inventor must realise speech can be broken into units and convince others','Because early societies were small','Because there were no teachers'], c:1, e:'Đoạn 2 liệt kê ba việc người phát minh phải làm, còn người vay mượn thì không.' },
          { t:'mc', q:'3. The phrase "arrives already proven" in paragraph 2 means the borrowed idea', o:['is difficult to use','has been shown to work','is officially approved','is very old'], c:1, e:'Người vay mượn nhận được ý tưởng đã được chứng minh là dùng được.' },
          { t:'mc', q:'4. What problem did the Greeks face with the Phoenician script?', o:['It had too few symbols','It had symbols for sounds Greek did not use','It was written right to left','It was too decorative'], c:1, e:'they found themselves with symbols for sounds their language did not use.' },
          { t:'mc', q:'5. How does the author characterise the Greek reassignment of symbols to vowels?', o:['Carefully planned','Almost accidental but very consequential','A complete failure','Copied from Egypt'], c:1, e:'a change that was almost accidental and that turned out to matter enormously.' },
          { t:'mc', q:'6. Why did Japanese need additional syllabic systems?', o:['Chinese characters were too few','Chinese characters could not represent Japanese grammatical endings','Chinese characters were banned','Writing brushes were unavailable'], c:1, e:'to write the grammatical endings that Chinese characters could not represent.' },
          { t:'mc', q:'7. The phrase "accumulated repair" in paragraph 4 suggests the system was', o:['designed from scratch','built up through successive fixes','repaired by scholars','abandoned and rebuilt'], c:1, e:'produced not by design but by accumulated repair — chắp vá dần.' },
          { t:'tf', q:'8. The passage states that awkward features of scripts were designed deliberately for modern users.', o:['Đúng','Sai'], c:1, e:'Đoạn 5 nói ngược lại: chúng là «hoá thạch» của quyết định cho ngôn ngữ khác, thế kỷ khác.' },
          { t:'mc', q:'9. The word "fossils" in paragraph 5 is used to mean', o:['very old bones','leftover traces of earlier decisions','mistakes','decorations'], c:1, e:'records of a decision taken for a different language, in another century.' },
          { t:'mc', q:'10. What is the main purpose of the passage?', o:['To praise the alphabet','To explain why writing systems are inherited and therefore imperfect','To compare Greek and Japanese','To argue for spelling reform'], c:1, e:'Toàn bài giải thích cơ chế vay mượn và hệ quả của nó.' }
        ] },
      { title:'Passage 2 — The Economics of Repair', ins:'Read the passage and answer Questions 11–20.', vi:'Câu 11–20: Đọc bài về kinh tế của việc sửa chữa.',
        qs:[
          { t:'mc', q:'11. According to paragraph 1, the decline of repair is usually blamed on', o:['rising wages','poor modern manufacturing','a lack of workshops','government policy'], c:1, e:'often blamed on shoddy modern manufacturing — nhưng tác giả không đồng ý.', p:'THE ECONOMICS OF REPAIR\n\n[1] Until the middle of the twentieth century, most manufactured goods were repaired several times before being discarded. Shoes were resoled, radios were rewired, and every town had at least one workshop for each. The decline of repair is often blamed on shoddy modern manufacturing, but the main cause is arithmetic.\n\n[2] Repair is labour, and labour costs rose steadily through the century while manufacturing costs fell. A toaster that took two hours of skilled work to fix and forty minutes of automated assembly to build will not be repaired, no matter how strongly the owner feels about waste. The decision is made by the wage rate, not by attitude.\n\n[3] Design has magnified the effect. Components glued rather than screwed, batteries sealed into cases and parts sold only as whole assemblies all raise the labour cost of repair without lowering the price of the product much. Manufacturers rarely do this out of malice; it is simply cheaper to assemble a device that was never meant to be opened.\n\n[4] Recent legislation in several countries has tried to reverse the trend by requiring spare parts to be available for a fixed number of years and repair manuals to be published. Early evidence suggests these rules change design more than they change consumer behaviour: manufacturers redesign for compliance, while most owners still replace rather than repair.\n\n[5] The most effective interventions may therefore be the least dramatic. Community repair workshops, where volunteers fix items for free, do not solve the arithmetic — they simply move the labour outside the market, where the wage rate does not apply.' },
          { t:'mc', q:'12. What does the author say is the main cause instead?', o:['Arithmetic: the relative cost of labour and manufacturing','Consumer laziness','Lack of spare parts','Advertising'], c:0, e:'the main cause is arithmetic.' },
          { t:'mc', q:'13. The toaster example is used to show that', o:['toasters break often','the wage rate, not attitude, decides whether repair happens','automation is unreliable','repairs are dangerous'], c:1, e:'The decision is made by the wage rate, not by attitude.' },
          { t:'mc', q:'14. According to paragraph 3, which design choice raises repair costs?', o:['Using screws','Gluing components and sealing batteries','Publishing manuals','Using metal cases'], c:1, e:'Components glued rather than screwed, batteries sealed into cases.' },
          { t:'mc', q:'15. What does the author say about manufacturers’ motives?', o:['They deliberately sabotage repair','It is simply cheaper to assemble sealed devices','They follow government orders','They want to help recyclers'], c:1, e:'rarely do this out of malice; it is simply cheaper.' },
          { t:'mc', q:'16. What has recent legislation required?', o:['Free repairs','Spare parts availability and published manuals','A ban on glue','Longer warranties only'], c:1, e:'requiring spare parts to be available… and repair manuals to be published.' },
          { t:'mc', q:'17. According to paragraph 4, what has this legislation mainly changed so far?', o:['Consumer behaviour','Product design','Prices','Recycling rates'], c:1, e:'these rules change design more than they change consumer behaviour.' },
          { t:'tf', q:'18. The passage claims community repair workshops solve the underlying economic problem.', o:['Đúng','Sai'], c:1, e:'do not solve the arithmetic — they simply move the labour outside the market.' },
          { t:'mc', q:'19. Why do community workshops work despite the arithmetic?', o:['They use cheaper parts','The labour is volunteered, so the wage rate does not apply','They repair only new items','They receive subsidies'], c:1, e:'move the labour outside the market, where the wage rate does not apply.' },
          { t:'mc', q:'20. The author’s overall approach in this passage is to', o:['blame manufacturers','replace a common explanation with an economic one','argue for banning new products','describe the history of shoes'], c:1, e:'Bài thay lời giải thích quen thuộc (hàng kém) bằng lời giải thích kinh tế (giá nhân công).' }
        ] } ] },

    { id:'listening', name:'Listening', vi:'Nghe hiểu · 28 câu · 36 phút', parts:[
      { title:'Conversation 1 — Student and Careers Adviser (Questions 21–25)', ins:'Listen to each item and choose the best answer.', vi:'Câu 21–25: Hội thoại với cố vấn nghề nghiệp.',
        qs:[
          { k:'listen', t:'mc', q:'21. Why has the student come to the careers office?', o:['To find a part-time job','To ask whether to accept an unpaid internship','To change degree course','To get a reference letter'], c:1, e:'«I have been offered an internship, but it is unpaid».', a:'Come in. What can I do for you? — I have been offered a summer internship at a museum, but it is unpaid, and I am not sure whether to take it.' },
          { k:'listen', t:'mc', q:'22. What is the student’s main worry?', o:['The work is boring','Losing paid work over the summer','The location','The length of the internship'], c:1, e:'«I usually earn my rent money in the summer».', a:'The problem is that I usually earn my rent money in the summer. If I do this, I have nothing coming in for ten weeks.' },
          { k:'listen', t:'mc', q:'23. What does the adviser ask the student to find out?', o:['Whether expenses are covered','Whether the museum is hiring','Who else applied','The dress code'], c:0, e:'«ask whether they cover travel and lunch — many do».', a:'First, go back and ask whether they cover travel and lunch. Many do, and it is never in the advert.' },
          { k:'listen', t:'mc', q:'24. What alternative does the adviser mention?', o:['A shorter arrangement of three days a week','An online course','A different museum','Applying next year'], c:0, e:'«ask if they would take you three days a week».', a:'Second, ask if they would take you three days a week instead of five. Then you can keep a paid job on the other two.' },
          { k:'listen', t:'mc', q:'25. What does the adviser say about unpaid internships in general?', o:['They are always worth taking','They are worth it only if the work is real and named on a CV','They should never be accepted','They are illegal'], c:1, e:'«worth it if you come out with something you can point to».', a:'And be honest with yourself. It is worth it if you come out with something you can point to on a CV. It is not worth it if you spend ten weeks photocopying.' }
        ] },
      { title:'Lecture 1 — Music History (Questions 26–31)', ins:'Listen to each item and choose the best answer.', vi:'Câu 26–31: Bài giảng lịch sử âm nhạc.',
        qs:[
          { k:'listen', t:'mc', q:'26. What is the lecture mainly about?', o:['How recording changed the way music is performed','The invention of the piano','Opera in the nineteenth century','Music education'], c:0, e:'«what recording did to performance».', a:'Today, not the history of recording technology, but what recording did to performance itself.' },
          { k:'listen', t:'mc', q:'27. Before recording, how did performers treat a written score?', o:['As an exact instruction','As a framework to be varied','As a secret document','As a teaching aid only'], c:1, e:'«the score was a starting point; ornament was expected».', a:'Before recording, the score was a starting point. Ornament was expected. Two performances of the same piece could differ substantially, and nobody thought that improper.' },
          { k:'listen', t:'mc', q:'28. What effect did recordings have on interpretation?', o:['Performances became more varied','Performances converged towards a standard','Scores were rewritten','Ornament increased'], c:1, e:'«everyone hears the same famous recording and drifts towards it».', a:'Once a recording exists, everyone hears the same famous version and drifts towards it. Interpretation narrows.' },
          { k:'listen', t:'mc', q:'29. What does the professor say about mistakes?', o:['They became more acceptable','They became far less tolerated','They were edited out of live concerts','They never mattered'], c:1, e:'«a spliced record has no wrong notes, and audiences began to expect that».', a:'And a spliced record has no wrong notes. Audiences began to expect that live, which is a standard no human ever had to meet before.' },
          { k:'listen', t:'mc', q:'30. Why does the professor mention early jazz recordings?', o:['To show recordings preserved improvisation but also froze it','To criticise jazz musicians','To compare volume levels','To date the first recording'], c:0, e:'«a solo invented once and then copied by everyone who bought the record».', a:'Jazz is the clearest case: a solo invented once, in one afternoon, then copied note for note by everyone who bought the record.' },
          { k:'listen', t:'mc', q:'31. What is the professor’s overall view?', o:['Recording was purely harmful','Recording preserved music but narrowed how it is played','Recording had no effect','Recording should be banned'], c:1, e:'Giọng của bài: vừa lưu giữ vừa thu hẹp.', a:'So recording preserved more music than any archive ever could, and at the same time made us play it in fewer ways.' }
        ] },
      { title:'Lecture 2 — Sleep Science (Questions 32–37)', ins:'Listen to each item and choose the best answer.', vi:'Câu 32–37: Bài giảng khoa học giấc ngủ.',
        qs:[
          { k:'listen', t:'mc', q:'32. What misconception does the lecturer begin by correcting?', o:['That sleep is a single uniform state','That sleep is unnecessary','That dreams predict the future','That naps are harmful'], c:0, e:'«sleep is not one thing; it is several states in a cycle».', a:'First, a correction. Sleep is not one thing. It is several distinct states, cycling roughly every ninety minutes.' },
          { k:'listen', t:'mc', q:'33. Which stage is associated with consolidating factual memory?', o:['REM sleep','Deep slow-wave sleep','Light stage-one sleep','Waking rest'], c:1, e:'«deep slow-wave sleep is where facts get filed».', a:'Deep slow-wave sleep, mostly in the first half of the night, is where facts get filed.' },
          { k:'listen', t:'mc', q:'34. What does the lecturer say REM sleep appears to do?', o:['Repair muscle','Connect ideas and process emotion','Lower body temperature','Nothing measurable'], c:1, e:'«REM connects things and takes the sting out of memories».', a:'REM, which dominates the second half, connects things — and seems to take the emotional sting out of memories while keeping the content.' },
          { k:'listen', t:'mc', q:'35. Why is cutting sleep short particularly costly?', o:['You lose mostly deep sleep','You lose mostly REM, because REM comes later','You lose both equally','It has no effect'], c:1, e:'«cut two hours off the end and you cut mostly REM».', a:'This matters practically. Cut two hours off the end of your night and you are not losing an even slice — you are cutting mostly REM.' },
          { k:'listen', t:'mc', q:'36. What does the lecturer say about catching up at weekends?', o:['It fully restores the deficit','It helps a little but does not fully restore performance','It is dangerous','It is the best strategy'], c:1, e:'«you recover some, not all».', a:'Weekend catch-up helps. You recover some of it, not all, and the studies are fairly consistent on that.' },
          { k:'listen', t:'mc', q:'37. What practical advice does the lecturer end with?', o:['Sleep more at weekends','Keep the wake-up time constant','Nap every afternoon','Avoid all screens'], c:1, e:'«the single most useful habit is a constant wake time».', a:'If you take one habit from today, take this: a constant wake time. The body clock is set by when you get up, not by when you go to bed.' }
        ] },
      { title:'Conversation 2 & Lecture 3 (Questions 38–48)', ins:'Listen to each item and choose the best answer.', vi:'Câu 38–48: Hội thoại nhóm bài tập và bài giảng kiến trúc.',
        qs:[
          { k:'listen', t:'mc', q:'38. What problem do the two students discuss?', o:['A group member has not contributed','The deadline moved','The topic is too broad','They lost their notes'], c:0, e:'«Duc has not sent anything for two weeks».', a:'Have you heard from Duc? — No. He has not sent anything for two weeks, and the presentation is on Friday.' },
          { k:'listen', t:'mc', q:'39. What does the first student suggest doing?', o:['Reporting him immediately','Messaging him with a specific small task and a deadline','Doing his part quietly','Changing groups'], c:1, e:'«give him one small thing with a date».', a:'Before we tell anyone, let us give him one small thing with a date. «Send us three slides by Wednesday.» Vague reminders never work.' },
          { k:'listen', t:'mc', q:'40. Why does the second student hesitate?', o:['She thinks it is unfair to cover for him','She does not have his number','She is behind herself','She dislikes presentations'], c:0, e:'«I do not want to end up doing his section at midnight».', a:'Fine, but I do not want to end up doing his section at midnight on Thursday. That happened last term.' },
          { k:'listen', t:'mc', q:'41. What do they agree to do if there is no reply?', o:['Present without him','Email the tutor before the deadline, not after','Postpone','Split his part secretly'], c:1, e:'«email the tutor on Wednesday, not on Friday».', a:'Then we email the tutor on Wednesday, not on Friday. Tutors can help before a deadline. Afterwards they can only sympathise.' },
          { k:'listen', t:'mc', q:'42. What does this conversation illustrate about group work?', o:['It is always unfair','Acting early and specifically is better than waiting','Groups should be smaller','Tutors are unhelpful'], c:1, e:'Cả hai điểm: nhiệm vụ cụ thể + báo sớm.', a:'Right. Specific task, clear date, and tell someone early. That is all we can do.' },
          { k:'listen', t:'mc', q:'43. What is the lecture mainly about?', o:['Why some buildings feel comfortable','The history of concrete','Building regulations','Famous architects'], c:0, e:'«why some rooms feel right and others do not».', a:'Today: why some rooms feel right the moment you walk in, and others never do, even when nothing is obviously wrong.' },
          { k:'listen', t:'mc', q:'44. According to the lecturer, ceiling height affects', o:['temperature only','the kind of thinking people do','acoustics only','lighting cost'], c:1, e:'«high ceilings push people towards abstract thinking».', a:'There is decent evidence that high ceilings push people towards abstract, exploratory thinking, and low ones towards focused, detailed work.' },
          { k:'listen', t:'mc', q:'45. What does the lecturer say about daylight?', o:['It matters less than artificial light','Its direction and change through the day matter, not just quantity','It should be avoided in offices','It is impossible to measure'], c:1, e:'«a room with light from two sides feels different».', a:'And daylight is not just a quantity. A room lit from two sides, where the light changes through the day, feels different from one lit evenly from above.' },
          { k:'listen', t:'mc', q:'46. Why does the lecturer mention corridors?', o:['They waste space','A view of something distant reduces the sense of confinement','They are hard to heat','They should be removed'], c:1, e:'«give a corridor a window at the end and it stops feeling like a tunnel».', a:'Give a corridor a window at the far end and it stops feeling like a tunnel. The distance is what does it, not the light.' },
          { k:'listen', t:'mc', q:'47. What does the lecturer warn students about?', o:['Copying famous buildings','Treating these findings as fixed rules','Using computers','Working alone'], c:1, e:'«these are tendencies, not rules».', a:'A warning: these are tendencies measured across groups, not rules. Design from them, do not obey them.' },
          { k:'listen', t:'mc', q:'48. What will students do in the next session?', o:['Visit a site and record their reactions','Sit an exam','Watch a film','Meet an architect'], c:0, e:'«next week we walk through the building and write down what we notice».', a:'Next week we walk through this building together and write down what we notice before we analyse anything.' }
        ] } ] },

    { id:'writing', name:'Writing', vi:'Viết · 2 task · 29 phút', parts:[
      { title:'Integrated Writing Task — 20 minutes', ins:'Read the passage, listen to the lecture, then write 150–225 words summarising the points made in the lecture and explaining how they cast doubt on the reading.', vi:'Task 1 (20 phút, 150–225 từ): tóm tắt ý bài giảng và giải thích chúng phản bác bài đọc thế nào.',
        qs:[
          { k:'listen', t:'essay', min:150, words:['lecture','reading'],
            q:'READING PASSAGE (3 minutes)\n\nSeveral universities have replaced lectures with recorded videos that students watch before class. Supporters offer three arguments. First, students can pause and rewatch difficult explanations, which a live lecture does not allow. Second, class time is freed for discussion and problem solving, which is where deeper learning happens. Third, recordings help students who cannot attend because of work, illness or distance, making the course more equitable.',
            a:'Now listen to part of a lecture on this topic. — Each of those three claims needs looking at. Take pausing first. The ability to pause only helps students who actually use it, and the recordings show that most watch straight through at increased speed, often the night before. The feature exists; the behaviour it assumes does not. Second, the freed class time. That only becomes discussion if the students arrive having watched the video, and attendance data from several courses shows between a third and a half do not. The seminar then turns into a repeat of the lecture, which is the worst of both systems. Third, equity. Recordings genuinely help students who cannot attend, and I would not argue with that. But the same studies find that students with unstable internet or no quiet space at home fall further behind, because the work has been moved from a place the university provides into homes it does not control. So the equity effect runs in both directions at once.',
            e:'Cấu trúc bài giảng: giữ nguyên ba luận điểm nhưng thêm điều kiện — tính năng tạm dừng chỉ có tác dụng nếu người học thật sự dùng; giờ thảo luận chỉ có nghĩa nếu sinh viên đã xem trước; và công bằng thì có hai chiều.' }
        ] },
      { title:'Writing for an Academic Discussion — 10 minutes', ins:'Read the discussion and write a response of at least 100 words that contributes your own opinion.', vi:'Task 2 (10 phút, tối thiểu 100 từ): tham gia thảo luận học thuật, nêu quan điểm riêng có lập luận.',
        qs:[
          { t:'essay', min:100, words:['I','because'],
            q:'PROFESSOR: This week we consider public transport funding. Some cities have made buses and trams free at the point of use, paid for from general taxation. Others argue that fares should be kept and the money spent on running more services. Which approach would you support in your own city, and why?\n\nLINH: Free transport, clearly. Fares hit the people with the least money hardest, and collecting them costs a surprising amount in machines and staff.\n\nSAM: I would keep fares but make them very cheap. A free service with a bus every forty minutes is not much use to anyone who has to get to work on time.',
            e:'Bài điểm cao: chọn rõ một phía, phản hồi đích danh Linh hoặc Sam, thêm một lý do MỚI (ví dụ: chi phí thu vé so với chi phí vận hành, hay tác động lên tắc đường), và kết bằng một điều kiện cụ thể cho thành phố của mình.' }
        ] } ] }
  ]
}
];

if (typeof module !== 'undefined'){ module.exports = { TOEFL_EXAMS, TOEFL_SCALE, toeflScale }; }
