/* ============================================================
   LangLab — Đề thi thử TOEFL iBT
   Do LangLab tự biên soạn theo dạng thức TOEFL iBT (ets.org),
   KHÔNG phải đề thi chính thức của ETS.

   Cấu trúc phần làm trên máy trong app:
     Reading    20 câu · 35 phút · 2 bài đọc học thuật
     Listening  28 câu · 36 phút · 2 hội thoại + 3 bài giảng
     Writing     2 task · 29 phút (Integrated 20′ · Academic Discussion 10′)
   Phần Speaking gồm 4 task nói vào micro — luyện ở màn «Luyện nói».

   Quy đổi: mỗi phần quy về thang 0–30, tổng 0–120 (TOEFL_SCALE).
   ============================================================ */

/* Quy đổi điểm thô sang thang 30 của từng phần (ước lượng theo bảng công bố của ETS) */
const TOEFL_SCALE = {
  reading:   [[20,30],[19,29],[18,28],[17,26],[16,25],[15,23],[14,22],[13,20],[12,18],[11,17],[10,15],[9,13],[8,11],[7,9],[6,7],[5,5],[4,3],[3,2],[2,1]],
  listening: [[28,30],[27,29],[26,28],[25,27],[24,26],[23,25],[22,23],[21,22],[20,21],[19,20],[18,18],[17,17],[16,15],[15,14],[14,13],[13,11],[12,10],[10,7],[8,5],[6,3],[4,1]]
};
function toeflScale(raw, kind){
  const t = TOEFL_SCALE[kind] || TOEFL_SCALE.reading;
  for (let i = 0; i < t.length; i++) if (raw >= t[i][0]) return t[i][1];
  return 0;
}

const TOEFL_EXAMS = [

{
  id:'toefl-ibt-1', lang:'en', level:'toefl', badge:'TOEFL · iBT', title:'Đề thi thử TOEFL iBT — Đề 1',
  official:'Đúng cấu trúc phần làm trên máy: Reading 20 câu (35′) · Listening 28 câu (36′) · Writing 2 task (29′). Speaking 4 task nói vào micro — luyện ở màn «Luyện nói». Tổng điểm quy về thang 0–120.',
  minutes:100, maxScore:300, pass:180, passEach:0, plays:1,
  sections:[
    { id:'R', name:'Reading', vi:'Đọc · 20 câu · 35 phút', parts:[
      { title:'Passage 1 — The Domestication of the Horse', ins:'Read the passage and answer Questions 1–10.', vi:'Câu 1–10: Đọc bài về việc thuần hoá ngựa.',
        qs:[
          { t:'mc', q:'1. According to paragraph 1, the main obstacle to identifying early domestication is that', o:['horse bones decay quickly.','domesticated and wild bones look almost identical.','few horse bones survive from that period.','the sites have never been excavated.'], c:1,
            p:'THE DOMESTICATION OF THE HORSE\n\n[1] Establishing when horses were first domesticated has proved unusually difficult. Unlike cattle or sheep, whose skeletons changed noticeably within a few generations of domestication, early domestic horses were anatomically almost indistinguishable from wild ones. A bone from a tamed horse and a bone from a hunted horse can look the same under a microscope, and for decades this meant that archaeologists were arguing about evidence that could not settle the question.\n\n[2] Three lines of indirect evidence eventually broke the deadlock. The first was bit wear. A metal or rope bit held in the mouth leaves a characteristic pattern of damage on the second premolar, and this pattern does not occur in wild populations. The second was the shape of the herd. In a hunted population, the remains are dominated by young adults, because hunters take the animals they can catch; in a managed herd, the age profile is broader and includes old animals that were kept for breeding. The third was chemical: residues absorbed into the walls of clay pots have been shown to include mare’s milk, which no hunter could obtain.\n\n[3] Taken together, this evidence points to the steppe grasslands north of the Black Sea, around five and a half thousand years ago. The date remains contested, and some researchers argue for a slightly later and more western origin, but the region is now widely accepted.\n\n[4] The consequences were out of all proportion to the animal. A person on foot travels perhaps thirty kilometres a day; a rider covers three times that and arrives able to fight. Herding, which had previously limited a family to the number of animals it could watch on foot, became possible on a far larger scale. Trade routes lengthened. So did the reach of disease, and of language: the spread of the Indo-European languages across Eurasia is now thought to be linked, though not simply, to the mobility that horses allowed.\n\n[5] It is worth noting what domestication did not immediately produce. Riding appears to have come first, but the evidence for horses pulling wheeled vehicles is a thousand years later, and cavalry as an organised military force is later still. The technologies that made the horse decisive in warfare — the chariot, the saddle, the stirrup — were each separated by centuries. The animal was available long before people worked out what to do with it.',
            e:'Đoạn [1]: «early domestic horses were anatomically almost indistinguishable from wild ones».' },
          { t:'mc', q:'2. The word «deadlock» in paragraph 2 is closest in meaning to', o:['a situation with no progress','a violent argument','a locked container','a written agreement'], c:0, e:'deadlock = bế tắc, không tiến triển được.' },
          { t:'mc', q:'3. Bit wear is useful as evidence because it', o:['appears on all horse bones.','is easy to date precisely.','does not occur in wild horses.','shows the age of the animal.'], c:2, e:'«this pattern does not occur in wild populations».' },
          { t:'mc', q:'4. According to paragraph 2, the age profile of a hunted population is dominated by', o:['very old animals.','young adults.','newborn foals.','males only.'], c:1, e:'«the remains are dominated by young adults».' },
          { t:'mc', q:'5. Traces of mare’s milk are significant because they show that horses were', o:['eaten rather than ridden.','kept and milked rather than hunted.','traded over long distances.','used to pull vehicles.'], c:1, e:'«mare’s milk, which no hunter could obtain» → phải nuôi mới vắt sữa được.' },
          { t:'mc', q:'6. What does the author say about the date of domestication?', o:['It is now agreed by all researchers.','It is still disputed by some researchers.','It has been shown to be much earlier.','It cannot be estimated at all.'], c:1, e:'«The date remains contested».' },
          { t:'mc', q:'7. According to paragraph 4, a rider could travel about', o:['thirty kilometres a day.','sixty kilometres a day.','ninety kilometres a day.','one hundred and fifty kilometres a day.'], c:2, e:'«a rider covers three times that» — ba lần 30 km = 90 km.' },
          { t:'mc', q:'8. The author mentions the spread of Indo-European languages in order to', o:['prove that horses originated in Europe.','illustrate a consequence of increased mobility.','question the dating of domestication.','contrast language with disease.'], c:1, e:'Ngôn ngữ được nêu như một hệ quả của khả năng di chuyển.' },
          { t:'mc', q:'9. Paragraph 5 emphasises that', o:['riding and driving developed at the same time.','the military use of horses came long after domestication.','chariots were invented before riding.','the stirrup was the earliest invention.'], c:1, e:'«cavalry as an organised military force is later still».' },
          { t:'mc', q:'10. Which sentence best expresses the main idea of the passage?', o:['Horses were domesticated much earlier than cattle.','Indirect evidence resolved a long-standing problem, and the consequences of domestication unfolded slowly.','Bit wear is the only reliable evidence of domestication.','Horses were more important for trade than for war.'], c:1, e:'Bài trình bày ba loại chứng cứ gián tiếp rồi nói hệ quả diễn ra dần qua nhiều thế kỷ.' }
        ] },
      { title:'Passage 2 — Why Some Species Become Invasive', ins:'Read the passage and answer Questions 11–20.', vi:'Câu 11–20: Đọc bài về loài xâm lấn.',
        qs:[
          { t:'mc', q:'11. According to paragraph 1, most introduced species', o:['become invasive within a decade.','fail to establish at all.','are introduced deliberately.','spread faster than native species.'], c:1,
            p:'WHY SOME SPECIES BECOME INVASIVE\n\n[1] Of every hundred species carried by humans into a new region, the great majority simply die. Of those that survive, most establish small, unremarkable populations that never spread. Only a handful — the figure often quoted is around one in a thousand — become what ecologists call invasive: abundant, widespread and damaging. Explaining why that handful behaves so differently is one of the oldest unsolved problems in ecology.\n\n[2] The most influential early explanation was the enemy release hypothesis. A species arriving in a new region leaves behind the predators, parasites and diseases that limited it at home. Freed from these controls, it can allocate to growth and reproduction the resources it previously spent on defence. The hypothesis has clear supporting cases: several plants introduced to North America carry far fewer insect herbivores there than in their native range, and grow correspondingly larger.\n\n[3] Yet enemy release cannot be the whole story, since every introduced species enjoys it and only a few become invasive. Attention has therefore shifted to what the arriving species does that the residents cannot. Some invaders exploit a resource nobody else is using; others change the environment itself. A grass that burns readily, for example, can convert a shrubland into a fire-prone grassland in which it thrives and its competitors do not. In such cases the invader is not simply winning a competition but altering the rules of the game.\n\n[4] Timing matters as much as biology. Analyses of invasion records show that the strongest single predictor of establishment is not any trait of the species but propagule pressure — the number of individuals released and the number of separate release events. A species introduced once, in small numbers, usually fails however well adapted it is; the same species introduced repeatedly over decades usually succeeds. This finding is uncomfortable, because it suggests that much of what looks like biological superiority is in fact an accident of trade volume.\n\n[5] There is also a time lag that complicates every attempt at prediction. Many invasions begin with a long quiet phase — sometimes fifty years or more — during which the population is small and apparently harmless, before expanding rapidly. A management agency looking at a newly established population therefore has very little information on which to act, and the cost of acting is immediate while the benefit is distant and uncertain. It is precisely this asymmetry, rather than any scientific disagreement, that explains why so few invasions are stopped early.',
            e:'Đoạn [1]: «the great majority simply die» và chỉ khoảng một phần nghìn thành xâm lấn.' },
          { t:'mc', q:'12. The enemy release hypothesis explains invasiveness in terms of', o:['faster reproduction in warm climates.','the absence of natural predators and diseases.','competition with native plants.','human transport routes.'], c:1, e:'«leaves behind the predators, parasites and diseases».' },
          { t:'mc', q:'13. According to paragraph 2, freed from natural enemies, a species can', o:['change its genetic make-up.','move resources from defence to growth.','survive without water.','avoid detection.'], c:1, e:'«allocate to growth and reproduction the resources it previously spent on defence».' },
          { t:'mc', q:'14. The main weakness of the enemy release hypothesis is that', o:['it has no supporting evidence.','it applies to all introduced species, not only invasive ones.','it only works for animals.','it was proposed too recently.'], c:1, e:'«every introduced species enjoys it and only a few become invasive».' },
          { t:'mc', q:'15. The example of the fire-prone grass illustrates a species that', o:['outcompetes rivals for the same resource.','modifies its environment to its own advantage.','is spread deliberately by humans.','has no natural enemies.'], c:1, e:'«altering the rules of the game» — thay đổi chính môi trường.' },
          { t:'mc', q:'16. «Propagule pressure» refers to', o:['the speed at which a species reproduces.','the number of individuals and release events.','the strength of native competition.','the temperature range a species tolerates.'], c:1, e:'«the number of individuals released and the number of separate release events».' },
          { t:'mc', q:'17. The author describes the propagule pressure finding as «uncomfortable» because it suggests that', o:['scientists have been dishonest.','invasion success is partly a matter of trade volume rather than biology.','no management is possible.','the data are unreliable.'], c:1, e:'«much of what looks like biological superiority is in fact an accident of trade volume».' },
          { t:'mc', q:'18. According to paragraph 5, the quiet phase before an invasion expands may last', o:['a few months.','about five years.','fifty years or more.','several centuries.'], c:2, e:'«sometimes fifty years or more».' },
          { t:'mc', q:'19. According to the passage, the main reason invasions are rarely stopped early is', o:['scientific disagreement.','a lack of trained staff.','the mismatch between immediate costs and distant benefits.','public opposition to control measures.'], c:2, e:'«the cost of acting is immediate while the benefit is distant and uncertain… this asymmetry, rather than any scientific disagreement».' },
          { t:'mc', q:'20. The passage as a whole is organised as', o:['a chronological history of invasions.','a single hypothesis defended throughout.','a sequence of explanations, each shown to be incomplete.','a comparison of two regions.'], c:2, e:'Bài lần lượt nêu enemy release → thay đổi môi trường → propagule pressure → độ trễ, mỗi cái bổ khuyết cho cái trước.' }
        ] }
    ]},
    { id:'L', name:'Listening', vi:'Nghe · 28 câu · 36 phút', parts:[
      { title:'Conversation 1 — Student and Registrar (Questions 21–25)', ins:'Listen to each item and choose the best answer.', vi:'Câu 21–25: Hội thoại giữa sinh viên và phòng đào tạo.',
        qs:[
          { k:'listen', t:'mc', q:'21. Why does the student go to the registrar’s office?', o:['To pay a fee','To change a course','To collect a transcript','To report a lost card'], c:1, e:'«I want to drop statistics and add data visualisation» → đổi môn.',
            a:'Hi, how can I help? — Hi. I want to drop statistics and add data visualisation instead, if that is still possible.' },
          { k:'listen', t:'mc', q:'22. What is the problem with the student’s request?', o:['The new course is full.','The deadline has passed.','He lacks a prerequisite.','The two courses clash.'], c:2, e:'«you have not taken the programming course» → thiếu môn tiên quyết.',
            a:'Let me check. Data visualisation has a prerequisite, and according to your record you have not taken the programming course.' },
          { k:'listen', t:'mc', q:'23. What does the registrar suggest he does first?', o:['Email the department head','Speak to the course instructor','Take a placement test','Wait until next term'], c:1, e:'«talk to Dr Reid, the instructor» → gặp giảng viên.',
            a:'What are my options? — Talk to Dr Reid, the instructor. If she signs a waiver, I can process the change today.' },
          { k:'listen', t:'mc', q:'24. What does the student say about his timetable?', o:['He has no free afternoons.','He works on Fridays.','He has two classes at the same time.','He prefers morning classes.'], c:1, e:'«I work on Fridays» → đi làm thứ Sáu.',
            a:'Is Friday afternoon possible for you? — Not really. I work on Fridays, that is the one day I cannot come in.' },
          { k:'listen', t:'mc', q:'25. What will the student probably do next?', o:['Go to Dr Reid’s office','Pay the late fee','Return the following week','Enrol online'], c:0, e:'«Her office hours are today from two» → tới gặp Dr Reid.',
            a:'Her office hours are today from two until four, room 3.14. If you go now you will probably catch her.' }
        ] },
      { title:'Lecture 1 — Art History (Questions 26–31)', ins:'Listen to each item and choose the best answer.', vi:'Câu 26–31: Bài giảng lịch sử nghệ thuật.',
        qs:[
          { k:'listen', t:'mc', q:'26. What is the lecture mainly about?', o:['The invention of oil paint','Why fresco painting declined','How pigments were traded','The restoration of frescoes'], c:1, e:'«why fresco largely disappeared» → vì sao bích hoạ suy tàn.',
            a:'Today I want to explain something that puzzles a lot of students: why fresco, the dominant wall-painting technique for centuries, largely disappeared.' },
          { k:'listen', t:'mc', q:'27. According to the professor, the main technical demand of fresco is that', o:['the wall must be dry.','the paint must be applied while the plaster is wet.','only three colours can be used.','it must be done in daylight.'], c:1, e:'«you paint into wet plaster» → phải vẽ khi vữa còn ướt.',
            a:'In true fresco you paint into wet plaster, so the pigment becomes part of the wall as it dries. That is why it lasts, and also why it is unforgiving.' },
          { k:'listen', t:'mc', q:'28. The professor uses the term «giornata» to refer to', o:['a type of pigment.','the amount of plaster laid for one day’s work.','a school of painters.','a preparatory drawing.'], c:1, e:'«the patch you can finish in one day» → mảng vữa làm trong một ngày.',
            a:'Painters worked in sections called giornate — literally «days» — the patch of plaster you can finish in one day, because tomorrow it will be dry and useless.' },
          { k:'listen', t:'mc', q:'29. What does the professor say about correcting mistakes in fresco?', o:['They can be painted over easily.','The plaster must be cut out and replaced.','They are usually left visible.','Only the artist can see them.'], c:1, e:'«you chisel it out» → phải đục bỏ và trát lại.',
            a:'And if you make a mistake? You cannot paint over it. You chisel the section out, replaster and start again.' },
          { k:'listen', t:'mc', q:'30. According to the lecture, one advantage of oil on canvas was that it', o:['dried faster.','could be moved and sold.','used cheaper pigments.','required less skill.'], c:1, e:'«a painting you can roll up and sell» → có thể di chuyển và bán.',
            a:'Oil on canvas changed the economics completely. A fresco belongs to a wall; a canvas is a painting you can roll up, transport and sell to somebody in another city.' },
          { k:'listen', t:'mc', q:'31. What does the professor imply about climate?', o:['It had no effect on the technique.','Damp northern conditions were unsuitable for fresco.','Frescoes survive better in cold regions.','Climate mattered less than cost.'], c:1, e:'«damp walls of northern Europe destroy fresco» → khí hậu ẩm miền Bắc không hợp.',
            a:'There is a geographical point too. The damp walls of northern Europe destroy fresco within a generation, which is one reason the technique stayed largely Italian.' }
        ] },
      { title:'Lecture 2 — Environmental Science (Questions 32–37)', ins:'Listen to each item and choose the best answer.', vi:'Câu 32–37: Bài giảng khoa học môi trường.',
        qs:[
          { k:'listen', t:'mc', q:'32. What aspect of wetlands does the professor focus on?', o:['Their role in flood control','Their bird populations','Their soil chemistry','Their legal protection'], c:0, e:'«what wetlands do to floodwater» → vai trò điều tiết lũ.',
            a:'Right — wetlands. I am not going to talk about birds today. I want to look at something less photogenic: what wetlands do to floodwater.' },
          { k:'listen', t:'mc', q:'33. The professor compares a wetland to', o:['a filter.','a sponge.','a wall.','a pump.'], c:1, e:'«behaves like a sponge» → như miếng bọt biển.',
            a:'A healthy wetland behaves like a sponge. It absorbs water quickly during a storm and releases it slowly over the following days.' },
          { k:'listen', t:'mc', q:'34. According to the lecture, draining a wetland tends to', o:['reduce flooding downstream.','increase the speed of runoff.','improve water quality.','have no measurable effect.'], c:1, e:'«water arrives downstream faster and all at once» → dòng chảy nhanh hơn.',
            a:'Drain it, and the same rainfall now runs off a hard surface. The water arrives downstream faster and all at once, which is precisely what causes a flood peak.' },
          { k:'listen', t:'mc', q:'35. The professor mentions the cost of engineered defences in order to', o:['argue that they never work.','show that wetland restoration can be cheaper.','criticise local government.','explain why they are rarely built.'], c:1, e:'«restoring the marsh cost a fraction» → phục hồi đầm rẻ hơn nhiều.',
            a:'In one catchment the concrete option was costed at forty million. Restoring the marsh upstream cost a fraction of that and did the same job.' },
          { k:'listen', t:'mc', q:'36. What limitation of wetland restoration does the professor acknowledge?', o:['It takes years to become effective.','It requires imported plants.','It only works in warm climates.','It increases mosquito populations.'], c:0, e:'«it takes years before it functions» → cần nhiều năm mới có tác dụng.',
            a:'I should be honest about the drawback. You cannot build a wetland in a season. It takes years before it functions properly, and politicians rarely have years.' },
          { k:'listen', t:'mc', q:'37. What does the professor ask students to do before the next class?', o:['Read two articles','Visit a local wetland','Prepare a presentation','Submit a data table'], c:0, e:'«read the two papers» → đọc hai bài báo.',
            a:'For Thursday, please read the two papers in the folder — the Danish case study and the review article. We will compare them.' }
        ] },
      { title:'Conversation 2 & Lecture 3 (Questions 38–48)', ins:'Listen to each item and choose the best answer.', vi:'Câu 38–48: Hội thoại thư viện và bài giảng tâm lý học.',
        qs:[
          { k:'listen', t:'mc', q:'38. Why does the student visit the library desk?', o:['To renew a book','To find a missing article','To book a study room','To pay a fine'], c:1, e:'«the article is not in the database» → tìm bài báo không thấy.',
            a:'Excuse me — I am trying to find an article for my essay and it does not seem to be in the database at all.' },
          { k:'listen', t:'mc', q:'39. What does the librarian say about the journal?', o:['It was cancelled last year.','It is only available in print.','It is under a different title.','It is restricted to staff.'], c:2, e:'«the journal changed its name in 2019» → đổi tên.',
            a:'Ah — I know this one. The journal changed its name in twenty nineteen, so anything older is filed under the old title.' },
          { k:'listen', t:'mc', q:'40. What does the librarian offer to do?', o:['Order the article from another library','Print the article','Extend the essay deadline','Contact the author'], c:0, e:'«request it from another library» → mượn liên thư viện.',
            a:'If you still cannot find it, I can request it from another library. It usually takes two or three days and it is free for students.' },
          { k:'listen', t:'mc', q:'41. What is the student’s main concern?', o:['The cost','The deadline','The referencing style','The length of the essay'], c:1, e:'«my essay is due on Monday» → hạn nộp.',
            a:'Two or three days might be tight. My essay is due on Monday.' },
          { k:'listen', t:'mc', q:'42. What does the librarian suggest as an alternative?', o:['Citing a later paper by the same author','Using a textbook instead','Asking the tutor for an extension','Searching a different database'], c:3, e:'«try the open archive» → thử một cơ sở dữ liệu khác.',
            a:'In that case try the open archive — a lot of authors deposit a free version there. Search the title, not the journal.' },
          { k:'listen', t:'mc', q:'43. What is the lecture mainly about?', o:['How memory is stored','Why eyewitness testimony is unreliable','The development of language in children','Methods of measuring attention'], c:1, e:'«why eyewitnesses get things wrong» → độ tin cậy của lời khai nhân chứng.',
            a:'Today: eyewitness testimony. Specifically, why eyewitnesses get things wrong so often while feeling completely certain.',
            p:'' },
          { k:'listen', t:'mc', q:'44. According to the professor, confidence and accuracy are', o:['strongly related.','only weakly related.','identical.','inversely related in all cases.'], c:1, e:'«the correlation is weak» → tương quan yếu.',
            a:'The first thing to understand is that the correlation between how confident a witness feels and how accurate they are is weak. Juries assume the opposite.' },
          { k:'listen', t:'mc', q:'45. In the classic study described, what changed the participants’ estimates of speed?', o:['The colour of the cars','The verb used in the question','The time of day','The number of witnesses'], c:1, e:'«smashed versus hit» → động từ dùng trong câu hỏi.',
            a:'In the classic study, participants watched the same film of a collision. Some were asked how fast the cars were going when they smashed into each other; others, when they hit. The smashed group gave higher speeds — and a week later were more likely to report broken glass that was never there.' },
          { k:'listen', t:'mc', q:'46. The professor uses the term «reconstruction» to argue that memory is', o:['stored like a recording.','rebuilt each time it is recalled.','permanent once formed.','stronger under stress.'], c:1, e:'«rebuilt from fragments each time» → dựng lại mỗi lần nhớ.',
            a:'Memory is not a recording that we play back. It is rebuilt from fragments each time, and anything we have heard since can be built into it.' },
          { k:'listen', t:'mc', q:'47. What practical change does the professor mention?', o:['Longer interviews','Sequential rather than simultaneous line-ups','Recording all testimony on video','Using two interviewers'], c:1, e:'«show faces one at a time» → nhận diện tuần tự.',
            a:'One practical result: police in several countries now show faces one at a time rather than all together, which reduces the tendency to pick whoever looks most like the memory.' },
          { k:'listen', t:'mc', q:'48. What does the professor say about the reliability of witnesses overall?', o:['They should never be believed.','Their evidence is useful but must be handled carefully.','They are accurate if questioned quickly.','Only trained observers are reliable.'], c:1, e:'«useful evidence, but it needs handling like any fragile material» → hữu ích nhưng phải xử lý cẩn thận.',
            a:'None of this means witnesses are useless. It means their evidence is useful evidence, but it needs handling like any fragile material — carefully, and early.' }
        ] }
    ]},
    { id:'W', name:'Writing', vi:'Viết · 2 task · 29 phút', parts:[
      { title:'Integrated Writing Task — 20 minutes', ins:'Read the passage, listen to the lecture, then write 150–225 words summarising the points made in the lecture and explaining how they cast doubt on the reading.', vi:'Task 1 (20 phút, 150–225 từ): tóm tắt ý bài giảng và giải thích chúng phản bác bài đọc thế nào.',
        qs:[
          { k:'listen', t:'essay', min:150, words:['lecture','reading'],
            q:'READING PASSAGE (3 minutes)\n\nMany companies have introduced a four-day working week with no reduction in pay. Supporters give three reasons. First, productivity rises: employees who work fewer hours waste less time and concentrate better, so total output does not fall. Second, staff turnover drops sharply, because a shorter week is a benefit competitors find hard to match, and recruitment is expensive. Third, the environmental impact is positive, since one fewer commuting day per employee per week reduces traffic and office energy use.\n\nNow listen to the lecture. Then write your response.\n\n(Bài viết BẮT BUỘC có từ «lecture» và «reading».)',
            a:'The reading gives three reasons for the four-day week. I want to look at each one more carefully. On productivity: the trials that show output holding steady are almost all in office work where output is hard to measure. Where output is measurable — a factory line, a hospital ward, a call centre — four days of work produce four days of output. You cannot compress a shift. On turnover: yes, the firms that moved first saw a dramatic fall in resignations, but that is a competitive advantage, not a general effect. If every employer offers four days, nobody has an advantage, and the effect disappears. And on the environment: the studies that found lower emissions measured commuting only. Two of them also found that employees used the extra day for leisure travel, and in one case the additional weekend journeys cancelled out the entire commuting saving.',
            e:'BÀI MẪU (band cao):\n\nThe lecture challenges all three arguments presented in the reading.\n\nFirst, the reading claims that productivity rises because employees concentrate better. The lecture points out that this finding comes almost entirely from office work, where output is difficult to measure. In settings where output can be counted — a factory, a hospital ward or a call centre — four days of work simply produce four days of output, because a shift cannot be compressed.\n\nSecond, the reading argues that a shorter week reduces staff turnover. The lecturer accepts that early adopters saw resignations fall sharply, but explains that this is a competitive advantage rather than a property of the policy itself. Once every employer offers the same benefit, no firm gains an advantage and the effect disappears.\n\nFinally, the reading states that the environmental impact is positive. The lecture responds that the relevant studies measured commuting alone. Two of them found that employees used the free day for leisure travel, and in one case these extra weekend journeys cancelled out the entire saving from not commuting.\n\nGHI CHÚ: bài Integrated KHÔNG nêu ý kiến cá nhân. Nhiệm vụ duy nhất là thuật lại ý bài giảng và đối chiếu với bài đọc.' }
        ] },
      { title:'Writing for an Academic Discussion — 10 minutes', ins:'Read the discussion and write a response of at least 100 words that contributes your own opinion.', vi:'Task 2 (10 phút, tối thiểu 100 từ): tham gia thảo luận học thuật, nêu quan điểm riêng có lập luận.',
        qs:[
          { t:'essay', min:100, words:['I','because'],
            q:'PROFESSOR NGUYEN: This week we are looking at transport policy. Some cities have made public transport completely free, funded by taxes. Others argue that fares should be kept but kept low, and that the money saved should be spent on improving the service. Which approach do you think works better, and why?\n\nMAYA: I would make it free. Every study I have read shows that the biggest barrier for low-income households is cost, not frequency. Free travel is also simple to administer — no ticket machines, no inspectors, no fare evasion.\n\nDANIEL: I disagree. A free service that arrives every forty minutes is worthless. If we have limited money, spend it on more buses and longer hours. People will pay a small fare for a service that actually turns up.\n\nWrite a post responding to the discussion. State your own opinion and support it.\n\n(Bài viết BẮT BUỘC có từ «I» và «because».)',
            e:'BÀI MẪU (band cao):\n\nI find Daniel’s argument more convincing, although I think the two positions are less opposed than they appear.\n\nMaya is right that cost is a real barrier, but a free service only helps people who can actually use it. In my own city the buses are cheap and still half empty, because they run every forty minutes and stop at nine in the evening. Making those buses free would not persuade a nurse finishing a night shift to leave her motorbike at home; a bus every ten minutes until midnight would.\n\nI would therefore keep a low, flat fare and spend the money on frequency first, because frequency is what turns public transport into a genuine alternative. Once the service is good enough that most people prefer it, targeted free travel for students and low-income households becomes affordable — and by then it would actually be used.\n\nGHI CHÚ: dạng bài này chỉ 10 phút. Công thức an toàn: nêu bạn nghiêng về ai → thừa nhận điểm đúng của phía kia → một ví dụ cụ thể → chốt lại quan điểm.' }
        ] }
    ]}
  ]
}

];

if (typeof module !== 'undefined'){ module.exports = { TOEFL_EXAMS, TOEFL_SCALE, toeflScale }; }
