/* ============================================================
   LangLab — từ vựng thông dụng (bổ sung ngoài giáo trình)
   ------------------------------------------------------------
   Khoảng 400 từ hay gặp nhất trong đời sống, xếp theo chủ đề, để
   từ điển và bảng tra không bị mỏng. Đây là từ do LangLab tự soạn,
   không lấy từ sách; những từ đã có trong khoá học sẽ được khử
   trùng lặp khi gộp (xem js/words.js).

   Trường dữ liệu giống hệt vocab của khoá học:
     ko · rom · vi · pos · [hanja · hv]
   ============================================================ */

const VOCAB_COMMON = [

  /* ---------- Gia đình & con người (가족 · 사람) ---------- */
  {ko:'남자', rom:'namja', vi:'đàn ông, con trai', pos:'danh từ', hanja:'男子', hv:'nam tử'},
  {ko:'여자', rom:'yeoja', vi:'phụ nữ, con gái', pos:'danh từ', hanja:'女子', hv:'nữ tử'},
  {ko:'아이', rom:'ai', vi:'đứa trẻ', pos:'danh từ'},
  {ko:'아기', rom:'agi', vi:'em bé', pos:'danh từ'},
  {ko:'어른', rom:'eoreun', vi:'người lớn', pos:'danh từ'},
  {ko:'남편', rom:'nampyeon', vi:'chồng', pos:'danh từ', hanja:'男便', hv:'nam tiện'},
  {ko:'아내', rom:'anae', vi:'vợ', pos:'danh từ'},
  {ko:'아들', rom:'adeul', vi:'con trai', pos:'danh từ'},
  {ko:'딸', rom:'ttal', vi:'con gái', pos:'danh từ'},
  {ko:'부모님', rom:'bumonim', vi:'bố mẹ', pos:'danh từ', hanja:'父母—', hv:'phụ mẫu'},
  {ko:'아저씨', rom:'ajeossi', vi:'chú, bác (đàn ông trung niên)', pos:'danh từ'},
  {ko:'아주머니', rom:'ajumeoni', vi:'cô, bác (phụ nữ trung niên)', pos:'danh từ'},
  {ko:'남자친구', rom:'namjachingu', vi:'bạn trai', pos:'danh từ'},
  {ko:'여자친구', rom:'yeojachingu', vi:'bạn gái', pos:'danh từ'},
  {ko:'이웃', rom:'iut', vi:'hàng xóm', pos:'danh từ'},
  {ko:'사랑', rom:'sarang', vi:'tình yêu', pos:'danh từ'},

  /* ---------- Cơ thể (몸) ---------- */
  {ko:'몸', rom:'mom', vi:'cơ thể', pos:'danh từ'},
  {ko:'머리', rom:'meori', vi:'đầu; tóc', pos:'danh từ'},
  {ko:'얼굴', rom:'eolgul', vi:'khuôn mặt', pos:'danh từ'},
  {ko:'눈', rom:'nun', vi:'mắt', pos:'danh từ'},
  {ko:'코', rom:'ko', vi:'mũi', pos:'danh từ'},
  {ko:'입', rom:'ip', vi:'miệng', pos:'danh từ'},
  {ko:'귀', rom:'gwi', vi:'tai', pos:'danh từ'},
  {ko:'이', rom:'i', vi:'răng', pos:'danh từ'},
  {ko:'목', rom:'mok', vi:'cổ', pos:'danh từ'},
  {ko:'손', rom:'son', vi:'tay', pos:'danh từ'},
  {ko:'발', rom:'bal', vi:'chân (bàn chân)', pos:'danh từ'},
  {ko:'다리', rom:'dari', vi:'chân (cẳng chân)', pos:'danh từ'},
  {ko:'팔', rom:'pal', vi:'cánh tay', pos:'danh từ'},
  {ko:'배', rom:'bae', vi:'bụng', pos:'danh từ'},
  {ko:'등', rom:'deung', vi:'lưng', pos:'danh từ'},
  {ko:'어깨', rom:'eokkae', vi:'vai', pos:'danh từ'},
  {ko:'마음', rom:'maeum', vi:'lòng, tâm trí', pos:'danh từ'},
  {ko:'기분', rom:'gibun', vi:'tâm trạng', pos:'danh từ', hanja:'氣分', hv:'khí phân'},

  /* ---------- Ăn uống (음식) ---------- */
  {ko:'음식', rom:'eumsik', vi:'món ăn, đồ ăn', pos:'danh từ', hanja:'飮食', hv:'ẩm thực'},
  {ko:'과일', rom:'gwail', vi:'trái cây', pos:'danh từ'},
  {ko:'사과', rom:'sagwa', vi:'táo', pos:'danh từ'},
  {ko:'바나나', rom:'banana', vi:'chuối', pos:'danh từ'},
  {ko:'포도', rom:'podo', vi:'nho', pos:'danh từ', hanja:'葡萄', hv:'bồ đào'},
  {ko:'수박', rom:'subak', vi:'dưa hấu', pos:'danh từ'},
  {ko:'딸기', rom:'ttalgi', vi:'dâu tây', pos:'danh từ'},
  {ko:'채소', rom:'chaeso', vi:'rau', pos:'danh từ', hanja:'菜蔬', hv:'thái sơ'},
  {ko:'고기', rom:'gogi', vi:'thịt', pos:'danh từ'},
  {ko:'생선', rom:'saengseon', vi:'cá (để ăn)', pos:'danh từ', hanja:'生鮮', hv:'sinh tiên'},
  {ko:'계란', rom:'gyeran', vi:'trứng gà', pos:'danh từ', hanja:'鷄卵', hv:'kê noãn'},
  {ko:'빵', rom:'ppang', vi:'bánh mì', pos:'danh từ'},
  {ko:'우유', rom:'uyu', vi:'sữa', pos:'danh từ', hanja:'牛乳', hv:'ngưu nhũ'},
  {ko:'차', rom:'cha', vi:'trà', pos:'danh từ', hanja:'茶', hv:'trà'},
  {ko:'주스', rom:'juseu', vi:'nước ép', pos:'danh từ'},
  {ko:'맥주', rom:'maekju', vi:'bia', pos:'danh từ', hanja:'麥酒', hv:'mạch tửu'},
  {ko:'소금', rom:'sogeum', vi:'muối', pos:'danh từ'},
  {ko:'설탕', rom:'seoltang', vi:'đường', pos:'danh từ', hanja:'雪糖', hv:'tuyết đường'},
  {ko:'국', rom:'guk', vi:'canh', pos:'danh từ'},
  {ko:'국수', rom:'guksu', vi:'mì, bún', pos:'danh từ'},
  {ko:'라면', rom:'ramyeon', vi:'mì ăn liền', pos:'danh từ'},
  {ko:'김밥', rom:'gimbap', vi:'cơm cuộn', pos:'danh từ'},
  {ko:'떡볶이', rom:'tteokbokki', vi:'bánh gạo cay', pos:'danh từ'},
  {ko:'배고프다', rom:'baegopeuda', vi:'đói', pos:'tính từ'},
  {ko:'배부르다', rom:'baebureuda', vi:'no', pos:'tính từ'},
  {ko:'요리하다', rom:'yorihada', vi:'nấu ăn', pos:'động từ', hanja:'料理—', hv:'liệu lý'},

  /* ---------- Động vật (동물) ---------- */
  {ko:'동물', rom:'dongmul', vi:'động vật', pos:'danh từ', hanja:'動物', hv:'động vật'},
  {ko:'강아지', rom:'gangaji', vi:'chó, cún', pos:'danh từ'},
  {ko:'개', rom:'gae', vi:'chó', pos:'danh từ'},
  {ko:'고양이', rom:'goyangi', vi:'mèo', pos:'danh từ'},
  {ko:'새', rom:'sae', vi:'chim', pos:'danh từ'},
  {ko:'물고기', rom:'mulgogi', vi:'cá', pos:'danh từ'},
  {ko:'말', rom:'mal', vi:'ngựa', pos:'danh từ'},
  {ko:'소', rom:'so', vi:'bò', pos:'danh từ'},
  {ko:'돼지', rom:'dwaeji', vi:'lợn, heo', pos:'danh từ'},
  {ko:'닭', rom:'dak', vi:'gà', pos:'danh từ'},
  {ko:'토끼', rom:'tokki', vi:'thỏ', pos:'danh từ'},
  {ko:'호랑이', rom:'horangi', vi:'hổ', pos:'danh từ'},
  {ko:'코끼리', rom:'kkokkiri', vi:'voi', pos:'danh từ'},
  {ko:'곰', rom:'gom', vi:'gấu', pos:'danh từ'},

  /* ---------- Thiên nhiên & thời tiết (자연 · 날씨) ---------- */
  {ko:'하늘', rom:'haneul', vi:'bầu trời', pos:'danh từ'},
  {ko:'땅', rom:'ttang', vi:'đất', pos:'danh từ'},
  {ko:'해', rom:'hae', vi:'mặt trời', pos:'danh từ'},
  {ko:'달', rom:'dal', vi:'mặt trăng; tháng', pos:'danh từ'},
  {ko:'별', rom:'byeol', vi:'ngôi sao', pos:'danh từ'},
  {ko:'구름', rom:'gureum', vi:'mây', pos:'danh từ'},
  {ko:'바다', rom:'bada', vi:'biển', pos:'danh từ'},
  {ko:'산', rom:'san', vi:'núi', pos:'danh từ', hanja:'山', hv:'sơn'},
  {ko:'강', rom:'gang', vi:'sông', pos:'danh từ', hanja:'江', hv:'giang'},
  {ko:'나무', rom:'namu', vi:'cây', pos:'danh từ'},
  {ko:'꽃', rom:'kkot', vi:'hoa', pos:'danh từ'},
  {ko:'풀', rom:'pul', vi:'cỏ', pos:'danh từ'},
  {ko:'돌', rom:'dol', vi:'đá', pos:'danh từ'},
  {ko:'불', rom:'bul', vi:'lửa', pos:'danh từ'},
  {ko:'날씨', rom:'nalssi', vi:'thời tiết', pos:'danh từ'},
  {ko:'맑다', rom:'makda', vi:'trong, quang đãng', pos:'tính từ'},
  {ko:'흐리다', rom:'heurida', vi:'âm u', pos:'tính từ'},

  /* ---------- Nhà cửa & đồ vật (집 · 물건) ---------- */
  {ko:'문', rom:'mun', vi:'cửa', pos:'danh từ', hanja:'門', hv:'môn'},
  {ko:'창문', rom:'changmun', vi:'cửa sổ', pos:'danh từ', hanja:'窓門', hv:'song môn'},
  {ko:'벽', rom:'byeok', vi:'tường', pos:'danh từ', hanja:'壁', hv:'bích'},
  {ko:'바닥', rom:'badak', vi:'sàn nhà', pos:'danh từ'},
  {ko:'천장', rom:'cheonjang', vi:'trần nhà', pos:'danh từ', hanja:'天障', hv:'thiên chướng'},
  {ko:'계단', rom:'gyedan', vi:'cầu thang', pos:'danh từ', hanja:'階段', hv:'giai đoạn'},
  {ko:'열쇠', rom:'yeolsoe', vi:'chìa khoá', pos:'danh từ'},
  {ko:'거울', rom:'geoul', vi:'gương', pos:'danh từ'},
  {ko:'시계', rom:'sigye', vi:'đồng hồ', pos:'danh từ', hanja:'時計', hv:'thời kế'},
  {ko:'우산', rom:'usan', vi:'ô, dù', pos:'danh từ', hanja:'雨傘', hv:'vũ tán'},
  {ko:'가방', rom:'gabang', vi:'cặp, túi xách', pos:'danh từ'},
  {ko:'지갑', rom:'jigap', vi:'ví', pos:'danh từ', hanja:'紙匣', hv:'chỉ hạp'},
  {ko:'안경', rom:'angyeong', vi:'kính (mắt)', pos:'danh từ', hanja:'眼鏡', hv:'nhãn kính'},
  {ko:'컵', rom:'keop', vi:'cốc, ly', pos:'danh từ'},
  {ko:'접시', rom:'jeopsi', vi:'đĩa', pos:'danh từ'},
  {ko:'숟가락', rom:'sutgarak', vi:'thìa', pos:'danh từ'},
  {ko:'젓가락', rom:'jeotgarak', vi:'đũa', pos:'danh từ'},
  {ko:'칼', rom:'kal', vi:'dao', pos:'danh từ'},
  {ko:'종이', rom:'jongi', vi:'giấy', pos:'danh từ'},
  {ko:'전화기', rom:'jeonhwagi', vi:'điện thoại (máy)', pos:'danh từ', hanja:'電話機', hv:'điện thoại cơ'},
  {ko:'컴퓨터', rom:'keompyuteo', vi:'máy tính', pos:'danh từ'},
  {ko:'텔레비전', rom:'tellebijeon', vi:'ti vi', pos:'danh từ'},
  {ko:'냉장고', rom:'naengjanggo', vi:'tủ lạnh', pos:'danh từ', hanja:'冷藏庫', hv:'lãnh tàng khố'},
  {ko:'선풍기', rom:'seonpunggi', vi:'quạt máy', pos:'danh từ', hanja:'扇風機', hv:'phiến phong cơ'},
  {ko:'에어컨', rom:'eeokeon', vi:'điều hoà', pos:'danh từ'},

  /* ---------- Quần áo (옷) ---------- */
  {ko:'옷', rom:'ot', vi:'quần áo', pos:'danh từ'},
  {ko:'바지', rom:'baji', vi:'quần', pos:'danh từ'},
  {ko:'치마', rom:'chima', vi:'váy', pos:'danh từ'},
  {ko:'셔츠', rom:'syeocheu', vi:'áo sơ mi', pos:'danh từ'},
  {ko:'신발', rom:'sinbal', vi:'giày dép', pos:'danh từ'},
  {ko:'양말', rom:'yangmal', vi:'tất, vớ', pos:'danh từ', hanja:'洋襪', hv:'dương miệt'},
  {ko:'모자', rom:'moja', vi:'mũ, nón', pos:'danh từ', hanja:'帽子', hv:'mạo tử'},
  {ko:'장갑', rom:'janggap', vi:'găng tay', pos:'danh từ', hanja:'掌匣', hv:'chưởng hạp'},
  {ko:'입다', rom:'ipda', vi:'mặc', pos:'động từ'},
  {ko:'벗다', rom:'beotda', vi:'cởi', pos:'động từ'},
  {ko:'신다', rom:'sinda', vi:'đi (giày, tất)', pos:'động từ'},

  /* ---------- Nơi chốn (장소) ---------- */
  {ko:'곳', rom:'got', vi:'nơi, chỗ', pos:'danh từ'},
  {ko:'집', rom:'jip', vi:'nhà', pos:'danh từ'},
  {ko:'회사', rom:'hoesa', vi:'công ty', pos:'danh từ', hanja:'會社', hv:'hội xã'},
  {ko:'병원', rom:'byeongwon', vi:'bệnh viện', pos:'danh từ', hanja:'病院', hv:'bệnh viện'},
  {ko:'약국', rom:'yakguk', vi:'hiệu thuốc', pos:'danh từ', hanja:'藥局', hv:'dược cục'},
  {ko:'은행', rom:'eunhaeng', vi:'ngân hàng', pos:'danh từ', hanja:'銀行', hv:'ngân hàng'},
  {ko:'우체국', rom:'ucheguk', vi:'bưu điện', pos:'danh từ', hanja:'郵遞局', hv:'bưu đệ cục'},
  {ko:'공원', rom:'gongwon', vi:'công viên', pos:'danh từ', hanja:'公園', hv:'công viên'},
  {ko:'극장', rom:'geukjang', vi:'rạp hát, rạp phim', pos:'danh từ', hanja:'劇場', hv:'kịch trường'},
  {ko:'공항', rom:'gonghang', vi:'sân bay', pos:'danh từ', hanja:'空港', hv:'không cảng'},
  {ko:'호텔', rom:'hotel', vi:'khách sạn', pos:'danh từ'},
  {ko:'교회', rom:'gyohoe', vi:'nhà thờ', pos:'danh từ', hanja:'敎會', hv:'giáo hội'},
  {ko:'백화점', rom:'baekhwajeom', vi:'trung tâm thương mại', pos:'danh từ', hanja:'百貨店', hv:'bách hoá điếm'},
  {ko:'편의점', rom:'pyeonuijeom', vi:'cửa hàng tiện lợi', pos:'danh từ', hanja:'便宜店', hv:'tiện nghi điếm'},
  {ko:'카페', rom:'kape', vi:'quán cà phê', pos:'danh từ'},
  {ko:'화장실', rom:'hwajangsil', vi:'nhà vệ sinh', pos:'danh từ', hanja:'化粧室', hv:'hoá trang thất'},

  /* ---------- Giao thông (교통) ---------- */
  {ko:'길', rom:'gil', vi:'đường', pos:'danh từ'},
  {ko:'차', rom:'cha', vi:'xe hơi', pos:'danh từ', hanja:'車', hv:'xa'},
  {ko:'오토바이', rom:'otobai', vi:'xe máy', pos:'danh từ'},
  {ko:'비행기', rom:'bihaenggi', vi:'máy bay', pos:'danh từ', hanja:'飛行機', hv:'phi hành cơ'},
  {ko:'배', rom:'bae', vi:'thuyền, tàu thuỷ', pos:'danh từ'},
  {ko:'표', rom:'pyo', vi:'vé', pos:'danh từ', hanja:'票', hv:'phiếu'},

  /* ---------- Thời gian (시간) ---------- */
  {ko:'시간', rom:'sigan', vi:'thời gian; tiếng', pos:'danh từ', hanja:'時間', hv:'thời gian'},
  {ko:'오전', rom:'ojeon', vi:'buổi sáng (AM)', pos:'danh từ', hanja:'午前', hv:'ngọ tiền'},
  {ko:'오후', rom:'ohu', vi:'buổi chiều (PM)', pos:'danh từ', hanja:'午後', hv:'ngọ hậu'},
  {ko:'밤', rom:'bam', vi:'ban đêm', pos:'danh từ'},
  {ko:'새벽', rom:'saebyeok', vi:'rạng sáng', pos:'danh từ'},
  {ko:'주', rom:'ju', vi:'tuần', pos:'danh từ', hanja:'週', hv:'chu'},
  {ko:'달', rom:'dal', vi:'tháng', pos:'danh từ'},
  {ko:'년', rom:'nyeon', vi:'năm', pos:'danh từ', hanja:'年', hv:'niên'},
  {ko:'올해', rom:'olhae', vi:'năm nay', pos:'danh từ'},
  {ko:'작년', rom:'jangnyeon', vi:'năm ngoái', pos:'danh từ', hanja:'昨年', hv:'tạc niên'},
  {ko:'내년', rom:'naenyeon', vi:'năm sau', pos:'danh từ', hanja:'來年', hv:'lai niên'},
  {ko:'지금', rom:'jigeum', vi:'bây giờ', pos:'danh từ', hanja:'只今', hv:'chỉ kim'},
  {ko:'나중', rom:'najung', vi:'sau này', pos:'danh từ'},
  {ko:'요즘', rom:'yojeum', vi:'dạo này', pos:'danh từ'},
  {ko:'항상', rom:'hangsang', vi:'luôn luôn', pos:'phó từ', hanja:'恒常', hv:'hằng thường'},
  {ko:'벌써', rom:'beolsseo', vi:'đã… rồi', pos:'phó từ'},
  {ko:'아직', rom:'ajik', vi:'vẫn chưa', pos:'phó từ'},
  {ko:'금방', rom:'geumbang', vi:'vừa mới; ngay', pos:'phó từ'},

  /* ---------- Động từ thường dùng (동사) ---------- */
  {ko:'하다', rom:'hada', vi:'làm', pos:'động từ'},
  {ko:'되다', rom:'doeda', vi:'trở thành, được', pos:'động từ'},
  {ko:'주다', rom:'juda', vi:'cho', pos:'động từ'},
  {ko:'받다', rom:'batda', vi:'nhận', pos:'động từ'},
  {ko:'사다', rom:'sada', vi:'mua', pos:'động từ'},
  {ko:'팔다', rom:'palda', vi:'bán', pos:'động từ'},
  {ko:'열다', rom:'yeolda', vi:'mở', pos:'động từ'},
  {ko:'닫다', rom:'datda', vi:'đóng', pos:'động từ'},
  {ko:'켜다', rom:'kyeoda', vi:'bật', pos:'động từ'},
  {ko:'끄다', rom:'kkeuda', vi:'tắt', pos:'động từ'},
  {ko:'울다', rom:'ulda', vi:'khóc', pos:'động từ'},
  {ko:'웃다', rom:'utda', vi:'cười', pos:'động từ'},
  {ko:'앉다', rom:'anda', vi:'ngồi', pos:'động từ'},
  {ko:'서다', rom:'seoda', vi:'đứng', pos:'động từ'},
  {ko:'걷다', rom:'geotda', vi:'đi bộ', pos:'động từ'},
  {ko:'뛰다', rom:'ttwida', vi:'chạy', pos:'động từ'},
  {ko:'날다', rom:'nalda', vi:'bay', pos:'động từ'},
  {ko:'들다', rom:'deulda', vi:'cầm, nâng', pos:'động từ'},
  {ko:'놓다', rom:'nota', vi:'đặt, để xuống', pos:'động từ'},
  {ko:'찾다', rom:'chatda', vi:'tìm', pos:'động từ'},
  {ko:'잃다', rom:'ilta', vi:'mất, đánh mất', pos:'động từ'},
  {ko:'기다리다', rom:'gidarida', vi:'chờ, đợi', pos:'động từ'},
  {ko:'생각하다', rom:'saenggakhada', vi:'nghĩ', pos:'động từ'},
  {ko:'알다', rom:'alda', vi:'biết', pos:'động từ'},
  {ko:'모르다', rom:'moreuda', vi:'không biết', pos:'động từ'},
  {ko:'믿다', rom:'mitda', vi:'tin', pos:'động từ'},
  {ko:'좋아하다', rom:'joahada', vi:'thích', pos:'động từ'},
  {ko:'싫어하다', rom:'sireohada', vi:'ghét', pos:'động từ'},
  {ko:'원하다', rom:'wonhada', vi:'muốn', pos:'động từ'},
  {ko:'돕다', rom:'dopda', vi:'giúp', pos:'động từ'},
  {ko:'가르치다', rom:'gareuchida', vi:'dạy', pos:'động từ'},
  {ko:'배우다', rom:'baeuda', vi:'học', pos:'động từ'},
  {ko:'묻다', rom:'mutda', vi:'hỏi', pos:'động từ'},
  {ko:'대답하다', rom:'daedaphada', vi:'trả lời', pos:'động từ', hanja:'對答—', hv:'đối đáp'},
  {ko:'말하다', rom:'malhada', vi:'nói', pos:'động từ'},
  {ko:'듣다', rom:'deutda', vi:'nghe', pos:'động từ'},
  {ko:'쓰다', rom:'sseuda', vi:'viết; dùng', pos:'động từ'},
  {ko:'그리다', rom:'geurida', vi:'vẽ', pos:'động từ'},
  {ko:'만들다', rom:'mandeulda', vi:'làm ra, tạo', pos:'động từ'},
  {ko:'고치다', rom:'gochida', vi:'sửa', pos:'động từ'},
  {ko:'씻다', rom:'ssitda', vi:'rửa', pos:'động từ'},
  {ko:'청소하다', rom:'cheongsohada', vi:'dọn dẹp', pos:'động từ', hanja:'淸掃—', hv:'thanh tảo'},
  {ko:'빨래하다', rom:'ppallaehada', vi:'giặt đồ', pos:'động từ'},
  {ko:'들어가다', rom:'deureogada', vi:'đi vào', pos:'động từ'},
  {ko:'나가다', rom:'nagada', vi:'đi ra', pos:'động từ'},
  {ko:'올라가다', rom:'ollagada', vi:'đi lên', pos:'động từ'},
  {ko:'내려가다', rom:'naeryeogada', vi:'đi xuống', pos:'động từ'},
  {ko:'돌아가다', rom:'doragada', vi:'quay về', pos:'động từ'},
  {ko:'죽다', rom:'jukda', vi:'chết', pos:'động từ'},
  {ko:'살다', rom:'salda', vi:'sống', pos:'động từ'},

  /* ---------- Tính từ thường dùng (형용사) ---------- */
  {ko:'크다', rom:'keuda', vi:'to, lớn', pos:'tính từ'},
  {ko:'작다', rom:'jakda', vi:'nhỏ', pos:'tính từ'},
  {ko:'많다', rom:'manta', vi:'nhiều', pos:'tính từ'},
  {ko:'적다', rom:'jeokda', vi:'ít', pos:'tính từ'},
  {ko:'높다', rom:'nopda', vi:'cao', pos:'tính từ'},
  {ko:'낮다', rom:'natda', vi:'thấp', pos:'tính từ'},
  {ko:'길다', rom:'gilda', vi:'dài', pos:'tính từ'},
  {ko:'짧다', rom:'jjalda', vi:'ngắn', pos:'tính từ'},
  {ko:'빠르다', rom:'ppareuda', vi:'nhanh', pos:'tính từ'},
  {ko:'느리다', rom:'neurida', vi:'chậm', pos:'tính từ'},
  {ko:'새롭다', rom:'saeropda', vi:'mới', pos:'tính từ'},
  {ko:'낡다', rom:'nakda', vi:'cũ, sờn', pos:'tính từ'},
  {ko:'좋다', rom:'jota', vi:'tốt', pos:'tính từ'},
  {ko:'나쁘다', rom:'nappeuda', vi:'xấu, tệ', pos:'tính từ'},
  {ko:'예쁘다', rom:'yeppeuda', vi:'đẹp, xinh', pos:'tính từ'},
  {ko:'멋있다', rom:'meositda', vi:'ngầu, bảnh', pos:'tính từ'},
  {ko:'깨끗하다', rom:'kkaekkeutada', vi:'sạch sẽ', pos:'tính từ'},
  {ko:'더럽다', rom:'deoreopda', vi:'bẩn', pos:'tính từ'},
  {ko:'쉽다', rom:'swipda', vi:'dễ', pos:'tính từ'},
  {ko:'어렵다', rom:'eoryeopda', vi:'khó', pos:'tính từ'},
  {ko:'무겁다', rom:'mugeopda', vi:'nặng', pos:'tính từ'},
  {ko:'가볍다', rom:'gabyeopda', vi:'nhẹ', pos:'tính từ'},
  {ko:'덥다', rom:'deopda', vi:'nóng (thời tiết)', pos:'tính từ'},
  {ko:'춥다', rom:'chupda', vi:'lạnh (thời tiết)', pos:'tính từ'},
  {ko:'뜨겁다', rom:'tteugeopda', vi:'nóng (đồ vật)', pos:'tính từ'},
  {ko:'차갑다', rom:'chagapda', vi:'lạnh (đồ vật)', pos:'tính từ'},
  {ko:'밝다', rom:'bakda', vi:'sáng', pos:'tính từ'},
  {ko:'어둡다', rom:'eodupda', vi:'tối', pos:'tính từ'},
  {ko:'조용하다', rom:'joyonghada', vi:'yên tĩnh', pos:'tính từ'},
  {ko:'시끄럽다', rom:'sikkeureopda', vi:'ồn ào', pos:'tính từ'},
  {ko:'행복하다', rom:'haengbokhada', vi:'hạnh phúc', pos:'tính từ', hanja:'幸福—', hv:'hạnh phúc'},
  {ko:'슬프다', rom:'seulpeuda', vi:'buồn', pos:'tính từ'},
  {ko:'화나다', rom:'hwanada', vi:'tức giận', pos:'động từ'},
  {ko:'무섭다', rom:'museopda', vi:'sợ, đáng sợ', pos:'tính từ'},
  {ko:'심심하다', rom:'simsimhada', vi:'chán', pos:'tính từ'},
  {ko:'재미있다', rom:'jaemiitda', vi:'thú vị, vui', pos:'tính từ'},
  {ko:'재미없다', rom:'jaemieopda', vi:'nhạt, chán', pos:'tính từ'},
  {ko:'피곤하다', rom:'pigonhada', vi:'mệt', pos:'tính từ', hanja:'疲困—', hv:'bì khốn'},
  {ko:'아프다', rom:'apeuda', vi:'đau, ốm', pos:'tính từ'},
  {ko:'건강하다', rom:'geonganghada', vi:'khoẻ mạnh', pos:'tính từ', hanja:'健康—', hv:'kiện khang'},
  {ko:'바쁘다', rom:'bappeuda', vi:'bận', pos:'tính từ'},
  {ko:'중요하다', rom:'jungyohada', vi:'quan trọng', pos:'tính từ', hanja:'重要—', hv:'trọng yếu'},
  {ko:'유명하다', rom:'yumyeonghada', vi:'nổi tiếng', pos:'tính từ', hanja:'有名—', hv:'hữu danh'},
  {ko:'편하다', rom:'pyeonhada', vi:'thoải mái, tiện', pos:'tính từ', hanja:'便—', hv:'tiện'},
  {ko:'불편하다', rom:'bulpyeonhada', vi:'bất tiện', pos:'tính từ', hanja:'不便—', hv:'bất tiện'},
  {ko:'비슷하다', rom:'biseutada', vi:'giống, tương tự', pos:'tính từ'},
  {ko:'다르다', rom:'dareuda', vi:'khác', pos:'tính từ'},
  {ko:'같다', rom:'gatda', vi:'giống nhau', pos:'tính từ'},

  /* ---------- Phó từ & liên từ hay gặp ---------- */
  {ko:'아주', rom:'aju', vi:'rất', pos:'phó từ'},
  {ko:'너무', rom:'neomu', vi:'quá', pos:'phó từ'},
  {ko:'정말', rom:'jeongmal', vi:'thật sự', pos:'phó từ'},
  {ko:'조금', rom:'jogeum', vi:'một chút', pos:'phó từ'},
  {ko:'많이', rom:'mani', vi:'nhiều', pos:'phó từ'},
  {ko:'빨리', rom:'ppalli', vi:'nhanh lên', pos:'phó từ'},
  {ko:'천천히', rom:'cheoncheonhi', vi:'từ từ', pos:'phó từ'},
  {ko:'같이', rom:'gachi', vi:'cùng nhau', pos:'phó từ'},
  {ko:'혼자', rom:'honja', vi:'một mình', pos:'phó từ'},
  {ko:'다시', rom:'dasi', vi:'lại, lần nữa', pos:'phó từ'},
  {ko:'먼저', rom:'meonjeo', vi:'trước tiên', pos:'phó từ'},
  {ko:'그리고', rom:'geurigo', vi:'và, rồi', pos:'liên từ'},
  {ko:'그래서', rom:'geuraeseo', vi:'vì vậy', pos:'liên từ'},
  {ko:'그러나', rom:'geureona', vi:'nhưng', pos:'liên từ'},
  {ko:'그런데', rom:'geureonde', vi:'nhưng mà, vả lại', pos:'liên từ'},
  {ko:'그러면', rom:'geureomyeon', vi:'nếu vậy thì', pos:'liên từ'},
  {ko:'그러니까', rom:'geureonikka', vi:'cho nên', pos:'liên từ'},
  {ko:'왜냐하면', rom:'waenyahamyeon', vi:'bởi vì', pos:'liên từ'},
  {ko:'만약', rom:'manyak', vi:'nếu như', pos:'phó từ', hanja:'萬若', hv:'vạn nhược'},

  /* ---------- Học tập & công việc ---------- */
  {ko:'공부', rom:'gongbu', vi:'việc học', pos:'danh từ', hanja:'工夫', hv:'công phu'},
  {ko:'숙제', rom:'sukje', vi:'bài tập về nhà', pos:'danh từ', hanja:'宿題', hv:'túc đề'},
  {ko:'시험', rom:'siheom', vi:'kỳ thi', pos:'danh từ', hanja:'試驗', hv:'thí nghiệm'},
  {ko:'문제', rom:'munje', vi:'vấn đề; câu hỏi', pos:'danh từ', hanja:'問題', hv:'vấn đề'},
  {ko:'질문', rom:'jilmun', vi:'câu hỏi', pos:'danh từ', hanja:'質問', hv:'chất vấn'},
  {ko:'대답', rom:'daedap', vi:'câu trả lời', pos:'danh từ', hanja:'對答', hv:'đối đáp'},
  {ko:'수업', rom:'sueop', vi:'tiết học', pos:'danh từ', hanja:'授業', hv:'thụ nghiệp'},
  {ko:'방학', rom:'banghak', vi:'kỳ nghỉ (trường)', pos:'danh từ', hanja:'放學', hv:'phóng học'},
  {ko:'일', rom:'il', vi:'công việc; việc', pos:'danh từ'},
  {ko:'돈', rom:'don', vi:'tiền', pos:'danh từ'},
  {ko:'값', rom:'gap', vi:'giá', pos:'danh từ'},
  {ko:'가격', rom:'gagyeok', vi:'giá cả', pos:'danh từ', hanja:'價格', hv:'giá cách'},

  /* ---------- Từ để hỏi & đại từ ---------- */
  {ko:'누구', rom:'nugu', vi:'ai', pos:'từ để hỏi'},
  {ko:'무엇', rom:'mueot', vi:'cái gì', pos:'từ để hỏi'},
  {ko:'어디', rom:'eodi', vi:'ở đâu', pos:'từ để hỏi'},
  {ko:'언제', rom:'eonje', vi:'khi nào', pos:'từ để hỏi'},
  {ko:'왜', rom:'wae', vi:'tại sao', pos:'từ để hỏi'},
  {ko:'어떻게', rom:'eotteoke', vi:'như thế nào', pos:'từ để hỏi'},
  {ko:'얼마', rom:'eolma', vi:'bao nhiêu', pos:'từ để hỏi'},
  {ko:'몇', rom:'myeot', vi:'mấy', pos:'từ để hỏi'},
  {ko:'이것', rom:'igeot', vi:'cái này', pos:'đại từ'},
  {ko:'그것', rom:'geugeot', vi:'cái đó', pos:'đại từ'},
  {ko:'저것', rom:'jeogeot', vi:'cái kia', pos:'đại từ'},
  {ko:'여기', rom:'yeogi', vi:'ở đây', pos:'đại từ'},
  {ko:'거기', rom:'geogi', vi:'ở đó', pos:'đại từ'},
  {ko:'저기', rom:'jeogi', vi:'ở kia', pos:'đại từ'},
  {ko:'우리', rom:'uri', vi:'chúng ta, chúng tôi', pos:'đại từ'},

  /* ---------- Sở thích & giải trí ---------- */
  {ko:'취미', rom:'chwimi', vi:'sở thích', pos:'danh từ', hanja:'趣味', hv:'thú vị'},
  {ko:'영화', rom:'yeonghwa', vi:'phim', pos:'danh từ', hanja:'映畵', hv:'ánh hoạ'},
  {ko:'음악', rom:'eumak', vi:'âm nhạc', pos:'danh từ', hanja:'音樂', hv:'âm nhạc'},
  {ko:'노래', rom:'norae', vi:'bài hát', pos:'danh từ'},
  {ko:'춤', rom:'chum', vi:'điệu nhảy', pos:'danh từ'},
  {ko:'그림', rom:'geurim', vi:'bức tranh', pos:'danh từ'},
  {ko:'사진', rom:'sajin', vi:'ảnh', pos:'danh từ', hanja:'寫眞', hv:'tả chân'},
  {ko:'책', rom:'chaek', vi:'sách', pos:'danh từ', hanja:'冊', hv:'sách'},
  {ko:'신문', rom:'sinmun', vi:'báo', pos:'danh từ', hanja:'新聞', hv:'tân văn'},
  {ko:'게임', rom:'geim', vi:'trò chơi', pos:'danh từ'},
  {ko:'운동', rom:'undong', vi:'thể thao', pos:'danh từ', hanja:'運動', hv:'vận động'},
  {ko:'축구', rom:'chukgu', vi:'bóng đá', pos:'danh từ', hanja:'蹴球', hv:'xúc cầu'},
  {ko:'농구', rom:'nonggu', vi:'bóng rổ', pos:'danh từ', hanja:'籠球', hv:'lung cầu'},
  {ko:'수영', rom:'suyeong', vi:'bơi lội', pos:'danh từ', hanja:'水泳', hv:'thuỷ vịnh'},
  {ko:'여행', rom:'yeohaeng', vi:'du lịch', pos:'danh từ', hanja:'旅行', hv:'lữ hành'},

  /* ---------- Chào hỏi & biểu hiện ---------- */
  {ko:'안녕히 가세요', rom:'annyeonghi gaseyo', vi:'tạm biệt (người ở lại nói)', pos:'biểu hiện'},
  {ko:'안녕히 계세요', rom:'annyeonghi gyeseyo', vi:'tạm biệt (người đi nói)', pos:'biểu hiện'},
  {ko:'감사합니다', rom:'gamsahamnida', vi:'cảm ơn', pos:'biểu hiện', hanja:'感謝—', hv:'cảm tạ'},
  {ko:'고맙습니다', rom:'gomapseumnida', vi:'cảm ơn', pos:'biểu hiện'},
  {ko:'죄송합니다', rom:'joesonghamnida', vi:'xin lỗi', pos:'biểu hiện', hanja:'罪悚—', hv:'tội tủng'},
  {ko:'미안합니다', rom:'mianhamnida', vi:'xin lỗi', pos:'biểu hiện', hanja:'未安—', hv:'vị an'},
  {ko:'괜찮다', rom:'gwaenchanta', vi:'không sao, ổn', pos:'tính từ'},
  {ko:'축하합니다', rom:'chukhahamnida', vi:'chúc mừng', pos:'biểu hiện', hanja:'祝賀—', hv:'chúc hạ'},
  {ko:'실례합니다', rom:'sillyehamnida', vi:'xin phép, cho hỏi', pos:'biểu hiện', hanja:'失禮—', hv:'thất lễ'},
  {ko:'환영합니다', rom:'hwanyeonghamnida', vi:'chào mừng', pos:'biểu hiện', hanja:'歡迎—', hv:'hoan nghênh'},

  /* ---------- Số & đếm ---------- */
  {ko:'번호', rom:'beonho', vi:'số (thứ tự)', pos:'danh từ', hanja:'番號', hv:'phiên hiệu'},
  {ko:'개', rom:'gae', vi:'cái (đơn vị đếm)', pos:'đơn vị', hanja:'個', hv:'cá'},
  {ko:'명', rom:'myeong', vi:'người (đơn vị đếm)', pos:'đơn vị', hanja:'名', hv:'danh'},
  {ko:'마리', rom:'mari', vi:'con (đếm động vật)', pos:'đơn vị'},
  {ko:'권', rom:'gwon', vi:'quyển', pos:'đơn vị', hanja:'卷', hv:'quyển'},
  {ko:'장', rom:'jang', vi:'tờ, tấm', pos:'đơn vị', hanja:'張', hv:'trương'},
  {ko:'번', rom:'beon', vi:'lần', pos:'đơn vị', hanja:'番', hv:'phiên'},
  {ko:'살', rom:'sal', vi:'tuổi', pos:'đơn vị'},
  {ko:'반', rom:'ban', vi:'một nửa; lớp', pos:'danh từ', hanja:'半', hv:'bán'}
];
if (typeof window !== 'undefined') window.VOCAB_COMMON = VOCAB_COMMON;
