/* ============================================================
   LangLab — từ vựng thông dụng (bổ sung ngoài giáo trình)
   ------------------------------------------------------------
   Khoảng 400 từ hay gặp nhất trong đời sống, xếp theo chủ đề, để
   từ điển và bảng tra không bị mỏng. Đây là từ do LangLab tự soạn,
   không lấy từ sách; những từ đã có trong khoá học sẽ được khử
   trùng lặp khi gộp (xem js/words.js).

   Trường dữ liệu giống hệt vocab của khoá học:
     ko · rom · vi · pos · [hanja · hv]
   ============================================================ */

const VOCAB_COMMON = [

  /* ---------- Gia đình & con người (가족 · 사람) ---------- */
  {ko:'남자', rom:'namja', vi:'đàn ông, con trai', pos:'danh từ', hanja:'男子', hv:'nam tử'},
  {ko:'여자', rom:'yeoja', vi:'phụ nữ, con gái', pos:'danh từ', hanja:'女子', hv:'nữ tử'},
  {ko:'아이', rom:'ai', vi:'đứa trẻ', pos:'danh từ'},
  {ko:'아기', rom:'agi', vi:'em bé', pos:'danh từ'},
  {ko:'어른', rom:'eoreun', vi:'người lớn', pos:'danh từ'},
  {ko:'남편', rom:'nampyeon', vi:'chồng', pos:'danh từ', hanja:'男便', hv:'nam tiện'},
  {ko:'아내', rom:'anae', vi:'vợ', pos:'danh từ'},
  {ko:'아들', rom:'adeul', vi:'con trai', pos:'danh từ'},
  {ko:'딸', rom:'ttal', vi:'con gái', pos:'danh từ'},
  {ko:'부모님', rom:'bumonim', vi:'bố mẹ', pos:'danh từ', hanja:'父母—', hv:'phụ mẫu'},
  {ko:'아저씨', rom:'ajeossi', vi:'chú, bác (đàn ông trung niên)', pos:'danh từ'},
  {ko:'아주머니', rom:'ajumeoni', vi:'cô, bác (phụ nữ trung niên)', pos:'danh từ'},
  {ko:'남자친구', rom:'namjachingu', vi:'bạn trai', pos:'danh từ'},
  {ko:'여자친구', rom:'yeojachingu', vi:'bạn gái', pos:'danh từ'},
  {ko:'이웃', rom:'iut', vi:'hàng xóm', pos:'danh từ'},
  {ko:'사랑', rom:'sarang', vi:'tình yêu', pos:'danh từ'},

  /* ---------- Cơ thể (몸) ---------- */
  {ko:'몸', rom:'mom', vi:'cơ thể', pos:'danh từ'},
  {ko:'머리', rom:'meori', vi:'đầu; tóc', pos:'danh từ'},
  {ko:'얼굴', rom:'eolgul', vi:'khuôn mặt', pos:'danh từ'},
  {ko:'눈', rom:'nun', vi:'mắt', pos:'danh từ'},
  {ko:'코', rom:'ko', vi:'mũi', pos:'danh từ'},
  {ko:'입', rom:'ip', vi:'miệng', pos:'danh từ'},
  {ko:'귀', rom:'gwi', vi:'tai', pos:'danh từ'},
  {ko:'이', rom:'i', vi:'răng', pos:'danh từ'},
  {ko:'목', rom:'mok', vi:'cổ', pos:'danh từ'},
  {ko:'손', rom:'son', vi:'tay', pos:'danh từ'},
  {ko:'발', rom:'bal', vi:'chân (bàn chân)', pos:'danh từ'},
  {ko:'다리', rom:'dari', vi:'chân (cẳng chân)', pos:'danh từ'},
  {ko:'팔', rom:'pal', vi:'cánh tay', pos:'danh từ'},
  {ko:'배', rom:'bae', vi:'bụng', pos:'danh từ'},
  {ko:'등', rom:'deung', vi:'lưng', pos:'danh từ'},
  {ko:'어깨', rom:'eokkae', vi:'vai', pos:'danh từ'},
  {ko:'마음', rom:'maeum', vi:'lòng, tâm trí', pos:'danh từ'},
  {ko:'기분', rom:'gibun', vi:'tâm trạng', pos:'danh từ', hanja:'氣分', hv:'khí phân'},

  /* ---------- Ăn uống (음식) ---------- */
  {ko:'음식', rom:'eumsik', vi:'món ăn, đồ ăn', pos:'danh từ', hanja:'飮食', hv:'ẩm thực'},
  {ko:'과일', rom:'gwail', vi:'trái cây', pos:'danh từ'},
  {ko:'사과', rom:'sagwa', vi:'táo', pos:'danh từ'},
  {ko:'바나나', rom:'banana', vi:'chuối', pos:'danh từ'},
  {ko:'포도', rom:'podo', vi:'nho', pos:'danh từ', hanja:'葡萄', hv:'bồ đào'},
  {ko:'수박', rom:'subak', vi:'dưa hấu', pos:'danh từ'},
  {ko:'딸기', rom:'ttalgi', vi:'dâu tây', pos:'danh từ'},
  {ko:'채소', rom:'chaeso', vi:'rau', pos:'danh từ', hanja:'菜蔬', hv:'thái sơ'},
  {ko:'고기', rom:'gogi', vi:'thịt', pos:'danh từ'},
  {ko:'생선', rom:'saengseon', vi:'cá (để ăn)', pos:'danh từ', hanja:'生鮮', hv:'sinh tiên'},
  {ko:'계란', rom:'gyeran', vi:'trứng gà', pos:'danh từ', hanja:'鷄卵', hv:'kê noãn'},
  {ko:'빵', rom:'ppang', vi:'bánh mì', pos:'danh từ'},
  {ko:'우유', rom:'uyu', vi:'sữa', pos:'danh từ', hanja:'牛乳', hv:'ngưu nhũ'},
  {ko:'차', rom:'cha', vi:'trà', pos:'danh từ', hanja:'茶', hv:'trà'},
  {ko:'주스', rom:'juseu', vi:'nước ép', pos:'danh từ'},
  {ko:'맥주', rom:'maekju', vi:'bia', pos:'danh từ', hanja:'麥酒', hv:'mạch tửu'},
  {ko:'소금', rom:'sogeum', vi:'muối', pos:'danh từ'},
  {ko:'설탕', rom:'seoltang', vi:'đường', pos:'danh từ', hanja:'雪糖', hv:'tuyết đường'},
  {ko:'국', rom:'guk', vi:'canh', pos:'danh từ'},
  {ko:'국수', rom:'guksu', vi:'mì, bún', pos:'danh từ'},
  {ko:'라면', rom:'ramyeon', vi:'mì ăn liền', pos:'danh từ'},
  {ko:'김밥', rom:'gimbap', vi:'cơm cuộn', pos:'danh từ'},
  {ko:'떡볶이', rom:'tteokbokki', vi:'bánh gạo cay', pos:'danh từ'},
  {ko:'배고프다', rom:'baegopeuda', vi:'đói', pos:'tính từ'},
  {ko:'배부르다', rom:'baebureuda', vi:'no', pos:'tính từ'},
  {ko:'요리하다', rom:'yorihada', vi:'nấu ăn', pos:'động từ', hanja:'料理—', hv:'liệu lý'},

  /* ---------- Động vật (동물) ---------- */
  {ko:'동물', rom:'dongmul', vi:'động vật', pos:'danh từ', hanja:'動物', hv:'động vật'},
  {ko:'강아지', rom:'gangaji', vi:'chó, cún', pos:'danh từ'},
  {ko:'개', rom:'gae', vi:'chó', pos:'danh từ'},
  {ko:'고양이', rom:'goyangi', vi:'mèo', pos:'danh từ'},
  {ko:'새', rom:'sae', vi:'chim', pos:'danh từ'},
  {ko:'물고기', rom:'mulgogi', vi:'cá', pos:'danh từ'},
  {ko:'말', rom:'mal', vi:'ngựa', pos:'danh từ'},
  {ko:'소', rom:'so', vi:'bò', pos:'danh từ'},
  {ko:'돼지', rom:'dwaeji', vi:'lợn, heo', pos:'danh từ'},
  {ko:'닭', rom:'dak', vi:'gà', pos:'danh từ'},
  {ko:'토끼', rom:'tokki', vi:'thỏ', pos:'danh từ'},
  {ko:'호랑이', rom:'horangi', vi:'hổ', pos:'danh từ'},
  {ko:'코끼리', rom:'kkokkiri', vi:'voi', pos:'danh từ'},
  {ko:'곰', rom:'gom', vi:'gấu', pos:'danh từ'},

  /* ---------- Thiên nhiên & thời tiết (자연 · 날씨) ---------- */
  {ko:'하늘', rom:'haneul', vi:'bầu trời', pos:'danh từ'},
  {ko:'땅', rom:'ttang', vi:'đất', pos:'danh từ'},
  {ko:'해', rom:'hae', vi:'mặt trời', pos:'danh từ'},
  {ko:'달', rom:'dal', vi:'mặt trăng; tháng', pos:'danh từ'},
  {ko:'별', rom:'byeol', vi:'ngôi sao', pos:'danh từ'},
  {ko:'구름', rom:'gureum', vi:'mây', pos:'danh từ'},
  {ko:'바다', rom:'bada', vi:'biển', pos:'danh từ'},
  {ko:'산', rom:'san', vi:'núi', pos:'danh từ', hanja:'山', hv:'sơn'},
  {ko:'강', rom:'gang', vi:'sông', pos:'danh từ', hanja:'江', hv:'giang'},
  {ko:'나무', rom:'namu', vi:'cây', pos:'danh từ'},
  {ko:'꽃', rom:'kkot', vi:'hoa', pos:'danh từ'},
  {ko:'풀', rom:'pul', vi:'cỏ', pos:'danh từ'},
  {ko:'돌', rom:'dol', vi:'đá', pos:'danh từ'},
  {ko:'불', rom:'bul', vi:'lửa', pos:'danh từ'},
  {ko:'날씨', rom:'nalssi', vi:'thời tiết', pos:'danh từ'},
  {ko:'맑다', rom:'makda', vi:'trong, quang đãng', pos:'tính từ'},
  {ko:'흐리다', rom:'heurida', vi:'âm u', pos:'tính từ'},

  /* ---------- Nhà cửa & đồ vật (집 · 물건) ---------- */
  {ko:'문', rom:'mun', vi:'cửa', pos:'danh từ', hanja:'門', hv:'môn'},
  {ko:'창문', rom:'changmun', vi:'cửa sổ', pos:'danh từ', hanja:'窓門', hv:'song môn'},
  {ko:'벽', rom:'byeok', vi:'tường', pos:'danh từ', hanja:'壁', hv:'bích'},
  {ko:'바닥', rom:'badak', vi:'sàn nhà', pos:'danh từ'},
  {ko:'천장', rom:'cheonjang', vi:'trần nhà', pos:'danh từ', hanja:'天障', hv:'thiên chướng'},
  {ko:'계단', rom:'gyedan', vi:'cầu thang', pos:'danh từ', hanja:'階段', hv:'giai đoạn'},
  {ko:'열쇠', rom:'yeolsoe', vi:'chìa khoá', pos:'danh từ'},
  {ko:'거울', rom:'geoul', vi:'gương', pos:'danh từ'},
  {ko:'시계', rom:'sigye', vi:'đồng hồ', pos:'danh từ', hanja:'時計', hv:'thời kế'},
  {ko:'우산', rom:'usan', vi:'ô, dù', pos:'danh từ', hanja:'雨傘', hv:'vũ tán'},
  {ko:'가방', rom:'gabang', vi:'cặp, túi xách', pos:'danh từ'},
  {ko:'지갑', rom:'jigap', vi:'ví', pos:'danh từ', hanja:'紙匣', hv:'chỉ hạp'},
  {ko:'안경', rom:'angyeong', vi:'kính (mắt)', pos:'danh từ', hanja:'眼鏡', hv:'nhãn kính'},
  {ko:'컵', rom:'keop', vi:'cốc, ly', pos:'danh từ'},
  {ko:'접시', rom:'jeopsi', vi:'đĩa', pos:'danh từ'},
  {ko:'숟가락', rom:'sutgarak', vi:'thìa', pos:'danh từ'},
  {ko:'젓가락', rom:'jeotgarak', vi:'đũa', pos:'danh từ'},
  {ko:'칼', rom:'kal', vi:'dao', pos:'danh từ'},
  {ko:'종이', rom:'jongi', vi:'giấy', pos:'danh từ'},
  {ko:'전화기', rom:'jeonhwagi', vi:'điện thoại (máy)', pos:'danh từ', hanja:'電話機', hv:'điện thoại cơ'},
  {ko:'컴퓨터', rom:'keompyuteo', vi:'máy tính', pos:'danh từ'},
  {ko:'텔레비전', rom:'tellebijeon', vi:'ti vi', pos:'danh từ'},
  {ko:'냉장고', rom:'naengjanggo', vi:'tủ lạnh', pos:'danh từ', hanja:'冷藏庫', hv:'lãnh tàng khố'},
  {ko:'선풍기', rom:'seonpunggi', vi:'quạt máy', pos:'danh từ', hanja:'扇風機', hv:'phiến phong cơ'},
  {ko:'에어컨', rom:'eeokeon', vi:'điều hoà', pos:'danh từ'},

  /* ---------- Quần áo (옷) ---------- */
  {ko:'옷', rom:'ot', vi:'quần áo', pos:'danh từ'},
  {ko:'바지', rom:'baji', vi:'quần', pos:'danh từ'},
  {ko:'치마', rom:'chima', vi:'váy', pos:'danh từ'},
  {ko:'셔츠', rom:'syeocheu', vi:'áo sơ mi', pos:'danh từ'},
  {ko:'신발', rom:'sinbal', vi:'giày dép', pos:'danh từ'},
  {ko:'양말', rom:'yangmal', vi:'tất, vớ', pos:'danh từ', hanja:'洋襪', hv:'dương miệt'},
  {ko:'모자', rom:'moja', vi:'mũ, nón', pos:'danh từ', hanja:'帽子', hv:'mạo tử'},
  {ko:'장갑', rom:'janggap', vi:'găng tay', pos:'danh từ', hanja:'掌匣', hv:'chưởng hạp'},
  {ko:'입다', rom:'ipda', vi:'mặc', pos:'động từ'},
  {ko:'벗다', rom:'beotda', vi:'cởi', pos:'động từ'},
  {ko:'신다', rom:'sinda', vi:'đi (giày, tất)', pos:'động từ'},

  /* ---------- Nơi chốn (장소) ---------- */
  {ko:'곳', rom:'got', vi:'nơi, chỗ', pos:'danh từ'},
  {ko:'집', rom:'jip', vi:'nhà', pos:'danh từ'},
  {ko:'회사', rom:'hoesa', vi:'công ty', pos:'danh từ', hanja:'會社', hv:'hội xã'},
  {ko:'병원', rom:'byeongwon', vi:'bệnh viện', pos:'danh từ', hanja:'病院', hv:'bệnh viện'},
  {ko:'약국', rom:'yakguk', vi:'hiệu thuốc', pos:'danh từ', hanja:'藥局', hv:'dược cục'},
  {ko:'은행', rom:'eunhaeng', vi:'ngân hàng', pos:'danh từ', hanja:'銀行', hv:'ngân hàng'},
  {ko:'우체국', rom:'ucheguk', vi:'bưu điện', pos:'danh từ', hanja:'郵遞局', hv:'bưu đệ cục'},
  {ko:'공원', rom:'gongwon', vi:'công viên', pos:'danh từ', hanja:'公園', hv:'công viên'},
  {ko:'극장', rom:'geukjang', vi:'rạp hát, rạp phim', pos:'danh từ', hanja:'劇場', hv:'kịch trường'},
  {ko:'공항', rom:'gonghang', vi:'sân bay', pos:'danh từ', hanja:'空港', hv:'không cảng'},
  {ko:'호텔', rom:'hotel', vi:'khách sạn', pos:'danh từ'},
  {ko:'교회', rom:'gyohoe', vi:'nhà thờ', pos:'danh từ', hanja:'敎會', hv:'giáo hội'},
  {ko:'백화점', rom:'baekhwajeom', vi:'trung tâm thương mại', pos:'danh từ', hanja:'百貨店', hv:'bách hoá điếm'},
  {ko:'편의점', rom:'pyeonuijeom', vi:'cửa hàng tiện lợi', pos:'danh từ', hanja:'便宜店', hv:'tiện nghi điếm'},
  {ko:'카페', rom:'kape', vi:'quán cà phê', pos:'danh từ'},
  {ko:'화장실', rom:'hwajangsil', vi:'nhà vệ sinh', pos:'danh từ', hanja:'化粧室', hv:'hoá trang thất'},

  /* ---------- Giao thông (교통) ---------- */
  {ko:'길', rom:'gil', vi:'đường', pos:'danh từ'},
  {ko:'차', rom:'cha', vi:'xe hơi', pos:'danh từ', hanja:'車', hv:'xa'},
  {ko:'오토바이', rom:'otobai', vi:'xe máy', pos:'danh từ'},
  {ko:'비행기', rom:'bihaenggi', vi:'máy bay', pos:'danh từ', hanja:'飛行機', hv:'phi hành cơ'},
  {ko:'배', rom:'bae', vi:'thuyền, tàu thuỷ', pos:'danh từ'},
  {ko:'표', rom:'pyo', vi:'vé', pos:'danh từ', hanja:'票', hv:'phiếu'},

  /* ---------- Thời gian (시간) ---------- */
  {ko:'시간', rom:'sigan', vi:'thời gian; tiếng', pos:'danh từ', hanja:'時間', hv:'thời gian'},
  {ko:'오전', rom:'ojeon', vi:'buổi sáng (AM)', pos:'danh từ', hanja:'午前', hv:'ngọ tiền'},
  {ko:'오후', rom:'ohu', vi:'buổi chiều (PM)', pos:'danh từ', hanja:'午後', hv:'ngọ hậu'},
  {ko:'밤', rom:'bam', vi:'ban đêm', pos:'danh từ'},
  {ko:'새벽', rom:'saebyeok', vi:'rạng sáng', pos:'danh từ'},
  {ko:'주', rom:'ju', vi:'tuần', pos:'danh từ', hanja:'週', hv:'chu'},
  {ko:'달', rom:'dal', vi:'tháng', pos:'danh từ'},
  {ko:'년', rom:'nyeon', vi:'năm', pos:'danh từ', hanja:'年', hv:'niên'},
  {ko:'올해', rom:'olhae', vi:'năm nay', pos:'danh từ'},
  {ko:'작년', rom:'jangnyeon', vi:'năm ngoái', pos:'danh từ', hanja:'昨年', hv:'tạc niên'},
  {ko:'내년', rom:'naenyeon', vi:'năm sau', pos:'danh từ', hanja:'來年', hv:'lai niên'},
  {ko:'지금', rom:'jigeum', vi:'bây giờ', pos:'danh từ', hanja:'只今', hv:'chỉ kim'},
  {ko:'나중', rom:'najung', vi:'sau này', pos:'danh từ'},
  {ko:'요즘', rom:'yojeum', vi:'dạo này', pos:'danh từ'},
  {ko:'항상', rom:'hangsang', vi:'luôn luôn', pos:'phó từ', hanja:'恒常', hv:'hằng thường'},
  {ko:'벌써', rom:'beolsseo', vi:'đã… rồi', pos:'phó từ'},
  {ko:'아직', rom:'ajik', vi:'vẫn chưa', pos:'phó từ'},
  {ko:'금방', rom:'geumbang', vi:'vừa mới; ngay', pos:'phó từ'},

  /* ---------- Động từ thường dùng (동사) ---------- */
  {ko:'하다', rom:'hada', vi:'làm', pos:'động từ'},
  {ko:'되다', rom:'doeda', vi:'trở thành, được', pos:'động từ'},
  {ko:'주다', rom:'juda', vi:'cho', pos:'động từ'},
  {ko:'받다', rom:'batda', vi:'nhận', pos:'động từ'},
  {ko:'사다', rom:'sada', vi:'mua', pos:'động từ'},
  {ko:'팔다', rom:'palda', vi:'bán', pos:'động từ'},
  {ko:'열다', rom:'yeolda', vi:'mở', pos:'động từ'},
  {ko:'닫다', rom:'datda', vi:'đóng', pos:'động từ'},
  {ko:'켜다', rom:'kyeoda', vi:'bật', pos:'động từ'},
  {ko:'끄다', rom:'kkeuda', vi:'tắt', pos:'động từ'},
  {ko:'울다', rom:'ulda', vi:'khóc', pos:'động từ'},
  {ko:'웃다', rom:'utda', vi:'cười', pos:'động từ'},
  {ko:'앉다', rom:'anda', vi:'ngồi', pos:'động từ'},
  {ko:'서다', rom:'seoda', vi:'đứng', pos:'động từ'},
  {ko:'걷다', rom:'geotda', vi:'đi bộ', pos:'động từ'},
  {ko:'뛰다', rom:'ttwida', vi:'chạy', pos:'động từ'},
  {ko:'날다', rom:'nalda', vi:'bay', pos:'động từ'},
  {ko:'들다', rom:'deulda', vi:'cầm, nâng', pos:'động từ'},
  {ko:'놓다', rom:'nota', vi:'đặt, để xuống', pos:'động từ'},
  {ko:'찾다', rom:'chatda', vi:'tìm', pos:'động từ'},
  {ko:'잃다', rom:'ilta', vi:'mất, đánh mất', pos:'động từ'},
  {ko:'기다리다', rom:'gidarida', vi:'chờ, đợi', pos:'động từ'},
  {ko:'생각하다', rom:'saenggakhada', vi:'nghĩ', pos:'động từ'},
  {ko:'알다', rom:'alda', vi:'biết', pos:'động từ'},
  {ko:'모르다', rom:'moreuda', vi:'không biết', pos:'động từ'},
  {ko:'믿다', rom:'mitda', vi:'tin', pos:'động từ'},
  {ko:'좋아하다', rom:'joahada', vi:'thích', pos:'động từ'},
  {ko:'싫어하다', rom:'sireohada', vi:'ghét', pos:'động từ'},
  {ko:'원하다', rom:'wonhada', vi:'muốn', pos:'động từ'},
  {ko:'돕다', rom:'dopda', vi:'giúp', pos:'động từ'},
  {ko:'가르치다', rom:'gareuchida', vi:'dạy', pos:'động từ'},
  {ko:'배우다', rom:'baeuda', vi:'học', pos:'động từ'},
  {ko:'묻다', rom:'mutda', vi:'hỏi', pos:'động từ'},
  {ko:'대답하다', rom:'daedaphada', vi:'trả lời', pos:'động từ', hanja:'對答—', hv:'đối đáp'},
  {ko:'말하다', rom:'malhada', vi:'nói', pos:'động từ'},
  {ko:'듣다', rom:'deutda', vi:'nghe', pos:'động từ'},
  {ko:'쓰다', rom:'sseuda', vi:'viết; dùng', pos:'động từ'},
  {ko:'그리다', rom:'geurida', vi:'vẽ', pos:'động từ'},
  {ko:'만들다', rom:'mandeulda', vi:'làm ra, tạo', pos:'động từ'},
  {ko:'고치다', rom:'gochida', vi:'sửa', pos:'động từ'},
  {ko:'씻다', rom:'ssitda', vi:'rửa', pos:'động từ'},
  {ko:'청소하다', rom:'cheongsohada', vi:'dọn dẹp', pos:'động từ', hanja:'淸掃—', hv:'thanh tảo'},
  {ko:'빨래하다', rom:'ppallaehada', vi:'giặt đồ', pos:'động từ'},
  {ko:'들어가다', rom:'deureogada', vi:'đi vào', pos:'động từ'},
  {ko:'나가다', rom:'nagada', vi:'đi ra', pos:'động từ'},
  {ko:'올라가다', rom:'ollagada', vi:'đi lên', pos:'động từ'},
  {ko:'내려가다', rom:'naeryeogada', vi:'đi xuống', pos:'động từ'},
  {ko:'돌아가다', rom:'doragada', vi:'quay về', pos:'động từ'},
  {ko:'죽다', rom:'jukda', vi:'chết', pos:'động từ'},
  {ko:'살다', rom:'salda', vi:'sống', pos:'động từ'},

  /* ---------- Tính từ thường dùng (형용사) ---------- */
  {ko:'크다', rom:'keuda', vi:'to, lớn', pos:'tính từ'},
  {ko:'작다', rom:'jakda', vi:'nhỏ', pos:'tính từ'},
  {ko:'많다', rom:'manta', vi:'nhiều', pos:'tính từ'},
  {ko:'적다', rom:'jeokda', vi:'ít', pos:'tính từ'},
  {ko:'높다', rom:'nopda', vi:'cao', pos:'tính từ'},
  {ko:'낮다', rom:'natda', vi:'thấp', pos:'tính từ'},
  {ko:'길다', rom:'gilda', vi:'dài', pos:'tính từ'},
  {ko:'짧다', rom:'jjalda', vi:'ngắn', pos:'tính từ'},
  {ko:'빠르다', rom:'ppareuda', vi:'nhanh', pos:'tính từ'},
  {ko:'느리다', rom:'neurida', vi:'chậm', pos:'tính từ'},
  {ko:'새롭다', rom:'saeropda', vi:'mới', pos:'tính từ'},
  {ko:'낡다', rom:'nakda', vi:'cũ, sờn', pos:'tính từ'},
  {ko:'좋다', rom:'jota', vi:'tốt', pos:'tính từ'},
  {ko:'나쁘다', rom:'nappeuda', vi:'xấu, tệ', pos:'tính từ'},
  {ko:'예쁘다', rom:'yeppeuda', vi:'đẹp, xinh', pos:'tính từ'},
  {ko:'멋있다', rom:'meositda', vi:'ngầu, bảnh', pos:'tính từ'},
  {ko:'깨끗하다', rom:'kkaekkeutada', vi:'sạch sẽ', pos:'tính từ'},
  {ko:'더럽다', rom:'deoreopda', vi:'bẩn', pos:'tính từ'},
  {ko:'쉽다', rom:'swipda', vi:'dễ', pos:'tính từ'},
  {ko:'어렵다', rom:'eoryeopda', vi:'khó', pos:'tính từ'},
  {ko:'무겁다', rom:'mugeopda', vi:'nặng', pos:'tính từ'},
  {ko:'가볍다', rom:'gabyeopda', vi:'nhẹ', pos:'tính từ'},
  {ko:'덥다', rom:'deopda', vi:'nóng (thời tiết)', pos:'tính từ'},
  {ko:'춥다', rom:'chupda', vi:'lạnh (thời tiết)', pos:'tính từ'},
  {ko:'뜨겁다', rom:'tteugeopda', vi:'nóng (đồ vật)', pos:'tính từ'},
  {ko:'차갑다', rom:'chagapda', vi:'lạnh (đồ vật)', pos:'tính từ'},
  {ko:'밝다', rom:'bakda', vi:'sáng', pos:'tính từ'},
  {ko:'어둡다', rom:'eodupda', vi:'tối', pos:'tính từ'},
  {ko:'조용하다', rom:'joyonghada', vi:'yên tĩnh', pos:'tính từ'},
  {ko:'시끄럽다', rom:'sikkeureopda', vi:'ồn ào', pos:'tính từ'},
  {ko:'행복하다', rom:'haengbokhada', vi:'hạnh phúc', pos:'tính từ', hanja:'幸福—', hv:'hạnh phúc'},
  {ko:'슬프다', rom:'seulpeuda', vi:'buồn', pos:'tính từ'},
  {ko:'화나다', rom:'hwanada', vi:'tức giận', pos:'động từ'},
  {ko:'무섭다', rom:'museopda', vi:'sợ, đáng sợ', pos:'tính từ'},
  {ko:'심심하다', rom:'simsimhada', vi:'chán', pos:'tính từ'},
  {ko:'재미있다', rom:'jaemiitda', vi:'thú vị, vui', pos:'tính từ'},
  {ko:'재미없다', rom:'jaemieopda', vi:'nhạt, chán', pos:'tính từ'},
  {ko:'피곤하다', rom:'pigonhada', vi:'mệt', pos:'tính từ', hanja:'疲困—', hv:'bì khốn'},
  {ko:'아프다', rom:'apeuda', vi:'đau, ốm', pos:'tính từ'},
  {ko:'건강하다', rom:'geonganghada', vi:'khoẻ mạnh', pos:'tính từ', hanja:'健康—', hv:'kiện khang'},
  {ko:'바쁘다', rom:'bappeuda', vi:'bận', pos:'tính từ'},
  {ko:'중요하다', rom:'jungyohada', vi:'quan trọng', pos:'tính từ', hanja:'重要—', hv:'trọng yếu'},
  {ko:'유명하다', rom:'yumyeonghada', vi:'nổi tiếng', pos:'tính từ', hanja:'有名—', hv:'hữu danh'},
  {ko:'편하다', rom:'pyeonhada', vi:'thoải mái, tiện', pos:'tính từ', hanja:'便—', hv:'tiện'},
  {ko:'불편하다', rom:'bulpyeonhada', vi:'bất tiện', pos:'tính từ', hanja:'不便—', hv:'bất tiện'},
  {ko:'비슷하다', rom:'biseutada', vi:'giống, tương tự', pos:'tính từ'},
  {ko:'다르다', rom:'dareuda', vi:'khác', pos:'tính từ'},
  {ko:'같다', rom:'gatda', vi:'giống nhau', pos:'tính từ'},

  /* ---------- Phó từ & liên từ hay gặp ---------- */
  {ko:'아주', rom:'aju', vi:'rất', pos:'phó từ'},
  {ko:'너무', rom:'neomu', vi:'quá', pos:'phó từ'},
  {ko:'정말', rom:'jeongmal', vi:'thật sự', pos:'phó từ'},
  {ko:'조금', rom:'jogeum', vi:'một chút', pos:'phó từ'},
  {ko:'많이', rom:'mani', vi:'nhiều', pos:'phó từ'},
  {ko:'빨리', rom:'ppalli', vi:'nhanh lên', pos:'phó từ'},
  {ko:'천천히', rom:'cheoncheonhi', vi:'từ từ', pos:'phó từ'},
  {ko:'같이', rom:'gachi', vi:'cùng nhau', pos:'phó từ'},
  {ko:'혼자', rom:'honja', vi:'một mình', pos:'phó từ'},
  {ko:'다시', rom:'dasi', vi:'lại, lần nữa', pos:'phó từ'},
  {ko:'먼저', rom:'meonjeo', vi:'trước tiên', pos:'phó từ'},
  {ko:'그리고', rom:'geurigo', vi:'và, rồi', pos:'liên từ'},
  {ko:'그래서', rom:'geuraeseo', vi:'vì vậy', pos:'liên từ'},
  {ko:'그러나', rom:'geureona', vi:'nhưng', pos:'liên từ'},
  {ko:'그런데', rom:'geureonde', vi:'nhưng mà, vả lại', pos:'liên từ'},
  {ko:'그러면', rom:'geureomyeon', vi:'nếu vậy thì', pos:'liên từ'},
  {ko:'그러니까', rom:'geureonikka', vi:'cho nên', pos:'liên từ'},
  {ko:'왜냐하면', rom:'waenyahamyeon', vi:'bởi vì', pos:'liên từ'},
  {ko:'만약', rom:'manyak', vi:'nếu như', pos:'phó từ', hanja:'萬若', hv:'vạn nhược'},

  /* ---------- Học tập & công việc ---------- */
  {ko:'공부', rom:'gongbu', vi:'việc học', pos:'danh từ', hanja:'工夫', hv:'công phu'},
  {ko:'숙제', rom:'sukje', vi:'bài tập về nhà', pos:'danh từ', hanja:'宿題', hv:'túc đề'},
  {ko:'시험', rom:'siheom', vi:'kỳ thi', pos:'danh từ', hanja:'試驗', hv:'thí nghiệm'},
  {ko:'문제', rom:'munje', vi:'vấn đề; câu hỏi', pos:'danh từ', hanja:'問題', hv:'vấn đề'},
  {ko:'질문', rom:'jilmun', vi:'câu hỏi', pos:'danh từ', hanja:'質問', hv:'chất vấn'},
  {ko:'대답', rom:'daedap', vi:'câu trả lời', pos:'danh từ', hanja:'對答', hv:'đối đáp'},
  {ko:'수업', rom:'sueop', vi:'tiết học', pos:'danh từ', hanja:'授業', hv:'thụ nghiệp'},
  {ko:'방학', rom:'banghak', vi:'kỳ nghỉ (trường)', pos:'danh từ', hanja:'放學', hv:'phóng học'},
  {ko:'일', rom:'il', vi:'công việc; việc', pos:'danh từ'},
  {ko:'돈', rom:'don', vi:'tiền', pos:'danh từ'},
  {ko:'값', rom:'gap', vi:'giá', pos:'danh từ'},
  {ko:'가격', rom:'gagyeok', vi:'giá cả', pos:'danh từ', hanja:'價格', hv:'giá cách'},

  /* ---------- Từ để hỏi & đại từ ---------- */
  {ko:'누구', rom:'nugu', vi:'ai', pos:'từ để hỏi'},
  {ko:'무엇', rom:'mueot', vi:'cái gì', pos:'từ để hỏi'},
  {ko:'어디', rom:'eodi', vi:'ở đâu', pos:'từ để hỏi'},
  {ko:'언제', rom:'eonje', vi:'khi nào', pos:'từ để hỏi'},
  {ko:'왜', rom:'wae', vi:'tại sao', pos:'từ để hỏi'},
  {ko:'어떻게', rom:'eotteoke', vi:'như thế nào', pos:'từ để hỏi'},
  {ko:'얼마', rom:'eolma', vi:'bao nhiêu', pos:'từ để hỏi'},
  {ko:'몇', rom:'myeot', vi:'mấy', pos:'từ để hỏi'},
  {ko:'이것', rom:'igeot', vi:'cái này', pos:'đại từ'},
  {ko:'그것', rom:'geugeot', vi:'cái đó', pos:'đại từ'},
  {ko:'저것', rom:'jeogeot', vi:'cái kia', pos:'đại từ'},
  {ko:'여기', rom:'yeogi', vi:'ở đây', pos:'đại từ'},
  {ko:'거기', rom:'geogi', vi:'ở đó', pos:'đại từ'},
  {ko:'저기', rom:'jeogi', vi:'ở kia', pos:'đại từ'},
  {ko:'우리', rom:'uri', vi:'chúng ta, chúng tôi', pos:'đại từ'},

  /* ---------- Sở thích & giải trí ---------- */
  {ko:'취미', rom:'chwimi', vi:'sở thích', pos:'danh từ', hanja:'趣味', hv:'thú vị'},
  {ko:'영화', rom:'yeonghwa', vi:'phim', pos:'danh từ', hanja:'映畵', hv:'ánh hoạ'},
  {ko:'음악', rom:'eumak', vi:'âm nhạc', pos:'danh từ', hanja:'音樂', hv:'âm nhạc'},
  {ko:'노래', rom:'norae', vi:'bài hát', pos:'danh từ'},
  {ko:'춤', rom:'chum', vi:'điệu nhảy', pos:'danh từ'},
  {ko:'그림', rom:'geurim', vi:'bức tranh', pos:'danh từ'},
  {ko:'사진', rom:'sajin', vi:'ảnh', pos:'danh từ', hanja:'寫眞', hv:'tả chân'},
  {ko:'책', rom:'chaek', vi:'sách', pos:'danh từ', hanja:'冊', hv:'sách'},
  {ko:'신문', rom:'sinmun', vi:'báo', pos:'danh từ', hanja:'新聞', hv:'tân văn'},
  {ko:'게임', rom:'geim', vi:'trò chơi', pos:'danh từ'},
  {ko:'운동', rom:'undong', vi:'thể thao', pos:'danh từ', hanja:'運動', hv:'vận động'},
  {ko:'축구', rom:'chukgu', vi:'bóng đá', pos:'danh từ', hanja:'蹴球', hv:'xúc cầu'},
  {ko:'농구', rom:'nonggu', vi:'bóng rổ', pos:'danh từ', hanja:'籠球', hv:'lung cầu'},
  {ko:'수영', rom:'suyeong', vi:'bơi lội', pos:'danh từ', hanja:'水泳', hv:'thuỷ vịnh'},
  {ko:'여행', rom:'yeohaeng', vi:'du lịch', pos:'danh từ', hanja:'旅行', hv:'lữ hành'},

  /* ---------- Chào hỏi & biểu hiện ---------- */
  {ko:'안녕히 가세요', rom:'annyeonghi gaseyo', vi:'tạm biệt (người ở lại nói)', pos:'biểu hiện'},
  {ko:'안녕히 계세요', rom:'annyeonghi gyeseyo', vi:'tạm biệt (người đi nói)', pos:'biểu hiện'},
  {ko:'감사합니다', rom:'gamsahamnida', vi:'cảm ơn', pos:'biểu hiện', hanja:'感謝—', hv:'cảm tạ'},
  {ko:'고맙습니다', rom:'gomapseumnida', vi:'cảm ơn', pos:'biểu hiện'},
  {ko:'죄송합니다', rom:'joesonghamnida', vi:'xin lỗi', pos:'biểu hiện', hanja:'罪悚—', hv:'tội tủng'},
  {ko:'미안합니다', rom:'mianhamnida', vi:'xin lỗi', pos:'biểu hiện', hanja:'未安—', hv:'vị an'},
  {ko:'괜찮다', rom:'gwaenchanta', vi:'không sao, ổn', pos:'tính từ'},
  {ko:'축하합니다', rom:'chukhahamnida', vi:'chúc mừng', pos:'biểu hiện', hanja:'祝賀—', hv:'chúc hạ'},
  {ko:'실례합니다', rom:'sillyehamnida', vi:'xin phép, cho hỏi', pos:'biểu hiện', hanja:'失禮—', hv:'thất lễ'},
  {ko:'환영합니다', rom:'hwanyeonghamnida', vi:'chào mừng', pos:'biểu hiện', hanja:'歡迎—', hv:'hoan nghênh'},

  /* ---------- Số & đếm ---------- */
  {ko:'번호', rom:'beonho', vi:'số (thứ tự)', pos:'danh từ', hanja:'番號', hv:'phiên hiệu'},
  {ko:'개', rom:'gae', vi:'cái (đơn vị đếm)', pos:'đơn vị', hanja:'個', hv:'cá'},
  {ko:'명', rom:'myeong', vi:'người (đơn vị đếm)', pos:'đơn vị', hanja:'名', hv:'danh'},
  {ko:'마리', rom:'mari', vi:'con (đếm động vật)', pos:'đơn vị'},
  {ko:'권', rom:'gwon', vi:'quyển', pos:'đơn vị', hanja:'卷', hv:'quyển'},
  {ko:'장', rom:'jang', vi:'tờ, tấm', pos:'đơn vị', hanja:'張', hv:'trương'},
  {ko:'번', rom:'beon', vi:'lần', pos:'đơn vị', hanja:'番', hv:'phiên'},
  {ko:'살', rom:'sal', vi:'tuổi', pos:'đơn vị'},
  {ko:'반', rom:'ban', vi:'một nửa; lớp', pos:'danh từ', hanja:'半', hv:'bán'},

  /* ============================================================
     TỪ KHOÁ TRONG BÀI ĐỌC (js/readings-ko.js · js/readings.js)
     Mọi từ khoá của 50 bài đọc tiếng Hàn đều phải tra được.
     Phần dưới bù những mục giáo trình chưa dạy.
     ============================================================ */

  /* ---------- Nhà ở · đồ đạc ---------- */
  {ko:'자취방', rom:'jachwibang', vi:'phòng trọ tự nấu ăn', pos:'danh từ', hanja:'自炊房', hv:'tự xuý phòng'},
  {ko:'보증금', rom:'bojeunggeum', vi:'tiền đặt cọc', pos:'danh từ', hanja:'保證金', hv:'bảo chứng kim'},
  {ko:'조건', rom:'jogeon', vi:'điều kiện', pos:'danh từ', hanja:'條件', hv:'điều kiện'},
  {ko:'계약하다', rom:'gyeyakhada', vi:'ký hợp đồng', pos:'động từ', hanja:'契約—', hv:'khế ước'},
  {ko:'엘리베이터', rom:'ellibeiteo', vi:'thang máy', pos:'danh từ'},
  {ko:'윗집', rom:'witjip', vi:'nhà tầng trên', pos:'danh từ'},
  {ko:'층간 소음', rom:'cheunggan soeum', vi:'tiếng ồn giữa các tầng', pos:'cụm danh từ', hanja:'層間騷音', hv:'tầng gian tao âm'},
  {ko:'집들이', rom:'jipdeuri', vi:'tiệc mừng nhà mới, tân gia', pos:'danh từ'},
  {ko:'상자', rom:'sangja', vi:'cái hộp, thùng', pos:'danh từ', hanja:'箱子', hv:'tương tử'},
  {ko:'휴지', rom:'hyuji', vi:'giấy vệ sinh', pos:'danh từ', hanja:'休紙', hv:'hưu chỉ'},
  {ko:'세제', rom:'seje', vi:'bột giặt, chất tẩy rửa', pos:'danh từ', hanja:'洗劑', hv:'tẩy tễ'},
  {ko:'저울', rom:'jeoul', vi:'cái cân', pos:'danh từ'},
  {ko:'탈의실', rom:'taruisil', vi:'phòng thử đồ', pos:'danh từ', hanja:'脫衣室', hv:'thoát y thất'},
  {ko:'골목', rom:'golmok', vi:'ngõ, hẻm', pos:'danh từ'},
  {ko:'밑', rom:'mit', vi:'phía dưới', pos:'danh từ'},
  {ko:'밖', rom:'bak', vi:'bên ngoài', pos:'danh từ'},
  {ko:'안', rom:'an', vi:'bên trong', pos:'danh từ'},
  {ko:'창가', rom:'changga', vi:'cạnh cửa sổ', pos:'danh từ', hanja:'窓—', hv:'song'},
  {ko:'자리', rom:'jari', vi:'chỗ, chỗ ngồi', pos:'danh từ'},
  {ko:'노약자석', rom:'noyakjaseok', vi:'ghế ưu tiên', pos:'danh từ', hanja:'老弱者席', hv:'lão nhược giả tịch'},

  /* ---------- Mua sắm · dịch vụ ---------- */
  {ko:'택배', rom:'taekbae', vi:'giao hàng tận nơi', pos:'danh từ', hanja:'宅配', hv:'trạch phối'},
  {ko:'배달', rom:'baedal', vi:'việc giao hàng tận nơi', pos:'danh từ', hanja:'配達', hv:'phối đạt'},
  {ko:'배달하다', rom:'baedalhada', vi:'giao hàng tận nơi', pos:'động từ', hanja:'配達—', hv:'phối đạt'},
  {ko:'매장', rom:'maejang', vi:'cửa hàng, gian hàng', pos:'danh từ', hanja:'賣場', hv:'mại trường'},
  {ko:'전통 시장', rom:'jeontong sijang', vi:'chợ truyền thống', pos:'cụm danh từ', hanja:'傳統市場', hv:'truyền thống thị trường'},
  {ko:'가격표', rom:'gagyeokpyo', vi:'bảng giá', pos:'danh từ', hanja:'價格表', hv:'giá cách biểu'},
  {ko:'덤', rom:'deom', vi:'phần cho thêm', pos:'danh từ'},
  {ko:'공짜', rom:'gongjja', vi:'miễn phí, của chùa', pos:'danh từ'},
  {ko:'할부', rom:'halbu', vi:'trả góp', pos:'danh từ', hanja:'割賦', hv:'cát phú'},
  {ko:'요금제', rom:'yogeumje', vi:'gói cước', pos:'danh từ', hanja:'料金制', hv:'liệu kim chế'},
  {ko:'중고', rom:'junggo', vi:'đồ cũ, hàng second-hand', pos:'danh từ', hanja:'中古', hv:'trung cổ'},
  {ko:'판매자', rom:'panmaeja', vi:'người bán', pos:'danh từ', hanja:'販賣者', hv:'phiến mại giả'},
  {ko:'사이즈', rom:'saijeu', vi:'cỡ, kích thước', pos:'danh từ'},
  {ko:'묶음', rom:'mukkeum', vi:'lốc, bó', pos:'danh từ'},
  {ko:'무게', rom:'muge', vi:'cân nặng, trọng lượng', pos:'danh từ'},
  {ko:'분실물', rom:'bunsilmul', vi:'đồ thất lạc', pos:'danh từ', hanja:'紛失物', hv:'phân thất vật'},
  {ko:'일회용', rom:'ilhoeyong', vi:'loại dùng một lần', pos:'danh từ', hanja:'一回用', hv:'nhất hồi dụng'},
  {ko:'다회용 용기', rom:'dahoeyong yonggi', vi:'hộp tái sử dụng', pos:'cụm danh từ', hanja:'多回用容器', hv:'đa hồi dụng dung khí'},
  {ko:'사고팔다', rom:'sagopalda', vi:'mua bán', pos:'động từ'},
  {ko:'이용하다', rom:'iyonghada', vi:'sử dụng', pos:'động từ', hanja:'利用—', hv:'lợi dụng'},
  {ko:'구하다', rom:'guhada', vi:'tìm kiếm (nhà, việc)', pos:'động từ', hanja:'求—', hv:'cầu'},
  {ko:'딱 맞다', rom:'ttak matda', vi:'vừa in, khít', pos:'cụm động từ'},
  {ko:'인기가 많다', rom:'ingiga manta', vi:'được ưa chuộng', pos:'cụm động từ', hanja:'人氣—', hv:'nhân khí'},

  /* ---------- Công việc · giấy tờ ---------- */
  {ko:'직원', rom:'jigwon', vi:'nhân viên', pos:'danh từ', hanja:'職員', hv:'chức viên'},
  {ko:'부장님', rom:'bujangnim', vi:'trưởng phòng', pos:'danh từ', hanja:'部長—', hv:'bộ trưởng'},
  {ko:'역무원', rom:'yeongmuwon', vi:'nhân viên nhà ga', pos:'danh từ', hanja:'驛務員', hv:'dịch vụ viên'},
  {ko:'미용사', rom:'miyongsa', vi:'thợ làm tóc', pos:'danh từ', hanja:'美容師', hv:'mỹ dung sư'},
  {ko:'간호사', rom:'ganhosa', vi:'y tá, điều dưỡng', pos:'danh từ', hanja:'看護師', hv:'khán hộ sư'},
  {ko:'입사하다', rom:'ipsahada', vi:'vào công ty làm', pos:'động từ', hanja:'入社—', hv:'nhập xã'},
  {ko:'회식', rom:'hoesik', vi:'tiệc liên hoan công ty', pos:'danh từ', hanja:'會食', hv:'hội thực'},
  {ko:'자기소개서', rom:'jagisogaeseo', vi:'thư giới thiệu bản thân', pos:'danh từ', hanja:'自己紹介書', hv:'tự kỷ thiệu giới thư'},
  {ko:'약점', rom:'yakjeom', vi:'điểm yếu', pos:'danh từ', hanja:'弱點', hv:'nhược điểm'},
  {ko:'비밀번호', rom:'bimilbeonho', vi:'mật khẩu', pos:'danh từ', hanja:'祕密番號', hv:'bí mật phiên hiệu'},
  {ko:'번호표를 뽑다', rom:'beonhopyoreul ppopda', vi:'rút số thứ tự', pos:'cụm động từ', hanja:'番號票—', hv:'phiên hiệu phiếu'},
  {ko:'주문을 받다', rom:'jumuneul batda', vi:'nhận đơn gọi món', pos:'cụm động từ', hanja:'注文—', hv:'chú văn'},
  {ko:'확인하다', rom:'hwaginhada', vi:'kiểm tra, xác nhận', pos:'động từ', hanja:'確認—', hv:'xác nhận'},
  {ko:'지적하다', rom:'jijeokhada', vi:'chỉ ra, nêu vấn đề', pos:'động từ', hanja:'指摘—', hv:'chỉ trích'},
  {ko:'지자체', rom:'jijache', vi:'chính quyền địa phương', pos:'danh từ', hanja:'自治體', hv:'tự trị thể'},
  {ko:'기준', rom:'gijun', vi:'tiêu chuẩn, cái chuẩn', pos:'danh từ', hanja:'基準', hv:'cơ chuẩn'},
  {ko:'일인 가구', rom:'irin gagu', vi:'hộ một người', pos:'cụm danh từ', hanja:'一人家口', hv:'nhất nhân gia khẩu'},

  /* ---------- Học tập · ngôn ngữ ---------- */
  {ko:'고등학생', rom:'godeunghaksaeng', vi:'học sinh cấp ba', pos:'danh từ', hanja:'高等學生', hv:'cao đẳng học sinh'},
  {ko:'시험 기간', rom:'siheom gigan', vi:'mùa thi, kỳ thi', pos:'cụm danh từ', hanja:'試驗期間', hv:'thí nghiệm kỳ gian'},
  {ko:'외우다', rom:'oeuda', vi:'học thuộc', pos:'động từ'},
  {ko:'높임말', rom:'nopimmal', vi:'kính ngữ', pos:'danh từ'},
  {ko:'반말', rom:'banmal', vi:'lối nói thân mật, không kính ngữ', pos:'danh từ', hanja:'半—', hv:'bán'},
  {ko:'말을 놓다', rom:'mareul nota', vi:'bỏ kính ngữ, chuyển sang nói thân mật', pos:'cụm động từ'},
  {ko:'말을 걸다', rom:'mareul geolda', vi:'bắt chuyện', pos:'cụm động từ'},
  {ko:'말씀하시다', rom:'malsseumhasida', vi:'nói (kính ngữ)', pos:'động từ'},
  {ko:'여쭤보다', rom:'yeojjwoboda', vi:'hỏi (kính ngữ)', pos:'động từ'},
  {ko:'뵙다', rom:'boepda', vi:'gặp (kính ngữ)', pos:'động từ'},
  {ko:'주무시다', rom:'jumusida', vi:'ngủ (kính ngữ)', pos:'động từ'},
  {ko:'소리 내어 읽다', rom:'sori naeeo ikda', vi:'đọc to thành tiếng', pos:'cụm động từ'},
  {ko:'틀리다', rom:'teullida', vi:'sai, nhầm', pos:'động từ'},
  {ko:'자막', rom:'jamak', vi:'phụ đề', pos:'danh từ', hanja:'字幕', hv:'tự mạc'},
  {ko:'대사', rom:'daesa', vi:'lời thoại', pos:'danh từ', hanja:'臺詞', hv:'đài từ'},
  {ko:'줄거리', rom:'julgeori', vi:'nội dung, cốt truyện', pos:'danh từ'},
  {ko:'시기', rom:'sigi', vi:'giai đoạn, thời kỳ', pos:'danh từ', hanja:'時期', hv:'thời kỳ'},
  {ko:'쌓이다', rom:'ssahida', vi:'chất chồng, tích lại', pos:'động từ'},
  {ko:'시도하다', rom:'sidohada', vi:'thử sức, thử làm', pos:'động từ', hanja:'試圖—', hv:'thí đồ'},
  {ko:'비교하다', rom:'bigyohada', vi:'so sánh', pos:'động từ', hanja:'比較—', hv:'tỉ giác'},
  {ko:'발견하다', rom:'balgyeonhada', vi:'phát hiện, tìm ra', pos:'động từ', hanja:'發見—', hv:'phát kiến'},

  /* ---------- Sức khoẻ · cơ thể ---------- */
  {ko:'감기에 걸리다', rom:'gamgie geollida', vi:'bị cảm', pos:'cụm động từ', hanja:'感氣—', hv:'cảm khí'},
  {ko:'약을 먹다', rom:'yageul meokda', vi:'uống thuốc', pos:'cụm động từ', hanja:'藥—', hv:'dược'},
  {ko:'열이 나다', rom:'yeori nada', vi:'bị sốt', pos:'cụm động từ', hanja:'熱—', hv:'nhiệt'},
  {ko:'콧물이 나다', rom:'konmuri nada', vi:'chảy nước mũi', pos:'cụm động từ'},
  {ko:'숨이 차다', rom:'sumi chada', vi:'hụt hơi, thở dốc', pos:'cụm động từ'},
  {ko:'푹 쉬다', rom:'puk swida', vi:'nghỉ cho đã', pos:'cụm động từ'},
  {ko:'지치다', rom:'jichida', vi:'kiệt sức', pos:'động từ'},
  {ko:'떨리다', rom:'tteollida', vi:'run', pos:'động từ'},
  {ko:'임산부', rom:'imsanbu', vi:'phụ nữ mang thai', pos:'danh từ', hanja:'妊産婦', hv:'nhâm sản phụ'},
  {ko:'털', rom:'teol', vi:'lông', pos:'danh từ'},
  {ko:'냄새를 맡다', rom:'naemsaereul matda', vi:'ngửi thấy mùi', pos:'cụm động từ'},

  /* ---------- Đi lại ---------- */
  {ko:'호선', rom:'hoseon', vi:'tuyến (số) tàu điện ngầm', pos:'danh từ', hanja:'號線', hv:'hiệu tuyến'},
  {ko:'고속도로', rom:'gosokdoro', vi:'đường cao tốc', pos:'danh từ', hanja:'高速道路', hv:'cao tốc đạo lộ'},
  {ko:'서서 가다', rom:'seoseo gada', vi:'đứng mà đi (trên xe)', pos:'cụm động từ'},
  {ko:'놓고 내리다', rom:'noko naerida', vi:'để quên rồi xuống xe', pos:'cụm động từ'},
  {ko:'비켜 주다', rom:'bikyeo juda', vi:'nhường chỗ, tránh ra', pos:'cụm động từ'},
  {ko:'자리를 비우다', rom:'jarireul biuda', vi:'bỏ trống chỗ, rời chỗ', pos:'cụm động từ'},
  {ko:'뛰어가다', rom:'ttwieogada', vi:'chạy đến', pos:'động từ'},
  {ko:'데려가다', rom:'deryeogada', vi:'dẫn ai đi cùng', pos:'động từ'},
  {ko:'서두르다', rom:'seodureuda', vi:'vội vàng, gấp gáp', pos:'động từ'},
  {ko:'싣다', rom:'sitda', vi:'chất, xếp lên xe', pos:'động từ'},

  /* ---------- Việc nhà · sinh hoạt ---------- */
  {ko:'빨래', rom:'ppallae', vi:'việc giặt giũ; đồ giặt', pos:'danh từ'},
  {ko:'정리하다', rom:'jeongnihada', vi:'sắp xếp, dọn gọn', pos:'động từ', hanja:'整理—', hv:'chỉnh lý'},
  {ko:'닦다', rom:'dakda', vi:'lau, chùi', pos:'động từ'},
  {ko:'붙이다', rom:'buchida', vi:'dán, gắn', pos:'động từ'},
  {ko:'지우다', rom:'jiuda', vi:'xoá', pos:'động từ'},
  {ko:'자르다', rom:'jareuda', vi:'cắt', pos:'động từ'},
  {ko:'식히다', rom:'sikhida', vi:'để nguội', pos:'động từ'},
  {ko:'펴다', rom:'pyeoda', vi:'trải ra, mở ra', pos:'động từ'},
  {ko:'안다', rom:'anda', vi:'ôm, bế', pos:'động từ'},
  {ko:'잃어버리다', rom:'ireobeorida', vi:'đánh mất', pos:'động từ'},
  {ko:'없어지다', rom:'eopseojida', vi:'biến mất', pos:'động từ'},
  {ko:'깨끗해지다', rom:'kkaekkeutaejida', vi:'trở nên sạch', pos:'động từ'},
  {ko:'음식물 쓰레기', rom:'eumsingmul sseuregi', vi:'rác thực phẩm', pos:'cụm danh từ', hanja:'飮食物—', hv:'ẩm thực vật'},
  {ko:'전용', rom:'jeonyong', vi:'chuyên dụng, dùng riêng', pos:'danh từ', hanja:'專用', hv:'chuyên dụng'},
  {ko:'따로', rom:'ttaro', vi:'riêng ra, tách ra', pos:'trạng từ'},
  {ko:'밥을 사다', rom:'babeul sada', vi:'mời ăn, bao một bữa', pos:'cụm động từ'},
  {ko:'영상 통화', rom:'yeongsang tonghwa', vi:'gọi video', pos:'cụm danh từ', hanja:'映像通話', hv:'ánh tượng thông thoại'},
  {ko:'안부', rom:'anbu', vi:'tin tức, tình hình (hỏi thăm)', pos:'danh từ', hanja:'安否', hv:'an phủ'},
  {ko:'약속을 정하다', rom:'yaksogeul jeonghada', vi:'hẹn gặp, chốt lịch', pos:'cụm động từ', hanja:'約束—定—', hv:'ước thúc · định'},
  {ko:'용기를 내다', rom:'yonggireul naeda', vi:'lấy can đảm', pos:'cụm động từ', hanja:'勇氣—', hv:'dũng khí'},
  {ko:'화를 내다', rom:'hwareul naeda', vi:'nổi giận', pos:'cụm động từ', hanja:'火—', hv:'hoả'},
  {ko:'깜짝 놀라다', rom:'kkamjjak nollada', vi:'giật mình', pos:'cụm động từ'},
  {ko:'마음에 들다', rom:'maeume deulda', vi:'vừa ý, ưng', pos:'cụm động từ'},
  {ko:'노래를 부르다', rom:'noraereul bureuda', vi:'hát', pos:'cụm động từ'},
  {ko:'습관이 되다', rom:'seupgwani doeda', vi:'thành thói quen', pos:'cụm động từ', hanja:'習慣—', hv:'tập quán'},
  {ko:'알려 주다', rom:'allyeo juda', vi:'chỉ bảo cho, cho biết', pos:'cụm động từ'},
  {ko:'도망가다', rom:'domangada', vi:'chạy trốn', pos:'động từ', hanja:'逃亡—', hv:'đào vong'},
  {ko:'지켜보다', rom:'jikyeoboda', vi:'quan sát, theo dõi', pos:'động từ'},
  {ko:'겪다', rom:'gyeokda', vi:'trải qua, gặp phải', pos:'động từ'},
  {ko:'떠오르다', rom:'tteooreuda', vi:'hiện lên (trong đầu); mọc lên', pos:'động từ'},
  {ko:'멈추다', rom:'meomchuda', vi:'dừng lại', pos:'động từ'},
  {ko:'느껴지다', rom:'neukkyeojida', vi:'cảm thấy, thấy như', pos:'động từ'},
  {ko:'달라지다', rom:'dallajida', vi:'thay đổi, khác đi', pos:'động từ'},
  {ko:'늘다', rom:'neulda', vi:'tăng lên; tiến bộ', pos:'động từ'},
  {ko:'정하다', rom:'jeonghada', vi:'quyết định, chọn', pos:'động từ', hanja:'定—', hv:'định'},
  {ko:'꺼지다', rom:'kkeojida', vi:'tắt (máy, đèn)', pos:'động từ'},
  {ko:'젖다', rom:'jeotda', vi:'bị ướt', pos:'động từ'},
  {ko:'비가 오다', rom:'biga oda', vi:'trời mưa', pos:'cụm động từ'},
  {ko:'바람이 불다', rom:'barami bulda', vi:'gió thổi', pos:'cụm động từ'},
  {ko:'햇빛이 들다', rom:'haetbichi deulda', vi:'nắng chiếu vào', pos:'cụm động từ'},
  {ko:'비어 있다', rom:'bieo itda', vi:'đang để trống', pos:'cụm động từ'},
  {ko:'손꼽히다', rom:'sonkkopida', vi:'được xếp vào hàng đầu', pos:'động từ'},
  {ko:'나타나다', rom:'natanada', vi:'xuất hiện, hiện ra', pos:'động từ'},
  {ko:'없다', rom:'eopda', vi:'không có, không tồn tại', pos:'tính từ'},

  /* ---------- Tính chất · cảm nhận ---------- */
  {ko:'신선하다', rom:'sinseonhada', vi:'tươi, tươi mới', pos:'tính từ', hanja:'新鮮—', hv:'tân tiên'},
  {ko:'싱싱하다', rom:'singsinghada', vi:'tươi rói (rau, cá)', pos:'tính từ'},
  {ko:'힘들다', rom:'himdeulda', vi:'vất vả, mệt', pos:'tính từ'},
  {ko:'흔하다', rom:'heunhada', vi:'phổ biến, thường gặp', pos:'tính từ'},
  {ko:'부족하다', rom:'bujokhada', vi:'thiếu, không đủ', pos:'tính từ', hanja:'不足—', hv:'bất túc'},
  {ko:'분명하다', rom:'bunmyeonghada', vi:'rõ ràng', pos:'tính từ', hanja:'分明—', hv:'phân minh'},
  {ko:'공평하다', rom:'gongpyeonghada', vi:'công bằng', pos:'tính từ', hanja:'公平—', hv:'công bình'},
  {ko:'어색하다', rom:'eosaekhada', vi:'gượng gạo, ngượng', pos:'tính từ', hanja:'語塞—', hv:'ngữ tắc'},
  {ko:'귀찮다', rom:'gwichanta', vi:'phiền, ngại', pos:'tính từ'},
  {ko:'아깝다', rom:'akkapda', vi:'tiếc, phí', pos:'tính từ'},
  {ko:'사소하다', rom:'sasohada', vi:'vặt vãnh, nhỏ nhặt', pos:'tính từ', hanja:'些少—', hv:'ta thiểu'},
  {ko:'가득하다', rom:'gadeukada', vi:'đầy ắp', pos:'tính từ'},
  {ko:'하얗다', rom:'hayata', vi:'trắng', pos:'tính từ'},
  {ko:'두려워하다', rom:'duryeowohada', vi:'sợ hãi, e sợ', pos:'động từ'},
  {ko:'상태', rom:'sangtae', vi:'tình trạng', pos:'danh từ', hanja:'狀態', hv:'trạng thái'},
  {ko:'분위기', rom:'bunwigi', vi:'không khí, bầu không khí', pos:'danh từ', hanja:'雰圍氣', hv:'phân vi khí'},
  {ko:'상대', rom:'sangdae', vi:'đối phương, người cùng', pos:'danh từ', hanja:'相對', hv:'tương đối'},
  {ko:'정', rom:'jeong', vi:'cái tình, sự gắn bó', pos:'danh từ', hanja:'情', hv:'tình'},
  {ko:'정상', rom:'jeongsang', vi:'đỉnh núi', pos:'danh từ', hanja:'頂上', hv:'đỉnh thượng'},
  {ko:'너머', rom:'neomeo', vi:'bên kia, phía sau', pos:'danh từ'},
  {ko:'그대로', rom:'geudaero', vi:'nguyên như vậy', pos:'trạng từ'},
  {ko:'남의 나라', rom:'namui nara', vi:'xứ người, nước người ta', pos:'cụm danh từ'},
  {ko:'삼분의 일', rom:'sambunui il', vi:'một phần ba', pos:'cụm số từ', hanja:'三分—一', hv:'tam phân chi nhất'},
  {ko:'절반', rom:'jeolban', vi:'một nửa', pos:'danh từ', hanja:'折半', hv:'chiết bán'},
  {ko:'대부분', rom:'daebubun', vi:'phần lớn', pos:'danh từ', hanja:'大部分', hv:'đại bộ phận'},
  {ko:'첫날', rom:'cheonnal', vi:'ngày đầu tiên', pos:'danh từ'},
  {ko:'하루 종일', rom:'haru jongil', vi:'cả ngày', pos:'cụm trạng từ', hanja:'—終日', hv:'chung nhật'},
  {ko:'사계절', rom:'sagyejeol', vi:'bốn mùa', pos:'danh từ', hanja:'四季節', hv:'tứ quý tiết'},
  {ko:'평소', rom:'pyeongso', vi:'ngày thường, lúc bình thường', pos:'danh từ', hanja:'平素', hv:'bình tố'},
  {ko:'한참', rom:'hancham', vi:'một hồi lâu', pos:'danh từ'},
  {ko:'직접', rom:'jikjeop', vi:'trực tiếp, tận tay', pos:'trạng từ', hanja:'直接', hv:'trực tiếp'},
  {ko:'미리', rom:'miri', vi:'trước, từ trước', pos:'trạng từ'},
  {ko:'훨씬', rom:'hwolssin', vi:'hơn hẳn, hơn nhiều', pos:'trạng từ'},
  {ko:'거의', rom:'geoui', vi:'hầu như', pos:'trạng từ'},
  {ko:'자꾸', rom:'jakku', vi:'cứ, liên tục', pos:'trạng từ'},
  {ko:'오히려', rom:'ohiryeo', vi:'ngược lại, trái lại', pos:'trạng từ'},
  {ko:'반대', rom:'bandae', vi:'ngược lại; sự phản đối', pos:'danh từ', hanja:'反對', hv:'phản đối'},
  {ko:'당연히', rom:'dangyeonhi', vi:'đương nhiên', pos:'trạng từ', hanja:'當然—', hv:'đương nhiên'},
  {ko:'여전히', rom:'yeojeonhi', vi:'vẫn còn, y như cũ', pos:'trạng từ', hanja:'如前—', hv:'như tiền'},
  {ko:'곧바로', rom:'gotbaro', vi:'ngay lập tức', pos:'trạng từ'},
  {ko:'자동으로', rom:'jadongeuro', vi:'tự động', pos:'trạng từ', hanja:'自動—', hv:'tự động'},
  {ko:'생각보다', rom:'saenggakboda', vi:'hơn tưởng tượng', pos:'cụm trạng từ'},
  {ko:'그 다음에', rom:'geu daeume', vi:'sau đó', pos:'cụm trạng từ'},
  {ko:'다 해서', rom:'da haeseo', vi:'tất cả là, cộng lại là', pos:'cụm trạng từ'},
  {ko:'아무것도', rom:'amugeotdo', vi:'không gì cả', pos:'đại từ'},
  {ko:'쯤', rom:'jjeum', vi:'khoảng, cỡ', pos:'phụ tố'},
  {ko:'잘 못 -', rom:'jal mot', vi:'không… giỏi, làm không nên', pos:'cụm trạng từ'},

  /* ---------- Đuôi câu · mẫu ngữ pháp trong bài đọc ---------- */
  {ko:'-째', rom:'-jjae', vi:'thứ… (đếm thứ tự thời gian)', pos:'phụ tố'},
  {ko:'-마다', rom:'-mada', vi:'mỗi, cứ mỗi', pos:'trợ từ'},
  {ko:'-쯤', rom:'-jjeum', vi:'khoảng, cỡ', pos:'phụ tố'},
  {ko:'-당', rom:'-dang', vi:'mỗi (đơn vị)', pos:'phụ tố', hanja:'當', hv:'đương'},
  {ko:'-이나', rom:'-ina', vi:'những (nhấn số lượng nhiều)', pos:'trợ từ'},
  {ko:'-동안', rom:'-dongan', vi:'trong suốt (khoảng thời gian)', pos:'danh từ phụ thuộc'},
  {ko:'-께서', rom:'-kkeseo', vi:'trợ từ chủ ngữ kính ngữ', pos:'trợ từ'},
  {ko:'-에 따라', rom:'-e ttara', vi:'tuỳ theo…', pos:'cụm ngữ pháp'},
  {ko:'-을/를 위한', rom:'-eul/reul wihan', vi:'dành cho…', pos:'cụm ngữ pháp'},
  {ko:'-에서 -까지', rom:'-eseo -kkaji', vi:'từ… đến…', pos:'cụm ngữ pháp'},
  {ko:'-에서 오다', rom:'-eseo oda', vi:'đến từ…', pos:'cụm ngữ pháp'},
  {ko:'-(으)로만', rom:'-(eu)roman', vi:'chỉ bằng…', pos:'cụm ngữ pháp'},
  {ko:'-밖에 안', rom:'-bakke an', vi:'chỉ… mà thôi', pos:'cụm ngữ pháp'},
  {ko:'-았/었-', rom:'-at/eot-', vi:'đuôi quá khứ', pos:'đuôi câu'},
  {ko:'-(으)셨습니다', rom:'-(eu)syeotseumnida', vi:'đuôi kính ngữ quá khứ', pos:'đuôi câu'},
  {ko:'-(으)면서', rom:'-(eu)myeonseo', vi:'vừa… vừa…', pos:'đuôi câu'},
  {ko:'-(으)면', rom:'-(eu)myeon', vi:'nếu…, khi…', pos:'đuôi câu'},
  {ko:'-(으)려고', rom:'-(eu)ryeogo', vi:'để mà (mục đích)', pos:'đuôi câu'},
  {ko:'-(으)려다가', rom:'-(eu)ryeodaga', vi:'định… rồi lại…', pos:'đuôi câu'},
  {ko:'-기 전에', rom:'-gi jeone', vi:'trước khi…', pos:'cụm ngữ pháp'},
  {ko:'-(으)ㄴ 후에', rom:'-(eu)n hue', vi:'sau khi…', pos:'cụm ngữ pháp'},
  {ko:'-고 나니까', rom:'-go nanikka', vi:'sau khi… thì…', pos:'cụm ngữ pháp'},
  {ko:'-았/었더니', rom:'-at/eotdeoni', vi:'làm… thì kết quả là…', pos:'cụm ngữ pháp'},
  {ko:'-기 때문에', rom:'-gi ttaemune', vi:'bởi vì…', pos:'cụm ngữ pháp'},
  {ko:'-기로 하다', rom:'-giro hada', vi:'quyết định làm…', pos:'cụm ngữ pháp'},
  {ko:'-고 싶다', rom:'-go sipda', vi:'muốn…', pos:'cụm ngữ pháp'},
  {ko:'-아/어야 하다', rom:'-a/eoya hada', vi:'phải…', pos:'cụm ngữ pháp'},
  {ko:'-아/어야', rom:'-a/eoya', vi:'phải… thì mới…', pos:'đuôi câu'},
  {ko:'-아/어지다', rom:'-a/eojida', vi:'trở nên…', pos:'cụm ngữ pháp'},
  {ko:'-아/어도 되다', rom:'-a/eodo doeda', vi:'được phép…', pos:'cụm ngữ pháp'},
  {ko:'-아/어 주세요', rom:'-a/eo juseyo', vi:'làm ơn… giúp tôi', pos:'cụm ngữ pháp'},
  {ko:'-아/어 주다', rom:'-a/eo juda', vi:'làm giúp cho ai', pos:'cụm ngữ pháp'},
  {ko:'-아/어 드리다', rom:'-a/eo deurida', vi:'làm cho (kính ngữ)', pos:'cụm ngữ pháp'},
  {ko:'-아/어 두다', rom:'-a/eo duda', vi:'làm sẵn, để sẵn', pos:'cụm ngữ pháp'},
  {ko:'-(으)면 되다', rom:'-(eu)myeon doeda', vi:'chỉ cần… là được', pos:'cụm ngữ pháp'},
  {ko:'-(으)ㄹ 수 있다', rom:'-(eu)l su itda', vi:'có thể…', pos:'cụm ngữ pháp'},
  {ko:'-(으)ㄹ 수 없다', rom:'-(eu)l su eopda', vi:'không thể…', pos:'cụm ngữ pháp'},
  {ko:'-(으)ㄹ 거예요', rom:'-(eu)l geoyeyo', vi:'sẽ… (dự định, phỏng đoán)', pos:'cụm ngữ pháp'},
  {ko:'-(으)ㄹ까 봐', rom:'-(eu)lkka bwa', vi:'sợ rằng…', pos:'cụm ngữ pháp'},
  {ko:'-(으)ㄹ까요?', rom:'-(eu)lkkayo', vi:'…nhé? (rủ rê, hỏi ý)', pos:'đuôi câu'},
  {ko:'-(으)ㄹ 것 같다', rom:'-(eu)l geot gatda', vi:'chắc là…, có vẻ…', pos:'cụm ngữ pháp'},
  {ko:'-(으)ㄹ 만큼', rom:'-(eu)l mankeum', vi:'đến mức…', pos:'cụm ngữ pháp'},
  {ko:'-(으)ㄹ 만하다', rom:'-(eu)l manhada', vi:'đáng để…', pos:'cụm ngữ pháp'},
  {ko:'-(으)ㄹ지도 모르다', rom:'-(eu)ljido moreuda', vi:'có lẽ…, biết đâu…', pos:'cụm ngữ pháp'},
  {ko:'-(으)ㄹ 때마다', rom:'-(eu)l ttaemada', vi:'mỗi lần…', pos:'cụm ngữ pháp'},
  {ko:'-(으)ㄹ 일', rom:'-(eu)l il', vi:'việc mà… (sẽ/có thể)', pos:'cụm ngữ pháp'},
  {ko:'-(으)ㄴ 적이 없다', rom:'-(eu)n jeogi eopda', vi:'chưa từng…', pos:'cụm ngữ pháp'},
  {ko:'-(으)ㄴ 지 …이/가 되다', rom:'-(eu)n ji … i/ga doeda', vi:'đã được bao lâu kể từ khi…', pos:'cụm ngữ pháp'},
  {ko:'-(으)ㄴ 지 -만에', rom:'-(eu)n ji -mane', vi:'sau khi… được đúng…', pos:'cụm ngữ pháp'},
  {ko:'-(으)ㄴ 대신', rom:'-(eu)n daesin', vi:'bù lại, đổi lấy', pos:'cụm ngữ pháp'},
  {ko:'-(으)ㄴ 것 중에서', rom:'-(eu)n geot jungeseo', vi:'trong số những cái đã…', pos:'cụm ngữ pháp'},
  {ko:'-(으)라는 뜻', rom:'-(eu)raneun tteut', vi:'mang ý nghĩa là hãy…', pos:'cụm ngữ pháp'},
  {ko:'-는 법', rom:'-neun beop', vi:'cách làm…', pos:'cụm ngữ pháp'},
  {ko:'-는 편이 낫다', rom:'-neun pyeoni natda', vi:'thà… thì hơn', pos:'cụm ngữ pháp'},
  {ko:'-다고 하다', rom:'-dago hada', vi:'nghe nói rằng…', pos:'cụm ngữ pháp'},
  {ko:'-지 마세요', rom:'-ji maseyo', vi:'xin đừng…', pos:'cụm ngữ pháp'},
  {ko:'-이/가 아니라', rom:'-i/ga anira', vi:'không phải… mà là…', pos:'cụm ngữ pháp'},

  /* ============================================================
     TỪ TRONG THÂN BÀI ĐỌC
     Trong bài đọc mỗi từ đều bấm tra được, nên cả những từ nền tảng
     nhất (있다, 것, 수, 때, 더…) cũng phải có mục.
     ============================================================ */

  /* ---------- Vị từ nền tảng ---------- */
  {ko:'있다', rom:'itda', vi:'có; ở, tồn tại', pos:'tính từ'},
  {ko:'않다', rom:'anta', vi:'không (phủ định đứng sau -지)', pos:'động từ'},
  {ko:'싶다', rom:'sipda', vi:'muốn (dùng với -고 싶다)', pos:'tính từ'},
  {ko:'아니다', rom:'anida', vi:'không phải là', pos:'tính từ'},
  {ko:'나다', rom:'nada', vi:'ra, nảy sinh (열이 나다, 눈물이 나다)', pos:'động từ'},
  {ko:'넘다', rom:'neomda', vi:'vượt quá, trèo qua', pos:'động từ'},
  {ko:'넓다', rom:'neopda', vi:'rộng', pos:'tính từ'},
  {ko:'두다', rom:'duda', vi:'đặt, để', pos:'động từ'},
  {ko:'끝내다', rom:'kkeutnaeda', vi:'kết thúc, làm cho xong', pos:'động từ'},
  {ko:'생기다', rom:'saenggida', vi:'nảy sinh, xuất hiện; trông như', pos:'động từ'},
  {ko:'좋아지다', rom:'joajida', vi:'tốt lên, đỡ hơn', pos:'động từ'},
  {ko:'작아지다', rom:'jagajida', vi:'nhỏ đi', pos:'động từ'},
  {ko:'들어오다', rom:'deureooda', vi:'đi vào, lọt vào', pos:'động từ'},
  {ko:'도와주다', rom:'dowajuda', vi:'giúp đỡ', pos:'động từ'},
  {ko:'알리다', rom:'allida', vi:'báo cho biết', pos:'động từ'},
  {ko:'부르다', rom:'bureuda', vi:'gọi; hát', pos:'động từ'},
  {ko:'드시다', rom:'deusida', vi:'dùng bữa, ăn (kính ngữ)', pos:'động từ'},
  {ko:'운영하다', rom:'unyeonghada', vi:'vận hành, điều hành', pos:'động từ', hanja:'運營—', hv:'vận doanh'},
  {ko:'포장되다', rom:'pojangdoeda', vi:'được đóng gói', pos:'động từ', hanja:'包裝—', hv:'bao trang'},
  {ko:'설계되다', rom:'seolgyedoeda', vi:'được thiết kế', pos:'động từ', hanja:'設計—', hv:'thiết kế'},
  {ko:'이상하다', rom:'isanghada', vi:'kỳ lạ, khác thường', pos:'tính từ', hanja:'異常—', hv:'dị thường'},

  /* ---------- Danh từ phụ thuộc · đại từ ---------- */
  {ko:'것', rom:'geot', vi:'cái, việc, điều', pos:'danh từ phụ thuộc'},
  {ko:'게', rom:'ge', vi:'cái mà… (rút gọn của 것이)', pos:'danh từ phụ thuộc'},
  {ko:'걸', rom:'geol', vi:'cái mà… (rút gọn của 것을)', pos:'danh từ phụ thuộc'},
  {ko:'수', rom:'su', vi:'khả năng (dùng trong -(으)ㄹ 수 있다/없다)', pos:'danh từ phụ thuộc'},
  {ko:'때', rom:'ttae', vi:'lúc, khi', pos:'danh từ phụ thuộc'},
  {ko:'점', rom:'jeom', vi:'điểm, khía cạnh', pos:'danh từ', hanja:'點', hv:'điểm'},
  {ko:'그', rom:'geu', vi:'đó, ấy (chỉ định)', pos:'đại từ chỉ định'},
  {ko:'이런', rom:'ireon', vi:'thế này, như thế này', pos:'đại từ chỉ định'},
  {ko:'뭔가', rom:'mwonga', vi:'cái gì đó', pos:'đại từ'},
  {ko:'이렇게', rom:'ireoke', vi:'như thế này', pos:'trạng từ'},

  /* ---------- Trạng từ hay gặp ---------- */
  {ko:'더', rom:'deo', vi:'hơn, thêm', pos:'trạng từ'},
  {ko:'제일', rom:'jeil', vi:'nhất', pos:'trạng từ', hanja:'第一', hv:'đệ nhất'},
  {ko:'가장', rom:'gajang', vi:'nhất (trang trọng hơn 제일)', pos:'trạng từ'},
  {ko:'이제', rom:'ije', vi:'bây giờ, từ giờ', pos:'trạng từ'},
  {ko:'함께', rom:'hamkke', vi:'cùng nhau', pos:'trạng từ'},
  {ko:'다만', rom:'daman', vi:'chỉ có điều', pos:'liên từ'},
  {ko:'갑자기', rom:'gapjagi', vi:'đột nhiên', pos:'trạng từ'},
  {ko:'가까이', rom:'gakkai', vi:'gần, ở gần', pos:'trạng từ'},
  {ko:'꼭', rom:'kkok', vi:'nhất định, chắc chắn', pos:'trạng từ'},
  {ko:'깜짝', rom:'kkamjjak', vi:'giật nảy (깜짝 놀라다)', pos:'trạng từ'},
  {ko:'대신', rom:'daesin', vi:'thay vì, thay cho', pos:'danh từ', hanja:'代身', hv:'đại thân'},
  {ko:'결국', rom:'gyeolguk', vi:'cuối cùng thì', pos:'trạng từ', hanja:'結局', hv:'kết cục'},
  {ko:'동안', rom:'dongan', vi:'trong khoảng (thời gian)', pos:'danh từ'},
  {ko:'다', rom:'da', vi:'tất cả, hết', pos:'trạng từ'},
  {ko:'혼자서도', rom:'honjaseodo', vi:'ngay cả khi một mình', pos:'cụm trạng từ'},

  /* ---------- Số đếm ---------- */
  {ko:'둘', rom:'dul', vi:'hai (số đếm thuần Hàn)', pos:'số từ'},
  {ko:'두', rom:'du', vi:'hai (đứng trước danh từ)', pos:'số từ'},
  {ko:'세', rom:'se', vi:'ba (đứng trước danh từ)', pos:'số từ'},
  {ko:'네', rom:'ne', vi:'bốn (đứng trước danh từ); vâng', pos:'số từ'},
  {ko:'다섯', rom:'daseot', vi:'năm (số đếm thuần Hàn)', pos:'số từ'},
  {ko:'여섯', rom:'yeoseot', vi:'sáu (số đếm thuần Hàn)', pos:'số từ'},
  {ko:'일곱', rom:'ilgop', vi:'bảy (số đếm thuần Hàn)', pos:'số từ'},
  {ko:'여덟', rom:'yeodeol', vi:'tám (số đếm thuần Hàn)', pos:'số từ'},
  {ko:'첫', rom:'cheot', vi:'đầu tiên (첫 번째)', pos:'số thứ tự'},
  {ko:'번째', rom:'beonjjae', vi:'thứ… (đếm thứ tự)', pos:'danh từ phụ thuộc', hanja:'番—', hv:'phiên'},
  {ko:'오', rom:'o', vi:'năm (số Hán–Hàn)', pos:'số từ', hanja:'五', hv:'ngũ'},
  {ko:'십오', rom:'sibo', vi:'mười lăm', pos:'số từ', hanja:'十五', hv:'thập ngũ'},
  {ko:'삼십', rom:'samsip', vi:'ba mươi', pos:'số từ', hanja:'三十', hv:'tam thập'},
  {ko:'이백', rom:'ibaek', vi:'hai trăm', pos:'số từ', hanja:'二百', hv:'nhị bách'},
  {ko:'삼천', rom:'samcheon', vi:'ba nghìn', pos:'số từ', hanja:'三千', hv:'tam thiên'},
  {ko:'이틀', rom:'iteul', vi:'hai ngày', pos:'danh từ'},
  {ko:'사흘', rom:'saheul', vi:'ba ngày', pos:'danh từ'},

  /* ---------- Đơn vị đếm ---------- */
  {ko:'끼', rom:'kki', vi:'bữa (đếm bữa ăn)', pos:'đơn vị'},
  {ko:'층', rom:'cheung', vi:'tầng', pos:'đơn vị', hanja:'層', hv:'tầng'},

  /* ---------- Danh từ đời sống ---------- */
  {ko:'근처', rom:'geuncheo', vi:'gần đây, vùng lân cận', pos:'danh từ', hanja:'近處', hv:'cận xứ'},
  {ko:'마트', rom:'mateu', vi:'siêu thị', pos:'danh từ'},
  {ko:'커피숍', rom:'keopisyop', vi:'quán cà phê', pos:'danh từ'},
  {ko:'단어', rom:'daneo', vi:'từ vựng, từ', pos:'danh từ', hanja:'單語', hv:'đơn ngữ'},
  {ko:'눈물', rom:'nunmul', vi:'nước mắt', pos:'danh từ'},
  {ko:'남동생', rom:'namdongsaeng', vi:'em trai', pos:'danh từ', hanja:'男—', hv:'nam'},
  {ko:'집주인', rom:'jipjuin', vi:'chủ nhà', pos:'danh từ', hanja:'—主人', hv:'chủ nhân'},
  {ko:'사장님', rom:'sajangnim', vi:'giám đốc, ông/bà chủ', pos:'danh từ', hanja:'社長—', hv:'xã trưởng'},
  {ko:'운동장', rom:'undongjang', vi:'sân vận động, sân trường', pos:'danh từ', hanja:'運動場', hv:'vận động trường'},
  {ko:'시청', rom:'sicheong', vi:'toà thị chính', pos:'danh từ', hanja:'市廳', hv:'thị sảnh'},
  {ko:'주택', rom:'jutaek', vi:'nhà ở, nhà riêng', pos:'danh từ', hanja:'住宅', hv:'trú trạch'},
  {ko:'의료', rom:'uiryo', vi:'y tế', pos:'danh từ', hanja:'醫療', hv:'y liệu'},
  {ko:'가구', rom:'gagu', vi:'hộ gia đình; đồ nội thất', pos:'danh từ', hanja:'家口 / 家具', hv:'gia khẩu / gia cụ'},
  {ko:'전체', rom:'jeonche', vi:'toàn bộ', pos:'danh từ', hanja:'全體', hv:'toàn thể'},
  {ko:'상품', rom:'sangpum', vi:'sản phẩm, mặt hàng', pos:'danh từ', hanja:'商品', hv:'thương phẩm'},
  {ko:'위기', rom:'wigi', vi:'khủng hoảng, lúc nguy cấp', pos:'danh từ', hanja:'危機', hv:'nguy cơ'},
  {ko:'서비스', rom:'seobiseu', vi:'dịch vụ', pos:'danh từ'},
  {ko:'형태', rom:'hyeongtae', vi:'hình thái, dạng', pos:'danh từ', hanja:'形態', hv:'hình thái'},
  {ko:'분량', rom:'bullyang', vi:'khẩu phần, lượng', pos:'danh từ', hanja:'分量', hv:'phân lượng'},
  {ko:'가전제품', rom:'gajeonjepum', vi:'đồ điện gia dụng', pos:'danh từ', hanja:'家電製品', hv:'gia điện chế phẩm'},
  {ko:'반대쪽', rom:'bandaejjok', vi:'phía đối diện', pos:'danh từ', hanja:'反對—', hv:'phản đối'},
  {ko:'혼밥', rom:'honbap', vi:'ăn cơm một mình', pos:'danh từ', note:'혼자 + 밥 — từ mới của giới trẻ'},
  {ko:'혼술', rom:'honsul', vi:'uống rượu một mình', pos:'danh từ', note:'혼자 + 술'},
  {ko:'삼각김밥', rom:'samgak gimbap', vi:'cơm nắm tam giác', pos:'danh từ', hanja:'三角—', hv:'tam giác'},
  {ko:'김치찌개', rom:'gimchi jjigae', vi:'canh kimchi', pos:'danh từ'},
  {ko:'아메리카노', rom:'amerikano', vi:'cà phê americano', pos:'danh từ'},
  {ko:'라테', rom:'rate', vi:'cà phê latte', pos:'danh từ'},
  {ko:'아이스', rom:'aiseu', vi:'đá, lạnh (아이스 아메리카노)', pos:'danh từ'},
  {ko:'볼펜', rom:'bolpen', vi:'bút bi', pos:'danh từ'},

  /* ---------- Tên riêng trong bài ---------- */
  {ko:'하노이', rom:'Hanoi', vi:'Hà Nội', pos:'tên riêng'},
  {ko:'한강', rom:'Hangang', vi:'sông Hàn (Seoul)', pos:'tên riêng', hanja:'漢江', hv:'Hán giang'},
  {ko:'민수', rom:'Minsu', vi:'Min-su (tên nam phổ biến)', pos:'tên riêng'},
  {ko:'북한산', rom:'Bukhansan', vi:'núi Bukhan (Seoul)', pos:'tên riêng', hanja:'北漢山', hv:'Bắc Hán sơn'},
  {ko:'부산', rom:'Busan', vi:'Busan', pos:'tên riêng', hanja:'釜山', hv:'Phủ Sơn'},
  {ko:'구름', rom:'gureum', vi:'đám mây; tên con mèo trong bài đọc', pos:'danh từ'},

  /* ---------- Bổ sung đợt 2: từ còn lại trong thân bài đọc ---------- */

  /* Danh từ */
  {ko:'건물', rom:'geonmul', vi:'toà nhà', pos:'danh từ', hanja:'建物', hv:'kiến vật'},
  {ko:'가운데', rom:'gaunde', vi:'ở giữa; trong số', pos:'danh từ'},
  {ko:'노트북', rom:'noteubuk', vi:'máy tính xách tay', pos:'danh từ'},
  {ko:'룸메이트', rom:'rummeiteu', vi:'bạn cùng phòng', pos:'danh từ'},
  {ko:'미용실', rom:'miyongsil', vi:'tiệm làm tóc', pos:'danh từ', hanja:'美容室', hv:'mỹ dung thất'},
  {ko:'한식당', rom:'hansikdang', vi:'quán ăn Hàn', pos:'danh từ', hanja:'韓食堂', hv:'Hàn thực đường'},
  {ko:'지하철역', rom:'jihacheollyeok', vi:'ga tàu điện ngầm', pos:'danh từ', hanja:'地下鐵驛', hv:'địa hạ thiết dịch'},
  {ko:'아파트', rom:'apateu', vi:'chung cư, căn hộ', pos:'danh từ'},
  {ko:'옆집', rom:'yeopjip', vi:'nhà bên cạnh', pos:'danh từ'},
  {ko:'센터', rom:'senteo', vi:'trung tâm', pos:'danh từ'},
  {ko:'점심시간', rom:'jeomsimsigan', vi:'giờ nghỉ trưa', pos:'danh từ', hanja:'點心時間', hv:'điểm tâm thời gian'},
  {ko:'일주일', rom:'iljuil', vi:'một tuần', pos:'danh từ', hanja:'一週日', hv:'nhất chu nhật'},
  {ko:'반년', rom:'bannyeon', vi:'nửa năm', pos:'danh từ', hanja:'半年', hv:'bán niên'},
  {ko:'기간', rom:'gigan', vi:'thời gian, kỳ hạn', pos:'danh từ', hanja:'期間', hv:'kỳ gian'},
  {ko:'마지막', rom:'majimak', vi:'cuối cùng', pos:'danh từ'},
  {ko:'다음', rom:'daeum', vi:'tiếp theo, lần sau', pos:'danh từ'},
  {ko:'이번', rom:'ibeon', vi:'lần này', pos:'danh từ', hanja:'—番', hv:'phiên'},
  {ko:'지난', rom:'jinan', vi:'vừa qua, trước (지난주)', pos:'định từ'},
  {ko:'전', rom:'jeon', vi:'trước (시간); toàn bộ', pos:'danh từ', hanja:'前', hv:'tiền'},
  {ko:'후', rom:'hu', vi:'sau (시간)', pos:'danh từ', hanja:'後', hv:'hậu'},
  {ko:'중', rom:'jung', vi:'trong, giữa; đang', pos:'danh từ', hanja:'中', hv:'trung'},
  {ko:'적', rom:'jeok', vi:'lần, kinh nghiệm (-(으)ㄴ 적이 있다)', pos:'danh từ phụ thuộc'},
  {ko:'지', rom:'ji', vi:'kể từ khi (-(으)ㄴ 지)', pos:'danh từ phụ thuộc'},
  {ko:'편', rom:'pyeon', vi:'phía, bên; xu hướng (-는 편이다)', pos:'danh từ phụ thuộc', hanja:'便', hv:'tiện'},
  {ko:'만', rom:'man', vi:'vạn (10 000); sau đúng… (지 일주일 만에)', pos:'danh từ', hanja:'萬', hv:'vạn'},
  {ko:'제', rom:'je', vi:'của tôi (khiêm nhường, rút gọn 저의)', pos:'đại từ'},
  {ko:'저희', rom:'jeohui', vi:'chúng tôi (khiêm nhường)', pos:'đại từ'},
  {ko:'자기', rom:'jagi', vi:'bản thân mình', pos:'đại từ', hanja:'自己', hv:'tự kỷ'},
  {ko:'누구', rom:'nugu', vi:'ai', pos:'đại từ nghi vấn'},
  {ko:'누군가', rom:'nugunga', vi:'ai đó', pos:'đại từ'},
  {ko:'무슨', rom:'museun', vi:'cái gì, loại nào', pos:'định từ nghi vấn'},
  {ko:'어떤', rom:'eotteon', vi:'nào đó, thế nào', pos:'định từ'},
  {ko:'어느', rom:'eoneu', vi:'nào (trong số)', pos:'định từ'},
  {ko:'아무', rom:'amu', vi:'bất kỳ ai/cái gì', pos:'định từ'},
  {ko:'하나', rom:'hana', vi:'một (số đếm thuần Hàn)', pos:'số từ'},
  {ko:'아홉', rom:'ahop', vi:'chín (số đếm thuần Hàn)', pos:'số từ'},
  {ko:'십', rom:'sip', vi:'mười (số Hán–Hàn)', pos:'số từ', hanja:'十', hv:'thập'},
  {ko:'삼분', rom:'sambun', vi:'ba phần (삼분의 일: một phần ba)', pos:'danh từ', hanja:'三分', hv:'tam phân'},
  {ko:'군데', rom:'gunde', vi:'nơi, chỗ (đếm địa điểm)', pos:'đơn vị'},
  {ko:'통', rom:'tong', vi:'thùng; bức (đếm thư, điện thoại)', pos:'đơn vị'},
  {ko:'칸', rom:'kan', vi:'ô, ngăn, khoang', pos:'danh từ'},
  {ko:'뜻', rom:'tteut', vi:'nghĩa, ý nghĩa', pos:'danh từ'},
  {ko:'소리', rom:'sori', vi:'tiếng, âm thanh', pos:'danh từ'},
  {ko:'모양', rom:'moyang', vi:'hình dáng', pos:'danh từ', hanja:'模樣', hv:'mô dạng'},
  {ko:'문법', rom:'munbeop', vi:'ngữ pháp', pos:'danh từ', hanja:'文法', hv:'văn pháp'},
  {ko:'문장', rom:'munjang', vi:'câu văn', pos:'danh từ', hanja:'文章', hv:'văn chương'},
  {ko:'한국어', rom:'hangugeo', vi:'tiếng Hàn', pos:'danh từ', hanja:'韓國語', hv:'Hàn quốc ngữ'},
  {ko:'인기', rom:'ingi', vi:'sự được yêu thích', pos:'danh từ', hanja:'人氣', hv:'nhân khí'},
  {ko:'영상', rom:'yeongsang', vi:'hình ảnh, video', pos:'danh từ', hanja:'映像', hv:'ánh tượng'},
  {ko:'채팅', rom:'chaeting', vi:'nhắn tin trò chuyện', pos:'danh từ'},
  {ko:'앱', rom:'aep', vi:'ứng dụng (app)', pos:'danh từ'},
  {ko:'화', rom:'hwa', vi:'cơn giận', pos:'danh từ', hanja:'火', hv:'hoả'},
  {ko:'힘', rom:'him', vi:'sức lực', pos:'danh từ'},
  {ko:'숨', rom:'sum', vi:'hơi thở', pos:'danh từ'},
  {ko:'햇빛', rom:'haetbit', vi:'ánh nắng', pos:'danh từ'},
  {ko:'파란색', rom:'paransaek', vi:'màu xanh dương', pos:'danh từ', hanja:'—色', hv:'sắc'},
  {ko:'새것', rom:'saegeot', vi:'đồ mới', pos:'danh từ'},
  {ko:'주문', rom:'jumun', vi:'đơn hàng, việc gọi món', pos:'danh từ', hanja:'注文', hv:'chú văn'},
  {ko:'필요', rom:'piryo', vi:'sự cần thiết', pos:'danh từ', hanja:'必要', hv:'tất yếu'},
  {ko:'편리함', rom:'pyeollinam', vi:'sự tiện lợi', pos:'danh từ', hanja:'便利—', hv:'tiện lợi'},
  {ko:'택시비', rom:'taeksibi', vi:'tiền taxi', pos:'danh từ', hanja:'—費', hv:'phí'},
  {ko:'책상값', rom:'chaeksanggap', vi:'tiền cái bàn học', pos:'danh từ', hanja:'冊床—', hv:'sách sàng'},
  {ko:'별로', rom:'byeollo', vi:'không mấy, chẳng lấy gì làm', pos:'trạng từ', hanja:'別—', hv:'biệt'},
  {ko:'곧', rom:'got', vi:'ngay, sắp', pos:'trạng từ'},
  {ko:'그냥', rom:'geunyang', vi:'cứ thế, chỉ đơn giản là', pos:'trạng từ'},
  {ko:'오래', rom:'orae', vi:'lâu', pos:'trạng từ'},
  {ko:'못', rom:'mot', vi:'không thể (phủ định năng lực)', pos:'trạng từ'},
  {ko:'딱', rom:'ttak', vi:'vừa khít, đúng y', pos:'trạng từ'},
  {ko:'따라', rom:'ttara', vi:'theo (-에 따라)', pos:'trạng từ'},
  {ko:'그래', rom:'geurae', vi:'ừ, thế à', pos:'thán từ'},
  {ko:'아니라', rom:'anira', vi:'không phải… (mà là)', pos:'cụm ngữ pháp'},

  /* Đồ ăn · vật liệu */
  {ko:'김', rom:'gim', vi:'rong biển khô', pos:'danh từ'},
  {ko:'참기름', rom:'chamgireum', vi:'dầu vừng', pos:'danh từ'},
  {ko:'당근', rom:'danggeun', vi:'cà rốt', pos:'danh từ'},
  {ko:'햄', rom:'haem', vi:'thịt nguội, giăm bông', pos:'danh từ'},
  {ko:'과자', rom:'gwaja', vi:'bánh kẹo, đồ ăn vặt', pos:'danh từ', hanja:'菓子', hv:'quả tử'},
  {ko:'술', rom:'sul', vi:'rượu', pos:'danh từ'},
  {ko:'치킨', rom:'chikin', vi:'gà rán', pos:'danh từ'},
  {ko:'쌀국수', rom:'ssalguksu', vi:'phở, bún gạo', pos:'danh từ'},
  {ko:'사이다', rom:'saida', vi:'nước ngọt có ga vị chanh', pos:'danh từ'},
  {ko:'테이프', rom:'teipeu', vi:'băng dính', pos:'danh từ'},
  {ko:'플라스틱', rom:'peullaseutik', vi:'nhựa', pos:'danh từ'},
  {ko:'유리병', rom:'yuribyeong', vi:'chai thuỷ tinh', pos:'danh từ', hanja:'琉璃甁', hv:'lưu ly bình'},
  {ko:'배편', rom:'baepyeon', vi:'đường biển (gửi hàng)', pos:'danh từ', hanja:'—便', hv:'tiện'},
  {ko:'드라마', rom:'deurama', vi:'phim truyền hình', pos:'danh từ'},
  {ko:'면접관', rom:'myeonjeopgwan', vi:'người phỏng vấn', pos:'danh từ', hanja:'面接官', hv:'diện tiếp quan'},
  {ko:'세계', rom:'segye', vi:'thế giới', pos:'danh từ', hanja:'世界', hv:'thế giới'},
  {ko:'중국', rom:'jungguk', vi:'Trung Quốc', pos:'tên riêng', hanja:'中國', hv:'Trung quốc'},
  {ko:'몽골', rom:'monggol', vi:'Mông Cổ', pos:'tên riêng'},
  {ko:'설', rom:'seol', vi:'Tết Nguyên đán (Hàn Quốc)', pos:'danh từ'},
  {ko:'어린아이', rom:'eorinai', vi:'trẻ nhỏ', pos:'danh từ'},
  {ko:'남', rom:'nam', vi:'người khác, người dưng', pos:'danh từ'},
  {ko:'이야기', rom:'iyagi', vi:'câu chuyện', pos:'danh từ'},

  /* Động từ · tính từ */
  {ko:'이야기하다', rom:'iyagihada', vi:'nói chuyện, kể chuyện', pos:'động từ'},
  {ko:'물어보다', rom:'mureoboda', vi:'hỏi thử', pos:'động từ'},
  {ko:'알아듣다', rom:'aradeutda', vi:'nghe hiểu', pos:'động từ'},
  {ko:'걸어가다', rom:'georeogada', vi:'đi bộ đến', pos:'động từ'},
  {ko:'돌아다니다', rom:'doradanida', vi:'đi lòng vòng, đi khắp nơi', pos:'động từ'},
  {ko:'나오다', rom:'naoda', vi:'đi ra, xuất hiện', pos:'động từ'},
  {ko:'들리다', rom:'deullida', vi:'nghe thấy (tự nhiên)', pos:'động từ'},
  {ko:'보이다', rom:'boida', vi:'nhìn thấy; cho xem', pos:'động từ'},
  {ko:'넣다', rom:'neota', vi:'bỏ vào, cho vào', pos:'động từ'},
  {ko:'놓다', rom:'nota', vi:'đặt xuống, để', pos:'động từ'},
  {ko:'남기다', rom:'namgida', vi:'để lại', pos:'động từ'},
  {ko:'남다', rom:'namda', vi:'còn lại', pos:'động từ'},
  {ko:'맡기다', rom:'matgida', vi:'gửi lại, giao cho giữ', pos:'động từ'},
  {ko:'버리다', rom:'beorida', vi:'vứt bỏ', pos:'động từ'},
  {ko:'보내다', rom:'bonaeda', vi:'gửi; trải qua (thời gian)', pos:'động từ'},
  {ko:'바뀌다', rom:'bakkwida', vi:'bị đổi, thay đổi', pos:'động từ'},
  {ko:'변하다', rom:'byeonhada', vi:'biến đổi', pos:'động từ', hanja:'變—', hv:'biến'},
  {ko:'사라지다', rom:'sarajida', vi:'biến mất', pos:'động từ'},
  {ko:'줄다', rom:'julda', vi:'giảm đi', pos:'động từ'},
  {ko:'지나다', rom:'jinada', vi:'trôi qua, đi qua', pos:'động từ'},
  {ko:'뽑다', rom:'ppopda', vi:'rút ra, chọn ra', pos:'động từ'},
  {ko:'누르다', rom:'nureuda', vi:'bấm, ấn', pos:'động từ'},
  {ko:'비우다', rom:'biuda', vi:'làm trống, bỏ trống', pos:'động từ'},
  {ko:'비키다', rom:'bikida', vi:'tránh ra, dịch ra', pos:'động từ'},
  {ko:'끓이다', rom:'kkeurida', vi:'đun, nấu sôi', pos:'động từ'},
  {ko:'앉다', rom:'anta', vi:'ngồi', pos:'động từ'},
  {ko:'입다', rom:'ipda', vi:'mặc', pos:'động từ'},
  {ko:'웃다', rom:'utda', vi:'cười', pos:'động từ'},
  {ko:'붙다', rom:'butda', vi:'dính vào; đỗ (kỳ thi)', pos:'động từ'},
  {ko:'자르다', rom:'jareuda', vi:'cắt, chặt', pos:'động từ'},
  {ko:'틀리다', rom:'teullida', vi:'sai, nhầm', pos:'động từ'},
  {ko:'모으다', rom:'moeuda', vi:'thu góp, dành dụm', pos:'động từ'},
  {ko:'예매하다', rom:'yemaehada', vi:'đặt vé trước', pos:'động từ', hanja:'豫買—', hv:'dự mại'},
  {ko:'연락하다', rom:'yeollakhada', vi:'liên lạc', pos:'động từ', hanja:'連絡—', hv:'liên lạc'},
  {ko:'설명하다', rom:'seolmyeonghada', vi:'giải thích', pos:'động từ', hanja:'說明—', hv:'thuyết minh'},
  {ko:'생각하다', rom:'saenggakhada', vi:'nghĩ', pos:'động từ'},
  {ko:'거절하다', rom:'geojeolhada', vi:'từ chối', pos:'động từ', hanja:'拒絕—', hv:'cự tuyệt'},
  {ko:'위하다', rom:'wihada', vi:'vì, dành cho (-을/를 위하다)', pos:'động từ', hanja:'爲—', hv:'vị'},
  {ko:'어울리다', rom:'eoullida', vi:'hợp, hoà hợp', pos:'động từ'},
  {ko:'어색해지다', rom:'eosaekhaejida', vi:'trở nên gượng gạo', pos:'động từ'},
  {ko:'가까워지다', rom:'gakkawojida', vi:'gần lại, thân hơn', pos:'động từ'},
  {ko:'가벼워지다', rom:'gabyeowojida', vi:'nhẹ đi', pos:'động từ'},
  {ko:'짧아지다', rom:'jjalbajida', vi:'ngắn đi', pos:'động từ'},
  {ko:'공평해지다', rom:'gongpyeonghaejida', vi:'trở nên công bằng', pos:'động từ', hanja:'公平—', hv:'công bình'},
  {ko:'얇다', rom:'yalda', vi:'mỏng', pos:'tính từ'},
  {ko:'젊다', rom:'jeomda', vi:'trẻ', pos:'tính từ'},
  {ko:'낯설다', rom:'natseolda', vi:'lạ lẫm, không quen', pos:'tính từ'},
  {ko:'친하다', rom:'chinhada', vi:'thân thiết', pos:'tính từ', hanja:'親—', hv:'thân'},

  /* ---------- Bổ sung cho bài tập nghe – xem tranh ---------- */
  /* Đồ vật trong nhà */
  {ko:'소파', rom:'sopa', vi:'ghế sofa', pos:'danh từ'},
  {ko:'탁자', rom:'takja', vi:'cái bàn (bàn thấp, bàn trà)', pos:'danh từ', hanja:'卓子', hv:'trác tử'},
  {ko:'외투', rom:'oetu', vi:'áo khoác ngoài', pos:'danh từ', hanja:'外套', hv:'ngoại sáo'},
  {ko:'화분', rom:'hwabun', vi:'chậu cây cảnh', pos:'danh từ', hanja:'花盆', hv:'hoa bồn'},
  {ko:'주전자', rom:'jujeonja', vi:'cái ấm (đun, rót nước)', pos:'danh từ', hanja:'酒煎子', hv:'tửu tiễn tử'},
  {ko:'책장', rom:'chaekjang', vi:'kệ sách, giá sách', pos:'danh từ', hanja:'冊欌', hv:'sách tráp'},
  {ko:'사다리', rom:'sadari', vi:'cái thang', pos:'danh từ'},
  {ko:'표지판', rom:'pyojipan', vi:'biển báo, biển chỉ đường', pos:'danh từ', hanja:'標識板', hv:'tiêu chí bản'},
  {ko:'글씨', rom:'geulssi', vi:'chữ viết, nét chữ', pos:'danh từ'},

  /* Đơn vị đếm */
  {ko:'켤레', rom:'kyeolle', vi:'đôi (đếm giày, tất)', pos:'đơn vị đếm'},
  {ko:'그루', rom:'geuru', vi:'cây (đếm cây cối)', pos:'đơn vị đếm'},
  {ko:'대', rom:'dae', vi:'chiếc (đếm xe cộ, máy móc)', pos:'đơn vị đếm', hanja:'臺', hv:'đài'},
  {ko:'송이', rom:'songi', vi:'bông (đếm hoa)', pos:'đơn vị đếm'},

  /* Số Hán–Hàn hay dùng khi nghe */
  {ko:'백', rom:'baek', vi:'trăm', pos:'số từ', hanja:'百', hv:'bách'},
  {ko:'천', rom:'cheon', vi:'nghìn', pos:'số từ', hanja:'千', hv:'thiên'},
  {ko:'육', rom:'yuk', vi:'sáu', pos:'số từ', hanja:'六', hv:'lục'},
  {ko:'십삼', rom:'sipsam', vi:'mười ba', pos:'số từ', hanja:'十三', hv:'thập tam'},
  {ko:'오십', rom:'osip', vi:'năm mươi', pos:'số từ', hanja:'五十', hv:'ngũ thập'},
  {ko:'오천', rom:'ocheon', vi:'năm nghìn', pos:'số từ', hanja:'五千', hv:'ngũ thiên'},
  {ko:'삼천', rom:'samcheon', vi:'ba nghìn', pos:'số từ', hanja:'三千', hv:'tam thiên'},

  /* Động từ và trạng thái */
  {ko:'달리다', rom:'dallida', vi:'chạy', pos:'động từ'},
  {ko:'공부하다', rom:'gongbuhada', vi:'học bài', pos:'động từ', hanja:'工夫—', hv:'công phu'},
  {ko:'요리', rom:'yori', vi:'việc nấu ăn; món ăn', pos:'danh từ', hanja:'料理', hv:'liệu lý'},
  {ko:'설거지', rom:'seolgeoji', vi:'việc rửa bát', pos:'danh từ'},
  {ko:'가리키다', rom:'garikida', vi:'chỉ tay về phía', pos:'động từ'},
  {ko:'열리다', rom:'yeollida', vi:'được mở ra', pos:'động từ'},
  {ko:'닫히다', rom:'dachida', vi:'bị đóng lại', pos:'động từ'},
  {ko:'켜지다', rom:'kyeojida', vi:'được bật lên', pos:'động từ'},
  {ko:'꺼지다', rom:'kkeojida', vi:'bị tắt đi', pos:'động từ'},
  {ko:'놓이다', rom:'nochida', vi:'được đặt, được để', pos:'động từ'},
  {ko:'걸리다', rom:'geollida', vi:'được treo lên; mất (thời gian)', pos:'động từ'},
  {ko:'올라가다', rom:'ollagada', vi:'trèo lên, đi lên', pos:'động từ'},

  /* Trợ từ và phó từ hay làm bẫy nghe */
  {ko:'에', rom:'e', vi:'ở, tại (nơi tồn tại); vào lúc', pos:'trợ từ'},
  {ko:'에서', rom:'eseo', vi:'ở (nơi diễn ra hành động); từ', pos:'trợ từ'},
  {ko:'도', rom:'do', vi:'cũng; (đi với phủ định) một… nào', pos:'trợ từ'},
  {ko:'들', rom:'deul', vi:'đuôi chỉ số nhiều', pos:'đuôi từ'},
  {ko:'아무도', rom:'amudo', vi:'không một ai (đi với phủ định)', pos:'đại từ'},

  /* ============================================================
     BỔ SUNG SAU KHI ĐO ĐỘ PHỦ TRA TỪ
     ------------------------------------------------------------
     Đo lại toàn bộ câu ví dụ thấy nhiều chỗ bấm vào không ra gì.
     Phần lớn không phải từ vựng thiếu mà là hai thứ khác:

       · DANH TỪ PHỤ THUỘC và MẪU NGỮ PHÁP — 거예요, 만큼, 마련이다,
         셈이다, 따름이다. Chúng không phải «từ» theo nghĩa thông
         thường nên giáo trình không xếp vào bảng từ vựng, nhưng lại
         là thứ người học bấm vào nhiều nhất vì không đoán được nghĩa.

       · ĐỘNG TỪ ĐI VỚI TRỢ TỪ CỐ ĐỊNH — 통하다 (-를 통해), 비하다
         (-에 비해), 인하다 (-로 인해). Trong câu chúng luôn hiện ra ở
         dạng đã chia nên không ai nghĩ tới việc tra dạng gốc.

     Nội dung do LangLab tự biên soạn.
     ============================================================ */

  /* ---------- Danh từ phụ thuộc & mẫu ngữ pháp ---------- */
  {ko:'거예요', rom:'geoyeyo', vi:'sẽ…; chắc là… (nói tắt của 것이에요, đứng sau -을/ㄹ)', pos:'mẫu ngữ pháp'},
  {ko:'건', rom:'geon', vi:'cái mà… (nói tắt của 것은)', pos:'mẫu ngữ pháp'},
  {ko:'만큼', rom:'mankeum', vi:'bằng, đến mức', pos:'danh từ phụ thuộc'},
  {ko:'데', rom:'de', vi:'chỗ, nơi; việc, điểm', pos:'danh từ phụ thuộc'},
  {ko:'텐데', rom:'tende', vi:'chắc là… (đứng sau -을/ㄹ, tỏ phỏng đoán kèm tiếc nuối)', pos:'mẫu ngữ pháp'},
  {ko:'데다가', rom:'dedaga', vi:'thêm vào đó, đã… lại còn…', pos:'mẫu ngữ pháp'},
  {ko:'따름', rom:'ttareum', vi:'chỉ có thế thôi (…을 따름이다)', pos:'danh từ phụ thuộc'},
  {ko:'마련', rom:'maryeon', vi:'lẽ tất nhiên sẽ… (…기 마련이다)', pos:'danh từ phụ thuộc'},
  {ko:'뿐', rom:'ppun', vi:'chỉ, chỉ có', pos:'danh từ phụ thuộc'},
  {ko:'셈', rom:'sem', vi:'coi như là (…는 셈이다)', pos:'danh từ phụ thuộc'},
  {ko:'나름', rom:'nareum', vi:'tuỳ vào (…기 나름이다)', pos:'danh từ phụ thuộc'},
  {ko:'십상', rom:'sipsang', vi:'dễ mà… lắm (…기 십상이다)', pos:'danh từ phụ thuộc', hanja:'十常', hv:'thập thường'},
  {ko:'채', rom:'chae', vi:'nguyên trạng, cứ để nguyên (…은 채로)', pos:'danh từ phụ thuộc'},
  {ko:'겸', rom:'gyeom', vi:'kiêm, vừa… vừa…', pos:'danh từ phụ thuộc', hanja:'兼', hv:'kiêm'},
  {ko:'둥', rom:'dung', vi:'kiểu như, ra vẻ (…는 둥 마는 둥)', pos:'danh từ phụ thuộc'},
  {ko:'리', rom:'ri', vi:'lẽ nào, có lí nào (…을 리가 없다)', pos:'danh từ phụ thuộc', hanja:'理', hv:'lí'},
  {ko:'바', rom:'ba', vi:'điều, việc (…는 바와 같이)', pos:'danh từ phụ thuộc'},
  {ko:'만무하다', rom:'manmuhada', vi:'không thể có chuyện… (…을 리 만무하다)', pos:'tính từ', hanja:'萬無—', hv:'vạn vô'},
  {ko:'마는', rom:'maneun', vi:'nhưng mà (nối sau câu, văn viết)', pos:'liên từ'},
  {ko:'무언가', rom:'mueonga', vi:'cái gì đó', pos:'đại từ'},
  {ko:'대가', rom:'daega', vi:'cái giá phải trả', pos:'danh từ', hanja:'代價', hv:'đại giá'},
  {ko:'한', rom:'han', vi:'giới hạn, chừng mực (…는 한)', pos:'danh từ phụ thuộc', hanja:'限', hv:'hạn'},

  /* ---------- Động từ đi kèm trợ từ cố định ---------- */
  {ko:'통하다', rom:'tonghada', vi:'thông qua, nhờ vào (…를 통해)', pos:'động từ', hanja:'通—', hv:'thông'},
  {ko:'비하다', rom:'bihada', vi:'so với (…에 비해)', pos:'động từ', hanja:'比—', hv:'tỉ'},
  {ko:'반하다', rom:'banhada', vi:'ngược lại với (…에 반해)', pos:'động từ', hanja:'反—', hv:'phản'},
  {ko:'인하다', rom:'inhada', vi:'do, bởi (…로 인해)', pos:'động từ', hanja:'因—', hv:'nhân'},
  {ko:'대하다', rom:'daehada', vi:'về, đối với (…에 대해)', pos:'động từ', hanja:'對—', hv:'đối'},
  {ko:'관하다', rom:'gwanhada', vi:'liên quan tới (…에 관해)', pos:'động từ', hanja:'關—', hv:'quan'},
  {ko:'비롯하다', rom:'birothada', vi:'bắt đầu từ; kể cả (…를 비롯해)', pos:'động từ'},
  {ko:'비롯되다', rom:'birotdoeda', vi:'bắt nguồn từ', pos:'động từ'},
  {ko:'불구하다', rom:'bulguhada', vi:'mặc dù (…에도 불구하고)', pos:'động từ', hanja:'不拘—', hv:'bất câu'},
  {ko:'말미암다', rom:'malmiamda', vi:'do bởi (…로 말미암아, văn viết)', pos:'động từ'},
  {ko:'막론하다', rom:'mangnonhada', vi:'bất kể (…를 막론하고)', pos:'động từ', hanja:'莫論—', hv:'mạc luận'},
  {ko:'따르다', rom:'ttareuda', vi:'theo, tuân theo (…에 따르면: theo như)', pos:'động từ'},
  {ko:'불과하다', rom:'bulgwahada', vi:'chỉ là, chẳng qua là', pos:'tính từ', hanja:'不過—', hv:'bất quá'},
  {ko:'중시하다', rom:'jungsihada', vi:'coi trọng', pos:'động từ', hanja:'重視—', hv:'trọng thị'},
  {ko:'척하다', rom:'cheokhada', vi:'giả vờ, làm ra vẻ', pos:'động từ'},
  {ko:'대신하다', rom:'daesinhada', vi:'thay thế', pos:'động từ', hanja:'代身—', hv:'đại thân'},

  /* ---------- Động từ · tính từ còn thiếu ---------- */
  {ko:'어떻다', rom:'eotteota', vi:'thế nào, ra sao', pos:'tính từ'},
  {ko:'필요하다', rom:'piryohada', vi:'cần thiết', pos:'tính từ', hanja:'必要—', hv:'tất yếu'},
  {ko:'걱정되다', rom:'geokjeongdoeda', vi:'thấy lo, đâm lo', pos:'động từ'},
  {ko:'걱정하다', rom:'geokjeonghada', vi:'lo lắng', pos:'động từ'},
  {ko:'안전하다', rom:'anjeonhada', vi:'an toàn', pos:'tính từ', hanja:'安全—', hv:'an toàn'},
  {ko:'자연스럽다', rom:'jayeonseureopda', vi:'tự nhiên, không gượng', pos:'tính từ', hanja:'自然—', hv:'tự nhiên'},
  {ko:'아름답다', rom:'areumdapda', vi:'đẹp', pos:'tính từ'},
  {ko:'소용없다', rom:'soyongeopda', vi:'vô ích', pos:'tính từ', hanja:'所用—', hv:'sở dụng'},
  {ko:'화내다', rom:'hwanaeda', vi:'nổi giận', pos:'động từ', hanja:'火—', hv:'hoả'},
  {ko:'어기다', rom:'eogida', vi:'vi phạm, trái lời', pos:'động từ'},
  {ko:'실천하다', rom:'silcheonhada', vi:'thực hiện, đưa vào làm', pos:'động từ', hanja:'實踐—', hv:'thực tiễn'},
  {ko:'실패하다', rom:'silpaehada', vi:'thất bại', pos:'động từ', hanja:'失敗—', hv:'thất bại'},
  {ko:'깊다', rom:'gipda', vi:'sâu', pos:'tính từ'},
  {ko:'늘어나다', rom:'neureonada', vi:'tăng lên, nhiều thêm', pos:'động từ'},
  {ko:'줄어들다', rom:'jureodeulda', vi:'giảm đi', pos:'động từ'},
  {ko:'짓다', rom:'jitda', vi:'xây; làm ra; đặt (tên)', pos:'động từ'},
  {ko:'기대다', rom:'gidaeda', vi:'dựa vào, ỷ vào', pos:'động từ'},
  {ko:'인정하다', rom:'injeonghada', vi:'công nhận, thừa nhận', pos:'động từ', hanja:'認定—', hv:'nhận định'},
  {ko:'대화하다', rom:'daehwahada', vi:'trò chuyện, đối thoại', pos:'động từ', hanja:'對話—', hv:'đối thoại'},
  {ko:'싸우다', rom:'ssauda', vi:'cãi nhau, đánh nhau', pos:'động từ'},
  {ko:'자유롭다', rom:'jayuropda', vi:'tự do', pos:'tính từ', hanja:'自由—', hv:'tự do'},
  {ko:'약해지다', rom:'yakhaejida', vi:'yếu đi', pos:'động từ', hanja:'弱—', hv:'nhược'},
  {ko:'택하다', rom:'taekhada', vi:'chọn', pos:'động từ', hanja:'擇—', hv:'trạch'},
  {ko:'얻다', rom:'eotda', vi:'nhận được, đạt được', pos:'động từ'},
  {ko:'이해되다', rom:'ihaedoeda', vi:'hiểu ra, thấy dễ hiểu', pos:'động từ', hanja:'理解—', hv:'lí giải'},
  {ko:'교류하다', rom:'gyoryuhada', vi:'giao lưu', pos:'động từ', hanja:'交流—', hv:'giao lưu'},
  {ko:'참여하다', rom:'chamyeohada', vi:'tham gia', pos:'động từ', hanja:'參與—', hv:'tham dự'},
  {ko:'발전하다', rom:'baljeonhada', vi:'phát triển', pos:'động từ', hanja:'發展—', hv:'phát triển'},
  {ko:'지키다', rom:'jikida', vi:'giữ gìn, tuân thủ', pos:'động từ'},
  {ko:'높이다', rom:'nopida', vi:'nâng cao', pos:'động từ'},
  {ko:'넓히다', rom:'neolpida', vi:'mở rộng', pos:'động từ'},
  {ko:'깎다', rom:'kkakda', vi:'gọt; bớt giá', pos:'động từ'},
  {ko:'아끼다', rom:'akkida', vi:'tiết kiệm; quý trọng', pos:'động từ'},
  {ko:'나아지다', rom:'naajida', vi:'khá lên, tốt lên', pos:'động từ'},
  {ko:'후회하다', rom:'huhoehada', vi:'hối hận', pos:'động từ', hanja:'後悔—', hv:'hậu hối'},
  {ko:'고민하다', rom:'gominhada', vi:'trăn trở, băn khoăn', pos:'động từ', hanja:'苦悶—', hv:'khổ muộn'},
  {ko:'노력하다', rom:'noryeokhada', vi:'nỗ lực', pos:'động từ', hanja:'努力—', hv:'nỗ lực'},
  {ko:'취직하다', rom:'chwijikhada', vi:'xin được việc', pos:'động từ', hanja:'就職—', hv:'tựu chức'},
  {ko:'창업하다', rom:'changeophada', vi:'khởi nghiệp', pos:'động từ', hanja:'創業—', hv:'sáng nghiệp'},
  {ko:'도전하다', rom:'dojeonhada', vi:'thử sức, thách thức', pos:'động từ', hanja:'挑戰—', hv:'khiêu chiến'},
  {ko:'번역하다', rom:'beonyeokhada', vi:'dịch', pos:'động từ', hanja:'飜譯—', hv:'phiên dịch'},
  {ko:'검증하다', rom:'geomjeunghada', vi:'kiểm chứng', pos:'động từ', hanja:'檢證—', hv:'kiểm chứng'},
  {ko:'배려하다', rom:'baeryeohada', vi:'quan tâm, để ý tới người khác', pos:'động từ', hanja:'配慮—', hv:'phối lự'},
  {ko:'포기하다', rom:'pogihada', vi:'từ bỏ', pos:'động từ', hanja:'抛棄—', hv:'phao khí'},
  {ko:'보존되다', rom:'bojondoeda', vi:'được bảo tồn', pos:'động từ', hanja:'保存—', hv:'bảo tồn'},
  {ko:'과로하다', rom:'gwarohada', vi:'làm việc quá sức', pos:'động từ', hanja:'過勞—', hv:'quá lao'},
  {ko:'감추다', rom:'gamchuda', vi:'giấu đi', pos:'động từ'},
  {ko:'희생되다', rom:'huisaengdoeda', vi:'bị hi sinh', pos:'động từ', hanja:'犧牲—', hv:'hi sinh'},
  {ko:'감탄하다', rom:'gamtanhada', vi:'thán phục', pos:'động từ', hanja:'感歎—', hv:'cảm thán'},
  {ko:'대체하다', rom:'daechehada', vi:'thay thế', pos:'động từ', hanja:'代替—', hv:'đại thế'},
  {ko:'존중하다', rom:'jonjunghada', vi:'tôn trọng', pos:'động từ', hanja:'尊重—', hv:'tôn trọng'},
  {ko:'대비하다', rom:'daebihada', vi:'chuẩn bị đối phó', pos:'động từ', hanja:'對備—', hv:'đối bị'},
  {ko:'묻히다', rom:'muchida', vi:'bị dính, bị vùi', pos:'động từ'},
  {ko:'잘리다', rom:'jallida', vi:'bị cắt', pos:'động từ'},
  {ko:'선물하다', rom:'seonmulhada', vi:'tặng quà', pos:'động từ', hanja:'膳物—', hv:'thiện vật'},
  {ko:'살아가다', rom:'saragada', vi:'sống, sinh sống', pos:'động từ'},
  {ko:'드러나다', rom:'deureonada', vi:'lộ ra, hiện ra', pos:'động từ'},
  {ko:'지배하다', rom:'jibaehada', vi:'chi phối, thống trị', pos:'động từ', hanja:'支配—', hv:'chi phối'},
  {ko:'미치다', rom:'michida', vi:'gây ảnh hưởng, tác động tới', pos:'động từ'},
  {ko:'간소해지다', rom:'gansohaejida', vi:'trở nên giản tiện', pos:'động từ', hanja:'簡素—', hv:'giản tố'},
  {ko:'소중하다', rom:'sojunghada', vi:'quý giá', pos:'tính từ', hanja:'所重—', hv:'sở trọng'},
  {ko:'유한하다', rom:'yuhanhada', vi:'hữu hạn', pos:'tính từ', hanja:'有限—', hv:'hữu hạn'},
  {ko:'가난하다', rom:'gananhada', vi:'nghèo', pos:'tính từ'},
  {ko:'독창적이다', rom:'dokchangjeogida', vi:'độc đáo, có sáng tạo riêng', pos:'tính từ', hanja:'獨創的—', hv:'độc sáng đích'},
  {ko:'객관적이다', rom:'gaekgwanjeogida', vi:'khách quan', pos:'tính từ', hanja:'客觀的—', hv:'khách quan đích'},
  {ko:'치열해지다', rom:'chiyeolhaejida', vi:'trở nên gay gắt', pos:'động từ', hanja:'熾烈—', hv:'sí liệt'},
  {ko:'편향되다', rom:'pyeonhyangdoeda', vi:'bị thiên lệch', pos:'động từ', hanja:'偏向—', hv:'thiên hướng'},
  {ko:'뒤따르다', rom:'dwittareuda', vi:'đi kèm theo sau', pos:'động từ'},
  {ko:'타고나다', rom:'tagonada', vi:'bẩm sinh có', pos:'động từ'},
  {ko:'틀림없다', rom:'teullimeopda', vi:'chắc chắn, không sai vào đâu', pos:'tính từ'},
  {ko:'인정받다', rom:'injeongbatda', vi:'được công nhận', pos:'động từ', hanja:'認定—', hv:'nhận định'},
  {ko:'바람직하다', rom:'baramjikhada', vi:'đáng mong muốn, nên như vậy', pos:'tính từ'},
  {ko:'대응하다', rom:'daeeunghada', vi:'ứng phó', pos:'động từ', hanja:'對應—', hv:'đối ứng'},
  {ko:'분명해지다', rom:'bunmyeonghaejida', vi:'trở nên rõ ràng', pos:'động từ', hanja:'分明—', hv:'phân minh'},
  {ko:'충분하다', rom:'chungbunhada', vi:'đầy đủ', pos:'tính từ', hanja:'充分—', hv:'sung phân'},
  {ko:'참신하다', rom:'chamsinhada', vi:'mới mẻ, độc đáo', pos:'tính từ', hanja:'斬新—', hv:'trảm tân'},
  {ko:'평등하다', rom:'pyeongdeunghada', vi:'bình đẳng', pos:'tính từ', hanja:'平等—', hv:'bình đẳng'},

  /* ---------- Phó từ · đại từ · liên từ ---------- */
  {ko:'좀', rom:'jom', vi:'một chút; làm ơn (nói giảm cho lịch sự)', pos:'phó từ'},
  {ko:'서로', rom:'seoro', vi:'lẫn nhau', pos:'phó từ'},
  {ko:'뭐', rom:'mwo', vi:'gì, cái gì (nói tắt của 무엇)', pos:'đại từ'},
  {ko:'또', rom:'tto', vi:'lại, lại nữa', pos:'phó từ'},
  {ko:'그저', rom:'geujeo', vi:'chỉ là, đơn thuần', pos:'phó từ'},
  {ko:'한번', rom:'hanbeon', vi:'một lần; thử xem', pos:'phó từ'},
  {ko:'누구나', rom:'nuguna', vi:'ai cũng', pos:'đại từ'},
  {ko:'그렇게', rom:'geureoke', vi:'như thế, như vậy', pos:'phó từ'},
  {ko:'옛날', rom:'yennal', vi:'ngày xưa', pos:'danh từ'},
  {ko:'매달', rom:'maedal', vi:'hằng tháng', pos:'phó từ', hanja:'每—', hv:'mỗi'},
  {ko:'그러니', rom:'geureoni', vi:'vậy nên', pos:'liên từ'},
  {ko:'점점', rom:'jeomjeom', vi:'dần dần', pos:'phó từ', hanja:'漸漸', hv:'tiệm tiệm'},
  {ko:'완전히', rom:'wanjeonhi', vi:'hoàn toàn', pos:'phó từ', hanja:'完全—', hv:'hoàn toàn'},
  {ko:'언젠가', rom:'eonjenga', vi:'một lúc nào đó', pos:'phó từ'},
  {ko:'스스로', rom:'seuseuro', vi:'tự mình', pos:'phó từ'},
  {ko:'무척', rom:'mucheok', vi:'vô cùng, rất', pos:'phó từ'},
  {ko:'차분히', rom:'chabunhi', vi:'điềm tĩnh, thong thả', pos:'phó từ'},
  {ko:'바로', rom:'baro', vi:'ngay, chính là', pos:'phó từ'},
  {ko:'매우', rom:'maeu', vi:'rất', pos:'phó từ'},
  {ko:'역시', rom:'yeoksi', vi:'quả nhiên; cũng vậy', pos:'phó từ', hanja:'亦是', hv:'diệc thị'},
  {ko:'여러', rom:'yeoreo', vi:'nhiều, vài', pos:'định từ'},
  {ko:'소홀히', rom:'soholhi', vi:'qua loa, lơ là', pos:'phó từ', hanja:'疏忽—', hv:'sơ hốt'},
  {ko:'당분간', rom:'dangbungan', vi:'trong thời gian tới', pos:'phó từ', hanja:'當分間', hv:'đương phân gian'},
  {ko:'예전', rom:'yejeon', vi:'trước kia', pos:'danh từ'},
  {ko:'지난번', rom:'jinanbeon', vi:'lần trước', pos:'danh từ'},
  {ko:'그날', rom:'geunal', vi:'hôm ấy', pos:'danh từ'},
  {ko:'글쎄요', rom:'geulsseyo', vi:'để xem đã, khó nói quá', pos:'thán từ'},
  {ko:'그럼', rom:'geureom', vi:'vậy thì; tất nhiên rồi', pos:'liên từ'},
  {ko:'나머지', rom:'nameoji', vi:'phần còn lại', pos:'danh từ'},
  {ko:'본인', rom:'bonin', vi:'bản thân người đó', pos:'danh từ', hanja:'本人', hv:'bản nhân'},

  /* ---------- Danh từ còn thiếu ---------- */
  {ko:'원인', rom:'wonin', vi:'nguyên nhân', pos:'danh từ', hanja:'原因', hv:'nguyên nhân'},
  {ko:'역할', rom:'yeokhal', vi:'vai trò', pos:'danh từ', hanja:'役割', hv:'dịch cát'},
  {ko:'삶', rom:'sam', vi:'cuộc sống, cuộc đời', pos:'danh từ'},
  {ko:'질', rom:'jil', vi:'chất lượng', pos:'danh từ', hanja:'質', hv:'chất'},
  {ko:'손해', rom:'sonhae', vi:'thiệt hại', pos:'danh từ', hanja:'損害', hv:'tổn hại'},
  {ko:'효과', rom:'hyogwa', vi:'hiệu quả', pos:'danh từ', hanja:'效果', hv:'hiệu quả'},
  {ko:'지식', rom:'jisik', vi:'kiến thức', pos:'danh từ', hanja:'知識', hv:'tri thức'},
  {ko:'배움', rom:'baeum', vi:'sự học', pos:'danh từ'},
  {ko:'상상력', rom:'sangsangnyeok', vi:'trí tưởng tượng', pos:'danh từ', hanja:'想像力', hv:'tưởng tượng lực'},
  {ko:'예술', rom:'yesul', vi:'nghệ thuật', pos:'danh từ', hanja:'藝術', hv:'nghệ thuật'},
  {ko:'껍데기', rom:'kkeopdegi', vi:'cái vỏ ngoài', pos:'danh từ'},
  {ko:'기계', rom:'gigye', vi:'máy móc', pos:'danh từ', hanja:'機械', hv:'cơ giới'},
  {ko:'위험', rom:'wiheom', vi:'nguy hiểm, rủi ro', pos:'danh từ', hanja:'危險', hv:'nguy hiểm'},
  {ko:'다름', rom:'dareum', vi:'sự khác biệt', pos:'danh từ'},
  {ko:'순간', rom:'sungan', vi:'khoảnh khắc', pos:'danh từ', hanja:'瞬間', hv:'thuấn gian'},
  {ko:'행사', rom:'haengsa', vi:'sự kiện, lễ hội', pos:'danh từ', hanja:'行事', hv:'hành sự'},
  {ko:'참여', rom:'chamyeo', vi:'sự tham gia', pos:'danh từ', hanja:'參與', hv:'tham dự'},
  {ko:'사실', rom:'sasil', vi:'sự thật; thật ra', pos:'danh từ', hanja:'事實', hv:'sự thật'},
  {ko:'증거', rom:'jeunggeo', vi:'bằng chứng', pos:'danh từ', hanja:'證據', hv:'chứng cứ'},
  {ko:'근거', rom:'geungeo', vi:'căn cứ, cơ sở', pos:'danh từ', hanja:'根據', hv:'căn cứ'},
  {ko:'목표', rom:'mokpyo', vi:'mục tiêu', pos:'danh từ', hanja:'目標', hv:'mục tiêu'},
  {ko:'성과', rom:'seonggwa', vi:'thành quả', pos:'danh từ', hanja:'成果', hv:'thành quả'},
  {ko:'양식', rom:'yangsik', vi:'kiểu, phong cách; biểu mẫu', pos:'danh từ', hanja:'樣式', hv:'dạng thức'},
  {ko:'원형', rom:'wonhyeong', vi:'nguyên bản, hình dạng gốc', pos:'danh từ', hanja:'原形', hv:'nguyên hình'},
  {ko:'유서', rom:'yuseo', vi:'lai lịch lâu đời (유서 깊다)', pos:'danh từ', hanja:'由緖', hv:'do tự'},
  {ko:'계층', rom:'gyecheung', vi:'tầng lớp', pos:'danh từ', hanja:'階層', hv:'giai tầng'},
  {ko:'확대', rom:'hwakdae', vi:'sự mở rộng', pos:'danh từ', hanja:'擴大', hv:'khuếch đại'},
  {ko:'시민', rom:'simin', vi:'người dân, công dân', pos:'danh từ', hanja:'市民', hv:'thị dân'},
  {ko:'정부', rom:'jeongbu', vi:'chính phủ', pos:'danh từ', hanja:'政府', hv:'chính phủ'},
  {ko:'산업화', rom:'saneophwa', vi:'công nghiệp hoá', pos:'danh từ', hanja:'産業化', hv:'sản nghiệp hoá'},
  {ko:'환경오염', rom:'hwangyeongoyeom', vi:'ô nhiễm môi trường', pos:'danh từ', hanja:'環境汚染', hv:'hoàn cảnh ô nhiễm'},
  {ko:'남용', rom:'namyong', vi:'sự lạm dụng', pos:'danh từ', hanja:'濫用', hv:'lạm dụng'},
  {ko:'편집', rom:'pyeonjip', vi:'sự biên tập', pos:'danh từ', hanja:'編輯', hv:'biên tập'},
  {ko:'윤리', rom:'yulli', vi:'đạo đức, luân lí', pos:'danh từ', hanja:'倫理', hv:'luân lí'},
  {ko:'지위', rom:'jiwi', vi:'địa vị', pos:'danh từ', hanja:'地位', hv:'địa vị'},
  {ko:'관용', rom:'gwanyong', vi:'sự bao dung', pos:'danh từ', hanja:'寬容', hv:'khoan dung'},
  {ko:'바탕', rom:'batang', vi:'nền tảng', pos:'danh từ'},
  {ko:'불교', rom:'bulgyo', vi:'đạo Phật', pos:'danh từ', hanja:'佛敎', hv:'phật giáo'},
  {ko:'정취', rom:'jeongchwi', vi:'nét thi vị, hồn quê', pos:'danh từ', hanja:'情趣', hv:'tình thú'},
  {ko:'녹지', rom:'nokji', vi:'mảng xanh', pos:'danh từ', hanja:'綠地', hv:'lục địa'},
  {ko:'의욕', rom:'uiyok', vi:'ý chí, động lực', pos:'danh từ', hanja:'意慾', hv:'ý dục'},
  {ko:'끈기', rom:'kkeungi', vi:'sự bền bỉ', pos:'danh từ'},
  {ko:'장점', rom:'jangjeom', vi:'điểm mạnh', pos:'danh từ', hanja:'長點', hv:'trường điểm'},
  {ko:'핵심', rom:'haeksim', vi:'cốt lõi', pos:'danh từ', hanja:'核心', hv:'hạch tâm'},
  {ko:'성숙', rom:'seongsuk', vi:'sự trưởng thành', pos:'danh từ', hanja:'成熟', hv:'thành thục'},
  {ko:'태도', rom:'taedo', vi:'thái độ', pos:'danh từ', hanja:'態度', hv:'thái độ'},
  {ko:'자세', rom:'jase', vi:'tư thế; thái độ', pos:'danh từ', hanja:'姿勢', hv:'tư thế'},
  {ko:'소식', rom:'sosik', vi:'tin tức', pos:'danh từ', hanja:'消息', hv:'tiêu tức'},
  {ko:'습관', rom:'seupgwan', vi:'thói quen', pos:'danh từ', hanja:'習慣', hv:'tập quán'},
  {ko:'지역', rom:'jiyeok', vi:'khu vực', pos:'danh từ', hanja:'地域', hv:'địa vực'},
  {ko:'대기업', rom:'daegieop', vi:'tập đoàn lớn', pos:'danh từ', hanja:'大企業', hv:'đại xí nghiệp'},
  {ko:'중소기업', rom:'jungsogieop', vi:'doanh nghiệp vừa và nhỏ', pos:'danh từ', hanja:'中小企業', hv:'trung tiểu xí nghiệp'},
  {ko:'뮤지컬', rom:'myujikeol', vi:'nhạc kịch', pos:'danh từ'},
  {ko:'클래식', rom:'keullaesik', vi:'nhạc cổ điển', pos:'danh từ'},
  {ko:'음식물', rom:'eumsingmul', vi:'thức ăn, đồ ăn thừa', pos:'danh từ', hanja:'飮食物', hv:'ẩm thực vật'},
  {ko:'다회용', rom:'dahoeyong', vi:'dùng được nhiều lần', pos:'danh từ', hanja:'多回用', hv:'đa hồi dụng'},
  {ko:'층간', rom:'cheunggan', vi:'giữa các tầng (층간 소음: tiếng ồn giữa các tầng)', pos:'danh từ', hanja:'層間', hv:'tầng gian'},
  {ko:'유연', rom:'yuyeon', vi:'linh hoạt', pos:'danh từ', hanja:'柔軟', hv:'nhu nhuyễn'},
  {ko:'허리띠', rom:'heoritti', vi:'thắt lưng', pos:'danh từ'},
  {ko:'며칠', rom:'myeochil', vi:'mấy ngày; ngày mấy', pos:'danh từ'},
  {ko:'월', rom:'wol', vi:'tháng', pos:'danh từ', hanja:'月', hv:'nguyệt'},
  {ko:'칠', rom:'chil', vi:'bảy (số Hán–Hàn)', pos:'số từ', hanja:'七', hv:'thất'},
  {ko:'십일', rom:'sibil', vi:'mười một', pos:'số từ', hanja:'十一', hv:'thập nhất'},
  {ko:'이십오', rom:'isibo', vi:'hai mươi lăm', pos:'số từ', hanja:'二十五', hv:'nhị thập ngũ'},
  {ko:'이천', rom:'icheon', vi:'hai nghìn', pos:'số từ', hanja:'二千', hv:'nhị thiên'},
  {ko:'육천', rom:'yukcheon', vi:'sáu nghìn', pos:'số từ', hanja:'六千', hv:'lục thiên'},
  {ko:'삼만', rom:'samman', vi:'ba vạn (30.000)', pos:'số từ', hanja:'三萬', hv:'tam vạn'},
  {ko:'이십', rom:'isip', vi:'hai mươi', pos:'số từ', hanja:'二十', hv:'nhị thập'},

  /* ---------- Tên riêng ---------- */
  {ko:'꾸언', rom:'kkueon', vi:'Quân (tên nam, người Việt)', pos:'tên riêng'},
  {ko:'응우옌', rom:'eunguyen', vi:'Nguyễn (họ người Việt)', pos:'tên riêng'},
  {ko:'딘', rom:'din', vi:'Đình (tên đệm người Việt)', pos:'tên riêng'},
  {ko:'김민수', rom:'gimminsu', vi:'Kim Min-su (họ tên người Hàn)', pos:'tên riêng'},
  {ko:'수진', rom:'sujin', vi:'Su-jin (tên nữ, người Hàn)', pos:'tên riêng'},
  {ko:'제주도', rom:'jejudo', vi:'đảo Jeju', pos:'tên riêng', hanja:'濟州島', hv:'tế châu đảo'},
  {ko:'명동', rom:'myeongdong', vi:'Myeong-dong (khu mua sắm ở Seoul)', pos:'tên riêng', hanja:'明洞', hv:'minh động'},
  {ko:'서울역', rom:'seoullyeok', vi:'ga Seoul', pos:'tên riêng', hanja:'—驛', hv:'dịch'},
  {ko:'충무로역', rom:'chungmuroyeok', vi:'ga Chungmuro', pos:'tên riêng', hanja:'忠武路驛', hv:'trung vũ lộ dịch'},
  {ko:'전주', rom:'jeonju', vi:'Jeonju (thành phố nổi tiếng về ẩm thực và làng cổ)', pos:'tên riêng', hanja:'全州', hv:'toàn châu'},
  {ko:'한옥마을', rom:'hanongmaeul', vi:'làng nhà cổ Hanok', pos:'tên riêng', hanja:'韓屋—', hv:'hàn ốc'},

];
if (typeof window !== 'undefined') window.VOCAB_COMMON = VOCAB_COMMON;
