/* ============================================================
   LangLab — TỪ NỀN CỦA TIẾNG TÂY BAN NHA
   ------------------------------------------------------------
   Cùng một lí do như bên tiếng Pháp: ràng buộc «không từ nào lặp
   giữa 100 bài» giữ kho từ sạch nhưng đẩy việc chọn từ trôi sang
   từ hiếm, nên «hacer», «libro», «día», «semana», «el», «de» chỉ
   sống trong câu ví dụ mà không bao giờ thành mục từ. Bấm vào thì
   không tra được.

   Tệp này lấp đúng chỗ đó. Hình dạng mục từ giống hệt từ vựng bài
   học, nên bảng chia động từ, hợp giống và bộ tách gốc La-tinh tự
   chạy — thêm một động từ là mọi dạng chia của nó tra được ngay.

   Nội dung do LangLab tự biên soạn.
   ============================================================ */

const WORDS_CORE_ES = [

/* ---------- MẠO TỪ VÀ TỪ HẠN ĐỊNH ---------- */
{ es:'el', ipa:'el', vi:'(mạo từ xác định, giống đực)', pos:'mạo từ', g:'', note:'Gặp a thành al, gặp de thành del. Có dấu «él» thì lại là đại từ «anh ấy».' },
{ es:'la', ipa:'la', vi:'(mạo từ xác định, giống cái)', pos:'mạo từ', g:'' },
{ es:'los', ipa:'los', vi:'(mạo từ xác định, số nhiều đực)', pos:'mạo từ', g:'' },
{ es:'las', ipa:'las', vi:'(mạo từ xác định, số nhiều cái)', pos:'mạo từ', g:'' },
{ es:'lo', ipa:'lo', vi:'(mạo từ trung tính); nó, điều đó', pos:'mạo từ', g:'', note:'Lo + tính từ tạo ra khái niệm trừu tượng: lo importante = «cái quan trọng». Cũng là đại từ tân ngữ giống đực.' },
{ es:'un', ipa:'un', vi:'một (giống đực)', pos:'mạo từ', g:'' },
{ es:'una', ipa:'ˈu.na', vi:'một (giống cái)', pos:'mạo từ', g:'' },
{ es:'unos', ipa:'ˈu.nos', vi:'một vài (đực)', pos:'mạo từ', g:'' },
{ es:'unas', ipa:'ˈu.nas', vi:'một vài (cái)', pos:'mạo từ', g:'' },
{ es:'al', ipa:'al', vi:'tới, đến (a + el)', pos:'giới từ', g:'', note:'Al + nguyên mẫu nghĩa là «khi»: al llegar = khi tới.' },
{ es:'del', ipa:'del', vi:'của, từ (de + el)', pos:'giới từ', g:'' },
{ es:'este', ipa:'ˈes.te', vi:'này (đực)', pos:'từ chỉ định', g:'' },
{ es:'esta', ipa:'ˈes.ta', vi:'này (cái)', pos:'từ chỉ định', g:'' },
{ es:'estos', ipa:'ˈes.tos', vi:'những… này (đực)', pos:'từ chỉ định', g:'' },
{ es:'estas', ipa:'ˈes.tas', vi:'những… này (cái)', pos:'từ chỉ định', g:'' },
{ es:'esto', ipa:'ˈes.to', vi:'điều này', pos:'đại từ', g:'' },
{ es:'ese', ipa:'ˈe.se', vi:'đó (đực)', pos:'từ chỉ định', g:'', note:'Ba tầng khoảng cách: este (gần tôi), ese (gần anh), aquel (xa cả hai).' },
{ es:'esa', ipa:'ˈe.sa', vi:'đó (cái)', pos:'từ chỉ định', g:'' },
{ es:'eso', ipa:'ˈe.so', vi:'điều đó', pos:'đại từ', g:'' },
{ es:'aquel', ipa:'aˈkel', vi:'kia (xa)', pos:'từ chỉ định', g:'' },
{ es:'aquella', ipa:'aˈke.ʝa', vi:'kia (cái, xa)', pos:'từ chỉ định', g:'' },
{ es:'mi', ipa:'mi', vi:'của tôi', pos:'từ sở hữu', g:'', note:'Có dấu «mí» thì là đại từ sau giới từ: para mí.' },
{ es:'mis', ipa:'mis', vi:'của tôi (số nhiều)', pos:'từ sở hữu', g:'' },
{ es:'tu', ipa:'tu', vi:'của cậu', pos:'từ sở hữu', g:'', note:'Không dấu là «của cậu», có dấu «tú» là «cậu».' },
{ es:'tus', ipa:'tus', vi:'của cậu (số nhiều)', pos:'từ sở hữu', g:'' },
{ es:'su', ipa:'su', vi:'của anh ấy, của cô ấy, của ngài, của họ', pos:'từ sở hữu', g:'', note:'Một chữ gánh rất nhiều chủ sở hữu — khi mơ hồ thì thêm de él, de ella, de usted.' },
{ es:'sus', ipa:'sus', vi:'của họ (số nhiều)', pos:'từ sở hữu', g:'' },
{ es:'nuestro', ipa:'ˈnwes.tɾo', vi:'của chúng tôi', pos:'từ sở hữu', g:'' },
{ es:'nuestra', ipa:'ˈnwes.tɾa', vi:'của chúng tôi (cái)', pos:'từ sở hữu', g:'' },
{ es:'vuestro', ipa:'ˈbwes.tɾo', vi:'của các bạn', pos:'từ sở hữu', g:'', note:'Chỉ dùng ở Tây Ban Nha; Mỹ Latin dùng su.' },

/* ---------- ĐẠI TỪ ---------- */
{ es:'yo', ipa:'ʝo', vi:'tôi', pos:'đại từ', g:'', note:'Thường bỏ đi vì đuôi động từ đã cho biết ngôi; nói ra là để nhấn mạnh.' },
{ es:'tú', ipa:'tu', vi:'cậu', pos:'đại từ', g:'' },
{ es:'él', ipa:'el', vi:'anh ấy', pos:'đại từ', g:'' },
{ es:'ella', ipa:'ˈe.ʝa', vi:'cô ấy', pos:'đại từ', g:'' },
{ es:'usted', ipa:'usˈteð', vi:'ngài, quý ông, quý bà', pos:'đại từ', g:'', note:'Lịch sự, nhưng động từ chia như ngôi thứ ba: usted tiene.' },
{ es:'nosotros', ipa:'noˈso.tɾos', vi:'chúng tôi', pos:'đại từ', g:'' },
{ es:'nosotras', ipa:'noˈso.tɾas', vi:'chúng tôi (toàn nữ)', pos:'đại từ', g:'' },
{ es:'vosotros', ipa:'boˈso.tɾos', vi:'các bạn', pos:'đại từ', g:'' },
{ es:'ellos', ipa:'ˈe.ʝos', vi:'họ (đực)', pos:'đại từ', g:'' },
{ es:'ellas', ipa:'ˈe.ʝas', vi:'họ (cái)', pos:'đại từ', g:'' },
{ es:'ustedes', ipa:'usˈte.ðes', vi:'quý vị, các ngài', pos:'đại từ', g:'' },
{ es:'me', ipa:'me', vi:'tôi (tân ngữ)', pos:'đại từ', g:'' },
{ es:'te', ipa:'te', vi:'cậu (tân ngữ)', pos:'đại từ', g:'' },
{ es:'se', ipa:'se', vi:'mình, nhau; người ta', pos:'đại từ', g:'', note:'Bốn việc: phản thân, tương hỗ, câu vô nhân xưng (se dice), và thay le trước lo/la.' },
{ es:'nos', ipa:'nos', vi:'chúng tôi (tân ngữ)', pos:'đại từ', g:'' },
{ es:'le', ipa:'le', vi:'cho anh ấy, cho cô ấy', pos:'đại từ', g:'' },
{ es:'les', ipa:'les', vi:'cho họ', pos:'đại từ', g:'' },
{ es:'mí', ipa:'mi', vi:'tôi (sau giới từ)', pos:'đại từ', g:'' },
{ es:'ti', ipa:'ti', vi:'cậu (sau giới từ)', pos:'đại từ', g:'' },
{ es:'conmigo', ipa:'komˈmi.ɣo', vi:'với tôi', pos:'đại từ', g:'', note:'Ba từ dính liền còn sót lại từ tiếng La-tinh: con + mi + cum.' },
{ es:'alguien', ipa:'ˈal.ɣjen', vi:'một ai đó', pos:'đại từ', g:'' },
{ es:'algo', ipa:'ˈal.ɣo', vi:'một cái gì đó', pos:'đại từ', g:'' },
{ es:'nadie', ipa:'ˈna.ðje', vi:'không ai', pos:'đại từ', g:'' },
{ es:'nada', ipa:'ˈna.ða', vi:'không gì', pos:'đại từ', g:'', note:'No… nada là phủ định đôi, bắt buộc trong tiếng Tây Ban Nha: no veo nada.' },
{ es:'todo', ipa:'ˈto.ðo', vi:'tất cả, mọi thứ', pos:'đại từ', g:'' },
{ es:'toda', ipa:'ˈto.ða', vi:'toàn bộ (cái)', pos:'từ hạn định', g:'' },
{ es:'todos', ipa:'ˈto.ðos', vi:'tất cả (số nhiều)', pos:'từ hạn định', g:'' },
{ es:'todas', ipa:'ˈto.ðas', vi:'tất cả (số nhiều cái)', pos:'từ hạn định', g:'' },
{ es:'otro', ipa:'ˈo.tɾo', vi:'khác', pos:'tính từ', g:'', note:'Không bao giờ đi với un: «otro día», chứ không phải «un otro día».' },
{ es:'otra', ipa:'ˈo.tɾa', vi:'khác (cái)', pos:'tính từ', g:'' },
{ es:'mismo', ipa:'ˈmiz.mo', vi:'cùng, chính', pos:'tính từ', g:'' },
{ es:'cada', ipa:'ˈka.ða', vi:'mỗi', pos:'từ hạn định', g:'', note:'Không đổi theo giống.' },
{ es:'alguno', ipa:'alˈɣu.no', vi:'nào đó', pos:'từ hạn định', g:'' },
{ es:'ninguno', ipa:'ninˈɣu.no', vi:'không một… nào', pos:'từ hạn định', g:'' },
{ es:'varios', ipa:'ˈba.ɾjos', vi:'vài', pos:'từ hạn định', g:'' },
{ es:'ambos', ipa:'ˈam.bos', vi:'cả hai', pos:'từ hạn định', g:'' },
{ es:'cualquier', ipa:'kwalˈkjeɾ', vi:'bất kì', pos:'từ hạn định', g:'' },

/* ---------- GIỚI TỪ VÀ LIÊN TỪ ---------- */
{ es:'de', ipa:'de', vi:'của, từ', pos:'giới từ', g:'', note:'Giới từ dùng nhiều nhất. Cũng là cách nói sở hữu: el libro de Ana.' },
{ es:'a', ipa:'a', vi:'tới, đến; (trước tân ngữ là người)', pos:'giới từ', g:'', note:'Tiếng Tây Ban Nha đặt a trước tân ngữ chỉ người: veo a María — tiếng Việt và tiếng Anh không có.' },
{ es:'en', ipa:'en', vi:'ở, trong, trên', pos:'giới từ', g:'', note:'Gánh cả «trong» lẫn «trên»: en la mesa có thể là trên bàn.' },
{ es:'con', ipa:'kon', vi:'với', pos:'giới từ', g:'' },
{ es:'sin', ipa:'sin', vi:'không có', pos:'giới từ', g:'' },
{ es:'por', ipa:'poɾ', vi:'bởi, qua, vì', pos:'giới từ', g:'', note:'Por là nguyên nhân và con đường; para là mục đích và đích đến. Cặp khó nhất của người mới học.' },
{ es:'para', ipa:'ˈpa.ɾa', vi:'để, cho', pos:'giới từ', g:'' },
{ es:'sobre', ipa:'ˈso.βɾe', vi:'trên; về', pos:'giới từ', g:'' },
{ es:'bajo', ipa:'ˈba.xo', vi:'dưới; thấp', pos:'giới từ / tính từ', g:'', note:'Là giới từ thì nghĩa «dưới»; là tính từ thì nghĩa «thấp».' },
{ es:'entre', ipa:'ˈen.tɾe', vi:'giữa', pos:'giới từ', g:'' },
{ es:'hasta', ipa:'ˈas.ta', vi:'cho tới; ngay cả', pos:'giới từ', g:'' },
{ es:'desde', ipa:'ˈdez.ðe', vi:'từ (mốc)', pos:'giới từ', g:'' },
{ es:'hacia', ipa:'ˈa.sja', vi:'về phía', pos:'giới từ', g:'' },
{ es:'según', ipa:'seˈɣun', vi:'theo như', pos:'giới từ', g:'' },
{ es:'durante', ipa:'duˈɾan.te', vi:'trong suốt', pos:'giới từ', g:'' },
{ es:'contra', ipa:'ˈkon.tɾa', vi:'chống lại', pos:'giới từ', g:'' },
{ es:'y', ipa:'i', vi:'và', pos:'liên từ', g:'', note:'Trước từ bắt đầu bằng âm i thì đổi thành e: madre e hija.' },
{ es:'e', ipa:'e', vi:'và (trước âm i)', pos:'liên từ', g:'' },
{ es:'o', ipa:'o', vi:'hoặc', pos:'liên từ', g:'', note:'Trước từ bắt đầu bằng o thì đổi thành u: siete u ocho.' },
{ es:'u', ipa:'u', vi:'hoặc (trước âm o)', pos:'liên từ', g:'' },
{ es:'pero', ipa:'ˈpe.ɾo', vi:'nhưng', pos:'liên từ', g:'' },
{ es:'sino', ipa:'ˈsi.no', vi:'mà là', pos:'liên từ', g:'', note:'Dùng khi câu trước là phủ định: no es rojo, sino azul.' },
{ es:'que', ipa:'ke', vi:'rằng; mà; hơn', pos:'liên từ', g:'', note:'Không dấu là liên từ; có dấu «qué» là từ hỏi «cái gì».' },
{ es:'porque', ipa:'poɾˈke', vi:'bởi vì', pos:'liên từ', g:'', note:'Viết liền, không dấu. Còn «por qué» tách ra có dấu là «tại sao».' },
{ es:'si', ipa:'si', vi:'nếu', pos:'liên từ', g:'', note:'Không dấu là «nếu»; có dấu «sí» là «vâng».' },
{ es:'cuando', ipa:'ˈkwan.do', vi:'khi', pos:'liên từ', g:'' },
{ es:'como', ipa:'ˈko.mo', vi:'như; vì', pos:'liên từ', g:'' },
{ es:'aunque', ipa:'awŋˈke', vi:'mặc dù', pos:'liên từ', g:'' },
{ es:'mientras', ipa:'ˈmjen.tɾas', vi:'trong khi', pos:'liên từ', g:'' },
{ es:'también', ipa:'tamˈbjen', vi:'cũng', pos:'trạng từ', g:'' },
{ es:'tampoco', ipa:'tamˈpo.ko', vi:'cũng không', pos:'trạng từ', g:'' },

/* ---------- TRẠNG TỪ THÔNG DỤNG ---------- */
{ es:'no', ipa:'no', vi:'không', pos:'trạng từ', g:'', note:'Luôn đứng ngay trước động từ: no quiero.' },
{ es:'sí', ipa:'si', vi:'vâng, có', pos:'trạng từ', g:'' },
{ es:'muy', ipa:'mwi', vi:'rất', pos:'trạng từ', g:'', note:'Muy đứng trước tính từ; mucho đứng sau động từ. Không lẫn được.' },
{ es:'mucho', ipa:'ˈmu.tʃo', vi:'nhiều', pos:'trạng từ', g:'' },
{ es:'poco', ipa:'ˈpo.ko', vi:'ít', pos:'trạng từ', g:'' },
{ es:'más', ipa:'mas', vi:'hơn, nữa', pos:'trạng từ', g:'' },
{ es:'menos', ipa:'ˈme.nos', vi:'ít hơn', pos:'trạng từ', g:'' },
{ es:'tan', ipa:'tan', vi:'đến thế, như vậy', pos:'trạng từ', g:'' },
{ es:'tanto', ipa:'ˈtan.to', vi:'nhiều đến thế', pos:'trạng từ', g:'' },
{ es:'demasiado', ipa:'de.maˈsja.ðo', vi:'quá', pos:'trạng từ', g:'' },
{ es:'bastante', ipa:'basˈtan.te', vi:'khá; đủ', pos:'trạng từ', g:'' },
{ es:'casi', ipa:'ˈka.si', vi:'gần như', pos:'trạng từ', g:'' },
{ es:'sólo', ipa:'ˈso.lo', vi:'chỉ', pos:'trạng từ', g:'' },
{ es:'ya', ipa:'ʝa', vi:'đã, rồi; bây giờ', pos:'trạng từ', g:'', note:'Từ nhỏ mà nhiều sắc: ya voy = «tôi đến ngay đây».' },
{ es:'todavía', ipa:'to.ðaˈβi.a', vi:'vẫn còn', pos:'trạng từ', g:'' },
{ es:'aún', ipa:'aˈun', vi:'vẫn, còn', pos:'trạng từ', g:'' },
{ es:'siempre', ipa:'ˈsjem.pɾe', vi:'luôn luôn', pos:'trạng từ', g:'' },
{ es:'nunca', ipa:'ˈnuŋ.ka', vi:'không bao giờ', pos:'trạng từ', g:'' },
{ es:'a veces', ipa:'a ˈβe.ses', vi:'đôi khi', pos:'trạng từ', g:'' },
{ es:'ahora', ipa:'aˈo.ɾa', vi:'bây giờ', pos:'trạng từ', g:'' },
{ es:'luego', ipa:'ˈlwe.ɣo', vi:'sau đó', pos:'trạng từ', g:'' },
{ es:'después', ipa:'desˈpwes', vi:'sau, sau đó', pos:'trạng từ', g:'' },
{ es:'antes', ipa:'ˈan.tes', vi:'trước', pos:'trạng từ', g:'' },
{ es:'entonces', ipa:'enˈton.ses', vi:'thế thì, lúc đó', pos:'trạng từ', g:'' },
{ es:'aquí', ipa:'aˈki', vi:'ở đây', pos:'trạng từ', g:'' },
{ es:'ahí', ipa:'aˈi', vi:'ở đó', pos:'trạng từ', g:'' },
{ es:'allí', ipa:'aˈʝi', vi:'ở kia', pos:'trạng từ', g:'' },
{ es:'cerca', ipa:'ˈseɾ.ka', vi:'gần', pos:'trạng từ', g:'' },
{ es:'lejos', ipa:'ˈle.xos', vi:'xa', pos:'trạng từ', g:'' },
{ es:'dentro', ipa:'ˈden.tɾo', vi:'bên trong', pos:'trạng từ', g:'' },
{ es:'fuera', ipa:'ˈfwe.ɾa', vi:'bên ngoài', pos:'trạng từ', g:'' },
{ es:'arriba', ipa:'aˈri.βa', vi:'ở trên', pos:'trạng từ', g:'' },
{ es:'abajo', ipa:'aˈβa.xo', vi:'ở dưới', pos:'trạng từ', g:'' },
{ es:'bien', ipa:'bjen', vi:'tốt, ổn', pos:'trạng từ', g:'' },
{ es:'mal', ipa:'mal', vi:'tệ', pos:'trạng từ', g:'' },
{ es:'mejor', ipa:'meˈxoɾ', vi:'tốt hơn', pos:'trạng từ', g:'' },
{ es:'peor', ipa:'peˈoɾ', vi:'tệ hơn', pos:'trạng từ', g:'' },
{ es:'rápido', ipa:'ˈra.pi.ðo', vi:'nhanh', pos:'trạng từ', g:'' },
{ es:'despacio', ipa:'desˈpa.sjo', vi:'chậm', pos:'trạng từ', g:'' },
{ es:'juntos', ipa:'ˈxun.tos', vi:'cùng nhau', pos:'trạng từ', g:'' },
{ es:'quizá', ipa:'kiˈsa', vi:'có lẽ', pos:'trạng từ', g:'' },
{ es:'claro', ipa:'ˈkla.ɾo', vi:'rõ; tất nhiên', pos:'trạng từ', g:'' },

/* ---------- ĐỘNG TỪ LÕI ---------- */
{ es:'ser', ipa:'seɾ', vi:'là (bản chất)', pos:'động từ', g:'', note:'soy, eres, es, somos, sois, son. Dùng cho thứ không đổi: nghề, quốc tịch, tính cách, giờ.' },
{ es:'estar', ipa:'esˈtaɾ', vi:'ở, đang (trạng thái)', pos:'động từ', g:'', note:'estoy, estás, está, estamos, estáis, están. Dùng cho vị trí và trạng thái tạm thời. Es guapo là đẹp sẵn; está guapo là hôm nay trông đẹp.' },
{ es:'haber', ipa:'aˈβeɾ', vi:'có (trợ động từ)', pos:'động từ', g:'', note:'Trợ động từ của thời hoàn thành: he comido. Dạng hay là «có tồn tại»: hay.' },
{ es:'tener', ipa:'teˈneɾ', vi:'có, sở hữu', pos:'động từ', g:'', note:'tengo, tienes, tiene, tenemos, tenéis, tienen. Dùng cho tuổi và cảm giác: tengo veinte años, tengo hambre.' },
{ es:'hacer', ipa:'aˈseɾ', vi:'làm, chế tạo', pos:'động từ', g:'', note:'hago, haces, hace. Quá khứ phân từ bất quy tắc: hecho. Dùng cho thời tiết: hace frío.' },
{ es:'ir', ipa:'iɾ', vi:'đi', pos:'động từ', g:'', note:'voy, vas, va, vamos, vais, van — chẳng còn dính gì tới nguyên mẫu. Ir a + nguyên mẫu là tương lai gần.' },
{ es:'decir', ipa:'deˈsiɾ', vi:'nói, bảo', pos:'động từ', g:'', note:'digo, dices, dice. Quá khứ phân từ dicho.' },
{ es:'poder', ipa:'poˈðeɾ', vi:'có thể', pos:'động từ', g:'', note:'puedo, puedes, puede — o đổi thành ue khi có trọng âm.' },
{ es:'querer', ipa:'keˈɾeɾ', vi:'muốn; yêu', pos:'động từ', g:'', note:'quiero, quieres, quiere. Te quiero là câu tỏ tình thường ngày của người Tây Ban Nha.' },
{ es:'deber', ipa:'deˈβeɾ', vi:'phải; nợ', pos:'động từ', g:'' },
{ es:'saber', ipa:'saˈβeɾ', vi:'biết (kiến thức)', pos:'động từ', g:'', note:'sé, sabes, sabe. Biết người, biết chỗ thì dùng conocer.' },
{ es:'conocer', ipa:'ko.noˈseɾ', vi:'biết, quen', pos:'động từ', g:'', note:'Ngôi thứ nhất thêm z: conozco.' },
{ es:'ver', ipa:'beɾ', vi:'thấy, xem', pos:'động từ', g:'', note:'veo, ves, ve. Quá khứ phân từ visto.' },
{ es:'venir', ipa:'beˈniɾ', vi:'đến', pos:'động từ', g:'', note:'vengo, vienes, viene.' },
{ es:'dar', ipa:'daɾ', vi:'cho, đưa', pos:'động từ', g:'', note:'doy, das, da.' },
{ es:'poner', ipa:'poˈneɾ', vi:'đặt, để', pos:'động từ', g:'', note:'pongo, pones, pone. Quá khứ phân từ puesto.' },
{ es:'llevar', ipa:'ʝeˈβaɾ', vi:'mang, đem; mặc', pos:'động từ', g:'' },
{ es:'traer', ipa:'tɾaˈeɾ', vi:'mang đến', pos:'động từ', g:'', note:'Llevar là đem đi khỏi đây; traer là đem về đây.' },
{ es:'salir', ipa:'saˈliɾ', vi:'ra, đi ra', pos:'động từ', g:'', note:'salgo, sales, sale.' },
{ es:'llegar', ipa:'ʝeˈɣaɾ', vi:'đến, tới', pos:'động từ', g:'' },
{ es:'entrar', ipa:'enˈtɾaɾ', vi:'vào', pos:'động từ', g:'' },
{ es:'volver', ipa:'bolˈβeɾ', vi:'trở lại', pos:'động từ', g:'', note:'Quá khứ phân từ vuelto.' },
{ es:'quedar', ipa:'keˈðaɾ', vi:'ở lại; còn lại; hẹn', pos:'động từ', g:'' },
{ es:'pasar', ipa:'paˈsaɾ', vi:'đi qua; xảy ra', pos:'động từ', g:'' },
{ es:'hablar', ipa:'aˈβlaɾ', vi:'nói, nói chuyện', pos:'động từ', g:'' },
{ es:'preguntar', ipa:'pɾe.ɣunˈtaɾ', vi:'hỏi', pos:'động từ', g:'' },
{ es:'contestar', ipa:'kon.tesˈtaɾ', vi:'trả lời', pos:'động từ', g:'' },
{ es:'llamar', ipa:'ʝaˈmaɾ', vi:'gọi', pos:'động từ', g:'', note:'Dạng phản thân llamarse dùng để nói tên: me llamo Quan.' },
{ es:'escuchar', ipa:'es.kuˈtʃaɾ', vi:'nghe', pos:'động từ', g:'' },
{ es:'oír', ipa:'oˈiɾ', vi:'nghe thấy', pos:'động từ', g:'', note:'oigo, oyes, oye.' },
{ es:'mirar', ipa:'miˈɾaɾ', vi:'nhìn', pos:'động từ', g:'' },
{ es:'leer', ipa:'leˈeɾ', vi:'đọc', pos:'động từ', g:'' },
{ es:'escribir', ipa:'es.kɾiˈβiɾ', vi:'viết', pos:'động từ', g:'', note:'Quá khứ phân từ escrito.' },
{ es:'comer', ipa:'koˈmeɾ', vi:'ăn', pos:'động từ', g:'' },
{ es:'beber', ipa:'beˈβeɾ', vi:'uống', pos:'động từ', g:'' },
{ es:'dormir', ipa:'doɾˈmiɾ', vi:'ngủ', pos:'động từ', g:'', note:'duermo, duermes, duerme.' },
{ es:'trabajar', ipa:'tɾa.βaˈxaɾ', vi:'làm việc', pos:'động từ', g:'' },
{ es:'vivir', ipa:'biˈβiɾ', vi:'sống, ở', pos:'động từ', g:'' },
{ es:'estudiar', ipa:'es.tuˈðjaɾ', vi:'học', pos:'động từ', g:'' },
{ es:'aprender', ipa:'a.pɾenˈdeɾ', vi:'học được', pos:'động từ', g:'' },
{ es:'enseñar', ipa:'en.seˈɲaɾ', vi:'dạy; cho xem', pos:'động từ', g:'' },
{ es:'entender', ipa:'en.tenˈdeɾ', vi:'hiểu', pos:'động từ', g:'', note:'entiendo, entiendes, entiende.' },
{ es:'comprar', ipa:'komˈpɾaɾ', vi:'mua', pos:'động từ', g:'' },
{ es:'vender', ipa:'benˈdeɾ', vi:'bán', pos:'động từ', g:'' },
{ es:'pagar', ipa:'paˈɣaɾ', vi:'trả tiền', pos:'động từ', g:'' },
{ es:'costar', ipa:'kosˈtaɾ', vi:'có giá', pos:'động từ', g:'', note:'cuesta, cuestan — chỉ dùng ngôi thứ ba.' },
{ es:'gastar', ipa:'ɣasˈtaɾ', vi:'chi, tiêu', pos:'động từ', g:'' },
{ es:'empezar', ipa:'em.peˈsaɾ', vi:'bắt đầu', pos:'động từ', g:'', note:'empiezo, empiezas, empieza.' },
{ es:'terminar', ipa:'teɾ.miˈnaɾ', vi:'kết thúc', pos:'động từ', g:'' },
{ es:'acabar', ipa:'a.kaˈβaɾ', vi:'xong; vừa mới', pos:'động từ', g:'', note:'Acabar de + nguyên mẫu nghĩa là «vừa mới»: acabo de llegar.' },
{ es:'seguir', ipa:'seˈɣiɾ', vi:'theo; tiếp tục', pos:'động từ', g:'', note:'sigo, sigues, sigue.' },
{ es:'esperar', ipa:'es.peˈɾaɾ', vi:'chờ; hi vọng', pos:'động từ', g:'', note:'Một chữ cho cả «chờ» lẫn «hi vọng» — ngữ cảnh phân biệt.' },
{ es:'buscar', ipa:'busˈkaɾ', vi:'tìm', pos:'động từ', g:'' },
{ es:'encontrar', ipa:'eŋ.konˈtɾaɾ', vi:'tìm thấy; gặp', pos:'động từ', g:'', note:'encuentro, encuentras, encuentra.' },
{ es:'perder', ipa:'peɾˈðeɾ', vi:'mất; thua; nhỡ', pos:'động từ', g:'' },
{ es:'ganar', ipa:'ɣaˈnaɾ', vi:'thắng; kiếm được', pos:'động từ', g:'' },
{ es:'olvidar', ipa:'ol.βiˈðaɾ', vi:'quên', pos:'động từ', g:'' },
{ es:'recordar', ipa:'re.koɾˈðaɾ', vi:'nhớ; nhắc', pos:'động từ', g:'' },
{ es:'pensar', ipa:'penˈsaɾ', vi:'nghĩ', pos:'động từ', g:'', note:'pienso, piensas, piensa.' },
{ es:'creer', ipa:'kɾeˈeɾ', vi:'tin', pos:'động từ', g:'' },
{ es:'parecer', ipa:'pa.ɾeˈseɾ', vi:'trông như', pos:'động từ', g:'' },
{ es:'gustar', ipa:'ɣusˈtaɾ', vi:'làm vừa ý', pos:'động từ', g:'', note:'Câu lộn ngược so với tiếng Việt: me gusta el café nghĩa là «cà phê làm tôi vừa ý». Chủ ngữ là cà phê.' },
{ es:'necesitar', ipa:'ne.se.siˈtaɾ', vi:'cần', pos:'động từ', g:'' },
{ es:'ayudar', ipa:'a.ʝuˈðaɾ', vi:'giúp', pos:'động từ', g:'' },
{ es:'usar', ipa:'uˈsaɾ', vi:'dùng', pos:'động từ', g:'' },
{ es:'probar', ipa:'pɾoˈβaɾ', vi:'thử; nếm', pos:'động từ', g:'' },
{ es:'intentar', ipa:'in.tenˈtaɾ', vi:'cố, thử', pos:'động từ', g:'' },
{ es:'lograr', ipa:'loˈɣɾaɾ', vi:'đạt được', pos:'động từ', g:'' },
{ es:'cambiar', ipa:'kamˈbjaɾ', vi:'thay đổi', pos:'động từ', g:'' },
{ es:'abrir', ipa:'aˈβɾiɾ', vi:'mở', pos:'động từ', g:'', note:'Quá khứ phân từ abierto.' },
{ es:'cerrar', ipa:'seˈraɾ', vi:'đóng', pos:'động từ', g:'', note:'cierro, cierras, cierra.' },
{ es:'elegir', ipa:'e.leˈxiɾ', vi:'chọn', pos:'động từ', g:'' },
{ es:'guardar', ipa:'ɣwaɾˈðaɾ', vi:'giữ, cất', pos:'động từ', g:'' },
{ es:'dejar', ipa:'deˈxaɾ', vi:'để lại; cho phép; thôi', pos:'động từ', g:'' },
{ es:'tomar', ipa:'toˈmaɾ', vi:'lấy; uống; đi (xe)', pos:'động từ', g:'' },
{ es:'coger', ipa:'koˈxeɾ', vi:'lấy, bắt', pos:'động từ', g:'', note:'Ở Tây Ban Nha rất thông dụng, nhưng ở nhiều nước Mỹ Latin lại là từ thô — bên đó dùng tomar.' },
{ es:'sentir', ipa:'senˈtiɾ', vi:'cảm thấy; lấy làm tiếc', pos:'động từ', g:'', note:'Lo siento nghĩa là «tôi xin lỗi».' },
{ es:'mover', ipa:'moˈβeɾ', vi:'di chuyển', pos:'động từ', g:'' },
{ es:'andar', ipa:'anˈdaɾ', vi:'đi bộ; chạy được', pos:'động từ', g:'' },
{ es:'caminar', ipa:'ka.miˈnaɾ', vi:'đi bộ', pos:'động từ', g:'' },
{ es:'correr', ipa:'koˈreɾ', vi:'chạy', pos:'động từ', g:'' },
{ es:'subir', ipa:'suˈβiɾ', vi:'lên', pos:'động từ', g:'' },
{ es:'bajar', ipa:'baˈxaɾ', vi:'xuống; tải về', pos:'động từ', g:'' },
{ es:'viajar', ipa:'bjaˈxaɾ', vi:'du lịch', pos:'động từ', g:'' },
{ es:'visitar', ipa:'bi.siˈtaɾ', vi:'thăm', pos:'động từ', g:'' },
{ es:'jugar', ipa:'xuˈɣaɾ', vi:'chơi', pos:'động từ', g:'', note:'juego, juegas, juega — u đổi thành ue, trường hợp duy nhất trong tiếng Tây Ban Nha.' },
{ es:'cantar', ipa:'kanˈtaɾ', vi:'hát', pos:'động từ', g:'' },
{ es:'bailar', ipa:'bajˈlaɾ', vi:'nhảy, múa', pos:'động từ', g:'' },
{ es:'cocinar', ipa:'ko.siˈnaɾ', vi:'nấu ăn', pos:'động từ', g:'' },
{ es:'limpiar', ipa:'limˈpjaɾ', vi:'dọn, lau', pos:'động từ', g:'' },
{ es:'lavar', ipa:'laˈβaɾ', vi:'giặt, rửa', pos:'động từ', g:'' },
{ es:'arreglar', ipa:'a.reˈɣlaɾ', vi:'sửa; xếp gọn', pos:'động từ', g:'' },
{ es:'construir', ipa:'kons.tɾuˈiɾ', vi:'xây', pos:'động từ', g:'' },
{ es:'crear', ipa:'kɾeˈaɾ', vi:'tạo ra', pos:'động từ', g:'' },
{ es:'enviar', ipa:'em.bjaɾ', vi:'gửi', pos:'động từ', g:'' },
{ es:'mandar', ipa:'manˈdaɾ', vi:'gửi; ra lệnh', pos:'động từ', g:'' },
{ es:'recibir', ipa:'re.siˈβiɾ', vi:'nhận', pos:'động từ', g:'' },
{ es:'explicar', ipa:'eks.pliˈkaɾ', vi:'giải thích', pos:'động từ', g:'' },
{ es:'contar', ipa:'konˈtaɾ', vi:'kể; đếm', pos:'động từ', g:'', note:'cuento, cuentas, cuenta.' },
{ es:'mostrar', ipa:'mosˈtɾaɾ', vi:'cho xem', pos:'động từ', g:'' },
{ es:'decidir', ipa:'de.siˈðiɾ', vi:'quyết định', pos:'động từ', g:'' },
{ es:'preferir', ipa:'pɾe.feˈɾiɾ', vi:'thích hơn', pos:'động từ', g:'' },
{ es:'aceptar', ipa:'a.sepˈtaɾ', vi:'chấp nhận', pos:'động từ', g:'' },
{ es:'permitir', ipa:'peɾ.miˈtiɾ', vi:'cho phép', pos:'động từ', g:'' },
{ es:'reservar', ipa:'re.seɾˈβaɾ', vi:'đặt trước', pos:'động từ', g:'' },
{ es:'alquilar', ipa:'al.kiˈlaɾ', vi:'thuê', pos:'động từ', g:'' },
{ es:'servir', ipa:'seɾˈβiɾ', vi:'phục vụ; dùng để', pos:'động từ', g:'' },
{ es:'llover', ipa:'ʝoˈβeɾ', vi:'mưa', pos:'động từ', g:'', note:'Chỉ có llueve — không có ngôi nào khác.' },
{ es:'nevar', ipa:'neˈβaɾ', vi:'có tuyết', pos:'động từ', g:'' },
{ es:'nacer', ipa:'naˈseɾ', vi:'sinh ra', pos:'động từ', g:'' },
{ es:'morir', ipa:'moˈɾiɾ', vi:'chết', pos:'động từ', g:'', note:'Quá khứ phân từ muerto.' },
{ es:'crecer', ipa:'kɾeˈseɾ', vi:'lớn lên', pos:'động từ', g:'' },
{ es:'convertir', ipa:'kom.beɾˈtiɾ', vi:'biến thành', pos:'động từ', g:'' },
{ es:'añadir', ipa:'a.ɲaˈðiɾ', vi:'thêm', pos:'động từ', g:'' },
{ es:'quitar', ipa:'kiˈtaɾ', vi:'bỏ ra, cất đi', pos:'động từ', g:'' },
{ es:'rellenar', ipa:'re.ʝeˈnaɾ', vi:'điền vào', pos:'động từ', g:'' },
{ es:'firmar', ipa:'fiɾˈmaɾ', vi:'kí', pos:'động từ', g:'' },
{ es:'apuntar', ipa:'a.punˈtaɾ', vi:'ghi lại', pos:'động từ', g:'' },
{ es:'medir', ipa:'meˈðiɾ', vi:'đo', pos:'động từ', g:'' },
{ es:'pesar', ipa:'peˈsaɾ', vi:'cân', pos:'động từ', g:'' },
{ es:'contener', ipa:'kon.teˈneɾ', vi:'chứa', pos:'động từ', g:'' },
{ es:'valer', ipa:'baˈleɾ', vi:'đáng giá', pos:'động từ', g:'', note:'Vale là tiếng «được, ok» nghe thường xuyên nhất ở Tây Ban Nha.' },
{ es:'bastar', ipa:'basˈtaɾ', vi:'đủ', pos:'động từ', g:'' },
{ es:'doler', ipa:'doˈleɾ', vi:'đau', pos:'động từ', g:'', note:'Cấu trúc lộn ngược như gustar: me duele la cabeza.' },
{ es:'reír', ipa:'reˈiɾ', vi:'cười', pos:'động từ', g:'' },
{ es:'levantar', ipa:'le.βanˈtaɾ', vi:'nâng lên; thức dậy', pos:'động từ', g:'' },
{ es:'sentar', ipa:'senˈtaɾ', vi:'ngồi', pos:'động từ', g:'' },
{ es:'parar', ipa:'paˈɾaɾ', vi:'dừng', pos:'động từ', g:'' },
{ es:'revisar', ipa:'re.βiˈsaɾ', vi:'xem lại, kiểm tra', pos:'động từ', g:'' },
{ es:'repetir', ipa:'re.peˈtiɾ', vi:'nhắc lại', pos:'động từ', g:'' },
{ es:'llorar', ipa:'ʝoˈɾaɾ', vi:'khóc', pos:'động từ', g:'' },
{ es:'dirigir', ipa:'di.ɾiˈxiɾ', vi:'điều hành; hướng về', pos:'động từ', g:'' },

/* ---------- DANH TỪ LÕI ---------- */
{ es:'día', ipa:'ˈdi.a', vi:'ngày', pos:'danh từ', g:'m', note:'Tận cùng bằng a mà là giống đực — el día. Ngoại lệ phải nhớ.' },
{ es:'semana', ipa:'seˈma.na', vi:'tuần', pos:'danh từ', g:'f' },
{ es:'mes', ipa:'mes', vi:'tháng', pos:'danh từ', g:'m' },
{ es:'año', ipa:'ˈa.ɲo', vi:'năm', pos:'danh từ', g:'m' },
{ es:'hora', ipa:'ˈo.ɾa', vi:'giờ, tiếng', pos:'danh từ', g:'f' },
{ es:'minuto', ipa:'miˈnu.to', vi:'phút', pos:'danh từ', g:'m' },
{ es:'tiempo', ipa:'ˈtjem.po', vi:'thời gian; thời tiết', pos:'danh từ', g:'m', note:'Một chữ cho hai nghĩa: no tengo tiempo và ¿qué tiempo hace?' },
{ es:'vez', ipa:'bes', vi:'lần', pos:'danh từ', g:'f', note:'Số nhiều veces — z đổi thành c.' },
{ es:'mañana', ipa:'maˈɲa.na', vi:'buổi sáng; ngày mai', pos:'danh từ', g:'f', note:'La mañana là buổi sáng; mañana trơ trọi là ngày mai.' },
{ es:'tarde', ipa:'ˈtaɾ.ðe', vi:'buổi chiều; muộn', pos:'danh từ', g:'f' },
{ es:'noche', ipa:'ˈno.tʃe', vi:'buổi đêm', pos:'danh từ', g:'f' },
{ es:'hoy', ipa:'oj', vi:'hôm nay', pos:'trạng từ', g:'' },
{ es:'ayer', ipa:'aˈʝeɾ', vi:'hôm qua', pos:'trạng từ', g:'' },
{ es:'persona', ipa:'peɾˈso.na', vi:'người', pos:'danh từ', g:'f', note:'Luôn giống cái, kể cả khi chỉ đàn ông.' },
{ es:'gente', ipa:'ˈxen.te', vi:'người ta, mọi người', pos:'danh từ', g:'f', note:'Số ít nhưng nghĩa số nhiều: la gente dice.' },
{ es:'hombre', ipa:'ˈom.bɾe', vi:'người đàn ông', pos:'danh từ', g:'m' },
{ es:'mujer', ipa:'muˈxeɾ', vi:'người phụ nữ; vợ', pos:'danh từ', g:'f' },
{ es:'niño', ipa:'ˈni.ɲo', vi:'đứa trẻ, bé trai', pos:'danh từ', g:'m' },
{ es:'niña', ipa:'ˈni.ɲa', vi:'bé gái', pos:'danh từ', g:'f' },
{ es:'chico', ipa:'ˈtʃi.ko', vi:'cậu trai', pos:'danh từ', g:'m' },
{ es:'chica', ipa:'ˈtʃi.ka', vi:'cô gái', pos:'danh từ', g:'f' },
{ es:'amigo', ipa:'aˈmi.ɣo', vi:'người bạn', pos:'danh từ', g:'m' },
{ es:'amiga', ipa:'aˈmi.ɣa', vi:'người bạn gái', pos:'danh từ', g:'f' },
{ es:'familia', ipa:'faˈmi.lja', vi:'gia đình', pos:'danh từ', g:'f' },
{ es:'padre', ipa:'ˈpa.ðɾe', vi:'bố', pos:'danh từ', g:'m', note:'Số nhiều padres nghĩa là «bố mẹ».' },
{ es:'madre', ipa:'ˈma.ðɾe', vi:'mẹ', pos:'danh từ', g:'f' },
{ es:'hijo', ipa:'ˈi.xo', vi:'con trai', pos:'danh từ', g:'m' },
{ es:'hija', ipa:'ˈi.xa', vi:'con gái', pos:'danh từ', g:'f' },
{ es:'hermano', ipa:'eɾˈma.no', vi:'anh, em trai', pos:'danh từ', g:'m' },
{ es:'hermana', ipa:'eɾˈma.na', vi:'chị, em gái', pos:'danh từ', g:'f' },
{ es:'abuelo', ipa:'aˈβwe.lo', vi:'ông', pos:'danh từ', g:'m' },
{ es:'señor', ipa:'seˈɲoɾ', vi:'ông, ngài', pos:'danh từ', g:'m' },
{ es:'señora', ipa:'seˈɲo.ɾa', vi:'bà', pos:'danh từ', g:'f' },
{ es:'cosa', ipa:'ˈko.sa', vi:'thứ, việc', pos:'danh từ', g:'f' },
{ es:'casa', ipa:'ˈka.sa', vi:'nhà', pos:'danh từ', g:'f', note:'En casa (không mạo từ) nghĩa là «ở nhà».' },
{ es:'piso', ipa:'ˈpi.so', vi:'căn hộ; tầng', pos:'danh từ', g:'m' },
{ es:'habitación', ipa:'a.βi.taˈsjon', vi:'phòng', pos:'danh từ', g:'f' },
{ es:'puerta', ipa:'ˈpweɾ.ta', vi:'cửa', pos:'danh từ', g:'f' },
{ es:'mesa', ipa:'ˈme.sa', vi:'bàn', pos:'danh từ', g:'f' },
{ es:'silla', ipa:'ˈsi.ʝa', vi:'ghế', pos:'danh từ', g:'f' },
{ es:'calle', ipa:'ˈka.ʝe', vi:'phố', pos:'danh từ', g:'f' },
{ es:'ciudad', ipa:'sjuˈðað', vi:'thành phố', pos:'danh từ', g:'f' },
{ es:'país', ipa:'paˈis', vi:'nước, quốc gia', pos:'danh từ', g:'m' },
{ es:'mundo', ipa:'ˈmun.do', vi:'thế giới', pos:'danh từ', g:'m' },
{ es:'lugar', ipa:'luˈɣaɾ', vi:'chỗ, nơi', pos:'danh từ', g:'m' },
{ es:'sitio', ipa:'ˈsi.tjo', vi:'chỗ', pos:'danh từ', g:'m' },
{ es:'parte', ipa:'ˈpaɾ.te', vi:'phần', pos:'danh từ', g:'f' },
{ es:'lado', ipa:'ˈla.ðo', vi:'phía, bên', pos:'danh từ', g:'m' },
{ es:'escuela', ipa:'esˈkwe.la', vi:'trường học', pos:'danh từ', g:'f' },
{ es:'clase', ipa:'ˈkla.se', vi:'lớp; giờ học; loại', pos:'danh từ', g:'f' },
{ es:'trabajo', ipa:'tɾaˈβa.xo', vi:'công việc', pos:'danh từ', g:'m' },
{ es:'oficina', ipa:'o.fiˈsi.na', vi:'văn phòng', pos:'danh từ', g:'f' },
{ es:'libro', ipa:'ˈli.βɾo', vi:'quyển sách', pos:'danh từ', g:'m' },
{ es:'palabra', ipa:'paˈla.βɾa', vi:'từ, lời', pos:'danh từ', g:'f' },
{ es:'idioma', ipa:'iˈðjo.ma', vi:'ngôn ngữ', pos:'danh từ', g:'m', note:'Tận cùng bằng a mà giống đực — gốc Hy Lạp, như problema, tema.' },
{ es:'lengua', ipa:'ˈleŋ.ɡwa', vi:'tiếng; cái lưỡi', pos:'danh từ', g:'f' },
{ es:'pregunta', ipa:'pɾeˈɣun.ta', vi:'câu hỏi', pos:'danh từ', g:'f' },
{ es:'respuesta', ipa:'resˈpwes.ta', vi:'câu trả lời', pos:'danh từ', g:'f' },
{ es:'problema', ipa:'pɾoˈβle.ma', vi:'vấn đề', pos:'danh từ', g:'m' },
{ es:'ejemplo', ipa:'eˈxem.plo', vi:'ví dụ', pos:'danh từ', g:'m' },
{ es:'razón', ipa:'raˈson', vi:'lí do; lẽ phải', pos:'danh từ', g:'f', note:'Tener razón nghĩa là «nói đúng».' },
{ es:'idea', ipa:'iˈðe.a', vi:'ý tưởng', pos:'danh từ', g:'f' },
{ es:'vida', ipa:'ˈbi.ða', vi:'đời, cuộc sống', pos:'danh từ', g:'f' },
{ es:'mano', ipa:'ˈma.no', vi:'bàn tay', pos:'danh từ', g:'f', note:'Tận cùng bằng o mà giống cái — la mano.' },
{ es:'cabeza', ipa:'kaˈβe.sa', vi:'cái đầu', pos:'danh từ', g:'f' },
{ es:'ojo', ipa:'ˈo.xo', vi:'con mắt', pos:'danh từ', g:'m' },
{ es:'pie', ipa:'pje', vi:'bàn chân', pos:'danh từ', g:'m' },
{ es:'agua', ipa:'ˈa.ɣwa', vi:'nước', pos:'danh từ', g:'f', note:'Giống cái nhưng đi với el (el agua) để tránh hai chữ a dính nhau; tính từ vẫn hợp giống cái: el agua fría.' },
{ es:'pan', ipa:'pan', vi:'bánh mì', pos:'danh từ', g:'m' },
{ es:'café', ipa:'kaˈfe', vi:'cà phê; quán cà phê', pos:'danh từ', g:'m' },
{ es:'comida', ipa:'koˈmi.ða', vi:'đồ ăn; bữa trưa', pos:'danh từ', g:'f' },
{ es:'dinero', ipa:'diˈne.ɾo', vi:'tiền', pos:'danh từ', g:'m' },
{ es:'precio', ipa:'ˈpɾe.sjo', vi:'giá', pos:'danh từ', g:'m' },
{ es:'euro', ipa:'ˈew.ɾo', vi:'đồng euro', pos:'danh từ', g:'m' },
{ es:'tren', ipa:'tɾen', vi:'tàu hoả', pos:'danh từ', g:'m' },
{ es:'coche', ipa:'ˈko.tʃe', vi:'xe hơi', pos:'danh từ', g:'m', note:'Ở Mỹ Latin thường gọi là carro hoặc auto.' },
{ es:'perro', ipa:'ˈpe.ro', vi:'con chó', pos:'danh từ', g:'m', note:'rr rung kép — khác hẳn pero «nhưng».' },
{ es:'gato', ipa:'ˈɣa.to', vi:'con mèo', pos:'danh từ', g:'m' },
{ es:'nombre', ipa:'ˈnom.bɾe', vi:'tên', pos:'danh từ', g:'m' },
{ es:'número', ipa:'ˈnu.me.ɾo', vi:'số', pos:'danh từ', g:'m' },
{ es:'fin', ipa:'fin', vi:'sự kết thúc', pos:'danh từ', g:'m' },
{ es:'final', ipa:'fiˈnal', vi:'phần cuối; cuối cùng', pos:'danh từ', g:'m' },
{ es:'principio', ipa:'pɾinˈsi.pjo', vi:'lúc đầu; nguyên tắc', pos:'danh từ', g:'m' },
{ es:'punto', ipa:'ˈpun.to', vi:'điểm; dấu chấm', pos:'danh từ', g:'m' },
{ es:'forma', ipa:'ˈfoɾ.ma', vi:'hình thức, cách', pos:'danh từ', g:'f' },
{ es:'manera', ipa:'maˈne.ɾa', vi:'cách', pos:'danh từ', g:'f' },
{ es:'falta', ipa:'ˈfal.ta', vi:'sự thiếu; lỗi', pos:'danh từ', g:'f', note:'Hacer falta nghĩa là «cần»; a falta de nghĩa là «vì thiếu».' },
{ es:'ganas', ipa:'ˈɣa.nas', vi:'sự muốn, hứng', pos:'danh từ', g:'f', note:'Tener ganas de nghĩa là «muốn, có hứng».' },
{ es:'hambre', ipa:'ˈam.bɾe', vi:'cơn đói', pos:'danh từ', g:'f' },
{ es:'sed', ipa:'seð', vi:'cơn khát', pos:'danh từ', g:'f' },
{ es:'suerte', ipa:'ˈsweɾ.te', vi:'sự may mắn', pos:'danh từ', g:'f' },
{ es:'cuenta', ipa:'ˈkwen.ta', vi:'hoá đơn; tài khoản', pos:'danh từ', g:'f' },

/* ---------- TÍNH TỪ LÕI ---------- */
{ es:'grande', ipa:'ˈɣɾan.de', vi:'to, lớn', pos:'tính từ', g:'', note:'Rút thành gran khi đứng trước danh từ số ít: un gran libro.' },
{ es:'pequeño', ipa:'peˈke.ɲo', vi:'nhỏ', pos:'tính từ', g:'' },
{ es:'bueno', ipa:'ˈbwe.no', vi:'tốt, ngon', pos:'tính từ', g:'', note:'Rút thành buen trước danh từ giống đực: un buen día.' },
{ es:'malo', ipa:'ˈma.lo', vi:'tệ, xấu', pos:'tính từ', g:'', note:'Rút thành mal trước danh từ giống đực.' },
{ es:'nuevo', ipa:'ˈnwe.βo', vi:'mới', pos:'tính từ', g:'' },
{ es:'viejo', ipa:'ˈbje.xo', vi:'già, cũ', pos:'tính từ', g:'' },
{ es:'joven', ipa:'ˈxo.βen', vi:'trẻ', pos:'tính từ', g:'' },
{ es:'bonito', ipa:'boˈni.to', vi:'đẹp, xinh', pos:'tính từ', g:'' },
{ es:'guapo', ipa:'ˈɣwa.po', vi:'đẹp (người)', pos:'tính từ', g:'' },
{ es:'feo', ipa:'ˈfe.o', vi:'xấu (nhìn)', pos:'tính từ', g:'' },
{ es:'largo', ipa:'ˈlaɾ.ɣo', vi:'dài', pos:'tính từ', g:'', note:'Bạn giả: largo là «dài», không phải «lớn».' },
{ es:'corto', ipa:'ˈkoɾ.to', vi:'ngắn', pos:'tính từ', g:'' },
{ es:'alto', ipa:'ˈal.to', vi:'cao', pos:'tính từ', g:'' },
{ es:'caliente', ipa:'kaˈljen.te', vi:'nóng', pos:'tính từ', g:'' },
{ es:'frío', ipa:'ˈfɾi.o', vi:'lạnh', pos:'tính từ', g:'' },
{ es:'fácil', ipa:'ˈfa.sil', vi:'dễ', pos:'tính từ', g:'' },
{ es:'difícil', ipa:'diˈfi.sil', vi:'khó', pos:'tính từ', g:'' },
{ es:'caro', ipa:'ˈka.ɾo', vi:'đắt', pos:'tính từ', g:'' },
{ es:'barato', ipa:'baˈɾa.to', vi:'rẻ', pos:'tính từ', g:'' },
{ es:'gratis', ipa:'ˈɣɾa.tis', vi:'miễn phí', pos:'tính từ', g:'' },
{ es:'contento', ipa:'konˈten.to', vi:'vui, hài lòng', pos:'tính từ', g:'' },
{ es:'feliz', ipa:'feˈlis', vi:'hạnh phúc', pos:'tính từ', g:'' },
{ es:'triste', ipa:'ˈtɾis.te', vi:'buồn', pos:'tính từ', g:'' },
{ es:'cansado', ipa:'kanˈsa.ðo', vi:'mệt', pos:'tính từ', g:'' },
{ es:'enfermo', ipa:'emˈfeɾ.mo', vi:'ốm', pos:'tính từ', g:'' },
{ es:'listo', ipa:'ˈlis.to', vi:'sẵn sàng; thông minh', pos:'tính từ', g:'', note:'Với estar là «sẵn sàng», với ser là «thông minh».' },
{ es:'posible', ipa:'poˈsi.βle', vi:'có thể được', pos:'tính từ', g:'' },
{ es:'verdadero', ipa:'beɾ.ðaˈðe.ɾo', vi:'thật', pos:'tính từ', g:'' },
{ es:'falso', ipa:'ˈfal.so', vi:'sai, giả', pos:'tính từ', g:'' },
{ es:'importante', ipa:'im.poɾˈtan.te', vi:'quan trọng', pos:'tính từ', g:'' },
{ es:'primero', ipa:'pɾiˈme.ɾo', vi:'thứ nhất', pos:'tính từ', g:'', note:'Rút thành primer trước danh từ giống đực.' },
{ es:'segundo', ipa:'seˈɣun.do', vi:'thứ hai; giây', pos:'tính từ', g:'' },
{ es:'último', ipa:'ˈul.ti.mo', vi:'cuối cùng', pos:'tính từ', g:'' },
{ es:'próximo', ipa:'ˈpɾok.si.mo', vi:'kế tiếp', pos:'tính từ', g:'' },
{ es:'solo', ipa:'ˈso.lo', vi:'một mình', pos:'tính từ', g:'' },
{ es:'lleno', ipa:'ˈʝe.no', vi:'đầy', pos:'tính từ', g:'' },
{ es:'vacío', ipa:'baˈsi.o', vi:'trống', pos:'tính từ', g:'' },
{ es:'limpio', ipa:'ˈlim.pjo', vi:'sạch', pos:'tính từ', g:'' },
{ es:'sucio', ipa:'ˈsu.sjo', vi:'bẩn', pos:'tính từ', g:'' },
{ es:'fuerte', ipa:'ˈfweɾ.te', vi:'mạnh', pos:'tính từ', g:'' },
{ es:'amable', ipa:'aˈma.βle', vi:'tử tế', pos:'tính từ', g:'' },
{ es:'seguro', ipa:'seˈɣu.ɾo', vi:'chắc chắn; an toàn', pos:'tính từ', g:'' },
{ es:'español', ipa:'es.paˈɲol', vi:'tiếng Tây Ban Nha; người Tây Ban Nha', pos:'tính từ', g:'', note:'Tên tiếng và dân tộc không viết hoa trong tiếng Tây Ban Nha.' },
{ es:'francés', ipa:'fɾanˈses', vi:'tiếng Pháp', pos:'tính từ', g:'' },
{ es:'inglés', ipa:'iŋˈɡles', vi:'tiếng Anh', pos:'tính từ', g:'' },
{ es:'vietnamita', ipa:'bjet.naˈmi.ta', vi:'tiếng Việt; người Việt', pos:'tính từ', g:'', note:'Đuôi -ita dùng chung cho cả nam và nữ.' },

/* ---------- TỪ HỎI ---------- */
{ es:'qué', ipa:'ke', vi:'cái gì', pos:'từ hỏi', g:'', note:'Từ hỏi luôn có dấu sắc, kể cả trong câu hỏi gián tiếp: no sé qué hacer.' },
{ es:'quién', ipa:'kjen', vi:'ai', pos:'từ hỏi', g:'' },
{ es:'dónde', ipa:'ˈdon.de', vi:'ở đâu', pos:'từ hỏi', g:'' },
{ es:'cuándo', ipa:'ˈkwan.do', vi:'khi nào', pos:'từ hỏi', g:'' },
{ es:'cómo', ipa:'ˈko.mo', vi:'thế nào', pos:'từ hỏi', g:'' },
{ es:'cuánto', ipa:'ˈkwan.to', vi:'bao nhiêu', pos:'từ hỏi', g:'' },
{ es:'cuál', ipa:'kwal', vi:'cái nào', pos:'từ hỏi', g:'' },

/* ---------- SỐ ---------- */
{ es:'cero', ipa:'ˈse.ɾo', vi:'số không', pos:'số', g:'m' },
{ es:'uno', ipa:'ˈu.no', vi:'một', pos:'số', g:'' },
{ es:'dos', ipa:'dos', vi:'hai', pos:'số', g:'' },
{ es:'tres', ipa:'tɾes', vi:'ba', pos:'số', g:'' },
{ es:'cuatro', ipa:'ˈkwa.tɾo', vi:'bốn', pos:'số', g:'' },
{ es:'cinco', ipa:'ˈsiŋ.ko', vi:'năm', pos:'số', g:'' },
{ es:'seis', ipa:'sejs', vi:'sáu', pos:'số', g:'' },
{ es:'siete', ipa:'ˈsje.te', vi:'bảy', pos:'số', g:'' },
{ es:'ocho', ipa:'ˈo.tʃo', vi:'tám', pos:'số', g:'' },
{ es:'nueve', ipa:'ˈnwe.βe', vi:'chín', pos:'số', g:'' },
{ es:'diez', ipa:'djes', vi:'mười', pos:'số', g:'' },
{ es:'once', ipa:'ˈon.se', vi:'mười một', pos:'số', g:'' },
{ es:'doce', ipa:'ˈdo.se', vi:'mười hai', pos:'số', g:'' },
{ es:'trece', ipa:'ˈtɾe.se', vi:'mười ba', pos:'số', g:'' },
{ es:'catorce', ipa:'kaˈtoɾ.se', vi:'mười bốn', pos:'số', g:'' },
{ es:'quince', ipa:'ˈkin.se', vi:'mười lăm', pos:'số', g:'' },
{ es:'veinte', ipa:'ˈbejn.te', vi:'hai mươi', pos:'số', g:'' },
{ es:'treinta', ipa:'ˈtɾejn.ta', vi:'ba mươi', pos:'số', g:'' },
{ es:'cuarenta', ipa:'kwaˈɾen.ta', vi:'bốn mươi', pos:'số', g:'' },
{ es:'cincuenta', ipa:'siŋˈkwen.ta', vi:'năm mươi', pos:'số', g:'' },
{ es:'sesenta', ipa:'seˈsen.ta', vi:'sáu mươi', pos:'số', g:'' },
{ es:'setenta', ipa:'seˈten.ta', vi:'bảy mươi', pos:'số', g:'' },
{ es:'ochenta', ipa:'oˈtʃen.ta', vi:'tám mươi', pos:'số', g:'' },
{ es:'noventa', ipa:'noˈβen.ta', vi:'chín mươi', pos:'số', g:'' },
{ es:'cien', ipa:'sjen', vi:'một trăm', pos:'số', g:'', note:'Đúng một trăm thì nói cien; hơn một trăm thì thành ciento: ciento cinco.' },
{ es:'mil', ipa:'mil', vi:'một nghìn', pos:'số', g:'' },
{ es:'millón', ipa:'miˈʝon', vi:'triệu', pos:'danh từ', g:'m' },
{ es:'medio', ipa:'ˈme.ðjo', vi:'một nửa', pos:'tính từ', g:'' },

/* ---------- THỨ VÀ THÁNG ---------- */
{ es:'lunes', ipa:'ˈlu.nes', vi:'thứ Hai', pos:'danh từ', g:'m', note:'Thứ trong tiếng Tây Ban Nha không viết hoa, và số nhiều giữ nguyên: los lunes.' },
{ es:'martes', ipa:'ˈmaɾ.tes', vi:'thứ Ba', pos:'danh từ', g:'m' },
{ es:'miércoles', ipa:'ˈmjeɾ.ko.les', vi:'thứ Tư', pos:'danh từ', g:'m' },
{ es:'jueves', ipa:'ˈxwe.βes', vi:'thứ Năm', pos:'danh từ', g:'m' },
{ es:'viernes', ipa:'ˈbjeɾ.nes', vi:'thứ Sáu', pos:'danh từ', g:'m' },
{ es:'sábado', ipa:'ˈsa.βa.ðo', vi:'thứ Bảy', pos:'danh từ', g:'m' },
{ es:'domingo', ipa:'doˈmiŋ.ɡo', vi:'Chủ nhật', pos:'danh từ', g:'m' },
{ es:'enero', ipa:'eˈne.ɾo', vi:'tháng Một', pos:'danh từ', g:'m' },
{ es:'febrero', ipa:'feˈβɾe.ɾo', vi:'tháng Hai', pos:'danh từ', g:'m' },
{ es:'marzo', ipa:'ˈmaɾ.so', vi:'tháng Ba', pos:'danh từ', g:'m' },
{ es:'abril', ipa:'aˈβɾil', vi:'tháng Tư', pos:'danh từ', g:'m' },
{ es:'mayo', ipa:'ˈma.ʝo', vi:'tháng Năm', pos:'danh từ', g:'m' },
{ es:'junio', ipa:'ˈxu.njo', vi:'tháng Sáu', pos:'danh từ', g:'m' },
{ es:'julio', ipa:'ˈxu.ljo', vi:'tháng Bảy', pos:'danh từ', g:'m' },
{ es:'agosto', ipa:'aˈɣos.to', vi:'tháng Tám', pos:'danh từ', g:'m' },
{ es:'septiembre', ipa:'sepˈtjem.bɾe', vi:'tháng Chín', pos:'danh từ', g:'m' },
{ es:'octubre', ipa:'okˈtu.βɾe', vi:'tháng Mười', pos:'danh từ', g:'m' },
{ es:'noviembre', ipa:'noˈβjem.bɾe', vi:'tháng Mười một', pos:'danh từ', g:'m' },
{ es:'diciembre', ipa:'diˈsjem.bɾe', vi:'tháng Mười hai', pos:'danh từ', g:'m' },

/* ---------- TÊN RIÊNG ---------- */
{ es:'España', ipa:'esˈpa.ɲa', vi:'Tây Ban Nha', pos:'tên riêng', g:'f' },
{ es:'Madrid', ipa:'maˈðɾið', vi:'Ma-đrít (thủ đô Tây Ban Nha)', pos:'tên riêng', g:'' },
{ es:'Barcelona', ipa:'baɾ.seˈlo.na', vi:'Bác-xê-lô-na', pos:'tên riêng', g:'' },
{ es:'Valencia', ipa:'baˈlen.sja', vi:'Va-len-xi-a', pos:'tên riêng', g:'' },
{ es:'Sevilla', ipa:'seˈβi.ʝa', vi:'Xê-vi-gia', pos:'tên riêng', g:'' },
{ es:'Zaragoza', ipa:'sa.ɾaˈɣo.sa', vi:'Xa-ra-gô-xa', pos:'tên riêng', g:'' },
{ es:'Bilbao', ipa:'bilˈβa.o', vi:'Bin-ba-ô', pos:'tên riêng', g:'' },
{ es:'Granada', ipa:'ɣɾaˈna.ða', vi:'Gra-na-đa', pos:'tên riêng', g:'' },
{ es:'Málaga', ipa:'ˈma.la.ɣa', vi:'Ma-la-ga', pos:'tên riêng', g:'' },
{ es:'Salamanca', ipa:'sa.laˈmaŋ.ka', vi:'Xa-la-măng-ca', pos:'tên riêng', g:'' },
{ es:'México', ipa:'ˈme.xi.ko', vi:'Mê-hi-cô', pos:'tên riêng', g:'m' },
{ es:'Argentina', ipa:'aɾ.xenˈti.na', vi:'Ác-hen-ti-na', pos:'tên riêng', g:'f' },
{ es:'Colombia', ipa:'koˈlom.bja', vi:'Cô-lôm-bi-a', pos:'tên riêng', g:'f' },
{ es:'Perú', ipa:'peˈɾu', vi:'Pê-ru', pos:'tên riêng', g:'m' },
{ es:'Chile', ipa:'ˈtʃi.le', vi:'Chi-lê', pos:'tên riêng', g:'m' },
{ es:'Cuba', ipa:'ˈku.βa', vi:'Cu-ba', pos:'tên riêng', g:'f' },
{ es:'Vietnam', ipa:'bjetˈnam', vi:'Việt Nam', pos:'tên riêng', g:'m' },
{ es:'Hanói', ipa:'aˈnoj', vi:'Hà Nội', pos:'tên riêng', g:'' },
{ es:'Europa', ipa:'ewˈɾo.pa', vi:'châu Âu', pos:'tên riêng', g:'f' },
{ es:'Francia', ipa:'ˈfɾan.sja', vi:'nước Pháp', pos:'tên riêng', g:'f' },
{ es:'Italia', ipa:'iˈta.lja', vi:'nước Ý', pos:'tên riêng', g:'f' },
{ es:'Alemania', ipa:'a.leˈma.nja', vi:'nước Đức', pos:'tên riêng', g:'f' },
{ es:'María', ipa:'maˈɾi.a', vi:'Ma-ri-a (tên nữ)', pos:'tên riêng', g:'f' },
{ es:'Ana', ipa:'ˈa.na', vi:'A-na (tên nữ)', pos:'tên riêng', g:'f' },
{ es:'Carmen', ipa:'ˈkaɾ.men', vi:'Các-men (tên nữ)', pos:'tên riêng', g:'f' },
{ es:'Lucía', ipa:'luˈsi.a', vi:'Lu-xi-a (tên nữ)', pos:'tên riêng', g:'f' },
{ es:'Elena', ipa:'eˈle.na', vi:'Ê-lê-na (tên nữ)', pos:'tên riêng', g:'f' },
{ es:'Laura', ipa:'ˈlaw.ɾa', vi:'Lau-ra (tên nữ)', pos:'tên riêng', g:'f' },
{ es:'Sofía', ipa:'soˈfi.a', vi:'Xô-phi-a (tên nữ)', pos:'tên riêng', g:'f' },
{ es:'Juan', ipa:'xwan', vi:'Hoan (tên nam)', pos:'tên riêng', g:'m' },
{ es:'Pedro', ipa:'ˈpe.ðɾo', vi:'Pê-đrô (tên nam)', pos:'tên riêng', g:'m' },
{ es:'Carlos', ipa:'ˈkaɾ.los', vi:'Các-lốt (tên nam)', pos:'tên riêng', g:'m' },
{ es:'Diego', ipa:'ˈdje.ɣo', vi:'Đi-ê-gô (tên nam)', pos:'tên riêng', g:'m' },
{ es:'Miguel', ipa:'miˈɣel', vi:'Mi-ghen (tên nam)', pos:'tên riêng', g:'m' },
{ es:'Pablo', ipa:'ˈpa.βlo', vi:'Pa-blô (tên nam)', pos:'tên riêng', g:'m' },
{ es:'Javier', ipa:'xaˈβjeɾ', vi:'Ha-vi-e (tên nam)', pos:'tên riêng', g:'m' },
{ es:'Antonio', ipa:'anˈto.njo', vi:'An-tô-ni-ô (tên nam)', pos:'tên riêng', g:'m' },
{ es:'Luis', ipa:'lwis', vi:'Lu-ít (tên nam)', pos:'tên riêng', g:'m' },
{ es:'Jorge', ipa:'ˈxoɾ.xe', vi:'Hoóc-hê (tên nam)', pos:'tên riêng', g:'m' },
{ es:'Quan', ipa:'kwan', vi:'Quân (tên nam, người Việt)', pos:'tên riêng', g:'m' },
{ es:'Navidad', ipa:'na.βiˈðað', vi:'Giáng sinh', pos:'tên riêng', g:'f' }

];

if (typeof window !== 'undefined') window.WORDS_CORE_ES = WORDS_CORE_ES;
