/* ============================================================
   LangLab — TỪ NỀN CỦA TIẾNG PHÁP
   ------------------------------------------------------------
   Vì sao có tệp này: khoá học đặt ràng buộc không từ nào lặp lại
   giữa 100 bài. Ràng buộc ấy giữ cho kho từ sạch, nhưng nó đẩy
   việc chọn từ trôi dần sang những từ hiếm — còn «faire», «semaine»,
   «mois», «je», «à» thì được dùng thoải mái trong câu ví dụ mà
   không bao giờ được liệt kê thành mục từ.

   Hậu quả: bấm vào một từ trong câu ví dụ thì quá nửa số từ không
   tra được. Tệp này lấp đúng chỗ đó — những từ thông dụng nhất,
   thứ mà một cuốn từ điển không có thì không gọi là từ điển.

   Mỗi mục có cùng hình dạng với từ vựng bài học, nên bảng chia
   động từ, hợp giống tính từ và bộ tách gốc La-tinh đều tự chạy
   được, không phải sửa gì thêm. Thêm một động từ vào đây là mọi
   dạng chia của nó lập tức tra được.

   Nội dung do LangLab tự biên soạn.
   ============================================================ */

const WORDS_CORE_FR = [

/* ---------- MẠO TỪ VÀ TỪ HẠN ĐỊNH ---------- */
{ fr:'le', ipa:'lə', vi:'(mạo từ xác định, giống đực)', pos:'mạo từ', g:'', note:'Trước nguyên âm rút thành l’: l’homme. Sau à và de thì hoà lại: au, du.' },
{ fr:'la', ipa:'la', vi:'(mạo từ xác định, giống cái)', pos:'mạo từ', g:'' },
{ fr:'les', ipa:'le', vi:'(mạo từ xác định, số nhiều)', pos:'mạo từ', g:'', note:'Đọc nối với nguyên âm sau: les amis nghe thành «lê-za-mi».' },
{ fr:'un', ipa:'œ̃', vi:'một (giống đực)', pos:'mạo từ', g:'' },
{ fr:'une', ipa:'yn', vi:'một (giống cái)', pos:'mạo từ', g:'' },
{ fr:'des', ipa:'de', vi:'(mạo từ không xác định số nhiều); của các', pos:'mạo từ', g:'', note:'Vừa là số nhiều của un/une, vừa là de + les.' },
{ fr:'du', ipa:'dy', vi:'(mạo từ bộ phận, giống đực); của', pos:'mạo từ', g:'', note:'de + le. Dùng cho lượng không đếm được: du pain, du café.' },
{ fr:'de la', ipa:'də la', vi:'(mạo từ bộ phận, giống cái)', pos:'mạo từ', g:'' },
{ fr:'au', ipa:'o', vi:'ở, tới (giống đực)', pos:'giới từ', g:'', note:'à + le. Đi với tên nước giống đực: au Vietnam.' },
{ fr:'aux', ipa:'o', vi:'ở, tới (số nhiều)', pos:'giới từ', g:'', note:'à + les.' },
{ fr:'ce', ipa:'sə', vi:'này, đó (giống đực)', pos:'từ chỉ định', g:'', note:'Trước nguyên âm đổi thành cet: cet homme.' },
{ fr:'cet', ipa:'sɛt', vi:'này, đó (đực, trước nguyên âm)', pos:'từ chỉ định', g:'' },
{ fr:'cette', ipa:'sɛt', vi:'này, đó (giống cái)', pos:'từ chỉ định', g:'' },
{ fr:'ces', ipa:'se', vi:'những… này', pos:'từ chỉ định', g:'' },
{ fr:'mon', ipa:'mɔ̃', vi:'của tôi (đực)', pos:'từ sở hữu', g:'', note:'Trước danh từ giống cái bắt đầu bằng nguyên âm vẫn dùng mon: mon amie.' },
{ fr:'ma', ipa:'ma', vi:'của tôi (cái)', pos:'từ sở hữu', g:'' },
{ fr:'mes', ipa:'me', vi:'của tôi (số nhiều)', pos:'từ sở hữu', g:'' },
{ fr:'ton', ipa:'tɔ̃', vi:'của cậu (đực)', pos:'từ sở hữu', g:'' },
{ fr:'ta', ipa:'ta', vi:'của cậu (cái)', pos:'từ sở hữu', g:'' },
{ fr:'tes', ipa:'te', vi:'của cậu (số nhiều)', pos:'từ sở hữu', g:'' },
{ fr:'son', ipa:'sɔ̃', vi:'của anh ấy, của cô ấy (đực)', pos:'từ sở hữu', g:'', note:'Theo giống của VẬT, không theo giới tính người chủ — khác hẳn tiếng Anh.' },
{ fr:'sa', ipa:'sa', vi:'của anh ấy, của cô ấy (cái)', pos:'từ sở hữu', g:'' },
{ fr:'ses', ipa:'se', vi:'của anh ấy, của cô ấy (số nhiều)', pos:'từ sở hữu', g:'' },
{ fr:'notre', ipa:'nɔtʁ', vi:'của chúng tôi', pos:'từ sở hữu', g:'' },
{ fr:'nos', ipa:'no', vi:'của chúng tôi (số nhiều)', pos:'từ sở hữu', g:'' },
{ fr:'votre', ipa:'vɔtʁ', vi:'của anh, của các bạn', pos:'từ sở hữu', g:'' },
{ fr:'vos', ipa:'vo', vi:'của anh (số nhiều)', pos:'từ sở hữu', g:'' },
{ fr:'leur', ipa:'lœʁ', vi:'của họ; cho họ', pos:'từ sở hữu', g:'', note:'Vừa là từ sở hữu, vừa là đại từ gián tiếp số nhiều.' },
{ fr:'leurs', ipa:'lœʁ', vi:'của họ (số nhiều)', pos:'từ sở hữu', g:'' },

/* ---------- ĐẠI TỪ ---------- */
{ fr:'je', ipa:'ʒə', vi:'tôi', pos:'đại từ', g:'', note:'Trước nguyên âm rút thành j’: j’ai, j’habite.' },
{ fr:'tu', ipa:'ty', vi:'cậu, mày (thân mật)', pos:'đại từ', g:'', note:'Dùng với bạn bè, người nhà, trẻ con. Với người lạ phải dùng vous.' },
{ fr:'il', ipa:'il', vi:'anh ấy, nó', pos:'đại từ', g:'', note:'Cũng dùng cho chủ ngữ giả: il pleut, il faut, il y a.' },
{ fr:'elle', ipa:'ɛl', vi:'cô ấy, nó (giống cái)', pos:'đại từ', g:'' },
{ fr:'on', ipa:'ɔ̃', vi:'người ta; chúng tôi', pos:'đại từ', g:'', note:'Trong nói thường ngày, on thay hẳn cho nous: on y va = chúng mình đi thôi. Động từ vẫn chia như ngôi thứ ba số ít.' },
{ fr:'nous', ipa:'nu', vi:'chúng tôi, chúng ta', pos:'đại từ', g:'' },
{ fr:'vous', ipa:'vu', vi:'anh, chị, quý vị; các bạn', pos:'đại từ', g:'', note:'Vừa là số nhiều của tu, vừa là cách xưng hô lịch sự với một người.' },
{ fr:'ils', ipa:'il', vi:'họ (đực hoặc hỗn hợp)', pos:'đại từ', g:'', note:'Chỉ cần một người nam trong nhóm là cả nhóm dùng ils.' },
{ fr:'elles', ipa:'ɛl', vi:'họ (toàn nữ)', pos:'đại từ', g:'' },
{ fr:'me', ipa:'mə', vi:'tôi (tân ngữ)', pos:'đại từ', g:'' },
{ fr:'te', ipa:'tə', vi:'cậu (tân ngữ)', pos:'đại từ', g:'' },
{ fr:'se', ipa:'sə', vi:'mình, nhau (phản thân)', pos:'đại từ', g:'' },
{ fr:'lui', ipa:'lɥi', vi:'anh ấy; cho anh ấy, cho cô ấy', pos:'đại từ', g:'', note:'Đại từ gián tiếp dùng chung cho cả nam lẫn nữ.' },
{ fr:'moi', ipa:'mwa', vi:'tôi (nhấn mạnh)', pos:'đại từ', g:'', note:'Dùng sau giới từ và khi đứng một mình: avec moi, et moi ?' },
{ fr:'toi', ipa:'twa', vi:'cậu (nhấn mạnh)', pos:'đại từ', g:'' },
{ fr:'eux', ipa:'ø', vi:'họ (nhấn mạnh, đực)', pos:'đại từ', g:'' },
{ fr:'celui', ipa:'sə.lɥi', vi:'cái đó, người đó (đực)', pos:'đại từ', g:'' },
{ fr:'celle', ipa:'sɛl', vi:'cái đó, người đó (cái)', pos:'đại từ', g:'' },
{ fr:'ceux', ipa:'sø', vi:'những cái đó (đực)', pos:'đại từ', g:'' },
{ fr:'ceci', ipa:'sə.si', vi:'cái này', pos:'đại từ', g:'' },
{ fr:'quelqu’un', ipa:'kɛl.kœ̃', vi:'một người nào đó', pos:'đại từ', g:'' },
{ fr:'quelque chose', ipa:'kɛl.kə ʃoz', vi:'một cái gì đó', pos:'đại từ', g:'' },
{ fr:'tout', ipa:'tu', vi:'tất cả, mọi thứ', pos:'đại từ', g:'', note:'Chữ t cuối câm khi đứng một mình, nhưng đọc lên trong tout à fait.' },
{ fr:'toute', ipa:'tut', vi:'toàn bộ (giống cái)', pos:'từ hạn định', g:'' },
{ fr:'tous', ipa:'tus', vi:'tất cả (số nhiều đực)', pos:'từ hạn định', g:'', note:'Đọc «tus» khi là đại từ, «tu» khi đứng trước danh từ: tous les jours.' },
{ fr:'toutes', ipa:'tut', vi:'tất cả (số nhiều cái)', pos:'từ hạn định', g:'' },
{ fr:'chaque', ipa:'ʃak', vi:'mỗi', pos:'từ hạn định', g:'' },
{ fr:'plusieurs', ipa:'ply.zjœʁ', vi:'vài, nhiều', pos:'từ hạn định', g:'' },
{ fr:'quelques', ipa:'kɛl.kə', vi:'một vài', pos:'từ hạn định', g:'' },
{ fr:'aucun', ipa:'o.kœ̃', vi:'không một… nào', pos:'từ hạn định', g:'' },
{ fr:'autre', ipa:'otʁ', vi:'khác', pos:'tính từ', g:'' },
{ fr:'même', ipa:'mɛm', vi:'cùng, chính; ngay cả', pos:'tính từ', g:'' },

/* ---------- GIỚI TỪ VÀ LIÊN TỪ ---------- */
{ fr:'à', ipa:'a', vi:'ở, tới, lúc; của', pos:'giới từ', g:'', note:'Giới từ dùng nhiều nhất của tiếng Pháp. Gặp le thành au, gặp les thành aux.' },
{ fr:'de', ipa:'də', vi:'của, từ', pos:'giới từ', g:'', note:'Trước nguyên âm rút thành d’: d’accord, d’ici.' },
{ fr:'en', ipa:'ɑ̃', vi:'ở, trong, bằng', pos:'giới từ', g:'', note:'Đi với tên nước giống cái (en France) và với tháng, mùa, chất liệu.' },
{ fr:'dans', ipa:'dɑ̃', vi:'trong, bên trong', pos:'giới từ', g:'', note:'Khác en: dans chỉ chỗ cụ thể có ranh giới, en chỉ chung chung.' },
{ fr:'sur', ipa:'syʁ', vi:'trên', pos:'giới từ', g:'' },
{ fr:'sous', ipa:'su', vi:'dưới', pos:'giới từ', g:'' },
{ fr:'avec', ipa:'a.vɛk', vi:'với, cùng', pos:'giới từ', g:'' },
{ fr:'sans', ipa:'sɑ̃', vi:'không có', pos:'giới từ', g:'' },
{ fr:'pour', ipa:'puʁ', vi:'để, cho', pos:'giới từ', g:'' },
{ fr:'par', ipa:'paʁ', vi:'bởi, qua, mỗi', pos:'giới từ', g:'' },
{ fr:'chez', ipa:'ʃe', vi:'ở nhà, ở chỗ (ai)', pos:'giới từ', g:'', note:'Chỉ dùng với người: chez moi, chez le médecin. Không dùng với địa điểm.' },
{ fr:'entre', ipa:'ɑ̃tʁ', vi:'giữa', pos:'giới từ', g:'' },
{ fr:'vers', ipa:'vɛʁ', vi:'về phía; khoảng', pos:'giới từ', g:'' },
{ fr:'devant', ipa:'də.vɑ̃', vi:'phía trước', pos:'giới từ', g:'' },
{ fr:'derrière', ipa:'dɛ.ʁjɛʁ', vi:'phía sau', pos:'giới từ', g:'' },
{ fr:'depuis', ipa:'də.pɥi', vi:'từ khi, đã được', pos:'giới từ', g:'', note:'Đi với thì HIỆN TẠI: j’habite ici depuis trois ans.' },
{ fr:'jusqu’à', ipa:'ʒys.ka', vi:'cho tới', pos:'giới từ', g:'' },
{ fr:'et', ipa:'e', vi:'và', pos:'liên từ', g:'', note:'Không bao giờ nối âm sang từ sau, khác với các từ khác kết thúc bằng t.' },
{ fr:'ou', ipa:'u', vi:'hoặc', pos:'liên từ', g:'', note:'Không dấu là «hoặc»; có dấu «où» là «ở đâu».' },
{ fr:'mais', ipa:'mɛ', vi:'nhưng', pos:'liên từ', g:'' },
{ fr:'donc', ipa:'dɔ̃k', vi:'vậy nên', pos:'liên từ', g:'' },
{ fr:'que', ipa:'kə', vi:'rằng; mà; hơn', pos:'liên từ', g:'', note:'Ba việc trong một chữ: nối mệnh đề, làm đại từ quan hệ tân ngữ, và làm vế so sánh. Trước nguyên âm rút thành qu’.' },
{ fr:'qui', ipa:'ki', vi:'ai; mà (chủ ngữ)', pos:'đại từ', g:'', note:'Không bao giờ rút gọn, khác với que.' },
{ fr:'si', ipa:'si', vi:'nếu; có chứ', pos:'liên từ', g:'', note:'«Si» còn là cách trả lời CÓ cho một câu hỏi phủ định — chỗ mà oui không dùng được.' },
{ fr:'parce que', ipa:'paʁs kə', vi:'bởi vì', pos:'liên từ', g:'' },
{ fr:'quand', ipa:'kɑ̃', vi:'khi nào', pos:'liên từ', g:'' },
{ fr:'comme', ipa:'kɔm', vi:'như; vì', pos:'liên từ', g:'' },
{ fr:'sauf', ipa:'sof', vi:'trừ', pos:'giới từ', g:'' },
{ fr:'selon', ipa:'sə.lɔ̃', vi:'theo như', pos:'giới từ', g:'' },
{ fr:'pendant', ipa:'pɑ̃.dɑ̃', vi:'trong suốt', pos:'giới từ', g:'' },

/* ---------- TRẠNG TỪ THÔNG DỤNG ---------- */
{ fr:'ne', ipa:'nə', vi:'(nửa đầu của phủ định)', pos:'trạng từ', g:'', note:'Khi nói, người Pháp thường nuốt mất chữ này: «je sais pas».' },
{ fr:'pas', ipa:'pa', vi:'không (nửa sau của phủ định)', pos:'trạng từ', g:'' },
{ fr:'oui', ipa:'wi', vi:'vâng, đúng', pos:'thán từ', g:'' },
{ fr:'non', ipa:'nɔ̃', vi:'không', pos:'thán từ', g:'' },
{ fr:'très', ipa:'tʁɛ', vi:'rất', pos:'trạng từ', g:'' },
{ fr:'beaucoup', ipa:'bo.ku', vi:'nhiều, lắm', pos:'trạng từ', g:'' },
{ fr:'trop', ipa:'tʁo', vi:'quá', pos:'trạng từ', g:'' },
{ fr:'assez', ipa:'a.se', vi:'khá; đủ', pos:'trạng từ', g:'' },
{ fr:'peu', ipa:'pø', vi:'ít', pos:'trạng từ', g:'' },
{ fr:'moins', ipa:'mwɛ̃', vi:'ít hơn', pos:'trạng từ', g:'' },
{ fr:'plus', ipa:'ply', vi:'hơn; nữa', pos:'trạng từ', g:'', note:'Đọc «ply» khi so sánh, «plys» khi là số cộng, và câm hẳn trong «ne… plus».' },
{ fr:'aussi', ipa:'o.si', vi:'cũng', pos:'trạng từ', g:'' },
{ fr:'encore', ipa:'ɑ̃.kɔʁ', vi:'vẫn còn, nữa', pos:'trạng từ', g:'' },
{ fr:'déjà', ipa:'de.ʒa', vi:'đã, rồi', pos:'trạng từ', g:'' },
{ fr:'toujours', ipa:'tu.ʒuʁ', vi:'luôn luôn', pos:'trạng từ', g:'' },
{ fr:'jamais', ipa:'ʒa.mɛ', vi:'không bao giờ', pos:'trạng từ', g:'' },
{ fr:'souvent', ipa:'su.vɑ̃', vi:'thường xuyên', pos:'trạng từ', g:'' },
{ fr:'parfois', ipa:'paʁ.fwa', vi:'đôi khi', pos:'trạng từ', g:'' },
{ fr:'maintenant', ipa:'mɛ̃t.nɑ̃', vi:'bây giờ', pos:'trạng từ', g:'' },
{ fr:'alors', ipa:'a.lɔʁ', vi:'thế thì, lúc đó', pos:'trạng từ', g:'' },
{ fr:'puis', ipa:'pɥi', vi:'rồi thì', pos:'trạng từ', g:'' },
{ fr:'ici', ipa:'i.si', vi:'ở đây', pos:'trạng từ', g:'' },
{ fr:'là', ipa:'la', vi:'ở đó, đây', pos:'trạng từ', g:'' },
{ fr:'partout', ipa:'paʁ.tu', vi:'khắp nơi', pos:'trạng từ', g:'' },
{ fr:'bien', ipa:'bjɛ̃', vi:'tốt, hay', pos:'trạng từ', g:'' },
{ fr:'mal', ipa:'mal', vi:'tệ, dở; chỗ đau', pos:'trạng từ', g:'' },
{ fr:'vite', ipa:'vit', vi:'nhanh', pos:'trạng từ', g:'' },
{ fr:'juste', ipa:'ʒyst', vi:'vừa đúng; chỉ', pos:'trạng từ', g:'' },
{ fr:'seulement', ipa:'sœl.mɑ̃', vi:'chỉ, chỉ có điều', pos:'trạng từ', g:'' },
{ fr:'exactement', ipa:'ɛɡ.zak.tə.mɑ̃', vi:'chính xác', pos:'trạng từ', g:'' },
{ fr:'longtemps', ipa:'lɔ̃.tɑ̃', vi:'lâu', pos:'trạng từ', g:'' },
{ fr:'tard', ipa:'taʁ', vi:'muộn', pos:'trạng từ', g:'' },
{ fr:'tôt', ipa:'to', vi:'sớm', pos:'trạng từ', g:'' },
{ fr:'dessus', ipa:'də.sy', vi:'ở trên đó', pos:'trạng từ', g:'' },
{ fr:'dessous', ipa:'də.su', vi:'ở dưới đó', pos:'trạng từ', g:'' },
{ fr:'voilà', ipa:'vwa.la', vi:'đây rồi, đó', pos:'trạng từ', g:'', note:'Từ vạn năng: vừa để đưa đồ, vừa để kết thúc một lời giải thích.' },
{ fr:'voici', ipa:'vwa.si', vi:'đây là', pos:'trạng từ', g:'' },

/* ---------- ĐỘNG TỪ LÕI ---------- */
{ fr:'être', ipa:'ɛtʁ', vi:'là, thì, ở', pos:'động từ', g:'', note:'Động từ bất quy tắc nặng nhất: suis, es, est, sommes, êtes, sont. Vừa là động từ chính, vừa là trợ động từ của các động từ di chuyển và phản thân.' },
{ fr:'avoir', ipa:'a.vwaʁ', vi:'có', pos:'động từ', g:'', note:'ai, as, a, avons, avez, ont. Là trợ động từ của phần lớn thời quá khứ, và là động từ của cảm giác: avoir faim, avoir froid, avoir vingt ans.' },
{ fr:'faire', ipa:'fɛʁ', vi:'làm, chế tạo', pos:'động từ', g:'', note:'fais, fais, fait, faisons, faites, font. Dùng cho thời tiết (il fait chaud) và cho hoạt động (faire du sport).' },
{ fr:'aller', ipa:'a.le', vi:'đi', pos:'động từ', g:'', note:'vais, vas, va, allons, allez, vont. Aller + nguyên mẫu là cách nói tương lai gần: je vais partir.' },
{ fr:'dire', ipa:'diʁ', vi:'nói, bảo', pos:'động từ', g:'', note:'Dạng vous dites — không phải «disez».' },
{ fr:'pouvoir', ipa:'pu.vwaʁ', vi:'có thể', pos:'động từ', g:'', note:'peux, peux, peut, pouvons, pouvez, peuvent. Quá khứ phân từ pu.' },
{ fr:'vouloir', ipa:'vu.lwaʁ', vi:'muốn', pos:'động từ', g:'', note:'Je veux là thẳng thừng; je voudrais mới là cách nói lịch sự.' },
{ fr:'devoir', ipa:'də.vwaʁ', vi:'phải; nợ', pos:'động từ', g:'' },
{ fr:'savoir', ipa:'sa.vwaʁ', vi:'biết (kiến thức, kĩ năng)', pos:'động từ', g:'', note:'Biết một việc, một sự thật. Còn connaître là biết một người, một chỗ.' },
{ fr:'voir', ipa:'vwaʁ', vi:'thấy, xem', pos:'động từ', g:'' },
{ fr:'venir', ipa:'və.niʁ', vi:'đến', pos:'động từ', g:'', note:'venir de + nguyên mẫu nghĩa là «vừa mới»: je viens de manger.' },
{ fr:'prendre', ipa:'pʁɑ̃dʁ', vi:'lấy, bắt, dùng', pos:'động từ', g:'' },
{ fr:'donner', ipa:'dɔ.ne', vi:'cho, đưa', pos:'động từ', g:'' },
{ fr:'parler', ipa:'paʁ.le', vi:'nói, nói chuyện', pos:'động từ', g:'' },
{ fr:'aimer', ipa:'ɛ.me', vi:'thích, yêu', pos:'động từ', g:'' },
{ fr:'penser', ipa:'pɑ̃.se', vi:'nghĩ', pos:'động từ', g:'' },
{ fr:'croire', ipa:'kʁwaʁ', vi:'tin', pos:'động từ', g:'' },
{ fr:'trouver', ipa:'tʁu.ve', vi:'tìm thấy; thấy rằng', pos:'động từ', g:'' },
{ fr:'chercher', ipa:'ʃɛʁ.ʃe', vi:'tìm, tìm kiếm', pos:'động từ', g:'' },
{ fr:'passer', ipa:'pa.se', vi:'đi qua; trải qua', pos:'động từ', g:'' },
{ fr:'mettre', ipa:'mɛtʁ', vi:'đặt, mặc vào', pos:'động từ', g:'' },
{ fr:'partir', ipa:'paʁ.tiʁ', vi:'khởi hành, đi khỏi', pos:'động từ', g:'' },
{ fr:'sortir', ipa:'sɔʁ.tiʁ', vi:'ra ngoài, đi chơi', pos:'động từ', g:'' },
{ fr:'entrer', ipa:'ɑ̃.tʁe', vi:'vào', pos:'động từ', g:'' },
{ fr:'rester', ipa:'ʁɛs.te', vi:'ở lại, còn lại', pos:'động từ', g:'' },
{ fr:'arriver', ipa:'a.ʁi.ve', vi:'đến; xảy ra', pos:'động từ', g:'' },
{ fr:'rentrer', ipa:'ʁɑ̃.tʁe', vi:'về nhà', pos:'động từ', g:'' },
{ fr:'demander', ipa:'də.mɑ̃.de', vi:'hỏi, yêu cầu', pos:'động từ', g:'' },
{ fr:'répondre', ipa:'ʁe.pɔ̃dʁ', vi:'trả lời', pos:'động từ', g:'' },
{ fr:'appeler', ipa:'a.pə.le', vi:'gọi', pos:'động từ', g:'', note:'Nhân đôi chữ l khi trọng âm rơi vào gốc: j’appelle, nhưng nous appelons.' },
{ fr:'écouter', ipa:'e.ku.te', vi:'nghe, lắng nghe', pos:'động từ', g:'' },
{ fr:'regarder', ipa:'ʁə.ɡaʁ.de', vi:'nhìn, xem', pos:'động từ', g:'' },
{ fr:'lire', ipa:'liʁ', vi:'đọc', pos:'động từ', g:'' },
{ fr:'écrire', ipa:'e.kʁiʁ', vi:'viết', pos:'động từ', g:'' },
{ fr:'manger', ipa:'mɑ̃.ʒe', vi:'ăn', pos:'động từ', g:'', note:'Giữ chữ e trước a và o để chữ g còn đọc mềm: nous mangeons.' },
{ fr:'boire', ipa:'bwaʁ', vi:'uống', pos:'động từ', g:'' },
{ fr:'dormir', ipa:'dɔʁ.miʁ', vi:'ngủ', pos:'động từ', g:'' },
{ fr:'travailler', ipa:'tʁa.va.je', vi:'làm việc', pos:'động từ', g:'' },
{ fr:'habiter', ipa:'a.bi.te', vi:'ở, sống tại', pos:'động từ', g:'' },
{ fr:'acheter', ipa:'aʃ.te', vi:'mua', pos:'động từ', g:'' },
{ fr:'payer', ipa:'pɛ.je', vi:'trả tiền', pos:'động từ', g:'' },
{ fr:'commencer', ipa:'kɔ.mɑ̃.se', vi:'bắt đầu', pos:'động từ', g:'' },
{ fr:'finir', ipa:'fi.niʁ', vi:'kết thúc, xong', pos:'động từ', g:'' },
{ fr:'continuer', ipa:'kɔ̃.ti.nɥe', vi:'tiếp tục', pos:'động từ', g:'' },
{ fr:'attendre', ipa:'a.tɑ̃dʁ', vi:'chờ', pos:'động từ', g:'', note:'Không có giới từ đứng sau: j’attends le bus, chứ không phải «attendre pour».' },
{ fr:'oublier', ipa:'u.bli.je', vi:'quên', pos:'động từ', g:'' },
{ fr:'apprendre', ipa:'a.pʁɑ̃dʁ', vi:'học', pos:'động từ', g:'' },
{ fr:'comprendre', ipa:'kɔ̃.pʁɑ̃dʁ', vi:'hiểu', pos:'động từ', g:'' },
{ fr:'connaître', ipa:'kɔ.nɛtʁ', vi:'biết, quen', pos:'động từ', g:'' },
{ fr:'ouvrir', ipa:'u.vʁiʁ', vi:'mở', pos:'động từ', g:'' },
{ fr:'fermer', ipa:'fɛʁ.me', vi:'đóng', pos:'động từ', g:'' },
{ fr:'choisir', ipa:'ʃwa.ziʁ', vi:'chọn', pos:'động từ', g:'' },
{ fr:'changer', ipa:'ʃɑ̃.ʒe', vi:'thay đổi', pos:'động từ', g:'' },
{ fr:'garder', ipa:'ɡaʁ.de', vi:'giữ', pos:'động từ', g:'' },
{ fr:'tenir', ipa:'tə.niʁ', vi:'giữ, cầm', pos:'động từ', g:'' },
{ fr:'porter', ipa:'pɔʁ.te', vi:'mang, mặc', pos:'động từ', g:'' },
{ fr:'suivre', ipa:'sɥivʁ', vi:'theo', pos:'động từ', g:'' },
{ fr:'vivre', ipa:'vivʁ', vi:'sống', pos:'động từ', g:'' },
{ fr:'mourir', ipa:'mu.ʁiʁ', vi:'chết', pos:'động từ', g:'' },
{ fr:'naître', ipa:'nɛtʁ', vi:'sinh ra', pos:'động từ', g:'' },
{ fr:'devenir', ipa:'də.və.niʁ', vi:'trở thành', pos:'động từ', g:'' },
{ fr:'sembler', ipa:'sɑ̃.ble', vi:'trông như, có vẻ', pos:'động từ', g:'' },
{ fr:'rendre', ipa:'ʁɑ̃dʁ', vi:'trả lại; làm cho', pos:'động từ', g:'' },
{ fr:'perdre', ipa:'pɛʁdʁ', vi:'mất, thua', pos:'động từ', g:'' },
{ fr:'gagner', ipa:'ɡa.ɲe', vi:'thắng; kiếm được', pos:'động từ', g:'' },
{ fr:'jouer', ipa:'ʒwe', vi:'chơi', pos:'động từ', g:'' },
{ fr:'chanter', ipa:'ʃɑ̃.te', vi:'hát', pos:'động từ', g:'' },
{ fr:'marcher', ipa:'maʁ.ʃe', vi:'đi bộ; chạy được', pos:'động từ', g:'', note:'Nói về máy móc, marcher nghĩa là «hoạt động»: ça marche.' },
{ fr:'courir', ipa:'ku.ʁiʁ', vi:'chạy', pos:'động từ', g:'' },
{ fr:'monter', ipa:'mɔ̃.te', vi:'lên', pos:'động từ', g:'' },
{ fr:'descendre', ipa:'de.sɑ̃dʁ', vi:'xuống', pos:'động từ', g:'' },
{ fr:'tourner', ipa:'tuʁ.ne', vi:'rẽ, quay', pos:'động từ', g:'' },
{ fr:'revenir', ipa:'ʁə.və.niʁ', vi:'trở lại', pos:'động từ', g:'' },
{ fr:'aider', ipa:'ɛ.de', vi:'giúp', pos:'động từ', g:'' },
{ fr:'montrer', ipa:'mɔ̃.tʁe', vi:'chỉ, cho xem', pos:'động từ', g:'' },
{ fr:'expliquer', ipa:'ɛks.pli.ke', vi:'giải thích', pos:'động từ', g:'' },
{ fr:'raconter', ipa:'ʁa.kɔ̃.te', vi:'kể', pos:'động từ', g:'' },
{ fr:'utiliser', ipa:'y.ti.li.ze', vi:'dùng', pos:'động từ', g:'' },
{ fr:'essayer', ipa:'e.sɛ.je', vi:'thử', pos:'động từ', g:'' },
{ fr:'réussir', ipa:'ʁe.y.siʁ', vi:'thành công, đỗ', pos:'động từ', g:'' },
{ fr:'préparer', ipa:'pʁe.pa.ʁe', vi:'chuẩn bị', pos:'động từ', g:'' },
{ fr:'envoyer', ipa:'ɑ̃.vwa.je', vi:'gửi', pos:'động từ', g:'' },
{ fr:'recevoir', ipa:'ʁə.sə.vwaʁ', vi:'nhận', pos:'động từ', g:'' },
{ fr:'téléphoner', ipa:'te.le.fɔ.ne', vi:'gọi điện', pos:'động từ', g:'' },
{ fr:'rencontrer', ipa:'ʁɑ̃.kɔ̃.tʁe', vi:'gặp', pos:'động từ', g:'' },
{ fr:'visiter', ipa:'vi.zi.te', vi:'tham quan', pos:'động từ', g:'', note:'Dùng cho địa điểm. Thăm người thì nói rendre visite à.' },
{ fr:'voyager', ipa:'vwa.ja.ʒe', vi:'du lịch', pos:'động từ', g:'' },
{ fr:'réserver', ipa:'ʁe.zɛʁ.ve', vi:'đặt trước', pos:'động từ', g:'' },
{ fr:'louer', ipa:'lwe', vi:'thuê; cho thuê', pos:'động từ', g:'' },
{ fr:'coûter', ipa:'ku.te', vi:'có giá', pos:'động từ', g:'' },
{ fr:'servir', ipa:'sɛʁ.viʁ', vi:'phục vụ; dùng để', pos:'động từ', g:'' },
{ fr:'goûter', ipa:'ɡu.te', vi:'nếm', pos:'động từ', g:'' },
{ fr:'cuisiner', ipa:'kɥi.zi.ne', vi:'nấu ăn', pos:'động từ', g:'' },
{ fr:'nettoyer', ipa:'nɛ.twa.je', vi:'dọn, lau', pos:'động từ', g:'' },
{ fr:'laver', ipa:'la.ve', vi:'giặt, rửa', pos:'động từ', g:'' },
{ fr:'ranger', ipa:'ʁɑ̃.ʒe', vi:'xếp gọn', pos:'động từ', g:'' },
{ fr:'réparer', ipa:'ʁe.pa.ʁe', vi:'sửa', pos:'động từ', g:'' },
{ fr:'construire', ipa:'kɔ̃s.tʁɥiʁ', vi:'xây', pos:'động từ', g:'' },
{ fr:'créer', ipa:'kʁe.e', vi:'tạo ra', pos:'động từ', g:'' },
{ fr:'produire', ipa:'pʁɔ.dɥiʁ', vi:'sản xuất', pos:'động từ', g:'' },
{ fr:'vendre', ipa:'vɑ̃dʁ', vi:'bán', pos:'động từ', g:'' },
{ fr:'coucher', ipa:'ku.ʃe', vi:'nằm; đi ngủ', pos:'động từ', g:'' },
{ fr:'lever', ipa:'lə.ve', vi:'nâng; thức dậy', pos:'động từ', g:'' },
{ fr:'asseoir', ipa:'a.swaʁ', vi:'ngồi', pos:'động từ', g:'' },
{ fr:'arrêter', ipa:'a.ʁɛ.te', vi:'dừng', pos:'động từ', g:'' },
{ fr:'décider', ipa:'de.si.de', vi:'quyết định', pos:'động từ', g:'' },
{ fr:'espérer', ipa:'ɛs.pe.ʁe', vi:'hi vọng', pos:'động từ', g:'' },
{ fr:'préférer', ipa:'pʁe.fe.ʁe', vi:'thích hơn', pos:'động từ', g:'' },
{ fr:'accepter', ipa:'ak.sɛp.te', vi:'chấp nhận', pos:'động từ', g:'' },
{ fr:'refuser', ipa:'ʁə.fy.ze', vi:'từ chối', pos:'động từ', g:'' },
{ fr:'permettre', ipa:'pɛʁ.mɛtʁ', vi:'cho phép', pos:'động từ', g:'' },
{ fr:'falloir', ipa:'fa.lwaʁ', vi:'cần phải', pos:'động từ', g:'', note:'Chỉ tồn tại ở ngôi thứ ba: il faut. Không có «je faux».' },
{ fr:'plaire', ipa:'plɛʁ', vi:'làm vui lòng', pos:'động từ', g:'', note:'Người Pháp nói ça me plaît thay vì «tôi thích nó» — chủ ngữ là VẬT.' },
{ fr:'suffire', ipa:'sy.fiʁ', vi:'đủ', pos:'động từ', g:'' },
{ fr:'valoir', ipa:'va.lwaʁ', vi:'đáng giá', pos:'động từ', g:'' },
{ fr:'rire', ipa:'ʁiʁ', vi:'cười', pos:'động từ', g:'' },
{ fr:'pleuvoir', ipa:'plø.vwaʁ', vi:'mưa', pos:'động từ', g:'' },
{ fr:'neiger', ipa:'nɛ.ʒe', vi:'có tuyết', pos:'động từ', g:'' },
{ fr:'ajouter', ipa:'a.ʒu.te', vi:'thêm', pos:'động từ', g:'' },
{ fr:'enlever', ipa:'ɑ̃l.ve', vi:'bỏ ra, cất đi', pos:'động từ', g:'' },
{ fr:'remplir', ipa:'ʁɑ̃.pliʁ', vi:'điền, làm đầy', pos:'động từ', g:'' },
{ fr:'signer', ipa:'si.ɲe', vi:'kí', pos:'động từ', g:'' },
{ fr:'noter', ipa:'nɔ.te', vi:'ghi lại', pos:'động từ', g:'' },
{ fr:'compter', ipa:'kɔ̃.te', vi:'đếm; dự định', pos:'động từ', g:'' },
{ fr:'mesurer', ipa:'mə.zy.ʁe', vi:'đo', pos:'động từ', g:'' },
{ fr:'peser', ipa:'pə.ze', vi:'cân', pos:'động từ', g:'' },
{ fr:'contenir', ipa:'kɔ̃t.niʁ', vi:'chứa', pos:'động từ', g:'' },

/* ---------- DANH TỪ LÕI ---------- */
{ fr:'jour', ipa:'ʒuʁ', vi:'ngày', pos:'danh từ', g:'m' },
{ fr:'journée', ipa:'ʒuʁ.ne', vi:'ngày (cả quãng thời gian)', pos:'danh từ', g:'f', note:'Jour là cái mốc, journée là cả ngày dài trải ra: bonne journée !' },
{ fr:'semaine', ipa:'sə.mɛn', vi:'tuần', pos:'danh từ', g:'f' },
{ fr:'mois', ipa:'mwa', vi:'tháng', pos:'danh từ', g:'m', note:'Số ít và số nhiều viết giống nhau: un mois, deux mois.' },
{ fr:'an', ipa:'ɑ̃', vi:'năm', pos:'danh từ', g:'m', note:'Dùng để đếm: deux ans. Còn année dùng khi nói về nội dung của năm.' },
{ fr:'année', ipa:'a.ne', vi:'năm (cả quãng)', pos:'danh từ', g:'f' },
{ fr:'heure', ipa:'œʁ', vi:'giờ, tiếng', pos:'danh từ', g:'f' },
{ fr:'minute', ipa:'mi.nyt', vi:'phút', pos:'danh từ', g:'f' },
{ fr:'temps', ipa:'tɑ̃', vi:'thời gian; thời tiết', pos:'danh từ', g:'m', note:'Một chữ cho hai nghĩa: je n’ai pas le temps và quel temps fait-il ?' },
{ fr:'fois', ipa:'fwa', vi:'lần', pos:'danh từ', g:'f' },
{ fr:'matin', ipa:'ma.tɛ̃', vi:'buổi sáng', pos:'danh từ', g:'m' },
{ fr:'midi', ipa:'mi.di', vi:'buổi trưa, 12 giờ', pos:'danh từ', g:'m' },
{ fr:'soir', ipa:'swaʁ', vi:'buổi tối', pos:'danh từ', g:'m' },
{ fr:'nuit', ipa:'nɥi', vi:'đêm', pos:'danh từ', g:'f' },
{ fr:'hier', ipa:'jɛʁ', vi:'hôm qua', pos:'trạng từ', g:'' },
{ fr:'aujourd’hui', ipa:'o.ʒuʁ.dɥi', vi:'hôm nay', pos:'trạng từ', g:'' },
{ fr:'demain', ipa:'də.mɛ̃', vi:'ngày mai', pos:'trạng từ', g:'' },
{ fr:'personne', ipa:'pɛʁ.sɔn', vi:'người; không ai', pos:'danh từ', g:'f', note:'Là danh từ thì nghĩa «người»; đứng với ne thì nghĩa «không ai».' },
{ fr:'gens', ipa:'ʒɑ̃', vi:'người ta, mọi người', pos:'danh từ', g:'m', note:'Chỉ có số nhiều.' },
{ fr:'homme', ipa:'ɔm', vi:'người đàn ông', pos:'danh từ', g:'m' },
{ fr:'femme', ipa:'fam', vi:'người phụ nữ; vợ', pos:'danh từ', g:'f', note:'Viết là emme mà đọc là «am» — ngoại lệ hiếm.' },
{ fr:'enfant', ipa:'ɑ̃.fɑ̃', vi:'đứa trẻ', pos:'danh từ', g:'m' },
{ fr:'ami', ipa:'a.mi', vi:'người bạn', pos:'danh từ', g:'m' },
{ fr:'famille', ipa:'fa.mij', vi:'gia đình', pos:'danh từ', g:'f' },
{ fr:'père', ipa:'pɛʁ', vi:'bố', pos:'danh từ', g:'m' },
{ fr:'mère', ipa:'mɛʁ', vi:'mẹ', pos:'danh từ', g:'f' },
{ fr:'fils', ipa:'fis', vi:'con trai', pos:'danh từ', g:'m', note:'Chữ l câm, chữ s đọc lên — «fis».' },
{ fr:'fille', ipa:'fij', vi:'con gái; cô gái', pos:'danh từ', g:'f' },
{ fr:'frère', ipa:'fʁɛʁ', vi:'anh, em trai', pos:'danh từ', g:'m' },
{ fr:'sœur', ipa:'sœʁ', vi:'chị, em gái', pos:'danh từ', g:'f' },
{ fr:'monsieur', ipa:'mə.sjø', vi:'ông, ngài', pos:'danh từ', g:'m', note:'Số nhiều là messieurs, đọc «mê-siơ».' },
{ fr:'madame', ipa:'ma.dam', vi:'bà, chị', pos:'danh từ', g:'f' },
{ fr:'chose', ipa:'ʃoz', vi:'thứ, việc', pos:'danh từ', g:'f' },
{ fr:'truc', ipa:'tʁyk', vi:'cái này cái kia (nói thường)', pos:'danh từ', g:'m' },
{ fr:'maison', ipa:'mɛ.zɔ̃', vi:'nhà', pos:'danh từ', g:'f' },
{ fr:'appartement', ipa:'a.paʁ.tə.mɑ̃', vi:'căn hộ', pos:'danh từ', g:'m' },
{ fr:'chambre', ipa:'ʃɑ̃bʁ', vi:'phòng ngủ', pos:'danh từ', g:'f' },
{ fr:'porte', ipa:'pɔʁt', vi:'cửa', pos:'danh từ', g:'f' },
{ fr:'table', ipa:'tabl', vi:'bàn', pos:'danh từ', g:'f' },
{ fr:'chaise', ipa:'ʃɛz', vi:'ghế', pos:'danh từ', g:'f' },
{ fr:'rue', ipa:'ʁy', vi:'phố', pos:'danh từ', g:'f' },
{ fr:'ville', ipa:'vil', vi:'thành phố', pos:'danh từ', g:'f' },
{ fr:'pays', ipa:'pe.i', vi:'nước, quốc gia', pos:'danh từ', g:'m' },
{ fr:'monde', ipa:'mɔ̃d', vi:'thế giới; người (đông)', pos:'danh từ', g:'m', note:'Tout le monde nghĩa là «mọi người», không phải «cả thế giới».' },
{ fr:'école', ipa:'e.kɔl', vi:'trường học', pos:'danh từ', g:'f' },
{ fr:'travail', ipa:'tʁa.vaj', vi:'công việc', pos:'danh từ', g:'m', note:'Số nhiều bất quy tắc: travaux.' },
{ fr:'bureau', ipa:'by.ʁo', vi:'bàn làm việc; văn phòng', pos:'danh từ', g:'m' },
{ fr:'livre', ipa:'livʁ', vi:'quyển sách', pos:'danh từ', g:'m', note:'Giống đực là sách; giống cái (la livre) là nửa kilo và đồng bảng Anh.' },
{ fr:'mot', ipa:'mo', vi:'từ, chữ', pos:'danh từ', g:'m' },
{ fr:'langue', ipa:'lɑ̃ɡ', vi:'ngôn ngữ; cái lưỡi', pos:'danh từ', g:'f' },
{ fr:'question', ipa:'kɛs.tjɔ̃', vi:'câu hỏi', pos:'danh từ', g:'f' },
{ fr:'problème', ipa:'pʁɔ.blɛm', vi:'vấn đề', pos:'danh từ', g:'m', note:'Tận cùng bằng -ème mà vẫn là giống đực.' },
{ fr:'exemple', ipa:'ɛɡ.zɑ̃pl', vi:'ví dụ', pos:'danh từ', g:'m' },
{ fr:'raison', ipa:'ʁɛ.zɔ̃', vi:'lí do; lẽ phải', pos:'danh từ', g:'f', note:'Avoir raison nghĩa là «nói đúng».' },
{ fr:'idée', ipa:'i.de', vi:'ý tưởng', pos:'danh từ', g:'f' },
{ fr:'vie', ipa:'vi', vi:'đời, cuộc sống', pos:'danh từ', g:'f' },
{ fr:'main', ipa:'mɛ̃', vi:'bàn tay', pos:'danh từ', g:'f' },
{ fr:'tête', ipa:'tɛt', vi:'cái đầu', pos:'danh từ', g:'f' },
{ fr:'pied', ipa:'pje', vi:'bàn chân', pos:'danh từ', g:'m' },
{ fr:'eau', ipa:'o', vi:'nước', pos:'danh từ', g:'f', note:'Số nhiều eaux, vẫn đọc là «o».' },
{ fr:'pain', ipa:'pɛ̃', vi:'bánh mì', pos:'danh từ', g:'m' },
{ fr:'café', ipa:'ka.fe', vi:'cà phê; quán cà phê', pos:'danh từ', g:'m' },
{ fr:'argent', ipa:'aʁ.ʒɑ̃', vi:'tiền; bạc', pos:'danh từ', g:'m' },
{ fr:'prix', ipa:'pʁi', vi:'giá; giải thưởng', pos:'danh từ', g:'m' },
{ fr:'euro', ipa:'ø.ʁo', vi:'đồng euro', pos:'danh từ', g:'m' },
{ fr:'train', ipa:'tʁɛ̃', vi:'tàu hoả', pos:'danh từ', g:'m' },
{ fr:'voiture', ipa:'vwa.tyʁ', vi:'xe hơi', pos:'danh từ', g:'f' },
{ fr:'chien', ipa:'ʃjɛ̃', vi:'con chó', pos:'danh từ', g:'m' },
{ fr:'chat', ipa:'ʃa', vi:'con mèo', pos:'danh từ', g:'m' },
{ fr:'eau de vie', ipa:'o də vi', vi:'rượu mạnh', pos:'danh từ', g:'f' },
{ fr:'nom', ipa:'nɔ̃', vi:'tên; họ', pos:'danh từ', g:'m' },
{ fr:'numéro', ipa:'ny.me.ʁo', vi:'số', pos:'danh từ', g:'m' },
{ fr:'fin', ipa:'fɛ̃', vi:'sự kết thúc', pos:'danh từ', g:'f' },
{ fr:'début', ipa:'de.by', vi:'lúc bắt đầu', pos:'danh từ', g:'m' },
{ fr:'côté', ipa:'ko.te', vi:'phía, bên', pos:'danh từ', g:'m' },
{ fr:'place', ipa:'plas', vi:'chỗ; quảng trường', pos:'danh từ', g:'f' },
{ fr:'part', ipa:'paʁ', vi:'phần', pos:'danh từ', g:'f' },
{ fr:'coup', ipa:'ku', vi:'cú, nhát; lần', pos:'danh từ', g:'m' },
{ fr:'point', ipa:'pwɛ̃', vi:'điểm; dấu chấm', pos:'danh từ', g:'m' },
{ fr:'peine', ipa:'pɛn', vi:'sự khó; hình phạt', pos:'danh từ', g:'f' },
{ fr:'envie', ipa:'ɑ̃.vi', vi:'sự thèm, muốn', pos:'danh từ', g:'f', note:'Avoir envie de nghĩa là «muốn», dùng nhiều hơn vouloir trong nói thường.' },
{ fr:'besoin', ipa:'bə.zwɛ̃', vi:'sự cần', pos:'danh từ', g:'m' },
{ fr:'faim', ipa:'fɛ̃', vi:'cơn đói', pos:'danh từ', g:'f' },
{ fr:'soif', ipa:'swaf', vi:'cơn khát', pos:'danh từ', g:'f' },

/* ---------- TÍNH TỪ LÕI ---------- */
{ fr:'grand', ipa:'ɡʁɑ̃', vi:'to, lớn, cao', pos:'tính từ', g:'' },
{ fr:'petit', ipa:'pə.ti', vi:'nhỏ, bé', pos:'tính từ', g:'' },
{ fr:'bon', ipa:'bɔ̃', vi:'tốt, ngon', pos:'tính từ', g:'', note:'Giống cái là bonne, đọc rõ chữ n.' },
{ fr:'mauvais', ipa:'mo.vɛ', vi:'tệ, dở', pos:'tính từ', g:'' },
{ fr:'beau', ipa:'bo', vi:'đẹp', pos:'tính từ', g:'', note:'Ba dạng: beau, bel (trước nguyên âm), belle.' },
{ fr:'joli', ipa:'ʒɔ.li', vi:'xinh', pos:'tính từ', g:'' },
{ fr:'nouveau', ipa:'nu.vo', vi:'mới', pos:'tính từ', g:'', note:'nouveau, nouvel, nouvelle.' },
{ fr:'vieux', ipa:'vjø', vi:'già, cũ', pos:'tính từ', g:'', note:'vieux, vieil, vieille.' },
{ fr:'jeune', ipa:'ʒœn', vi:'trẻ', pos:'tính từ', g:'' },
{ fr:'long', ipa:'lɔ̃', vi:'dài', pos:'tính từ', g:'', note:'Giống cái longue.' },
{ fr:'court', ipa:'kuʁ', vi:'ngắn', pos:'tính từ', g:'' },
{ fr:'haut', ipa:'o', vi:'cao', pos:'tính từ', g:'', note:'Chữ h của haut chặn nối âm: le haut, không phải «l’haut».' },
{ fr:'bas', ipa:'ba', vi:'thấp', pos:'tính từ', g:'' },
{ fr:'chaud', ipa:'ʃo', vi:'nóng', pos:'tính từ', g:'' },
{ fr:'froid', ipa:'fʁwa', vi:'lạnh', pos:'tính từ', g:'' },
{ fr:'facile', ipa:'fa.sil', vi:'dễ', pos:'tính từ', g:'' },
{ fr:'difficile', ipa:'di.fi.sil', vi:'khó', pos:'tính từ', g:'' },
{ fr:'cher', ipa:'ʃɛʁ', vi:'đắt; thân mến', pos:'tính từ', g:'', note:'Đứng trước danh từ nghĩa «thân mến», đứng sau nghĩa «đắt».' },
{ fr:'gratuit', ipa:'ɡʁa.tɥi', vi:'miễn phí', pos:'tính từ', g:'' },
{ fr:'content', ipa:'kɔ̃.tɑ̃', vi:'vui, hài lòng', pos:'tính từ', g:'' },
{ fr:'heureux', ipa:'œ.ʁø', vi:'hạnh phúc', pos:'tính từ', g:'', note:'Giống cái heureuse.' },
{ fr:'triste', ipa:'tʁist', vi:'buồn', pos:'tính từ', g:'' },
{ fr:'fatigué', ipa:'fa.ti.ɡe', vi:'mệt', pos:'tính từ', g:'' },
{ fr:'malade', ipa:'ma.lad', vi:'ốm', pos:'tính từ', g:'' },
{ fr:'prêt', ipa:'pʁɛ', vi:'sẵn sàng', pos:'tính từ', g:'' },
{ fr:'possible', ipa:'pɔ.sibl', vi:'có thể được', pos:'tính từ', g:'' },
{ fr:'vrai', ipa:'vʁɛ', vi:'thật, đúng', pos:'tính từ', g:'' },
{ fr:'faux', ipa:'fo', vi:'sai, giả', pos:'tính từ', g:'' },
{ fr:'important', ipa:'ɛ̃.pɔʁ.tɑ̃', vi:'quan trọng', pos:'tính từ', g:'' },
{ fr:'premier', ipa:'pʁə.mje', vi:'thứ nhất', pos:'tính từ', g:'' },
{ fr:'dernier', ipa:'dɛʁ.nje', vi:'cuối cùng; vừa rồi', pos:'tính từ', g:'' },
{ fr:'prochain', ipa:'pʁɔ.ʃɛ̃', vi:'kế tiếp', pos:'tính từ', g:'' },
{ fr:'seul', ipa:'sœl', vi:'một mình; duy nhất', pos:'tính từ', g:'' },
{ fr:'plein', ipa:'plɛ̃', vi:'đầy', pos:'tính từ', g:'' },
{ fr:'vide', ipa:'vid', vi:'trống', pos:'tính từ', g:'' },
{ fr:'propre', ipa:'pʁɔpʁ', vi:'sạch; của riêng', pos:'tính từ', g:'', note:'Đứng sau là «sạch», đứng trước là «riêng»: ma propre voiture.' },
{ fr:'sale', ipa:'sal', vi:'bẩn', pos:'tính từ', g:'' },
{ fr:'fort', ipa:'fɔʁ', vi:'mạnh; giỏi', pos:'tính từ', g:'' },
{ fr:'gentil', ipa:'ʒɑ̃.ti', vi:'tử tế', pos:'tính từ', g:'', note:'Giống cái gentille, lúc này chữ l mới đọc.' },
{ fr:'français', ipa:'fʁɑ̃.sɛ', vi:'tiếng Pháp; người Pháp', pos:'tính từ', g:'', note:'Viết hoa khi là người, viết thường khi là tiếng hay tính từ.' },
{ fr:'espagnol', ipa:'ɛs.pa.ɲɔl', vi:'tiếng Tây Ban Nha', pos:'tính từ', g:'' },
{ fr:'anglais', ipa:'ɑ̃.ɡlɛ', vi:'tiếng Anh', pos:'tính từ', g:'' },
{ fr:'vietnamien', ipa:'vjɛt.na.mjɛ̃', vi:'tiếng Việt; người Việt', pos:'tính từ', g:'' },

/* ---------- TỪ HỎI ---------- */
{ fr:'quoi', ipa:'kwa', vi:'cái gì', pos:'từ hỏi', g:'', note:'Dùng sau giới từ và cuối câu; đầu câu thì dùng que.' },
{ fr:'où', ipa:'u', vi:'ở đâu', pos:'từ hỏi', g:'' },
{ fr:'comment', ipa:'kɔ.mɑ̃', vi:'thế nào', pos:'từ hỏi', g:'' },
{ fr:'pourquoi', ipa:'puʁ.kwa', vi:'tại sao', pos:'từ hỏi', g:'' },
{ fr:'combien', ipa:'kɔ̃.bjɛ̃', vi:'bao nhiêu', pos:'từ hỏi', g:'' },
{ fr:'quel', ipa:'kɛl', vi:'nào, gì', pos:'từ hỏi', g:'', note:'Hợp giống và số: quel, quelle, quels, quelles.' },

/* ---------- SỐ ---------- */
{ fr:'zéro', ipa:'ze.ʁo', vi:'số không', pos:'số', g:'m' },
{ fr:'deux', ipa:'dø', vi:'hai', pos:'số', g:'' },
{ fr:'trois', ipa:'tʁwa', vi:'ba', pos:'số', g:'' },
{ fr:'quatre', ipa:'katʁ', vi:'bốn', pos:'số', g:'' },
{ fr:'cinq', ipa:'sɛ̃k', vi:'năm', pos:'số', g:'' },
{ fr:'six', ipa:'sis', vi:'sáu', pos:'số', g:'' },
{ fr:'sept', ipa:'sɛt', vi:'bảy', pos:'số', g:'', note:'Chữ p câm.' },
{ fr:'huit', ipa:'ɥit', vi:'tám', pos:'số', g:'' },
{ fr:'neuf', ipa:'nœf', vi:'chín; mới', pos:'số', g:'' },
{ fr:'dix', ipa:'dis', vi:'mười', pos:'số', g:'' },
{ fr:'onze', ipa:'ɔ̃z', vi:'mười một', pos:'số', g:'' },
{ fr:'douze', ipa:'duz', vi:'mười hai', pos:'số', g:'' },
{ fr:'treize', ipa:'tʁɛz', vi:'mười ba', pos:'số', g:'' },
{ fr:'quatorze', ipa:'ka.tɔʁz', vi:'mười bốn', pos:'số', g:'' },
{ fr:'quinze', ipa:'kɛ̃z', vi:'mười lăm', pos:'số', g:'' },
{ fr:'seize', ipa:'sɛz', vi:'mười sáu', pos:'số', g:'' },
{ fr:'vingt', ipa:'vɛ̃', vi:'hai mươi', pos:'số', g:'' },
{ fr:'trente', ipa:'tʁɑ̃t', vi:'ba mươi', pos:'số', g:'' },
{ fr:'quarante', ipa:'ka.ʁɑ̃t', vi:'bốn mươi', pos:'số', g:'' },
{ fr:'cinquante', ipa:'sɛ̃.kɑ̃t', vi:'năm mươi', pos:'số', g:'' },
{ fr:'soixante', ipa:'swa.sɑ̃t', vi:'sáu mươi', pos:'số', g:'' },
{ fr:'cent', ipa:'sɑ̃', vi:'một trăm', pos:'số', g:'' },
{ fr:'mille', ipa:'mil', vi:'một nghìn', pos:'số', g:'', note:'Không bao giờ thêm s: deux mille.' },
{ fr:'million', ipa:'mi.ljɔ̃', vi:'triệu', pos:'danh từ', g:'m' },
{ fr:'demi', ipa:'də.mi', vi:'một nửa', pos:'tính từ', g:'' },

/* ---------- THỨ VÀ THÁNG ---------- */
{ fr:'lundi', ipa:'lœ̃.di', vi:'thứ Hai', pos:'danh từ', g:'m', note:'Thứ và tháng của tiếng Pháp KHÔNG viết hoa.' },
{ fr:'mardi', ipa:'maʁ.di', vi:'thứ Ba', pos:'danh từ', g:'m' },
{ fr:'mercredi', ipa:'mɛʁ.kʁə.di', vi:'thứ Tư', pos:'danh từ', g:'m' },
{ fr:'jeudi', ipa:'ʒø.di', vi:'thứ Năm', pos:'danh từ', g:'m' },
{ fr:'vendredi', ipa:'vɑ̃.dʁə.di', vi:'thứ Sáu', pos:'danh từ', g:'m' },
{ fr:'samedi', ipa:'sam.di', vi:'thứ Bảy', pos:'danh từ', g:'m' },
{ fr:'dimanche', ipa:'di.mɑ̃ʃ', vi:'Chủ nhật', pos:'danh từ', g:'m' },
{ fr:'janvier', ipa:'ʒɑ̃.vje', vi:'tháng Một', pos:'danh từ', g:'m' },
{ fr:'février', ipa:'fe.vʁi.je', vi:'tháng Hai', pos:'danh từ', g:'m' },
{ fr:'mars', ipa:'maʁs', vi:'tháng Ba', pos:'danh từ', g:'m', note:'Chữ s ở đây đọc lên, khác với các từ khác kết thúc bằng s.' },
{ fr:'avril', ipa:'a.vʁil', vi:'tháng Tư', pos:'danh từ', g:'m' },
{ fr:'mai', ipa:'mɛ', vi:'tháng Năm', pos:'danh từ', g:'m' },
{ fr:'juin', ipa:'ʒɥɛ̃', vi:'tháng Sáu', pos:'danh từ', g:'m' },
{ fr:'juillet', ipa:'ʒɥi.jɛ', vi:'tháng Bảy', pos:'danh từ', g:'m' },
{ fr:'août', ipa:'ut', vi:'tháng Tám', pos:'danh từ', g:'m' },
{ fr:'septembre', ipa:'sɛp.tɑ̃bʁ', vi:'tháng Chín', pos:'danh từ', g:'m' },
{ fr:'octobre', ipa:'ɔk.tɔbʁ', vi:'tháng Mười', pos:'danh từ', g:'m' },
{ fr:'novembre', ipa:'nɔ.vɑ̃bʁ', vi:'tháng Mười một', pos:'danh từ', g:'m' },
{ fr:'décembre', ipa:'de.sɑ̃bʁ', vi:'tháng Mười hai', pos:'danh từ', g:'m' },

/* ---------- TÊN RIÊNG ---------- */
{ fr:'France', ipa:'fʁɑ̃s', vi:'nước Pháp', pos:'tên riêng', g:'f', note:'Tên nước giống cái nên đi với en: en France.' },
{ fr:'Paris', ipa:'pa.ʁi', vi:'Pa-ri', pos:'tên riêng', g:'' },
{ fr:'Lyon', ipa:'ljɔ̃', vi:'Li-ông (thành phố lớn thứ hai của Pháp)', pos:'tên riêng', g:'' },
{ fr:'Marseille', ipa:'maʁ.sɛj', vi:'Mác-xây (cảng lớn nhất nước Pháp)', pos:'tên riêng', g:'' },
{ fr:'Toulouse', ipa:'tu.luz', vi:'Tu-lu-dơ', pos:'tên riêng', g:'' },
{ fr:'Bordeaux', ipa:'bɔʁ.do', vi:'Boóc-đô', pos:'tên riêng', g:'' },
{ fr:'Nice', ipa:'nis', vi:'Ni-xơ', pos:'tên riêng', g:'' },
{ fr:'Strasbourg', ipa:'stʁaz.buʁ', vi:'Xtra-xbua', pos:'tên riêng', g:'' },
{ fr:'Lille', ipa:'lil', vi:'Lin', pos:'tên riêng', g:'' },
{ fr:'Nantes', ipa:'nɑ̃t', vi:'Năng-tơ', pos:'tên riêng', g:'' },
{ fr:'Seine', ipa:'sɛn', vi:'sông Seine', pos:'tên riêng', g:'f' },
{ fr:'Europe', ipa:'ø.ʁɔp', vi:'châu Âu', pos:'tên riêng', g:'f' },
{ fr:'Vietnam', ipa:'vjɛt.nam', vi:'Việt Nam', pos:'tên riêng', g:'m' },
{ fr:'Hanoï', ipa:'a.nɔj', vi:'Hà Nội', pos:'tên riêng', g:'' },
{ fr:'Belgique', ipa:'bɛl.ʒik', vi:'nước Bỉ', pos:'tên riêng', g:'f' },
{ fr:'Suisse', ipa:'sɥis', vi:'Thuỵ Sĩ', pos:'tên riêng', g:'f' },
{ fr:'Canada', ipa:'ka.na.da', vi:'Ca-na-đa', pos:'tên riêng', g:'m' },
{ fr:'Espagne', ipa:'ɛs.paɲ', vi:'Tây Ban Nha', pos:'tên riêng', g:'f' },
{ fr:'Italie', ipa:'i.ta.li', vi:'nước Ý', pos:'tên riêng', g:'f' },
{ fr:'Allemagne', ipa:'al.maɲ', vi:'nước Đức', pos:'tên riêng', g:'f' },
{ fr:'Marie', ipa:'ma.ʁi', vi:'Ma-ri (tên nữ)', pos:'tên riêng', g:'f' },
{ fr:'Sophie', ipa:'sɔ.fi', vi:'Xô-phi (tên nữ)', pos:'tên riêng', g:'f' },
{ fr:'Claire', ipa:'klɛʁ', vi:'Cle (tên nữ)', pos:'tên riêng', g:'f' },
{ fr:'Camille', ipa:'ka.mij', vi:'Ca-mi (tên dùng cho cả nam và nữ)', pos:'tên riêng', g:'' },
{ fr:'Julie', ipa:'ʒy.li', vi:'Giuy-li (tên nữ)', pos:'tên riêng', g:'f' },
{ fr:'Léa', ipa:'le.a', vi:'Lê-a (tên nữ)', pos:'tên riêng', g:'f' },
{ fr:'Marc', ipa:'maʁk', vi:'Mác (tên nam)', pos:'tên riêng', g:'m' },
{ fr:'Paul', ipa:'pɔl', vi:'Pôn (tên nam)', pos:'tên riêng', g:'m' },
{ fr:'Pierre', ipa:'pjɛʁ', vi:'Pi-e (tên nam); hòn đá', pos:'tên riêng', g:'m' },
{ fr:'Jean', ipa:'ʒɑ̃', vi:'Giăng (tên nam)', pos:'tên riêng', g:'m' },
{ fr:'Luc', ipa:'lyk', vi:'Luych (tên nam)', pos:'tên riêng', g:'m' },
{ fr:'Antoine', ipa:'ɑ̃.twan', vi:'Ăng-toan (tên nam)', pos:'tên riêng', g:'m' },
{ fr:'Thomas', ipa:'tɔ.ma', vi:'Tô-ma (tên nam)', pos:'tên riêng', g:'m', note:'Chữ s cuối câm.' },
{ fr:'Nicolas', ipa:'ni.kɔ.la', vi:'Ni-cô-la (tên nam)', pos:'tên riêng', g:'m' },
{ fr:'Julien', ipa:'ʒy.ljɛ̃', vi:'Giuy-liêng (tên nam)', pos:'tên riêng', g:'m' },
{ fr:'Quan', ipa:'kwan', vi:'Quân (tên nam, người Việt)', pos:'tên riêng', g:'m' },
{ fr:'Noël', ipa:'nɔ.ɛl', vi:'Nô-en, Giáng sinh', pos:'tên riêng', g:'m', note:'Dấu hai chấm trên chữ e báo rằng o và e đọc tách ra.' }

];

if (typeof window !== 'undefined') window.WORDS_CORE_FR = WORDS_CORE_FR;
