const { JSDOM, VirtualConsole } = require('jsdom');
const fs = require('fs');
const dir = '/sessions/serene-blissful-faraday/mnt/N1.NGOAI NGU/langlab';
const html = fs.readFileSync(dir + '/dist/langlab.html', 'utf8');
const errors = [], spoken = [];
const vc = new VirtualConsole();
vc.on('jsdomError', e => { if (!/Not implemented/.test(e.message)) errors.push('jsdomError: ' + e.message); });
vc.on('error', (...a) => errors.push('console.error: ' + a.join(' ')));
const dom = new JSDOM(html, { runScripts:'dangerously', pretendToBeVisual:true, virtualConsole:vc, url:'http://localhost:9999/', beforeParse(window){
  window.Element.prototype.getTotalLength = () => 60; window.Element.prototype.getPointAtLength = () => ({x:20,y:20});
  Object.defineProperty(window.Element.prototype,'transform',{get(){return{baseVal:{consolidate(){return null;}}};},configurable:true});
  window.Element.prototype.getBBox = () => ({x:0,y:0,width:100,height:100});
  window.Element.prototype.getBoundingClientRect = () => ({left:0,top:0,width:300,height:300,right:300,bottom:300});
  window.Element.prototype.scrollIntoView = function(){};
  window.HTMLCanvasElement.prototype.getContext = () => new Proxy({}, {get:()=>()=>{}});
  window.scrollTo=()=>{}; window.confirm=()=>true;
  window.matchMedia=()=>({matches:false,addEventListener(){},removeEventListener(){},addListener(){},removeListener(){}});
  window.fetch=()=>Promise.reject(new Error('no server'));
  window.speechSynthesis={speaking:false,cancel(){},resume(){},pause(){},getVoices(){return[{lang:'ja-JP',name:'JA'},{lang:'ko-KR',name:'KO'},{lang:'zh-CN',name:'ZH'},{lang:'ru-RU',name:'RU'}];},addEventListener(){},removeEventListener(){},speak(u){ spoken.push([u.lang,u.text]); }};
  window.SpeechSynthesisUtterance=function(t){this.text=t;};
}});
const win=dom.window,d=win.document;
const click=s=>{const el=typeof s==='string'?d.querySelector(s):s; if(!el) throw new Error('không thấy '+s); el.dispatchEvent(new win.MouseEvent('click',{bubbles:true}));};
const n=s=>d.querySelectorAll(s).length, body=()=>d.getElementById('view').textContent;
let pass=0,fail=0; const check=(name,fn)=>{ try{ const r=fn(); if(r===false) throw new Error('sai'); pass++; console.log('ok   '+name);}catch(e){ fail++; console.log('FAIL '+name+' — '+e.message);} };
(async()=>{
  await new Promise(r=>setTimeout(r,150));
  if (errors.length) console.log('BOOT ERRORS:', errors.slice(0,3).join(' | '));
  check('kho fact: 320 mẩu, 64 mỗi ngôn ngữ, đủ hình minh hoạ, không trùng tiêu đề', ()=>{
    const F=win.eval('FACTS')||[], A=win.eval('FACT_ART')||{};
    const by={}; F.forEach(f=>by[f.lang]=(by[f.lang]||0)+1);
    const seen=new Set(); const dup=F.filter(f=>{const k=f.lang+'|'+f.title; if(seen.has(k))return true; seen.add(k); return false;});
    return F.length===320 && ['ko','zh','ru','ja','en'].every(l=>by[l]===64) && dup.length===0 && F.every(f=>!!A[f.art] && f.cat && f.title && f.body && f.extra && f.word && f.word.t && f.word.vi);
  });
  check('menu mọi ngôn ngữ đều có «Bạn có biết?»', ()=> n('[data-go="facts"]')===5);
  click('[data-go="facts"]');
  check('màn Bạn có biết?: chip ngôn ngữ + chip chủ đề + thẻ fact', ()=> n('[data-facts-lang]')===5 && n('[data-facts-cat]')>=7 && n('.fact-card')===64 && n('.fact-card .fact-art')===64);
  check('lọc theo chủ đề: chọn «Ẩm thực» còn ít thẻ hơn', ()=>{ const all=n('.fact-card'); const cat=[...d.querySelectorAll('[data-facts-cat]')].find(b=>/Ẩm thực/.test(b.textContent)); click(cat); const few=n('.fact-card'); return few>0 && few<all; });
  check('đổi sang tiếng Nhật: 64 thẻ của Nhật Bản', ()=>{ click('[data-facts-lang="ja"]'); return n('.fact-card')===64 && /Nhật Bản/.test(body()); });
  check('có kho fact tiếng Anh, nút nghe dùng giọng en', ()=>{ click('[data-facts-lang="en"]'); const ok = n('.fact-card')===64 && /Anh – Mỹ/.test(body()); spoken.length=0; click('.fact-card'); const b=d.querySelector('#factModal .fact-word .icon-btn'); if(b) click(b); const voice = spoken.length===1 && /^en/.test(spoken[0][0]); click('#factModal [data-fact-close]'); click('[data-facts-lang="ja"]'); return ok && voice; });
  check('mở thẻ → bảng chi tiết có hình, nội dung, «Thú vị hơn nữa», từ khoá', ()=>{ click('.fact-card'); const m=d.querySelector('#factModal.open'); return !!m && n('#factModal .fact-art')===1 && /Thú vị hơn nữa/.test(m.textContent) && n('#factModal .fact-word')===1 && n('#factModal [data-fact-next]')===1; });
  check('nút nghe trong bảng dùng đúng giọng của ngôn ngữ', ()=>{ spoken.length=0; const b=d.querySelector('#factModal .fact-word .icon-btn'); if(!b) return false; click(b); return spoken.length===1 && spoken[0][0]==='ja-JP'; });
  check('«Fact khác» đổi sang mẩu khác', ()=>{ const t1=d.querySelector('#factModal h3').textContent; click('#factModal [data-fact-next]'); const t2=d.querySelector('#factModal h3').textContent; return t1!==t2; });
  check('Esc đóng bảng', ()=>{ d.dispatchEvent(new win.KeyboardEvent('keydown',{key:'Escape',bubbles:true})); return !d.querySelector('#factModal.open'); });
  check('bong bóng: hiện khi đang học tiếng Hàn, bấm mở bảng, ✕ ẩn đi', ()=>{
    win.__facts.store.set('factLastAt',0); click('[data-go="home"]');
    win.__facts.show(win.__facts.pick('ko'));
    const shown = n('#factBubble.show')===1 && /Bạn có biết/.test(d.querySelector('#factBubble').textContent);
    click('#factBubble [data-fact-open]');
    const opened = !!d.querySelector('#factModal.open');
    click('#factModal [data-fact-close]');
    win.__facts.show(win.__facts.pick('ko')); click('#factBubble [data-fact-hide]');
    return shown && opened && n('#factBubble.show')===0;
  });
  check('bong bóng chỉ lấy fact của ngôn ngữ đang học', ()=>{ click('[data-go="zh_home"]'); const lg=win.__facts.lang(); const f=win.__facts.pick(lg); return lg==='zh' && f.lang==='zh'; });
  check('bong bóng có tay cầm và kéo rê đặt được chỗ khác', ()=>{
    win.__facts.store.set('factsOn', true);
    win.__facts.resetPos();
    win.__facts.show(win.__facts.pick('ko'));
    const el = d.querySelector('#factBubble');
    const hasGrip = !!el.querySelector('[data-fact-grip]');
    const down = new win.PointerEvent('pointerdown', { bubbles:true, clientX:60, clientY:600 });
    el.querySelector('.fact-bubble-main').dispatchEvent(down);
    d.dispatchEvent(new win.PointerEvent('pointermove', { bubbles:true, clientX:420, clientY:190 }));
    const dragging = el.classList.contains('dragging');
    d.dispatchEvent(new win.PointerEvent('pointerup', { bubbles:true, clientX:420, clientY:190 }));
    const moved = !!el.style.left && !!el.style.top && el.style.right === 'auto';
    const saved = win.__facts.store.get('factBubblePos', null);
    return hasGrip && dragging && moved && !!saved && !el.classList.contains('dragging');
  });
  check('vị trí bong bóng được nhớ lại, và trả về góc cũ được', ()=>{
    win.__facts.store.set('factBubblePos', { left:300, top:150 });
    win.__facts.show(win.__facts.pick('ko'));
    const el = d.querySelector('#factBubble');
    const restored = el.style.left === '300px' && el.style.top === '150px';
    win.__facts.resetPos();
    const cleared = !el.style.left && !win.__facts.store.get('factBubblePos', null);
    return restored && cleared;
  });
  check('kéo xong thì cú click không mở luôn bảng fact', ()=>{
    win.__facts.resetPos();
    win.__facts.show(win.__facts.pick('ko'));
    const el = d.querySelector('#factBubble'), main = el.querySelector('.fact-bubble-main');
    const m0 = d.querySelector('#factModal'); if (m0) m0.classList.remove('open');
    main.dispatchEvent(new win.PointerEvent('pointerdown', { bubbles:true, clientX:60, clientY:600 }));
    d.dispatchEvent(new win.PointerEvent('pointermove', { bubbles:true, clientX:300, clientY:300 }));
    d.dispatchEvent(new win.PointerEvent('pointerup', { bubbles:true, clientX:300, clientY:300 }));
    click('#factBubble [data-fact-open]');
    const notOpened = n('#factModal.open') === 0 && n('#factBubble.show') === 1;
    /* bấm bình thường (không kéo) thì vẫn mở được */
    win.__facts.show(win.__facts.pick('ko'));
    click('#factBubble [data-fact-open]');
    const opensNormally = n('#factModal.open') === 1;
    d.querySelector('#factModal').classList.remove('open');
    win.__facts.resetPos();
    return notOpened && opensNormally;
  });
  check('tắt bong bóng lưu vào cài đặt, bật lại được', ()=>{ win.__facts.store.set('factsOn',false); const off=win.__facts.on()===false; win.__facts.schedule(); const hidden=n('#factBubble.show')===0; win.__facts.store.set('factsOn',true); return off && hidden && win.__facts.on()===true; });
  check('không có lỗi console', ()=> errors.length===0);
  if (errors.length) console.log('ERRORS:', errors.slice(0,4).join(' | '));
  console.log('\n'+pass+' đạt / '+fail+' lỗi'); process.exit(fail?1:0);
})();
