const { JSDOM, VirtualConsole } = require('jsdom');
const fs = require('fs');
const dir = '/sessions/serene-blissful-faraday/mnt/N1.NGOAI NGU/langlab';
const html = fs.readFileSync(dir + '/dist/langlab.html', 'utf8');
const errors = [];
const vc = new VirtualConsole();
vc.on('jsdomError', e => { if (!/Not implemented/.test(e.message)) errors.push('jsdomError: ' + e.message); });
vc.on('error', (...a) => errors.push('console.error: ' + a.join(' ')));
const spoken = [];
const dom = new JSDOM(html, { runScripts:'dangerously', pretendToBeVisual:true, virtualConsole:vc, url:'http://localhost:9999/', beforeParse(window){
  window.Element.prototype.getTotalLength = () => 60; window.Element.prototype.getPointAtLength = () => ({x:20,y:20});
  Object.defineProperty(window.Element.prototype,'transform',{get(){return{baseVal:{consolidate(){return null;}}};},configurable:true});
  window.Element.prototype.getBBox = () => ({x:0,y:0,width:100,height:100});
  window.Element.prototype.getBoundingClientRect = () => ({left:0,top:0,width:250,height:250,right:250,bottom:250});
  window.Element.prototype.scrollIntoView = function(){};
  window.HTMLCanvasElement.prototype.getContext = () => new Proxy({}, {get:()=>()=>{}});
  window.scrollTo=()=>{}; window.confirm=()=>true;
  window.matchMedia=()=>({matches:false,addEventListener(){},removeEventListener(){},addListener(){},removeListener(){}});
  window.fetch=()=>Promise.reject(new Error('no server'));
  window.speechSynthesis={speaking:false,cancel(){},resume(){},pause(){},getVoices(){return[{lang:'zh-CN',name:'Chinese'}];},addEventListener(){},removeEventListener(){},speak(u){ spoken.push(u.text); }};
  window.SpeechSynthesisUtterance=function(t){this.text=t;};
}});
const win=dom.window,d=win.document;
const click=s=>{const el=typeof s==='string'?d.querySelector(s):s; if(!el) throw new Error('không thấy '+s); el.dispatchEvent(new win.MouseEvent('click',{bubbles:true}));};
const n=s=>d.querySelectorAll(s).length, body=()=>d.getElementById('view').textContent;
let pass=0,fail=0; const check=(name,fn)=>{ try{ const r=fn(); if(r===false) throw new Error('sai'); pass++; console.log('ok   '+name);}catch(e){ fail++; console.log('FAIL '+name+' — '+e.message);} };
(async()=>{
  await new Promise(r=>setTimeout(r,120));
  if (errors.length) console.log('BOOT ERRORS:', errors.slice(0,4).join(' | '));
  check('boot không lỗi', ()=>errors.length===0);
  click('[data-go="zh_exam"]');
  check('danh sách đề: giới thiệu HSK + 5 đề đầy đủ + 5 kiểm tra nhanh', ()=> body().includes('HSK là gì') && n('[data-hsk-start]:not([data-hsk-start="quick"])')===5 && n('[data-hsk-start="quick"]')===5 && body().includes('chinesetest.cn'));
  click('[data-hsk-start="hsk3-a"]');
  check('mở đề HSK3: thanh điều khiển + đồng hồ 90:00 + 80 câu + 3 tab phần', ()=> !!d.getElementById('hskTimer') && d.getElementById('hskTimer').textContent==='90:00' && n('.hsk-q')===80 && n('.hsk-tab')===3 && n('[data-hsk-pause]')===1 && n('[data-hsk-submit]')===2 && n('[data-hsk-exit]')===1);
  check('nghe câu 1: phát script (bỏ nhãn 女/男) và giảm số lần', ()=>{ const b=d.querySelector('[data-hsk-play="1"]'); click(b); const ok1=spoken.length===1 && !/[女男]：/.test(spoken[0]) && b.querySelector('small').textContent.includes('1'); click(b); return ok1 && spoken.length===2 && b.disabled; });
  check('chọn đáp án câu 1 (bank) → tab 听力 1/40', ()=>{ click('[data-hsk-ans="1"][data-opt="1"]'); return d.querySelector('[data-hsk-ans="1"][data-opt="1"]').classList.contains('on') && d.querySelector('.hsk-tab').textContent.includes('1/40'); });
  check('tạm dừng: đề bị che + nút Tiếp tục; tiếp tục lại hiện đề', ()=>{ click('[data-hsk-pause]'); const p = n('.hsk-paused')===1 && d.querySelector('.topik-quiz').classList.contains('paused'); click('.hsk-paused [data-hsk-pause]'); return p && n('.hsk-paused')===0 && d.querySelector('[data-hsk-ans="1"][data-opt="1"]').classList.contains('on'); });
  check('sắp xếp câu 71: bấm từ theo thứ tự → dòng đáp án', ()=>{ ['1','0','2','3'].forEach(ci=>click(`[data-hsk-ord="71"][data-ci="${ci}"]`)); const line=d.querySelector('#hskQ71 .hsk-order-line').textContent; return line.includes('请把窗户打开') && n('[data-hsk-ord-clear="71"]')===1; });
  check('viết chữ câu 76: nhập 床', ()=>{ const inp=d.querySelector('[data-hsk-in="76"]'); inp.value='床'; inp.dispatchEvent(new win.Event('input',{bubbles:true})); return true; });
  await new Promise(r=>setTimeout(r,500));
  check('lưu tiến độ vào localStorage (sau debounce ô nhập)', ()=>{ const s=JSON.parse(win.localStorage.getItem('langlab.hskExam')); return s && s.testId==='hsk3-a' && s.answers['1']===1 && s.answers['76']==='床' && Array.isArray(s.answers['71']); });
  check('thoát ra danh sách → thẻ "đề đang làm dở" → Tiếp tục làm (ở trạng thái tạm dừng)', ()=>{ click('[data-hsk-exit]'); const a = n('[data-hsk-resume]')===1 && body().includes('đề đang làm dở'); click('[data-hsk-resume]'); return a && n('.hsk-paused')===1 && n('.hsk-q')===80; });
  click('.hsk-paused [data-hsk-pause]');
  check('nộp bài → kết quả theo 3 kỹ năng, câu 1 đúng, 71 & 76 đúng', ()=>{ click('[data-hsk-submit]'); const ok = body().includes('Kết quả') && n('.hsk-sec')===3; const q1=d.getElementById('hskQ1'), q71=d.getElementById('hskQ71'), q76=d.getElementById('hskQ76'); return ok && q1.classList.contains('ok') && q71.classList.contains('ok') && q76.classList.contains('ok') && body().includes('Giải thích') && n('.hsk-script')>=40; });
  check('lọc "Chỉ hiện câu sai" → ẩn câu đúng', ()=>{ click('[data-hsk-filter="wrong"]'); return !d.getElementById('hskQ1') && !!d.getElementById('hskQ2'); });
  check('điểm: 3 câu đúng/80 → dưới ngưỡng, hiện "chưa đạt"', ()=> body().includes('chưa đạt'));
  check('sau khi nộp, không còn đề lưu dở', ()=> win.localStorage.getItem('langlab.hskExam')==='null');
  click('[data-hsk-home]');
  check('về danh sách đề', ()=> n('[data-hsk-start]')>=8);
  click('[data-hsk-start="quick"][data-hsk-level="hsk2"]');
  check('kiểm tra nhanh HSK2: 20 câu, 8 phút, không có nút nghe', ()=> n('.hsk-q')===20 && d.getElementById('hskTimer').textContent==='08:00' && n('[data-hsk-play]')===0);
  // chọn đúng bằng cách đọc explain? không có; chọn đáp án đầu tiên rồi nộp
  click('[data-hsk-ans="1"][data-opt="0"]'); click('[data-hsk-submit]');
  check('nộp đề nhanh (có câu chưa làm, confirm=true) → kết quả %', ()=> body().includes('/100 điểm'));
  click('[data-hsk-retry]');
  check('Làm lại đề nhanh → đề mới 20 câu', ()=> n('.hsk-q')===20 && !!d.getElementById('hskTimer'));
  click('[data-hsk-exit]');
  click('[data-hsk-start="hsk1-a"]');
  check('HSK1: 40 câu, có tranh + pinyin, bank A–F', ()=> n('.hsk-q')===40 && n('.hsk-pic')>=10 && n('.hsk-py')>=15 && n('.hsk-bank')>=4);
  check('HSK2: 60 câu', ()=>{ click('[data-hsk-exit]'); click('[data-hsk-start="hsk2-a"]'); return n('.hsk-q')===60; });
  check('HSK4: 100 câu, 1 lần nghe, có ô viết câu (5) + sắp xếp đoạn', ()=>{ click('[data-hsk-exit]'); click('[data-hsk-start="hsk4-a"]'); return n('.hsk-q')===100 && d.querySelector('[data-hsk-play="1"] small').textContent.includes('1') && n('textarea[data-hsk-in]')===5 && n('.hsk-order')===20 && d.getElementById('hskTimer').textContent==='105:00'; });
  check('HSK4 câu 96: viết câu có từ 坚持 → chấm đúng', ()=>{ const ta=d.querySelector('[data-hsk-in="96"]'); ta.value='我每天都坚持学习汉语。'; ta.dispatchEvent(new win.Event('input',{bubbles:true})); click('[data-hsk-submit]'); return d.getElementById('hskQ96').classList.contains('ok') && body().includes('Bài mẫu tham khảo'); });
  check('HSK5: 100 câu, đoạn văn chung của phần (hsk-part-p) + 2 bài viết', ()=>{ click('[data-hsk-home]'); click('[data-hsk-start="hsk5-a"]'); return n('.hsk-q')===100 && n('.hsk-part-p')===9 && n('textarea[data-hsk-in]')===2 && n('.hsk-words')>=1; });
  check('HSK5 câu 99: đoạn ≥80 chữ đủ 5 từ → đúng; câu 100 ngắn → sai', ()=>{ const ta=d.querySelector('[data-hsk-in="99"]'); ta.value='每个人都有自己的梦想，但实现梦想的路上总会遇到困难。我的朋友小李从小想当歌手，家里人都反对，他一边打工一边练习，坚持了五年，终于在去年的比赛中获得了第一名。他的成功告诉我：只要不放弃，梦想就不会离你太远。'; ta.dispatchEvent(new win.Event('input',{bubbles:true})); const t2=d.querySelector('[data-hsk-in="100"]'); t2.value='今天毕业了。'; t2.dispatchEvent(new win.Event('input',{bubbles:true})); const c=d.getElementById('hskCnt99').textContent; click('[data-hsk-submit]'); return /\d+ chữ Hán/.test(c) && d.getElementById('hskQ99').classList.contains('ok') && d.getElementById('hskQ100').classList.contains('bad'); });
  console.log('\n'+pass+' đạt / '+fail+' lỗi'); process.exit(fail?1:0);
})();
