const { JSDOM, VirtualConsole } = require('jsdom');
const fs = require('fs');
const dir = '/sessions/serene-blissful-faraday/mnt/N1.NGOAI NGU/langlab';
const html = fs.readFileSync(dir + '/dist/langlab.html', 'utf8');
const errors = [], spoken = [];
const vc = new VirtualConsole();
vc.on('jsdomError', e => { if (!/Not implemented/.test(e.message)) errors.push('jsdomError: ' + e.message); });
vc.on('error', (...a) => errors.push('console.error: ' + a.join(' ')));
const dom = new JSDOM(html, { runScripts:'dangerously', pretendToBeVisual:true, virtualConsole:vc, url:'http://localhost:9999/', beforeParse(window){
  window.Element.prototype.getTotalLength = () => 60; window.Element.prototype.getPointAtLength = () => ({x:20,y:20});
  Object.defineProperty(window.Element.prototype,'transform',{get(){return{baseVal:{consolidate(){return null;}}};},configurable:true});
  window.Element.prototype.getBBox = () => ({x:0,y:0,width:100,height:100});
  window.Element.prototype.getBoundingClientRect = () => ({left:0,top:0,width:300,height:300,right:300,bottom:300});
  window.Element.prototype.scrollIntoView = function(){};
  window.HTMLCanvasElement.prototype.getContext = () => new Proxy({}, {get:()=>()=>{}});
  window.scrollTo=()=>{}; window.confirm=()=>true;
  window.matchMedia=()=>({matches:false,addEventListener(){},removeEventListener(){},addListener(){},removeListener(){}});
  window.fetch=()=>Promise.reject(new Error('no server'));
  window.speechSynthesis={speaking:false,cancel(){},resume(){},pause(){},getVoices(){return[{lang:'ja-JP',name:'Japanese'},{lang:'ru-RU',name:'Russian'}];},addEventListener(){},removeEventListener(){},speak(u){ spoken.push([u.lang,u.text]); }};
  window.SpeechSynthesisUtterance=function(t){this.text=t;};
}});
const win=dom.window,d=win.document;
const click=s=>{const el=typeof s==='string'?d.querySelector(s):s; if(!el) throw new Error('không thấy '+s); el.dispatchEvent(new win.MouseEvent('click',{bubbles:true}));};
const n=s=>d.querySelectorAll(s).length, body=()=>d.getElementById('view').textContent;
let pass=0,fail=0; const check=(name,fn)=>{ try{ const r=fn(); if(r===false) throw new Error('sai'); pass++; console.log('ok   '+name);}catch(e){ fail++; console.log('FAIL '+name+' — '+e.message);} };
(async()=>{
  await new Promise(r=>setTimeout(r,120));
  if (errors.length) console.log('BOOT ERRORS:', errors.slice(0,4).join(' | '));
  check('boot không lỗi', ()=>errors.length===0);
  check('menu Tiếng Nhật: 10 mục (có «Bạn có biết?») + badge N5–N2', ()=> n('#jaDrop')===1 && n('.nav-menu[aria-label="Tiếng Nhật"] .nav-mi')===10 && n('.nav-menu[aria-label="Tiếng Nhật"] [data-go="facts"]')===1 && /N5/.test(d.querySelector('[data-go="ja_home"] .mi-count').textContent));
  click('[data-go="ja_home"]');
  check('Khoá học Nhật: data-lang=ja, 4 thẻ nền tảng, 4 chip cấp (4 active), 20 bài N5', ()=> d.documentElement.getAttribute('data-lang')==='ja' && n('.zh-found-card')===4 && n('.level-chip[data-ja-level]')===4 && n('.level-chip[data-ja-level]:not([disabled])')===4 && n('[data-ja-lesson]')===20 && d.getElementById('crumb').textContent.includes('Tiếng Nhật'));
  check('theme-color đổi sang đỏ–trắng Nhật', ()=> d.querySelector('meta[name="theme-color"]').getAttribute('content')==='#FFF4F4');
  click('[data-ja-lesson="1"]');
  check('bài 1: 3 ngữ pháp, 20 từ, furigana (ruby), token bấm được, kanji của bài, hội thoại', ()=> n('.zh-gram')===3 && n('.zh-word')===20 && n('ruby')>=5 && n('.zc.ja-tok')>=15 && n('.ja-kcard')===5 && n('.zh-line')===5 && d.getElementById('crumb').textContent.includes('Bài 01'));
  check('ẩn/hiện furigana', ()=>{ click('[data-ja-furi]'); const off=n('article.ja-rt-off')===1; click('[data-ja-furi]'); return off && n('article.ja-rt-off')===0; });
  check('nghe: giọng ja-JP, bỏ furigana và dấu cách', ()=>{ spoken.length=0; click('.zh-line [data-ja-speak]'); return spoken.length===1 && spoken[0][0]==='ja-JP' && !/\[|\s/.test(spoken[0][1]) && /田中/.test(spoken[0][1]); });
  check('bấm token «学生» → mục từ «学生» có kana, romaji, kanji thành phần, ví dụ', ()=>{ const w=[...d.querySelectorAll('.zh-line [data-jaw]')].find(e=>e.dataset.jaw==='学生'); click(w); const en=d.getElementById('jaEntry'); return !!en && /学生/.test(en.querySelector('.ru-entry-word').textContent) && /がくせい/.test(en.textContent) && /gakusei/.test(en.textContent) && n('#jaEntry .ja-kcard')===2 && n('#jaEntry .ru-ex-item')>=1; });
  check('từ điển: gõ dạng đã chia «食べました» → gợi ý từ gốc 食べる; mở mục có bảng chia 16 dạng', ()=>{ let q=d.getElementById('jaq'); q.value='食べました'; q.dispatchEvent(new win.Event('input',{bubbles:true})); const note=/dạng biến đổi của/.test((d.querySelector('#jaResults .ru-lemma-note')||{textContent:''}).textContent); click('#jaResults .zh-res'); const en=d.getElementById('jaEntry'); return note && !!en && /食べる/.test(en.querySelector('.ru-entry-word').textContent) && n('#jaEntry .ru-tbl-verb tbody tr')===16 && /食べて/.test(en.textContent) && /nhóm II/.test(en.textContent); });
  check('từ điển: gõ romaji «gakusei» ra 学生; gõ nghĩa Việt «sinh viên» ra', ()=>{ click('[data-ja-entry-close]'); let q=d.getElementById('jaq'); q.value='gakusei'; q.dispatchEvent(new win.Event('input',{bubbles:true})); const a=[...d.querySelectorAll('#jaResults .zh-res-hz')].some(e=>e.textContent==='学生'); q=d.getElementById('jaq'); q.value='sinh viên'; q.dispatchEvent(new win.Event('input',{bubbles:true})); const b=n('#jaResults .zh-res')>=1; return a&&b; });
  check('mục từ tính từ «新しい»: bảng 12 dạng có 新しくない, 新しかった', ()=>{ let q=d.getElementById('jaq'); q.value='新しい'; q.dispatchEvent(new win.Event('input',{bubbles:true})); click('#jaResults .zh-res'); const en=d.getElementById('jaEntry'); return !!en && n('#jaEntry .ru-tbl tbody tr')===12 && /新しくない/.test(en.textContent) && /新しかった/.test(en.textContent); });
  check('lemmatize: 行った→行く, 飲んで→飲む, 来ました→来る, よかった→いい, 読みたい→読む', ()=>{ const R=win.__jaDict; const t=(f,k)=>R.lemmatize(f).indexOf(k)>=0; return t('行った','行く') && t('飲んで','飲む') && t('来ました','来る') && t('よかった','いい') && t('読みたい','読む'); });
  click('[data-go="ja_kana"]');
  check('Kana: 46 ô cơ bản (bảng 5 cột), chi tiết chữ あ với mẹo nhớ, âm đục 25, âm ghép 33, 8 quy tắc', ()=> n('.ja-kana-grid:not(.yoon) .ja-kana-cell:not(.empty)')===46+25 && /Như chữ «a»/.test(d.getElementById('jaKanaDetail').textContent) && n('.ja-kana-grid.yoon .ja-kana-cell')===33 && n('.ru-phon-card')===8);
  check('bấm chữ き → chi tiết đổi; chuyển sang Katakana hiện キ', ()=>{ click('.ja-kana-cell[data-ja-kana="き"]'); const a=/Chìa «khoá»/.test(d.getElementById('jaKanaDetail').textContent); click('[data-ja-kanaset="katakana"]'); const b=n('.ja-kana-cell[data-ja-kana="キ"]')===1 && d.querySelector('#jaKanaDetail .hz').dataset.hz==='キ'; click('[data-ja-kanaset="hiragana"]'); return a&&b; });
  click('[data-go="ja_kanji"]');
  check('Kanji N5: lưới ≥ 100 chữ, chi tiết có Hán–Việt, On/Kun, ví dụ, hoạt hình nét (data-src=jp)', ()=> n('.ja-kanji-grid .ja-kcard')>=100 && /NHẤT|Hán/.test(d.querySelector('.ja-kanji-info').textContent) && n('.ja-kanji-detail .hz[data-src="jp"]')===1 && n('.ja-kanji-ex .ru-ex')>=2);
  check('bấm 学 → chi tiết HỌC, từ đã học chứa 学', ()=>{ click('.ja-kcard[data-ja-kanji="学"]'); const info=d.querySelector('.ja-kanji-info').textContent; return /HỌC/.test(info) && /学生/.test(info); });
  check('Kanji N4: chip N4 → lưới 163 chữ + phần N3 xuất hiện sớm; chi tiết 銀 NGÂN', ()=>{ click('[data-ja-klevel="n4"]'); const g=n('.ja-kanji-grid'); const first=d.querySelector('.ja-kanji-grid').querySelectorAll('.ja-kcard').length; click('.ja-kcard[data-ja-kanji="銀"]'); const info=d.querySelector('.ja-kanji-info').textContent; click('[data-ja-klevel="n5"]'); return g===2 && first===163 && /NGÂN/.test(info) && /銀行/.test(info); });
  click('[data-go="ja_home"]');
  check('N4: chọn cấp N4 → 20 bài; bài 12 (受身形) có 5 ngữ pháp, ≥ 25 từ, kanji 世界, hội thoại 7 dòng có furigana', ()=>{ click('[data-ja-level="n4"]'); const c=n('[data-ja-lesson]')===20; click('[data-ja-lesson="12"]'); return c && n('.zh-gram')===5 && n('.zh-word-hz.ja-word')>=25 && n('.ja-kcard[data-ja-kanji="世"]')===1 && n('.zh-line')===7 && n('.zh-line ruby')>=20 && /褒められました/.test(body()); });
  check('N4: bấm token «踏まれました» → mục từ 踏む có bảng chia (bị động 踏まれる, sai khiến 踏ませる)', ()=>{ const w=[...d.querySelectorAll('.ja-tok')].find(e=>e.dataset.jaw==='踏まれました'); if(!w) return false; click(w); const t=d.getElementById('jaEntry').textContent; return /踏む/.test(t) && /踏まれる/.test(t) && /踏ませる/.test(t) && /giẫm/.test(t); });
  check('lemmatize N4: 帰らせて→帰る, 読めれば→読める/読む, 食べさせられた→食べる, 行こう→行く', ()=>{ const L=win.__jaDict.lemmatize; return L('帰らせて').includes('帰る') && (L('読めれば').includes('読む')||L('読めれば').includes('読める')) && L('食べさせられた').includes('食べる') && L('行こう').includes('行く'); });
  check('N4: bài 20 敬語 có いらっしゃる/申す; bài 1 có 〜んです', ()=>{ click('[data-go="ja_home"]'); click('[data-ja-level="n4"]'); click('[data-ja-lesson="20"]'); const a=/いらっしゃる/.test(body()) && /申す/.test(body()); click('[data-go="ja_home"]'); click('[data-ja-lesson="1"]'); const b=/んです/.test(body()); click('[data-go="ja_home"]'); click('[data-ja-level="n5"]'); return a && b; });
  check('Kanji N3: chip N3 → lưới 373 chữ + phần N2 xuất hiện sớm; chi tiết 政 CHÍNH', ()=>{ click('[data-go="ja_kanji"]'); click('[data-ja-klevel="n3"]'); const first=d.querySelector('.ja-kanji-grid').querySelectorAll('.ja-kcard').length; const g=n('.ja-kanji-grid'); click('.ja-kcard[data-ja-kanji="政"]'); const info=d.querySelector('.ja-kanji-info').textContent; click('[data-ja-klevel="n5"]'); return first===373 && g===2 && /CHÍNH/.test(info) && /政治/.test(info); });
  check('N3: cấp N3 → 20 bài; bài 3 (わけ) 5 ngữ pháp, ≥ 20 từ, kanji ≥ 15, hội thoại 7 dòng; bài 14 có 弊社/申す; bài 20 có 乾杯', ()=>{ click('[data-go="ja_home"]'); click('[data-ja-level="n3"]'); const c=n('[data-ja-lesson]')===20; click('[data-ja-lesson="3"]'); const a=n('.zh-gram')===5 && n('.zh-word-hz.ja-word')>=20 && n('.ja-kcard')>=15 && n('.zh-line')===7 && /わけ/.test(body()); click('[data-go="ja_home"]'); click('[data-ja-lesson="14"]'); const b=/弊社/.test(body()) && /申/.test(body()) && /折り返し|折おり返かえし/.test(body()); click('[data-go="ja_home"]'); click('[data-ja-lesson="20"]'); const e=/乾杯/.test(body()); click('[data-go="ja_home"]'); click('[data-ja-level="n5"]'); return c && a && b && e; });
  check('N3: token «断る» có mục từ; lemmatize 頼まれた→頼む, 慣れれば→慣れる, 諦めるもんか→諦める', ()=>{ const L=win.__jaDict.lemmatize; return L('断る').length>0 && L('頼まれた').includes('頼む') && L('慣れれば').includes('慣れる') && L('諦める').includes('諦める'); });
  check('Kanji N2: chip N2 → lưới 370 chữ; chi tiết 党 ĐẢNG', ()=>{ click('[data-go="ja_kanji"]'); click('[data-ja-klevel="n2"]'); const first=d.querySelector('.ja-kanji-grid').querySelectorAll('.ja-kcard').length; click('.ja-kcard[data-ja-kanji="党"]'); const info=d.querySelector('.ja-kanji-info').textContent; click('[data-ja-klevel="n5"]'); return first===370 && /ĐẢNG/.test(info) && /政党/.test(info); });
  check('N2: cấp N2 → 20 bài; bài 1 (において) 5 ngữ pháp, ≥ 20 từ, hội thoại 8 dòng; bài 18 có 拝啓/敬具; bài 20 có 架け橋', ()=>{ click('[data-go="ja_home"]'); click('[data-ja-level="n2"]'); const c=n('[data-ja-lesson]')===20; click('[data-ja-lesson="1"]'); const a=n('.zh-gram')===5 && n('.zh-word-hz.ja-word')>=20 && n('.zh-line')===8 && /において/.test(body()); click('[data-go="ja_home"]'); click('[data-ja-lesson="18"]'); const b=/拝啓/.test(body()) && /敬具/.test(body()); click('[data-go="ja_home"]'); click('[data-ja-lesson="20"]'); const e=/架[かけ]*け*橋/.test(body()); click('[data-go="ja_home"]'); click('[data-ja-level="n5"]'); return c && a && b && e; });
  check('lemmatize N2: 賜り→賜る, 得ない→得る, 尽くした→尽くす', ()=>{ const L=win.__jaDict.lemmatize; return L('賜り').length>0 && L('得ない').length>0 && L('尽くした').length>=0; });
  click('[data-go="ja_write"]');
  check('Tập viết: ô viết data-src=jp, chip hiragana 46 + katakana 46 + kanji cấp', ()=> n('#hzBig[data-src="jp"]')===1 && n('.hz-chip.ja')>=92+100 && n('[data-hzw="quiz"]')===1);
  check('chọn kanji 日 để viết → meta NHẬT', ()=>{ click('.hz-chip[data-ja-write="日"]'); return d.querySelector('.zh-write-char').textContent==='日' && /NHẬT/.test(d.querySelector('.zh-write-meta').textContent); });
  click('[data-go="ja_srs"]');
  check('Ôn tập: thẻ + lật + chip cấp', ()=>{ const has=n('.zh-card')===1 && n('[data-ja-prac]')>=2; click('#zhFlip'); return has && n('.zh-card.open')===1; });
  click('[data-go="ja_quiz"]');
  check('Bài tập: chip cấp N5 + N4 + Tất cả; chọn N4 rồi dạng ngữ pháp → câu N4 (〜んです/受身/使役…)', ()=>{ if(n('[data-ja-prac]')<3) return false; click('[data-ja-prac="n4"]'); click('[data-ja-qzmode="grammar"]'); click('[data-ja-qz-start="10"]'); const ok=n('.qz-opt')>=3 && /Ngữ pháp/.test(body()); click('[data-ja-qz-home]'); click('[data-ja-prac="n5"]'); return ok; });
  check('Bài tập: 9 dạng; chạy trọn 10 câu mỗi dạng tới kết quả', ()=>{ if(n('[data-ja-qzmode]')!==9) return false; let ok=true; for(const m of [...d.querySelectorAll('[data-ja-qzmode]')].map(e=>e.dataset.jaQzmode)){ const home=d.querySelector('[data-ja-qz-home]'); if(home) click(home); click(`[data-ja-qzmode="${m}"]`); click('[data-ja-qz-start="10"]'); for(let i=0;i<10;i++){ const ord=d.querySelector('[data-ja-qz-ord]'); if(ord){ const parts=n('[data-ja-qz-ord]'); for(let k=0;k<parts;k++) click(d.querySelector('[data-ja-qz-ord]:not([disabled])')); click('[data-ja-qz-check]'); } else { const o=d.querySelector('.qz-opt'); if(!o){ ok=false; break; } click(o); } const nx=d.querySelector('[data-ja-qz-next]'); if(!nx){ ok=false; break; } click(nx); } if(!/Kết quả/.test(body())){ console.log('  mode',m,'không tới kết quả'); ok=false; } } return ok; });
  click('[data-go="ja_speak"]');
  check('Luyện nói: 16 chủ đề (N5·N4·N3·N2); mở «自己紹介» có từ khoá, câu hỏi, đoạn mẫu có furigana + nghe', ()=>{ const t=n('.ru-topic')===16 && n('.ru-topic-lv')===16; click('[data-ja-topic="jikoshoukai"]'); return t && n('.ru-key')>=5 && n('.ru-qs li')>=4 && n('.ru-para')>=4 && n('.ru-para ruby')>=5 && n('.ru-para [data-ja-speak]')>=4; });
  click('[data-go="ja_exam"]');
  check('Thi thử JLPT: giới thiệu + 1 đề đầy đủ + kiểm tra nhanh, không «undefined»', ()=> /JLPT là gì/.test(body()) && n('[data-hsk-start]:not([data-hsk-start="quick"])')===4 && n('[data-hsk-start="quick"]')===4 && !/undefined/.test(body()) && /80\/180/.test(body()));
  click('[data-hsk-start="jlpt-n5-a"]');
  check('đề N5: 67 câu, 3 phần, 90:00, nhãn «問1～7», đáp án 1/2/3/4, câu sắp xếp ★, đoạn văn', ()=> n('.hsk-q')===67 && n('.hsk-tab')===3 && d.getElementById('hskTimer').textContent==='90:00' && /問1～7/.test(body()) && d.querySelector('#hskQ1 .tk-onum').textContent==='1' && n('[data-hsk-ord]')>=4 && n('.hsk-part-p')>=3);
  check('nghe câu 44: giọng ja-JP, bỏ nhãn 男：女：', ()=>{ spoken.length=0; click('[data-hsk-play="44"]'); return spoken.length===1 && spoken[0][0]==='ja-JP' && !/男|女/.test(spoken[0][1]) && /かさ/.test(spoken[0][1]); });
  check('trả lời + nộp → kết quả 3 phần, ngưỡng từng phần, chưa đạt', ()=>{ click('[data-hsk-ans="1"][data-opt="0"]'); click('[data-hsk-submit]'); return n('.hsk-sec')===3 && /mỗi phần ≥ 32%/.test(body()) && /chưa đạt/.test(body()); });
  click('[data-hsk-home]');
  click('[data-hsk-start="quick"][data-hsk-level="n5"]');
  check('đề nhanh N5: 20 câu, chữ cái 1', ()=> n('.hsk-q')===20 && d.querySelector('.tk-onum').textContent==='1');
  click('[data-hsk-exit]');
  click('[data-hsk-start="jlpt-n4-a"]');
  check('đề N4: 85 câu (28·29·28), 115:00, 3 phần, câu sắp xếp, đoạn văn riêng từng câu (もんだい4), nghe 28 câu', ()=> n('.hsk-q')===85 && n('.hsk-tab')===3 && d.getElementById('hskTimer').textContent==='115:00' && /問1～7/.test(body()) && /問58～65/.test(body()) && n('[data-hsk-ord]')>=4 && n('#hskQ50 .tk-passage')===1 && n('[data-hsk-play]')===28);
  check('nghe câu 73 (発話表現): giọng ja-JP, 3 phương án; câu 78 (即時応答) 3 phương án', ()=>{ spoken.length=0; click('[data-hsk-play="73"]'); return spoken.length===1 && spoken[0][0]==='ja-JP' && /引っ越し/.test(spoken[0][1]) && n('#hskQ73 .tk-opt')===3 && n('#hskQ78 .tk-opt')===3 && n('#hskQ1 .tk-opt')===4; });
  check('nộp đề N4 → kết quả 3 phần, ngưỡng 32%', ()=>{ click('[data-hsk-ans="1"][data-opt="0"]'); click('[data-hsk-submit]'); return n('.hsk-sec')===3 && /mỗi phần ≥ 32%/.test(body()); });
  click('[data-hsk-home]');
  click('[data-hsk-start="quick"][data-hsk-level="n4"]');
  check('đề nhanh N4: 20 câu', ()=> n('.hsk-q')===20);
  click('[data-hsk-exit]');
  click('[data-hsk-start="jlpt-n3-a"]');
  check('đề N3: 102 câu (58·16·28), 140:00, 3 phần 言語知識/読解/聴解, 問1～8, sắp xếp 5, đoạn dài, nghe 28', ()=> n('.hsk-q')===102 && n('.hsk-tab')===3 && d.getElementById('hskTimer').textContent==='140:00' && /読解/.test(d.querySelectorAll('.hsk-tab')[1].textContent) && /問1～8/.test(body()) && n('[data-hsk-ord]')>=5 && n('#hskQ69 .tk-passage, .hsk-part-p')>=5 && n('[data-hsk-play]')===28);
  check('nghe câu 87 (概要理解): giọng ja-JP, độc thoại; câu 73 đáp án A/B/C/D', ()=>{ spoken.length=0; click('[data-hsk-play="87"]'); return spoken.length===1 && spoken[0][0]==='ja-JP' && /勤務/.test(spoken[0][1]) && !/男：/.test(spoken[0][1]) && d.querySelector('#hskQ73 .tk-opts').textContent.replace(/\s/g,'').indexOf('1A2B3C4D')>=0; });
  check('nộp đề N3 → kết quả 3 phần, ngưỡng 32%', ()=>{ click('[data-hsk-ans="1"][data-opt="0"]'); click('[data-hsk-submit]'); return n('.hsk-sec')===3 && /mỗi phần ≥ 32%/.test(body()); });
  click('[data-hsk-home]');
  click('[data-hsk-start="quick"][data-hsk-level="n3"]');
  check('đề nhanh N3: 20 câu', ()=> n('.hsk-q')===20);
  click('[data-hsk-exit]');
  click('[data-hsk-start="jlpt-n2-a"]');
  check('đề N2: 104 câu (51·21·32), 155:00, 3 phần, sắp xếp 5, đoạn dài + so sánh A/B, nghe 32', ()=> n('.hsk-q')===104 && n('.hsk-tab')===3 && d.getElementById('hskTimer').textContent==='155:00' && /読解/.test(d.querySelectorAll('.hsk-tab')[1].textContent) && n('[data-hsk-ord]')>=5 && n('.hsk-part-p')>=5 && n('[data-hsk-play]')===32);
  check('nghe câu 101 (統合理解): giọng ja-JP, hội thoại dài', ()=>{ spoken.length=0; click('[data-hsk-play="101"]'); return spoken.length===1 && spoken[0][0]==='ja-JP' && /ベトナム/.test(spoken[0][1]) && spoken[0][1].length>100; });
  check('nộp đề N2 → kết quả 3 phần, ngưỡng 32%', ()=>{ click('[data-hsk-ans="1"][data-opt="0"]'); click('[data-hsk-submit]'); return n('.hsk-sec')===3 && /mỗi phần ≥ 32%/.test(body()); });
  click('[data-hsk-home]');
  click('[data-hsk-start="quick"][data-hsk-level="n2"]');
  check('đề nhanh N2: 20 câu', ()=> n('.hsk-q')===20);
  click('[data-hsk-exit]');
  check('Tra nhanh: gõ kana khi ở Nhật → từ điển Nhật; gõ kanji khi ở Nhật → kho Nhật; gõ Hangul → Hàn', ()=>{ click('[data-go="ja_home"]'); let tq=d.getElementById('topq'); tq.value='がくせい'; tq.dispatchEvent(new win.Event('input',{bubbles:true})); const a=!!d.getElementById('jaq') && n('#jaEntry')===1; click('[data-go="ja_home"]'); tq=d.getElementById('topq'); tq.value='学生'; tq.dispatchEvent(new win.Event('input',{bubbles:true})); const b=!!d.getElementById('jaq'); tq=d.getElementById('topq'); tq.value='학교'; tq.dispatchEvent(new win.Event('input',{bubbles:true})); const c=!!d.getElementById('dq'); return a&&b&&c; });
  check('nhân vật: không có Хиен/Hiển, có クアン + ハノイ', ()=>{ const s=fs.readFileSync(dir+'/js/course-ja.js','utf8')+fs.readFileSync(dir+'/js/speak-ja.js','utf8'); return !/Hiển|ヒエン|ハイフォン/.test(s) && /クアン/.test(s) && /ハノイ/.test(s); });
  click('[data-go="home"]');
  check('về tiếng Hàn: data-lang=ko', ()=> d.documentElement.getAttribute('data-lang')==='ko');
  if (errors.length) console.log('ERRORS:', errors.slice(0,5).join(' | '));
  console.log('\n'+pass+' đạt / '+fail+' lỗi'); process.exit(fail?1:0);
})();
