const { JSDOM, VirtualConsole } = require('jsdom');
const fs = require('fs');
const dir = '/sessions/serene-blissful-faraday/mnt/N1.NGOAI NGU/langlab';
const html = fs.readFileSync(dir + '/dist/langlab.html', 'utf8');
const errors = [], spoken = [];
const vc = new VirtualConsole();
vc.on('jsdomError', e => { if (!/Not implemented/.test(e.message)) errors.push('jsdomError: ' + e.message); });
vc.on('error', (...a) => errors.push('console.error: ' + a.join(' ')));
const dom = new JSDOM(html, { runScripts:'dangerously', pretendToBeVisual:true, virtualConsole:vc, url:'http://localhost:9999/', beforeParse(window){
  window.Element.prototype.getTotalLength = () => 60; window.Element.prototype.getPointAtLength = () => ({x:20,y:20});
  Object.defineProperty(window.Element.prototype,'transform',{get(){return{baseVal:{consolidate(){return null;}}};},configurable:true});
  window.Element.prototype.getBBox = () => ({x:0,y:0,width:100,height:100});
  window.Element.prototype.getBoundingClientRect = () => ({left:0,top:0,width:300,height:300,right:300,bottom:300});
  window.Element.prototype.scrollIntoView = function(){};
  window.HTMLCanvasElement.prototype.getContext = () => new Proxy({}, {get:()=>()=>{}});
  window.scrollTo=()=>{}; window.confirm=()=>true;
  window.matchMedia=()=>({matches:false,addEventListener(){},removeEventListener(){},addListener(){},removeListener(){}});
  window.fetch=()=>Promise.reject(new Error('no server'));
  window.speechSynthesis={speaking:false,cancel(){},resume(){},pause(){},getVoices(){return[{lang:'ru-RU',name:'Russian'},{lang:'zh-CN',name:'Chinese'}];},addEventListener(){},removeEventListener(){},speak(u){ spoken.push([u.lang,u.text]); }};
  window.SpeechSynthesisUtterance=function(t){this.text=t;};
}});
const win=dom.window,d=win.document;
const click=s=>{const el=typeof s==='string'?d.querySelector(s):s; if(!el) throw new Error('không thấy '+s); el.dispatchEvent(new win.MouseEvent('click',{bubbles:true}));};
const n=s=>d.querySelectorAll(s).length, body=()=>d.getElementById('view').textContent;
let pass=0,fail=0; const check=(name,fn)=>{ try{ const r=fn(); if(r===false) throw new Error('sai'); pass++; console.log('ok   '+name);}catch(e){ fail++; console.log('FAIL '+name+' — '+e.message);} };
(async()=>{
  await new Promise(r=>setTimeout(r,120));
  if (errors.length) console.log('BOOT ERRORS:', errors.slice(0,4).join(' | '));
  check('boot không lỗi', ()=>errors.length===0);
  check('menu Tiếng Nga: 10 mục (có «Bạn có biết?») + badge', ()=> n('#ruDrop')===1 && n('.nav-menu[aria-label="Tiếng Nga"] .nav-mi')===10 && n('.nav-menu[aria-label="Tiếng Nga"] [data-go="facts"]')===1 && /A1/.test(d.querySelector('[data-go="ru_home"] .mi-count').textContent));
  click('[data-go="ru_home"]');
  check('Khoá học Nga: data-lang=ru, 4 thẻ nền tảng, chip cấp, 15 bài A1', ()=> d.documentElement.getAttribute('data-lang')==='ru' && n('.zh-found-card')===4 && n('.level-chip[data-ru-level]')===6 && n('[data-ru-lesson]')===15 && d.getElementById('crumb').textContent.includes('Tiếng Nga'));
  check('B1 & B2: mỗi cấp 15 bài; B1 bài 2 có причастие, B2 bài 10 có thành ngữ', ()=>{ click('.level-chip[data-ru-level="b1"]'); const b1=n('[data-ru-lesson]')===15; click('[data-ru-lesson="2"]'); const p=body().includes('сидя́щий'); click('[data-go="ru_home"]'); click('.level-chip[data-ru-level="b2"]'); const b2=n('[data-ru-lesson]')===15; click('[data-ru-lesson="10"]'); const f=body().includes('баклу́ши'); click('[data-go="ru_home"]'); click('.level-chip[data-ru-level="a1"]'); return b1&&p&&b2&&f; });
  check('badge menu A1–C2', ()=> d.querySelector('[data-go="ru_home"] .mi-count').textContent==='A1–C2');
  check('C1 & C2: mỗi cấp 15 bài; C1 bài 2 có паро́ним, C2 bài 1 có эвфеми́зм, C2 bài 3 có tục ngữ', ()=>{ click('.level-chip[data-ru-level="c1"]'); const c1=n('[data-ru-lesson]')===15; click('[data-ru-lesson="2"]'); const p=body().includes('паро́ним'); click('[data-go="ru_home"]'); click('.level-chip[data-ru-level="c2"]'); const c2=n('[data-ru-lesson]')===15; click('[data-ru-lesson="1"]'); const e=body().includes('эвфеми́зм'); click('[data-go="ru_home"]'); click('.level-chip[data-ru-level="c2"]'); click('[data-ru-lesson="3"]'); const pr=body().includes('Семь раз отме́рь'); click('[data-go="ru_home"]'); click('.level-chip[data-ru-level="a1"]'); return c1&&p&&c2&&e&&pr; });
  check('Bài tập: ngân hàng ngữ pháp có C1 + C2 (≥ 35 câu mỗi cấp)', ()=> (()=>{ const R=win.eval('RU_EXERCISES'); return R.filter(x=>x.level==='c1').length>=35 && R.filter(x=>x.level==='c2').length>=35; })());
  check('A2: chuyển cấp hiện 15 bài, bài 10 có tiền tố chuyển động', ()=>{ click('.level-chip[data-ru-level="a2"]'); const ok=n('[data-ru-lesson]')===15; click('[data-ru-lesson="10"]'); const cr=d.getElementById('crumb').textContent.includes('A2') && body().includes('перешёл'); click('[data-go="ru_home"]'); click('.level-chip[data-ru-level="a1"]'); return ok && cr; });
  check('theme-color đổi sang xanh Nga', ()=> d.querySelector('meta[name="theme-color"]').getAttribute('content')==='#E6ECF6');
  click('[data-go="ru_alphabet"]');
  check('Bảng chữ cái: 33 chữ, chi tiết chữ А, nút nghe', ()=> n('.ru-letter')===33 && body().includes('tên chữ «а»') && n('#ruDetail [data-ru-speak]')>=1);
  click('[data-ru-letter="Ж"]');
  check('bấm Ж → chi tiết đổi, viết tay', ()=> body().includes('tên chữ «жэ»') && d.querySelector('.ru-letter[data-ru-letter="Ж"]').classList.contains('on') && n('#ruDetail .ru-hw')===1);
  click('#ruDetail [data-ru-speak]');
  check('nghe: giọng ru-RU, bỏ dấu trọng âm', ()=> spoken.length===1 && spoken[0][0]==='ru-RU' && !/́/.test(spoken[0][1]));
  click('[data-go="ru_phonetics"]');
  check('Phát âm: 8 quy tắc + ví dụ', ()=> n('.ru-phon-card')===8 && n('.ru-phon-card .ru-ex')>=20);
  click('[data-go="ru_write"]');
  await new Promise(r=>setTimeout(r,40));
  check('Tập viết: canvas + 3 dạng chữ + 33 chip, chữ hiện tại Ж', ()=> !!d.getElementById('ruTrace') && n('.ru-write-forms > span')===3 && n('.ru-chip')===33 && d.getElementById('ruTrace').dataset.letter==='Жж');
  click('[data-ru-write-letter="Д"]');
  check('đổi chữ Д trong tập viết', ()=> d.querySelector('.ru-chip.on').textContent==='Д' && body().includes('д thảo'));
  click('[data-go="ru_home"]'); click('[data-ru-lesson="6"]');
  check('bài 6: tiêu đề, 2 ngữ pháp, 15 từ có trọng âm, hội thoại, crumb A1 › Bài 06', ()=> body().includes('Где вы живёте') && n('.zh-gram')===2 && n('.zh-word')===15 && n('.zh-line')>=4 && Array.from(d.querySelectorAll('.zh-word-hz')).some(e=>/́/.test(e.textContent)) && d.getElementById('crumb').textContent.includes('Bài 06'));
  check('từ trong hội thoại bấm được → từ điển (từ "живёшь" → tìm không dấu)', ()=>{ const w=d.querySelector('.zh-line [data-ruw="живёшь"]') || d.querySelectorAll('.zh-line [data-ruw]')[3]; click(w); return !!d.getElementById('ruq'); });
  check('từ điển: gõ "семья" không dấu ra kết quả có nhãn bài', ()=>{ const q=d.getElementById('ruq'); q.value='семья'; q.dispatchEvent(new win.Event('input',{bubbles:true})); return n('#ruResults .zh-res')>=1 && n('#ruResults .zh-ref[data-ru-open]')>=1; });
  check('gõ nghĩa tiếng Việt "gia đình" cũng ra', ()=>{ const q=d.getElementById('ruq'); q.value='gia đình'; q.dispatchEvent(new win.Event('input',{bubbles:true})); return n('#ruResults .zh-res')>=1; });
  click('#ruResults .zh-ref[data-ru-open]');
  check('nhãn bài mở đúng bài 2', ()=> d.getElementById('crumb').textContent.includes('Bài 02'));
  check('Từ bấm được: gạch chấm (.ru-tok) + dòng gợi ý trong bài', ()=> n('.ru-click-hint')===1 && n('.zc.ru-tok')>=10 && n('.zh-word-hz.ru-word[title]')===15);
  check('bấm «зову́т» trong hội thoại → mục từ «звать»: nghĩa, bảng chia, quá khứ, mệnh lệnh, ví dụ', ()=>{ click('[data-go="ru_home"]'); click('.level-chip[data-ru-level="a1"]'); click('[data-ru-lesson="1"]'); const w=[...d.querySelectorAll('.zh-line [data-ruw]')].find(e=>/зову/i.test(e.dataset.ruw)); click(w); const en=d.getElementById('ruEntry'); return !!en && /звать/.test(en.querySelector('.ru-entry-word').textContent) && n('#ruEntry .ru-senses li')>=2 && n('#ruEntry .ru-tbl-verb')===1 && /зову́/.test(en.textContent) && /Quá khứ/.test(en.textContent) && /Mệnh lệnh/.test(en.textContent) && n('#ruEntry .ru-ex-item')>=1; });
  check('gõ dạng biến đổi «книги» → gợi ý từ gốc; mở mục «книга»: bảng 6 cách × 2 số, cấu tạo từ', ()=>{ const q=d.getElementById('ruq'); q.value='книги'; q.dispatchEvent(new win.Event('input',{bubbles:true})); const note=/dạng biến đổi của/.test((d.querySelector('#ruResults .ru-lemma-note')||{textContent:''}).textContent); click('#ruResults .zh-res'); const en=d.getElementById('ruEntry'); const t=en&&en.querySelector('.ru-tbl'); return note && !!t && n('#ruEntry .ru-tbl tbody tr')===6 && /кни́ги/.test(t.textContent) && /кни́гами/.test(t.textContent) && /giống cái/.test(en.textContent) && n('#ruEntry .ru-seg-row .ru-seg')>=2; });
  check('mục từ tính từ «новый»: bảng 4 cột, dạng ngắn, so sánh hơn; đại từ «я»: bảng cách', ()=>{ click('[data-ru-entry-close]'); let q=d.getElementById('ruq'); q.value='новый'; q.dispatchEvent(new win.Event('input',{bubbles:true})); click('#ruResults .zh-res'); const a=d.getElementById('ruEntry'); const okA=!!a && n('#ruEntry .ru-tbl thead th')===5 && /Dạng ngắn/.test(a.textContent) && /нове́е/.test(a.textContent); click('[data-ru-entry-close]'); q=d.getElementById('ruq'); q.value='я'; q.dispatchEvent(new win.Event('input',{bubbles:true})); click('#ruResults .zh-res'); const p=d.getElementById('ruEntry'); const okP=!!p && /меня́/.test(p.textContent) && /мне/.test(p.textContent); click('[data-ru-entry-close]'); return okA && okP; });
  check('mục từ có nghĩa 1/2/3 + cách dùng (kết hợp từ) từ kho soạn tay: «день»', ()=>{ const q=d.getElementById('ruq'); q.value='день'; q.dispatchEvent(new win.Event('input',{bubbles:true})); click('#ruResults .zh-res'); const en=d.getElementById('ruEntry'); const ok=!!en && n('#ruEntry .ru-senses li')>=2 && n('#ruEntry .ru-coll li')>=4 && /дня/.test(en.textContent) && /днём/.test(en.textContent); click('[data-ru-entry-close]'); return ok; });
  click('[data-go="ru_srs"]');
  check('Ôn tập: thẻ + lật + chip cấp', ()=>{ const has=n('.zh-card')===1 && n('[data-ru-prac]')>=2; click('#zhFlip'); return has && n('.zh-card.open')===1; });
  click('[data-go="ru_quiz"]'); click('[data-ru-qzmode="vocab"]'); click('[data-ru-qz-start="10"]');
  check('Bài tập: 2–4 lựa chọn, chấm, giải thích + nghe', ()=>{ const ok=n('.qz-opt')>=2 && n('.qz-opt')<=4; click('.qz-opt'); return ok && n('.qz-explain')===1 && n('[data-ru-qz-next]')===1 && n('.qz-explain [data-ru-speak]')===1; });
  check('Bài tập trọng âm: chế độ riêng ra câu "trọng âm đúng"', ()=>{ click('[data-ru-qz-home]'); click('[data-ru-qzmode="stress"]'); click('[data-ru-qz-start="10"]'); return body().includes('trọng âm đúng'); });
  check('Bài tập: 9 dạng, mỗi dạng chạy trọn 10 câu tới kết quả (kể cả sắp xếp câu)', ()=>{ click('[data-ru-qz-home]'); if(n('[data-ru-qzmode]')!==9) return false; let ok=true;
    for(const mode of ['vocab','stress','cloze','grammar','order','trans','listen','dialog','mix']){ click(`[data-ru-qzmode="${mode}"]`); click('[data-ru-qz-start="10"]');
      for(let i=0;i<10;i++){ if(d.querySelector('[data-ru-qz-ord]')){ const parts=n('[data-ru-qz-ord]'); for(let k=0;k<parts;k++) click(d.querySelector('[data-ru-qz-ord]:not([disabled])')); click('[data-ru-qz-check]'); } else { const o=d.querySelector('.qz-opt'); if(!o){ ok=false; break; } click(o); } if(!d.querySelector('.qz-explain')){ ok=false; break; } click('[data-ru-qz-next]'); }
      if(!body().includes('Kết quả')) ok=false; click('[data-ru-qz-home]'); }
    return ok; });
  check('Bài tập sắp xếp: có nút Kiểm tra, xoá, chấm và hiện đáp án', ()=>{ click('[data-ru-qzmode="order"]'); click('[data-ru-qz-start="10"]'); const parts=n('[data-ru-qz-ord]'); click(d.querySelector('[data-ru-qz-ord]')); const cleared = n('[data-ru-qz-clear]')===1; click('[data-ru-qz-clear]'); for(let k=0;k<parts;k++) click(d.querySelector('[data-ru-qz-ord]:not([disabled])')); click('[data-ru-qz-check]'); const ex=d.querySelector('.qz-explain'); return cleared && !!ex && n('[data-ru-qz-next]')===1 && (ex.classList.contains('ok') || ex.textContent.includes('Đáp án')); });
  click('[data-go="ru_speak"]');
  check('Luyện nói: 12 chủ đề', ()=> n('.ru-topic')===12);
  click('[data-ru-topic="workday"]');
  check('chủ đề rabочий день: từ khoá, câu hỏi, đoạn có dịch + nghe', ()=> n('.ru-key')>=8 && n('.ru-qs li')>=4 && n('.ru-para')>=4 && n('.ru-para .ru-para-vi')>=4 && n('.ru-para [data-ru-speak]')>=4);
  click('[data-go="ru_exam"]');
  check('Thi thử ТРКИ: giới thiệu + 6 đề đầy đủ (A1–C2) + kiểm tra nhanh, không có «undefined»', ()=> body().includes('ТРКИ là gì') && n('[data-hsk-start]:not([data-hsk-start="quick"])')===6 && n('[data-hsk-start="quick"]')===6 && body().includes('66%') && !body().includes('undefined') && body().includes('ТРКИ-4'));
  check('đề ТРКИ-1 B1: 217 câu, 4 phần, 205 phút, nhãn «задания», đoạn điền từ có (151)', ()=>{ click('[data-hsk-start="trki-b1-a"]'); const ok = n('.hsk-q')===217 && n('.hsk-tab')===4 && d.getElementById('hskTimer').textContent==='205:00' && body().includes('задания 1–20') && !body().includes('题') && body().includes('(151)'); click('[data-hsk-exit]'); return ok; });
  check('đề ТРКИ-2 B2: 203 câu; ТРКИ-3 C1: 153 câu; ТРКИ-4 C2: 153 câu, 265 phút', ()=>{ click('[data-hsk-start="trki-b2-a"]'); const b2=n('.hsk-q')===203; click('[data-hsk-exit]'); click('[data-hsk-start="trki-c1-a"]'); const c1=n('.hsk-q')===153; click('[data-hsk-exit]'); click('[data-hsk-start="trki-c2-a"]'); const c2=n('.hsk-q')===153 && d.getElementById('hskTimer').textContent==='265:00'; click('[data-hsk-exit]'); return b2&&c1&&c2; });
  check('C2: nghe câu 126 phát giọng ru-RU, bỏ nhãn người nói; nộp bài chấm 4 phần', ()=>{ click('[data-hsk-start="trki-c2-a"]'); spoken.length=0; click('[data-hsk-play="134"]'); const sp = spoken.length===1 && spoken[0][0]==='ru-RU' && !/Ведущая:|Волков:/.test(spoken[0][1]) && /реформа орфографии/.test(spoken[0][1]); click('[data-hsk-ans="1"][data-opt="1"]'); click('[data-hsk-submit]'); const res = n('.hsk-sec')===4 && body().includes('mỗi phần ≥ 66%'); click('[data-hsk-home]'); return sp && res; });
  click('[data-hsk-start="trki-a1-a"]');
  check('đề ТЭУ A1: 132 câu, 4 phần, đồng hồ 150:00, nghe 2 lần, chữ cái А/Б/В', ()=> n('.hsk-q')===132 && n('.hsk-tab')===4 && d.getElementById('hskTimer').textContent==='150:00' && d.querySelector('[data-hsk-play="116"] small').textContent.includes('2') && d.querySelector('#hskQ1 .tk-onum').textContent==='А' && n('textarea[data-hsk-in]')===2);
  check('nghe câu 116: giọng ru-RU, bỏ gạch đầu dòng', ()=>{ spoken.length=0; click('[data-hsk-play="116"]'); return spoken.length===1 && spoken[0][0]==='ru-RU' && !/—/.test(spoken[0][1]); });
  check('bài viết: đếm theo TỪ; đủ 40 từ + 4 cụm → đúng', ()=>{ const ta=d.querySelector('[data-hsk-in="131"]'); ta.value='Меня зовут Куан. Мне 23 года. Я из Вьетнама, из города Ханой. Сейчас я живу в Москве. Я учусь в академии на третьем курсе. У меня есть родители, младший брат и младшая сестра. Я люблю футбол и музыку. Я изучаю русский язык, потому что хочу работать в России.'; ta.dispatchEvent(new win.Event('input',{bubbles:true})); return /\d+ từ/.test(d.getElementById('hskCnt131').textContent); });
  click('[data-hsk-ans="1"][data-opt="0"]'); click('[data-hsk-submit]');
  check('kết quả ТРКИ: 4 phần, ngưỡng "mỗi phần ≥ 66%", câu 131 đúng, chưa đạt', ()=> n('.hsk-sec')===4 && body().includes('mỗi phần ≥ 66%') && d.getElementById('hskQ131').classList.contains('ok') && body().includes('chưa đạt'));
  click('[data-hsk-home]');
  check('đề ТБУ A2: 152 câu', ()=>{ click('[data-hsk-start="trki-a2-a"]'); const ok = n('.hsk-q')===152 && n('.hsk-part-p')===3; click('[data-hsk-exit]'); return ok; });
  click('[data-hsk-start="quick"][data-hsk-level="a1"]');
  check('đề nhanh tiếng Nga: 20 câu, chữ cái А/Б/В/Г', ()=> n('.hsk-q')===20 && d.querySelector('.tk-onum').textContent==='А');
  click('[data-hsk-ans="1"][data-opt="0"]'); click('[data-hsk-submit]');
  check('nộp → kết quả', ()=> body().includes('/100 điểm'));
  check('Tra nhanh: gõ Cyrillic → từ điển Nga; gợi ý kho khác', ()=>{ click('[data-go="ru_home"]'); const tq=d.getElementById('topq'); tq.value='семья'; tq.dispatchEvent(new win.Event('input',{bubbles:true})); return d.getElementById('ruq') && d.getElementById('ruq').value==='семья' && n('#ruResults .zh-res')>=1; });
  check('Tra nhanh: gõ nghĩa Việt "gia đình" khi đang ở Nga → kho Nga, có nút chuyển sang Hàn/Trung', ()=>{ const tq=d.getElementById('topq'); tq.value='gia đình'; tq.dispatchEvent(new win.Event('input',{bubbles:true})); return n('#ruResults .zh-res')>=1 && n('#ruResults .dict-cross [data-cross]')>=1; });
  check('bấm nút chuyển → từ điển Trung với cùng từ khoá', ()=>{ click('#ruResults .dict-cross [data-cross="zh_dict"]'); return d.getElementById('zhq') && d.getElementById('zhq').value==='gia đình' && n('#zhResults .zh-res')>=1 && d.documentElement.getAttribute('data-lang')==='zh'; });
  check('Tra nhanh: gõ chữ Hán khi đang ở Nga → sang từ điển Trung', ()=>{ click('[data-go="ru_home"]'); const tq=d.getElementById('topq'); tq.value='学'; tq.dispatchEvent(new win.Event('input',{bubbles:true})); return !!d.getElementById('zhq') && n('#zhResults .zh-res')>=1; });
  check('Tra nhanh: gõ Hangul → từ điển Hàn', ()=>{ const tq=d.getElementById('topq'); tq.value='학교'; tq.dispatchEvent(new win.Event('input',{bubbles:true})); return !!d.getElementById('dq') && d.documentElement.getAttribute('data-lang')==='ko'; });
  const tqTxt = ()=> (d.querySelector('#tqPh .tq-ph-in')||{textContent:''}).textContent + ' ' + (d.getElementById('topq').getAttribute('aria-label')||'');
  check('gợi ý ô tra nhanh đổi theo ngôn ngữ', ()=>{ click('[data-go="ru_home"]'); const a=/Nga/.test(tqTxt()); click('[data-go="zh_home"]'); const b=/Trung/.test(tqTxt()); return a&&b; });
  check('nhân vật: không còn Хиен/Хайфон, có Куан + Ханой', ()=>{ click('[data-go="ru_speak"]'); const back=d.querySelector('[data-ru-topic=""]'); if(back) click(back); click('[data-ru-topic="city"]'); const t=body(); return !/Хиен|Хайфон/.test(t) && /Куан|Ханой/.test(t); });
  click('[data-go="home"]');
  check('về tiếng Hàn: data-lang=ko', ()=> d.documentElement.getAttribute('data-lang')==='ko');
  console.log('\n'+pass+' đạt / '+fail+' lỗi'); process.exit(fail?1:0);
})();
